const {PGlite}=require(process.env.ATLAS_PGLITE || '@electric-sql/pglite');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;
create table atlas_user_profiles(user_id uuid,role text,status text,allowed_community_ids uuid[],locked_tab_ids text[],locked_page_keys text[]);
create table atlas_communities(community_id uuid primary key,display_name text,canonical_name text,status text,deleted_at timestamptz);
create table atlas_community_aliases(community_id uuid,alias text,active boolean);
create function atlas_can_access_community(id uuid) returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from atlas_user_profiles where user_id=auth.uid() and status='active' and (role in ('admin','centra','executive') or id=any(allowed_community_ids))) $$;
insert into auth.users values ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');
insert into atlas_communities values ('10000000-0000-0000-0000-000000000001','Test A','test a','active',null),('10000000-0000-0000-0000-000000000002','Test B','test b','inactive',null);
insert into atlas_user_profiles values ('00000000-0000-0000-0000-000000000001','admin','active','{}','{}','{}'),('00000000-0000-0000-0000-000000000002','centra','active','{}','{}','{}'),('00000000-0000-0000-0000-000000000003','manager','active','{10000000-0000-0000-0000-000000000002}','{}','{}');`);
await db.exec(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/application-publication.sql','utf8'));
const signIn=async n=>db.exec(`reset role; set request.jwt.claim.sub='00000000-0000-0000-0000-${String(n).padStart(12,'0')}'; set role authenticated;`);
const upload={validationStatus:'valid',sourceAsOf:'2026-09-16',reportPeriodKey:'2026-09',fileName:'synthetic.xlsx',records:[{applicationId:'1',propertySource:'Test A',mappingStatus:'mapped',residentName:'Synthetic',communityId:'TEST_A',atlasName:'Test A',sourceRowNumber:2}]};
const publish=async u=>(await db.query('select atlas_publish_application_import($1::jsonb) as result',[JSON.stringify(u)])).rows[0].result.imports;
await signIn(1); const first=await publish(upload); assert.equal(first.length,1); assert.equal(first[0].records[0].communityId,'10000000-0000-0000-0000-000000000001'); const id=first[0].import_id;
assert.equal((await publish({...upload,batchId:'different',uploadedAt:'later'}))[0].import_id,id);
assert.equal((await db.query('select count(*)::int n from atlas_application_import_versions')).rows[0].n,1);
await assert.rejects(()=>publish({...upload,records:[...upload.records,{...upload.records[0]}]}),/Duplicate/);
await assert.rejects(()=>publish({...upload,sourceAsOf:''}),/source-effective/);
await assert.rejects(()=>publish({...upload,records:[{...upload.records[0],propertySource:'Unknown'}]}),/mapping/);
await signIn(2); assert.equal((await db.query('select count(*)::int n from atlas_application_imports')).rows[0].n,1);
await assert.rejects(()=>publish({...upload,records:[...upload.records,{...upload.records[0],applicationId:'2',propertySource:'Test B'}]}),/denied/);
assert.equal((await db.query('select count(*)::int n from atlas_application_imports')).rows[0].n,1,'Mixed-scope import rolls back');
await db.query("select atlas_revise_application_import($1,1,'delete','test')",[id]);
assert.ok((await publish(upload))[0].deleted_at,'Replay does not restore deletion');
await assert.rejects(()=>db.query("select atlas_revise_application_import($1,1,'restore','stale')",[id]),/another session/);
await db.query("select atlas_revise_application_import($1,2,'restore','explicit restore')",[id]);
assert.equal((await db.query('select count(*)::int n from atlas_application_import_versions')).rows[0].n,3);
await assert.rejects(()=>db.query('update atlas_application_imports set version=99'),/permission denied/);
await signIn(3); assert.equal((await db.query('select count(*)::int n from atlas_application_imports')).rows[0].n,0);
await assert.rejects(()=>db.query("select atlas_revise_application_import($1,3,'delete','unauthorized')",[id]),/denied/);
await db.exec('reset role; set role anon'); await assert.rejects(()=>publish(upload),/permission denied/);
await signIn(1);
await publish({...upload,records:[{...upload.records[0],propertySource:'Test B',atlasName:'Forged A',communityId:'wrong'}]});
await signIn(3);
const scoped=(await db.query('select records from atlas_application_imports')).rows;
assert.equal(scoped.length,1,'Explicit inactive assignment permits its own community');
assert.equal(scoped[0].records[0].atlasName,'Test B','Server overrides forged display and scope identity');
await assert.rejects(()=>publish({...upload,records:[{...upload.records[0],propertySource:'Test B'}]}),/denied/,'Read assignment does not grant publication');
await db.exec(`reset role; update atlas_user_profiles set locked_tab_ids='{7}',locked_page_keys='{application_performance}' where role='centra'`);
await signIn(2);
assert.equal((await db.query('select count(*)::int n from atlas_application_imports')).rows[0].n,0,'Module read lock enforced');
await assert.rejects(()=>publish(upload),/denied/,'Data Import lock enforced');
await db.exec(`reset role; update atlas_user_profiles set status='disabled',locked_tab_ids='{}',locked_page_keys='{}' where role='centra'`);
await signIn(2); assert.equal((await db.query('select count(*)::int n from atlas_application_imports')).rows[0].n,0);
await assert.rejects(()=>publish(upload),/denied/);
await signIn(1);
const bulk=await publish({...upload,records:Array.from({length:1578},(_,i)=>({...upload.records[0],applicationId:'bulk-'+i}))});
assert.equal(bulk[0].records.length,1578,'Portfolio-sized source publishes atomically');
assert.equal((await publish({...upload,records:Array.from({length:1578},(_,i)=>({...upload.records[0],applicationId:'bulk-'+i}))}))[0].import_id,bulk[0].import_id,'Large replay retains identity');
console.log('PASS: real Postgres engine; idempotency, source validation, atomic scope failure, RLS, disabled user, anonymous denial, version conflict, tombstone replay, restore and audit.');
await db.close();
})().catch(e=>{console.error(e);process.exitCode=1});
