const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const B=require('../docs/portfolio-operations-dashboard/application-source-bridge.js');
const root=__dirname+'/../docs/portfolio-operations-dashboard/';
const html=fs.readFileSync(root+'index.html','utf8');
const context={console,Date,Map,Set,XLSX:require(process.env.ATLAS_XLSX || 'xlsx'),window:{},DEFAULT_CURRENT_MONTH:8,MONTHS:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],applicationResidentDataState:{reportMonthIdx:8,reportYear:2026},savedData:{},PROPERTIES:[]};
context.FULL_MONTHS=context.MONTHS; vm.createContext(context);
for(const match of html.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm)){try{vm.runInContext(match[0],context);}catch{}}
vm.runInContext(html.slice(html.indexOf('const APPLICATION_RESIDENT_DATA_SHEET_NAME'),html.indexOf('function normalizeApplicationResidentDateInput')),context);
context.getKnownAtlasCommunityName=()=>'';context.matchPropertyName=()=>'';context.getAllCommunityNames=()=>[];
const fixture=process.env.ATLAS_RESIDENT_FIXTURE;
if(fixture){
 const book=context.XLSX.read(fs.readFileSync(fixture),{type:"buffer",cellDates:true});
 const upload=context.parseApplicationResidentDataWorkbook(book,{name:'RISE - Resident Data (5).xlsx'},{reportMonthIdx:8,reportYear:2026});
 assert.equal(upload.records.length,1578,'All property sheets parsed');
 const scope=[...new Set(upload.records.map(r=>r.atlasName).filter(Boolean))];
 const data=B.project([upload],scope);
 assert(data.records.length>1000);assert(data.imports.length===1);
 assert.equal(B.project([upload,JSON.parse(JSON.stringify(upload))],scope).records.length,data.records.length,'Duplicate upload is idempotent');
 assert.equal(B.project([upload],[]).records.length,0,'Empty permission scope fails closed');
 assert(!data.records.some(r=>r.moveIn),'Scheduled move-in does not prove possession');
 console.log('PASS real Resident Data: 1,578 rows across property tabs; mapped projection, duplicate import and empty scope.');
}
const box=process.env.ATLAS_BOX_FIXTURE;
if(box){
 const book=context.XLSX.read(fs.readFileSync(box),{type:"buffer"});const rows=context.XLSX.utils.sheet_to_json(book.Sheets['RISE Sereno'],{header:1,defval:'',raw:true});
 const parsed=B.boxScore(rows);const values=Object.assign({},...parsed.map(r=>r.values));
 assert.equal(values.applications,7);assert.equal(values.approvals,5);assert.equal(values.new_leads,76);assert.equal(values.tours,26);
 assert.equal(values.total_units-values.available_units,241);assert.equal(values.source_leased_units,265);assert.equal(values.occupied_units,258);
 assert.equal(values.available_units,values.vacant_units+values.notice_unrented-values.vacant_rented);
 assert.equal(values.occupied_units/values.total_units*100,80.625);
 console.log('PASS real Sereno Box Score: 7 applications, 5 approvals, 76 leads, 26 tours; 258 physical, 265 source leased, 241 exposure adjusted.');
}
const r={applicationId:'same',communityId:'A',atlasName:'A',mappingStatus:'mapped',residentName:'Test',applicationStatus:'Application: Started',newLeadCreatedOn:'2026-09-01'};
const up=(id,asOf,records)=>({batchId:id,sourceAsOf:asOf,uploadedAt:asOf,validationStatus:'valid',records});
const older=up('old','2026-08-01',[{...r,applicationStatus:'Application: Completed'}]),latest=up('new','2026-09-16',[r]);
assert.equal(B.project([latest,older],['A']).records[0].applicationStatus,r.applicationStatus);
assert.equal(B.project([latest,up('conflict','2026-09-16',[{...r,applicationStatus:'Application: Denied'}])],['A']).records.length,0);
assert.equal(B.project([latest,up('other','2026-09-16',[{...r,communityId:'B',atlasName:'B'}])],['A','B']).records.length,2);
assert.equal(B.filter([{...r,property:'A',newLeadCreatedOn:'2025-09-02'}],{date:'mtd'},new Date('2026-09-16')).length,0);
const merged=B.merge({uploads:[latest]},{uploads:[older]});assert.equal(merged.uploads.length,2);
assert.equal(B.merge({uploads:[{...latest,deletedAt:'2026-09-17',validationStatus:'deleted'}]},{uploads:[latest]}).uploads[0].validationStatus,'deleted');
console.log('PASS backfill precedence, conflicting snapshots, community-scoped identity, prior-year filter, additive merge and deletion tombstones.');
if(box){
 const book=context.XLSX.read(fs.readFileSync(box),{type:'buffer'}), raw=context.XLSX.utils.sheet_to_json(book.Sheets['RISE Sereno'],{header:1,defval:'',raw:true});
 const entries=B.boxScore(raw).map(sourceRow=>({sourceRow:{...sourceRow,sourceSheet:'RISE Sereno'},row:sourceRow.values}));
 const month={},lineage=[];
 Object.assign(context,{dataImportShouldApplyCurrentMetric:()=>true,normalizeSavedCommunityRecord:(name,r)=>r||{},dataImportPercentValue:v=>v==null?null:Number(v),dataImportUpsertFloorPlan:()=>{},getWritableMonthlyPeriodEntries:()=>({historyEntry:month}),dataImportApplyMetric:(record,plan,result,name,period,target,value,field)=>{if(value===null||value===undefined)return false;assert(context.applyValueToRecord(record,period.monthIdx,target,value,period.year));lineage.push({currentState:true,reportType:'box_score',communityName:name,periodKey:period.periodKey,atlasField:field,importedValue:value,sourceFile:plan.name});return true;}});
 context.dataImportApplyGroupedSnapshot({communityName:'Sereno',period:{periodKey:'2026-09',year:2026,monthIdx:8},entries},{reportType:'box_score',name:'Fixture.xlsx'},{issues:[],formulas:[],destinations:new Set()});
 assert.equal(month.applications,7);assert.equal(month.applicationsApproved,5);assert.equal(month.tours,26);assert.equal(month.leasedSnapshot,241);assert.equal(month.sourceLeasedUnits,265);assert.equal(month.exposureUnits,79);assert.equal(month.leasedOccupancyPct,82.8125);
 Object.assign(context,{dataImport2State:{lineage},getAtlasApplicationScopeCommunityNames:()=>['Sereno'],isAtlasCommunityActiveByName:()=>true});
 const metrics=context.getAtlasApplicationPeriodMetrics('2026-09');assert.equal(metrics[0].cells.applications.value,7);assert.equal(context.getAtlasApplicationPeriodMetrics('2025-09')[0].cells.applications.value,null);
 context.dataImportApplyGroupedSnapshot({communityName:'Sereno',period:{periodKey:'2026-09',year:2026,monthIdx:8},entries:[{row:{application_id:'test',application_status:'Started'}}]},{reportType:'leasing_resident_data'},{issues:[],formulas:[],destinations:new Set()});assert.equal(month.applications,7,'Resident snapshots must never replace completed period flows');

 const occupiedBefore=month.occupiedSnapshot;
 context.normalizeSavedCommunityRecord=()=>({communityPropertyType:'Student Housing'});
 context.dataImportApplyGroupedSnapshot({communityName:'Student',period:{periodKey:'2026-09',year:2026,monthIdx:8},entries},{reportType:'box_score',name:'Fixture.xlsx'},{issues:[],formulas:[],destinations:new Set()});
 assert.equal(month.occupiedSnapshot,occupiedBefore,'Unit-based source does not overwrite student bed counts');
 context.dataImportShouldApplyCurrentMetric=()=>false;
 month.exposureUnits=99;
 context.normalizeSavedCommunityRecord=()=>({});
 context.dataImportApplyGroupedSnapshot({communityName:'Sereno',period:{periodKey:'2026-09',year:2026,monthIdx:8},entries},{reportType:'box_score',name:'Fixture.xlsx'},{issues:[],formulas:[],destinations:new Set()});
 assert.equal(month.exposureUnits,99,'Rejected older source cannot replace derived occupancy fields');
 const applicationSource=entries.find(entry=>entry.row.applications!==undefined).sourceRow;
 context.dataImportDestinationExists=field=>field==='applications';
 const mapped=context.dataImportMapSourceRow(applicationSource,{reportType:'box_score'});
 assert.equal(mapped.mapped.applications,7);
 assert(mapped.sourceFields.applications.includes('RISE Sereno / lead conversions'));
 assert(mapped.sourceFields.applications.includes('/ application /'));
 assert(/Completed/i.test(mapped.sourceFields.applications));
 const ignored=context.dataImportMapSourceRow(applicationSource,{reportType:'box_score',questionAnswers:[{kind:'mapping',originalField:'applications',value:'__ignore_import__'}]});
 assert.equal(ignored.mapped.applications,undefined,'Approved ignore remains honored');
 const ambiguous=context.dataImportMapSourceRow(applicationSource,{reportType:'box_score',questionAnswers:[{kind:'mapping',originalField:'Completed',value:'applications'}]});
 assert.equal(ambiguous.mapped.applications,undefined,'Ambiguous repeated headers are held for qualified review');
 context.defaultMonthly=()=>Array.from({length:12},()=>({}));
 const normalized=context.normalizeMonthlyHistoryByPeriod({'2026-09':{sourceTotalUnits:320,sourceLeasedUnits:265,exposureAdjustedOccupancyPct:75.3125}});
 assert.equal(normalized['2026-09'].sourceLeasedUnits,265,'Actual history normalizer retains separate source metrics');
 console.log('PASS source → grouped publication → monthly fields → period widget; detail import cannot overwrite flow counts.');
}
for(const name of ['application-source-bridge.js','application-performance.js','application-performance-ui.js'])new vm.Script(fs.readFileSync(root+name,'utf8'));
console.log('PASS script syntax.');
const deleted={...latest,deletedAt:'2026-09-17T12:00:00Z',validationStatus:'deleted'};
const restored={...latest,restoredAt:'2026-09-18T12:00:00Z'};
assert.equal(B.merge({uploads:[deleted]},{uploads:[restored]}).uploads[0].validationStatus,'valid');
const hydrated=JSON.parse(JSON.stringify(B.merge({uploads:[latest]},{uploads:[older]})));
assert.equal(B.project(hydrated.uploads,['A']).records[0].applicationStatus,r.applicationStatus);
console.log('PASS serialized hydration and explicit restore after deletion (simulated storage, not authenticated multi-user verification).');
const eventHandlers={},capturedBooks=[];
const synthetic=B.project([up('ui','2026-09-16T12:00:00Z',[{...r,residentName:'Synthetic applicant',leasingAgent:'Test agent',sourceSheetName:'A',sourceRowNumber:4}])],['A']);
const uiContext={console,Date,Map,Set,localStorage:{getItem:()=>null},document:{createElement:()=>({innerHTML:'',content:{querySelectorAll:()=>[]}})},alert:()=>{}};
uiContext.window={AtlasApplicationSources:B,getAtlasCanonicalApplicationData:()=>synthetic,getAtlasApplicationScopeCommunityNames:()=>['A'],isAtlasCommunityActiveByName:()=>true,getAtlasApplicationPeriodMetrics:()=>[],getApplicationResidentReportPeriodKey:()=> '2026-09',renderTab:()=>{},addEventListener:(event,fn)=>eventHandlers[event]=fn,XLSX:{utils:context.XLSX.utils,writeFile:book=>capturedBooks.push(book)}};
vm.createContext(uiContext);
for(const name of ['application-performance.js','application-performance-ui.js'])vm.runInContext(fs.readFileSync(root+name,'utf8'),uiContext);
eventHandlers.load();
const rendered=uiContext.window.renderApplicationPerformanceTab();
assert(rendered.includes('Applicant snapshots'));
assert(rendered.includes('Lease lifecycle source required'));
assert(!rendered.includes('Verified lifecycle'));
assert(!rendered.includes('from prior stage'));
uiContext.window.atlasApplicationExport();
assert.equal(context.XLSX.utils.sheet_to_json(capturedBooks[0].Sheets['Applicant Snapshots']).length,1);
uiContext.window.atlasApplicationCommandFilter('search','no match');
assert.equal(uiContext.window.getAtlasApplicationCommandRecords().length,0);
uiContext.window.atlasApplicationExport();assert.equal(capturedBooks.length,1,'No different unfiltered export on empty view');
console.log('PASS actual UI renderer and XLSX export share filtered rows; unsupported lifecycle and conversion rates remain unavailable.');
