const {readDashboardSource}=require('./dashboard-source.cjs');
const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const html=readDashboardSource(__dirname+'/../docs/portfolio-operations-dashboard/index.html');
const c={console,Date,Map,Set,Number,AbortController,window:{dispatchEvent(){}},Event:class Event{},applicationResidentDataState:{uploads:[]},csvError:'',renderTab(){},normalizeApplicationResidentUpload:x=>x,getApplicationResidentCommunityIdForAtlasName:()=> 'LOCAL_A'};
vm.createContext(c);
c.scheduleAtlasSharedRender = () => c.renderTab();
vm.runInContext('let atlasApplicationHydrationEpoch=0; let atlasApplicationSessionUser=null;',c);
for (const name of ['atlasApplicationPublicationEnabled','applicationUploadFromCentral','clearAtlasSharedApplications','hydrateAtlasSharedApplications','reviseAtlasSharedApplication']) {
 const match=[...html.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm)].find(m=>m[0].startsWith('function '+name+'(')||m[0].startsWith('async function '+name+'('));
 vm.runInContext(match[0],c);
}
const row={import_id:'id1',community_id:'uuid-a',version:1,source_metadata:{fileName:'synthetic.xlsx',sourceAsOf:'2026-09-16',reportPeriodKey:'2026-09'},records:[{applicationId:'a',atlasName:'Test A',communityId:'uuid-a',propertySource:'Test A'}],created_at:'2026-09-17T00:00:00Z',deleted_at:null};
let user='one',response=[row],trackingSharedCount=null;
c.window.refreshAtlasApplicationTrackingEvidence=()=>{trackingSharedCount=c.applicationResidentDataState.uploads.filter(u=>u.centralImportId).length;};
c.window.ATLAS_CENTRAL={getConfig:()=>({applicationPublication:true}),getSession:()=>user?{user:{id:user}}:null,readApplicationImports:async()=>response,reviseApplicationImport:async(id,version,action)=>{assert.equal(version,1);return {...row,version:2,deleted_at:'2026-09-17T01:00:00Z'}}};
(async()=>{
 c.applicationResidentDataState.uploads=[{batchId:'legacy'},{centralImportId:'stale'}];
 await c.hydrateAtlasSharedApplications();
 assert.equal(c.applicationResidentDataState.uploads.length,2);
 assert.equal(trackingSharedCount,1,"Tracking header refreshes after shared evidence arrives");
 const shared=c.applicationResidentDataState.uploads[0];
 assert.equal(shared.records[0].communityId,'LOCAL_A');
 assert.equal(shared.records[0].canonicalCommunityId,'uuid-a');
 assert.equal(shared.centralVersion,1);
 await c.reviseAtlasSharedApplication(shared,'delete','test');
 assert.equal(c.applicationResidentDataState.uploads[0].validationStatus,'deleted');
 assert.equal(c.applicationResidentDataState.lastDeletedUpload.centralVersion,2);
 let resolve; c.window.ATLAS_CENTRAL.readApplicationImports=()=>new Promise(r=>resolve=r);
 const pending=c.hydrateAtlasSharedApplications(); user='two'; c.clearAtlasSharedApplications(); resolve([row]); await pending;
 assert.equal(c.applicationResidentDataState.uploads.length,1,'Previous user response cannot repopulate session');
 c.window.ATLAS_CENTRAL.readApplicationImports=async()=>{throw new Error('denied')};
 c.applicationResidentDataState.uploads.push(shared); await c.hydrateAtlasSharedApplications();
 assert.equal(c.applicationResidentDataState.uploads.length,1,'Failed read clears stale shared records');
 assert.match(c.csvError,/denied/);
 assert.equal(trackingSharedCount,0,'Tracking header clears stale evidence after read failure');
 user=null; await c.hydrateAtlasSharedApplications();
 assert.equal(c.applicationResidentDataState.lastDeletedUpload,null);
 user='three';let navigation='home',access='admin',reads=0,normalizations=0,requestSignal;
 c.getAtlasRenderContextKey=()=>JSON.stringify([user,access,navigation]);
 c.window.ATLAS_CENTRAL.getAccessContextKey=()=>JSON.stringify([user,access]);
 c.normalizeApplicationResidentUpload=value=>{normalizations++;return value;};
 c.window.ATLAS_CENTRAL.readApplicationImports=async()=>{reads++;return [row];};
 await c.hydrateAtlasSharedApplications();await c.hydrateAtlasSharedApplications();
 assert.equal(normalizations,1,'Unchanged versions do not clone or normalize the payload again');
 let finish;c.window.ATLAS_CENTRAL.readApplicationImports=({signal})=>{reads++;requestSignal=signal;return new Promise(resolve=>finish=resolve);};
 const beforeReads=reads,a=c.hydrateAtlasSharedApplications(),b=c.hydrateAtlasSharedApplications();
 assert.equal(reads,beforeReads+1,'Repeated hydration in one navigation shares a single read');
 navigation='reports';
 const cancellation=html.match(/^  if \(typeof hydrateAtlasSharedApplications === "function".*$/m)?.[0];assert(cancellation,'Root render cancels a prior navigation read');vm.runInContext(cancellation,c);
 assert.equal(requestSignal.aborted,true);finish([{...row,version:7}]);await Promise.all([a,b]);
 assert.equal(c.applicationResidentDataState.uploads[0].centralVersion,1,'Cancelled navigation cannot install a late payload');
 const oldAccess=c.hydrateAtlasSharedApplications();access='regional';finish([{...row,version:8}]);await oldAccess;
 assert.equal(c.applicationResidentDataState.uploads[0].centralVersion,1,'Same-user access changes reject stale payloads');
 const parent=new AbortController(),external=c.hydrateAtlasSharedApplications({signal:parent.signal});parent.abort();assert.equal(requestSignal.aborted,true);finish([{...row,version:9}]);await external;
 assert.equal(c.applicationResidentDataState.uploads[0].centralVersion,1);
 const firstSignal=new AbortController(),secondSignal=new AbortController(),first=c.hydrateAtlasSharedApplications({signal:firstSignal.signal}),second=c.hydrateAtlasSharedApplications({signal:secondSignal.signal});
 secondSignal.abort();assert.equal(await second,false);assert.equal(requestSignal.aborted,false,'Cancelling a joining caller leaves the original subscriber active');
 firstSignal.abort();assert.equal(await first,false);assert.equal(requestSignal.aborted,true,'Last subscriber cancellation stops the shared hydration');finish([{...row,version:10}]);
 const keptSignal=new AbortController(),leaving=c.hydrateAtlasSharedApplications({signal:keptSignal.signal}),remaining=c.hydrateAtlasSharedApplications();keptSignal.abort();await leaving;assert.equal(requestSignal.aborted,false);finish([{...row,version:11}]);await remaining;
 assert.equal(c.applicationResidentDataState.uploads[0].centralVersion,11,'Another active subscriber still receives the verified result');
 console.log('PASS client hydration, canonical identity, server versions, deletion, session/access/navigation races, shared reads, unchanged normalization, cancellation and failed-read clearing.');
})().catch(e=>{console.error(e);process.exitCode=1});
