const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/index.html','utf8');
let profile={role:'centra',status:'active',allowed_community_ids:['active-id'],allowed_market_values:['central'],locked_tab_ids:['0','7','8'],locked_page_keys:['portfolio_home','data_import','reports']};
let selected='Nocatee',portfolio=false,signedIn=true;
const properties={Nocatee:{atlasCommunityId:'nocatee-id',market:'central'},Viera:{atlasCommunityId:'viera-id',market:'central'},Sereno:{atlasCommunityId:'active-id',market:'central'}};
const c={console,Date,Map,Set,window:{},activeTab:16};vm.createContext(c);
for(const match of html.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm))vm.runInContext(match[0],c);
vm.runInContext(html.slice(html.indexOf('const ATLAS_ACCESS_TABS ='),html.indexOf('const ATLAS_ACCESS_ROLES =')),c);
Object.assign(c,{getAtlasAccessProfile:()=>profile,getAtlasCentralStatus:()=>({configured:true,signedIn,role:profile.role}),getAtlasSharedPropertyByName:n=>properties[n],atlasAccessLocationScopeValues:()=>[],atlasNormalizeSharedText:v=>String(v||'').toLowerCase(),atlasCommunityLocationScopeValue:()=>'',isAtlasCommunityActiveByName:n=>n==='Sereno',getProp:()=>({name:selected}),isPortfolioWorkspaceSelected:()=>portfolio,getCommunityNamesByStatusScope:({communityStatusMode})=>communityStatusMode==='active'?['Sereno']:Object.keys(properties)});
assert.equal(c.getAtlasAccessTab(16).key,'application_performance');
assert.equal(c.atlasAccessDecision(16).ok,false,'Inactive requires explicit assignment');
assert.equal(c.atlasRoleDefaultsToAllActiveCommunities('centra'),true);
assert.equal(c.atlasRoleCanSeeInactiveCommunities(profile,'Nocatee'),false,'Market scope cannot grant inactive access');
profile.allowed_community_ids.push('nocatee-id');
assert.equal(c.atlasAccessDecision(16).ok,true,'Application Performance no longer inherits locked Portfolio Home');
assert.equal(c.atlasAccessDecision(7).ok,false,'Existing Data Import lock remains enforced');
assert.equal(c.atlasAccessDecision(8).ok,false,'Existing Reports lock remains enforced');
assert.deepEqual(Array.from(c.getAtlasWorkspaceCommunityOptionNames()).sort(),['Nocatee','Sereno']);
assert.equal(c.atlasApplicationCommunityInScope('Nocatee'),true);
assert.equal(c.atlasApplicationCommunityInScope('Viera'),false,'Another inactive property remains denied');
portfolio=true;assert.equal(c.atlasApplicationCommunityInScope('Nocatee'),false,'Inactive stays outside portfolio rollups');portfolio=false;
profile.locked_tab_ids.push('16');assert.equal(c.atlasAccessDecision(16).ok,false,'Explicit Application Performance lock wins');profile.locked_tab_ids.pop();
signedIn=false;assert.equal(c.atlasDashboardUserCanSeeCommunityName('Sereno'),false,'Missing authentication fails closed');signedIn=true;
profile.status='disabled';assert.equal(c.atlasAccessDecision(16).ok,false);assert.equal(c.atlasRoleCanSeeInactiveCommunities(profile,'Nocatee'),false);
console.log('PASS real access functions: explicit inactive assignment, isolated property review, active-only portfolio, distinct Application Performance permission, unchanged locks, authentication and disabled-account denial.');
profile.status='active';
profile.community_access_records=[{community_id:'nocatee-id',canonical_name:'nocatee',display_name:'Nocatee',status:'inactive',market:'central'}];
c.getAtlasSharedPropertyByName=()=>null;
assert.equal(c.getAtlasCommunityAccessRecord('Nocatee').atlasCommunityId,'nocatee-id');
assert.equal(c.atlasAccessDecision(16).ok,true,'Scoped directory is sufficient without the all-module document');
assert.equal(c.atlasRoleCanSeeInactiveCommunities(profile,'Viera'),false,'Unknown directory entry fails closed');
console.log('PASS directory-backed access without whole-document visibility.');
