const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{createHash}=require('node:crypto'),{execFileSync}=require('node:child_process');
require('fake-indexeddb/auto');
const {IDBObjectStore}=require('fake-indexeddb'),api=require('../docs/portfolio-operations-dashboard/migration-archive.js'),Zip=require('../docs/portfolio-operations-dashboard/vendor/jszip.min.js');
const core=fs.readFileSync(require.resolve('../docs/portfolio-operations-dashboard/workspace-core.js'),'utf8'),fn=(source,name)=>{const m=source.match(new RegExp('^(?:async )?function '+name+'\\([^\\n]*\\) \\{[\\s\\S]*?^\\}','m'));assert(m,name);return m[0];};
const sha=value=>createHash('sha256').update(value).digest('hex'),old=execFileSync('git',['show','origin/atlas-asset-releases:_atlas-assets/774663d5c700ea5d00a0b13a627f965f78173d7a4700f6728ed6a6620adbf8df/portfolio-operations-dashboard/index.html'],{cwd:require('node:path').resolve(__dirname,'..'),encoding:'utf8',maxBuffer:32*1024**2});
const open=()=>new Promise((resolve,reject)=>{const r=indexedDB.open('archive-builder-test-'+crypto.randomUUID(),1);r.onupgradeneeded=()=>r.result.createObjectStore('records',{keyPath:'key'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const storeIO=db=>(mode,action)=>new Promise((resolve,reject)=>{const tx=db.transaction('records',mode);let req;try{req=action(tx.objectStore('records'));}catch(e){tx.abort();reject(e);return;}tx.oncomplete=()=>resolve(req?.result??null);tx.onabort=tx.onerror=()=>reject(tx.error||req?.error||Error('transaction failed'));});
async function context(){const db=await open(),io=storeIO(db),summary={counts:1},bundle={keys:{example:'{"signed":-1.005,"missing":null,"zero":0}'},indexedDb:{communityData:{Example:{value:0}}}};const g={console,JSON,Date,Blob,crypto:globalThis.crypto,JSZip:Zip,DATA_IMPORT_2_STATE_KEY:'imports',DATA_IMPORT_FILE_ARCHIVE_PREFIX:'source:',withAtlasStateStore:io,atlasStateWritePromise:Promise.resolve(),collectAtlasCentralMigrationSnapshot:async()=>({reconciliation:summary,exceptions:[]}),redactAtlasCentralStorageBundle:v=>v,buildDashboardStorageBundle:async()=>bundle,parseAtlasMigrationJson:JSON.parse,buildAtlasMigrationReconciliationSummary:()=>summary,hashAtlasMigrationPayload:async()=> 'source-fingerprint',buildOperationsWorkspaceContext:()=>({}),normalizeAtlasSharedData:x=>x,atlasSharedData:{},AtlasMigrationArchive:api};g.window=g;vm.createContext(g);vm.runInContext(fn(core,'packAtlasCentralRetainedRecords')+'\n'+fn(core,'buildAtlasCentralAppStatePayload'),g);return {db,io,g,bundle};}
async function remove(db){const name=db.name;db.close();await new Promise((resolve,reject)=>{const r=indexedDB.deleteDatabase(name);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
async function archiveFixture(){return api.pack({keys:{zero:0,missing:null}},[{key:'small',value:{missing:null,zero:0}},{key:'last',value:{history:Array.from({length:30},(_,i)=>({i,value:'Ω evidence'.repeat(60),signed:-1.005,zero:0,missing:null})),blob:new Blob(['original'],{type:'text/plain'})}}],Zip,{segmentBytes:512});}
async function corrupt(archive,kind){const zip=await Zip.loadAsync(Buffer.from(archive.data,'base64')),manifest=JSON.parse(await zip.file('manifest.json').async('string')),last=manifest.entries.at(-1);if(kind==='missing')zip.remove(last.segments.at(-1).name);if(kind==='corrupt')zip.file(last.segments.at(-1).name,'invalid');if(kind==='order')manifest.entries.reverse();if(kind==='count')manifest.entries.pop();zip.file('manifest.json',JSON.stringify(manifest));const bytes=await zip.generateAsync({type:'uint8array'});return {...archive,bytes:bytes.length,sha256:sha(bytes),data:Buffer.from(bytes).toString('base64')};}

test('bundle-only verification checks every member and preserves public unpack/Blob data',async()=>{const archive=await archiveFixture(),all=await api.unpack(archive,Zip),verified=await api.verifyBundle(archive,Zip);assert.deepEqual(verified.bundle,all.bundle);assert.deepEqual(verified.manifest,all.manifest);assert.equal(verified.recordsVerified,all.records.length+1);assert.equal(Object.hasOwn(verified,'records'),false);assert.equal(await all.records.at(-1).value.blob.text(),'original');assert.equal(all.records.at(-1).value.history[0].missing,null);assert.equal(all.records.at(-1).value.history[0].zero,0);});
test('bundle-only verification cannot skip corrupt/missing last member or manifest identity',async()=>{const archive=await archiveFixture();for(const kind of ['missing','corrupt','order','count'])await assert.rejects(api.verifyBundle(await corrupt(archive,kind),Zip),/Migration|migration/,kind);await assert.rejects(api.verifyBundle({...archive,sha256:'0'.repeat(64)},Zip),/fingerprint/);await assert.rejects(api.verifyBundle({},Zip),/Unsupported/);});
test('native selected-key snapshot retains every permitted record without cloning unrelated backups',async()=>{const {db,io,g,bundle}=await context(),rows=[{key:'imports',value:{batches:[{id:'one',beforeSnapshot:{capturedAt:'a',source:{zero:0,missing:null}}}]}},{key:'source:a',value:{blob:new Blob(['source bytes'])}},{key:'occupancy_replay_backup:old',value:{untouched:true}},{key:'daily_backup:unrelated',value:{doNotClone:'retained'}},{key:'atlas_replay_receipt_v1:local',value:{status:'committed',localOnly:true}}];await io('readwrite',s=>{for(const row of rows)s.put(row);});const getAll=IDBObjectStore.prototype.getAll,get=IDBObjectStore.prototype.get;const reads=[];IDBObjectStore.prototype.getAll=function(){throw Error('Full getAll is forbidden');};IDBObjectStore.prototype.get=function(key){reads.push(key);return get.call(this,key);};try{const packed=await g.packAtlasCentralRetainedRecords(bundle),restored=await api.unpack(packed,Zip);assert.deepEqual(restored.records.map(r=>r.key),['imports','occupancy_replay_backup:old','source:a']);assert.equal(restored.records[0].value.batches[0].beforeSnapshot.source.missing,null);assert.equal(await restored.records[2].value.blob.text(),'source bytes');assert(!reads.includes('daily_backup:unrelated'));assert(!reads.includes('atlas_replay_receipt_v1:local'),'Local replay receipt is neither cloned nor deleted by portable archive capture');assert.deepEqual((await io('readonly',s=>s.get('atlas_replay_receipt_v1:local'))).value,rows[4].value);assert.deepEqual((await io('readonly',s=>s.get('daily_backup:unrelated'))).value,rows[3].value);}finally{IDBObjectStore.prototype.getAll=getAll;IDBObjectStore.prototype.get=get;await remove(db);}});
test('actual current and retained builders pack in separate frame then verify every member without full unpack',async()=>{const {patchArchiveBuilderBoundary}=await import('./archive-builder-compat.mjs');const patched=patchArchiveBuilderBoundary(old,core);assert.equal(patched.replace(fn(patched,'packAtlasCentralRetainedRecords')+'\n\n','').includes('function packAtlasCentralRetainedRecords('),false);for(const source of [core,patched]){const {db,io,g,bundle}=await context();vm.runInContext(fn(source,'buildAtlasCentralAppStatePayload'),g);await io('readwrite',s=>s.put({key:'imports',value:{batches:[{id:'one',beforeSnapshot:{capturedAt:'a'}}]}}));let packed=false,verified=false;g.AtlasMigrationArchive={...api,packRecords:async(...args)=>{const result=await api.packRecords(...args);packed=true;return result;},unpack:()=>{throw Error('Builder cannot retain all decoded history');},verifyBundle:async(...args)=>{assert(packed);verified=true;return api.verifyBundle(...args);}};const result=await g.buildAtlasCentralAppStatePayload();assert(verified);assert.deepEqual((await api.unpack(result.bundle,Zip)).bundle,bundle);assert.equal(result.reconciliation.counts,1);await remove(db);}});
test('unresolved legacy/projected/split history cannot produce a portable archive',async()=>{for(const value of [{batches:[{id:'one',beforeSnapshotRef:{batchId:'one',capturedAt:'a'}}]},{historyStorage:{view:'current'},batches:[]},{__atlasImportHistory:2,revision:1}]){const {db,io,g,bundle}=await context();await io('readwrite',s=>s.put({key:'imports',value}));await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/complete|Complete|incomplete/);await remove(db);}});
test('verified split export includes snapshots and rejects captured-head changes',async()=>{const {executeHistory}=await import('../docs/portfolio-operations-dashboard/features/import-history-store.mjs');for(const change of [false,true]){const {db,g,bundle,io}=await context();const request={dbName:db.name,storeName:'records',key:'imports'};await executeHistory({...request,operation:'save',value:{batches:[{id:'one',beforeSnapshot:{capturedAt:'a',zero:0,missing:null}}],sourceArchive:[],canonicalRecords:[],lineage:[]}});g.dataImportHistoryOperation=async (operation,extra={})=>{assert.equal(operation,'exportPacked');const value=await executeHistory({...request,operation,...extra});if(change){const row=await io('readonly',s=>s.get('imports'));row.value.revision++;await io('readwrite',s=>s.put(row));}return value;};if(change)await assert.rejects(g.packAtlasCentralRetainedRecords(bundle,{expandImportHistory:true}),/changed/);else{const packed=await g.packAtlasCentralRetainedRecords(bundle,{expandImportHistory:true}),restored=await api.unpack(packed,Zip),b=restored.records[0].value.batches[0];assert.equal(b.beforeSnapshot.missing,null);assert.equal(b.beforeSnapshot.zero,0);assert.equal(Object.hasOwn(b,'beforeSnapshotRef'),false);assert.equal(Object.hasOwn(restored.records[0].value,'__atlasImportHistory'),false);}await remove(db);}});
test('compatibility patch rejects drift and preserves every byte outside its three boundaries',async()=>{const {patchArchiveBuilderBoundary,ARCHIVE_BUILDER_BOUNDARY_COUNT}=await import('./archive-builder-compat.mjs');assert.equal(ARCHIVE_BUILDER_BOUNDARY_COUNT,3);const patched=patchArchiveBuilderBoundary(old,core);const oldBuilder=fn(old,'buildAtlasCentralAppStatePayload'),newBuilder=fn(patched,'buildAtlasCentralAppStatePayload'),helper=fn(patched,'packAtlasCentralRetainedRecords');assert.equal(patched.replace(helper+'\n\n','').replace(newBuilder,oldBuilder),old);assert.throws(()=>patchArchiveBuilderBoundary(old.replace('const retainedRecords = (await','let retainedRecords = (await'),core),/boundary/);assert.throws(()=>patchArchiveBuilderBoundary(patched,core),/boundary/);});

test('unavailable native storage and missing canonical history fail before packing; empty native store remains valid',async()=>{const {db,g,bundle}=await context();let packs=0;g.AtlasMigrationArchive={...api,packRecords:async(...args)=>{packs++;return api.packRecords(...args);}};const actualIO=g.withAtlasStateStore;g.withAtlasStateStore=async()=>null;await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/storage is unavailable/);assert.equal(packs,0);g.withAtlasStateStore=actualIO;g.dataImport2State={batches:[{id:'retained'}]};await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/no retained canonical record/);assert.equal(packs,0);await actualIO('readwrite',s=>s.put({key:'imports',value:null}));await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/no retained canonical record/);assert.equal(packs,0);await actualIO('readwrite',s=>s.delete('imports'));g.dataImport2State={batches:[],sourceArchive:[],canonicalRecords:[],lineage:[]};const packed=await g.packAtlasCentralRetainedRecords(bundle);assert.equal(packed.recordCount,0);assert.equal(packs,1);await remove(db);});

test('archive decoding avoids iterable staging while preserving every binary byte and malformed-source rejection',async()=>{const source=fs.readFileSync(require.resolve('../docs/portfolio-operations-dashboard/migration-archive.js'),'utf8'),buffer=Uint8Array.from({length:65536},(_,i)=>i%256),record={key:'bytes',blob:new Blob([buffer])};const archive=await api.pack({zero:0,missing:null},[record],Zip);assert(!source.includes('Uint8Array.from(raw,c=>c.charCodeAt(0));\n      if(bytes.length!==archive.bytes'),'Whole-archive decode must not use iterable staging');const restored=await api.unpack(archive,Zip);assert.deepEqual(new Uint8Array(await restored.records[0].blob.arrayBuffer()),buffer);await assert.rejects(api.verifyBundle({...archive,data:'not*base64'},Zip),/archive unpack failed/);await assert.rejects(api.verifyBundle({...archive,bytes:archive.bytes+1},Zip),/fingerprint/);});

const tempPrefix='__atlas_archive_capture_v1:';
test('prepared worker members preserve the portable archive and reject tampering before publication',async()=>{
 const value={key:'imports',value:{history:Array.from({length:25},(_,i)=>({i,text:'Ω🧭'.repeat(100),zero:0,missing:null})),blob:new Blob(['exact bytes'])}};
 const prepared=await api.packRecord('record-0.json',value,{segmentBytes:512});
 const build=packed=>api.packRecords({source:true},{count:1,readPackedRecord:()=>packed,readRecord:()=>{throw Error('No expanded cross-thread record');}},Zip);
 const restored=await api.unpack(await build(prepared),Zip);assert.deepEqual(restored.records,[value]);
 for(const kind of ['bytes','name','missing','fingerprint']){
  const bad=structuredClone(prepared);
  if(kind==='bytes')bad.files[0].bytes[0]^=1;
  if(kind==='name')bad.files[0].name='another-source';
  if(kind==='missing')bad.files.pop();
  if(kind==='fingerprint')bad.entry.sha256='changed';
  await assert.rejects(build(bad),/prepared|Prepared/);
 }
});
const smallRows=()=>[{key:'imports',value:{batches:[{id:'one',beforeSnapshot:{capturedAt:'a',zero:0,missing:null}}]}},{key:'source:a',value:{blob:new Blob(['source']),signed:-1.005}},{key:'occupancy_replay_backup:old',value:{neverDiscard:true}}];
const rowsOf=io=>io('readonly',s=>s.getAll());
const seed=async(io,rows=smallRows())=>{await io('readwrite',s=>{for(const row of rows)s.put(row);});return rows;};

test('callback packing preserves every original member fingerprint and reads each next record only after compression',async()=>{
 const bundle={keys:{zero:0,missing:null}},records=[{key:'large',value:Array.from({length:18},(_,i)=>({i,text:'Ω'.repeat(80),zero:0,missing:null}))},{key:'blob',blob:new Blob(['source'])}];
 const before=await api.pack(bundle,records,Zip,{segmentBytes:512}),beforeAll=await api.unpack(before,Zip),events=[];
 const last=beforeAll.manifest.entries[1].segments.at(-1).name;
 function TrackedZip(){const zip=new Zip(),file=zip.file;zip.file=function(name,value){if(value!==undefined)events.push(name);return file.apply(this,arguments);};return zip;}
 const next=await api.packRecords(bundle,{count:records.length,readRecord:async i=>{if(i===1)assert(events.includes(last),'First record must be compressed/stored before reading the next');events.push('read:'+i);return structuredClone(records[i]);}},TrackedZip,{segmentBytes:512});
 const after=await api.unpack(next,Zip);assert.deepEqual(after.manifest,beforeAll.manifest);assert.deepEqual(after.records,beforeAll.records);assert.equal(events.filter(x=>x.startsWith('read:')).length,records.length);
 await assert.rejects(api.packRecords({}, {count:-1,readRecord:()=>null},Zip),/Invalid migration record source/);
 await assert.rejects(api.packRecords({}, {count:1,readRecord:()=>{throw Error('source failed');}},Zip),/source record 0.*source failed/);
});

test('coherent native capture excludes existing temporary orphans, preserves originals and cleans only its inventory',async()=>{
 const {db,io,g,bundle}=await context(),rows=await seed(io),orphan={key:tempPrefix+'older:0',format:'atlas_archive_capture_v1',captureId:'older',sourceKey:'imports',record:{key:'imports',value:{otherCapture:true}}};
 await io('readwrite',s=>s.put(orphan));const archive=await g.packAtlasCentralRetainedRecords(bundle),all=await api.unpack(archive,Zip);assert.equal(all.records.length,rows.length);assert.deepEqual(await rowsOf(io),[orphan,...[...rows].sort((a,b)=>a.key.localeCompare(b.key))]);assert.deepEqual(all.records,[...rows].sort((a,b)=>a.key.localeCompare(b.key)));await remove(db);
});

test('queued edits cannot mix values into the captured native snapshot',async()=>{
 const {db,io,g,bundle}=await context(),before=await seed(io),originalAdd=IDBObjectStore.prototype.add;let queued;
 IDBObjectStore.prototype.add=function(value){if(value?.format==='atlas_archive_capture_v1'&&!queued)queued=io('readwrite',s=>{s.put({key:'imports',value:{batches:[{id:'later'}]}});s.put({key:'source:a',value:{signed:999}});});return originalAdd.apply(this,arguments);};
 g.AtlasMigrationArchive={...api,packRecords:async(...args)=>{await queued;return api.packRecords(...args);}};
 try{const archive=await g.packAtlasCentralRetainedRecords(bundle),all=await api.unpack(archive,Zip);assert.deepEqual(all.records,[...before].sort((a,b)=>a.key.localeCompare(b.key)));assert.equal((await io('readonly',s=>s.get('imports'))).value.batches[0].id,'later');assert.equal((await io('readonly',s=>s.get('source:a'))).value.signed,999);assert(!(await rowsOf(io)).some(r=>r.key.startsWith(tempPrefix)));}finally{IDBObjectStore.prototype.add=originalAdd;await remove(db);}
});

test('quota and capture transaction abort never change original records or leave partial snapshot rows',async()=>{
 for(const kind of ['quota','abort']){const {db,io,g,bundle}=await context(),before=await seed(io),add=IDBObjectStore.prototype.add;let count=0;
  IDBObjectStore.prototype.add=function(value){if(value?.format==='atlas_archive_capture_v1'&&++count===2){if(kind==='quota')throw new DOMException('Archive quota failure','QuotaExceededError');this.transaction.abort();}return add.apply(this,arguments);};
  try{await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/quota|transaction|inactive|abort/i);assert.deepEqual(await rowsOf(io),[...before].sort((a,b)=>a.key.localeCompare(b.key)));}finally{IDBObjectStore.prototype.add=add;await remove(db);}
 }
});

test('missing captured record and source read failure reject and remove only this temporary snapshot',async()=>{
 for(const kind of ['missing','read']){const {db,io,g,bundle}=await context(),before=await seed(io),get=IDBObjectStore.prototype.get;
  g.AtlasMigrationArchive={...api,packRecords:async(...args)=>{if(kind==='missing'){const row=(await rowsOf(io)).find(r=>r.key.startsWith(tempPrefix));await io('readwrite',s=>s.delete(row.key));}else IDBObjectStore.prototype.get=function(key){if(String(key).startsWith(tempPrefix))throw Error('Snapshot read failure');return get.apply(this,arguments);};return api.packRecords(...args);}};
  try{await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/captured archive record|Snapshot read failure/);assert.deepEqual(await rowsOf(io),[...before].sort((a,b)=>a.key.localeCompare(b.key)));}finally{IDBObjectStore.prototype.get=get;await remove(db);}
 }
});

test('cleanup failure is explicit and cannot report a complete archive',async()=>{
 const {db,io,g,bundle}=await context(),before=await seed(io),removeKey=IDBObjectStore.prototype.delete;
 IDBObjectStore.prototype.delete=function(key){if(String(key).startsWith(tempPrefix))throw Error('Cleanup I/O failure');return removeKey.apply(this,arguments);};
 try{await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/cleanup failed; no archive is complete.*Retained capture/);const rows=await rowsOf(io);assert.equal(rows.filter(r=>r.key.startsWith(tempPrefix)).length,before.length);assert.deepEqual(rows.filter(r=>!r.key.startsWith(tempPrefix)),[...before].sort((a,b)=>a.key.localeCompare(b.key)));}finally{IDBObjectStore.prototype.delete=removeKey;await remove(db);}
});

test('account, profile, access, storage and replay changes fail closed while cleaning their original native database',async()=>{
 for(const kind of ['actor','profile','access','storage','replay']){const {db,io,g,bundle}=await context(),before=await seed(io);let actor='one',access='first',profile={role:'Admin',status:'active'};
  g.ATLAS_CENTRAL={getSession:()=>({user:{id:actor}}),getAccessContextKey:()=>access,getStoredProfile:()=>profile};g.ATLAS_STATE_DB_NAME=db.name;
  g.AtlasMigrationArchive={...api,packRecords:async(...args)=>{if(kind==='actor')actor='two';if(kind==='profile')profile={role:'User',status:'active'};if(kind==='access')access='changed';if(kind==='storage')g.ATLAS_STATE_DB_NAME='other';if(kind==='replay')g.AtlasReplayGeneration=1;return api.packRecords(...args);}};
  await assert.rejects(g.packAtlasCentralRetainedRecords(bundle),/account, storage or source replay changed/);assert.deepEqual(await rowsOf(io),[...before].sort((a,b)=>a.key.localeCompare(b.key)));await remove(db);
 }
});

test('periodic access verification timestamp changes preserve an otherwise identical archive identity',async()=>{
 const {db,io,g,bundle}=await context(),before=await seed(io);
 let profile={user_id:'one',role:'Admin',status:'active',access_backend:'same',access_verified_at:'earlier',updated_at:'unchanged'};
 g.ATLAS_CENTRAL={getSession:()=>({user:{id:'one'}}),getAccessContextKey:()=> 'same-access',getStoredProfile:()=>profile};
 g.AtlasMigrationArchive={...api,packRecords:async(...args)=>{profile={...profile,access_verified_at:'later'};return api.packRecords(...args);}};
 try {const archive=await g.packAtlasCentralRetainedRecords(bundle),restored=await api.unpack(archive,Zip);assert.deepEqual(restored.records,[...before].sort((a,b)=>a.key.localeCompare(b.key)));assert.deepEqual(await rowsOf(io),[...before].sort((a,b)=>a.key.localeCompare(b.key)));}finally{await remove(db);}
});

test('current form is flushed before the source snapshot and mismatches fail before history packing',async()=>{const {db,g,bundle}=await context();let flushed=false,packed=false;g.buildDashboardStorageBundle=async()=>{flushed=true;return bundle;};g.collectAtlasCentralMigrationSnapshot=async()=>{assert(flushed,'snapshot must follow the form save');return {reconciliation:{operatingTotals:{leasesSigned:2}},exceptions:[]};};g.buildAtlasMigrationReconciliationSummary=()=>({operatingTotals:{leasesSigned:1}});g.packAtlasCentralRetainedRecords=async()=>{packed=true;throw Error('must not pack');};await assert.rejects(g.buildAtlasCentralAppStatePayload(),/capture reconciliation.*operatingTotals.leasesSigned: source 2, archive 1/);assert.equal(packed,false);await remove(db);});

test('archive round-trip reconciliation still rejects changed totals after a successful capture check',async()=>{const {db,g,bundle}=await context();let checks=0;g.collectAtlasCentralMigrationSnapshot=async()=>({reconciliation:{operatingTotals:{leasesSigned:2}},exceptions:[]});g.buildAtlasMigrationReconciliationSummary=()=>({operatingTotals:{leasesSigned:++checks===1?2:1}});g.packAtlasCentralRetainedRecords=async()=>({});g.AtlasMigrationArchive={verifyBundle:async()=>({bundle})};await assert.rejects(g.buildAtlasCentralAppStatePayload(),/round-trip reconciliation.*operatingTotals.leasesSigned: source 2, archive 1/);assert.equal(checks,2);await remove(db);});
