const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
const root=path.join(__dirname,'../docs/portfolio-operations-dashboard/centralization');
async function setup(){
 const f=await fixture(),{db,A,B,BUDGET,CLOSE}=f;await db.exec('reset role');
 await db.exec(`alter table atlas_user_profiles add column bonus_permissions text[] default '{}';alter table atlas_communities add column community_name text;
 create table atlas_roles(role_id uuid primary key,title text,active boolean default true);
 create table atlas_employees(employee_id uuid primary key,full_name text,status text,version int default 1,updated_at timestamptz,deleted_at timestamptz);
 create table atlas_employee_assignments(assignment_id uuid primary key,employee_id uuid,community_id uuid,role_id uuid,employment_status text,effective_start date,effective_end date,version int default 1,deleted_at timestamptz);
 create table atlas_incentive_plans(incentive_plan_id uuid primary key,role_id uuid,plan_name text,effective_start date,effective_end date,eligibility_rules jsonb,metric_rules jsonb,source_hash text,version int default 1,updated_at timestamptz,deleted_at timestamptz);
 create table atlas_bonus_periods(bonus_period_id uuid primary key default gen_random_uuid(),period_key text unique,year int,quarter text,start_date date,end_date date,status text);
 create table atlas_bonus_calculation_runs(bonus_calculation_run_id uuid primary key,bonus_period_id uuid,community_id uuid,status text,calculation_hash text,source_snapshot_id uuid,calculated_by uuid,inputs jsonb,exceptions jsonb,calculated_at timestamptz default now(),approved_by uuid,approved_at timestamptz,total_payout numeric,deleted_at timestamptz);
 create table atlas_bonus_calculation_lines(bonus_line_id uuid primary key default gen_random_uuid(),bonus_calculation_run_id uuid,employee_id uuid,assignment_id uuid,incentive_plan_id uuid,metric_key text,metric_source_table text,metric_source_id uuid,payout_amount numeric,line_payload jsonb,deleted_at timestamptz);
 create table atlas_command_financial_summaries(community_id uuid,period_key text,summary jsonb,primary key(community_id,period_key));
 grant select,insert,update,delete on all tables in schema public to authenticated;
 `);
 const role=randomUUID(),employee=randomUUID(),assignment=randomUUID();await db.query("insert into atlas_roles values($1,'Synthetic General Manager',true)",[role]);await db.query("insert into atlas_employees(employee_id,full_name,status) values($1,'Synthetic Employee','Active')",[employee]);await db.query("insert into atlas_employee_assignments(assignment_id,employee_id,community_id,role_id,employment_status,effective_start,effective_end) values($1,$2,$3,$4,'Active','2026-01-01','2026-12-31')",[assignment,employee,A,role]);
 await db.query("update atlas_approved_budget_versions set payload=payload||$1::jsonb where version_id=$2",[JSON.stringify({metricMappings:{revenue:[{glCode:'5120',factor:1},{glCode:'5220',factor:1}],expenses:[{glCode:'6100',factor:1},{glCode:'6200',factor:1}],noi:[{glCode:'5120',factor:1},{glCode:'5220',factor:1},{glCode:'6100',factor:-1},{glCode:'6200',factor:-1}],cashFlow:[{glCode:'5120',factor:1},{glCode:'5220',factor:1},{glCode:'6100',factor:-1},{glCode:'6200',factor:-1},{glCode:'8100',factor:-1}]}}),BUDGET]);
 const closes=[CLOSE];for(const month of ['2026-02','2026-03']){const id=randomUUID();closes.push(id);await db.query('insert into atlas_financial_close_versions values($1,$2,$3,$4,now(),$5)',[id,A,month,'close-'+month,'{}']);await db.query("insert into atlas_financial_close_heads values($1,$2,'accrual',$3)",[A,month,id]);}
 for(let i=0;i<3;i++){const month=`2026-0${i+1}`;await db.query('insert into atlas_command_financial_summaries values($1,$2,$3)',[A,month,JSON.stringify({communityId:A,period:month,registryVersion:'atlas-finance-v1',budgetVersion:BUDGET,actualCloseVersion:closes[i],revenue:{actual:997.5,budget:950},expenses:{actual:225,budget:250},noi:{actual:772.5,budget:700},cashFlow:{actual:752.5,budget:680}})]);}
 await db.exec(fs.readFileSync(path.join(root,'reforecast-builder.sql'),'utf8'));
 await db.exec(fs.readFileSync(path.join(root,'bonus-workflow.sql'),'utf8'));
 const call=async(name,args)=>(await db.query(`select ${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args.map(a=>a&&typeof a==='object'&&!Array.isArray(a)?JSON.stringify(a):a))).rows[0].result;
 return {...f,role,employee,assignment,closes,call};
}
async function run(){
 const {db,A,B,role,employee,assignment,closes,call,signIn}=await setup();await signIn(1);
 const workspace=()=>call('atlas_bonus_workspace',[null]);let initial=await workspace();assert.equal(initial.plans.length,0);assert.equal(initial.employees[0].bonusEligible,false);assert.equal(initial.runs.length,0);
 const curve=[{thresholdPct:0,payoutPct:0},{thresholdPct:100,payoutPct:80},{thresholdPct:105,payoutPct:100}];
 const planPayload={name:'Synthetic financial scorecard',roleId:role,effectiveStart:'2026-01-01',effectiveEnd:'2026-12-31',targetBonus:1000,maximumPayout:1000,eligibilityRules:{requireBonusEligible:true,communityIds:[A]},metrics:[{id:'rev',metricKey:'revenue',goal:100,weight:50,thresholdCurve:curve},{id:'cost',metricKey:'expenses',goal:100,weight:50,thresholdCurve:curve}],reason:'Synthetic reviewed plan'};
 const planRequest=randomUUID(),plan=await call('atlas_bonus_plan_save',[null,0,planPayload,planRequest]);assert.equal(plan.version,1);assert.deepEqual(await call('atlas_bonus_plan_save',[null,0,planPayload,planRequest]),plan);await assert.rejects(()=>call('atlas_bonus_plan_save',[null,0,{...planPayload,targetBonus:2000},planRequest]),/different operation/);
 for(const changed of [{...planPayload,targetBonus:null},{...planPayload,metrics:[{...planPayload.metrics[0],metricKey:'occupancy',weight:100}]},{...planPayload,metrics:[{...planPayload.metrics[0],payoutStructure:'salary_percent',weight:100}]}])await assert.rejects(()=>call('atlas_bonus_plan_save',[null,0,changed,randomUUID()]),/finite number|Unsupported/);
 const draftPayload={assignmentId:assignment,planId:plan.id,periodKey:'2026-Q1',reason:'Synthetic canonical calculation'};
 await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,draftPayload,randomUUID()]),/eligibility/);
 const eligible=await call('atlas_bonus_eligibility_save',[employee,1,{bonusEligible:true,bonusEffectiveDate:'2026-01-01',reason:'Explicit synthetic eligibility'},randomUUID()]);assert.equal(eligible.employeeVersion,2);
 await assert.rejects(()=>db.query('update atlas_employees set bonus_eligible=false where employee_id=$1',[employee]),/governed setup/);
 await signIn(3);const request=randomUUID();let result=await call('atlas_bonus_workflow',[null,'draft',0,draftPayload,request]);assert.equal(result.totalPayout,1000);assert.equal(result.calculation.metricResults[0].rawActual,2992.5);assert.equal(result.calculation.metricResults[0].baseline,2850);assert.equal(result.calculation.metricResults[0].variance,142.5);assert.equal(result.calculation.metricResults[0].actual,105);assert.equal(result.calculation.metricResults[1].variance,-75);assert.equal(result.calculation.metricResults[1].actual,110);assert.equal(result.calculation.metricResults[1].earned,500);
 assert.deepEqual(await call('atlas_bonus_workflow',[null,'draft',0,draftPayload,request]),result);
 await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,draftPayload,randomUUID()]),/already exists/);
 await assert.rejects(()=>call('atlas_record_bonus_calculation',['2026-Q1',2026,'Q1','2026-01-01','2026-03-31',{},'locked']),/legacy caller-supplied|permission denied/);
 await assert.rejects(()=>db.query("update atlas_bonus_calculation_runs set status='approved' where bonus_calculation_run_id=$1",[result.runId]),/permission denied/);
 const action=async(name,actor=3,payload={reason:'Synthetic workflow review'})=>{await signIn(actor);result=await call('atlas_bonus_workflow',[result.runId,name,result.revision,payload,randomUUID()]);return result;};
 await action('submit');await signIn(1);await db.exec('reset role');await db.query("update atlas_user_profiles set bonus_permissions='{view_bonus_module,run_calculations,approve_bonuses}' where role='finance'");await signIn(3);await assert.rejects(()=>call('atlas_bonus_workflow',[result.runId,'approve',result.revision,{reason:'Self approval attempt'},randomUUID()]),/different authorized reviewer/);
 await signIn(4);assert.equal((await workspace()).runs.length,0);await assert.rejects(()=>call('atlas_bonus_workflow',[result.runId,'approve',result.revision,{reason:'Outside scope attempt'},randomUUID()]),/access denied/);
 await signIn(2);await assert.rejects(()=>call('atlas_bonus_workflow',[result.runId,'approve',1,{reason:'Stale revision attempt'},randomUUID()]),/revision changed/);
 await action('approve',2);assert.equal(result.status,'approved');let receipts=await call('atlas_read_bonus_receipts',['2026-Q1']);assert.equal(receipts[0].verified,true);
 // A changed close/summary invalidates numeric evidence even when a caller repeats the old total.
 await db.exec('reset role');await db.query("update atlas_command_financial_summaries set summary=jsonb_set(summary,'{expenses,actual}','275') where community_id=$1",[A]);await signIn(1);
 await assert.rejects(()=>call('atlas_bonus_workflow',[result.runId,'lock',result.revision,{reason:'Stale source attempt'},randomUUID()]),/changed; recalculate/);
 assert.equal((await workspace()).runs[0].stale,true);
 await action('recalculate');assert.equal(result.totalPayout,500);assert.equal(result.calculation.metricResults[0].earned,500);assert.equal(result.calculation.metricResults[1].actual,90);assert.equal(result.calculation.metricResults[1].variance,75);assert.equal(result.calculation.metricResults[1].earned,0);
 await action('submit');await action('approve',2);await action('lock',1);assert.equal(result.status,'locked');
 const lockedHash=result.calculationHash;await db.exec('reset role');await db.query("update atlas_command_financial_summaries set summary=jsonb_set(summary,'{expenses,actual}','1') where community_id=$1",[A]);await signIn(1);assert.equal((await workspace()).runs[0].calculationHash,lockedHash);
 await assert.rejects(()=>call('atlas_bonus_workflow',[result.runId,'recalculate',result.revision,{reason:'Change locked history'},randomUUID()]),/Retained/);
 await assert.rejects(()=>call('atlas_bonus_workflow',[result.runId,'record_external_payment',result.revision,{reason:'Wrong payment',externalReference:'TEST-001',paidDate:'2026-04-15',amount:null},randomUUID()]),/finite number/);
 await assert.rejects(()=>call('atlas_bonus_workflow',[result.runId,'record_external_payment',result.revision,{reason:'Wrong payment',externalReference:'TEST-001',paidDate:'2026-04-15',amount:1000},randomUUID()]),/exact approved amount/);
 await action('record_external_payment',1,{reason:'Synthetic external payment receipt',externalReference:'SYNTHETIC-TEST-001',paidDate:'2026-04-15',amount:500});assert.equal(result.status,'paid');assert.equal(result.payment.amount,500);assert.equal((await call('atlas_read_bonus_receipts',['2026-Q1']))[0].period.status,'paid');await db.exec('reset role');assert.equal((await db.query('select status from atlas_bonus_periods')).rows[0].status,'open','per-run payment must not freeze unrelated communities');assert.equal((await db.query('select count(*)::int count from atlas_bonus_calculation_runs')).rows[0].count,1);
 // Immutable plan history and explicit zero targets remain valid setup; no implicit fallback.
 await signIn(1);const zeroPlan=await call('atlas_bonus_plan_save',[plan.id,1,{...planPayload,targetBonus:0,maximumPayout:0},randomUUID()]);assert.equal(zeroPlan.version,2);assert.equal(zeroPlan.targetBonus,0);await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from atlas_private.bonus_plan_versions')).rows[0].n,2);
 await signIn(1);await db.exec("reset role;update atlas_user_profiles set locked_page_keys='{bonus}' where role='admin'");await signIn(1);await assert.rejects(workspace,/access denied/);await db.exec('reset role;set role anon');await assert.rejects(workspace,/permission denied/);
 await db.close();console.log('PASS governed Bonus explicit setup, canonical financial arithmetic, independent approval, idempotency/concurrency, scoped permissions, stale recalculation, locked history and external-only payment recording');
}
if(require.main===module)run().catch(e=>{console.error(e);process.exitCode=1});module.exports={setup};
