// Local browser + in-memory central stub only. No hosted API request is possible.
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),root=path.resolve(import.meta.dirname,'..');
const server=http.createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/'){res.setHeader('content-type','text/html');res.end('<!doctype html><div id="host"></div><script type="module">window.bonusModule=await import("/docs/portfolio-operations-dashboard/features/bonus-workflow.mjs");window.ready=true;</script>');return;}if(!/^\/docs\/portfolio-operations-dashboard\/features\/bonus-workflow(?:-client)?\.mjs$/.test(pathname)){res.writeHead(404);res.end();return;}res.setHeader('content-type','text/javascript');res.end(await fs.readFile(path.join(root,pathname)));}catch{res.writeHead(500);res.end();}});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true}),page=await browser.newPage(),errors=[],requests=[];page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push(request.url()));
const id=n=>'10000000-0000-4000-8000-'+String(n).padStart(12,'0'),community=id(1),community2=id(2),planId=id(3),roleId=id(4),assignmentId=id(5),employeeId=id(6),runId=id(7),lockedId=id(8),paidId=id(9),approvedId=id(10);
const plan={id:planId,version:4,name:'Canonical plan',roleId,effectiveStart:'2026-01-01',effectiveEnd:'2026-12-31',targetBonus:200,maximumPayout:250,eligibilityRules:{requireBonusEligible:true,communityIds:[community,community2]},metrics:[{id:'kept_noi_id',name:'NOI contract measure',metricKey:'noi',goal:110,weight:60,thresholdCurve:[{thresholdPct:0,payoutPct:0},{thresholdPct:90,payoutPct:40},{thresholdPct:100,payoutPct:80}]},{id:'kept_revenue_id',name:'Revenue',metricKey:'revenue',goal:100,weight:40,thresholdCurve:[{thresholdPct:0,payoutPct:0},{thresholdPct:80,payoutPct:20},{thresholdPct:90,payoutPct:40},{thresholdPct:100,payoutPct:80},{thresholdPct:105,payoutPct:100}]}]};
const baseRun={calculationHash:'a'.repeat(64),communityId:community,assignmentId,employeeId,planId,period:{periodKey:'2026-Q1',start:'2026-01-01',end:'2026-03-31'},totalPayout:80,calculation:{metricResults:[{metric:{name:'NOI'},rawActual:4550,actual:100,ratio:100,earned:80}],salary:987654321,secret:'DO-NOT-RENDER-SECRET'},events:[{action:'approved',createdAt:'2026-09-24',reason:'<img src=x onerror="window.injected=true">'}]};
const fixture={permissions:{editPlans:true,editEligibility:true,calculate:true,approve:true,lock:true,recordPayment:true},communities:[{id:community,name:'Synthetic A'},{id:community2,name:'Synthetic B'}],roles:[{id:roleId,title:'Manager'}],plans:[plan],employees:[{employeeId,assignmentId,employeeVersion:3,assignmentVersion:2,name:'<img src=x onerror="window.injected=true"> Employee',communityId:community,roleId,bonusEligible:true,eligibilityEditable:true,bonusEffectiveDate:'2026-01-01'}],runs:[{...baseRun,runId,revision:2,status:'review',stale:true,reason:'Actual close changed'},{...baseRun,runId:lockedId,revision:4,status:'locked'},{...baseRun,runId:paidId,revision:5,status:'paid',payment:{externalReference:'PAYROLL-SYNTHETIC-1',paidDate:'2026-09-24',amount:80}},{...baseRun,runId:approvedId,revision:3,status:'approved'}]};
const idle=()=>page.waitForFunction(()=>document.querySelector('#host').getAttribute('aria-busy')==='false');
const form=type=>page.locator('[data-form="'+type+'"]');
const openSetup=async()=>{const summary=page.getByText('Plan and eligibility setup',{exact:true});if(!await summary.locator('..').evaluate(el=>el.open))await summary.click();};
const getCalls=()=>page.evaluate(()=>window.calls);
try{
 await page.goto(origin);await page.waitForFunction(()=>window.ready);await page.evaluate(async fixture=>{window.fixture=structuredClone(fixture);window.calls=[];window.failWrite=false;window.failRead=false;window.breakReadAfterWrite=false;window.actor='synthetic-admin';window.central={getSession:()=>({user:{id:window.actor}}),async fetchJson(url,options){const body=JSON.parse(options.body);window.calls.push({url,body});if(url.endsWith('/atlas_bonus_workspace')){if(window.failRead)throw Error('Synthetic workspace read failed');return structuredClone(window.fixture);}if(window.failWrite){window.failWrite=false;throw Error('Synthetic uncertain write after send');}if(window.breakReadAfterWrite){window.breakReadAfterWrite=false;window.failRead=true;}if(url.endsWith('/atlas_bonus_plan_save')){const next={...body.p_payload,id:body.p_plan_id||crypto.randomUUID(),version:body.p_expected_version+1};window.fixture.plans=window.fixture.plans.filter(row=>row.id!==next.id).concat(next);return structuredClone(next);}if(url.endsWith('/atlas_bonus_eligibility_save')){const employee=window.fixture.employees.find(row=>row.employeeId===body.p_employee_id);Object.assign(employee,body.p_payload,{employeeVersion:body.p_expected_version+1});return {employeeId:employee.employeeId,employeeVersion:employee.employeeVersion,bonusEligible:employee.bonusEligible,bonusEffectiveDate:employee.bonusEffectiveDate};}const run=window.fixture.runs.find(row=>row.runId===body.p_run_id);if(run){run.revision++;if(body.p_action==='approve')run.status='approved';if(body.p_action==='lock')run.status='locked';if(body.p_action==='record_external_payment'){run.status='paid';run.payment=body.p_payload;}return structuredClone(run);}const created={calculationHash:'c'.repeat(64),runId:crypto.randomUUID(),revision:1,status:'draft',assignmentId:body.p_payload.assignmentId,planId:body.p_payload.planId,period:{periodKey:body.p_payload.periodKey},totalPayout:80,calculation:{},events:[]};window.fixture.runs.push(created);return structuredClone(created);}};await window.bonusModule.mountBonusWorkflow(document.querySelector('#host'),{central:window.central,periodKey:'2026-Q1'});},fixture);await idle();
 assert.equal(await page.locator('#host img,#host script').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);assert(!await page.locator('#host').innerText().then(text=>/987654321|DO-NOT-RENDER-SECRET/.test(text)));assert.match(await page.locator('#host').innerText(),/\$4,550\.00/);assert.match(await page.locator('#host').innerText(),/100\.00%/);assert.match(await page.locator('#host').innerText(),/Actual close changed/);assert.match(await page.locator('#host').innerText(),/Payment confirmed/);assert.match(await page.locator('#host').innerText(),/PAYROLL-SYNTHETIC-1/);
 await openSetup();await form('plan').locator('[name=planId]').selectOption(planId);assert.equal(await form('plan').locator('[name=name]').inputValue(),'Canonical plan');assert.equal(await form('plan').locator('[name=targetBonus]').inputValue(),'200');assert.equal(await form('plan').locator('[name=goal_noi]').inputValue(),'110');assert.deepEqual(await form('plan').locator('[name=communityIds]').evaluate(el=>[...el.selectedOptions].map(o=>o.value)),[community,community2]);assert.equal(await form('plan').locator('[name=replaceCurve]').isChecked(),false);await form('plan').locator('[name=name]').fill('Reviewed revised plan');await form('plan').locator('[name=reason]').fill('Retain exact existing metric IDs and curves');await form('plan').locator('[name=confirm]').check();await page.evaluate(()=>window.failWrite=true);await form('plan').locator('button').click();await idle();assert.match(await page.locator('[role=alert]').allTextContents().then(a=>a.join(' ')),/uncertain write/);assert.equal(await form('plan').locator('[name=name]').inputValue(),'Reviewed revised plan');assert.equal(await form('plan').locator('[name=confirm]').isChecked(),true);await form('plan').locator('button').click();await idle();let calls=(await getCalls()).filter(call=>call.url.endsWith('/atlas_bonus_plan_save'));assert.equal(calls.length,2);assert.equal(calls[0].body.p_request_id,calls[1].body.p_request_id);assert.equal(calls[1].body.p_plan_id,planId);assert.equal(calls[1].body.p_expected_version,4);assert.deepEqual(calls[1].body.p_payload.eligibilityRules.communityIds,[community,community2]);const savedNoi=calls[1].body.p_payload.metrics.find(row=>row.metricKey==='noi');assert.equal(savedNoi.id,'kept_noi_id');assert.equal(savedNoi.goal,110);assert.deepEqual(savedNoi.thresholdCurve,plan.metrics[0].thresholdCurve);assert.deepEqual(calls[1].body.p_payload.metrics.find(row=>row.metricKey==='revenue').thresholdCurve,plan.metrics[1].thresholdCurve);
 // Refresh cannot rebase an unsaved plan edit onto somebody else's intervening version.
 await form('plan').locator('[name=planId]').selectOption(planId);await form('plan').locator('[name=name]').fill('Unsaved original terms');await form('plan').locator('[name=reason]').fill('Keep this unsaved edit');await form('plan').locator('[name=confirm]').check();await page.evaluate(()=>{window.fixture.plans[0].version++;window.fixture.plans[0].targetBonus=350;});await page.locator('[data-refresh]').click();await idle();const beforePlanConflict=(await getCalls()).filter(call=>call.url.endsWith('/atlas_bonus_plan_save')).length;await form('plan').locator('button').click();assert.equal((await getCalls()).filter(call=>call.url.endsWith('/atlas_bonus_plan_save')).length,beforePlanConflict);assert.match(await page.locator('[role=alert]').allTextContents().then(a=>a.join(' ')),/plan changed after you selected it/);assert.equal(await form('plan').locator('[name=name]').inputValue(),'Unsaved original terms');await form('plan').locator('[name=planId]').selectOption('');await form('plan').locator('[name=planId]').selectOption(planId);assert.equal(await form('plan').locator('[name=targetBonus]').inputValue(),'350');assert.equal(await form('plan').locator('[name=planVersion]').inputValue(),'6');
 // Eligibility uses the exact selected employee version and permits explicit false.
 await form('eligibility').locator('[name=assignmentId]').selectOption(assignmentId);await form('eligibility').locator('[name=bonusEligible]').selectOption('false');await form('eligibility').locator('[name=bonusEffectiveDate]').fill('2026-09-24');await form('eligibility').locator('[name=reason]').fill('Synthetic eligibility review');await form('eligibility').locator('button').click();await idle();const eligibility=(await getCalls()).find(call=>call.url.endsWith('/atlas_bonus_eligibility_save')).body;assert.equal(eligibility.p_employee_id,employeeId);assert.equal(eligibility.p_expected_version,3);assert.equal(eligibility.p_payload.bonusEligible,false);
 // Calculation requires explicit assignment and versioned plan; RPC rejection preserves the form.
 await page.getByText('Create a calculation for review',{exact:true}).click();await form('draft').locator('[name=assignmentId]').selectOption(assignmentId);await form('draft').locator('[name=planId]').selectOption(planId);await form('draft').locator('[name=reason]').fill('Synthetic calculation review');await page.evaluate(()=>window.failWrite=true);await form('draft').locator('button').click();await idle();assert.equal(await form('draft').locator('[name=assignmentId]').inputValue(),assignmentId);assert.equal(await form('draft').locator('[name=reason]').inputValue(),'Synthetic calculation review');await form('draft').locator('button').click();await idle();calls=(await getCalls()).filter(call=>call.url.endsWith('/atlas_bonus_workflow')&&call.body.p_action==='draft');assert.equal(calls[0].body.p_request_id,calls[1].body.p_request_id);assert.equal(calls[1].body.p_expected_revision,0);assert.equal(calls[1].body.p_payload.planId,planId);assert.equal(calls[1].body.p_payload.periodKey,'2026-Q1');
 // Payment captures an already processed external payment; no transfer endpoint exists.
 let payment=page.locator('[data-form=transition][data-run="'+lockedId+'"]');await payment.locator('[name=reason]').fill('Payroll already processed this synthetic payment');await payment.locator('[name=externalReference]').fill('PAYROLL-SYNTHETIC-2');await payment.locator('[name=paidDate]').fill('2026-09-24');await payment.locator('[name=amount]').fill('80');await payment.locator('[name=confirmedPayment]').check();await page.evaluate(()=>window.failWrite=true);await payment.locator('button').click();await idle();assert.equal(await payment.locator('[name=externalReference]').inputValue(),'PAYROLL-SYNTHETIC-2');await payment.locator('button').click();await idle();calls=(await getCalls()).filter(call=>call.body.p_action==='record_external_payment');assert.equal(calls[0].body.p_request_id,calls[1].body.p_request_id);assert.equal(calls[1].body.p_expected_revision,4);assert.deepEqual(calls[1].body.p_payload,{reason:'Payroll already processed this synthetic payment',externalReference:'PAYROLL-SYNTHETIC-2',paidDate:'2026-09-24',amount:80});assert.match(await page.locator('#host').innerText(),/PAYROLL-SYNTHETIC-2/);assert.equal(await page.locator('[data-form=transition][data-run="'+lockedId+'"]').count(),0);
 // A successful write with unavailable readback must never claim verified success or offer a duplicate write.
 const approved=page.locator('[data-form=transition][data-run="'+approvedId+'"]');await approved.locator('[name=reason]').fill('Lock synthetic approved amount for payroll');await approved.locator('[name=confirmReview]').check();await page.evaluate(()=>window.breakReadAfterWrite=true);await approved.locator('button').click();await idle();assert.match(await page.locator('[role=status]').allTextContents().then(a=>a.join(' ')),/readback is unavailable/);assert.equal(await approved.locator('button').isDisabled(),true);assert.equal(await approved.locator('[name=reason]').inputValue(),'Lock synthetic approved amount for payroll');await page.evaluate(()=>window.failRead=false);await page.locator('[data-refresh]').click();await idle();assert.equal(await approved.locator('[name=reason]').inputValue(),'');assert.equal(await approved.locator('[name=externalReference]').count(),1);
 assert.match(await page.locator('[role=status]').allTextContents().then(a=>a.join(' ')),/saved step verified/);assert.doesNotMatch(await page.locator('[role=status]').allTextContents().then(a=>a.join(' ')),/readback is unavailable/);
 // Account changes do not submit old selections or keep old employee records visible.
 await openSetup();await form('eligibility').locator('[name=assignmentId]').selectOption(assignmentId);await form('eligibility').locator('[name=bonusEligible]').selectOption('true');await form('eligibility').locator('[name=bonusEffectiveDate]').fill('2026-09-24');await form('eligibility').locator('[name=reason]').fill('Must not save across accounts');const before=(await getCalls()).length;await page.evaluate(()=>window.actor='different-account');await form('eligibility').locator('button').click();assert.equal((await getCalls()).length,before);assert.match(await page.locator('[role=alert]').innerText(),/account changed/);assert.equal(await page.locator('form').count(),0);
 assert.deepEqual(errors,[]);assert(requests.every(url=>url.startsWith(origin)),'No external or API network calls');console.log('PASS Bonus UI: exact plan prefill/versions/communities/custom curves, preserved error/retry inputs and request IDs, eligibility false, explicit draft scope, retained raw actual and attainment, payroll confirmation only, honest unavailable readback, scoped session invalidation, and escaped private-free rendering.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
