const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{setup}=require('./bonus-workflow-db.test.cjs');
(async()=>{
 const {db,A,B,BUDGET,employee,assignment,role,call,signIn}=await setup();await db.exec('reset role;alter table atlas_user_profiles add column employee_id uuid');
 const admin='00000000-0000-0000-0000-000000000001',regional='00000000-0000-0000-0000-000000000002',finance='00000000-0000-0000-0000-000000000003',people='00000000-0000-0000-0000-000000000005';
 await db.query("update atlas_user_profiles set role='people',allowed_community_ids=array[$1::uuid] where user_id=$2",[A,people]);await signIn(1);
 const payload={name:'Synthetic boundaries',roleId:role,effectiveStart:'2026-01-01',effectiveEnd:'2026-12-31',targetBonus:0,maximumPayout:0,eligibilityRules:{requireBonusEligible:true,communityIds:[A]},metrics:[{id:'rev',metricKey:'revenue',goal:100,weight:100,thresholdCurve:[{thresholdPct:95,payoutPct:50},{thresholdPct:100,payoutPct:80},{thresholdPct:105,payoutPct:100}]}],reason:'Synthetic reviewed boundaries'};
 await assert.rejects(()=>call('atlas_bonus_plan_save',[null,0,{...payload,targetBonus:-1},randomUUID()]),/outside/);await assert.rejects(()=>call('atlas_bonus_plan_save',[null,0,{...payload,targetBonus:1.001},randomUUID()]),/whole cents/);
 // Cache replay cannot recover a prior response after its community access is revoked.
 await signIn(5);const planRequest=randomUUID(),plan=await call('atlas_bonus_plan_save',[null,0,payload,planRequest]),eligibilityRequest=randomUUID(),eligibilityPayload={bonusEligible:true,bonusEffectiveDate:'2026-01-01',reason:'Synthetic explicit eligibility'};
 await call('atlas_bonus_eligibility_save',[employee,1,eligibilityPayload,eligibilityRequest]);await db.exec('reset role');await db.query("update atlas_user_profiles set allowed_community_ids='{}' where user_id=$1",[people]);await signIn(5);
 await assert.rejects(()=>call('atlas_bonus_plan_save',[null,0,payload,planRequest]),/outside current community/);await assert.rejects(()=>call('atlas_bonus_eligibility_save',[employee,1,eligibilityPayload,eligibilityRequest]),/outside current community/);
 await db.exec('reset role');await db.query('update atlas_user_profiles set allowed_community_ids=array[$1::uuid] where user_id=$2',[A,people]);await signIn(1);
 const draft={assignmentId:assignment,planId:plan.id,periodKey:'2026-Q1',reason:'Synthetic boundary calculation'};
 await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,{...draft,amount:999999},randomUUID()]),/browser payout/);
 await db.exec('reset role');const otherAssignment=randomUUID();await db.query("insert into atlas_employee_assignments(assignment_id,employee_id,community_id,role_id,employment_status,effective_start,effective_end) values($1,$2,$3,$4,'Active','2026-01-01','2026-12-31')",[otherAssignment,employee,A,role]);await signIn(1);
 await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,draft,randomUUID()]),/Overlapping/);await db.exec('reset role');await db.query('delete from atlas_employee_assignments where assignment_id=$1',[otherAssignment]);await db.query("update atlas_employee_assignments set effective_start='2026-02-01' where assignment_id=$1",[assignment]);await signIn(1);await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,draft,randomUUID()]),/full quarter/);
 await db.exec('reset role');await db.query("update atlas_employee_assignments set effective_start='2026-01-01' where assignment_id=$1",[assignment]);await db.query("update atlas_command_financial_summaries set summary=jsonb_set(summary,'{revenue,actual}','null') where community_id=$1 and period_key='2026-02'",[A]);await signIn(1);await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,draft,randomUUID()]),/Closed actual.*finite number/);
 await db.exec('reset role');await db.query("update atlas_command_financial_summaries set summary=jsonb_set(summary,'{revenue,actual}','997.5') where community_id=$1",[A]);const original=(await db.query('select payload from atlas_approved_budget_versions where version_id=$1',[BUDGET])).rows[0].payload;await db.query("update atlas_approved_budget_versions set payload=jsonb_set(payload,'{metricMappings,revenue}','[{\"glCode\":\"5120\",\"factor\":0}]') where version_id=$1",[BUDGET]);await signIn(1);await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,draft,randomUUID()]),/Zero baseline/);
 await db.exec('reset role');await db.query("update atlas_approved_budget_versions set payload=jsonb_set(payload,'{metricMappings,revenue}','[{\"glCode\":\"5120\",\"factor\":-1}]') where version_id=$1",[BUDGET]);await db.query("update atlas_command_financial_summaries set summary=jsonb_set(summary,'{revenue,actual}','-950') where community_id=$1",[A]);await signIn(3);
 let signed=await call('atlas_bonus_workflow',[null,'draft',0,draft,randomUUID()]);assert.equal(signed.calculation.metricResults[0].baseline,-3000);assert.equal(signed.calculation.metricResults[0].rawActual,-2850);assert.equal(signed.calculation.metricResults[0].variance,150);assert.equal(signed.calculation.metricResults[0].actual,105,'An improvement against a negative target retains the correct attainment direction');await call('atlas_bonus_workflow',[signed.runId,'void',signed.revision,{reason:'Release synthetic signed-metric fixture'},randomUUID()]);
 await db.exec('reset role');await db.query('update atlas_approved_budget_versions set payload=$1 where version_id=$2',[JSON.stringify(original),BUDGET]);await db.query("update atlas_command_financial_summaries set summary=jsonb_set(summary,'{revenue,actual}','997.5') where community_id=$1",[A]);await signIn(3);
 const draftRequest=randomUUID();let run=await call('atlas_bonus_workflow',[null,'draft',0,draft,draftRequest]);assert.equal(run.totalPayout,0,'Explicit zero target must remain exactly zero');assert.equal(run.calculation.finalPayout,0);
 await db.exec('reset role');await db.query("update atlas_user_profiles set allowed_community_ids='{}' where user_id=$1",[finance]);await signIn(3);await assert.rejects(()=>call('atlas_bonus_workflow',[null,'draft',0,draft,draftRequest]),/outside current community/);await db.exec('reset role');await db.query('update atlas_user_profiles set allowed_community_ids=array[$1::uuid] where user_id=$2',[A,finance]);await signIn(3);
 run=await call('atlas_bonus_workflow',[run.runId,'submit',run.revision,{reason:'Synthetic submit'},randomUUID()]);await db.exec('reset role');await db.query('update atlas_user_profiles set employee_id=$1 where user_id=$2',[employee,regional]);await signIn(2);await assert.rejects(()=>call('atlas_bonus_workflow',[run.runId,'approve',run.revision,{reason:'Own beneficiary approval'},randomUUID()]),/own Bonus/);
 await db.exec('reset role');await db.query('update atlas_user_profiles set employee_id=null where user_id=$1',[regional]);await signIn(2);run=await call('atlas_bonus_workflow',[run.runId,'approve',run.revision,{reason:'Independent synthetic approval'},randomUUID()]);await signIn(1);run=await call('atlas_bonus_workflow',[run.runId,'lock',run.revision,{reason:'Synthetic zero lock'},randomUUID()]);run=await call('atlas_bonus_workflow',[run.runId,'record_external_payment',run.revision,{reason:'Zero award external receipt',externalReference:'SYNTHETIC-ZERO',paidDate:'2026-04-01',amount:0},randomUUID()]);assert.equal(run.totalPayout,0);assert.equal(run.payment.amount,0);
 await signIn(5);let receipts=await call('atlas_read_bonus_receipts',['2026-Q1']);assert.equal(receipts[0].verified,true);assert.equal(receipts[0].period.status,'paid');assert.equal(receipts[0].lines[0].payout_amount,0);await assert.rejects(()=>db.query('select inputs from atlas_bonus_calculation_runs'),/permission denied/);await assert.rejects(()=>db.query('select line_payload from atlas_bonus_calculation_lines'),/permission denied/);
 // Privileged fault injection is LOCAL ONLY: verify corrupt retained bytes cannot become payable for People.
 await db.exec('reset role;alter table atlas_bonus_calculation_lines disable trigger reforecast_bonus_line_immutable');await db.query("update atlas_bonus_calculation_lines set line_payload=line_payload||'{\"secureCalculationDetail\":{\"salary\":987654321}}'::jsonb where bonus_calculation_run_id=$1",[run.runId]);await db.exec('alter table atlas_bonus_calculation_lines enable trigger reforecast_bonus_line_immutable');await signIn(5);receipts=await call('atlas_read_bonus_receipts',['2026-Q1']);assert.equal(receipts[0].verified,false);assert(!JSON.stringify(receipts).includes('987654321'));
 await signIn(1);assert.equal((await call('atlas_read_bonus_receipts',['2026-Q1']))[0].verified,false);
 // Explicit permissions override a permissive role, including cached operation replay.
 await db.exec('reset role');await db.query("update atlas_user_profiles set bonus_permissions='{view_bonus_module}' where user_id=$1",[people]);await signIn(5);await assert.rejects(()=>call('atlas_bonus_plan_save',[null,0,payload,planRequest]),/setup access denied/);
 await db.close();console.log('PASS Bonus missing/null/zero/cent guards, overlap/proration rejection, scoped cache replay, beneficiary conflict, explicit permissions and exact redacted People retained receipts');
})().catch(e=>{console.error(e.message,e.where||'');process.exitCode=1});
