const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
const root=path.join(__dirname,'..'),migration=name=>fs.readFileSync(path.join(root,'supabase/migrations',name),'utf8');
(async()=>{
 const {parseReforecastWorkbook}=await import('../docs/portfolio-operations-dashboard/features/reforecast-intake.mjs');
 const {planningMappingDispositions}=await import('../docs/portfolio-operations-dashboard/features/planning-governance.mjs');
 const XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
 const {db,A,B,BUDGET,CLOSE,signIn}=await fixture(),owner='00000000-0000-0000-0000-000000000001';
 const call=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
 await db.exec('reset role');
 await db.exec(migration('20260924121641_planning_cell_workbook_integrity_governance.sql'));
 // Install the exact immutable audit storage/resolution functions; the remainder
 // of this migration concerns financial close ingestion outside this fixture.
 await db.exec(migration('20260924121647_immutable_workbook_audits_and_monthly_governance.sql').split('alter function atlas_private.finance_intake_validation')[0]);
 for(const file of ['20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql'])await db.exec(migration(file));
 const approvedMetricMappings={revenue:[{glCode:'5120',factor:1},{glCode:'5220',factor:1}],expenses:[{glCode:'6100',factor:1},{glCode:'6200',factor:1}],capital:[{glCode:'8100',factor:1}]};
 await db.query("update atlas_approved_budget_versions set payload=payload||jsonb_build_object('metricMappings',$1::jsonb,'mappingVersion','approved-fixture-v1') where version_id=$2",[approvedMetricMappings,BUDGET]);
 await signIn(1);
 const initialSource=await call('atlas_read_reforecast_builder_source',[A,['2026-02'],[BUDGET],null,'original_budget',null]);
 assert.equal(initialSource.registry.version,null);assert.equal(initialSource.baseline.approvedMetricMappings[0].versionId,BUDGET);assert.deepEqual(initialSource.baseline.approvedMetricMappings[0].metricMappings,approvedMetricMappings);
 assert.equal((await db.query('select count(*)::int n from atlas_reforecast_registries')).rows[0].n,0,'published metric evidence never creates a registry implicitly');
 const accounts=[['5120','Rent','income'],['5220','Vacancy','contra_income'],['6100','Payroll','expense'],['6200','Utilities','expense'],['8100','Capital','capital']].map(([accountCode,category,nature])=>({accountCode,category,nature,placement:nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'}));
 const registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),{accounts,driverMappings:{},reason:'Reviewed exact import registry',effectiveDate:'2026-01-01'}]);
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Scenario','Plan','Currency','Local'],['GL','Account','Feb 2026','Mar 2026'],['5120','Rent',1001.25,1002.501234],['6100','Payroll',0,210],['6200','Utilities',null,55],['5120','duplicate rent',999,998]]),'Plan');
 const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'}),evidence=await parseReforecastWorkbook(bytes,{xlsx:XLSX,fileName:'Synthetic.xlsx'});
 if(process.env.ATLAS_PROJECTED_AUDIT){await (await import('./workbook-projection-fixture.mjs')).installProjectionFixture(db);await signIn(1);}
 const audit=process.env.ATLAS_PROJECTED_AUDIT?await (await import('./workbook-projection-fixture.mjs')).saveProjectedAudit(db,A,evidence.integrity,bytes):await call('atlas_save_workbook_audit',[A,evidence.source.sha256,evidence.integrity,randomUUID()]);
 const assignment={communityId:A,confirmed:true,sourceEntities:[],actorId:owner,reason:'Reviewed community'};
 const uploadPayload={...evidence,source:{...evidence.source,originalFile:{encoding:'base64',data:Buffer.from(bytes).toString('base64')}},integrity:{auditId:audit.audit_id,fingerprint:audit.fingerprint,...(audit.manifest_hash?{manifestHash:audit.manifest_hash}:{})},propertyAssignment:assignment};
 const upload=await call('atlas_save_reforecast_upload',[A,randomUUID(),uploadPayload]);
 const periods=['2026-02','2026-03'],reviewedAt='2026-09-25T00:00:00Z',sourceScenario=evidence.lines[0].scenario;
 assert.equal(sourceScenario,'Plan');
 const selected=evidence.lines.filter(l=>l.row<6&&l.amount!==null);
 const mapping={confirmed:true,version:registry.version_id,propertyAssignment:assignment,sourceScenario,currency:'USD',periods,selectedLineIds:selected.map(l=>l.id),accountMappings:accounts.map(a=>({...a,sourceAccountCode:a.accountCode,sheet:'Plan',department:null,signMultiplier:1,allowReversal:false})),reason:'Import exact reviewed forecast values',reviewedBy:owner,reviewedAt,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:sourceScenario,reviewedBy:owner,reviewedAt},inputReviews:selected.map(l=>({cellId:l.id,confirmed:true,ownerId:owner,effectivePeriod:l.period,before:l.amount,after:l.amount,reason:'Reviewed input value',reviewedAt,integrityFingerprint:audit.fingerprint})),integrityReviews:[]};
 Object.assign(mapping,planningMappingDispositions(evidence,mapping));
 mapping.currencyMapping={sourceCurrency:'Local',reportingCurrency:'USD',method:'identity',confirmed:true,reviewedBy:owner,reviewedAt,reason:'Reviewed Local as USD with no currency conversion'};
 const payload={name:'Conventional from Plan',model:'conventional',scenarioPurpose:'conventional',governanceSchemaVersion:2,calendar:{...mapping.calendar,scenario:'Conventional from Plan'},periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:owner,reviewerId:owner,drivers:[],overrides:[],reason:'Create working forecast from reviewed Plan'};
 const scenario=randomUUID(),request=randomUUID(),args=[A,scenario,0,request,upload.upload_id,mapping,payload];
 const create=(overrides={})=>call('atlas_create_reforecast_from_import',[overrides.communityId??A,overrides.scenarioId??scenario,overrides.expectedRevision??0,overrides.requestId??randomUUID(),overrides.uploadId??upload.upload_id,overrides.mapping??mapping,overrides.payload??payload]);
 await db.exec('reset role');
 await db.exec(migration('20260925071533_reforecast_request_identity_consistency.sql'));
 await db.exec(migration('20260925162050_budget_governed_draft_investor_lifecycle.sql'));
 await db.exec("create function atlas_private.budget_calendar(cid uuid) returns jsonb language sql as $$select '{\"verified\":true,\"basis\":\"calendar\",\"startMonth\":1}'::jsonb$$");
 await signIn(1);
 let result=await call('atlas_create_reforecast_from_import',args);
 assert.equal(result.head.status,'working_draft');assert.equal(result.snapshot.completeness.blockerCount,0,JSON.stringify(result.snapshot.diagnostics));
 assert.equal((await db.query('select count(*)::int n from atlas_reforecast_publications')).rows[0].n,0);
 const save=(r,action,body=r.revision.payload,requestId=randomUUID())=>call('atlas_save_reforecast_scenario',[A,r.head.scenario_id,r.head.revision,requestId,action,body]);
 const twin=await create({scenarioId:randomUUID()});assert.equal(twin.head.status,'working_draft');
 assert.equal((await call('atlas_read_reforecast_workspace',[[A]])).length,2,'same-period drafts coexist');
 const beforeImport=result.revision.revision_id;
 await signIn(2);const body=structuredClone(result.revision.payload),cell=body.overrides.find(o=>o.accountCode==='5120'&&o.period==='2026-02');
 Object.assign(cell,{amount:1015,after:1015,before:cell.amount,ownerId:'00000000-0000-0000-0000-000000000002',reviewedAt:'2026-09-25T12:00:00Z',reason:'Authorized derived workbook edit'});
 result=await save(result,'save_draft',body);assert.equal(result.snapshot.completeness.blockerCount,0,JSON.stringify(result.snapshot.diagnostics));assert.equal(result.snapshot.lines.find(o=>o.accountCode==='5120'&&o.period==='2026-02').forecast,1015);
 assert.equal(result.revision.payload.overrides.find(o=>o.accountCode==='5120'&&o.period==='2026-02').source.kind,'manual_revision');
 assert.equal((await db.query('select snapshot from atlas_reforecast_revisions where revision_id=$1',[beforeImport])).rows[0].snapshot.lines.find(o=>o.accountCode==='5120'&&o.period==='2026-02').forecast,1001.25);
 result=await save(result,'submit');assert.equal(result.head.status,'submitted');
 assert.equal((await db.query('select count(*)::int n from atlas_reforecast_publications')).rows[0].n,0,'submit cannot publish');
 await assert.rejects(()=>save(result,'save_draft'),/Submitted revisions are immutable/);
 await assert.rejects(()=>save(result,'vp_approve'),/verified VP/);
 await signIn(1);await assert.rejects(()=>save(result,'vp_approve'),/verified VP/,'Admin alone cannot publish');await assert.rejects(()=>save(result,'withdraw'),/submitter/);
 result=await save(result,'reject',{...result.revision.payload,reason:'Return to preparer for documented review'});assert.equal(result.head.status,'rejected');
 await signIn(2);result=await save(result,'save_draft');result=await save(result,'submit');result=await save(result,'withdraw',{...result.revision.payload,reason:'Withdraw for preparation'});assert.equal(result.head.status,'withdrawn');result=await save(result,'submit');
 await signIn(5);const vpArgs=[A,result.head.scenario_id,result.head.revision,randomUUID(),'vp_approve',result.revision.payload];
 result=await call('atlas_save_reforecast_scenario',vpArgs);assert.equal(result.head.status,'pending_investor_approval');assert(result.publication.publication_id);
 assert.equal((await call('atlas_save_reforecast_scenario',vpArgs)).publication.publication_id,result.publication.publication_id,'VP retry is idempotent');
 assert(result.deliveries.some(d=>d.consumer_key==='canonical_baseline'&&d.delivery_status==='verified'),JSON.stringify(result.deliveries));
 assert(result.deliveries.some(d=>d.consumer_key==='official_report'&&d.delivery_status==='verified'),JSON.stringify(result.deliveries));
 assert(result.deliveries.some(d=>d.delivery_status==='pending'),'unverified consumer delivery remains visible');
 const firstPub=result.publication,firstSnapshot=JSON.stringify(firstPub.snapshot);
 assert.equal((await call('atlas_reforecast_effective_baseline',[[A],periods]))[0].publicationId,firstPub.publication_id);
 await assert.rejects(()=>save(result,'investor_approve'),/approval date/);
 result=await save(result,'investor_approve',{...result.revision.payload,investorApprovalDate:'2026-09-24'});assert.equal(result.head.status,'investor_approved');assert.equal(result.revision.payload.investorApprovalDate,'2026-09-24');
 const report=await call('atlas_read_reforecast_publication',[firstPub.publication_id]);assert.equal(report.investorStatus,'investor_approved');assert.equal(report.investorApprovalDate,'2026-09-24');assert.equal(report.verified,true);
 await assert.rejects(()=>save(result,'save_draft'),/locked/);
 result=await save(result,'reopen',{...result.revision.payload,reason:'Investor requested revised operating plan'});assert.equal(result.head.status,'reopened');
 assert.equal((await call('atlas_reforecast_effective_baseline',[[A],periods]))[0].publicationId,firstPub.publication_id,'reopen preserves last approved live baseline');
 result=await save(result,'submit');result=await save(result,'vp_approve');const secondPub=result.publication;
 assert.notEqual(secondPub.publication_id,firstPub.publication_id);assert.equal((await call('atlas_reforecast_effective_baseline',[[A],periods]))[0].publicationId,secondPub.publication_id,'new VP approval overrides older investor-approved version');
 await signIn(2);const changed=structuredClone(result.revision.payload),rent=changed.overrides.find(o=>o.accountCode==='5120'&&o.period==='2026-02');Object.assign(rent,{amount:1020,after:1020,before:1015,ownerId:'00000000-0000-0000-0000-000000000002',reason:'Investor requested rent revision'});
 result=await save(result,'edit',changed);assert.equal(result.head.status,'submitted','nonVP edit returns revised financial values to VP review');assert.equal((await call('atlas_reforecast_effective_baseline',[[A],periods]))[0].publicationId,secondPub.publication_id);
 assert.equal(JSON.stringify((await db.query('select snapshot from atlas_reforecast_publications where publication_id=$1',[firstPub.publication_id])).rows[0].snapshot),firstSnapshot);
 await signIn(5);result=await save(result,'vp_approve');const current=result.publication;
 const retryId=randomUUID(),delivery=await call('atlas_retry_budget_publication',[current.publication_id,retryId]);assert.deepEqual(await call('atlas_retry_budget_publication',[current.publication_id,retryId]),delivery);
 await signIn(1);await assert.rejects(()=>save(twin,'delete',{...twin.revision.payload,reason:'Remove unused parallel draft'}),/Confirm deletion/);
 const deleted=await save(twin,'delete',{...twin.revision.payload,reason:'Remove unused parallel draft',deleteConfirmed:true});assert.equal(deleted.head.status,'deleted');assert(!(await call('atlas_read_reforecast_workspace',[[A]])).some(r=>r.head.scenario_id===twin.head.scenario_id));
 await signIn(3);assert.equal((await call('atlas_read_reforecast_workspace',[[A]]))[0].permissions.canEdit,true,'Finance is authorized to edit shared drafts');
 await signIn(4);await assert.rejects(()=>save(result,'edit'),/access denied/);assert.deepEqual(await call('atlas_read_reforecast_workspace',[[A]]),[]);assert.equal((await db.query('select * from atlas_budget_workflow_audit')).rows.length,0);
 await db.exec('reset role');const workflowAudit=(await db.query('select * from atlas_budget_workflow_audit')).rows;assert(workflowAudit.some(e=>e.action==='delete'));assert(workflowAudit.some(e=>e.action==='investor_approve'));assert(workflowAudit.some(e=>e.action==='vp_publication'&&e.baseline_versions.length>0));
 await assert.rejects(()=>db.exec("update atlas_budget_workflow_audit set reason='forged'"),/immutable/);await assert.rejects(()=>db.exec("update atlas_budget_publication_deliveries set delivery_status='verified'"),/immutable/);
 const fingerprint=(await db.query('select snapshot from atlas_reforecast_publications where publication_id=$1',[current.publication_id])).rows[0].snapshot.fingerprint;
 await db.query('update atlas_financial_close_heads set version_id=$1 where community_id=$2',[randomUUID(),A]);await signIn(5);assert.equal((await call('atlas_reforecast_effective_baseline',[[A],periods]))[0].contentHash,fingerprint,'a changed actual close cannot invalidate the last VP snapshot');
 // A genuinely new property's original budget needs no pre-existing approved baseline.
 await db.exec('reset role');
 await db.exec("alter table atlas_approved_budget_versions alter column version_id set default gen_random_uuid();alter table atlas_approved_budget_versions alter column status set default 'locked';alter table atlas_approved_budget_versions add column fiscal_year integer,add column fiscal_start_month integer,add column scenario_id text,add column scenario_version text,add column effective_date date,add column content_hash text,add column approved_by uuid;");
 await db.exec('grant select on atlas_approved_budget_versions to authenticated');
 await db.query("update atlas_communities set first_expected_financial_period='2026-01' where community_id=$1",[B]);await signIn(1);
 const newAccounts=accounts.filter(a=>['5120','6100','6200'].includes(a.accountCode));
 const newRegistry=await call('atlas_save_reforecast_registry',[B,null,randomUUID(),{accounts:newAccounts,driverMappings:{},reason:'Review initial property GL registry',effectiveDate:'2026-01-01'}]);
 const newAudit=await call('atlas_save_workbook_audit',[B,evidence.source.sha256,evidence.integrity,randomUUID()]);
 const newAssignment={...assignment,communityId:B};
 const newUpload=await call('atlas_save_reforecast_upload',[B,randomUUID(),{...uploadPayload,propertyAssignment:newAssignment,integrity:{auditId:newAudit.audit_id,fingerprint:newAudit.fingerprint}}]);
 const newMapping={...mapping,version:newRegistry.version_id,propertyAssignment:newAssignment,accountMappings:mapping.accountMappings.filter(a=>newAccounts.some(n=>n.accountCode===a.accountCode))};
 const newPayload={...payload,recordType:'initial_budget',baselineType:'initial_workbook',baselineVersionIds:[],registryVersionId:newRegistry.version_id};
 let initial=await call('atlas_create_reforecast_from_import',[B,randomUUID(),0,randomUUID(),newUpload.upload_id,newMapping,newPayload]);
 assert.equal(initial.head.status,'working_draft');assert.equal(initial.snapshot.completeness.blockerCount,0,JSON.stringify(initial.snapshot.diagnostics));
 assert.equal(initial.source.baseline.versionIds.length,0);assert.equal(initial.snapshot.lines.find(l=>l.accountCode==='6200'&&l.period==='2026-02').forecast,null,'a blank initial workbook GL remains blank');
 assert.equal((await db.query('select count(*)::int n from atlas_approved_budget_versions where community_id=$1',[B])).rows[0].n,0,'initial import does not publish');
 const initialEdited=structuredClone(initial.revision.payload),initialCell=initialEdited.overrides.find(l=>l.accountCode==='5120'&&l.period==='2026-02');Object.assign(initialCell,{amount:1100,after:1100,before:initialCell.amount,reason:'VP-reviewed derived initial budget edit'});
 initial=await call('atlas_save_reforecast_scenario',[B,initial.head.scenario_id,initial.head.revision,randomUUID(),'save_draft',initialEdited]);
 initial=await call('atlas_save_reforecast_scenario',[B,initial.head.scenario_id,initial.head.revision,randomUUID(),'submit',initial.revision.payload]);await signIn(5);
 const initialApprovalArgs=[B,initial.head.scenario_id,initial.head.revision,randomUUID(),'vp_approve',initial.revision.payload];initial=await call('atlas_save_reforecast_scenario',initialApprovalArgs);
 const original=(await db.query('select * from atlas_approved_budget_versions where community_id=$1',[B])).rows[0];assert.equal(original.payload.rows.find(l=>l.glCode==='5120').monthly[1],1100);assert.equal(original.payload.rows.find(l=>l.glCode==='6200').monthly[1],null);assert.equal(original.payload.originPublicationId,initial.publication.publication_id);
 assert.equal((await call('atlas_reforecast_effective_baseline',[[B],periods]))[0].publicationId,initial.publication.publication_id);
 assert.equal((await call('atlas_save_reforecast_scenario',initialApprovalArgs)).publication.publication_id,initial.publication.publication_id,'initial publication replay does not recreate original budgets');
 const consumerArgs=[initial.publication.publication_id,'dashboard',randomUUID(),initial.publication.revision_id,initial.publication.snapshot.fingerprint];
 const consumerReceipt=await call('atlas_verify_budget_consumer',consumerArgs);assert.equal(consumerReceipt.delivery_status,'verified');assert.deepEqual(await call('atlas_verify_budget_consumer',consumerArgs),consumerReceipt);
 assert.equal((await call('atlas_verify_budget_consumer',[initial.publication.publication_id,'dashboard',randomUUID(),initial.publication.revision_id,'wrong'])).delivery_status,'failed');
 // Contract-backed rates and estimated months remain distinct at the server boundary.
 await db.exec('reset role');await db.exec('alter table atlas_communities add column market text');await db.query("update atlas_communities set market='Tampa, FL' where community_id=$1",[B]);
 const contractUpload=randomUUID(),contractReview=randomUUID(),contractId=randomUUID();
 const terms={contractId,accountCode:'6100',effectiveDate:'2026-01-01',endDate:'2026-03-31',monthlyAmount:100};
 await db.exec('create table atlas_contracts(contract_id uuid primary key,community_id uuid,status text,version integer,deleted_at timestamptz,start_date date,end_date date,amount numeric)');
 await db.query("insert into atlas_contracts values($1,$2,'active',1,null,'2026-01-01','2026-03-31',100)",[contractId,B]);
 const canonicalContract=(await db.query("select jsonb_build_object('version',c.version,'contentHash',encode(sha256(convert_to(to_jsonb(c)::text,'UTF8')),'hex')) value from atlas_contracts c where contract_id=$1",[contractId])).rows[0].value;
 await db.query('insert into atlas_reforecast_uploads(upload_id,community_id,request_id,source_hash,content_hash,payload,created_by,created_role) values($1,$2,$3,$4,$4,$5,$6,\'admin\')',[contractUpload,B,randomUUID(),'contract-hash',{sourceType:'contract',contract:terms},owner]);
 await db.query('insert into atlas_reforecast_source_reviews(review_id,community_id,upload_id,request_id,content_hash,payload,reviewed_by) values($1,$2,$3,$4,$5,$6,$7)',[contractReview,B,contractUpload,randomUUID(),'review-hash',{status:'approved',canonicalContract},owner]);
 const contractEvidence={kind:'contract',contractUploadId:contractUpload,contractId,sourceHash:'contract-hash',reviewId:contractReview,method:'contract_clause',coverage:'Contract Backed',contractBacked:true};
 const monthly={period:'2026-03',accountCode:'6100',amount:100,originalCalculatedValue:100,source:contractEvidence};
 const contractIssues=async overrides=>(await db.query('select atlas_private.budget_contract_issues($1,$2) result',[B,{periods:['2026-03','2026-04'],overrides}])).rows[0].result;
 assert.deepEqual(await contractIssues([monthly]),[]);
 const estimate={...monthly,period:'2026-04',amount:103,originalCalculatedValue:103,source:{...contractEvidence,method:'out_of_contract_estimate',coverage:'Out of Contract - Estimated',contractBacked:false,priorRate:100,inflationPercentage:3,assumption:{communityId:B,location:'Tampa, FL',percentage:3,source:'Property location inflation forecast',effectiveDate:'2026-04-01',ownerId:owner,confirmed:true}}};
 assert.deepEqual(await contractIssues([monthly,estimate]),[]);
 await db.query('update atlas_contracts set amount=125,version=2 where contract_id=$1',[contractId]);
 assert((await contractIssues([monthly])).some(i=>i.code==='contract_canonical_stale'),'initial-workbook contracts cannot bypass changed canonical rates or versions');
 await db.query("update atlas_contracts set amount=100,version=1,status='terminated' where contract_id=$1",[contractId]);
 assert((await contractIssues([monthly,estimate])).every(i=>i.code==='contract_canonical_stale'),'terminated contract evidence requires new review');
 await db.query("update atlas_contracts set status='active' where contract_id=$1",[contractId]);
 assert.deepEqual(await contractIssues([monthly,estimate]),[]);
 assert((await contractIssues([{...estimate,source:{...estimate.source,contractBacked:true}}])).some(i=>i.code==='contract_inflation_review'));
 assert((await contractIssues([{...estimate,source:{...estimate.source,assumption:{...estimate.source.assumption,location:'Other market'}}}])).some(i=>i.code==='contract_inflation_review'));
 assert((await contractIssues([{...monthly,originalCalculatedValue:101}])).some(i=>i.code==='contract_rate_mismatch'));
 assert.deepEqual(await contractIssues([{...monthly,amount:105,source:{...monthly.source,contractBacked:false,coverage:'User Override'}}]),[],'user overrides retain exact recommendation separately');
 const conflictingUpload=randomUUID();await db.query('insert into atlas_reforecast_uploads(upload_id,community_id,request_id,source_hash,content_hash,payload,created_by,created_role) values($1,$2,$3,$4,$4,$5,$6,\'admin\')',[conflictingUpload,B,randomUUID(),'other-contract-hash',{sourceType:'contract',contract:{...terms,contractId:randomUUID()}},owner]);
 await db.query('insert into atlas_reforecast_source_reviews(community_id,upload_id,request_id,content_hash,payload,reviewed_by) values($1,$2,$3,$4,$5,$6)',[B,conflictingUpload,randomUUID(),'other-review-hash',{status:'approved'},owner]);
 assert((await contractIssues([])).some(i=>i.code==='contract_source_conflict'),'conflict detection considers every uploaded active approved contract');
 const controlling={period:'2026-03',accountCode:'6100',uploadId:contractUpload,approved:true,reason:'Reviewed this executed contract controls',reviewedBy:owner,reviewedAt:'2026-09-25T12:00:00Z'};
 assert.deepEqual((await db.query('select atlas_private.budget_contract_issues($1,$2) result',[B,{periods:['2026-03'],overrides:[monthly],contractSourceDecisions:[controlling]}])).rows[0].result,[]);
 const access=(await db.query("select p.proname,has_function_privilege('anon',p.oid,'EXECUTE') allowed from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ('save_budget_workflow','atlas_verify_budget_consumer','verify_budget_consumer','atlas_retry_budget_publication','budget_publication_readback','budget_contract_issues','publish_initial_budget')")).rows;for(const f of access)assert.equal(f.allowed,false,f.proname);
 await db.exec('reset role;set role anon');await assert.rejects(()=>call('atlas_save_reforecast_scenario',vpArgs),/permission denied/);
 await db.close();console.log('PASS governed Budget Builder lifecycle: editable imports, concurrent drafts, shared-session edits, immutable submission, VP-only publication, investor date/final lock, reopening baseline continuity, newer VP baseline precedence, nonVP resubmission, confirmation/audit deletion, authorization, idempotent consumer delivery receipts, true no-baseline initial budgets, blank-preserving original publication, server contract/inflation checks and source conflict resolution');
})().catch(error=>{console.error(error);process.exitCode=1});
