const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const dir=__dirname+'/../docs/portfolio-operations-dashboard/';
const context={console,Date,URL,URLSearchParams,TextEncoder,structuredClone,setTimeout:()=>0,clearTimeout:()=>{},location:{search:'',href:'http://localhost/'},document:{addEventListener(){},querySelectorAll(){return []},getElementById(){return null}},localStorage:{getItem(){return null}},addEventListener(){},navigator:{}};context.window=context;context.parent=context;
vm.createContext(context);
const html=fs.readFileSync(dir+'RISE-Budget-Builder.html','utf8');
for(const m of html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)){if(m[1].trim()&&!m[1].includes('RBB.app.boot()'))vm.runInContext(m[1],context);}
vm.runInContext(fs.readFileSync(dir+'budget-mapped-import.js','utf8'),context);
vm.runInContext(fs.readFileSync(dir+'investor-budget-bridge.js','utf8'),context);
const R=context.RBB,M=R.importer,state=R.buildState(),p=state.properties[0],sc=state.scenarios.find(s=>s.type==='approved'&&s.locked);
const headers=['property','gl','year','effective_date',...'jan feb mar apr may jun jul aug sep oct nov dec'.split(' ')];
const rows=[headers,[p.code,'5120',2026,'2026-09-01',...Array(12).fill(1000)],[p.code,'6461',2026,'2026-09-01',...Array(12).fill(200)]];
const workbook=R.exporter.buildXlsx([{name:'Instructions',rows:[['Do not import']]},{name:'Approved',rows:[['Title'],...rows]}]);
if(process.env.ATLAS_BUDGET_FIXTURE)fs.writeFileSync(process.env.ATLAS_BUDGET_FIXTURE,workbook);
const read=R.xlsx.read(workbook),sheets=M.mappedSheets(read,'approved_budget');
assert.equal(sheets[1].header,1);
const validate=(r=rows)=>{const v=M.validate('approved_budget',r,state);v.fileName='fixture.xlsx';v.sheetName='Approved';v.headerRow=2;return v;};
let v=validate(sheets[1].rows);assert.equal(v.errors.length,0,JSON.stringify(v.errors));
const actuals=JSON.stringify(state.actuals);assert.equal(M.apply(v.type,v,state).applied,2);assert.equal(JSON.stringify(state.actuals),actuals);
const calc=R.engine.computeAll(state,sc.id,2026),vr=R.variance.compute(state,calc,p.id,2026);
assert.equal(vr.rows.find(r=>r.gl==='5120').budget[0],1000);
let report=R.investorSources(state).properties[p.name].periods['2026-01'];assert.equal(report.noi.budget,800);assert.match(report.noi.sources.budget,/fixture.xlsx.*Approved/);
assert.equal(M.apply(v.type,validate(),state).applied,0,'same-date import blocked');
const newer=rows.map(r=>r.slice());newer[1][3]=newer[2][3]='2026-09-02';newer[1][4]=1200;
assert.equal(M.apply(v.type,validate(newer),state).applied,2);
assert.equal(M.apply(v.type,validate(),state).applied,0,'older import blocked');
const missing=rows.map(r=>r.slice());missing[1][4]='';assert.equal(validate(missing).status,'rejected');
assert.equal(validate([...rows,rows[1]]).status,'rejected');
const wrong=rows.map(r=>r.slice());wrong[1][0]='Unknown';assert.equal(validate(wrong).status,'rejected');
const prior=M.validate('prior_budget',rows,state);M.apply('prior_budget',prior,state);assert.equal(JSON.stringify(state.actuals),actuals);
assert(!state.approvedBudgetImports['OTHER|2026']);assert(!state.approvedBudgetImports[p.id+'|2025']);
const restored=JSON.parse(JSON.stringify(R.persist.serialize(state,{}))).state;assert(restored.approvedBudgetImports[p.id+'|2026']);
assert.equal(R.investorSources(restored).properties[p.name].periods['2026-01'].noi.budget,1000);
console.log('PASS real XLSX multi-sheet/title-row ingestion, exact property/year, engine/reporting reconciliation, version precedence, persistence and actuals isolation');

M.addCatalogProperties(state,['Test Other Community']);
const otherRows=rows.map(r=>r.slice());otherRows[1][0]=otherRows[2][0]='Test Other Community';
v=validate(otherRows);assert.equal(v.errors.length,0);M.apply(v.type,v,state);
assert.equal(R.investorSources(state).properties['Test Other Community'].periods['2026-01'].noi.budget,800);
console.log('PASS ATLAS catalog community imports without generated financial assumptions');
const parentCode=fs.readFileSync(dir+'atlas-mounts.js','utf8');
const publish=parentCode.slice(parentCode.indexOf('  function publishBudgetToAtlas('),parentCode.indexOf('  function publishBudgetContractToAtlas('));
const pc={console,Date,savedData:{A:{}},matchPropertyName:n=>n==='A'?'A':null,persistSaved(){},syncSharedPropertyFromPortfolioRecord(){}};vm.createContext(pc);vm.runInContext(publish,pc);
const periods=Object.fromEntries(Array.from({length:12},(_,i)=>['2026-'+String(i+1).padStart(2,'0'),[{gl:'5120',budget:1000,nature:'income'}]]));
const packet={locked:true,property:{name:'A'},year:2026,effectiveDate:'2026-09-01',scenario:{id:'x',name:'Approved'},budgetByPeriod:periods};
assert.equal(pc.publishBudgetToAtlas(packet).ok,true);assert.equal(pc.publishBudgetToAtlas(packet).ok,true);
const conflicting=structuredClone(packet);conflicting.budgetByPeriod["2026-01"][0].budget=999;assert.equal(pc.publishBudgetToAtlas(conflicting).ok,false);
assert.equal(pc.publishBudgetToAtlas({...packet,effectiveDate:'2026-08-01'}).ok,false);
assert.equal(pc.publishBudgetToAtlas({...packet,property:{name:'B'}}).ok,false);
assert.equal(pc.publishBudgetToAtlas({...packet,effectiveDate:'2026-09-02'}).ok,true);
const dashboard=fs.readFileSync(dir+'index.html','utf8');
function fn(name,next){return dashboard.slice(dashboard.indexOf('function '+name+'('),dashboard.indexOf('\nfunction '+next+'(',dashboard.indexOf('function '+name+'(')));}
vm.runInContext(fn('summarizeFinancialLedgerRows','getFinancialSummaryForMonth'),pc);
let financial=pc.summarizeFinancialLedgerRows([{gl:'5120',actual:1100,budget:2},{gl:'6461',actual:100}], [{gl:'5120',budget:1000,nature:'income'},{gl:'6461',budget:200,nature:'expense'},{gl:'6520',budget:50,nature:'expense'}]);
assert.equal(financial.noiBudget,750);assert.equal(financial.noiActual,1000);assert.equal(financial.expenseBudget,250);
Object.assign(pc,{atlasBonusCommunitySummary:()=>({occPct:90,budgetOccAttainmentPct:999}),getSelectedDashboardMonthIndex:()=>8,getCommunityCommandApprovedGoal:()=>null});
pc.savedData.A.financialBudgetLedger.investorPacketSources={periods:{[new Date().getFullYear()+'-09']:{noi:{actual:1100,budget:1000},expenses:{actual:200,budget:200}}}};
vm.runInContext(fn('atlasBonusMetricActual','atlasBonusPerformanceRatio'),pc);
assert.equal(pc.atlasBonusMetricActual({communityName:'A'},{metricKey:'noi'}),110);
assert.equal(pc.atlasBonusMetricActual({communityName:'A'},{metricKey:'budget_attainment'}),100);
delete pc.savedData.A.financialBudgetLedger.investorPacketSources;
assert.equal(pc.atlasBonusMetricActual({communityName:'A'},{metricKey:'noi'}),null);
console.log('PASS ATLAS publication/version/community guards, financial budget precedence, budget-only accounts and financial bonus source/missing-data behavior');

const inventoryBefore=JSON.stringify(state);
M.setCatalogInventory([{name:'Test Other Community',totalUnits:320}]);
assert.equal(M.inventoryLabel(state.properties.find(p=>p.name==='Test Other Community')),'320 units');
assert.equal(JSON.stringify(state),inventoryBefore,'inventory context must not rewrite approved budget assumptions');
M.setCatalogInventory([{name:'Test Other Community',totalUnits:null}]);
assert.equal(M.inventoryLabel(state.properties.find(p=>p.name==='Test Other Community')),'Units unavailable');
M.setCatalogInventory([{name:'Test Other Community',totalUnits:0}]);
assert.equal(M.inventoryLabel(state.properties.find(p=>p.name==='Test Other Community')),'0 units');
