import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {fiscalBudgetPeriods,validateBudgetPeriods,calculateLeasingSchedule,calculateStrLeasingSchedule,validateBudgetDriverAdjustment,createBudgetDriverOverride,resolveBudgetDriverAmount,resolveBudgetTolerance,prepareBudgetLeasingDrivers} from '../docs/portfolio-operations-dashboard/features/budget-leasing-drivers.mjs';
import {computeReforecast} from '../docs/portfolio-operations-dashboard/features/reforecast-engine.mjs';

const periods=fiscalBudgetPeriods({year:2026}),stable=periods.map(period=>({period,units:100,beginningOccupiedUnits:100,moveIns:0,moveOuts:0,leasedUnits:100,marketRent:1000,concessions:0,badDebtPercent:0}));
const schedule=calculateLeasingSchedule({periods,monthly:stable});
assert.equal(schedule.issues.length,0);assert.equal(schedule.monthly[0].rentalIncome,100000);assert.equal(schedule.totals.rentalIncome,1200000);assert.equal(schedule.totals.physicalOccupancy,1);assert.equal(schedule.totals.netRentalIncome,1200000);
assert.deepEqual(validateBudgetPeriods(periods,{startMonth:1,annual:true}),[]);
const student=fiscalBudgetPeriods({year:2027,startMonth:8});assert.equal(student[0],'2027-08');assert.equal(student.at(-1),'2028-07');assert.equal(student.length,12);assert.equal(validateBudgetPeriods(student,{startMonth:8,annual:true}).length,0);assert(validateBudgetPeriods([...student].reverse()).length>0);assert.throws(()=>fiscalBudgetPeriods({year:2027,startMonth:0}),/fiscal start/);
const ramp=calculateLeasingSchedule({periods:periods.slice(0,2),monthly:[{period:periods[0],units:100,beginningOccupiedUnits:50,moveIns:10,moveOuts:0,marketRent:1000},{period:periods[1],units:100,moveIns:15,moveOuts:0,marketRent:1000}]});assert.equal(ramp.monthly[0].endingOccupiedUnits,60);assert.equal(ramp.monthly[1].beginningOccupiedUnits,60);assert.equal(ramp.monthly[1].averageOccupiedUnits,67.5);assert.equal(ramp.monthly[1].rentalIncome,67500);assert.equal(ramp.monthly[1].vacancy,-32500);
assert.equal(resolveBudgetDriverAmount({driver:{type:'OCCUPANCY-DRIVEN',rate:20},period:periods[1],leasing:ramp}),1350);
assert.equal(resolveBudgetDriverAmount({driver:{type:'VARIABLE',metric:'moveOuts',rate:180,baseAmount:30},period:periods[1],leasing:ramp}),30);
assert.equal(resolveBudgetDriverAmount({driver:{type:'UNIT-DRIVEN',rate:10},period:periods[1],leasing:ramp}),1000);
assert.equal(resolveBudgetDriverAmount({driver:{type:'UNIT-DRIVEN',rate:.35},period:'2026-01',leasing:{monthly:[{period:'2026-01',units:11.5}]}}),4.03,'Decimal product matches PostgreSQL at the half-cent boundary');
assert.equal(resolveBudgetDriverAmount({driver:{type:'FIXED',amount:0},period:periods[1]}),0);
assert.equal(resolveBudgetDriverAmount({driver:{type:'MANUAL',amount:40},period:periods[1]}),null);
assert.equal(calculateLeasingSchedule({periods:['2026-01'],monthly:[{period:'2026-01',units:0,occupiedUnits:0,marketRent:1000}]}).monthly[0].rentalIncome,0);
assert.equal(calculateLeasingSchedule({periods:['2026-01'],monthly:[{period:'2026-01',units:100,occupiedUnits:null,marketRent:1000}]}).monthly[0].rentalIncome,null);
const inconsistent=calculateLeasingSchedule({periods:['2026-01'],monthly:[{period:'2026-01',units:100,beginningOccupiedUnits:90,moveIns:0,moveOuts:5,endingOccupiedUnits:95}]});assert(inconsistent.issues.some(issue=>issue.code==='leasing_reconciliation'));assert.equal(inconsistent.monthly[0].endingOccupiedUnits,85);

const str=calculateStrLeasingSchedule({periods:['2028-02','2028-03'],beginningUnits:4,monthly:[{period:'2028-02',unitsEntering:6,unitsLeaving:0,blockedNights:10,budgetedOccupancy:.5,adr:200,averageLengthOfStay:2,operatingExpenses:1000,conventionalRentPerUnit:1500},{period:'2028-03',unitsEntering:10,unitsLeaving:0,blockedNights:20,budgetedOccupancy:.75,adr:300,averageLengthOfStay:3,operatingExpenses:2000,conventionalRentPerUnit:1500}]});
assert.equal(str.issues.length,0);assert.equal(str.monthly[0].availableNights,290);assert.equal(str.monthly[0].rentableNights,280);assert.equal(str.monthly[0].bookedNights,140);assert.equal(str.monthly[0].stays,70);assert.equal(str.monthly[0].grossRentalRevenue,28000);assert.equal(str.monthly[0].strNoi,27000);assert.equal(str.monthly[0].strUplift,12000);assert.equal(str.monthly[1].beginningAvailableUnits,10);assert.equal(str.monthly[1].availableNights,620);assert.equal(str.totals.grossRentalRevenue,163000);assert.equal(str.totals.adr,163000/590);assert.equal(str.totals.revpar,163000/910);assert.equal(str.totals.averageLengthOfStay,590/220);assert.equal(str.totals.budgetedOccupancy,590/880);
assert(calculateStrLeasingSchedule({periods:['2026-01'],monthly:[{period:'2026-01',endingUnits:1,blockedNights:50,budgetedOccupancy:1,adr:10,averageLengthOfStay:2}]}).issues.some(issue=>issue.code==='leasing_input_range'));
const warning=validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:145000,drivers:['rent']});assert.equal(warning.warning,true);assert.equal(warning.varianceAmount,45000);assert.equal(warning.variancePercent,45);assert.equal(warning.expectedAmount,100000);
assert.equal(validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:100050}).warning,false);
assert.equal(validateBudgetDriverAdjustment({calculatedAmount:0,manualAmount:1,tolerance:{dollar:100,percent:5}}).warning,true);
assert.equal(validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:101000,tolerance:{dollar:100,percent:5,operator:'and'}}).warning,false);
assert.equal(validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:145000,tolerance:{dollar:null,percent:null}}).warning,false);
assert.equal(validateBudgetDriverAdjustment({calculatedAmount:null,manualAmount:0}).missingAssumptions,true);
const override=createBudgetDriverOverride({reason:'Management Adjustment',userId:'editor',timestamp:'2026-09-29T12:00:00Z',calculatedAmount:100000,manualAmount:145000,affectedDrivers:['rent']});assert.equal(validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:145000,drivers:['rent'],override}).overrideAccepted,true);assert.equal(validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:146000,drivers:['rent'],override}).warning,true);assert.equal(validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:145000,drivers:['changed-rent'],override}).warning,true);assert.throws(()=>createBudgetDriverOverride({...override,reason:'Other',comment:''}),/written explanation/);
assert.deepEqual(resolveBudgetTolerance({default:{dollar:500,percent:3},categories:{Revenue:{percent:5}},accounts:{'5120':{dollar:10}}},{accountCode:'5120',category:'Revenue'}),{dollar:10,percent:5,operator:'or'});

const input={communityId:'property',periods,baseline:{versionId:'baseline',lines:periods.flatMap(period=>[{period,accountCode:'5120',amount:100000},{period,accountCode:'6500',amount:2000}])},actuals:{},registry:{version:'registry',accounts:[{accountCode:'5120',name:'Rent',category:'Revenue',nature:'income',placement:'above_noi'},{accountCode:'6500',name:'Utilities',category:'Utilities',nature:'expense',placement:'above_noi'}]},scenario:{versionId:'version1',driverVersion:'drivers1',drivers:[],overrides:[],leasingSchedule:{schemaVersion:1,monthly:stable},accountDrivers:[{id:'rent',accountCode:'5120',type:'OCCUPANCY-DRIVEN',metric:'rentalIncome'},{id:'utilities',accountCode:'6500',type:'OCCUPANCY-DRIVEN',rate:20}]}};
let result=computeReforecast(input);assert.equal(result.totals.reforecast.revenue,1200000);assert.equal(result.totals.reforecast.opex,24000);assert.equal(result.driverValidation.reconciled,true);assert.equal(result.leasingSchedule.totals.physicalOccupancy,1);assert.equal(result.lines[0].expectedDriverAmount,100000);
const manual=structuredClone(input);manual.scenario.overrides=[{period:periods[0],accountCode:'5120',amount:145000}];result=computeReforecast(manual);assert.equal(result.driverValidation.warnings.length,1);assert.equal(result.lines[0].forecast,145000);assert.equal(result.lines[0].driverCalculatedAmount,100000);assert.equal(result.status,'action_required');manual.scenario.overrides[0].driverOverride=override;result=computeReforecast(manual);assert.equal(result.driverValidation.warnings.length,0);assert.equal(result.driverValidation.overrides.length,1);
manual.scenario.overrides.push({period:periods[0],accountCode:'6500',amount:4000});result=computeReforecast(manual);assert.equal(result.driverValidation.warnings.length,1);assert.equal(result.driverValidation.warnings[0].accountCode,'6500');assert.equal(result.driverValidation.warnings[0].expectedAmount,2000);
const mixed=structuredClone(input);mixed.scenario.strBudgetApplications=[{programmeId:'established-str',cells:[{period:periods[0],accountCode:'5120',appliedDelta:20000}]}];mixed.scenario.overrides=[{period:periods[0],accountCode:'5120',amount:120000,source:{kind:'shared_str_programme'}}];const mixedResult=computeReforecast(mixed);assert.equal(mixedResult.driverValidation.warnings.length,0);assert.equal(mixedResult.lines[0].driverCalculatedAmount,120000,'Verified STR contributions are included with the conventional driver expectation');
const strOnly=structuredClone(input);strOnly.scenario.accountDrivers=[];strOnly.scenario.strBudgetApplications=[{programmeId:'str-expense',cells:[{period:periods[0],accountCode:'6500',combinedAmount:3000,appliedDelta:1000}]}];strOnly.scenario.overrides=[{period:periods[0],accountCode:'6500',amount:5000}];const strConflict=computeReforecast(strOnly);assert.equal(strConflict.driverValidation.warnings[0].expectedAmount,3000);assert.deepEqual(strConflict.driverValidation.warnings[0].affectedDrivers,['str-programme-str-expense']);
const strFingerprint=structuredClone(strOnly);delete strFingerprint.scenario.leasingSchedule;const earlier=computeReforecast(strFingerprint);strFingerprint.scenario.strBudgetApplications[0].cells[0].combinedAmount=4000;assert.notEqual(computeReforecast(strFingerprint).fingerprint,earlier.fingerprint,'STR-only driver expectation and validation are included in retained fingerprint');
const lockedStr=structuredClone(strFingerprint);lockedStr.lockedPeriods=[periods[0]];const lockedStrResult=computeReforecast(lockedStr);assert(lockedStrResult.lines.filter(row=>row.period===periods[0]).every(row=>!Object.hasOwn(row,'driverCalculatedAmount')),'No STR assumption is attached to immutable actual periods');
const compiled=prepareBudgetLeasingDrivers(input);const legacy=computeReforecast({...input,scenario:{...compiled.scenario,leasingSchedule:undefined,accountDrivers:undefined}});assert.equal(legacy.totals.reforecast.revenue,1200000);assert.equal(legacy.totals.reforecast.opex,24000);assert.equal(compiled.scenario.drivers.length,24);assert.equal(prepareBudgetLeasingDrivers({...input,scenario:compiled.scenario}).scenario.drivers.length,24,'Compiling again does not double-apply amounts');
const cycle=prepareBudgetLeasingDrivers({...input,scenario:{...input.scenario,accountDrivers:[{accountCode:'5120',type:'REVENUE-DRIVEN',baseAccountCode:'6500',rate:1},{accountCode:'6500',type:'REVENUE-DRIVEN',baseAccountCode:'5120',rate:1}]}});assert(cycle.issues.some(issue=>issue.code==='driver_dependency_cycle'));

const html=fs.readFileSync('docs/portfolio-operations-dashboard/RISE-Budget-Builder.html','utf8'),start=html.indexOf('var RBB ='),end=html.indexOf('})(RBB);',html.indexOf('R.buildState ='))+'})(RBB);'.length,context=vm.createContext({console,Date,Map,Set,window:{},setTimeout:()=>0});vm.runInContext(html.slice(start,end),context);const R=context.RBB,state=R.buildState(),property=state.properties.find(p=>p.id==='DORO'),group=property.units.find(row=>row.units>=2),cfg={propertyId:property.id,name:'Schedule acceptance',unitPicks:[{groupId:group.id,units:2}],unitRamp:{2026:Array(12).fill(2),2027:Array(12).fill(2)},adr:200,occupancy:.5,alos:2,blockedPct:0,curve:'flat'};
const preview=R.strBuilder.preview(state,cfg,2026);assert.equal(preview.leasingSchedule.monthly[0].availableNights,62);assert.equal(preview.leasingSchedule.monthly[0].bookedNights,preview.booked[0]);assert.equal(preview.leasingSchedule.monthly[0].grossRentalRevenue,preview.gross[0]);assert.equal(preview.leasingSchedule.monthly[0].strNoi,preview.strNoi[0]);assert.equal(preview.leasingSchedule.totals.adr,preview.annual.adr);
const longer=R.strBuilder.preview(state,{...cfg,alosMode:'monthly',alosMonthly:{2026:Array(12).fill(4)}},2026);assert.equal(longer.stays[0],preview.stays[0]/2);assert.equal(longer.cleaning[0],preview.cleaning[0]/2);assert.equal(longer.booked[0],preview.booked[0]);
property.fiscalYearBegins='Aug';const fiscal=R.strBuilder.fiscalLeasingSchedule(state,cfg,2026);assert.equal(fiscal.periods[0],'2026-08');assert.equal(fiscal.periods[11],'2027-07');assert.equal(fiscal.monthly[5].beginningAvailableUnits,fiscal.monthly[4].endingUnits);
const rollover=R.strBuilder.preview(state,cfg,2027);assert.equal(rollover.leasingSchedule.monthly[0].beginningAvailableUnits,2);assert.equal(rollover.leasingSchedule.monthly[0].unitsEntering,0);assert.equal(rollover.furnish[0],0,'January does not furnish retained December units again');assert.equal(rollover.listingSetup[0],0,'January does not repeat listing setup for retained units');
const reducedCfg={...cfg,unitRamp:{2026:Array(12).fill(2),2027:[1,...Array(11).fill(2)]},furnishCapexPerUnit:10000,listingSetupPerUnit:500},takeback=R.strBuilder.preview(state,reducedCfg,2027);assert.equal(takeback.leasingSchedule.monthly[0].unitsLeaving,1);assert.equal(takeback.furnish[0],0);assert.equal(takeback.leasingSchedule.monthly[1].unitsEntering,1);assert.equal(takeback.furnish[1],10000);assert.equal(takeback.listingSetup[1],500);
const declared=R.strBuilder.preview(state,{...cfg,beginningStrUnits:{2027:1},furnishCapexPerUnit:10000},2027);assert.equal(declared.leasingSchedule.monthly[0].beginningAvailableUnits,1);assert.equal(declared.leasingSchedule.monthly[0].unitsEntering,1);assert.equal(declared.furnish[0],10000,'An explicit reviewed opening roster controls both the schedule and startup costs');
assert.equal(fiscal.monthly.find(row=>row.period==='2027-01').unitsEntering,rollover.leasingSchedule.monthly[0].unitsEntering,'The fiscal-year schedule and source startup driver agree across January');
const appliedProgramme=R.strBuilder.apply(state,cfg,[2026,2027]),retained=appliedProgramme.programme.supportingSchedules[2026].leasingSchedule;
assert.equal(appliedProgramme.programme.supportingSchedules[2027].leasingSchedule.monthly[0].beginningAvailableUnits,retained.monthly.at(-1).endingUnits,'Retained non-calendar budgets carry STR opening units across January');assert.equal(appliedProgramme.programme.supportingSchedules[2027].leasingSchedule.monthly[0].unitsEntering,0);assert.equal(appliedProgramme.lines.find(line=>line.gl==='1504').yearData[2027][0],0);assert.equal(appliedProgramme.lines.find(line=>line.gl==='6205').yearData[2027][0],0);
for(const [index,row] of retained.monthly.entries()){
 const cents=predicate=>appliedProgramme.lines.filter(predicate).reduce((sum,line)=>sum+Math.round(line.yearData[2026][index]*100),0),expense=cents(line=>line.nature==='expense'),income=cents(line=>['income','contra_income'].includes(line.nature)),displaced=-cents(line=>line.displacement);
 assert.equal(row.operatingExpenses,expense/100);assert.equal(row.budgetedRevenue,(income+displaced)/100);assert.equal(row.strNoi,(income+displaced-expense)/100);assert.equal(row.strUplift,(income-expense)/100);assert.equal(row.driverCalculatedFinancials.operatingExpenses,appliedProgramme.previews[2026].totalStrExpense[index]);
}
assert.equal(retained.totals.operatingExpenses,retained.monthly.reduce((sum,row)=>sum+Math.round(row.operatingExpenses*100),0)/100,'Retained annual totals sum exact materialized cents');
assert(html.includes("id:'leasing',     label:'Leasing schedule'"));assert(html.includes('A.strScheduleCell'));assert(html.includes('programme.supportingSchedules[y]'));
console.log('PASS A/B/C/F/G/K/L conventional/stabilized/lease-up, student fiscal order and leap year, schedule-derived income and expenses, materiality and audited overrides, exact compiled legacy driver parity, STR schedule/ramp/nights/rates/stays/NOI and weighted annual metrics.');

for(const [index,script] of [...html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)].entries())if(!/type=["'](?:module|application\/json)/.test(script[1])&&script[2].trim())new vm.Script(script[2],{filename:'RISE-Budget-Builder.inline-'+index+'.js'});
console.log('PASS every inline legacy Builder script parses, including the new editable STR leasing tab.');
