const assert=require('node:assert/strict'),fs=require('node:fs'),{fixture}=require('./financial-intake-fixture.cjs');
(async()=>{const {db,cid,other,signIn}=await fixture();const migration=name=>fs.readFileSync(__dirname+'/../supabase/migrations/'+name,'utf8');try{
 await db.exec('reset role');
 await db.exec("alter table atlas_communities add column version integer default 1;alter table atlas_communities add column market text;alter table atlas_communities add column property_type text;alter table atlas_communities add column if not exists first_expected_financial_period text;update atlas_communities set display_name='RISE Doro',canonical_name='rise doro',market='Florida',property_type='High Rise' where community_id='"+cid+"';update atlas_communities set display_name='The Preserve at Tech',canonical_name='the preserve at tech',market='Student Housing' where community_id='"+other+"';");
 for(const file of ['20260924121641_planning_cell_workbook_integrity_governance.sql','20260924121647_immutable_workbook_audits_and_monthly_governance.sql','20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql','20260925071533_reforecast_request_identity_consistency.sql','20260925161938_governed_month_end_operational_review.sql','20260925162050_budget_governed_draft_investor_lifecycle.sql','20260925162055_governed_community_budget_calendar.sql'])await db.exec(migration(file));
 await signIn(1);const calendar=async id=>(await db.query('select atlas_read_budget_calendar($1) c',[id])).rows[0].c;
 assert.equal((await calendar(cid)).startMonth,1);assert.equal((await calendar(other)).startMonth,8);
 await db.exec('reset role');await db.exec("alter table atlas_communities add column if not exists review_status text;alter table atlas_communities add column if not exists review_flags jsonb;update atlas_communities set budget_calendar=null,review_status='review_required',review_flags='[\"market_inferred\"]'::jsonb where community_id='"+other+"'");
 await signIn(1);assert.equal((await calendar(other)).verified,false,'inferred classifications cannot silently govern a calendar');
 const verified=(await db.query('select atlas_set_budget_calendar($1,$2,$3,$4) c',[other,2,'Student Housing','Owner verified financial classification'])).rows[0].c;
 assert.equal(verified.startMonth,8);assert.equal(verified.verified,true);
 await db.exec('reset role');const alias=(await db.query("select community_id from atlas_community_aliases where alias='Ruston' and active")).rows;assert.deepEqual(alias,[{community_id:other}]);
 assert.equal((await db.query('select count(*) n from atlas_communities')).rows[0].n,2,'Identity migration never creates a duplicate community');
 await signIn(1);assert.deepEqual((await db.query('select atlas_month_end_queue($1,$2) q',[[cid,other],2026])).rows[0].q,[]);
 const columns=(await db.query("select routine_name from information_schema.routines where routine_schema='public' and routine_name in ('atlas_save_reforecast_scenario','atlas_reforecast_effective_baseline','atlas_read_month_end_review','atlas_close_financial_review_governed','atlas_read_finance','atlas_read_budget_calendar')")).rows;assert.equal(columns.length,6);
 await db.exec('reset role');const rows=(await db.query("select relname,relrowsecurity from pg_class where relname in ('atlas_month_end_attestations','atlas_month_end_decisions','atlas_actual_period_events','atlas_budget_workflow_audit','atlas_budget_calendar_events')")).rows;assert.equal(rows.length,5);assert(rows.every(r=>r.relrowsecurity));
 console.log('PASS combined actual intake, workbook, reforecast lifecycle, month-end and verified-calendar migrations; Doro January, Preserve August, canonical Ruston alias, no duplicate community, queue and RLS installation.');
 }finally{await db.close();}
})().catch(error=>{console.error(error.message,error.where||'');process.exitCode=1;});
