import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),root=path.resolve('docs/portfolio-operations-dashboard');
const html=`<!doctype html><html><body><script type="module">
import {openBudgetLeasingDialog} from '/features/budget-leasing-ui.mjs';
import {budgetDriverWarningDialog} from '/features/budget-driver-warning-ui.mjs';
import {computeReforecast} from '/features/reforecast-engine.mjs';
import {validateBudgetDriverAdjustment} from '/features/budget-leasing-drivers.mjs';
const periods=['2026-08','2026-09'];window.source={communityId:'community',periods,baseline:{versionId:'original',leasing:periods.map(period=>({period,units:100,beginningOccupiedUnits:100,moveIns:0,moveOuts:0,endingOccupiedUnits:100,marketRent:1000,concessionPerMoveIn:25,assumptionReference:'Retained operating source'})),lines:periods.flatMap(period=>[{period,accountCode:'5120',amount:100000},{period,accountCode:'6500',amount:2000}])},actuals:{},registry:{version:'mapping',accounts:[{accountCode:'5120',name:'Rent',nature:'income',category:'Revenue',placement:'above_noi'},{accountCode:'6500',name:'Utilities',nature:'expense',category:'Utilities',placement:'above_noi'}]}};
window.scenario={name:'Student test',periods,versionId:'draft',driverVersion:'drivers',ownerId:'editor',drivers:[],overrides:[]};window.snapshot=computeReforecast({...source,scenario});
window.dialog=title=>{const el=document.createElement('dialog');el.innerHTML='<h2>'+title+'</h2><div data-body></div><p data-status role="status"></p>';document.body.append(el);el.onclose=()=>el.remove();el.showModal();return el;};
openBudgetLeasingDialog({scenario,source,snapshot,actor:'editor',dialog,onSave:async value=>window.saved=value});
window.openWarning=()=>budgetDriverWarningDialog({check:validateBudgetDriverAdjustment({calculatedAmount:100000,manualAmount:145000,drivers:['rent']}),actor:'editor',dialog,onReturn:()=>window.returned=true,onAdjust:()=>window.adjusted=true,onOverride:value=>window.override=value});
</script></body></html>`;
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('content-type','text/html');res.end(html);return;}const filename=path.resolve(root,'.'+url.pathname);if(!filename.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('content-type','application/javascript');res.end(await fs.readFile(filename));}catch(error){res.writeHead(500).end(error.message);}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));
try{
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('[data-add-account-link]').click();let row=page.locator('[data-driver-link="0"]');await row.locator('[data-link="accountCode"]').selectOption('5120');await row.locator('[data-link="metric"]').selectOption('rentalIncome');await page.locator('[data-add-account-link]').click();row=page.locator('[data-driver-link="1"]');await row.locator('[data-link="accountCode"]').selectOption('6500');await row.locator('[data-link="rate"]').fill('20');await page.locator('[data-leasing-reason]').fill('Reviewed occupancy and rental assumptions');await page.locator('[data-leasing-calculate]').click();assert.match(await page.locator('[data-leasing-preview]').innerText(),/4 linked monthly amounts calculated/);await page.locator('[data-leasing-save]').click();await page.waitForFunction(()=>window.saved);const saved=await page.evaluate(()=>window.saved);assert.equal(saved.drivers.length,4);assert.equal(saved.leasingSchedule.monthly[0].concessionPerMoveIn,25);assert.equal(saved.leasingSchedule.monthly[0].assumptionReference,'Retained operating source');assert.equal(saved.drivers.find(row=>row.accountCodes[0]==='5120').value,100000);assert.equal(saved.drivers.find(row=>row.accountCodes[0]==='6500').value,2000);assert(!Object.hasOwn(saved.accountDrivers[0],'streamId'));assert(!Object.hasOwn(saved.accountDrivers[0],'baseAccountCode'));
 await page.evaluate(()=>window.openWarning());assert.match(await page.locator('dialog').innerText(),/145,000/);await page.locator('[data-override]').click();assert.match(await page.locator('[data-status]').innerText(),/override reason/);await page.locator('[data-reason]').selectOption('Other');await page.locator('[data-override]').click();assert.match(await page.locator('[data-status]').innerText(),/written explanation/);await page.locator('[data-comment]').fill('Known contract starts after the retained leasing forecast');await page.locator('[data-override]').click();await page.waitForFunction(()=>window.override);const override=await page.evaluate(()=>window.override);assert.equal(override.userId,'editor');assert.equal(override.reason,'Other');assert.equal(override.manualAmount,145000);assert.equal(override.calculatedAmount,100000);assert(Number.isFinite(Date.parse(override.timestamp)));
 await page.evaluate(()=>window.openWarning());await page.locator('dialog[open] [data-return]').click();assert.equal(await page.evaluate(()=>window.returned),true);await page.evaluate(()=>window.openWarning());await page.locator('dialog[open] [data-adjust]').click();assert.equal(await page.evaluate(()=>window.adjusted),true);assert.deepEqual(errors,[]);
 console.log('PASS browser: fiscal leasing rows, account links, recalculation preview/save, blank optional links omitted, BUDGET DRIVER WARNING amounts and all three actions, required Other explanation, user/timestamp audit.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
