import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),cid='10000000-0000-0000-0000-000000000001';
const server=spawn(process.execPath,['tools/reforecast-harness-server.cjs'],{env:{...process.env,PORT:'0',ATLAS_BUDGET_DRIVER_TEST:'1',ATLAS_GOVERNED_WORKFLOW_TEST:'1'},stdio:['ignore','pipe','pipe']});let output='',port;
await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Fixture startup failed '+output)),20000);server.once('exit',code=>{clearTimeout(timer);reject(Error('Fixture exited '+code+': '+output));});for(const stream of [server.stdout,server.stderr])stream.on('data',chunk=>{output+=chunk;const match=output.match(/acceptance http:\/\/127\.0\.0\.1:(\d+)/);if(match){port=match[1];clearTimeout(timer);resolve();}});});
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1700,height:1100}}),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));const idle=()=>page.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled);
try{
 await page.route('**/__api/rpc/atlas_month_end_queue',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto('http://127.0.0.1:'+port);await page.locator('[data-community]').selectOption(cid);await idle();await page.locator('[data-new]').click();await page.locator('[data-name]').fill('Operating driver browser acceptance');await page.locator('[data-last]').fill('2026-03');await page.locator('[data-last]').dispatchEvent('change');await page.waitForFunction(()=>!document.querySelector('[data-create]')?.disabled);await page.locator('dialog [data-calendar-confirm]').check();await page.locator('[data-create]').click();await page.locator('[data-budget-leasing]').click();
 for(const period of ['2026-02','2026-03'])for(const [field,value]of Object.entries({units:100,beginningOccupiedUnits:100,moveIns:0,moveOuts:0,endingOccupiedUnits:100,marketRent:1000,rentGrowth:0,lossToLeasePercent:0,concessions:0,badDebtPercent:0}))await page.locator('[data-leasing-period="'+period+'"] [data-leasing-field="'+field+'"]').fill(String(value));
 await page.locator('[data-add-account-link]').click();await page.locator('[data-link="accountCode"]').selectOption('5120');await page.locator('[data-link="metric"]').selectOption('rentalIncome');await page.locator('[data-leasing-reason]').fill('Reviewed full occupancy and monthly market rent');await page.locator('[data-leasing-save]').click();await page.locator('dialog[open]').waitFor({state:'detached'});
 const cell='[data-gl-cell][data-period="2026-02"][data-code="5120"]';await page.waitForFunction(()=>document.querySelector('[data-gl-cell][data-period="2026-02"][data-code="5120"]')?.value==='100000');await page.locator(cell).fill('145000');await page.locator(cell).dispatchEvent('change');await page.locator('dialog[open] [data-override]').waitFor();assert.match(await page.locator('dialog[open]').innerText(),/100,000/);assert.match(await page.locator('dialog[open]').innerText(),/145,000/);await page.locator('dialog[open] [data-reason]').selectOption('Other');await page.locator('dialog[open] [data-override]').click();assert.match(await page.locator('dialog[open] [data-status]').innerText(),/written explanation/);await page.locator('dialog[open] [data-comment]').fill('Reviewed signed rent commitment outside current lease assumptions');await page.locator('dialog[open] [data-override]').click();await page.locator('dialog[open]').waitFor({state:'detached'});await page.waitForFunction(()=>document.querySelector('[data-save-status]')?.textContent.startsWith('Saved and verified'));
 const records=await page.evaluate(async cid=>ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})}),cid),record=records.find(row=>row.revision.payload.name==='Operating driver browser acceptance');assert(record);assert.equal(record.snapshot.lines.find(row=>row.period==='2026-02'&&row.accountCode==='5120').forecast,145000);assert.equal(record.snapshot.driverValidation.warnings.length,0);assert.equal(record.snapshot.driverValidation.overrides.length,1);assert.equal(record.revision.payload.overrides[0].driverOverride.userId,'00000000-0000-0000-0000-000000000001');assert.equal(record.revision.payload.overrides[0].driverOverride.reason,'Other');assert.equal(record.snapshot.leasingSchedule.monthly[0].rentalIncome,100000);assert.deepEqual(errors,[]);
 console.log('PASS production Budget Builder browser + SQL fixture: configure leasing schedule and GL link, generate $100,000 supported rent, edit to $145,000, require Other explanation, persist authenticated override and keep calculated source unchanged.');
}catch(error){console.error(await page.locator('dialog [data-status],[role=alert],[data-save-status]').allTextContents());throw error;}finally{await browser.close();server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}
