const {PGlite}=require('@electric-sql/pglite'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{
 const db=new PGlite();const sql=name=>fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/'+name+'.sql','utf8');
 await db.exec(`create role service_role bypassrls;create role anon;create role authenticated;create schema auth;create schema atlas_private;
 create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth,atlas_private to authenticated;grant execute on function auth.uid() to authenticated;
 create table atlas_user_profiles(user_id uuid,role text,status text,locked_tab_ids text[],locked_page_keys text[],allowed_community_ids uuid[]);
 create table atlas_communities(community_id uuid primary key,display_name text,canonical_name text,status text,deleted_at timestamptz);
 create table atlas_community_aliases(community_id uuid,alias text,active boolean,source_module text);
 create function atlas_can_access_community(id uuid) returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from atlas_user_profiles where user_id=auth.uid() and status='active' and (role='admin' or id=any(allowed_community_ids))) $$;
 insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');
 insert into atlas_user_profiles values('00000000-0000-0000-0000-000000000001','admin','active','{}','{}','{}'),('00000000-0000-0000-0000-000000000002','regional','active','{}','{}','{10000000-0000-0000-0000-000000000001}'),('00000000-0000-0000-0000-000000000003','community_manager','active','{}','{}','{10000000-0000-0000-0000-000000000002}');
 insert into atlas_communities values('10000000-0000-0000-0000-000000000001','Doro','doro','active',null),('10000000-0000-0000-0000-000000000002','Other','other','active',null);`);
 for(const file of ['financial-package-review','financial-comparisons','financial-close','financial-close-cash-flow','financial-close-source-lineage','community-command','community-command-finance','community-command-delivery','community-command-plan-summary','community-command-report-ytd','financial-admin-publication','canonical-finance-reporting','canonical-finance-reporting-indexes','canonical-finance-budget-projection-performance'])await db.exec(sql(file));
 const cid='10000000-0000-0000-0000-000000000001';
 const signIn=async n=>db.exec(`reset role;set request.jwt.claim.sub='00000000-0000-0000-0000-${String(n).padStart(12,'0')}';set role authenticated;`);
 let sequence=0;
 const values=n=>({actual:n,budget:n,ytdActual:n,ytdBudget:n,annualBudget:n});
 const line=(kind,glCode,accountName,n)=>({kind,glCode,accountName,values:values(n),source:{page:3}});
 const certificate=(period,income=100,expense=40)=>({schemaVersion:1,sourceFile:'test-approved.pdf',sourceHash:(++sequence).toString(16).padStart(64,'0'),metadata:{sourceProperty:'Doro',period,basis:'accrual'},exceptions:[],rows:[line('posting','5120','GPR',income),line('control',null,'Net Rental Income',income),line('control',null,'Total Income',income),line('posting','6461','Operating Expense',expense),line('control',null,'Net Operating Income',income-expense),line('control',null,'Net Cash Flow',income-expense)]});
 const save=async c=>(await db.query('select * from atlas_save_financial_package_review($1,$2)',[cid,c])).rows[0];
 const close=async(r,expected=null)=>(await db.query('select * from atlas_close_financial_review($1,$2,$3,true)',[r.review_id,expected,'Accounting approved test package'])).rows[0];
 const read=async p=>(await db.query('select * from atlas_read_finance($1,$2)',[[cid],[p]])).rows[0];
 await signIn(1);
 const aug=await close(await save(certificate('2026-08')));
 let s=(await read('2026-08')).summary;
 assert.equal(s.gpr.actual,100);assert.equal(s.gpr.budget,null);assert.equal(s.cashFlow.actual,60);assert.equal(s.completeYtd,false);assert.equal(s.latestClosedPeriod,'2026-08');assert.equal(s.ytdGpr.actual,null);
 const first=(await db.query('select * from atlas_command_financial_summaries where community_id=$1 and period_key=$2',[cid,'2026-08'])).rows[0];
 assert.equal(first.summary.actualCloseVersion,aug.version_id,'close projects without another browser action');
 assert.equal(first.summary.assets.actual,null);assert.match(first.summary.assets.label,/balance sheet/);
 const budget={communityId:cid,year:2026,fiscalYear:2026,fiscalStartMonth:1,scenarioId:'approved',scenarioVersion:'approved-v1',effectiveDate:'2026-01-01',sourceFile:'test-approved-budget.xlsx',sourceHash:'a'.repeat(64),approvedLocked:true,reviewConfirmed:true,registryVersion:'atlas-finance-v1',occupancyPct:Array(12).fill(null),rows:[{glCode:'5120',monthly:Array(12).fill(100)},{glCode:'6461',monthly:Array(12).fill(50)}],metricMappings:{gpr:[{glCode:'5120',factor:1}],revenue:[{glCode:'5120',factor:1}],expenses:[{glCode:'6461',factor:1}],noi:[{glCode:'5120',factor:1},{glCode:'6461',factor:-1}],cashFlow:[{glCode:'5120',factor:1},{glCode:'6461',factor:-1}]}};
 const approve=async b=>(await db.query('select * from atlas_approve_original_budget($1,$2)',[cid,b])).rows[0];
 const b=await approve(budget);assert.equal((await approve(budget)).version_id,b.version_id);
 s=(await read('2026-08')).summary;assert.equal(s.gpr.budget,100);assert.equal(s.expenses.variance,10);assert.equal(s.cashFlow.budget,50);assert.equal(s.budgetVersion,b.version_id);
 await assert.rejects(()=>approve({...budget,scenarioVersion:'changed'}),/immutable/);
 await assert.rejects(()=>approve({...budget,rows:[{glCode:'5120',monthly:Array(12).fill(null)}]}),/missing is not zero/);
 await assert.rejects(()=>db.query('update atlas_approved_budget_versions set scenario_id=$1',['evil']),/permission denied/);
 const beforeCount=(await db.query('select count(*)::int n from atlas_command_financial_publications')).rows[0].n;
 const retry=await close(await save(certificate('2026-08')));assert.equal(retry.version_id,aug.version_id);assert.equal((await db.query('select count(*)::int n from atlas_command_financial_publications')).rows[0].n,beforeCount);
 const replacement=await save(certificate('2026-08',120,0));await assert.rejects(()=>close(replacement),/another session/);
 const corrected=await close(replacement,aug.version_id);assert.equal(corrected.previous_version_id,aug.version_id);
 s=(await read('2026-08')).summary;assert.equal(s.expenses.actual,0);assert.equal(s.gpr.actual,120);assert.equal(s.actualCloseVersion,corrected.version_id);
 assert.equal((await db.query('select metrics from atlas_financial_close_versions where version_id=$1',[aug.version_id])).rows[0].metrics.grossPotentialRent,100);
 for(let m=2;m<8;m++)await close(await save(certificate(`2026-${String(m).padStart(2,'0')}`,-10,0)));
 s=(await read('2026-08')).summary;assert.deepEqual(s.missingPeriods,['2026-01']);assert.equal(s.latestClosedPeriod,'2026-08');assert.equal(s.ytdGpr.actual,null);
 const jan=await close(await save(certificate('2026-01',0,0)));s=(await read('2026-08')).summary;assert.equal(s.completeYtd,true);assert.equal(s.ytdGpr.actual,60);assert.equal(s.ytdGpr.budget,800);
 await close(await save(certificate('2026-01',5,0)),jan.version_id);s=(await read('2026-08')).summary;assert.equal(s.ytdGpr.actual,65,'earlier replacements recalculate later YTD');
 assert.equal((await db.query('select summary from atlas_command_financial_summaries where period_key=$1',['2026-08'])).rows[0].summary.ytdGpr.actual,65);
 // A transaction failure must roll back both close head and projection.
 await db.exec(`reset role;create function atlas_private.fail_projection() returns trigger language plpgsql as $$ begin raise exception 'test projection failure';end;$$;create trigger fail_projection before update on atlas_command_financial_summaries for each row execute function atlas_private.fail_projection();`);await signIn(1);
 const fails=await save(certificate('2026-08',130,0));await assert.rejects(()=>close(fails,corrected.version_id),/test projection failure/);assert.equal((await read('2026-08')).summary.actualCloseVersion,corrected.version_id);
 await db.exec('reset role;drop trigger fail_projection on atlas_command_financial_summaries');await signIn(1);
 const current=(await db.query("select to_char(current_date,'YYYY-MM') p")).rows[0].p;await assert.rejects(()=>save(certificate(current)).then(r=>close(r)),/completed accounting month/);
 const plan=(await db.query('select * from atlas_save_community_plan($1,$2,0,$3)',[cid,'2026-08',{tasks:[]}])).rows[0];
 const report=(await db.query('select * from atlas_generate_community_plan_report($1,1,$2,null)',[plan.plan_id,'Synthetic acceptance'])).rows[0];assert.equal(report.snapshot.financial.summary.actualCloseVersion,corrected.version_id);assert.equal(report.snapshot.financial.summary.budgetVersion,b.version_id);

 await assert.rejects(()=>approve({...budget,effectiveDate:'2099-01-01'}),/Future-effective/);
 const withoutCash=certificate('2026-06',100,40);withoutCash.rows.pop();
 const oldJune=(await read('2026-06')).summary.actualCloseVersion;await close(await save(withoutCash),oldJune);
 assert.equal((await read('2026-06')).summary.cashFlow.actual,null,'an absent cash control must not become zero');
 const other='10000000-0000-0000-0000-000000000002';
 const segment=(months)=>({coverage:months,rows:budget.rows.map(r=>({...r,monthly:r.monthly.map((v,m)=>months.includes(m)?v:null)}))});
 const studentBudget={...budget,communityId:other,fiscalStartMonth:8,year:2025,fiscalYear:2026,...segment([7,8,9,10,11])};
 await db.query('select * from atlas_approve_original_budget($1,$2)',[other,studentBudget]);
 await db.query('select * from atlas_approve_original_budget($1,$2)',[other,{...studentBudget,year:2026,...segment([0,1,2,3,4,5,6])}]);
 await db.query('select * from atlas_approve_original_budget($1,$2)',[other,{...studentBudget,year:2026,fiscalYear:2027}]);
 for(const period of ['2025-08','2025-09','2025-10','2025-11','2025-12','2026-01']){
  const c=certificate(period);c.metadata.sourceProperty='Other';
  const r=(await db.query('select * from atlas_save_financial_package_review($1,$2)',[other,c])).rows[0];await close(r);
 }
 const student=(await db.query('select * from atlas_read_finance($1,$2)',[[other],['2026-01']])).rows[0].summary;
 assert.equal(student.fiscalStartPeriod,'2025-08');assert.equal(student.completeYtd,true);assert.equal(student.ytdGpr.actual,600);assert.equal(student.ytdGpr.budget,600);assert.equal(Object.keys(student.budgetVersions).length,6);
 // Legacy uploaded summaries cannot appear as canonical finance in a new report.
 const originalReport=report.snapshot.financial.summary.actualCloseVersion;
 const afterReplacement=(await db.query('select * from atlas_generate_community_plan_report($1,1,$2,null)',[plan.plan_id,'After historical correction'])).rows[0];
 assert.equal(report.snapshot.financial.summary.actualCloseVersion,originalReport);assert.equal(afterReplacement.snapshot.reportSchemaVersion,3);
 await signIn(2);s=(await read('2026-08')).summary;assert.equal(s.gpr.actual,120);assert.equal(s.gpr.budget,100,'clean independent authorized user reads same budget');await assert.rejects(()=>approve(budget),/Only an active/);await assert.rejects(()=>close(replacement),/Only an active/);
 await signIn(3);assert.equal(await read('2026-08'),undefined);assert.equal((await db.query('select * from atlas_approved_budget_versions where community_id=$1',[cid])).rows.length,0);
 await assert.rejects(()=>db.query('select atlas_private.project_finance($1)',[cid]),/permission denied/);
 await db.exec('reset role;set role anon');await assert.rejects(()=>read('2026-08'),/permission denied/);
 await db.exec('reset role');
 const largeCid='10000000-0000-0000-0000-000000000003';
 await db.query("insert into atlas_communities values($1,'Large budget','large','active',null)",[largeCid]);
 await signIn(1);
 const largeRows=[{glCode:'5120',monthly:Array(12).fill(10000)},...Array.from({length:287},(_,i)=>({glCode:String(7000+i),monthly:Array(12).fill(i===0?0:i===1?-5:10)}))];
 const expenseScope=largeRows.slice(1).map(r=>({glCode:r.glCode,factor:1}));
 const large={...budget,communityId:largeCid,rows:largeRows,metricMappings:{gpr:budget.metricMappings.gpr,revenue:budget.metricMappings.revenue,expenses:expenseScope,noi:[...budget.metricMappings.revenue,...expenseScope.map(p=>({...p,factor:-1}))],cashFlow:[...budget.metricMappings.revenue,...expenseScope.map(p=>({...p,factor:-1}))]}};
 await db.query('select * from atlas_approve_original_budget($1,$2)',[largeCid,large]);
 const largeRead=(await db.query('select * from atlas_read_finance($1,$2)',[[largeCid],['2026-12']])).rows[0].summary;
 assert.equal(largeRead.expenses.budget,2845);assert.equal(largeRead.noi.budget,7155);assert.equal(largeRead.ytd.expenses.budget,34140);assert.equal(largeRead.gpr.actual,null);
 await db.exec('reset role');
 const missing=structuredClone(large);missing.rows[2].monthly[0]=null;
 assert.equal((await db.query("select atlas_private.finance_budget_metric($1,'expenses',0) as amount",[missing])).rows[0].amount,null);
 assert.equal((await db.query("select atlas_private.finance_budget_metric($1,'unmapped',0) as amount",[large])).rows[0].amount,null);
 console.log('PASS full-year 288-GL approval and publication, complete mapped sums, missing amounts and absent mappings');
 await db.close();console.log('PASS atomic close projection, shared original budget, missing/signed/zero values, fiscal coverage, replacements, retries, reports, role isolation and clean-session readback');
})().catch(e=>{console.error(e);process.exitCode=1;});
