const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('docs/portfolio-operations-dashboard/index.html','utf8');
const finance=fs.readFileSync('docs/portfolio-operations-dashboard/financial-accountability.html','utf8');
const F=require('../docs/portfolio-operations-dashboard/financial-publication.js');
const P=require('../docs/portfolio-operations-dashboard/property-intelligence.js');
const c={console,Date,Map,Set,window:{AtlasFinancialPublication:F},FULL_MONTHS:['January','February','March','April','May','June','July','August','September','October','November','December'],MONTHS:[],getProp:()=>({name:'Doro'}),getReportHubMonthIndex:()=>8,matchPropertyName:n=>['Doro','Bartram'].includes(n)?n:null,historicalImportTarget:{community:'Bartram'},normalizeSavedCommunityRecord:(n,r)=>r};
vm.createContext(c);
for(const f of html.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm))vm.runInContext(f[0],c);
Object.assign(c,{getProp:()=>({name:'Doro'}),getReportHubMonthIndex:()=>8,matchPropertyName:n=>['Doro','Bartram'].includes(n)?n:null,getRecordMonthlyDataForYear:(r,y)=>r.years?.[y]||r.monthlyData||Array(12).fill({}),getRecordSavedBudgetOccPct:()=>95});
assert.equal(c.getDlrReportCommunityName(),'Doro');assert.equal(c.resolveDlrReportCommunityName('Bogus'), '');assert.equal(c.resolveDlrReportCommunityName('Bartram'),'Bartram');
c.getProp=()=>({name:'Bartram'});assert.equal(c.getDlrReportCommunityName(),'Bartram');
for(const missing of [null,undefined,'',' ',NaN])for(const f of ['formatDlrMetricValue','formatDlrCurrency','formatDlrPercent'])assert.equal(c[f](missing),'N/A');
assert.equal(c.formatDlrPercent(0),'0.0%');assert.equal(c.formatDlrCurrency(0),'$0');
const expected={communityName:'Doro',communityId:'doro-id',totalUnits:247};
assert(c.validateDlrInventory({...expected,occupiedUnits:78,leasedUnits:108},expected));
assert(!c.validateDlrInventory({...expected,totalUnits:297,occupiedUnits:284,leasedUnits:272},expected));
assert(!c.validateDlrInventory({...expected,communityId:'other',occupiedUnits:78,leasedUnits:108},expected));
const application={applications:3,approvals:4,denials:1};
assert.equal(c.validateDlrApplicationCohort(application).sameCohort,false);
const provenance=Object.fromEntries(['applications','approvals','denials'].map(k=>[k,{cohort:'received',period:'2026-09',source:'source1'}]));
assert.equal(c.validateDlrApplicationCohort(application,provenance).valid,false);
assert.equal(c.validateDlrApplicationCohort({...application,applications:5},provenance).valid,true);
assert.equal(c.validateDlrApplicationCohort(application,{...provenance,denials:{...provenance.denials,period:'2026-08'}}).sameCohort,false);
c.dataImportNormalizeText=value=>String(value??'').trim().toLowerCase().replace(/\s+/g,' ');
const keyPeriod={periodKey:'2026-09'}, keySource={section:'Lead Conversions',period:{start:'2026-09-01',end:'2026-09-30'}};
const sectionKey=c.dataImportCanonicalRecordKey({reportType:'box_score',fileHash:'v1'},'Doro',keyPeriod,{},keySource);
assert.equal(sectionKey,c.dataImportCanonicalRecordKey({reportType:'box_score',fileHash:'v1'},'Doro',keyPeriod,{},keySource),'Exact file replay keeps one identity');
assert.notEqual(sectionKey,c.dataImportCanonicalRecordKey({reportType:'box_score',fileHash:'v2'},'Doro',keyPeriod,{},keySource),'A new file version remains independently auditable');
assert.notEqual(sectionKey,c.dataImportCanonicalRecordKey({reportType:'box_score',fileHash:'v1'},'Doro',keyPeriod,{}, {...keySource,section:'Lead Activity'}),'Distinct Box Score sections cannot suppress one another');
c.getApplicationDecisionMetrics=()=>({applications:99,approvals:88,denials:7});
assert.equal(c.buildDlrApplicationWindowMetricsFromMonths([{}],{applications:0}).applications,0);
assert.equal(c.buildDlrApplicationWindowMetricsFromMonths([{}],{applications:null}).applications,null);
const points=c.buildDlrForwardOccupancyTrendPoints({occupancyPct:78/247*100,forwardLook:[]});assert.equal(points[0].projectedOccupancy,78/247*100);
assert.equal(c.getVerifiedMonthlySnapshot({occupiedSnapshot:0}),null);
assert.equal(c.getVerifiedMonthlySnapshot({occupiedSnapshot:0,snapshotVerified:true}),0);
assert.equal(c.getVerifiedMonthlySnapshot({occupiedSnapshot:17}),null);
assert.equal(c.getVerifiedMonthlySnapshot({occupiedSnapshot:17,snapshotVerified:true}),17);
assert.equal(c.getVerifiedMonthlySnapshot({}),null);
let monthly=Array.from({length:12},()=>({}));monthly[8]={occupiedSnapshot:78,snapshotVerified:true};
assert.equal(c.buildVerifiedDlrProjection({monthlyData:monthly},8,2026,78,247).length,0);
monthly[9]={trendingMoveIns:0,trendingMoveOuts:0};monthly[10]={trendingMoveIns:3,trendingMoveOuts:1};monthly[11]={trendingMoveIns:4,trendingMoveOuts:2};
let projection=c.buildVerifiedDlrProjection({monthlyData:monthly},8,2026,78,247);assert.equal(projection.length,3);assert.equal(projection[0].projectedOccupancy,78/247*100);assert.equal(projection[2].projectedOccupancy,82/247*100);
assert.equal(c.buildCommunityProgressStabilization({sourceRecord:{monthlyData:monthly},totalUnits:247,reportMonthIdx:8,reportYear:2026}).months,null);
monthly[7]={occupiedSnapshot:70,snapshotVerified:true};assert.equal(c.buildCommunityProgressStabilization({sourceRecord:{monthlyData:monthly},totalUnits:247,reportMonthIdx:8,reportYear:2026}).months,20);
const financialRows=[{glCode:'4000',section:'Operating Income',lineItem:'Rent',actual:100,budget:110},{glCode:'5000',nature:'contra_income',actual:-10,budget:-5},{glCode:'6000',section:'Operating Expense',actual:20,budget:25}];
let record=F.apply({propertyName:'Doro'},{period:'2026-09',rows:financialRows,source:'ledger.csv'});
assert.equal(F.apply(record,{period:'2026-09',rows:financialRows,source:'ledger.csv'}),record,'Replay is idempotent');
const corrected=F.apply(record,{period:'2026-09',rows:[{...financialRows[0],actual:120}],source:'revision.csv',mode:'merge'});assert.equal(corrected.financialLedger['2026-09'].length,3);assert.equal(corrected.financialPublicationHistory.length,2);
assert.equal(c.getFinancialSummaryForMonth(record,8,2026).noiActual,70);assert.equal(c.getFinancialSummaryForMonth(record,8,2026).noiBudget,80);
assert.equal(c.getFinancialSummaryForMonth(record,7,2026).hasData,false);
assert.equal(c.summarizeFinancialLedgerRows([{actual:0,budget:0,glCode:'4000'}]).hasData,true);
record.monthlyData=Array.from({length:12},()=>({}));record.monthlyData[8]={actualCharges:0,grossPotentialRent:100,financialSource:'Rent September'};
assert.equal(c.getCommunityCommandEconomicOccupancyData(record,8,2026).mtdPct,0);
record.monthlyData[8].actualCharges=-5;assert.equal(c.getCommunityCommandEconomicOccupancyData(record,8,2026).mtdPct,-5);
record.monthlyData[8]={delinquencyBalance:10};assert.equal(c.getCommunityCommandEconomicOccupancyData(record,8,2026).mtdPct,null);
record.monthlyData[8]={actualCharges:20};assert.equal(c.getCommunityCommandEconomicOccupancyData(record,8,2026).mtdPct,null);
const fc={AtlasFinancialPublication:F};vm.createContext(fc);vm.runInContext(finance.match(/^function buildFinancialLedgerRows\([^\n]*\)\{[\s\S]*?^\}/m)[0],fc);
let ledger=fc.buildFinancialLedgerRows([{gl:'4000',name:'Rent',mAct:25,mBud:30,yAct:225,yBud:270}]);assert.equal(ledger[0].actual,25);assert.equal(ledger[0].budget,30);assert.equal(ledger[0].ytdActual,225);
// Real adapter regression: same community/file/range, different Box Score sections.
const pc={window:{AtlasPropertyIntelligence:P},Map,Set,Date,setInterval:()=>{},document:{hidden:true},dataImport2State:{canonicalRecords:[]}};vm.createContext(pc);vm.runInContext(fs.readFileSync('docs/portfolio-operations-dashboard/property-organization.js','utf8'),pc);
const period={start:'2026-09-01',end:'2026-09-30'};
const base={reportType:'box_score',communityName:'Doro',periodKey:'2026-09',sectionPeriod:period,sourceFile:'Box.xlsx',fileHash:'v1',importedAt:'2026-09-17',dataAsOf:'2026-09-17'};
pc.dataImport2State.canonicalRecords=[{...base,section:'Availability',values:{occupied_units:78}},{...base,section:'Lead Activity',values:{new_leads:51,tours:23}},{...base,section:'Lead Conversions',values:{applications:10,approvals:5,denied_applications:2,leases_completed:4}}];
let result=pc.window.atlasPropertyMetrics({name:'Doro',record:{}},period);assert.equal(result.applications.value,10);assert.equal(result.leases_completed.value,4);assert.equal(result.new_leads.value,51);
pc.dataImport2State.canonicalRecords.push({...pc.dataImport2State.canonicalRecords[2]});result=pc.window.atlasPropertyMetrics({name:'Doro',record:{}},period);assert.equal(result.applications.value,10);
pc.dataImport2State.canonicalRecords.push({...base,section:'Lead Conversions',fileHash:'v2',dataAsOf:'2026-09-18',importedAt:'2026-09-18',values:{applications:12,leases_completed:6}});result=pc.window.atlasPropertyMetrics({name:'Doro',record:{}},period);assert.equal(result.applications.value,12);
assert.equal(pc.window.atlasPropertyMetrics({name:'Other',record:{}},period).applications.value,null);
for(const file of [html,finance])for(const match of file.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi))if(match[1].trim())new vm.Script(match[1]);
console.log('PASS canonical report scope, invalid inventory, nullable formatting, cohort conflicts, exact MTD overrides, observed history, dated projections, monthly financial publication, signed values, duplicate sections and revisions.');
// Build the real DLR end-to-end with synthetic source records; unrelated photo/personnel services are stubbed.
const dlrRecord={propertyName:'Doro',communityId:'doro-id',currentMonth:8,currentOccupied:78,currentLeased:108,customUnits:247,monthlyData:Array.from({length:12},()=>({})),latestDlrSummary:{},marketSurveyData:{}};
dlrRecord.monthlyData[8]={occupiedSnapshot:78,leasedSnapshot:108,applications:3,applicationsApproved:4,denied:1,moveIns:9,moveOuts:6,renewalExpirations:0};
Object.assign(c,{savedData:{Doro:dlrRecord},DEFAULT_SEASONAL:Array(12).fill(1),DEFAULT_CURRENT_MONTH:8,getProp:()=>({name:'Doro',units:247}),getPropertyByName:()=>({name:'Doro',units:247}),getCommunityRecordForScope:()=>dlrRecord,getPersistedCommunityRecordForScope:()=>dlrRecord,getDlrWorkbookOverlayForCommunity:()=>null,normalizeCommunityPhotoBank:()=>[],normalizeMarketSurveyData:()=>({}),normalizeDlrSummary:()=>({dailyBoxScore:{},forwardLook:{},pricing:{},activity:{}}),defaultDlrSummary:()=>({dailyBoxScore:{},forwardLook:{},pricing:{},activity:{}}),normalizeDlrBoxScoreSnapshot:x=>x,hasDlrBoxScoreSnapshot:()=>false,isDlrSummaryForRequestedPeriod:()=>false,hasMeaningfulDlrSummary:()=>false,buildPortfolioDetailsForMonth:()=>[{summary:{occupiedRaw:78,leasedRaw:108,applications:3,applicationsApproved:4,applicationsDenied:1,moveIns:9,moveOuts:6}}],getResolvedTotalUnitsForRecord:()=>247,getCorporateLeaseUnitsForRecord:()=>0,computeScheduleFromContext:()=>Array(12).fill({}),buildDlrForwardLookRows:()=>[],computeProjectedEndingPhysicalOccupancy:()=>({pct:31}),getApplicationDecisionMetrics:e=>({applications:e.applications,approvals:e.applicationsApproved,denials:e.denied,cancelled:null,pendingDecision:null,leases:null}),getRenewalSummaryForMonth:()=>({expirations:0,signed:0,retentionRate:null}),getLeadSourceBreakdown:()=>({}),getLeadSourceTotal:()=>0,getEffectiveMoveOutsForMonth:()=>({effective:6}),getCommunityFloorPlanRentMetrics:()=>({}),getReportableCommunityFloorPlans:()=>[],buildCommunityFloorPlanVarianceRows:()=>({rows:[],unmatchedRates:[]}),resolveDlrEditableNotes:(s,n)=>({notes:n,editorValues:n}),resolveDlrMarketingState:()=>({}),buildDlrApplicationTrendRows:()=>[],buildDlrApplicationWindows:()=>({mtd:{}})});
vm.runInContext(html.match(/^function buildDlrInvestorNotes\([\s\S]*?^\}$/m)[0],c);
let report=c.buildDashboardDlrInvestorOverview('Doro',8,2026);
assert(report);assert.equal(report.communityName,'Doro');assert.equal(report.totalUnits,247);assert.equal(report.occupiedUnits,78);assert.equal(report.occupancyPct,78/247*100);assert.equal(report.renewalSnapshot.retentionRate,null);assert.equal(report.trendingOccupancyPct,null);assert(JSON.stringify(report.editableNotes).includes('90-day projection is unavailable'));assert(!JSON.stringify(report.editableNotes).includes('projected at')); assert(!JSON.stringify(report.notes).includes('including 4'));assert(!JSON.stringify(report.notes).includes('undefined'));assert.equal(c.buildDlrForwardOccupancyTrendPoints(report)[0].projectedOccupancy,report.occupancyPct);
c.getDlrWorkbookOverlayForCommunity=()=>({totalUnits:297,occupiedUnits:284,leasedUnits:272,communityId:'other'});c.dlrWorkbookReportState={};
assert.equal(c.buildDashboardDlrInvestorOverview('Doro',8,2026),null);
console.log('PASS actual DLR builder: selected community, counts/card/chart parity, missing denominator and projection, safe application narrative, mismatched overlay blocked.');

Object.assign(c,{currentOccupied:78,currentLeased:108,currentMonth:8,monthlyData:[],corporateLeaseUnits:0,savedBudgetTargets:[],seasonal:[],getMonthsToStabilization:()=>({months:null,targetUnits:235,reason:'Verified history required'}),renderWindowshadeCard:o=>o.bodyHtml});
const stabilizationMarkup=c.renderCommunityCommandStabilization({propName:'Doro',year:2026,monthIdx:8,record:{},traffic:{},appMetrics:{},renewal:{}});
assert(stabilizationMarkup.includes('Range Needed'));assert(!stabilizationMarkup.includes('September 2026'));console.log('PASS unavailable stabilization does not become the current calendar month.');
