import assert from 'node:assert/strict';
import {readFinance,financialSummary,bonusEvidence,number,readDetail} from '../docs/portfolio-operations-dashboard/features/canonical-finance.mjs';
import {createCache,coverage} from '../docs/portfolio-operations-dashboard/features/financial-close.mjs';
const cid='community',periods=['2025-04','2025-05','2025-06'];
const envelopes=periods.map((period,i)=>({communityId:cid,period,registryVersion:'atlas-finance-v1',accountingBasis:'accrual',currency:'USD',actualCloseVersion:'c'+i,budgetVersion:'b',targetApprovalStatus:'approved',revenue:{actual:i===0?-10:20,budget:10},expenses:{actual:0,budget:10}}));
assert.equal(number(' '),null);assert.equal(number(0),0);assert.equal(number(-10),-10);
assert.equal(financialSummary({...envelopes[0],noi:{actual:10,budget:null}}).noiVariance,null);
const evidence=bonusEvidence(envelopes,'revenue',periods);assert.equal(evidence.attainment,100);assert.deepEqual(evidence.actualCloseVersions,['c0','c1','c2']);
assert.equal(bonusEvidence(envelopes,'expenses',periods).attainment,200);
assert.equal(bonusEvidence(envelopes.slice(1),'revenue',periods),null);
assert.equal(bonusEvidence(envelopes.map(s=>({...s,budgetVersion:null})),'revenue',periods),null);
assert.equal(bonusEvidence(envelopes.map(s=>({...s,revenue:{actual:1,budget:0}})),'revenue',periods),null);
assert.equal(bonusEvidence(envelopes,'revenue',['2025-05','2025-06','2025-07']),null);
const rows=envelopes.map(s=>({community_id:cid,period_key:s.period,summary:s}));
assert.deepEqual(await readFinance({rpc:async()=>rows},[cid],periods),rows);
await assert.rejects(()=>readFinance({rpc:async()=>[{...rows[0],community_id:'other'}]},[cid],periods),/scope/);
let actor='a';await assert.rejects(()=>readFinance({getSession:()=>({user:{id:actor}}),rpc:async()=>{actor='b';return rows;}},[cid],periods),/Session changed/);
await assert.rejects(()=>readDetail({fetchJson:async()=>[]},{actualCloseVersion:'c',close:{row_count:1}}),/incomplete/);
assert.deepEqual(coverage([],2026),{first:0,last:0,missing:[],completeYtd:false});
assert.deepEqual(coverage([1,3,8].map(m=>({period_key:'2026-'+String(m).padStart(2,'0'),status:'closed',coverage:'full_month'})),2026),{first:1,last:8,missing:[2,4,5,6,7],completeYtd:false});
let fail=false;
const cache=createCache({readCommunitiesForAccess:async()=>[{community_id:cid,display_name:'Doro',canonical_name:'doro'}],rpc:async()=>{if(fail)throw Error('offline');return rows;}});
await cache.refresh(2025);assert.equal(cache.bonus('Doro','revenue',periods).attainment,100);fail=true;await assert.rejects(()=>cache.refresh(2025,true),/offline/);assert.equal(cache.envelope('Doro',periods[0]),null,'failed refresh must discard stale evidence');
console.log('PASS canonical adapter, exact quarter/year, source versions, missing/zero/signed values, invalid scope, stale cache and complete YTD');
const {readApprovedBudget}=await import('../docs/portfolio-operations-dashboard/features/canonical-finance.mjs');
const segments=[{version_id:'a',community_id:cid,calendar_year:2026,status:'locked',covered_months:[0,1],payload:{rows:[{glCode:'5120',monthly:[0,-5,...Array(10).fill(null)]}]}},{version_id:'b',community_id:cid,calendar_year:2026,status:'locked',covered_months:[2],payload:{rows:[{glCode:'5120',monthly:[null,null,10,...Array(9).fill(null)]}]}}];
const merged=await readApprovedBudget({fetchJson:async()=>segments},cid,2026);assert.deepEqual(merged.payload.rows[0].monthly.slice(0,4),[0,-5,10,null]);assert.equal(merged.periodVersions[2],'b');
await assert.rejects(()=>readApprovedBudget({fetchJson:async()=>[segments[0],segments[0]]},cid,2026),/Overlapping/);
const fs=await import('node:fs'),vm=await import('node:vm');
const html=fs.readFileSync(new URL('../docs/portfolio-operations-dashboard/index.html',import.meta.url),'utf8');
const body=html.slice(html.indexOf('function atlasBonusFinancialEvidence('),html.indexOf('\nfunction atlasBonusMetricActual('));
let requested;
const context={Date,refreshAtlasClosedFinancials:async()=>{},buildPeriodKey:(m,y)=>y+'-'+String(m+1).padStart(2,'0'),window:{AtlasClosedFinancialCache:{bonus:(name,key,periods)=>(requested={name,key,periods},{attainment:110})}}};vm.createContext(context);vm.runInContext(body,context);
assert.equal(context.atlasBonusFinancialEvidence({communityName:'Doro'},{metricKey:'noi'},{start:'2025-04-01',end:'2025-06-30'}).attainment,110);assert.equal(requested.periods.join(','),'2025-04,2025-05,2025-06');
assert.equal(context.atlasBonusFinancialEvidence({communityName:'Doro'},{metricKey:'noi'},{start:'2025-04-01',end:'2025-05-31'}),null);
for(const match of html.matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g)){if(!/type\s*=\s*["']module/.test(match[1])&&match[2].trim())new vm.Script(match[2]);}
console.log('PASS non-overlapping fiscal budget segments, retained missing amounts, Bonus requested historical quarter and dashboard syntax');
