const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{fixture}=require('./community-goals-fixture.cjs');
(async()=>{
const {db,A,B,signIn}=await fixture();
const payload={requiredMoveIns:0,applicationGoal:0,grossLeaseGoal:0,netLeaseGoal:0,occupancyGoal:47.6,leasedGoal:44.13,economicGoal:null,renewalGoal:null,reason:'Reviewed intentional zero production',effectiveDate:'2026-01-01',weeklyGoals:[{week:1,startDay:1,applicationGoal:0,grossLeaseGoal:0,netLeaseGoal:0}]};
const save=async(kind,revision,p=payload,cid=A,period='2026-09',id=randomUUID())=>(await db.query('select atlas_save_community_goals($1,$2,$3,$4,$5,$6::jsonb) as result',[cid,period,kind,revision,id,JSON.stringify(p)])).rows[0].result;
let r=await save('recommended',0,{...payload,applicationGoal:20});assert.equal(r.head.revision,0);assert.equal(r.head.recommendation_revision,1);const recId=r.record.record_id;
const draftRequest=randomUUID();r=await save('draft',0,payload,A,'2026-09',draftRequest);assert.equal(r.head.revision,1);assert.equal(r.record.payload.applicationGoal,0);const draftId=r.record.record_id;
assert.equal(r.record.payload.approvedAt,null);assert.equal(r.record.payload.approver,null);
r=await save('recommended',1,{...payload,applicationGoal:30});assert.equal(r.head.draft_id,draftId);assert.equal(r.head.revision,1);assert.equal(r.head.recommendation_revision,2);
const retry=await save('draft',0,payload,A,'2026-09',draftRequest);assert.equal(retry.record.record_id,draftId,'lost response retry has one immutable save');
await assert.rejects(()=>save('draft',1,{...payload,applicationGoal:8},A,'2026-09',draftRequest),/already used/);
await assert.rejects(()=>save('draft',0),/another session/);
r=await save('approved',1,{...payload,approver:'forged',approvedBy:'forged',approvedAt:'2000-01-01',communityId:B});
const approvedId=r.record.record_id;assert.equal(r.head.draft_id,null);assert.equal(r.head.approved_id,approvedId);assert.equal(r.record.payload.approver,'00000000-0000-0000-0000-000000000001');assert.equal(r.record.payload.communityId,A);assert.notEqual(r.record.payload.approvedAt,'2000-01-01');
assert.equal((await db.query('select count(*)::int as n from atlas_community_goal_records where record_id=$1',[draftId])).rows[0].n,1,'approval retains draft history');
await save('draft',2,{...payload,applicationGoal:8});
r=await save('recommended',2,{...payload,applicationGoal:40});assert.equal(r.head.approved_id,approvedId);assert.equal(r.head.revision,3,'recommendation revisions cannot replace human values');
await save('draft',0,{...payload,applicationGoal:18},B);
await save('draft',0,{...payload,applicationGoal:19},A,'2026-10');
await save('draft',0,{...payload,applicationGoal:21},A,'2027-09');
const heads=(await db.query('select * from atlas_community_goal_heads order by community_id,period_key')).rows;
assert.equal(heads.length,4,'community, month and year scopes are independent');
await assert.rejects(()=>save('approved',3,{...payload,applicationGoal:null}),/Complete/);
await assert.rejects(()=>save('approved',3,{...payload,weeklyGoals:[{week:1,startDay:1,applicationGoal:1,grossLeaseGoal:0,netLeaseGoal:0}]}),/total exactly/);
await assert.rejects(()=>save('draft',3,{...payload,effectiveDate:'2026-02-30'}),/date/);
await assert.rejects(()=>save('approved',3,{...payload,netLeaseGoal:1}),/must cover/);
await assert.rejects(()=>db.query("update atlas_community_goal_heads set revision=999"),/permission denied/);
await assert.rejects(()=>db.query("delete from atlas_community_goal_records"),/permission denied/);
await db.exec('reset role');await assert.rejects(()=>db.query("update atlas_community_goal_records set payload='{}'"),/immutable/);await signIn(1);
const plan=(await db.query('select * from atlas_save_community_plan($1,$2,0,$3::jsonb)',[A,'2026-09',JSON.stringify({tasks:[]})])).rows[0];
const report=async()=>(await db.query('select * from atlas_generate_community_plan_report($1,1)',[plan.plan_id])).rows[0];
const firstReport=await report();assert.equal(firstReport.snapshot.reportSchemaVersion,4);assert.equal(firstReport.snapshot.approvedGoals.id,approvedId);assert.equal(firstReport.snapshot.approvedGoals.applicationGoal,0);assert.equal(firstReport.report_id,(await report()).report_id);
r=await save('approved',3,{...payload,applicationGoal:12,grossLeaseGoal:8,netLeaseGoal:5,weeklyGoals:[{week:1,startDay:1,applicationGoal:12,grossLeaseGoal:8,netLeaseGoal:5}]});
const secondReport=await report();assert.notEqual(secondReport.report_id,firstReport.report_id);assert.equal(secondReport.snapshot.approvedGoals.applicationGoal,12);assert.equal((await db.query('select snapshot from atlas_community_plan_reports where report_id=$1',[firstReport.report_id])).rows[0].snapshot.approvedGoals.applicationGoal,0,'prior report remains immutable');
r=await save('approved',4,{...payload,effectiveDate:'2099-01-01'});assert.equal((await report()).snapshot.approvedGoals.applicationGoal,12,'future-effective approval does not replace current official reporting goals');
await signIn(3);assert.equal((await db.query('select * from atlas_community_goal_heads')).rows.length,1);await assert.rejects(()=>save('draft',0),/authorized/);await assert.rejects(()=>save('draft',1,payload,B),/authorized/);
await signIn(4);assert.equal((await db.query('select * from atlas_community_goal_heads')).rows.length,3,'scoped Bonus reads approved goals independently of Command');await assert.rejects(()=>save('draft',5),/authorized/);
await db.exec("reset role;update atlas_user_profiles set locked_tab_ids='{2,9}',locked_page_keys='{portfolio_overview,bonus}' where role='bonus'");await signIn(4);assert.equal((await db.query('select * from atlas_community_goal_heads')).rows.length,0);
await signIn(2);await save('draft',5);await db.exec("reset role;update atlas_user_profiles set locked_tab_ids='{2}' where role='executive'");await signIn(2);await assert.rejects(()=>save('draft',6),/authorized/);
await db.exec('reset role;set role anon');await assert.rejects(()=>db.query('select * from atlas_community_goal_records'),/permission denied/);
await db.close();console.log('PASS durable independent goal records, exact zero, atomic approval, immutable history/report snapshots, conflicts/retries, scope isolation, metadata, RLS and module locks');
})().catch(error=>{console.error(error);process.exitCode=1;});
