const assert=require('node:assert/strict');
const C=require('../docs/portfolio-operations-dashboard/community-command-contract.js');
const scope={communityId:'A',fiscalYear:2026,period:'2026-09'};
const actual={...scope,occupiedUnits:88,rentableUnits:100,source:'Entrata',sourceTimestamp:'2026-09-21'};
const budget={...scope,approvalStatus:'approved',locked:true,scenarioId:'approved',version:1,occupancyPct:90};
assert.equal(C.occupancy(scope,actual,budget).variance,-2);
assert.equal(C.occupancy(scope,{...actual,occupiedUnits:92},budget).label,'+2 Ahead');
assert.equal(C.occupancy(scope,{...actual,occupiedUnits:90},budget).label,'On Budget');
assert.equal(C.occupancy(scope,{...actual,occupiedUnits:0},{...budget,occupancyPct:0}).label,'On Budget');
for(const v of [null,undefined,-1,101,NaN])assert.equal(C.occupancy(scope,{...actual,occupiedUnits:v},budget).status,'missing');
assert.equal(C.occupancy(scope,actual,{...budget,occupancyPct:101}).status,'missing');
assert.equal(C.occupancy(scope,{...actual,rentableUnits:96},budget).budget,87);
assert.equal(C.occupancy(scope,actual,{...budget,period:'2026-08'}).status,'missing');
assert.equal(C.occupancy(scope,actual,{...budget,approvalStatus:'draft'}).status,'missing');
const fs={communityId:'A',fiscalYear:2026,periods:['2026-09'],metric:'expenses',scenarioId:'approved',scenarioVersion:1,periodBasis:'calendar_month'};
const mapping={communityId:'A',fiscalYear:2026,approvalStatus:'approved',version:1,metrics:{expenses:['6000'],gpr:['5000']}};
const row={communityId:'A',fiscalYear:2026,period:'2026-09',glCode:'6000',amount:100};
const fb={...fs,approvalStatus:'approved',locked:true,scenarioId:'approved',version:1,rows:[row],destinationId:'budget-A'};
const fa={...fs,approvalStatus:'approved',publicationId:'actual-A-September',source:'approved package',sourceTimestamp:'2026-09-21',rows:[{...row,amount:120}]};
assert.equal(C.financial(fs,mapping,fb,fa).variance,-20);assert.equal(C.financial(fs,mapping,fb,fa).label,'Overspent');
assert.equal(C.financial(fs,mapping,fb,{...fa,rows:[{...row,amount:80}]}).variance,20);
for(const bad of [{...fa,rows:[]},{...fa,rows:[row,row]},{...fa,communityId:'B'},{...fa,rows:[{...row,amount:null}]},{...fa,periodBasis:'fiscal_ytd'}])assert.equal(C.financial(fs,mapping,fb,bad).status,'missing');
assert.equal(C.financial({...fs,periods:['2026-08','2026-09']},mapping,fb,fa).status,'missing');
assert.equal(C.financial(fs,{...mapping,approvalStatus:'draft'},fb,fa).status,'missing');
const gr={...row,glCode:'5000'};assert.equal(C.financial({...fs,metric:'gpr'},mapping,{...fb,rows:[gr]},{...fa,rows:[{...gr,amount:120}]}).variance,20);
const task={id:'t',planId:'p',communityId:'A',status:'Accepted/Open',version:1,history:[]};
const ctx={communityId:'A',canEdit:true,actor:'u',at:'2026-09-21',expectedVersion:1,completionEvidence:'Evidence reference'};
const done=C.transitionTask(task,'Completed',ctx);assert.equal(done.verificationStatus,'Unverified');assert.equal(task.status,'Accepted/Open');
assert.throws(()=>C.transitionTask(done,'Verified',{...ctx,expectedVersion:2}),/permission/);
const verified=C.transitionTask(done,'Verified',{...ctx,expectedVersion:2,canVerify:true});assert.equal(verified.history.length,2);
assert.throws(()=>C.transitionTask(done,'In Progress',ctx),/changed/);
assert.throws(()=>C.transitionTask(task,'Completed',{...ctx,communityId:'B'}),/scoped/);
assert.equal(C.transitionTask(verified,'In Progress',{...ctx,expectedVersion:3}).verifiedAt,null);
console.log('PASS scoped budget/actual coverage, expense direction, historical denominator, missing/zero, task revisions and separate verification');
