import assert from 'node:assert/strict';
// Exercise the real summary hydration with the portfolio plan-count element present.
const count={textContent:''};
const cell=()=>({textContent:'',replaceChildren(){this.textContent='';},append(n){this.textContent=n.textContent;}});
const cells={units:cell(),gpr:cell(),expenses:cell()};
const planCell=cell();
globalThis.window=globalThis;
globalThis.AtlasCommunityCommandContract=(await import('../docs/portfolio-operations-dashboard/community-command-contract.js')).default;
globalThis.document={querySelector(selector){return selector==='[data-shared-plan-count]'?count:{dataset:{},querySelector(s){return s==='[data-shared-plan]'?planCell:cells[s.match(/data-metric="(.*?)"/)[1]];},querySelectorAll(){return Object.values(cells);}};},createElement(tag){return {tagName:tag.toUpperCase(),style:{}};}};
const {hydrate,cancel}=await import('../docs/portfolio-operations-dashboard/features/community-finance.mjs');
let queries=0;
const communityId='10000000-0000-0000-0000-000000000001';
await hydrate([{key:'sample',communityId,period:'2026-09',year:2026}],{rpc:async()=>{queries++;return [];},fetchJson:async path=>{queries++;return path.includes('plan_summaries')?[{community_id:communityId,period_key:'2026-09',stage:'Active',task_count:3,verified_count:1}]:[];}});
assert.equal(count.textContent,'1');
assert.equal(cells.gpr.textContent,'Missing publication');
assert.match(planCell.textContent,/3 tasks/);
assert.equal(queries,2);
await hydrate([{key:'sample',communityId,period:'2026-08',year:2026}],{fetchJson:async path=>path==='/rpc/atlas_read_finance'?[{community_id:communityId,period_key:'2026-08',fiscal_year:2026,summary:{registryVersion:'atlas-finance-v1',communityId,period:'2026-08',gpr:{actual:0,budget:null,status:'missing',label:'Missing approved budget'},expenses:{actual:-5,budget:null,status:'missing',label:'Missing approved budget'}}}]:[]});
assert.match(cells.gpr.textContent,/Actual \$0.*Missing approved budget/);assert.match(cells.expenses.textContent,/Actual -\$5.*Missing approved budget/);
cancel();console.log('Portfolio roster plan count and missing publication hydration pass');
