import assert from 'node:assert/strict';import fs from 'node:fs';import http from 'node:http';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright');
const root=path.resolve('docs/portfolio-operations-dashboard');
const server=http.createServer((req,res)=>{try{const file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!file.startsWith(root+path.sep))throw Error();res.setHeader('Content-Type','text/javascript');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true});
try{const page=await browser.newPage();await page.goto(origin+'/features/community-finance.mjs');await page.setContent('<table><tbody><tr data-command-finance="Test"><td data-metric="gpr"></td><td data-metric="expenses"></td><td data-metric="units"></td><td data-metric="occupancy-budget"></td></tr></tbody></table>');
const result=await page.evaluate(async()=>{const {hydrate}=await import('/features/community-finance.mjs');const id='22222222-2222-4222-8222-222222222222';const central={getSession:()=>({user:{id:'11111111-1111-4111-8111-111111111111'}}),getAccessContextKey:()=> 'test',fetchJson:async(url,options)=>{if(url==='/rpc/atlas_read_finance')return [{community_id:id,period_key:'2026-08',summary:{registryVersion:'atlas-finance-v1',communityId:id,period:'2026-08',periodState:'locked',actualCloseVersion:'version',effectiveBaseline:{status:'unavailable',communityId:id,period:'2026-08'},close:{community_id:id,period_key:'2026-08',version_id:'version',status:'closed',coverage:'full_month',source_file:'August.xlsx',approved_at:'2026-09-05',approved_by:'reviewer',metrics:{operatingExpenses:0}}}}];if(url.startsWith('/atlas_command_plan'))throw Error('Plan unavailable');return [];}};
await hydrate([{key:'Test',communityName:'Test',communityId:id,period:'2026-09',year:2026,rentRoll:{status:'valid',communityName:'Test',period:'2026-09',source:'hash',sourceFile:'September.xlsx',asOf:'2026-09-28',grossPotentialRent:12345.67,controls:{grossPotentialRent:{reconciled:true}}}}],central);
return {gpr:document.querySelector('[data-metric="gpr"]').textContent,expenses:document.querySelector('[data-metric="expenses"]').textContent};});assert.match(result.gpr,/\$12,345\.67/);assert.match(result.gpr,/2026-09 · Rent roll/);assert.match(result.expenses,/\$0\.00/);assert.match(result.expenses,/2026-08 · Closed actual · 2026-09 close missing/);console.log('PASS browser roster shows reconciled GPR and zero prior close without a budget or plan; actual month remains explicit');}
finally{await browser.close();await new Promise(r=>server.close(r));}
