const {PGlite}=require(process.env.ATLAS_PGLITE || '@electric-sql/pglite');
const fs=require('fs'),assert=require('node:assert/strict');
(async()=>{
const db=new PGlite();
await db.exec(`create role service_role bypassrls; create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;
create table atlas_user_profiles(user_id uuid,role text,status text,allowed_community_ids uuid[],locked_tab_ids text[],locked_page_keys text[]);
create table atlas_communities(community_id uuid primary key,display_name text,canonical_name text,status text,deleted_at timestamptz);
create table atlas_community_aliases(community_id uuid,alias text,active boolean);
create function atlas_can_access_community(id uuid) returns boolean language sql security definer set search_path=public as $$ select exists(select 1 from atlas_user_profiles where user_id=auth.uid() and status='active' and (role in ('admin','regional','executive') or id=any(allowed_community_ids))) $$;
insert into auth.users values ('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002'),('00000000-0000-0000-0000-000000000003');
insert into atlas_communities values ('10000000-0000-0000-0000-000000000001','Test A','test a','active',null),('10000000-0000-0000-0000-000000000002','Test B','test b','inactive',null);
insert into atlas_user_profiles values ('00000000-0000-0000-0000-000000000001','admin','active','{}','{}','{}'),('00000000-0000-0000-0000-000000000002','regional','active','{}','{}','{}'),('00000000-0000-0000-0000-000000000003','community_manager','active','{10000000-0000-0000-0000-000000000002}','{}','{}');`);
await db.exec(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/community-command.sql','utf8'));
await db.exec(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/community-command-finance.sql','utf8'));
await db.exec(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/community-command-delivery.sql','utf8'));
await db.exec(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/community-command-plan-summary.sql','utf8'));
await db.exec(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/community-command-report-ytd.sql','utf8'));
await db.exec(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/centralization/financial-admin-publication.sql','utf8'));
const signIn=async n=>db.exec(`reset role; set request.jwt.claim.sub='00000000-0000-0000-0000-${String(n).padStart(12,'0')}'; set role authenticated;`);
const A='10000000-0000-0000-0000-000000000001',B='10000000-0000-0000-0000-000000000002';
const task={id:'t1',title:'Validate variance',origin:'Manual',status:'Accepted/Open'};
const save=async(cid,v,tasks)=>(await db.query('select * from public.atlas_save_community_plan($1,$2,$3,$4::jsonb)',[cid,'2026-09',v,JSON.stringify({tasks})])).rows[0];
await signIn(1);let plan=await save(A,0,[task]);assert.equal(plan.version,1);
await assert.rejects(()=>save(A,0,[task]),/another session/);
await assert.rejects(()=>save(A,1,[task,task]),/duplicate/);
await assert.rejects(()=>save(A,1,[{...task,status:'Verified',completionEvidence:'e'}]),/Complete/);
plan=await save(A,1,[{...task,status:'Completed',completionEvidence:'verified source'}]);assert.equal(plan.payload.tasks[0].verificationStatus,'Unverified');
plan=await save(A,2,[{...plan.payload.tasks[0],status:'Verified'}]);assert.equal(plan.payload.tasks[0].verificationStatus,'Verified');
await assert.rejects(()=>save(A,3,[]),/Cancel/);
await assert.rejects(()=>save(A,3,[{...plan.payload.tasks[0],title:'Changed verified content'}]),/Reopen/);
const generate=async(v,note='Review')=>(await db.query('select * from public.atlas_generate_community_plan_report($1,$2,$3)',[plan.plan_id,v,note])).rows[0];
const report=await generate(3);assert.equal((await generate(3)).report_id,report.report_id,'repeat generation must deduplicate');
assert.equal(report.snapshot.plan.tasks[0].status,'Verified');
await assert.rejects(()=>generate(2),/another session/);
await assert.rejects(()=>db.query("update atlas_community_plan_reports set executive_note='tampered'"),/permission denied/);
await signIn(3);assert.equal((await db.query('select * from atlas_community_plans')).rows.length,0);assert.equal((await db.query('select * from atlas_command_plan_summaries')).rows.length,0);
await assert.rejects(()=>save(A,3,[task]),/denied/);
await assert.rejects(()=>generate(3),/denied/);
assert.equal((await db.query('select * from atlas_community_plan_reports')).rows.length,0);
let b=await save(B,0,[task]);b=await save(B,1,[{...task,status:'Completed',completionEvidence:'e'}]);
await assert.rejects(()=>save(B,2,[{...b.payload.tasks[0],status:'Verified'}]),/verification/);
await assert.rejects(()=>db.query('update atlas_community_plans set version=99'),/permission denied/);
await signIn(2);assert.equal((await db.query('select * from atlas_community_plans')).rows.length,1);
assert.equal((await db.query('select * from atlas_community_plan_events')).rows.length,3);
await db.exec("reset role; update atlas_user_profiles set locked_tab_ids='{2}' where role='regional'");await signIn(2);
assert.equal((await db.query('select * from atlas_community_plans')).rows.length,0);await assert.rejects(()=>save(A,3,[task]),/denied/);
await signIn(1);
const payload={communityId:A,period:'2026-09',year:2026,fiscalYear:2026,periodBasis:'calendar_month',approvedLocked:true,reviewConfirmed:true,scenarioId:'approved',scenarioVersion:'verified-budget-hash',builderPropertyId:'builder-A',actualSource:'approved actuals.xlsx',budgetSource:'locked budget.xlsx',sourceTimestamp:'2026-09-20T10:00:00Z',occupancyPct:95,mappingVersion:'reviewed-v1',rows:[{glCode:'5120',metric:'gpr',nature:'income',actual:900,budget:1000,ytdActual:5000,ytdBudget:6000},{glCode:'6500',metric:'expenses',nature:'expense',operatingApproved:true,actual:1200,budget:1000,ytdActual:6000,ytdBudget:5000}]};
const publish=async(data,version=0)=>(await db.query('select * from public.atlas_publish_command_financials($1,$2,$3,$4::jsonb)',[A,'2026-09',version,JSON.stringify(data)])).rows[0];
await signIn(2);await assert.rejects(()=>publish(payload),/Only an active Admin/);
await assert.rejects(()=>db.query('select atlas_private.atlas_publish_command_financials($1,$2,$3,$4::jsonb)',[A,'2026-09',0,JSON.stringify(payload)]),/permission denied/);await signIn(1);
const fiscalPayload={...payload,fiscalStartMonth:7,fiscalStartPeriod:'2025-07',period:'2026-09',fiscalPeriods:[]};
await assert.rejects(()=>publish(fiscalPayload),/Fiscal period scope mismatch/);
const validFiscal={...payload,fiscalStartMonth:7,fiscalStartPeriod:'2026-07',fiscalPeriods:['2026-07','2026-08','2026-09'],rows:payload.rows.map(r=>({...r,ytdActual:r.actual*3,ytdBudget:r.budget*3,fiscalEvidence:['2026-07','2026-08','2026-09'].map(period=>({period,actual:r.actual,budget:r.budget,actualSource:'actuals',sourceTimestamp:'2026-09-21',budgetSource:'approved',budgetEffectiveDate:'2026-01-01'}))}))};
await assert.rejects(()=>publish({...validFiscal,rows:validFiscal.rows.map(r=>({...r,ytdActual:1}))}),/does not reconcile/);
await assert.rejects(()=>publish({...validFiscal,rows:validFiscal.rows.map(r=>({...r,fiscalEvidence:r.fiscalEvidence.map((e,i)=>i===0?{...e,actual:null}:e)}))}),/must remain missing/);
await db.query('select atlas_private.validate_command_fiscal_ytd($1::jsonb)',[JSON.stringify(validFiscal)]).then(()=>assert.fail('private function must be denied'),e=>assert.match(e.message,/permission denied/));
await db.exec('reset role');
await db.query('select atlas_private.validate_command_fiscal_ytd($1::jsonb)',[JSON.stringify(validFiscal)]);
const crossYear={...validFiscal,period:'2027-01',fiscalStartPeriod:'2026-07',fiscalPeriods:['2026-07','2026-08','2026-09','2026-10','2026-11','2026-12','2027-01']};crossYear.rows=crossYear.rows.map(r=>({...r,ytdActual:r.actual*7,ytdBudget:r.budget*7,fiscalEvidence:crossYear.fiscalPeriods.map(period=>({...r.fiscalEvidence[0],period}))}));
await db.query('select atlas_private.validate_command_fiscal_ytd($1::jsonb)',[JSON.stringify(crossYear)]);
await signIn(1);
const pub=await publish(payload);assert.equal(pub.summary.gpr.variance,-100);assert.equal(pub.summary.expenses.variance,-200);assert.equal(pub.summary.expenses.label,'Overspent');
assert.equal((await publish(payload)).publication_id,pub.publication_id,'identical publication is idempotent');
await assert.rejects(()=>publish({...payload,rows:[...payload.rows,payload.rows[0]]},1),/duplicate/);
await assert.rejects(()=>publish({...payload,approvedLocked:false},1),/Incomplete/);
await assert.rejects(()=>publish({...payload,communityId:B},1),/Incomplete/);
await assert.rejects(()=>publish({...payload,year:2025},1),/mismatch/);
const missing={...payload,rows:payload.rows.map(r=>({...r,actual:null}))};
await assert.rejects(()=>publish(missing,0),/another session/);
const incomplete=await publish(missing,1);assert.equal(incomplete.summary.gpr.status,'missing');assert.equal(incomplete.summary.gpr.actual,null);
await assert.rejects(()=>publish(payload,2),/superseded/);
const sources=(await db.query('select * from atlas_command_findings where publication_id=$1',[incomplete.publication_id])).rows;assert.equal(sources.length,2);assert.equal(sources[0].payload.category,'Data Readiness');
const taskWithFinding={id:'finding-task',title:sources[0].payload.recommendedResponse,origin:'Recommended',sourceFindingId:sources[0].finding_id,status:'Accepted/Open'};
plan=await save(A,3,[plan.payload.tasks[0],taskWithFinding]);assert.equal(plan.version,4);
await assert.rejects(()=>save(A,4,[...plan.payload.tasks,{...taskWithFinding,id:'forged',sourceFindingId:B}]),/registered source/);
const updatedReport=await generate(4);assert.equal(updatedReport.snapshot.previousReport.reportId,report.report_id);assert.equal(updatedReport.snapshot.reportSchemaVersion,2);
assert.equal(updatedReport.snapshot.financial.publicationId,incomplete.publication_id);assert.equal(report.snapshot.financial,null,'old report remains immutable');
const claim=async emails=>(await db.query('select * from public.atlas_claim_command_report_delivery($1,$2)',[updatedReport.report_id,emails])).rows[0];
const delivery=await claim(['LEADER@risere.com']);assert.equal(delivery.status,'claimed');
await assert.rejects(()=>claim(['leader@risere.com','new@risere.com']),/already recorded/);
await assert.rejects(()=>claim(['not an email']),/valid recipients/);
await assert.rejects(()=>db.query("update atlas_command_report_deliveries set status='sent'"),/permission denied/);
await db.exec("reset role; update atlas_user_profiles set locked_page_keys='{budget}' where role='admin'");await signIn(1);
assert.equal((await db.query('select * from atlas_command_financial_publications')).rows.length,0);
await assert.rejects(()=>publish({...payload,sourceTimestamp:'2026-09-21T10:00:00Z'},2),/denied/);
await db.exec('reset role; set role anon');await assert.rejects(()=>db.query('select * from atlas_community_plans'),/permission denied/);
await db.close();console.log('PASS scoped shared plans, RLS, immutable audit, version conflicts, module locks and separate verification');
})().catch(e=>{console.error(e);process.exitCode=1;});
