const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=require('./dashboard-source.cjs').readDashboardSource('docs/portfolio-operations-dashboard/index.html');
const c=vm.createContext({Date,Map,Set,console,crypto:require('node:crypto').webcrypto});
for(const f of source.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm))vm.runInContext(f[0],c);
const community='Synthetic Campus',sourceId='trend-hash',period='2026-06';
const prov=(date,field)=>({community,source:sourceId,period:date.slice(0,7),dataAsOf:date,field});
const snap=(date,units,base)=>({occupiedSnapshot:units,rentableUnits:base,metricProvenance:{occupiedSnapshot:prov(date,'occupied_units')}});
Object.assign(c,{getAtlasTodayISODate:()=> '2026-10-02',getCommunityCommandDashboardOverride:()=>null,getCommunityCommandApprovedGoal:()=>null});
const model={propName:community,year:2026,monthIdx:8,totalUnits:388,corporateUnits:0,record:{},monthlyData:Array.from({length:12},()=>({}))};
model.monthlyData[5]={physicalSnapshotHistory:{'2026-06-01':snap('2026-06-01',170,390),'2026-06-30':snap('2026-06-30',143,386)}};
model.monthlyData[6]={physicalSnapshotHistory:{'2026-07-01':snap('2026-07-01',143,390),'2026-07-31':snap('2026-07-31',167,384)}};
let p=c.communityCommandOccupancyPeriods(model);assert.equal(p[5].beginningUnits,170);assert.equal(p[5].endingActualUnits,143);assert.equal(p[5].beginningPct,170/390*100);assert.equal(p[5].endingActualPct,143/386*100);assert.equal(p[6].endingActualPct,167/384*100);assert(p[6].warnings.some(s=>s.includes('Each percentage')));
model.corporateUnits=40;model.monthlyData[0]={physicalSnapshotHistory:{'2026-01-01':snap('2026-01-01',0,247),'2026-01-31':snap('2026-01-31',2,247)}};p=c.communityCommandOccupancyPeriods(model);assert.equal(p[0].beginningUnits,0);assert.equal(p[0].endingActualUnits,2,'Current corporate count must not erase historical source counts');
// Report rows carry their own months, including future months; the upload month does not relabel them.
const rows=c.dataImportParseTrendingRows([['Date Range','Beginning Occupancy','Move-ins','Move-outs','Ending Occupancy','','Beginning Occupied Units','Ending Occupied Units','Unit Space Count'],['06/01/2026 - 06/30/2026','',10,37,'','',170,143,390],['11/01/2026 - 11/30/2026','',2,0,'','',380,382,388]],community);
assert.equal(rows.length,2);assert.equal(rows[0].period.start,'2026-06-01');assert.equal(rows[1].period.start,'2026-11-01');
const imports={canonicalRecords:[],sourceArchive:[],lineage:[],reconciliationLog:[],exceptions:[],closedPeriods:[]},groups=[];
Object.assign(c,{window:{AtlasFeatures:{load:async()=>{}},atlasCsPreviewRenewalSheetRows:()=>{}},XLSX:{},savedData:{[community]:{}},dataImport2State:imports,dataImportRuntimeCanonicalIndex:null,dataImportRuntimeCurrentLineageIndex:null,dataImportRuntimeLineageBuffer:null,dataImportApprovalInProgress:false,dataImportApprovalPreflight:false,dataImportApprovalProgress:{rowsDone:0},dataImportUpdateApprovalProgress:()=>{},dataImportReadStructuredRows:async()=>[{sheetName:community,rows}],dataImportBuildAliasLookup:()=>new Map(),dataImportBuildInternalCommunityLookup:()=>new Map(),dataImportEffectiveFreshness:()=>({action:'warn',days:3650}),dataImportMapSourceRow:r=>({mapped:r.values,sourceFields:{},unmappedFields:[]}),dataImportResolveRowCommunity:()=>community,dataImportCommunitySupportsReport:()=>true,dataImportGetReportDef:()=>null,dataImportApplyGroupedSnapshot:g=>groups.push(g),dataImportRecordPlanLearningUsage:()=>{},persistSaved:()=>{},persistDataImport2State:()=>{},getProp:()=>({name:community}),loadPropertyData:()=>{},renderTab:()=>{},DATA_IMPORT_FILE_ARCHIVE_PREFIX:'archive:'});
(async()=>{const result=await c.dataImportRouteStructuredFile({},{reportType:'trending_occupancy',name:'trend.xlsx',fileHash:sourceId,metadata:{dataAsOf:'2026-10-02'},reportingMonthIdx:9,reportingYear:2026,selectedCommunities:[community],periodSelection:{requested:{monthIdx:9,year:2026}}},'batch');assert.equal(result.rowsHeld,0);assert.deepEqual(groups.map(g=>g.period.periodKey),['2026-06','2026-11']);console.log('PASS source boundary bases, historical corporate preservation, valid zero and multi-month trend approval route');})();
