import assert from 'node:assert/strict';
import {readBudgetCalendar,budgetYearPeriods,fiscalYtdPeriods,resolveImportCommunity} from '../docs/portfolio-operations-dashboard/features/community-budget-identity.mjs';
const communities=[{community_id:'d',display_name:'RISE Doro',canonical_name:'doro',property_type:'Multifamily',version:3},{community_id:'p',display_name:'The Preserve at Tech',market:'Student Housing',version:2}],aliases=[{community_id:'p',alias:'Ruston',active:true}];
const mf=readBudgetCalendar(communities[0]),student=readBudgetCalendar(communities[1]);
assert.deepEqual(budgetYearPeriods(2026,mf),Array.from({length:12},(_,i)=>`2026-${String(i+1).padStart(2,'0')}`));
assert.equal(budgetYearPeriods(2026,student).at(-1),'2027-07');
assert.deepEqual(fiscalYtdPeriods('2026-08',student),['2026-08']);
assert.equal(fiscalYtdPeriods('2026-08',mf).length,8);
assert.equal(fiscalYtdPeriods('2027-01',student)[0],'2026-08');
assert.equal(readBudgetCalendar({display_name:'Student Housing'}).verified,false);
assert.equal(readBudgetCalendar({market:'Student Housing',property_type:'Multifamily'}).verified,false);
assert.equal(readBudgetCalendar({market:'Student Housing',review_status:'review_required',review_flags:['market_inferred']}).verified,false);
assert.equal(readBudgetCalendar({market:'Student Housing',review_status:'review_required',review_flags:['market_inferred'],budget_calendar:{verified:true,source:'Owner verified settings',classification:'Student Housing',startMonth:8}}).verified,true);
assert.equal(resolveImportCommunity({fileName:'Ruston August close.pdf',embeddedNames:['The Preserve at Tech']},communities,aliases).communityId,'p');
assert.equal(resolveImportCommunity({fileName:'Conventional only Doro.xlsx',embeddedNames:['RISE Doro']},communities,aliases).communityId,'d');
assert.equal(resolveImportCommunity({fileName:'Doro.xlsx',embeddedNames:['Ruston']},communities,aliases).status,'mapping_required');
assert.equal(resolveImportCommunity({fileName:'Unknown.xlsx',embeddedNames:['Unknown']},communities,aliases).communityId,null);
assert.equal(resolveImportCommunity({fileName:'Doro.xlsx',embeddedNames:['Ruston'],selectedCommunityId:'p',confirmed:true,reason:'Reviewed embedded property against approved alias'},communities,aliases).communityId,'p');
assert.equal(resolveImportCommunity({fileName:'Conventional only Doro.xlsx',embeddedNames:['300 (RISE Doro)']},communities,aliases).communityId,'d');
console.log('PASS verified financial calendars, school-year YTD, approved aliases, filename corroboration and conflict blocking');
