const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const P=require('../docs/portfolio-operations-dashboard/property-intelligence.js');
const names=['Baymeadows','Bartram Park','Anthem House','Doro','Sereno'];
const details=names.map((name,i)=>({name,record:{boxScoreHistory:[{section:'Activity',start:'2026-09-01',end:'2026-09-30',importedAt:'2026-09-17',values:{new_leads:51+i,tours:23,applications:10,approvals:5,denied_applications:2,leases_completed:4},sourceFile:'Box Score fixture.xlsx',sourceSheet:name}],marketSurveyHistory:{'2026-09':{updatedOn:'2026-09-06',sourceFileName:'APTIQ fixture.xlsx',surveyComps:[{name,isSubject:true,concessionDetails:'Stale third-party special'},{name:'Competitor <A>',concessionDetails:'One month free',applicationsLast7:8,applicationsLast30:19,leasesLast7:2,leasesLast30:5,cancelPctLast7:0,cancelPctLast30:.31}]}}}}));
const offers=names.map((name,i)=>[name,{canManage:true,settings:{website:'https://example.com'},current:{status:i===1?'conflict':'found',lastVerifiedAt:'2026-09-17T11:00:00Z'},offers:[{id:'offer-'+i,source:'manual',text:'Two months free + $250 gift card <test>',components:[{type:'rent',text:'Two months free'},{type:'gift_card',text:'$250 gift card'}],start:'2026-09-01',end:'2026-09-30'}],observations:[],audit:[]}]);
const window={AtlasPropertyIntelligence:P,AtlasPropertyService:{cache:new Map(offers)},getCompCalculatorScopeMeta:()=>({marketArea:'North Florida'}),getSelectedDashboardPeriodKey:()=> '2026-09',getWorkspaceScopedDetails:()=>details,isAtlasLeaseTrackingCommunity:()=>true,atlasPropertyMetrics:(d,r)=>P.metrics(d.record.boxScoreHistory,r),renderTab:()=>{}};
const source=fs.readFileSync('docs/portfolio-operations-dashboard/concession-insights.js','utf8');vm.runInNewContext(source,{window,Intl,Date,Map,Set,console});
const api=window.AtlasConcessionInsights;let html=api.render();
assert(html.includes('gift card &lt;test&gt;'));assert(!html.includes('gift card <test>'));assert(!html.includes('Stale third-party special'));assert(html.includes('Apps 7d / 30d'));assert(html.includes('Conflicting website offers'));assert(html.includes('Completed applications'));
for(const name of names)window.atlasConcessionSelect(name,true);assert.equal(api.state.selected.length,4);assert(api.render().includes('Select at most four'));
window.atlasConcessionCompare();assert(api.render().includes('ci-comparison'));assert(!api.render().includes('<h2><label><input type="checkbox" checked onchange="atlasConcessionSelect(&quot;Sereno'));
window.atlasConcessionFilter('search','gift card');assert.equal(api.filtered(api.model(details,'2026-09')).length,5);window.atlasConcessionFilter('source','website');assert.equal(api.filtered(api.model(details,'2026-09')).length,0);
window.atlasConcessionReset();window.atlasConcessionClear();window.atlasConcessionFilter('mode','range');window.atlasConcessionFilter('start','2026-09-10');window.atlasConcessionFilter('end','2026-09-20');assert(api.render().includes('Partial or overlapping source coverage'));
console.log('PASS website/manual precedence, escaping, role-visible controls, 2–4 selection, competitor labels, source/search filters and partial ranges.');
if(process.env.ATLAS_UI_FIXTURE){
 const fixture=`const details=${JSON.stringify(details)},offerData=${JSON.stringify(offers)};window.AtlasPropertyService={cache:new Map(offerData),action:async(name,action,body)=>{const d=AtlasPropertyService.cache.get(name);if(action==='saveOffer'){const o={...body.offer,id:body.offer.id||'new-'+Date.now(),source:'manual'};d.offers=d.offers.filter(x=>x.id!==o.id).concat(o);}return d;}};window.getCompCalculatorScopeMeta=()=>({marketArea:'North Florida'});window.getSelectedDashboardPeriodKey=()=> '2026-09';window.getWorkspaceScopedDetails=()=>details;window.isAtlasLeaseTrackingCommunity=()=>true;window.atlasPropertyMetrics=(d,r)=>AtlasPropertyIntelligence.metrics(d.record.boxScoreHistory,r);window.renderTab=()=>document.getElementById('preview').innerHTML=AtlasConcessionInsights.render();`;
 fs.writeFileSync(process.env.ATLAS_UI_FIXTURE,`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATLAS comparison — local test data</title><link rel="stylesheet" href="./portfolio-operations-dashboard/concession-insights.css"><style>body{font-family:Arial,sans-serif;margin:0;padding:24px;background:#f3f6f9}</style></head><body><div id="preview"></div><script src="./portfolio-operations-dashboard/property-intelligence.js"></script><script>${fixture}</script><script src="./portfolio-operations-dashboard/concession-insights.js"></script><script>renderTab()</script></body></html>`);
}
