const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('docs/portfolio-operations-dashboard/concession-insights.js','utf8');
const detail={name:'Test community',record:{marketSurveyData:{specialsRecommendation:'Do not treat as actual',surveyComps:[{isSubject:true,concessionDetails:'Undated special'}]},marketSurveyHistory:{
 '2025-12':{sourceFileName:'December survey.xlsx',surveyComps:[{name:'Test community',isSubject:true,rent:1800,ner:1650,concessionDetails:'One month free'},{name:'Test competitor',rent:1850,ner:1700,concessionDetails:'Six weeks free'}]},
 '2026-01':{sourceFileName:'January survey.xlsx',surveyComps:[{name:'Test community',isSubject:true,rent:1820,ner:1670,concessionDetails:'$500 credit <test>'},{name:'Test competitor',rent:1850,ner:1700,concessionDetails:'Six weeks free'}]}}}};
const getMetrics=p=>p==='2026-01'||p==='2025-12'?[{community:detail.name,cells:Object.fromEntries(Object.entries({new_leads:50,tours:20,applications:10,approvals:8,denied_applications:0,cancelled_applications:1,leases_completed:p==='2026-01'?7:4}).map(([k,v])=>[k,{value:v,label:k,source:`${p} test.xlsx · test tab · ${k}`}]))}]:[];
const window={getCompCalculatorScopeMeta:()=>({marketArea:'Test market'}),getApplicationResidentReportPeriodKey:()=> '2026-01',getWorkspaceScopedDetails:()=>[detail],getAtlasApplicationPeriodMetrics:getMetrics,isAtlasLeaseTrackingCommunity:()=>true,renderTab:()=>{}};
vm.runInNewContext(source,{window,Intl,Date});const api=window.AtlasConcessionInsights;
const before=JSON.stringify(detail);const rows=api.model([detail],'2026-01',getMetrics);
assert.equal(rows[0].previous.period,'2025-12');assert.equal(rows[0].delta,3);assert.equal(rows[0].current.denials,0);assert.equal(rows[0].history[0].leases,null);assert.equal(rows[0].history[0].offer,'');assert.equal(rows[0].current.ratio,70);assert.equal(before,JSON.stringify(detail));
const recommendationOnly={name:'Recommendation only',record:{marketSurveyHistory:{'2026-01':{specialsRecommendation:'Two free months',marketConcessions:'Comp special'}}}};
assert.equal(api.snapshot(recommendationOnly,'2026-01',[]).offer,'');
assert.equal(api.snapshot({name:'A',record:{marketSurveyData:{updatedOn:'2026-01-15',subjectConcessionDetails:'Recorded source offer'}}},'2026-01',[]).offer,'Recorded source offer');
assert.equal(api.snapshot({name:'A',record:{marketSurveyHistory:{'2026-01':{updatedOn:'2025-12-15',subjectConcessionDetails:'Stale copied offer'}}}},'2026-01',[]).offer,'');
const html=api.render();assert(html.includes('$500 credit &lt;test&gt;'));assert(!html.includes('$500 credit <test>'));assert(html.includes('3 more completed leases'));assert(html.includes('2025-12 test.xlsx'));assert(!html.includes('Undated special'));
window.atlasConcessionFilter('community','Not authorized');assert.equal(api.filtered(rows).length,0);window.atlasConcessionReset();window.atlasConcessionFilter('search','Six weeks');assert.equal(api.filtered(rows).length,1);window.atlasConcessionFilter('search','No match');assert.equal(api.filtered(rows).length,0);window.atlasConcessionReset();
window.isAtlasLeaseTrackingCommunity=()=>false;assert(!api.render().includes('<h2>Test community</h2>'));window.isAtlasLeaseTrackingCommunity=()=>true;
assert.equal(api.shift('2026-01',-1),'2025-12');assert.equal(api.shift('2026-12',1),'2027-01');
console.log('PASS exact-period history, year rollover, missing vs zero, preserved sources, offer/recommendation separation, scope/filter behavior, escaping, and no source mutation.');
if(process.env.ATLAS_CONCESSION_PREVIEW){const css=fs.readFileSync('docs/portfolio-operations-dashboard/concession-insights.css','utf8');const mock=`const detail=${JSON.stringify(detail)};const getMetrics=${getMetrics.toString()};window.getCompCalculatorScopeMeta=()=>({marketArea:'Test market'});window.getApplicationResidentReportPeriodKey=()=> '2026-01';window.getWorkspaceScopedDetails=()=>[detail];window.getAtlasApplicationPeriodMetrics=getMetrics;window.renderTab=()=>document.getElementById('preview').innerHTML=window.AtlasConcessionInsights.render();`;
fs.writeFileSync(process.env.ATLAS_CONCESSION_PREVIEW,`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ATLAS concession dashboard — test fixture</title><style>body{font-family:Arial,sans-serif;background:#f3f6f9;padding:24px;margin:0}button{padding:10px;border:1px solid #ccc;border-radius:8px;background:white;cursor:pointer}${css}</style><div id="preview"></div><script>${mock}</script><script>${source}</script><script>renderTab()</script>`);}
