const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx={RBB:{app:{h:{esc:s=>String(s).replace(/</g,'&lt;')}}}};vm.createContext(ctx);
vm.runInContext(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/contract-terms.js','utf8'),ctx);
const T=ctx.RBB.contractTerms;
assert.equal(T.extract('Monthly service $100. Contract expires July 31.'),null);
const term=T.extract('Either party may terminate without cause with 60 days written notice. Early termination requires payment of the remaining fees. No cancellation fee applies after the initial term.');
assert.match(term.summary,/60 days/);assert.match(term.summary,/remaining fees/);assert.match(term.summary,/after the initial term/);
assert.match(T.cell({}),/Not recorded/);assert.match(T.cell({earlyCancellation:{...term,summary:'<script>bad</script>'}}),/&lt;script/);
const html=fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/RISE-Budget-Builder.html','utf8');
assert.match(html,/<th>Early cancellation<\/th>/);assert.match(html,/earlyCancellation:x.earlyCancellationSummary/);assert.match(html,/'Early cancellation','Status'/);
console.log('PASS cancellation conditions, no invented terms, escaped display, persisted intake and CSV column');
