import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {sha256,canonicalJson,financeSnapshot,forecastSnapshot} from '../docs/portfolio-operations-dashboard/features/financial-snapshot.mjs';
import {readFinance,bonusEvidence} from '../docs/portfolio-operations-dashboard/features/canonical-finance.mjs';
import {financialRows} from '../docs/portfolio-operations-dashboard/features/community-plan-report.mjs';
import {closeReportPdf,closeReportRows,closeReportHtml,closeReportWorkbook} from '../docs/portfolio-operations-dashboard/features/financial-close-report.mjs';
import {reportPdf,reportSnapshot,exportRows} from '../docs/portfolio-operations-dashboard/features/reforecast-report.mjs';
import {PDFDocument,PDFName,PDFDict,PDFArray,PDFRawStream,decodePDFRawStream} from '../docs/portfolio-operations-dashboard/vendor/pdf-lib-1.17.1.mjs';
const require=createRequire(import.meta.url),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
for(const text of ['', 'abc', 'Unicode € 文書', 'x'.repeat(300000)])assert.equal(sha256(text),createHash('sha256').update(text).digest('hex'));
const summary={communityId:'fixture-community',period:'2026-01',registryVersion:'atlas-finance-v1',accountingBasis:'accrual',currency:'USD',actualCloseVersion:'close-1',actualContentHash:'a'.repeat(64),budgetVersion:'budget-1',budgetContentHash:'b'.repeat(64),targetApprovalStatus:'approved',revenue:{actual:0,budget:100},expenses:{actual:-4.21,budget:20},noi:{actual:4.21,budget:80},cashFlow:{actual:null,budget:80}};
const record={community_id:summary.communityId,period_key:summary.period,publication_id:'publication-1',summary},session=()=>({getSession:()=>({user:{id:'fixture-reader'}}),fetchJson:async()=>structuredClone([record])});
const first=(await readFinance(session(),[summary.communityId],[summary.period]))[0],second=(await readFinance(session(),[summary.communityId],[summary.period]))[0];assert.deepEqual(first,second);
const retained=first.summary.financialSnapshot,report={snapshot:{community:'Fixture property',period:summary.period,financial:{publicationId:record.publication_id,summary:first.summary}}};
assert(financialRows(report).every(row=>row.Snapshot===retained.fingerprint));
assert.equal(financeSnapshot({...summary,publishedAt:'different-read-time'},record.publication_id).fingerprint,retained.fingerprint);
for(const change of [{period:'2026-02'},{actualContentHash:'c'.repeat(64)},{budgetVersion:'budget-2'},{revenue:{actual:null,budget:100}},{expenses:{actual:4.21,budget:20}}])assert.notEqual(financeSnapshot({...summary,...change},record.publication_id).fingerprint,retained.fingerprint);
const periods=['2026-01','2026-02','2026-03'],envelopes=periods.map((period,i)=>({...summary,period,actualCloseVersion:'close-'+i,publicationId:'pub-'+i})),bonus=bonusEvidence(envelopes,'expenses',periods);assert(bonus.sourceSnapshots.every((source,i)=>source.Snapshot===financeSnapshot(envelopes[i]).fingerprint));
async function evidence(bytes){const pdf=await PDFDocument.load(bytes),names=pdf.catalog.lookup(PDFName.of('Names'),PDFDict).lookup(PDFName.of('EmbeddedFiles'),PDFDict).lookup(PDFName.of('Names'),PDFArray),file=names.lookup(1,PDFDict),stream=file.lookup(PDFName.of('EF'),PDFDict).lookup(PDFName.of('F'),PDFRawStream);return {pdf,data:JSON.parse(new TextDecoder().decode(decodePDFRawStream(stream).decode()))};}
let close={communityId:summary.communityId,period:summary.period,versionId:summary.actualCloseVersion,contentHash:summary.actualContentHash,sourceHash:'c'.repeat(64),publicationId:'publication-1',budgetVersion:summary.budgetVersion,sourceFile:'fixture.xlsx',financialSnapshot:retained,carryIn:[],rows:[{gl_code:'004110',account_name:'Rental income',actual:0,ytd_actual:null,source_location:{sheet:'BCR',cell:'C12'}},{gl_code:'006210',account_name:'Expense credit',actual:-4.21,ytd_actual:-4.21,source_location:{sheet:'BCR',cell:'C13'}}]};
// Optional real-source rerun stays outside Git and never changes canonical data.
const certificatePath=process.env.ATLAS_PRIVATE_CERTIFICATE;
if(certificatePath){const certificate=JSON.parse(await readFile(certificatePath,'utf8'));close={...close,period:certificate.metadata.period,sourceHash:certificate.sourceHash,sourceFile:'redacted-source.xlsx',rows:certificate.rows.filter(row=>row.kind==='posting').map(row=>({gl_code:row.glCode,account_name:row.accountName,actual:row.values.actual,ytd_actual:row.values.ytdActual,source_location:row.source}))};assert(close.rows.length>0);close.financialSnapshot=financeSnapshot({...summary,period:close.period,actualCloseVersion:'isolated-real-source-rerun',actualContentHash:sha256(canonicalJson(close.rows))},'isolated-not-published');}
const rows=closeReportRows(close),bytes=await closeReportPdf(close),parsed=await evidence(bytes);assert.deepEqual(parsed.data.rows,JSON.parse(canonicalJson(rows)));assert.deepEqual(parsed.data.snapshot,close.financialSnapshot);assert.equal(parsed.pdf.getSubject(),close.financialSnapshot.fingerprint);assert(parsed.pdf.getPageCount()>=2);
const html=closeReportHtml(close),book=closeReportWorkbook(close,XLSX),reread=XLSX.read(XLSX.write(book,{type:'buffer',bookType:'xlsx'}),{type:'buffer'});assert.deepEqual(XLSX.utils.sheet_to_json(reread.Sheets['Canonical actuals'],{defval:null}),rows);assert(html.includes(close.financialSnapshot.fingerprint));
const scenario={identity:{communityId:'fixture-community',periods:['2026-02'],reforecastVersion:'r1',actualCutoff:null,baselineVersionIds:['budget-1'],mappingRegistryVersion:'map-1',driverVersion:'drivers-1'},lines:[{period:'2026-02',accountCode:'004110',accountName:'Rent',nature:'income',placement:'above_noi',originalBudget:0,forecast:0,actual:null}],monthly:[{period:'2026-02',closed:false,originalBudget:{revenue:0},reforecast:{revenue:0},actuals:null}]};
const forecastBytes=await reportPdf(scenario,null),forecastEvidence=await evidence(forecastBytes);assert.deepEqual(forecastEvidence.data.rows,JSON.parse(canonicalJson(exportRows(scenario,null))));assert.equal(forecastEvidence.data.snapshot.fingerprint,forecastSnapshot(scenario).fingerprint);assert.notEqual(reportSnapshot(scenario,{actuals:{cutoffPeriod:'2026-02',closeVersions:[{period:'2026-02',versionId:'new-close'}],lines:[]}},{actualsMode:'latest'}).fingerprint,forecastSnapshot(scenario).fingerprint);
if(process.env.ATLAS_OUTPUT_PROOF_DIR){await mkdir(process.env.ATLAS_OUTPUT_PROOF_DIR,{recursive:true});await writeFile(process.env.ATLAS_OUTPUT_PROOF_DIR+'/financial-output.pdf',bytes);await writeFile(process.env.ATLAS_OUTPUT_PROOF_DIR+'/reforecast-output.pdf',forecastBytes);await writeFile(process.env.ATLAS_OUTPUT_PROOF_DIR+'/financial-output-sanitized-proof.json',JSON.stringify({realSource:!!certificatePath,sourceHash:close.sourceHash,rowCount:rows.length,pages:parsed.pdf.getPageCount(),snapshotFingerprint:close.financialSnapshot.fingerprint,pdfAttachmentExact:true,xlsxRoundtripExact:true,screenFingerprintExact:true,publicationScope:'isolated output acceptance, no production publication'},null,2));}
console.log('PASS SHA-256 known vectors; retained finance/Community Plan/Bonus lineage; distinct vintages and current-actual projections; real PDF attached exact evidence, XLSX roundtrip, screen fingerprint and missing/zero/negative/leading-zero parity. '+(certificatePath?'Private real-source output rerun completed.':'Synthetic regression only.'));
