// Isolated packaging/gate tests. No cloud credentials, database, or browser data.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {execFileSync} from 'node:child_process';
import {prepareFinanceRelease,verifyFinanceArtifact,validateFinanceReleaseSelection,OPERATIONAL_RELEASE} from './build-atlas-finance-release.mjs';
const original=path.resolve(import.meta.dirname,'..');
const git=(args,cwd=original)=>execFileSync('git',args,{cwd,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
const workflow=await fs.readFile(path.join(original,'.github/workflows/deploy-cloudflare.yml'),'utf8');
const condition=workflow.match(/^  production:\n    if: (.+)$/m)[1];
const allowed=(event,ref,target,hash='',ready='',rollback='')=>Function('github','inputs','vars',`return ${condition}`)({event_name:event,ref},{target,finance_release_hash:hash,client_rollback_ref:rollback,client_rollback_release:rollback},{ATLAS_SCOPED_WORKSPACE_READY:ready});
assert.equal(allowed('push','refs/heads/main','',''),false);
assert.equal(allowed('workflow_dispatch','refs/heads/main','production',''),false);
assert.equal(allowed('workflow_dispatch','refs/heads/main','production','a'.repeat(64)),true);
assert.equal(allowed('workflow_dispatch','refs/heads/main','preview','a'.repeat(64)),false);
assert.equal(allowed('push','refs/heads/feature','','a'.repeat(64)),false);
assert.throws(()=>validateFinanceReleaseSelection({expectedReleaseId:'main'}),/64-character/);
assert.throws(()=>validateFinanceReleaseSelection({expectedReleaseId:'a'.repeat(64),clientRef:'b'.repeat(40)}),/mutually exclusive/);
assert.throws(()=>validateFinanceReleaseSelection({expectedReleaseId:'a'.repeat(64),clientRelease:'b'.repeat(64)}),/mutually exclusive/);
assert.match(workflow,/Validate explicit finance compatibility selection/);
assert.match(workflow,/if: env.ATLAS_CLIENT_ROLLBACK_REF == '' && env.ATLAS_FINANCE_RELEASE_HASH == ''/);
assert.match(workflow,/--config output\/atlas-finance-wrangler.json/);
assert.match(workflow,/Verify the finance artifact is unchanged before Pages/);
const temp=await fs.mkdtemp(path.join(os.tmpdir(),'atlas-finance-release-test-'));
try{
 const repo=path.join(temp,'repo'),remote=path.join(temp,'retention.git');
 git(['clone','--shared','--no-checkout',original,repo]);git(['checkout','--detach','HEAD'],repo);
 git(['init','--bare',remote]);git(['fetch',original,'7e95604058b1f36de76502d63128ad7eff4d3aac:refs/heads/atlas-asset-releases'],remote);git(['remote','set-url','origin',remote],repo);
 const before=git(['ls-remote','--heads','origin','atlas-asset-releases'],repo),status=git(['status','--porcelain'],repo);
 await assert.rejects(prepareFinanceRelease({repo,mode:'publish'}),/independently reviewed/);
 const receipt=await prepareFinanceRelease({repo});
 assert.equal(receipt.mode,'preview');assert.equal(receipt.operationalRelease,OPERATIONAL_RELEASE);
 assert.equal(receipt.releaseId,receipt.composition.composedSourceId,'Reviewed composed source is exactly the packed release');
 assert.equal(git(['ls-remote','--heads','origin','atlas-asset-releases'],repo),before,'Preview cannot publish retention');
 assert.equal(git(['status','--porcelain'],repo),status,'Composition cannot alter checked-out source');
 assert(receipt.retainedReleaseIds.includes(OPERATIONAL_RELEASE));
 await verifyFinanceArtifact({repo,expectedReleaseId:receipt.releaseId});
 assert.equal(receipt.composition.changedOperationalFiles.length,19);assert.equal(receipt.composition.unchangedOperationalFileCount,236);
 const archiveFile=path.join(receipt.out,'portfolio-operations-dashboard/migration-archive.js'),archiveBytes=await fs.readFile(archiveFile);
 await fs.writeFile(archiveFile,Buffer.concat([archiveBytes,Buffer.from('archive-tamper')]));await assert.rejects(verifyFinanceArtifact({repo,expectedReleaseId:receipt.releaseId}),/Canonical finance asset changed/);await fs.writeFile(archiveFile,archiveBytes);
 const config=JSON.parse(await fs.readFile(receipt.configPath,'utf8')),sourceConfig=JSON.parse(await fs.readFile(path.join(repo,'wrangler.jsonc'),'utf8'));
 assert.deepEqual(config.durable_objects,sourceConfig.durable_objects);assert.deepEqual(config.migrations,sourceConfig.migrations);assert.deepEqual(config.secrets,sourceConfig.secrets);assert(!config.build);
 const file=path.join(receipt.out,'portfolio-operations-dashboard/index.html'),bytes=await fs.readFile(file);
 await fs.writeFile(file,Buffer.concat([bytes,Buffer.from('tamper')]));await assert.rejects(verifyFinanceArtifact({repo,expectedReleaseId:receipt.releaseId}),/Canonical finance asset changed/);await fs.writeFile(file,bytes);
 await assert.rejects(prepareFinanceRelease({repo,mode:'publish',expectedReleaseId:'0'.repeat(64)}),/independently reviewed expected release hash/);
 assert.equal(git(['ls-remote','--heads','origin','atlas-asset-releases'],repo),before,'Mismatched source cannot publish retention');
 const published=await prepareFinanceRelease({repo,mode:'publish',expectedReleaseId:receipt.releaseId});
 assert.equal(published.releaseId,receipt.releaseId);assert.deepEqual(published.retainedReleaseIds,receipt.retainedReleaseIds);
 const retained=git(['ls-remote','--heads','origin','atlas-asset-releases'],repo);
 await prepareFinanceRelease({repo,mode:'publish',expectedReleaseId:receipt.releaseId});
 assert.equal(git(['ls-remote','--heads','origin','atlas-asset-releases'],repo),retained,'Exact retry does not rewrite retention');
 console.log('PASS explicit compatibility gate, mismatched hash fail-closed, source preservation, one-artifact verification, current Worker/bindings, full retained history and idempotent publication on a local bare remote');
}finally{await fs.rm(temp,{recursive:true,force:true});}
