import assert from 'node:assert/strict';
import {suggestMonthlyMappings,confirmMonthlyGovernance,monthlyGovernanceIssues} from '../docs/portfolio-operations-dashboard/features/financial-workbook-governance.mjs';
import {finalizeFinancialPackageEvidence} from '../docs/portfolio-operations-dashboard/features/financial-package.mjs';
const c={sourceFile:'source.xlsx',metadata:{period:'2028-04',basis:'accrual'},rows:[{kind:'posting',glCode:'004110',accountName:'Rent',source:{rowId:'BCR!10',sheet:'BCR',row:10,cells:{actual:'C10'}},values:{actual:0}}],intakeEvidence:{mappingVersion:'reviewed-v1',confirmedBy:'reviewer',hierarchy:[{metricKey:'revenue',factors:{'BCR!10':1}}],workbookAudit:{schemaVersion:'atlas.workbook-integrity.v1',inventory:{sheets:[]},fingerprint:'a'.repeat(64),findings:[]}}};
const options={reportingBasis:'calendar',fiscalStartMonth:1,currency:'USD',reason:'Reviewed monthly source mapping',mappings:suggestMonthlyMappings(c),findingsReviewed:true,actor:'reviewer'};
c.intakeEvidence.governance=confirmMonthlyGovernance(c,options);assert.deepEqual(monthlyGovernanceIssues(c),[]);assert.equal(c.intakeEvidence.governance.mappings[0].glCode,'004110');
for(const [field,value] of [['reportingBasis',null],['fiscalStartMonth',7],['currency','Local'],['scenario','plan'],['mappingVersion','wrong']]){const changed=structuredClone(c);changed.intakeEvidence.governance[field]=value;assert(monthlyGovernanceIssues(changed).length,field);}
for(const update of [{nature:''},{placement:''},{signMultiplier:0},{signMultiplier:-1},{nature:'expense'},{source:{sheet:'other',row:10,address:'C10'}}]){const changed=structuredClone(c);Object.assign(changed.intakeEvidence.governance.mappings[0],update);assert(monthlyGovernanceIssues(changed).length);}
for(const review of [{reason:'short'},{owner:'other'},{effectivePeriod:'2028-05'}]){const changed=structuredClone(c);Object.assign(changed.intakeEvidence.governance.review,review);assert(monthlyGovernanceIssues(changed).includes('mapping_review_owner_period'));}
const blocked=structuredClone(c);blocked.intakeEvidence.workbookAudit.findings=[{severity:'blocking',code:'circular_dependency'}];assert(monthlyGovernanceIssues(blocked).includes('workbook_dependency_blocked'));
console.log('PASS explicit monthly calendar/scenario/currency, complete account interpretation/source coordinates, reviewer/reason/effective period and unwaivable dependency blockers.');
