import assert from 'node:assert/strict';
import {financialValue,classifyStatement,parseComparisonSheet,parseComparisonLines,reconcileComparison,resolveCommunity,favorableVariance} from '../docs/portfolio-operations-dashboard/features/financial-package.mjs';
assert.deepEqual(financialValue(null),{value:null,status:'missing'});
assert.equal(financialValue('0.00').value,0);assert.equal(financialValue('(1,200.25)').value,-1200.25);
assert.equal(financialValue('—').status,'unavailable');assert.equal(financialValue('N/A').status,'not_applicable');assert.equal(financialValue('2,1O0.00').status,'invalid');
for(const [s,type]of [['RISE - Budget Comparison - Income Statement','budget_comparison'],['Forecasted Income Statement','forecast'],['T12 Income Statement','t12'],['Trial Balance','trial_balance'],['Invoice','supporting_document'],['RISE - GL Details','gl_detail']])assert.equal(classifyStatement(s),type);
const heading='RISE - Budget Comparison - Income Statement\nTest Property\nAug 2026\nAccrual Basis\nYTD ( Jan 2026 - Aug 2026 )';
const line=(code,name,a,b)=>`${code}  ${name}  ${a.toFixed(2)}  ${b.toFixed(2)}  ${(a-b).toFixed(2)}  0.00%  ${a.toFixed(2)}  ${b.toFixed(2)}  ${(a-b).toFixed(2)}  0.00%  ${b.toFixed(2)}`;
const text=heading+'\n'+['Income',line('5120','GPR',100,120),line('','Total Income',100,120),'Expenses',line('6500','Expense',25,20),line('','Net Operating Income',75,100)].join('\n');
const parsed=parseComparisonLines(text,{page:3});assert.equal(parsed.rows.length,4);assert.equal(reconcileComparison([parsed]).technicalReconciled,true);
const corrupt=structuredClone(parsed);corrupt.rows[0].values.actual=101;assert.equal(reconcileComparison([corrupt]).technicalReconciled,false);
const duplicate=structuredClone(parsed);duplicate.rows.push(duplicate.rows[0]);assert(reconcileComparison([duplicate]).exceptions.some(e=>e.code==='duplicate_gl'));
assert.equal(parseComparisonLines('Invoice\n'+text).rows.length,0,'supporting documents cannot masquerade as statements');
const wrong=structuredClone(parsed);wrong.metadata.sourceProperty='Other property';assert(reconcileComparison([parsed,wrong]).exceptions.some(e=>e.code==='conflicting_source_scope'));
assert.equal(favorableVariance(10,20,'higher_is_favorable'),-10);assert.equal(favorableVariance(10,20,'lower_is_favorable'),10);assert.equal(favorableVariance(0,null,'lower_is_favorable'),null);
assert.equal(resolveCommunity('Ruston',[{community_id:'a',display_name:'The Preserve at Tech'}],[{alias:'Ruston',community_id:'a',active:true}]).communityId,'a');
assert.equal(resolveCommunity('Unknown',[],[]).communityId,null);
assert.equal(resolveCommunity('X',[{community_id:'a',display_name:'X'},{community_id:'b',display_name:'X'}],[]).communityId,null);
const sheet=[[],['RISE - Budget Comparison - Income Statement'],['Test Property'],['Aug 2026'],['Accrual Basis'],[],['','','Aug 2026','','','','YTD ( Jan 2026 - Aug 2026 )'],[],[],['5120','GPR',0,null,0,0,0,null,0,0,null]];
const result=parseComparisonSheet(sheet,'Budget Comparison');assert.equal(result.rows[0].values.actual,0);assert.equal(result.rows[0].values.budget,null);
console.log('PASS statement isolation, source identity, arithmetic, duplicate GLs, missing/zero and explicit favorability');
