const assert=require('node:assert/strict'),{randomUUID,createHash}=require('node:crypto'),fs=require('node:fs'),{fixture}=require('./financial-intake-fixture.cjs');
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
const stamp=c=>{delete c.intakeEvidence.evidenceFingerprint;c.intakeEvidence.evidenceFingerprint=createHash('sha256').update(canonical(c.intakeEvidence)).digest('hex');return c;};
const actor='00000000-0000-0000-0000-000000000001';
function certificate(cid,period='2026-03',income=100){
 const rows=[],inventory=[],hierarchy=[],mappingVersion='reviewed-test-mapping-v1',sourceHash=createHash('sha256').update(period+'|'+income).digest('hex'),column={sheet:'BCR',column:'C',header:period+' Actual',period,type:'monthly_actual'};
 const add=(id,kind,code,label,amount,metric,children,factors)=>{const row=Number(id.split('!')[1]);inventory.push({id,sheet:'BCR',row,rawLabel:label,normalizedLabel:label,disposition:kind==='posting'?'mapped_leaf':'mapped_control',reason:'Reviewed source row',sourceHash,mappingVersion,included:true,glCode:code,columnMapping:{actual:column},actual:{value:amount,type:'number',blank:false,column:'C',period},rawCells:[{address:'C'+row,column:'C',value:amount,type:'n'}]});rows.push({kind,glCode:code,accountName:label,values:{actual:amount,budget:999,ytdActual:amount+777,ytdBudget:null,annualBudget:12000},source:{sheet:'BCR',row,rowId:id}});if(kind==='control'||metric)hierarchy.push({id:'control:'+id,sourceRowId:id,kind:kind==='posting'?'leaf_control':'rollup',metricKey:metric,sourceTotal:amount,childRowIds:children||[id],factors:factors||{[id]:1},tolerance:.01});};
 add('BCR!1','posting','8101','Gross Potential Rent',income,'gpr');add('BCR!2','posting','8102','Vacancy',-10);add('BCR!3','control',null,'Net Rental Income',income-10,'netRentalIncome',['BCR!1','BCR!2'],{'BCR!1':1,'BCR!2':1});add('BCR!4','control',null,'Total Income',income-10,'revenue',['BCR!1','BCR!2'],{'BCR!1':1,'BCR!2':1});add('BCR!5','posting','9101','Expense',40);add('BCR!6','posting','9102','Explicit zero expense',0);add('BCR!7','control',null,'Net Operating Income',income-50,'noi',['BCR!1','BCR!2','BCR!5','BCR!6'],{'BCR!1':1,'BCR!2':1,'BCR!5':-1,'BCR!6':-1});add('BCR!8','posting','9200','Capital',5);add('BCR!9','control',null,'Net Cash Flow',income-55,'cashFlow',['BCR!1','BCR!2','BCR!5','BCR!6','BCR!8'],{'BCR!1':1,'BCR!2':1,'BCR!5':-1,'BCR!6':-1,'BCR!8':-1});
 for(const [id,disposition,label]of[['BCR!10','memo_statistical','Square feet'],['BCR!11','header_or_section','Notes'],['BCR!12','duplicate','Repeated account evidence'],['T12!1','supporting','Prior year actual history']])inventory.push({id,sheet:id.split('!')[0],row:Number(id.split('!')[1]),rawLabel:label,normalizedLabel:label,disposition,reason:'Explicit reviewed disposition',sourceHash,mappingVersion,included:false,duplicateOf:disposition==='duplicate'?'BCR!1':null,columnMapping:{actual:column},actual:{value:null,type:'blank',blank:true,column:'C',period},rawCells:[{address:'A1',column:'A',value:label,type:'s'}]});
 const inventoryCounts={total:inventory.length,...Object.fromEntries(['mapped_leaf','mapped_control','header_or_section','memo_statistical','supporting','duplicate','excluded','unresolved'].map(k=>[k,inventory.filter(r=>r.disposition===k).length]))};
 return stamp({schemaVersion:1,sourceFile:'Generic BCR.xlsx',sourceHash,metadata:{sourceProperty:'Doro',period,basis:'accrual'},rows,exceptions:[],intakeEvidence:{version:1,parserVersion:'test-parser/2',sourceKind:'bcr',workflow:'monthly_close',mappingVersion,communityId:cid,communityConfirmed:true,periodConfirmed:true,exclusionsReviewed:true,confirmedBy:actor,confirmedAt:'2026-09-23T00:00:00Z',rowInventory:inventory,inventoryCounts,hierarchy,selectedActualColumn:column,selectedActualColumns:[column],sourceSheets:[{sheet:'BCR',sourceHash,inventoryCount:12},{sheet:'T12',sourceHash,inventoryCount:1}],coverage:{classification:'full_month'}}});
}
(async()=>{const {db,cid,other,signIn}=await fixture(),call=async(name,args)=>(await db.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
 const evidence=c=>({sourceHash:c.sourceHash,sourceFile:c.sourceFile,certificate:c});
 const stage=async(c,{through='reconciled',communityId=null}={})=>{let result;for(const state of ['uploaded','classified','community_period_confirmed','fully_mapped','reconciled']){result=await call('atlas_record_financial_intake',[result?.workflow.workflow_id||null,randomUUID(),result?.receipt.receipt_id||null,state,['uploaded','classified'].includes(state)?communityId:cid,evidence(c)]);if(state===through)break;}return result;};
 const save=async c=>{const staged=await stage(c);return call('atlas_save_financial_review_governed',[staged.workflow.workflow_id,staged.receipt.receipt_id,randomUUID(),c]);};
 const close=async(review,prior=null,id=randomUUID())=>call('atlas_close_financial_review_governed',[review.review_id,prior,id,'Reviewed full row evidence',true]);
 const read=async p=>(await call('atlas_read_finance',[[cid],[p]]))[0];
 let c=certificate(cid),staged=await stage(c,{through:'classified'});assert.equal(staged.workflow.community_id,null);assert.equal(staged.workflow.period_key,'2026-03');assert.equal(staged.receipt.inventory_count,13,'Early receipts preserve observed inventory without claiming reconciliation');assert.equal(staged.receipt.evidence.validation.validationComplete,false);
 await signIn(2);assert.equal((await db.query('select * from atlas_financial_intake_receipts where workflow_id=$1',[staged.workflow.workflow_id])).rows.length,0,'Unassigned upload owner only');await signIn(1);
 await assert.rejects(()=>call('atlas_record_financial_intake',[staged.workflow.workflow_id,randomUUID(),null,'community_period_confirmed',cid,evidence(c)]),/another session/);
 const reviewed=await save(c);assert.equal(reviewed.receipt.state,'Review Saved');assert.equal(reviewed.receipt.leaf_count,5);assert.equal(reviewed.receipt.inventory_count,13);
 const receiptRows=(await db.query('select status from atlas_financial_intake_receipts where workflow_id=$1 order by created_at,receipt_id',[reviewed.workflow.workflow_id])).rows;assert.equal(receiptRows.length,6);
 const request=randomUUID(),closed=await close(reviewed.review,null,request);assert.equal(closed.receipt.status,'canonically_published');assert.equal(closed.close.metrics.totalIncome,90);assert.equal(closed.close.metrics.operatingExpenses,40);assert.equal(closed.close.metrics.grossPotentialRent,100,'GPR role has no fixed GL code');assert.equal(closed.close.row_count,5);assert.equal((await close(reviewed.review,null,request)).close.version_id,closed.close.version_id);
 const verified=await call('atlas_verify_finance_receipt',[closed.receipt.receipt_id,closed.close.version_id,closed.close.content_hash]);assert.equal(verified.status,'readback_verified');assert.equal(verified.version_id,closed.close.version_id);await assert.rejects(()=>call('atlas_verify_finance_receipt',[closed.receipt.receipt_id,closed.close.version_id,'bad-hash']),/mismatch/);
 const initial=(await db.query('select * from atlas_read_finance($1,$2)',[[cid],['2026-03']])).rows[0];assert.equal(initial.summary.actualCloseVersion,closed.close.version_id);assert.equal(initial.summary.noi.actual,50);assert.equal(initial.summary.revenue.actual,90,'YTD/budget never promoted to monthly actuals');
 await signIn(2);const second=(await db.query('select * from atlas_read_finance($1,$2)',[[cid],['2026-03']])).rows[0];assert.deepEqual(second,initial);assert.equal((await db.query('select * from atlas_financial_intake_receipts where workflow_id=$1',[reviewed.workflow.workflow_id])).rows.length,9,'Assigned workflow receipts accessible to independent authorized reviewer');await assert.rejects(()=>close(reviewed.review),/Only an active Admin/);await signIn(1);
 const badLeaf=structuredClone(c);badLeaf.rows[0].values.actual++;const badInventory=structuredClone(c);badInventory.intakeEvidence.rowInventory.pop();stamp(badInventory);const noRollup=structuredClone(c);noRollup.intakeEvidence.hierarchy=noRollup.intakeEvidence.hierarchy.filter(n=>n.sourceRowId!=='BCR!7');stamp(noRollup);const blank=structuredClone(c);blank.rows[3].values.actual=null;stamp(blank);const t12=structuredClone(c);t12.intakeEvidence.sourceKind='t12';stamp(t12);
 for(const broken of [badLeaf,badInventory,noRollup,blank,t12])await assert.rejects(()=>save(broken),/incomplete|reconcile/);
 // A stale certificate cannot bypass stage validation by calling the old direct save/close paths.
 await assert.rejects(()=>call('atlas_save_financial_package_review',[cid,c]),/durable intake/);
 // An injected projection failure must preserve both the previous close and its verified publication.
 const replacement=await save(certificate(cid,'2026-03',120));await db.exec("reset role;create function atlas_private.fail_intake_projection() returns trigger language plpgsql as $$begin raise exception 'test projection rollback';end;$$;create trigger fail_intake_projection before update on atlas_command_financial_summaries for each row execute function atlas_private.fail_intake_projection();");await signIn(1);await assert.rejects(()=>close(replacement.review,closed.close.version_id),/test projection rollback/);assert.equal((await db.query('select version_id from atlas_financial_close_heads where community_id=$1',[cid])).rows[0].version_id,closed.close.version_id);await db.exec('reset role;drop trigger fail_intake_projection on atlas_command_financial_summaries');await signIn(1);
 // Retain historical February evidence while withdrawing its full-month authority through explicit policy.
 const feb=await close((await save(certificate(cid,'2026-02',30))).review);
 const policyPayload={firstFullMonth:'2026-03',effectiveDate:'2026-09-23',reason:'Accounting begins in March; February retained as startup evidence',periodOverrides:[{period:'2026-01',classification:'unavailable',reason:'Outside authoritative accounting coverage',retainedVersionIds:[]},{period:'2026-02',classification:'partial_startup',reason:'Retain source evidence without asserting full-month close',retainedVersionIds:[feb.close.version_id]}],carryIn:[{reportedPeriod:'2026-03',sourcePeriods:['2026-02'],treatment:'source_ytd_only',reason:'Printed source YTD contains prior startup activity; monthly March unchanged',versionIds:[feb.close.version_id,closed.close.version_id]}]};
 await assert.rejects(()=>call('atlas_set_financial_coverage_policy',[cid,null,randomUUID(),{...policyPayload,effectiveDate:null}]),/date and reason required/);
 const policy=await call('atlas_set_financial_coverage_policy',[cid,null,randomUUID(),policyPayload]);const febRead=(await db.query('select * from atlas_read_finance($1,$2)',[[cid],['2026-02']])).rows[0].summary;assert.equal(febRead.actualCloseVersion,null);assert.equal(febRead.noi.actual,null);assert.equal(febRead.coveragePolicy.classification,'partial_startup');assert.equal((await db.query('select metrics from atlas_financial_close_versions where version_id=$1',[feb.close.version_id])).rows[0].metrics.totalIncome,20,'Old version retained intact');
 const jan=(await db.query('select atlas_private.finance_envelope($1,$2) s',[cid,'2026-01']).catch(()=>({rows:[]}))).rows;assert.equal(jan.length,0,'Private helpers cannot be called directly');const march=(await db.query('select * from atlas_read_finance($1,$2)',[[cid],['2026-03']])).rows[0].summary;assert.equal(march.noi.actual,50);assert.equal(march.firstExpectedFinancialPeriod,'2026-03');assert.equal(march.completeYtd,true);assert.equal(march.carryInDisclosure[0].treatment,'source_ytd_only');
 await assert.rejects(()=>call('atlas_verify_finance_receipt',[feb.receipt.receipt_id,feb.close.version_id,feb.close.content_hash]),/superseded/);
 const source=await call('atlas_read_reforecast_source',[cid,['2026-01','2026-02','2026-03'],null,null]);assert.deepEqual(source.actuals.closeVersions.map(r=>r.period),['2026-03']);assert(source.actuals.notApplicablePeriods.includes('2026-02'));
 const changedMarch=certificate(cid,'2026-03',120);changedMarch.intakeEvidence.coverage.carryIn=policyPayload.carryIn;stamp(changedMarch);const cm=await close((await save(changedMarch)).review,closed.close.version_id);assert.equal(cm.close.metrics.totalIncome,110,'Carry-in does not add February to monthly March');
 // Approved budget publication includes durable receipt/hash and every fiscal-segment month.
 const budget={communityId:cid,year:2026,fiscalYear:2026,fiscalStartMonth:1,scenarioId:'approved',scenarioVersion:'one',effectiveDate:'2026-01-01',sourceFile:'approved-budget.xlsx',sourceHash:'a'.repeat(64),sourceHashKind:'workbook_bytes',approvedLocked:true,reviewConfirmed:true,registryVersion:'atlas-finance-v1',mappingVersion:'reviewed-owner-budget-v1',coverage:Array.from({length:12},(_,i)=>i),occupancyPct:Array(12).fill(null),rows:[{glCode:'8101',monthly:Array(12).fill(100)},{glCode:'9101',monthly:Array(12).fill(40)}],metricMappings:{gpr:[{glCode:'8101',factor:1}],revenue:[{glCode:'8101',factor:1}],expenses:[{glCode:'9101',factor:1}],noi:[{glCode:'8101',factor:1},{glCode:'9101',factor:-1}]}};
 await assert.rejects(()=>call('atlas_approve_original_budget_governed',[cid,randomUUID(),{...budget,sourceHashKind:null}]),/source hash basis/);
 const bid=randomUUID(),approved=await call('atlas_approve_original_budget_governed',[cid,bid,budget]);assert(approved.budget.version_id&&approved.budget.content_hash);assert.equal(approved.publications.length,12);assert.equal((await call('atlas_approve_original_budget_governed',[cid,bid,budget])).budget.version_id,approved.budget.version_id);assert.equal((await call('atlas_verify_finance_receipt',[approved.receipt.receipt_id,approved.budget.version_id,approved.budget.content_hash])).status,'readback_verified');await assert.rejects(()=>call('atlas_approve_original_budget_governed',[cid,randomUUID(),{...budget,coverage:[0,1]}]),/every month/);await assert.rejects(()=>call('atlas_approve_original_budget_governed',[cid,bid,{...budget,scenarioVersion:'different'}]),/request ID reused/);
 const janPublished=(await db.query('select * from atlas_read_finance($1,$2)',[[cid],['2026-01']])).rows[0].summary;assert.equal(janPublished.noi.actual,null);assert.equal(janPublished.noi.status,'unavailable');assert.equal(janPublished.coveragePolicy.classification,'unavailable');assert.equal(janPublished.actualCloseVersion,null);
 await signIn(2);assert.equal((await db.query('select version_id from atlas_approved_budget_versions where version_id=$1',[approved.budget.version_id])).rows[0].version_id,approved.budget.version_id);await assert.rejects(()=>call('atlas_approve_original_budget_governed',[cid,randomUUID(),budget]),/Only an active/);await signIn(3);assert.equal((await db.query('select * from atlas_financial_intake_workflows where community_id=$1',[cid])).rows.length,0);await signIn(1);
 // Multi-page PDF evidence selects one monthly actual column on each page, never the first page alone.
 const paged=structuredClone(c);const page1={...paged.intakeEvidence.selectedActualColumn,sheet:'PDF page 1'},page2={...page1,sheet:'PDF page 2'};
 for(const r of paged.intakeEvidence.rowInventory)if(r.sheet==='BCR'){r.sheet=r.row<=4?'PDF page 1':'PDF page 2';r.columnMapping.actual=r.row<=4?page1:page2;}
 for(const r of paged.rows)r.source.sheet=r.source.row<=4?'PDF page 1':'PDF page 2';
 paged.intakeEvidence.selectedActualColumn=page1;paged.intakeEvidence.selectedActualColumns=[page1,page2];paged.intakeEvidence.sourceSheets=[{sheet:'PDF page 1',sourceHash:c.sourceHash,inventoryCount:4},{sheet:'PDF page 2',sourceHash:c.sourceHash,inventoryCount:8},{sheet:'T12',sourceHash:c.sourceHash,inventoryCount:1}];stamp(paged);
 await db.exec('reset role');assert.equal((await db.query('select atlas_private.finance_intake_validation($1,$2) v',[paged,cid])).rows[0].v.reconciled,true);
 paged.intakeEvidence.selectedActualColumns[1].period='2026-02';stamp(paged);assert.equal((await db.query('select atlas_private.finance_intake_validation($1,$2) v',[paged,cid])).rows[0].v.reconciled,false,'Cross-page reporting period cannot drift');
 // New records remain immutable, scoped, and unreachable through privileged helper calls.
 await db.exec('reset role');
 const {canonicalEvidence}=await import('../docs/portfolio-operations-dashboard/features/financial-row-reconciliation.mjs');const numericEvidence={tiny:1.25e-7,large:-1.25e21,nested:[-0,null,1e-7,1e21,NaN]};assert.equal((await db.query('select atlas_private.finance_canonical_json($1) value',[numericEvidence])).rows[0].value,canonicalEvidence(numericEvidence));
 const tableNames=['atlas_financial_intake_workflows','atlas_financial_intake_receipts','atlas_financial_review_intakes','atlas_financial_coverage_policies','atlas_financial_coverage_heads'];
 for(const name of tableNames){const rights=(await db.query("select relrowsecurity,has_table_privilege('anon',$1,'SELECT') anon_read,has_table_privilege('authenticated',$1,'INSERT,UPDATE,DELETE') client_write from pg_class where oid=$1::regclass",[name])).rows[0];assert.equal(rights.relrowsecurity,true,name);assert.equal(rights.anon_read,false,name);assert.equal(rights.client_write,false,name);}
 for(const fn of ['finance_intake_validation(jsonb,uuid)','finance_receipt(uuid,text,uuid,text,jsonb,jsonb,uuid,text,uuid,uuid[])','approve_original_budget_validated(uuid,jsonb)','atlas_save_financial_package_review_legacy(uuid,jsonb)','reforecast_source_pre_coverage_policy(uuid,text[],uuid[],uuid)'])assert.equal((await db.query("select has_function_privilege('authenticated',$1,'EXECUTE') permitted",['atlas_private.'+fn])).rows[0].permitted,false,fn);
 await assert.rejects(()=>db.query("update atlas_financial_intake_receipts set source_hash=repeat('b',64) where receipt_id=$1",[verified.receipt_id]),/immutable/i);
 await signIn(1);
 // Optional private acceptance runs the actual approved source through all durable states and verifies both independent readers.
 const realPath=process.env.ATLAS_REAL_BCR_CERTIFICATE;if(realPath){
  const real=JSON.parse(fs.readFileSync(realPath,'utf8')),privateFixture=await fixture(),privateDb=privateFixture.db;
  const privateCall=async(name,args)=>(await privateDb.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
  await privateDb.exec('reset role');await privateDb.query('insert into atlas_community_aliases values($1,$2,true,$3)',[cid,real.metadata.sourceProperty,'private-acceptance']);
  const v=(await privateDb.query('select atlas_private.finance_intake_validation($1,$2) v',[real,cid])).rows[0].v;assert.equal(v.reconciled,true,JSON.stringify(v.issues));assert.equal(v.inventoryCount,683);assert.equal(v.checkedLeafCount,137);assert.equal(v.controlCount,35);
  await privateFixture.signIn(1);let intake;
  for(const state of ['uploaded','classified','community_period_confirmed','fully_mapped','reconciled'])intake=await privateCall('atlas_record_financial_intake',[intake?.workflow.workflow_id||null,randomUUID(),intake?.receipt.receipt_id||null,state,['uploaded','classified'].includes(state)?null:cid,evidence(real)]);
  const saved=await privateCall('atlas_save_financial_review_governed',[intake.workflow.workflow_id,intake.receipt.receipt_id,randomUUID(),real]);
  const committed=await privateCall('atlas_close_financial_review_governed',[saved.review.review_id,null,randomUUID(),'Private fixture full row reconciliation proof',true]);
  const proof=await privateCall('atlas_verify_finance_receipt',[committed.receipt.receipt_id,committed.close.version_id,committed.close.content_hash]);assert.equal(proof.status,'readback_verified');assert.equal(proof.leaf_count,137);
  const live=(await privateDb.query('select * from atlas_read_finance($1,$2)',[[cid],[real.metadata.period]])).rows[0];assert.equal(live.summary.actualCloseVersion,committed.close.version_id);assert.equal(live.summary.noi.actual,v.metrics.noi);assert.equal(live.summary.revenue.actual,v.metrics.revenue);
  await privateFixture.signIn(2);const otherReader=(await privateDb.query('select * from atlas_read_finance($1,$2)',[[cid],[real.metadata.period]])).rows[0];assert.deepEqual(otherReader,live);
  const mutatedPath=process.env.ATLAS_MUTATED_BCR_CERTIFICATE||realPath.replace('.json','-mutated.json');if(fs.existsSync(mutatedPath)){const mutated=JSON.parse(fs.readFileSync(mutatedPath,'utf8'));mutated.sourceFile??=real.sourceFile;await privateDb.exec('reset role');const invalid=(await privateDb.query('select atlas_private.finance_intake_validation($1,$2) v',[mutated,cid])).rows[0].v;assert.equal(invalid.reconciled,false);assert(invalid.issues.some(i=>i.code==='control_reconciliation'),'Changed real source amount breaks rebuilt rollups');await privateFixture.signIn(1);let next;for(const state of ['uploaded','classified','community_period_confirmed'])next=await privateCall('atlas_record_financial_intake',[next?.workflow.workflow_id||null,randomUUID(),next?.receipt.receipt_id||null,state,['uploaded','classified'].includes(state)?null:cid,evidence(mutated)]);next=await privateCall('atlas_record_financial_intake',[next.workflow.workflow_id,randomUUID(),next.receipt.receipt_id,'fully_mapped',cid,evidence(mutated)]);await assert.rejects(()=>privateCall('atlas_record_financial_intake',[next.workflow.workflow_id,randomUUID(),next.receipt.receipt_id,'reconciled',cid,evidence(mutated)]),/reconcile/);assert.equal((await privateDb.query('select version_id from atlas_financial_close_heads where community_id=$1',[cid])).rows[0].version_id,committed.close.version_id);}
  if(process.env.ATLAS_FINANCIAL_PROOF_PATH)fs.writeFileSync(process.env.ATLAS_FINANCIAL_PROOF_PATH,JSON.stringify({environment:'isolated local PGlite acceptance; not a production publication',verifiedAt:new Date().toISOString(),sourceHash:real.sourceHash,evidenceFingerprint:real.intakeEvidence.evidenceFingerprint,inventoryCount:v.inventoryCount,checkedLeafCount:v.checkedLeafCount,printedControlCount:v.controlCount,workflowId:saved.workflow.workflow_id,reviewId:saved.review.review_id,closeVersionId:committed.close.version_id,contentHash:committed.close.content_hash,publicationIds:proof.publication_ids,readbackReceiptId:proof.receipt_id,independentReaderMatched:true,alteredSourceRejected:true,financialValuesIncluded:false},null,2)+'\n');
  await privateDb.close();console.log('PASS private real BCR: 683 inventoried rows, 137 checked leaves, 35 printed rollups; durable save, close, publication, readback, independent reader, and changed-source rejection');
 }
 await db.close();console.log('PASS durable intake state receipts, complete row and hierarchy validation, transactional close/publication/readback, missing/zero/signed/monthly semantics, versioned coverage and budget approval, independent-session readback and scope.');
})().catch(e=>{console.error(e.message,e.where,e.stack);process.exitCode=1});
