import assert from 'node:assert/strict';
import {createIntake,prepareReview} from '../docs/portfolio-operations-dashboard/features/financial-intake-store.mjs';
import {parseComparisonSheet,reconcileComparison} from '../docs/portfolio-operations-dashboard/features/financial-package.mjs';
const cid='10000000-0000-0000-0000-000000000001',actor='10000000-0000-0000-0000-000000000002';
const amount=v=>[v,v,0,0,v,v,0,0,v*12];
const matrix=[['Budget Comparison - Income Statement'],['Example Property'],['Apr 2028'],['Accrual Basis'],[],[null,null,'Apr 2028',null,null,null,'YTD ( Jan 2028 - Apr 2028 )'],['Account','Account Name','Actual','Budget','$ Variance','% Variance','Actual','Budget','$ Variance','% Variance','Annual Budget'],['Income'],['Rental Income'],['4110','Gross Potential Rent (GPR)',...amount(0)],['','Total Income',...amount(0)],['Expenses'],['6210','Marketing Expense',...amount(0)],['','Total Expenses',...amount(0)],['','Net Operating Income',...amount(0)]];
const cells=Object.fromEntries(matrix.flatMap((row,i)=>row.map((v,c)=>[String.fromCharCode(65+c)+(i+1),{v,t:typeof v==='number'?'n':'s'}])));for(const [cell,f]of Object.entries({C11:'SUM(C10:C10)',C14:'SUM(C13:C13)',C15:'C11-C14'}))cells[cell].f=f;
const certificate=reconcileComparison([parseComparisonSheet(matrix,'BCR',{cells,sourceHash:'a'.repeat(64)})]);certificate.sourceHash='a'.repeat(64);certificate.sourceFile='synthetic.xlsx';
const durable={receipts:new Map(),reviews:new Map(),requests:new Map(),stages:[]};let activeActor=actor,throwOnce=true;
const central={getSession:()=>({user:{id:activeActor}}),async rpc(name,p){
 if(durable.requests.has(p.p_request_id))return structuredClone(durable.requests.get(p.p_request_id));
 const wid=p.p_workflow_id||crypto.randomUUID(),certificate=p.p_certificate||p.p_evidence.certificate;
 const receipt={receipt_id:crypto.randomUUID(),workflow_id:wid,community_id:p.p_community_id??(name.includes('save')?cid:null),status:name.includes('save')?'review_saved':p.p_stage,source_hash:certificate.sourceHash,previous_receipt_id:p.p_expected_receipt_id,actor_id:actor,created_at:new Date().toISOString()};
 const workflow={workflow_id:wid,current_receipt_id:receipt.receipt_id,status:receipt.status};let result={receipt,workflow};
 if(name.includes('save')){result.review={review_id:crypto.randomUUID(),content_hash:'c'.repeat(64),source_hash:certificate.sourceHash,community_id:cid,period_key:certificate.metadata.period,certificate};receipt.version_id=result.review.review_id;receipt.content_hash=result.review.content_hash;durable.reviews.set(result.review.review_id,result.review);}
 durable.receipts.set(receipt.receipt_id,receipt);durable.requests.set(p.p_request_id,result);durable.stages.push(receipt.status);
 if(throwOnce){throwOnce=false;throw Error('Acknowledgement interrupted');}return structuredClone(result);
 },async fetchJson(path){const id=path.match(/(?:receipt|review)_id=eq\.([^&]+)/)?.[1];return structuredClone([path.includes('receipts')?durable.receipts.get(id):durable.reviews.get(id)].filter(Boolean));}};
const flow=createIntake(central);await assert.rejects(flow.stage('uploaded',certificate),/interrupted/);await flow.stage('uploaded',certificate);assert.equal(durable.stages.length,1,'ambiguous acknowledgement retry reuses idempotency key');
const saved=await prepareReview(central,certificate,{communityId:cid,period:'2028-04',exclusionsReviewed:true,intake:flow});assert.deepEqual(durable.stages,['uploaded','classified','community_period_confirmed','fully_mapped','reconciled','review_saved']);assert.equal(saved.review.certificate.rows[0].values.actual,0);assert.equal(saved.intake.receipt.status,'review_saved');assert.ok(saved.review.review_id);assert.equal(durable.stages.includes('admin_closed'),false);
const fresh=createIntake(central,{workflow:saved.intake.workflow,receipt:saved.intake.receipt});assert.equal(fresh.receipt.receipt_id,saved.intake.receipt.receipt_id);const [reloaded]=await central.fetchJson('/atlas_financial_package_reviews?review_id=eq.'+saved.review.review_id);assert.deepEqual(reloaded,saved.review.intakeReceipt?Object.fromEntries(Object.entries(saved.review).filter(([k])=>k!=='intakeReceipt')):saved.review);
activeActor='other';await assert.rejects(fresh.stage('classified',certificate),/signed-in account changed/);activeActor=actor;
const partial=structuredClone(certificate);partial.rows[0].values.actual=null;await assert.rejects(prepareReview(central,partial,{communityId:cid,period:'2028-04',exclusionsReviewed:true}),/Review blocked/);
assert.equal(durable.stages.filter(x=>x==='review_saved').length,1);
console.log('PASS durable source stages, idempotent interrupted acknowledgement, explicit review gates, retained zero, central reload and actor guard; no automatic close/publication.');

let failStatus='uploaded';const baseFetch=central.fetchJson.bind(central);const flaky={...central,fetchJson:async path=>{const records=await baseFetch(path);if(path.includes('receipts')&&records[0]?.status===failStatus){failStatus=null;throw Error('Readback offline');}return records;}};
const retryFlow=createIntake(flaky);await assert.rejects(retryFlow.stage('uploaded',certificate),/offline/);assert.equal(retryFlow.receipt,null);const count=durable.stages.length;await retryFlow.stage('uploaded',certificate);assert.equal(durable.stages.length,count,'readback failure retry reuses original request');
failStatus='review_saved';await assert.rejects(prepareReview(flaky,certificate,{communityId:cid,period:'2028-04',exclusionsReviewed:true,intake:retryFlow}),/offline/);assert.equal(retryFlow.receipt.status,'reconciled');const staged=durable.stages.length;await prepareReview(flaky,certificate,{communityId:cid,period:'2028-04',exclusionsReviewed:true,intake:retryFlow});assert.equal(durable.stages.length,staged,'saved review retry must not duplicate review or change timestamp');
const corrected=createIntake(central);await assert.rejects(prepareReview(central,certificate,{communityId:cid,period:'2028-04',exclusionsReviewed:false,intake:corrected}),/exclusion_review_required/);assert.equal(corrected.receipt.status,'community_period_confirmed');const correctedResult=await prepareReview(central,certificate,{communityId:cid,period:'2028-04',exclusionsReviewed:true,intake:corrected});assert.equal(correctedResult.review.certificate.intakeEvidence.exclusionsReviewed,true);
console.log('PASS transient receipt/readback failure retains retry state and idempotency; corrected explicit exclusion confirmation creates a new retained evidence receipt.');
