/* Visible production workflow against isolated production SQL and synthetic figures. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright');
const cid='10000000-0000-0000-0000-000000000001',url='http://127.0.0.1:18801';let output='';
const server=spawn(process.execPath,['tools/reforecast-harness-server.cjs'],{env:{...process.env,PORT:'18801',ATLAS_GOVERNED_WORKFLOW_TEST:'1'},stdio:['ignore','pipe','pipe']});
await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error(output)),20000);server.once('exit',code=>{clearTimeout(timeout);reject(Error('Fixture startup '+code+': '+output));});for(const stream of [server.stdout,server.stderr])stream.on('data',chunk=>{output+=chunk;if(output.includes(url)){clearTimeout(timeout);resolve();}});});
const browser=await chromium.launch({headless:true,...(process.env.ATLAS_BROWSER_CHANNEL?{channel:process.env.ATLAS_BROWSER_CHANNEL}:{})}),errors=[];let regional,vp;
const idle=page=>page.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled),rows=page=>page.evaluate(async cid=>window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})}),cid);
const setup=async user=>{const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));await page.route('**/__api/rpc/atlas_month_end_queue',route=>route.fulfill({status:200,contentType:'application/json',body:'[]'}));await page.goto(url+'/?user='+user);await idle(page);return page;};
const saved=page=>page.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled&&document.querySelector('[data-save-status]')?.textContent.startsWith('Saved and verified'));
try{
 await fs.mkdir('output/playwright/governed-budget',{recursive:true});
 regional=await setup(2);await regional.locator('[data-community]').selectOption(cid);await idle(regional);await regional.locator('[data-new]').click();await regional.locator('[data-name]').fill('Governed lifecycle browser acceptance');await regional.locator('[data-last]').fill('2026-03');await regional.locator('[data-last]').dispatchEvent('change');await regional.waitForFunction(()=>!document.querySelector('[data-create]')?.disabled);await regional.locator('dialog [data-calendar-confirm]').check();await regional.locator('[data-create]').click();await saved(regional);
 let draft=(await rows(regional))[0];assert.equal(draft.head.status,'working_draft');assert.equal(draft.head.revision,1,'new draft autosaves without Save click');const id=draft.head.scenario_id;
 await regional.locator('[data-edit=reviewerId]').selectOption('00000000-0000-0000-0000-000000000005');await saved(regional);
 const cell='[data-gl-cell][data-period="2026-02"][data-code="5120"]';await regional.locator(cell).fill('1100');await saved(regional);draft=(await rows(regional)).find(row=>row.head.scenario_id===id);assert.equal(draft.revision.payload.overrides[0].amount,1100,'numerical edit autosaves before reason');assert.equal(draft.revision.payload.overrides[0].confirmed,false,'unexplained override remains publication-blocking');
 await regional.locator('[data-dense-reason]').fill('Reviewed rent projection change');await saved(regional);draft=(await rows(regional)).find(row=>row.head.scenario_id===id);assert.equal(draft.revision.payload.overrides[0].confirmed,true);
 // Exercise the actual import-choice dialog against the persisted open draft.
 for(const destination of ['new','current','cancel']){
  const choice=regional.evaluate(async({cid,destination})=>{const {chooseImportDestination}=await import('/docs/portfolio-operations-dashboard/features/reforecast-ui.mjs'),central=window.ATLAS_CENTRAL,entries=await central.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})}),s={central,actor:central.getSession().user.id,entries,communities:await central.readCommunitiesForAccess(),profiles:await central.readUserProfiles(),active:[],cid,year:2026,mode:'workspace',epoch:0,viewEpoch:0,container:{isConnected:false},R:{app:{notifyAtlasHeight(){}}}};try{const result=await chooseImportDestination(s,{ready:true,recoveryId:crypto.randomUUID(),communityId:cid,mapping:{periods:['2026-02','2026-03']},destination:'new',forecastName:'Imported parallel draft'});return {destination:result.destination,scenarioId:result.scenarioId};}catch(error){return {error:error.message};}},{cid,destination});
  const dialog=regional.locator('dialog[open]:has([data-import-new])');await dialog.locator('[data-import-new]').waitFor();assert.match(await dialog.innerText(),/Create New Draft/);assert.match(await dialog.innerText(),/Update Existing Draft/);assert.match(await dialog.innerText(),/Cancel/);await dialog.locator(destination==='new'?'[data-import-new]':destination==='current'?'[data-import-update]':'[data-import-cancel]').click();const selected=await choice;if(destination==='cancel')assert.match(selected.error,/Import cancelled/);else{assert.equal(selected.destination,destination);if(destination==='current')assert.equal(selected.scenarioId,id);}assert.equal((await rows(regional)).length,1,'choosing destination alone does not write or overwrite');
 }
 await regional.locator('[data-action=submit]').click();await idle(regional);assert.equal((await rows(regional)).find(row=>row.head.scenario_id===id).head.status,'submitted');assert.equal(await regional.locator('[data-approve-review]').count(),0,'Regional cannot VP approve');
 const active=page=>page.evaluate(async cid=>window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_active_reforecast',{method:'POST',body:JSON.stringify({p_community_ids:[cid],p_periods:['2026-02','2026-03']})}),cid);assert.deepEqual(await active(regional),[],'submission never publishes');
 vp=await setup(5);await vp.locator('[data-workspace-view=approvals]').click();await idle(vp);assert.equal(await vp.getByText('Monthly evidence status',{exact:true}).count(),0);assert.equal(await vp.locator('[data-open]').count(),1);await vp.screenshot({path:'output/playwright/governed-budget/approval-queue.png',fullPage:true});await vp.locator('[data-open="'+id+'"]').click();await idle(vp);await vp.locator('[data-approve-review]').click();await vp.locator('[data-approval-confirm]').check();await vp.locator('[data-confirm-approval]').click();await vp.locator('[data-confirm-approval]').waitFor({state:'detached'});await idle(vp);assert.deepEqual(await vp.locator('[role=alert]').allTextContents(),[]);
 const publication=(await active(vp))[0];assert(publication.publicationId);assert.equal((await rows(vp)).find(row=>row.head.scenario_id===id).head.status,'pending_investor_approval');assert(await vp.locator('[data-publication-delivery]').isVisible());
 await vp.locator('[data-lifecycle=investor_approve]').click();await vp.locator('[data-lifecycle-reason]').fill('Investor approval received');await vp.locator('[data-lifecycle-confirm]').click();assert.match(await vp.locator('dialog [data-status]').innerText(),/approval date/);await vp.locator('[data-investor-date]').fill('2026-09-24');await vp.locator('[data-lifecycle-confirm]').click();await vp.locator('[data-lifecycle-confirm]').waitFor({state:'detached'});await idle(vp);assert.deepEqual(await vp.locator('[role=alert]').allTextContents(),[]);assert.equal((await rows(vp)).find(row=>row.head.scenario_id===id).head.status,'investor_approved');assert(await vp.locator(cell).isDisabled());await vp.screenshot({path:'output/playwright/governed-budget/investor-approved.png',fullPage:true});
 await regional.reload();await idle(regional);assert.deepEqual(await active(regional),await active(vp),'second authorized session sees identical live publication');await vp.locator('[data-reopen]').click();await vp.locator('[data-lifecycle-reason]').fill('Investor requested reviewed change');await vp.locator('[data-lifecycle-confirm]').click();await vp.locator('[data-lifecycle-confirm]').waitFor({state:'detached'});await idle(vp);assert.equal((await active(vp))[0].publicationId,publication.publicationId,'reopen leaves approved snapshot live');assert.equal((await rows(vp)).find(row=>row.head.scenario_id===id).head.status,'reopened');
 await vp.locator('[data-action=submit]').click();await idle(vp);await vp.locator('[data-approve-review]').click();await vp.locator('[data-approval-confirm]').check();await vp.locator('[data-confirm-approval]').click();await vp.locator('[data-confirm-approval]').waitFor({state:'detached'});await idle(vp);const newer=(await active(vp))[0];assert.notEqual(newer.publicationId,publication.publicationId);
 await regional.locator('[data-workspace-view=approvals]').click();await idle(regional);await regional.locator('[data-open="'+id+'"]').click();await idle(regional);await regional.locator('[data-edit-pending]').click();await regional.locator('[data-dense-reason]').fill('Investor requested revised monthly target');await regional.locator(cell).fill('1200');await regional.waitForFunction(()=>document.querySelector('[data-save-status]')?.textContent.includes('Ready for Review and Approval'));assert.equal((await rows(regional)).find(row=>row.head.scenario_id===id).head.status,'submitted');assert.equal((await active(regional))[0].publicationId,newer.publicationId,'nonVP edit retains prior live baseline');assert(await regional.locator(cell).isDisabled());
 await vp.evaluate(async()=>{const {mountBudgetApprovalTasks}=await import('/docs/portfolio-operations-dashboard/features/budget-dashboard-tasks.mjs'),host=document.createElement('section');host.id='test-home-tasks';document.body.append(host);window.homeTask=null;await mountBudgetApprovalTasks(host,{central:window.ATLAS_CENTRAL,openReview:row=>{window.homeTask=row;}});});await vp.locator('#test-home-tasks [data-budget-review]').click();assert.equal(await vp.evaluate(()=>window.homeTask.id),id,'home Review retains exact scenario identity');
 assert.deepEqual(errors,[]);console.log('PASS visible governed workflow: autosave before reason, authoritative shared revisions, immutable submission/no publication, clean queue, denied Regional approval, VP publication and recovery cleanup, investor date/lock, independent session/reload parity, reopened baseline continuity, new VP precedence, nonVP edit resubmission and exact home-task review identity');
}catch(error){for(const page of [regional,vp].filter(Boolean))console.error('Visible failure:',{messages:await page.locator('[role=alert],dialog [data-status],[data-save-status]').allTextContents(),records:(await rows(page)).map(row=>({revision:row.head.revision,status:row.head.status,overrides:row.revision.payload.overrides}))});throw error;}
finally{await browser.close();server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}
