import assert from 'node:assert/strict';
import {indexedDB,IDBObjectStore} from 'fake-indexeddb';
import {executeHistory,historyHash,historyNamespace,isSplitHistory,mergeHistory,projectCurrentHistory,historyChanges} from '../docs/portfolio-operations-dashboard/features/import-history-store.mjs';
globalThis.indexedDB=indexedDB;
const dbName='history-split-test-'+crypto.randomUUID(),storeName='records',key='imports';
const run=(operation,extra={})=>executeHistory({dbName,storeName,key,operation,...extra});
const db=await new Promise((resolve,reject)=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore(storeName,{keyPath:'key'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const put=rows=>new Promise((resolve,reject)=>{const tx=db.transaction(storeName,'readwrite');for(const row of rows)tx.objectStore(storeName).put(row);tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error);});
const get=k=>new Promise((resolve,reject)=>{const r=db.transaction(storeName).objectStore(storeName).get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
const reads=[],oldGet=IDBObjectStore.prototype.get;IDBObjectStore.prototype.get=function(k){reads.push(k);return oldGet.call(this,k);};
try{
 const remote=extra=>executeHistory({dbName:dbName+'-remote',storeName,key,...extra});
 await remote({operation:'preferences',value:{activeView:'history',pendingBatch:{id:'pending-local-preview'}}});
 assert.equal((await remote({operation:'records',keys:[key]})).records[0].value,null,'Preferences never initialize or download canonical evidence');
 assert.equal((await remote({operation:'preferenceValues'})).values.pendingBatch.id,'pending-local-preview');
 const historical=Array.from({length:13051},(_,i)=>({id:'line-'+i,communityName:'A',periodKey:'2026-08',atlasField:'occupied_units',importedValue:i===0?0:i,currentState:i===0,fileHash:'source-hash',dataAsOf:'2026-08-31'}));
 const snapshot={capturedAt:'2026-09-01',savedData:{A:{occupied:0,unknown:{preserve:null}}},applicationResidentData:{uploads:[{id:'retained'}]},canonicalRecords:[{key:'prior',values:{amount:0}}],lineage:historical,reconciliationLog:[{text:'original'}],csvLog:['original']};
 const source={activeView:'overview',unknownFutureField:{zero:0,nullable:null},canonicalRecords:[{key:'source-record',communityName:'A',periodKey:'2026-08',reportType:'box_score',fileHash:'source-hash',dataAsOf:'2026-08-31',sectionPeriod:{asOf:'2026-08-31'},values:{occupied_units:0,total_units:100,rentable_units:100,physical_occupancy:0,resident:'not a startup field'}},{key:'unrelated',reportType:'rent_roll',values:{resident:'private'}}],lineage:historical,reconciliationLog:[{text:'current'}],batches:Array.from({length:73},(_,i)=>({id:'batch-'+i,status:'Approved',beforeSnapshot:{...snapshot,capturedAt:'snapshot-'+i}})),sourceArchive:Array.from({length:193},(_,i)=>({id:'source-'+i,batchId:'batch-0',reportType:'box_score',communities:['A'],importStatus:'Approved',fileHash:'hash-'+i}))};
 const originalHash=await historyHash(source);
 const appProjection=projectCurrentHistory({...source,lineage:[...historical,{id:'leads',currentState:true,communityName:'A',periodKey:'2026-08',atlasField:'new_leads',importedValue:0,originalField:'Lead Conversions: New Leads',sourceArchiveId:'archive-retained',fileHash:'source-hash',dataAsOf:'2026-08-31'},{id:'completed',currentState:true,communityName:'A',periodKey:'2026-08',atlasField:'leases_completed',importedValue:0,fileHash:'source-hash',dataAsOf:'2026-08-31'}],canonicalRecords:source.canonicalRecords.map(row=>({...row,values:{...row.values,new_leads:0,leases_completed:0}}))});
 assert.equal(appProjection.lineage.find(row=>row.atlasField==='new_leads').importedValue,0);assert.equal(appProjection.lineage.find(row=>row.atlasField==='new_leads').originalField,'Lead Conversions: New Leads');assert.equal(appProjection.lineage.find(row=>row.atlasField==='new_leads').sourceArchiveId,'archive-retained');assert.equal(appProjection.canonicalRecords[0].values.leases_completed,0);
 const pure=projectCurrentHistory(source);assert.equal(pure.lineage[0].importedValue,0);assert.equal(pure.canonicalRecords[0].values.occupied_units,0);assert.deepEqual(pure.unknownFutureField,{zero:0,nullable:null});
 const delta=historyChanges({...pure,activeView:'archive',pendingBatch:{id:'preview'}},pure);assert.deepEqual(delta.set,{});assert.deepEqual(delta.upsert,{});assert.equal(delta.preferences.pendingBatch.id,'preview');
 await put([{key,value:source,updatedAt:'original'},{key:'community_data',value:{A:{occupied:99}}},{key:'rise_ops_global_v1',value:{other:'preserved',applicationResidentData:{uploads:[]}}}]);
 const current=await run('current',{scope:{communityNames:['A'],periods:['2026-08']}});
 assert.equal(current.historyStorage.revision,1);assert.equal(current.historyStorage.counts.batches,73);assert.equal(current.historyStorage.counts.sourceArchive,193);assert.equal(current.historyStorage.counts.lineage,13051);
 assert.equal(current.batches.length,25);assert.equal(current.lineage.length,1);assert.equal(current.lineage[0].importedValue,0);assert.equal(current.canonicalRecords[0].values.physical_occupancy,0);assert.equal(current.canonicalRecords[0].values.resident,undefined);assert.equal(current.canonicalRecords[0].fileHash,'source-hash');assert.equal(current.canonicalRecords[0].sectionPeriod.asOf,'2026-08-31');assert.equal(current.reconciliationLog.length,0);
 assert.equal((await run('current',{scope:{communityNames:['B']}})).canonicalRecords.length,0);
 assert.deepEqual((await get(historyNamespace(key)+'legacy:'+originalHash)).value,source,'Original migration backup is exact and retained');
 reads.length=0;await run('current');assert(!reads.some(k=>k.includes(':snapshot:')||k.includes(':lineage:')||k.includes(':canonicalRecords:')),'Current reads never hydrate the historical corpus or rollback payloads');
 reads.length=0;const pref=await run('preferences',{value:{activeView:'history',mappingSearch:'zero'}});assert.equal(pref.preferencesRevision,1);assert(!reads.some(k=>k.includes(':snapshot:')||k.includes(':lineage:')||k.includes(':canonicalRecords:')),'Preference changes do not read evidence');
 await assert.rejects(run('preferences',{value:{lineage:[]}}),/preferences only/);
 const page=await run('page',{collection:'batches',offset:60,limit:10,expectedRevision:1});assert.equal(page.rows.length,10);assert.equal(page.total,73);assert.equal(page.nextOffset,70);assert.equal(page.rows[0].beforeSnapshot,undefined);
 assert.deepEqual(await run('snapshot',{batch:page.rows[0]}),source.batches[60].beforeSnapshot);
 assert.deepEqual((await run('export')).batches,source.batches);
 const full=await run('load');assert.equal(full.batches.length,73);assert.equal(full.sourceArchive.length,193);assert.equal(full.lineage.length,13051);assert.equal(full.activeView,'history');assert.equal(full.historyStorage.view,'full');
 await assert.rejects(run('save',{value:current,expectedRevision:1}),/complete import data/i);
 await assert.rejects(run('save',{value:{...full,batches:full.batches.slice(0,60)},expectedRevision:1}),/discard/);
 const changed=structuredClone(full);changed.batches[0].beforeSnapshotRef.capturedAt='changed';await assert.rejects(run('save',{value:changed,expectedRevision:1}),/evidence changed/);
 assert.throws(()=>mergeHistory({}, {__atlasImportHistory:2}),/storage|Complete/);
 const captured=await run('records',{keys:['community_data','rise_ops_global_v1']});
 const published=await run('publish',{value:{...full,unknownFutureField:{zero:0,nullable:null,additional:true}},expectedRevision:1,records:[{key:'community_data',value:{A:{occupied:88}},expectedHash:captured.records[0].hash}]});assert.equal(published.revision,2);assert.equal((await get('community_data')).value.A.occupied,88);
 await assert.rejects(run('save',{value:full,expectedRevision:1}),/changed/);await assert.rejects(run('page',{collection:'batches',expectedRevision:1}),/changed/);
 let latest=await run('load'),protectedRows=(await run('records',{keys:['community_data','rise_ops_global_v1']})).records;
 await assert.rejects(run('publish',{value:latest,expectedRevision:2,records:[{key:'community_data',value:{A:{shouldNotCommit:true}},expectedHash:'wrong'}]}),/changed/);
 assert.equal((await get(key)).value.revision,2);assert.equal((await get('community_data')).value.A.occupied,88);
 const bad={...latest,uncloneable:()=>{}};await assert.rejects(run('publish',{value:bad,expectedRevision:2,records:[{key:'community_data',value:{A:{shouldNotCommit:true}},expectedHash:protectedRows[0].hash}]}));assert.equal((await get(key)).value.revision,2);assert.equal((await get('community_data')).value.A.occupied,88,'A failed evidence write aborts every companion record');
 const originalAdd=IDBObjectStore.prototype.add;let forced=false;
 IDBObjectStore.prototype.add=function(row){if(!forced&&row.key.includes(':state:')){forced=true;throw Error('Synthetic mid-transaction failure');}return originalAdd.call(this,row);};
 try{await assert.rejects(run('publish',{value:{...latest,forceNewState:true},expectedRevision:2,records:[{key:'community_data',value:{A:{shouldNotCommit:true}},expectedHash:protectedRows[0].hash}]}),/mid-transaction/);}finally{IDBObjectStore.prototype.add=originalAdd;}
 assert(forced);assert.equal((await get(key)).value.revision,2);assert.equal((await get('community_data')).value.A.occupied,88,'An abort after requests are issued rolls back companion values and the root');
 const rollback=await run('rollback',{batch:latest.batches[0],expectedRevision:2,reason:'Synthetic verified recovery',actor:'synthetic',communityHash:protectedRows[0].hash,globalHash:protectedRows[1].hash});assert.equal(rollback.revision,3);
 assert.deepEqual((await get('community_data')).value,snapshot.savedData);assert.deepEqual((await get('rise_ops_global_v1')).value,{other:'preserved',applicationResidentData:snapshot.applicationResidentData});latest=await run('load');assert.equal(latest.batches.length,73);assert.equal(latest.sourceArchive.length,193);assert.equal(latest.lineage.length,13051);assert.equal(latest.batches[0].status,'Rolled Back');assert.deepEqual(await run('snapshot',{batch:latest.batches[0]}),source.batches[0].beforeSnapshot);
 const update=await run('update',{expectedRevision:3,append:{lineage:[{id:'new',currentState:false,importedValue:null}]}});assert.equal(update.revision,4);assert.equal((await run('load')).lineage.length,13052);
 const blob=new Blob(['immutable source bytes'],{type:'text/plain'}),rawKey='file:complete';
 const raw=await run('records',{keys:[rawKey],raw:true});
 await run('update',{expectedRevision:4,set:{rawPreserved:true},records:[{key:rawKey,record:{key:rawKey,value:{blob,fileName:'original.txt'},otherMetadata:'preserved'},expectedHash:raw.records[0].hash}]});
 assert.equal(await (await get(rawKey)).value.blob.text(),'immutable source bytes');assert.equal((await get(rawKey)).otherMetadata,'preserved');
 const ref=latest.batches[1].beforeSnapshotRef,storedSnapshot=await get(ref.storageKey);await put([{...storedSnapshot,value:{...storedSnapshot.value,savedData:{corrupt:true}}}]);await assert.rejects(run('snapshot',{batch:latest.batches[1]}),/fingerprint/);
 const controller=new AbortController();controller.abort();await assert.rejects(run('current',{signal:controller.signal}),/abort/i);
 assert(isSplitHistory((await get(key)).value));
 console.log('PASS split import history: complete73batches/193sources/13051lineage, immutable hashrefs, scoped zero provenance, lazy pages, preference isolation, revision conflicts, atomic publication/rollback, corruption denial, cancellation and retained legacy evidence');
}finally{IDBObjectStore.prototype.get=oldGet;db.close();indexedDB.deleteDatabase(dbName);}
