const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const P=require('../docs/portfolio-operations-dashboard/investor-packet-core.js'),S=require('../docs/portfolio-operations-dashboard/investor-packet-sources.js');
const sources={properties:{'RISE A':{name:'RISE A',periods:{'2026-01':{source:'budget.xlsx',revenue:{actual:100,budget:90},expenses:{actual:50,budget:40},drivers:[{id:'note',metric:'revenue',explanation:'Existing budget note',evidence:'GL 5120',owner:'Finance',classification:'hypothesis'}]}}}}};
const data={A:{monthlyHistoryByPeriod:{'2026-01':{guestCards:10}}},B:{}};
const storage=new Map([['rise.budget.autosave',JSON.stringify({formatVersion:1,state:{properties:[{name:'Legacy saved community'}]},investorPacketSources:sources})]]),listeners={};
const context={AtlasInvestorPacket:P,AtlasInvestorSources:S,window:{addEventListener(type,fn){listeners[type]=fn;}},console,savedData:data,APPLICATION_RESIDENT_DATA_PROPERTY_MAP:{'RISE A':{atlasName:'A'}},localStorage:{getItem:key=>storage.get(key)||null},getCommunityNamesByStatusScope:()=>['A','B'],getReportHubMonthIndex:()=>0,getReportHubYear:()=>2026,buildPeriodKey:()=> '2026-01',persistOpsGlobalData:()=>({ok:true}),renderTab(){},alert:m=>{throw Error(m)},setTimeout(){},clearTimeout(){},crypto:require('node:crypto').webcrypto};
vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/../docs/portfolio-operations-dashboard/investor-packet-ui.js','utf8'),context);
context.atlasInvestorPacketState={selectedCommunity:'A',communities:{}};
const ui=context.window.AtlasPacketUI;
assert.equal(ui.build().rows.find(r=>r.id==='revenue').cells.current.value,100,'Established ATLAS identity links should match automatically');
assert(ui.build().draft.performance.includes('$100'));
ui.row('drivers',0,'explanation','Reviewed edit');assert.equal(ui.build().draft.drivers[0].explanation,'Reviewed edit');
ui.remove('drivers',0);assert(!ui.build().draft.drivers.some(x=>x.id==='note'),'Removed imported commentary must stay removed');
ui.select('B');assert.equal(ui.build().rows.find(r=>r.id==='revenue').cells.current.value,null,'No cross-community budget fallback');
ui.select('A');
const current=()=>ui.build().rows.find(r=>r.id==='revenue').cells.current.value;
const v2Sources=structuredClone(sources);v2Sources.properties['RISE A'].periods['2026-01'].revenue.actual=250;
storage.set('rise.budget.autosave.v2',JSON.stringify({formatVersion:2,state:{properties:[{name:'Version two saved community'}]},investorPacketSources:v2Sources}));
assert.equal(current(),250,'Version 2 source takes priority over the legacy save');
assert.match(ui.render(),/<option value="Version two saved community"/,'Community source options prefer version 2');
assert.doesNotMatch(ui.render(),/<option value="Legacy saved community"/,'Legacy community names do not displace the current save');
const staleLegacy=JSON.parse(storage.get('rise.budget.autosave'));staleLegacy.investorPacketSources.properties['RISE A'].periods['2026-01'].revenue.actual=50;
storage.set('rise.budget.autosave',JSON.stringify(staleLegacy));
assert.equal(current(),250,'An older tab overwriting the legacy key cannot displace the v2 financial source');
storage.delete('rise.budget.autosave.v2');
assert.equal(current(),50,'Existing legacy-only browser saves still supply their source');
assert.match(ui.render(),/<option value="Legacy saved community"/,'Legacy-only community options remain available');
storage.set('rise.budget.autosave.v2','{unreadable current checkpoint');
assert.equal(current(),null,'A corrupt but present v2 checkpoint must not silently fall back to stale legacy financial values');
assert.doesNotMatch(ui.render(),/<option value="Legacy saved community"/,'A corrupt v2 checkpoint must not supply stale legacy community options');
assert.equal(storage.get('rise.budget.autosave.v2'),'{unreadable current checkpoint','The unreadable current checkpoint is retained for recovery');
storage.set('rise.budget.autosave.v2',JSON.stringify({formatVersion:2,state:{properties:[]}}));
assert.equal(current(),null,'An existing v2 checkpoint without financial sources never leaks stale legacy values');
storage.set('rise.budget.autosave.v2',JSON.stringify({formatVersion:2,state:{properties:[{name:'Version two saved community'}]},investorPacketSources:v2Sources}));
context.window.ATLAS_CENTRAL={};
assert.equal(current(),null,'A governed session never falls back to either browser financial source');

const requests=[],frame={contentWindow:{postMessage(value,origin){requests.push({value,origin});}}};
context.location={origin:'https://atlas.test'};
context.document={createElement(tag){assert.equal(tag,'iframe');return frame;},body:{appendChild(value){assert.equal(value,frame);}}};
const approvedSources=structuredClone(sources);approvedSources.properties['RISE A'].periods['2026-01'].revenue.actual=900;
const respond=()=>listeners.message({source:frame.contentWindow,origin:context.location.origin,data:{type:'atlas-investor-budget-sources',sources:approvedSources}});
ui.refresh();frame.onload();respond();
assert.equal(current(),900,'The governed reader response retains priority over all local checkpoints');
for(const key of ['rise.budget.autosave.v2','rise.budget.autosave']){
 const before=requests.length;listeners.storage({key});assert.equal(requests.length,before+1,key+' refreshes the existing read-only source frame');respond();
 assert.equal(current(),900,'Storage events refresh governed data without admitting browser financial fallbacks');
}
const before=requests.length;listeners.storage({key:'unrelated-key'});assert.equal(requests.length,before,'Unrelated storage writes do not refresh financial sources');
assert.deepEqual([...storage.keys()].sort(),['rise.budget.autosave','rise.budget.autosave.v2'],'Source reads retain both save records');
console.log('PASS automatic community identity links, generated narrative, editable imported notes, persistent suppression, community isolation, v2 source/name priority, legacy-only fallback, corrupt-v2 fail-closed reads, both-key refresh, stale-tab isolation and governed-source authority.');
