const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../docs/portfolio-operations-dashboard/lead-source-contract.js'),B=require('../docs/portfolio-operations-dashboard/application-source-bridge.js');
const html=fs.readFileSync('docs/portfolio-operations-dashboard/index.html','utf8');
const ctx=vm.createContext({console,window:{AtlasLeadSources:C},dataImport2State:{mappingRules:[],customFields:[],learningSettings:{}},DATA_IMPORT_FIELD_ALIASES:{},DATA_IMPORT_DESTINATION_GROUPS:[{fields:C.fields}],DATA_IMPORT_REPORT_TYPES:{}});
for(const match of html.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm))vm.runInContext(match[0],ctx);
const source=B.boxScore([['Lead Activity (09/01/2026 - 09/30/2026)'],['Unit Type','New Leads','Walk In','Off Site Event','Call','Email','Online','Chat','Text','Other'],['Total:',35,2,0,3,4,5,6,7,8]])[0];
source.sourceSheet='Community A';
const plan={reportType:'box_score',sourceSystem:'Entrata',name:'fixture.xlsx'};
let mapped=ctx.dataImportMapSourceRow(source,plan).mapped;
assert.equal(mapped.emails_online,9);assert.equal(mapped.__leadSourceMix.total,35);
ctx.dataImport2State.mappingRules=[{id:'email_override',originalField:'Email',canonicalField:'text_chat_other',sourceSystem:'Entrata',reportType:'box_score',scope:'Exact Source + Report',sharedLeadMapping:true,mappingVersion:'v2',learningStatus:'Trusted',confidence:100}];
mapped=ctx.dataImportMapSourceRow(source,plan).mapped;
assert.equal(mapped.emails_online,5);assert.equal(mapped.text_chat_other,25);assert.equal(mapped.__leadSourceMix.total,35);
assert.equal(mapped.__leadSourceMix.evidence.find(c=>c.label==='Email').mappingVersion,'v2');
assert.equal(ctx.dataImportFindSavedRuleForHeader('Email',{...plan,section:'Availability'}),null);
ctx.dataImport2State=JSON.parse(JSON.stringify(ctx.dataImport2State));
assert.equal(ctx.dataImportMapSourceRow({...source,sourceSheet:'Community B'},plan).mapped.text_chat_other,25);
assert.equal(ctx.getLeadSourceTotal({guestCards:99,leadSourceReconciliation:{version:C.version,buckets:mapped.__leadSourceMix.buckets,total:35,controls:[{value:0,status:'valid'}]}}),0);
console.log('PASS parser-to-import aggregation, shared exact override, component conservation, context guard, next-community reuse and zero-control report getter');
let month={},allow=true;
ctx.savedData={};
Object.assign(ctx,{normalizeSavedCommunityRecord:(_,r)=>r||{},getResolvedTotalUnitsForRecord:()=>100,getWritableMonthlyPeriodEntries:()=>({historyEntry:month,liveEntry:null}),dataImportUpsertFloorPlan:()=>{},dataImportShouldApplyCurrentMetric:()=>allow,
 dataImportApplyMetric:(_r,_p,_res,_name,_period,field,value)=>{if(value==null)return false;const key=field==='guest_cards'?'guestCards':C.storedFields[C.fields.indexOf(field)];if(key)month[key]=value;return true;}});
const result=()=>({issues:[],formulas:[],destinations:new Set()});
const publish=(entries)=>ctx.dataImportApplyGroupedSnapshot({communityName:'Community A',period:{monthIdx:8,year:2026,periodKey:'2026-09'},entries:entries.map(row=>({row,sourceRow:source}))},plan,result());
publish([mapped]);assert.equal(month.emailsOnline,5);assert.equal(month.offSiteEvent,0);assert.equal(month.guestCards,35);assert.equal(month.leadSourceReconciliation.total,35);
const beforeMonth=JSON.stringify(month);allow=false;publish([{...mapped,__leadSourceMix:{...mapped.__leadSourceMix,buckets:{...mapped.__leadSourceMix.buckets,emails_online:100}}}]);assert.equal(JSON.stringify(month),beforeMonth,'Stale source cannot replace published mix');
allow=true;month={};publish([mapped,mapped]);assert.equal(month.guestCards,undefined,'Duplicate mix does not publish a partial or doubled control');assert.equal(month.leadSourceReconciliation,undefined);
console.log('PASS actual grouped publication, legitimate zero, metadata, stale-source hold and duplicate representation hold');
