const {readDashboardSource}=require('./dashboard-source.cjs');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../docs/portfolio-operations-dashboard/lead-source-contract.js');
const B=require('../docs/portfolio-operations-dashboard/application-source-bridge.js');
const html=readDashboardSource('docs/portfolio-operations-dashboard/index.html');
const ctx=vm.createContext({console,window:{AtlasLeadSources:C,AtlasApplicationSources:B},dataImport2State:{mappingRules:[],customFields:[],learningSettings:{}},DATA_IMPORT_FIELD_ALIASES:{},DATA_IMPORT_DESTINATION_GROUPS:[{fields:C.fields}],DATA_IMPORT_REPORT_TYPES:{}});
for(const match of html.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm))vm.runInContext(match[0],ctx);
vm.runInContext(fs.readFileSync('docs/portfolio-operations-dashboard/lead-source-review.js','utf8'),ctx);
const row={new_leads:35,walk_in_leads:2,off_site_event_leads:0,call_leads:3,email_leads:4,online_leads:5,chat_leads:6,text_leads:7,other_leads:8};
const mix=ctx.dataImportLegacyLeadRow(row,{sourceFile:'test.csv',sourceSheet:'Sheet1',sourceRow:2});
assert.equal(mix.status,'reconciled');assert.equal(mix.total,35);assert.equal(mix.buckets.off_site_event,0);
const stored=JSON.parse(JSON.stringify({leadSourceReconciliation:mix}));
const sources=ctx.getLeadSourceBreakdown(stored),weekly=ctx.buildRiseWeeklyLeadSourceRows({trafficMetrics:sources});
assert.equal(weekly.length,5);assert.deepEqual(Array.from(weekly,r=>r.mappedChannel),C.definitions.map(d=>d.label));
assert.deepEqual(Array.from(weekly,r=>r.leads),Object.values(mix.buckets));
assert.equal(ctx.getLeadSourceTotal(stored),35);
assert.equal(ctx.getRecordLeadSourceBreakdown({monthlyData:[stored]},0).emails_online,9);
assert.equal(C.sum(Object.values(C.combine([sources,sources]))),70);
const missing=ctx.dataImportLegacyLeadRow({...row,email_leads:''},{sourceRow:2});
assert.equal(missing.buckets.emails_online,null);assert.equal(missing.total,null);
assert.equal(C.combine([sources,C.breakdown({leadSourceReconciliation:missing})]).emailsOnline,null);
assert.equal(ctx.buildRiseWeeklyLeadSourceRows({trafficMetrics:{guestCards:99}}).find(r=>r.mappedChannel==='Text / Chat / Other').leads,null,'Never fill Other from total');
assert.equal(ctx.dataImportLegacyLeadRow({...row,email_leads:-1},{sourceRow:2}).status,'review');
assert.equal(ctx.dataImportLegacyLeadRow({...row,emails_online:9},{sourceRow:2}).buckets.emails_online,9,'Combined selected once');
assert.equal(ctx.dataImportLegacyLeadRow({...row,new_leads:0},{sourceRow:2}).controls[0].variance,35,'Zero control retained');
ctx.dataImport2State.mappingRules=[{id:'r',originalField:'Email',canonicalField:'text_chat_other',sourceSystem:'Entrata',reportType:'box_score',scope:'Exact Source + Report',sharedLeadMapping:true,mappingVersion:'v2',learningStatus:'Trusted',confidence:100}];
assert.equal(ctx.dataImportLegacyLeadRow(row,{sourceRow:2}).buckets.text_chat_other,25,'Legacy path reuses shared override');
const source=[['Lead Activity (09/01/2026 - 09/30/2026)'],['Unit Type','New Leads','Walk In','Off Site Event','Call','Email','Online','Chat','Text','Other'],['Total:',35,2,0,3,4,5,6,7,8]];
Object.assign(ctx,{pickDailyBoxScoreReportDate:()=>null,extractAvailabilityTotalsFromRows:()=>null,extractPropertyPulseTotalsFromRows:()=>null,extractLeadActivityTotalsFromRows:()=>({newLeads:35}),extractLeadConversionTotalsFromRows:()=>null,extractLeadConversionTotals:()=>null});
const daily=ctx.buildDailyBoxScoreSnapshotFromRows(source,'test.xlsx');
assert.equal(daily.emailsOnline,5);assert.equal(daily.textChatOther,25);
assert.equal(ctx.normalizeDlrBoxScoreSnapshot(daily).leadSourceReconciliation.version,C.version);
console.log('PASS legacy CSV, daily Box Score, saved/reloaded state, five-bucket weekly reports, missing/zero/invalid values, combined precedence, no forced residual and shared override parity');
const W=require('../docs/portfolio-operations-dashboard/weekly-leasing-report.js');
const cells=Object.fromEntries(C.definitions.map((d,i)=>[d.field,{label:d.label,value:Object.values(mix.buckets)[i],source:JSON.stringify(mix.evidence)}]));
const report=W.model({communities:['Synthetic'],metrics:[{community:'Synthetic',cells}],period:'2026-09',end:'2026-09-21'});
const csvRows=W.rows(report).filter(r=>r.section==='Month-to-date Box Score');
assert.deepEqual(csvRows.map(r=>r.value),['2','0','3','9','21']);
assert(csvRows.every(r=>r.note.includes('sourceRow')));
assert(W.document(report).includes('Month-to-date lead sources'));
const monthly=ctx.dataImportKnownLeadColumns(['original_contact_method_email','original_contact_method_online','lead_off_site_event'],[0,5,0],{sourceRow:3});
assert.equal(monthly.buckets.emails_online,5);assert.equal(monthly.buckets.off_site_event,0);assert.equal(monthly.evidence[0].originalLabel,'original_contact_method_email');
console.log('PASS actual weekly report model, rendered table, CSV/Excel row parity, export lineage and explicit Monthly_Upload headers');
Object.assign(ctx,{normalizeDlrSummary:x=>({activity:{},...x}),getDlrActivityMetric:(_a,label)=>label==='Guest Cards'?99:7,getApplicationDecisionMetrics:()=>({applications:0,approvals:0,denials:0,cancelled:0,pendingDecision:0,leases:0}),getExplicitLeaseSignedCount:()=>0});
const allZero=C.aggregate(C.definitions.map(d=>({label:d.label,value:0})),{sourceSystem:'Entrata',reportType:'box_score',section:'Lead Activity'},[{label:'New Leads',value:0}]);
const authoritative=ctx.buildDlrTrafficMetricsFromSummary({activity:{}},{leadSourceReconciliation:allZero});
assert.equal(authoritative.guestCards,0);assert.equal(authoritative.emailsOnline,0);
console.log('PASS verified zero source mix outranks stale DLR summary totals');
const parsed=ctx.dataImportLeadCsvCells('property,emails_online,text_chat_other\r\n"Example, A","1,000",0\r\n');
assert.equal(parsed[1][0],'Example, A');assert.equal(parsed[1][1],'1,000');
const parsedMix=ctx.dataImportKnownLeadColumns(parsed[0],parsed[1],{sourceRow:2});assert.equal(parsedMix.buckets.emails_online,1000);assert.equal(parsedMix.buckets.text_chat_other,0);
ctx.extractedDashboardRows=[];ctx.extractedSourceLabel='';ctx.DASHBOARD_EXTRACT_HEADERS=['property','month','emails_online'];ctx.getExtractedDashboardRowYear=()=>2026;
ctx.mergeExtractedDashboardRows([{property:'A',month:'Sep',emails_online:9,__leadSourceMix:mix}]);assert.equal(ctx.extractedDashboardRows[0].__leadSourceMix.version,C.version);
ctx.mergeExtractedDashboardRows([{property:'A',month:'Sep',emails_online:5,__leadSourceMix:missing}]);assert.equal(ctx.extractedDashboardRows[0].__leadSourceConflict,true);
console.log('PASS quoted CSV counts, extracted-source lineage retention and duplicate representation conflict');
