import assert from 'node:assert/strict';import fs from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import {createRequire} from 'node:module';
import {parseComparisonSheet,reconcileComparison,finalizeFinancialPackageEvidence} from '../docs/portfolio-operations-dashboard/features/financial-package.mjs';
import {suggestMonthlyMappings,confirmMonthlyGovernance} from '../docs/portfolio-operations-dashboard/features/financial-workbook-governance.mjs';
const require=createRequire(import.meta.url),{fixture}=require('./financial-intake-fixture.cjs');const {db,cid,signIn}=await fixture(),actor='00000000-0000-0000-0000-000000000001';
const call=async(name,args)=>(await db.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
try{
 await db.exec('reset role');
 await db.exec(`create function atlas_private.budget_calendar(uuid) returns jsonb language sql as $$select '{"basis":"calendar","startMonth":1,"classification":"Multifamily","settingsVersion":1,"verified":true}'::jsonb$$;
 create function public.atlas_reforecast_effective_baseline(uuid[],text[]) returns jsonb language sql as $$select jsonb_agg(jsonb_build_object('communityId',$1[1],'period',p,'status','available','verified',true,'versionId','baseline-fixture','contentHash','fixture-hash','lines','[{"accountCode":"5120","amount":10000,"nature":"income","category":"Rent"},{"accountCode":"6100","amount":1000,"nature":"expense","category":"Maintenance"}]'::jsonb)) from unnest($2)p$$;`);
 await db.exec(fs.readFileSync(new URL('../supabase/migrations/20260925161938_governed_month_end_operational_review.sql',import.meta.url),'utf8'));
 const calculate=rows=>call('atlas_private.month_end_calculate',[{rows}]);
 const row=(actual,budget,category='Maintenance')=>({glCode:'6100',nature:'expense',category,actual,budget});
 for(const [a,b,required] of [[1500,1000,false],[10500,10000,false],[10501,10000,true],[1501,1000,true],[10000,10000,false],[9000,10000,false]])assert.equal((await calculate([row(a,b)])).rows[0].requiresExplanation,required,`${a}/${b}`);
 for(const [actual,budget,concern,required] of [[1100,1000,true,false],[20600,20000,true,false],[10500,10000,false,false],[1500,1000,true,false],[21000,20000,true,false],[10501,10000,true,true]]){const r=(await calculate([row(actual,budget)])).rows[0];assert.equal(r.concernFlag,concern,`Concern uses strict dollars OR percent: ${actual}/${budget}`);assert.equal(r.requiresExplanation,required,`Explanation uses strict dollars AND percent: ${actual}/${budget}`);}
 for(const budget of [null,0])for(const actual of [500,500.01]){const r=(await calculate([row(actual,budget)])).rows[0];assert.equal(r.unbudgetedExpense,true);assert.equal(r.concernFlag,actual>500,'Unbudgeted concern is strictly greater than $500');assert.equal(r.percentageVariance,null);assert.equal(r.requiresExplanation,false,'Unavailable percentage does not create a blocking explanation');assert.equal(r.budget,budget,'Blank and zero budget remain distinct');}
 for(const category of ['Payroll','Taxes','Insurance']){const r=(await calculate([row(5000,1000,category)])).rows[0];assert.equal(r.requiresExplanation,false);assert.equal(r.accountingVerification,true);assert.equal(r.systemNote,'See Accounting for verification. Explanation not required for approval.');}
 for(const budget of [null,0]){const r=(await calculate([row(200,budget)])).rows[0];assert.equal(r.unbudgetedExpense,true);assert.equal(r.percentageVariance,null);assert.equal(r.requiresExplanation,false);assert.equal(r.budget,budget);}
 assert.equal((await calculate([row(1350,1000)])).reforecastRecommended,false);assert.equal((await calculate([row(1350.01,1000)])).reforecastRecommended,true);
 assert.equal((await calculate([row(null,1000)])).expenseActual,null);assert.equal((await calculate([row(600,1000),row(1100,1000)])).reforecastRecommended,false);
 const build=async (expense,period='2026-01')=>{const values=(a,b)=>[a,b,a-b,b?(a-b)/b:null,a,b,a-b,b?(a-b)/b:null,b*12];const matrix=[['Budget Comparison - Income Statement'],['Doro'],[period==='2026-01'?'Jan 2026':period==='2026-02'?'Feb 2026':'Aug 2026'],['Accrual Basis'],[],[null,null,period==='2026-01'?'Jan 2026':period==='2026-02'?'Feb 2026':'Aug 2026',null,null,null,period==='2026-08'?'YTD ( Aug 2026 - Aug 2026 )':'YTD ( Jan 2026 - '+(period==='2026-01'?'Jan':'Feb')+' 2026 )'],['Account','Account Name','Actual','Budget','$ Variance','% Variance','Actual','Budget','$ Variance','% Variance','Annual Budget'],['Income'],['5120','Gross Potential Rent',...values(10000,10000)],['','Net Rental Income',...values(10000,10000)],['','Total Income',...values(10000,10000)],['Expenses'],['6100','Maintenance',...values(expense,9999)],['6200','GAS',null,null,null,null,null,null,null,null,null],['','Total Expenses',...values(expense,9999)],['','Net Operating Income',...values(10000-expense,1)]];
 const sourceHash=createHash('sha256').update(JSON.stringify(matrix)).digest('hex'),cells={C9:{v:10000},C10:{v:10000,f:'C9'},C11:{v:10000,f:'C9'},C13:{v:expense},C15:{v:expense,f:'SUM(C13:C14)'},C16:{v:10000-expense,f:'C11-C15'}};let c=reconcileComparison([parseComparisonSheet(matrix,'BCR',{cells,sourceHash})]);Object.assign(c,{sourceFile:'Synthetic January.pdf',sourceHash});const governance=confirmMonthlyGovernance(c,{reportingBasis:period==='2026-08'?'fiscal':'calendar',fiscalStartMonth:period==='2026-08'?8:1,currency:'USD',reason:'Synthetic monthly verified accounting source',mappings:suggestMonthlyMappings(c),actor});c=await finalizeFinancialPackageEvidence(c,{communityId:cid,period,actor,exclusionsReviewed:true,governance});assert.equal(c.safeToImport,true,JSON.stringify(c.safetyIssues));return c;};
 const save=async c=>{let stage;for(const state of ['uploaded','classified','community_period_confirmed','fully_mapped','reconciled'])stage=await call('atlas_record_financial_intake',[stage?.workflow.workflow_id||null,randomUUID(),stage?.receipt.receipt_id||null,state,['uploaded','classified'].includes(state)?null:cid,{sourceHash:c.sourceHash,sourceFile:c.sourceFile,certificate:c}]);return call('atlas_save_financial_review_governed',[stage.workflow.workflow_id,stage.receipt.receipt_id,randomUUID(),c]);};
 await signIn(1);const c=await build(1600),saved=await save(c),review=saved.review;
 let e=await call('atlas_read_month_end_review',[review.review_id]);assert(e.blockers.some(x=>x.includes('Accounting')));
 await assert.rejects(()=>call('atlas_close_financial_review_governed',[review.review_id,null,randomUUID(),'Synthetic acceptance approval',true]),/operational review/);
 assert.equal((await call('atlas_month_end_queue',[[cid],2026])).length,0,'Upload/reconciliation alone is not approval-queue eligible');
 await call('atlas_confirm_month_end_close',[review.review_id,'2026-02-12T10:00:00Z','2026-02-12T09:00:00Z','Verified Accounting close for fixture']);
 e=await call('atlas_read_month_end_review',[review.review_id]);assert.deepEqual(e.blockers,[]);assert.equal(e.rows.find(r=>r.glCode==='6100').budget,1000,'Accounting comparison budget never becomes baseline');assert.equal(e.exceptionCount,1);assert.equal(e.reforecastRecommended,true);
 assert.equal((await call('atlas_month_end_queue',[[cid],2026])).length,1);
 await assert.rejects(()=>call('atlas_save_month_end_decision',[review.review_id,e.fingerprint,{},{},randomUUID()]),/explanation/);
 await signIn(2);await assert.rejects(()=>call('atlas_save_month_end_decision',[review.review_id,e.fingerprint,{}, {'6100':'Admin-only override'},randomUUID()]),/Only Admin/);const second=await call('atlas_read_month_end_review',[review.review_id]);assert.deepEqual(second,e);await signIn(3);await assert.rejects(()=>call('atlas_read_month_end_review',[review.review_id]),/access denied/);await signIn(1);
 const decision=await call('atlas_save_month_end_decision',[review.review_id,e.fingerprint,{'6100':'Unexpected approved roof maintenance charge'},{},randomUUID()]);assert.equal(decision.actor_id,actor);
 const request=randomUUID(),closed=await call('atlas_close_financial_review_governed',[review.review_id,null,request,'Synthetic accepted fiscal YTD review',true]);assert.equal((await call('atlas_close_financial_review_governed',[review.review_id,null,request,'Synthetic accepted fiscal YTD review',true])).close.version_id,closed.close.version_id);
 assert.equal((await call('atlas_month_end_queue',[[cid],2026])).length,0,'Closed history excluded');
 await call('atlas_reopen_actual_period',[cid,'2026-01',closed.close.version_id,'Corrected source package requested',randomUUID()]);let read=(await db.query('select * from atlas_read_finance($1,$2)',[[cid],['2026-01']])).rows[0];assert.equal(read.summary.periodState,'reopened');assert.equal(read.summary.actualCloseVersion,closed.close.version_id,'Reopen retains live immutable prior close');assert.match(read.summary.periodWarning,/re-approved and locked/);
 const corrected=await save(await build(1700));await call('atlas_confirm_month_end_close',[corrected.review.review_id,'2026-02-13T10:00:00Z','2026-02-13T09:00:00Z','Verified corrected Accounting close']);e=await call('atlas_read_month_end_review',[corrected.review.review_id]);await call('atlas_save_month_end_decision',[corrected.review.review_id,e.fingerprint,{'6100':'Corrected source confirms expense overrun'},{},randomUUID()]);const replacement=await call('atlas_close_financial_review_governed',[corrected.review.review_id,closed.close.version_id,randomUUID(),'Corrected source accepted after reconciliation',true]);assert.equal(replacement.close.previous_version_id,closed.close.version_id);read=(await db.query('select * from atlas_read_finance($1,$2)',[[cid],['2026-01']])).rows[0];assert.equal(read.summary.periodState,'locked');assert.equal(read.summary.actualCloseVersion,replacement.close.version_id);

 const feb=await save(await build(800,'2026-02'));await call('atlas_confirm_month_end_close',[feb.review.review_id,'2026-03-12T10:00:00Z','2026-03-12T09:00:00Z','Verified next month accounting close']);const ytd=await call('atlas_read_month_end_review',[feb.review.review_id]);const maintenance=ytd.rows.find(r=>r.glCode==='6100');assert.deepEqual(ytd.periods,['2026-01','2026-02']);assert.equal(maintenance.actual,2500);assert.equal(maintenance.budget,2000);assert.equal(maintenance.variance,500);assert.equal(maintenance.requiresExplanation,false,'Monthly favorable variance offsets unfavorable within same GL before threshold');
 await db.exec(`reset role;create or replace function atlas_private.budget_calendar(uuid) returns jsonb language sql as $$select '{"basis":"fiscal","startMonth":8,"classification":"Student Housing","settingsVersion":2,"verified":true}'::jsonb$$;`);await signIn(1);const aug=await save(await build(1600,'2026-08'));await call('atlas_confirm_month_end_close',[aug.review.review_id,'2026-09-12T10:00:00Z','2026-09-12T09:00:00Z','Verified Student August accounting close']);const student=await call('atlas_read_month_end_review',[aug.review.review_id]);assert.deepEqual(student.periods,['2026-08']);assert.deepEqual(student.blockers,[]);assert.equal(student.rows.find(r=>r.glCode==='6100').actual,1600,'Student YTD starts in August and does not use January closes');
await db.exec('reset role');assert.equal((await db.query('select count(*) n from atlas_financial_close_versions')).rows[0].n,2);await assert.rejects(()=>db.query('delete from atlas_month_end_decisions'),/immutable/);assert.equal((await db.query("select has_function_privilege('authenticated','public.atlas_close_financial_review_before_operational(uuid,uuid,uuid,text,boolean)','EXECUTE') permitted")).rows[0].permitted,false);
 console.log('PASS database month-end strict thresholds, accounting notes, missing/zero, 35% boundary, source/baseline separation, close gate, immutable audit, scoped second session, idempotency, queue eligibility, corrected supersession and reopened consumer warning/relock.');
}finally{await db.close();}
