import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createOccupancyBudgetStore} from '../docs/portfolio-operations-dashboard/features/occupancy-budget-store.mjs';
let actor='a',fail=false,calls=0;
const central={getSession:()=>({user:{id:actor}}),refreshSession:async()=>{}};
const approved={community_id:'doro',calendar_year:2026,status:'locked',version_id:'v1',content_hash:'hash',covered_months:[0,8],payload:{occupancyPct:[0,null,null,null,null,null,null,null,56.085994]}};
const store=createOccupancyBudgetStore(central,{read:async(_,id)=>{calls++;if(fail)throw Error('offline');return id==='doro'?[approved]:[];}});
const entries=[{name:'Doro',recordId:'community:doro',communityId:'doro',year:2026},{name:'Other',recordId:'community:other',communityId:'other',year:2026}];
await Promise.all([store.hydrate(entries),store.hydrate(entries)]);assert.equal(calls,2);
const core=fs.readFileSync('docs/portfolio-operations-dashboard/workspace-core.js','utf8');
const c=vm.createContext({console,window:{AtlasOccupancyBudgets:store},Date});
for(const f of core.matchAll(/^(?:async )?function [A-Za-z_$][\w$]*\([^\n]*\) \{[\s\S]*?^\}/gm))vm.runInContext(f[0],c);
const record={communityId:'community:doro',reportYear:2026,savedBudgetTargets:Array(12).fill(47.6),monthlyData:Array.from({length:12},()=>({budgetOcc:47.6}))};
assert.equal(c.getRecordSavedBudgetOccPct(record,8,2026),56.085994,'locked budget takes precedence over stale curve');
assert.equal(c.getRecordSavedBudgetOccPct(record,0,2026),0,'approved zero remains available');
assert.equal(c.getRecordSavedBudgetOccPct(record,7,2026),null,'canonical missing month cannot fall back to stale curve');
assert.equal(c.getRecordSavedBudgetOccPct({...record,communityId:'community:other'},8,2026),47.6,'communities without governed originals retain their saved curve');
assert.equal(c.getRecordSavedBudgetOccPct(record,8,2025),null,'no cross-year budget substitution');
assert.equal(c.getRecordSavedBudgetOccPct(JSON.parse(JSON.stringify(record)),8,2026),56.085994,'reload preserves canonical resolution');
const revision=store.revision;store.clear();assert.notEqual(store.revision,revision);fail=true;await store.hydrate(entries);
assert.equal(c.getRecordSavedBudgetOccPct(record,8,2026),null,'failed shared read never silently returns stale curve');
assert.equal(store.get(record,8,2026).status,'error');
fail=false;store.clear();await store.hydrate(entries);actor='b';assert.equal(store.get(record,8,2026).status,'loading','access change cannot reuse another actor evidence');
let release;const delayed=createOccupancyBudgetStore(central,{read:()=>new Promise(resolve=>{release=resolve;})});const task=delayed.hydrate(entries.slice(0,1));await new Promise(resolve=>setImmediate(resolve));delayed.clear();release([approved]);await task;assert(!delayed.ready(entries.slice(0,1)),'clear discards in-flight completion');
console.log('PASS all-community budget precedence, approved zero, missing coverage/year, saved curve fallback, reload, request deduplication, errors and access/in-flight invalidation.');
