import assert from 'node:assert/strict';import fs from 'node:fs';import {randomUUID} from 'node:crypto';import {createRequire} from 'node:module';
import {parseReforecastWorkbook} from '../docs/portfolio-operations-dashboard/features/reforecast-intake.mjs';
import {reviewPlanningInputs} from '../docs/portfolio-operations-dashboard/features/planning-governance.mjs';
import {evaluateReforecastImportReview,reforecastImportGroups} from '../docs/portfolio-operations-dashboard/features/reforecast-import-ui.mjs';
import {reviewedOriginalBudgetStage} from '../docs/portfolio-operations-dashboard/features/original-budget-intake.mjs';
const require=createRequire(import.meta.url),{fixture}=require('./financial-intake-fixture.cjs'),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
const {db,cid,signIn}=await fixture(),actor='00000000-0000-0000-0000-000000000001';const call=async(name,args)=>(await db.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
try{
const legacyRequest=randomUUID(),legacyPayload={communityId:cid,year:2025,fiscalYear:2025,fiscalStartMonth:1,coverage:Array.from({length:12},(_,i)=>i),effectiveDate:'2025-01-01',scenarioId:'retained-original',scenarioVersion:'retained-v1',sourceFile:'Retained-approved-source.xlsx',sourceHash:'f'.repeat(64),sourceHashKind:'normalized_approved_rows',mappingVersion:'retained-mapping-v1',rows:[{glCode:'5120',monthly:Array(12).fill(100)},{glCode:'6100',monthly:Array(12).fill(20)}],metricMappings:{gpr:[{glCode:'5120',factor:1}],revenue:[{glCode:'5120',factor:1}],expenses:[{glCode:'6100',factor:1}],noi:[{glCode:'5120',factor:1},{glCode:'6100',factor:-1}]},occupancyPct:Array(12).fill(null),registryVersion:'atlas-finance-v1',approvedLocked:true,reviewConfirmed:true};const retained=await call('atlas_approve_original_budget_governed',[cid,legacyRequest,legacyPayload]);
await db.exec('reset role');for(const name of ['20260924121641_planning_cell_workbook_integrity_governance.sql','20260924121647_immutable_workbook_audits_and_monthly_governance.sql','20260924121653_original_budget_immutable_workbook_approval.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));await signIn(1);
const retainedRetry=await call('atlas_approve_original_budget_governed',[cid,legacyRequest,legacyPayload]);assert.equal(retainedRetry.budget.version_id,retained.budget.version_id,'Exact previously committed receipt retries survive new governance');await assert.rejects(()=>call('atlas_approve_original_budget_governed',[cid,randomUUID(),{...legacyPayload,year:2024,fiscalYear:2024}]),/immutable workbook/);
const periods=Array.from({length:12},(_,m)=>`2026-${String(m+1).padStart(2,'0')}`),accounts=[{accountCode:'5120',category:'Rental',nature:'income',placement:'above_noi',effectiveFrom:'2026-01'},{accountCode:'6100',category:'Payroll',nature:'expense',placement:'above_noi',effectiveFrom:'2026-01'}];const registry=await call('atlas_save_reforecast_registry',[cid,null,randomUUID(),{accounts,driverMappings:{},reason:'Reviewed annual source account mapping',effectiveDate:'2026-01-01'}]);
const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([['GL',...periods],['5120',0,...Array(11).fill(100)],['6100',...Array(12).fill(20)]]),'Budget');XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet([['Scenario','Plan'],['Currency','USD']]),'Controls');const bytes=XLSX.write(workbook,{type:'array',bookType:'xlsx'}),evidence=await parseReforecastWorkbook(bytes,{xlsx:XLSX,fileName:'Sanitized-original-budget.xlsx',includeOriginalBytes:true});
const assignment={communityId:cid,confirmed:true,explicit:true,actorId:actor,assignedAt:'2026-09-24T10:00:00Z',reason:'Explicitly assigned sanitized source',sourceEntities:[]};evidence.propertyAssignment=assignment;const audit=await call('atlas_save_workbook_audit',[cid,evidence.source.sha256,evidence.integrity,randomUUID()]);const upload=await call('atlas_save_reforecast_upload',[cid,randomUUID(),{...evidence,integrity:{auditId:audit.audit_id,fingerprint:audit.fingerprint,sourceHash:audit.source_hash}}]);
const source={communityId:cid,registry:{...registry.payload,version:registry.version_id},actuals:{cutoffPeriod:'2026-08'}},groups=reforecastImportGroups(evidence,'Plan',periods),input={purpose:'original_budget',evidence,source,assignment,scenario:'Plan',currency:'USD',periods,accountChoices:Object.fromEntries(groups.map(g=>[g.key,{accountCode:g.sourceAccountCode,signMultiplier:1}])),selectedLineIds:evidence.lines.map(l=>l.id),reason:'Reviewed full original budget source and source cell meanings',confirmed:true,reviewerId:actor,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:'Plan',reviewedBy:actor,reviewedAt:'2026-09-24T10:00:00Z'}};input.inputReviews=reviewPlanningInputs(evidence,input.selectedLineIds,{reason:'Reviewed each original planning input',ownerId:actor});const mapped=evaluateReforecastImportReview(input,[cid]);assert.equal(mapped.ready,true,JSON.stringify(mapped.issues));assert.equal(mapped.lines.length,24,'Original budget covers closed and open months without changing actuals');const stage=reviewedOriginalBudgetStage({...mapped,upload,communityId:cid,source},{propertyId:'synthetic',year:2026,effectiveDate:'2026-01-01'});
const payload={communityId:cid,year:2026,fiscalYear:2026,fiscalStartMonth:1,coverage:stage.coverage,effectiveDate:'2026-01-01',scenarioId:'original-budget',scenarioVersion:'reviewed-version',sourceFile:stage.sourceFile,sourceHash:stage.sourceHash,sourceHashKind:'workbook_bytes',mappingVersion:registry.version_id,currency:'USD',rows:stage.rows.map(r=>({...r,glCode:r.gl})),metricMappings:{gpr:[{glCode:'5120',factor:1}],revenue:[{glCode:'5120',factor:1}],expenses:[{glCode:'6100',factor:1}],noi:[{glCode:'5120',factor:1},{glCode:'6100',factor:-1}]},occupancyPct:Array(12).fill(null),registryVersion:'atlas-finance-v1',approvedLocked:true,reviewConfirmed:true,governance:stage.governance};
const approve=(p,id=randomUUID())=>call('atlas_approve_original_budget_governed',[cid,id,p]);await assert.rejects(()=>approve({...payload,sourceHashKind:'normalized_approved_rows'}),/immutable workbook/);await assert.rejects(()=>approve({...payload,governance:null}),/immutable workbook/);const missingInput=structuredClone(payload);missingInput.governance.mapping.inputReviews=[];await assert.rejects(()=>approve(missingInput),/planning_input_review_required/);const wrongAmount=structuredClone(payload);wrongAmount.rows[0].monthly[0]=1;await assert.rejects(()=>approve(wrongAmount),/differ from/);const wrongSign=structuredClone(payload);wrongSign.rows[0].sourceCells[0].signMultiplier=-1;await assert.rejects(()=>approve(wrongSign),/differ from/);const wrongPeriod=structuredClone(payload);wrongPeriod.governance.mapping.calendar.startMonth=2;await assert.rejects(()=>approve(wrongPeriod),/fiscal segment/);const wrongCoordinates=structuredClone(payload);wrongCoordinates.rows[0].sourceCells[0].address='B99';await assert.rejects(()=>approve(wrongCoordinates),/differ from/);await assert.rejects(()=>approve({...payload,currency:'CAD'}),/supports USD/);
const request=randomUUID(),result=await approve(payload,request);assert.equal(result.status,'committed');assert.equal(result.budget.payload.rows[0].monthly[0],0);assert.equal(result.publications.length,12);const retry=await approve(payload,request);assert.equal(retry.budget.version_id,result.budget.version_id);const verified=await call('atlas_verify_finance_receipt',[result.receipt.receipt_id,result.budget.version_id,result.budget.content_hash]);assert.equal(verified.status,'readback_verified');await signIn(2);const second=(await db.query('select version_id,content_hash from atlas_approved_budget_versions where version_id=$1',[result.budget.version_id])).rows[0];assert.equal(second.content_hash,result.budget.content_hash);await assert.rejects(()=>approve(payload),/Only an active/);await signIn(1);await assert.rejects(()=>approve({...payload,scenarioVersion:'new-version'}),/immutable/);
console.log('PASS original budget workbook upload/audit/explicit cell review, historical coverage isolated from actuals, zero preservation, normalized-row bypass rejection, amount/sign/period/coordinate blockers, immutable canonical approval/receipts, idempotent retry and second authorized-session readback');
}finally{await db.close();}
