import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {reviewedOriginalBudgetStage} from '../docs/portfolio-operations-dashboard/features/original-budget-intake.mjs';
import {approveOriginalBudget} from '../docs/portfolio-operations-dashboard/features/approved-budget.mjs';
import {saveForecastRecoveryEntries,saveForecastRecovery,readForecastRecovery,removeForecastRecovery,completeOriginalBudgetRecovery} from '../docs/portfolio-operations-dashboard/features/reforecast-recovery.mjs';
const id=n=>'40000000-0000-4000-8000-'+String(n).padStart(12,'0'),cid=id(1),actor=id(2),uploadId=id(3),requestId=id(4),versionId=id(5),receiptId=id(6),verifiedId=id(7),hash='a'.repeat(64),contentHash='b'.repeat(64),evidenceId='workbook:'+hash+':atlas-reforecast-xlsx/3',reviewId='original-budget-review',periods=Array.from({length:12},(_,i)=>'2026-'+String(i+1).padStart(2,'0'));
let activeActor=actor,mode='ok',writes=0,committed=null;
const central={getSession:()=>({user:{id:activeActor}}),getStoredProfile:()=>({role:'admin'}),async rpc(name,args){
 if(name==='atlas_approve_original_budget_governed'){
  assert.equal(args.p_request_id,requestId);if(!committed){writes++;committed={version_id:versionId,community_id:cid,calendar_year:2026,status:'locked',content_hash:contentHash,payload:structuredClone(args.p_payload)};}
  if(mode==='lost-response')throw Error('Uncertain original-budget response');
  return {status:'committed',budget:structuredClone(committed),receipt:{receipt_id:receiptId,version_id:versionId,content_hash:contentHash},publications:[]};
 }
 assert.equal(name,'atlas_verify_finance_receipt');if(mode==='unavailable-proof')throw Error('Verification unavailable');return {status:'readback_verified',receipt_id:verifiedId,version_id:versionId,content_hash:contentHash,source_hash:hash,mapping_version:'budget-mapping-reviewed',actor_id:activeActor,created_at:'2026-09-24T10:00:00Z'};
},async fetchJson(){if(mode==='unavailable-read')throw Error('Readback unavailable');const read=structuredClone(committed);if(mode==='wrong-row')read.payload.rows[0].monthly[0]=null;return [read];}};
const mapped={ready:true,communityId:cid,upload:{upload_id:uploadId,community_id:cid,source_hash:hash,payload:{source:{fileName:'Reviewed original.xlsx'}}},mapping:{confirmed:true,version:id(8),periods,calendar:{startMonth:1}},source:{registry:{accounts:[{accountCode:'5120',name:'Rent'}]}},lines:periods.map((period,i)=>({accountCode:'5120',period,amount:i===0?0:i===1?-10:100,nature:'income',sourceLineId:'Plan!B'+(i+1),sourceCoordinates:{sheet:'Plan',address:'B'+(i+1)},signMultiplier:1})),recoveryId:reviewId,reviewVersion:'review-version-one',evidenceId};
const stage=reviewedOriginalBudgetStage(mapped,{propertyId:'fixture',year:2026,effectiveDate:'2026-01-01'}),payload={communityId:cid,year:2026,fiscalYear:2026,fiscalStartMonth:1,coverage:stage.coverage,effectiveDate:stage.effectiveDate,sourceFile:stage.sourceFile,sourceHash:stage.sourceHash,sourceHashKind:stage.sourceHashKind,governance:stage.governance,mappingVersion:'budget-mapping-reviewed',approvedLocked:true,reviewConfirmed:true,rows:stage.rows.map(row=>({glCode:row.gl,monthly:row.monthly,sourceCells:row.sourceCells})),metricMappings:{revenue:[{glCode:'5120',factor:1}]}};
const seed=()=>saveForecastRecoveryEntries(central,[{id:evidenceId,value:{kind:'workbook-evidence',evidence:{source:{sha256:hash,originalFile:{data:'exact-original-bytes'}}}}},{id:reviewId,value:{kind:'import-review',purpose:'original_budget',communityId:cid,uploadId,evidenceId,reviewVersion:stage.importRecovery.reviewVersion,fields:{reason:'Reviewed exact original source'}}}]);
const retained=async()=>{assert(await readForecastRecovery(central,reviewId));assert(await readForecastRecovery(central,evidenceId));};
await seed();assert.equal(stage.stage,'staged');assert.equal(stage.importRecovery.reviewVersion,mapped.reviewVersion);assert.equal(stage.importRecovery.uploadId,uploadId);await retained();assert.equal(writes,0,'Review/staging never means central publication');
const approve=()=>approveOriginalBudget({central,cid,payload,requestId,importRecovery:stage.importRecovery});
for(mode of ['lost-response','unavailable-read','unavailable-proof','wrong-row']){await assert.rejects(approve);await retained();assert.equal(writes,1,'One stable request never creates another immutable version');}
mode='ok';const result=await approve();assert.equal(result.status,'readback_verified');assert.equal(await readForecastRecovery(central,reviewId),null);assert.equal(await readForecastRecovery(central,evidenceId),null);assert.equal(writes,1);await approve();
// Completed budget readback must not release another purpose's shared bytes,
// another actor's records, or a newer review using the same logical identity.
await seed();await saveForecastRecovery(central,'shared-review',{kind:'import-review',purpose:'reforecast',evidenceId,reviewVersion:'shared'});await approve();assert.equal(await readForecastRecovery(central,reviewId),null);assert(await readForecastRecovery(central,evidenceId));await removeForecastRecovery(central,'shared-review');
await seed();activeActor=id(20);await seed();activeActor=actor;await saveForecastRecovery(central,reviewId,{...(await readForecastRecovery(central,reviewId)),reviewVersion:'newer',fields:{reason:'Newer unsaved review'}});await approve();assert.equal((await readForecastRecovery(central,reviewId)).fields.reason,'Newer unsaved review');assert(await readForecastRecovery(central,evidenceId));activeActor=id(20);await retained();activeActor=actor;
await seed();for(const changed of [{...stage.importRecovery,sourceHash:'c'.repeat(64)},{...stage.importRecovery,uploadId:id(30)},{...stage.importRecovery,mappingVersion:id(31)}]){await assert.rejects(()=>completeOriginalBudgetRecovery(central,{recovery:changed,payload,result}));await retained();}
console.log('PASS original-budget recovery: staging retains review and bytes; uncertain response, missing readback/proof, or mismatched exact rows retain recovery; verified immutable publication releases only its frozen review and unshared bytes; source/mapping bindings, newer edits and actor isolation remain protected.');
