// Real report-library UI and download handlers over a controlled, read-only receipt transport.
import assert from 'node:assert/strict';
import http from 'node:http';
import {readFile,mkdir,mkdtemp,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve,join,extname} from 'node:path';
import {createRequire} from 'node:module';
import {ids} from './fixtures/reforecast-report-library-fixture.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js'),root=resolve('.'),folder=process.env.ATLAS_REPORT_LIBRARY_QA_OUTPUT||await mkdtemp(join(tmpdir(),'atlas-report-library-'));
await mkdir(folder,{recursive:true});
const html=`<!doctype html><html><head><meta charset="utf-8"><title>Report library regression</title><style>body{font:15px system-ui}dialog{width:85vw;max-height:85vh;overflow:auto}button,select{margin:8px;padding:8px}select{max-width:90%}.rf-state{font-weight:bold}</style></head><body><button id="open">Saved reports</button><script type="module">
import {reportLibraryFixture,ids} from '/tools/fixtures/reforecast-report-library-fixture.mjs';
import {reportLibraryDialog} from '/docs/portfolio-operations-dashboard/features/reforecast-report-library.mjs';
window.fixture=reportLibraryFixture();window.ids=ids;window.active=true;
const dialog=title=>{document.querySelector('dialog')?.remove();const el=document.createElement('dialog');el.innerHTML='<h1>'+title+'</h1><button data-close>Close</button><div data-body></div><p data-status role="status"></p>';el.querySelector('[data-close]').onclick=()=>el.close();document.body.append(el);el.showModal();return el;};
document.querySelector('#open').onclick=()=>{window.opening=reportLibraryDialog({central:fixture.central,communityId:ids.community,communityName:'Synthetic Community',selectedRevisionId:ids.approvedRevision,dialog,guard:()=>{if(!window.active)throw Error('Community changed');}});};window.ready=true;
</script></body></html>`;
const server=http.createServer(async(request,response)=>{try{const path=decodeURIComponent(new URL(request.url,'http://test').pathname);if(path==='/'){response.writeHead(200,{'content-type':'text/html'});response.end(html);return;}const file=resolve(root,'.'+path);if(!file.startsWith(root+'/'))throw Error('Invalid fixture route');const bytes=await readFile(file);response.writeHead(200,{'content-type':extname(file)==='.mjs'||extname(file)==='.js'?'text/javascript':'application/octet-stream'});response.end(bytes);}catch{response.writeHead(404);response.end('Not found');}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port;let browser;
const key=(kind,id)=>kind+':'+id,approvedKey=key('approved_forecast',ids.publication),draftKey=key('saved_revision',ids.draftRevision),originalKey=key('original_budget',ids.budget),strKey=key('approved_forecast',ids.strPublication);
const open=async page=>{await page.goto(url);await page.waitForFunction(()=>window.ready);await page.locator('#open').click();await page.waitForFunction(()=>document.querySelector('[data-library-export=pdf]')?.disabled===false);};
const choose=async(page,value)=>{await page.locator('[data-report-version]').selectOption(value);await page.waitForFunction(value=>document.querySelector('[data-report-version]')?.value===value&&document.querySelector('[data-library-export=pdf]')?.disabled===false,value);};
const download=async(page,format)=>{const pending=page.waitForEvent('download');await page.locator('[data-library-export='+format+']').click();const file=await pending,path=join(folder,file.suggestedFilename());await file.saveAs(path);await page.waitForFunction(()=>document.querySelector('[data-status]')?.textContent.includes('downloaded'));return {name:file.suggestedFilename(),bytes:await readFile(path)};};

const previewChecks=[];
const verifyPreview=async(page,book,label)=>{
 const cells=await page.locator('[data-report-cell]').evaluateAll(nodes=>nodes.map(el=>({kind:el.closest('table').dataset.reportTable,period:el.dataset.period,gl:el.dataset.gl,column:el.dataset.column,value:JSON.parse(el.dataset.rawValue)})));
 assert(cells.length>0,'Final chooser contains financial figures');
 for(const cell of cells){const sheet={monthly:'Monthly summary',gl:'GL detail',bridge:'STR contribution bridge'}[cell.kind],rows=XLSX.utils.sheet_to_json(book.Sheets[sheet],{defval:null});const row=rows.find(row=>(!cell.gl||row.GL===cell.gl)&&(!row.Period||row.Period===cell.period));assert(row,'Screen cell has exact matching XLSX row');assert.deepEqual(cell.value,row[cell.column]??null,'Screen raw value equals XLSX '+label+' '+cell.kind+' '+cell.period+' '+cell.gl+' '+cell.column);}
 const proof={label,cells:cells.length,numericZero:cells.filter(cell=>cell.value===0).length,missing:cells.filter(cell=>cell.value===null).length};previewChecks.push(proof);
 if(label==='draft'){assert(proof.numericZero>0);assert(proof.missing>0);assert(cells.some(cell=>cell.value===200.1234));}
 await page.locator('dialog').evaluate(el=>{el.querySelectorAll('details').forEach(detail=>detail.open=true);el.scrollTop=0;});
 if(process.env.ATLAS_REPORT_LIBRARY_QA_OUTPUT)await page.screenshot({path:join(folder,'report-library-'+label+'-preview.png'),fullPage:true});
};

try{
 browser=await chromium.launch({headless:true});const context=await browser.newContext({acceptDownloads:true,viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));let downloads=0;page.on('download',()=>downloads++);
 // Hold the actual PDF library load so a user changes selection while report generation awaits it.
 let releasePdf,enteredPdf;const pdfEntered=new Promise(resolve=>enteredPdf=resolve),pdfReleased=new Promise(resolve=>releasePdf=resolve);await page.route('**/vendor/pdf-lib-1.17.1.mjs*',async route=>{enteredPdf();await pdfReleased;await route.continue();});
 await open(page);assert.match(await page.locator('dialog').innerText(),/Download PDF for email \/ print/);assert.equal(await page.locator('[data-report-version]').inputValue(),approvedKey);assert.match(await page.locator('[data-report-details]').innerText(),/Prior approved Conventional/);
 await page.evaluate(()=>{const button=document.querySelector('[data-library-export=pdf]'),handler=button.onclick;button.onclick=(...args)=>window.exportAttempt=handler(...args);});await page.locator('[data-library-export=pdf]').click();await pdfEntered;await choose(page,draftKey);releasePdf();await page.evaluate(()=>window.exportAttempt);assert.equal(downloads,0,'Changing report selection cancels a late export before download');assert.match(await page.locator('[data-report-details]').innerText(),/DRAFT/);await page.unroute('**/vendor/pdf-lib-1.17.1.mjs*');
 const draftPdf=await download(page,'pdf'),draftXlsx=await download(page,'xlsx');assert.match(draftPdf.name,/DRAFT.*30000000-0000-0000-0000-000000000002/);assert.equal(draftPdf.bytes.subarray(0,5).toString(),'%PDF-');const draftBook=XLSX.read(draftXlsx.bytes,{type:'buffer'}),draftRows=XLSX.utils.sheet_to_json(draftBook.Sheets['GL detail'],{defval:null});assert.equal(draftRows[0].Forecast,200.1234);assert.match(JSON.stringify(draftRows),/DRAFT/);await verifyPreview(page,draftBook,'draft');
 await choose(page,approvedKey);const officialPdf=await download(page,'pdf'),officialXlsx=await download(page,'xlsx');assert.match(officialPdf.name,/APPROVED.*40000000-0000-0000-0000-000000000001/);assert.notEqual(officialPdf.name,draftPdf.name);assert.equal(officialPdf.bytes.subarray(0,5).toString(),'%PDF-');const approvedBook=XLSX.read(officialXlsx.bytes,{type:'buffer'});assert.equal(XLSX.utils.sheet_to_json(approvedBook.Sheets['GL detail'])[0].Active_baseline,100,'Older approved publication remains independent from current draft200');await verifyPreview(page,approvedBook,'approved');
 await choose(page,originalKey);assert.match(await page.locator('[data-report-details]').innerText(),/Approved original budget/);const originalPdf=await download(page,'pdf'),originalXlsx=await download(page,'xlsx');assert.match(originalPdf.name,/APPROVED.*50000000-0000-0000-0000-000000000001/);assert.equal(originalPdf.bytes.subarray(0,5).toString(),'%PDF-');const originalBook=XLSX.read(originalXlsx.bytes,{type:'buffer'}),originalRows=XLSX.utils.sheet_to_json(originalBook.Sheets['GL detail'],{defval:null});assert.equal(originalRows[0]['2026-09'],0);assert.equal(originalRows[0]['2026-10'],100);await verifyPreview(page,originalBook,'original');
 await choose(page,strKey);assert.match(await page.locator('[data-report-details]').innerText(),/separate Conventional parent/);const pairDownloads=[];const collect=file=>pairDownloads.push(file);page.on('download',collect);await page.locator('[data-library-export=xlsx]').click();await page.waitForFunction(()=>document.querySelector('[data-status]')?.textContent.startsWith('2 files downloaded'));page.off('download',collect);assert.equal(pairDownloads.length,2);assert.equal(new Set(pairDownloads.map(file=>file.suggestedFilename())).size,2);for(const file of pairDownloads){const path=join(folder,file.suggestedFilename());await file.saveAs(path);if(file.suggestedFilename().includes(ids.strPublication))await verifyPreview(page,XLSX.read(await readFile(path),{type:'buffer'}),'str');}
 // A late receipt from a previous selection must not replace the draft details or download identity.
 await choose(page,draftKey);await page.evaluate(()=>{window.fixture.onRead(async(request,result)=>{if(request.url==='/rpc/atlas_read_reforecast_publication')await new Promise(resolve=>{window.releaseReceipt=resolve;});return result;});});await page.locator('[data-report-version]').selectOption(approvedKey);await page.waitForFunction(()=>typeof window.releaseReceipt==='function');await choose(page,draftKey);await page.evaluate(()=>window.releaseReceipt());await page.evaluate(async()=>{await new Promise(resolve=>setTimeout(resolve,0));});assert.match(await page.locator('[data-report-details]').innerText(),/DRAFT/);assert.equal(await page.locator('[data-report-version]').inputValue(),draftKey);await page.evaluate(()=>window.fixture.onRead(null));
 // Access revoked after exact readback must prevent the actual export handler from downloading.
 const beforeDenied=downloads;await page.evaluate(()=>{window.fixture.profile.allowed_community_ids=[];});await page.locator('[data-library-export=pdf]').click();await page.waitForFunction(()=>document.querySelector('[data-status]')?.textContent.includes('access changed'));assert.equal(downloads,beforeDenied);
 const requests=await page.evaluate(()=>window.fixture.requests);assert(requests.every(row=>row.url==='/rpc/atlas_read_reforecast_publication'||!row.options.method||row.options.method==='GET'));assert(!requests.some(row=>/actual|finance|active_reforecast/.test(row.url)));assert.deepEqual(errors,[]);

 // Closing the dialog during a first PDF generation cancels its late download too.
 const closed=await context.newPage();closed.setDefaultTimeout(15000);let closedDownloads=0,releaseClosed,enterClosed;closed.on('download',()=>closedDownloads++);const closedEntered=new Promise(resolve=>enterClosed=resolve),closedReleased=new Promise(resolve=>releaseClosed=resolve);await closed.route('**/vendor/pdf-lib-1.17.1.mjs*',async route=>{enterClosed();await closedReleased;await route.continue();});await open(closed);await closed.evaluate(()=>{const button=document.querySelector('[data-library-export=pdf]'),handler=button.onclick;button.onclick=(...args)=>window.exportAttempt=handler(...args);});await closed.locator('[data-library-export=pdf]').click();await closedEntered;await closed.locator('[data-close]').click();releaseClosed();await closed.evaluate(()=>window.exportAttempt);assert.equal(closedDownloads,0);assert.equal(await closed.locator('dialog[open]').count(),0);
 if(process.env.ATLAS_REPORT_LIBRARY_QA_OUTPUT)await writeFile(join(folder,'browser-proof.json'),JSON.stringify({synthetic:true,productionAcceptance:false,previewChecks,downloads,readOnlyRequests:requests.length,historicalApproved:true,draft:true,originalBudget:true,strExactParentPair:true,lateSelectionCanceled:true,lateCloseCanceled:true,revokedAccessDenied:true},null,2)+'\n');
 console.log('PASS actual Chromium report library: select old approved, draft, original and STR; real PDF/XLSX downloads and immutable UUID filenames; XLSX reopens exact saved values; explicit DRAFT; Conventional/STR separate; stale selection and dialog-close cancel late PDF; revoked access denies download; no financial writes or current actual dependency.');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));if(!process.env.ATLAS_REPORT_LIBRARY_QA_OUTPUT)await rm(folder,{recursive:true,force:true});}
