/* Source acceptance runs the production browser UI against an isolated, disposable PostgreSQL fixture. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright');
const {PDFDocument,StandardFonts}=await import('../docs/portfolio-operations-dashboard/vendor/pdf-lib-1.17.1.mjs');
const cid='10000000-0000-0000-0000-000000000001',url=process.env.ATLAS_PROVIDER_TEST_URL||'http://127.0.0.1:8773';
let server=null,serverOutput='';
if(!process.env.ATLAS_PROVIDER_TEST_URL){
 server=spawn(process.execPath,['tools/reforecast-harness-server.cjs'],{cwd:process.cwd(),env:{...process.env,PORT:'8773'},stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Source fixture server did not become ready. '+serverOutput)),15000);server.once('exit',code=>{clearTimeout(timer);reject(Error('Source fixture server exited '+code+': '+serverOutput));});for(const stream of [server.stdout,server.stderr])stream.on('data',chunk=>{serverOutput+=chunk.toString();if(serverOutput.includes('acceptance http://127.0.0.1:8773')){clearTimeout(timer);resolve();}});});
}
const browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],transport=[];
page.setDefaultTimeout(12000);page.on('pageerror',error=>errors.push(error.message));
page.on('request',request=>{if(request.method()==='POST'&&request.url().includes('/__api/rpc/atlas_stage_reforecast_payload')){const body=request.postDataJSON();transport.push({action:body.p_action,requestId:body.p_request_id,communityId:body.p_community_id,bytes:Buffer.byteLength(request.postData())});}});
await fs.mkdir('output/playwright/forecast-provider',{recursive:true});
const makePdf=async lines=>{const document=await PDFDocument.create(),font=await document.embedFont(StandardFonts.Helvetica),sheet=document.addPage([842,595]);lines.forEach((line,index)=>sheet.drawText(line,{x:18,y:568-index*20,size:7,font}));return Buffer.from(await document.save());};
const syntheticStatement=await makePdf([
 'Autopilot Revenue Share 99999','Property Name Synthetic Community Total Revenue $1,000.00','Month August 2026 Management Fee ($400.00)','Occupancy Rate 50.00% Install / Other Fees $0.00','FF&E Service Fee ($100.00)','WiFi Service Fee $0.00','Partner Adjustment $0.00','Net Allocation $500.00','Unit Level Detail',
 'Unit Number Occupied Nights Rent Utilities Late Fee Damages Parking Pet Other Total Revenue Net Rent % Net Rent Install / Other Fees FF&E Service Fee WiFi Service Fee Partner Adjustment Net Allocation',
 'SYNTHETIC-UNIT-A 31 $1000.00 $0.00 $0.00 $0.00 $0.00 $0.00 $0.00 $1000.00 60% $600.00 $0.00 ($100.00) $0.00 $0.00 $500.00',
 'SYNTHETIC-UNIT-B 0 $0.00 $0.00 $0.00 $0.00 $0.00 $0.00 $0.00 $0.00 0% $0.00 $0.00 $0.00 $0.00 $0.00 $0.00','Reservation Level Detail',
 'Unit Number Reference ID Start Date End Date Standby Rent Utilities Late Fee Damages Parking Pet Other Total Revenue Net Rent % Net Rent Partner Adjustment Reservation Net',
 'SYNTHETIC-UNIT-A SYNTHETIC-RESERVATION 2026-08-01 2026-09-01 No $1000.00 $0.00 $0.00 $0.00 $0.00 $0.00 $0.00 $1000.00 60% $600.00 $0.00 $600.00'
]);
const sourceBytes=process.env.ATLAS_PROVIDER_SAMPLE_PATH?await fs.readFile(process.env.ATLAS_PROVIDER_SAMPLE_PATH):syntheticStatement,expectedNet=process.env.ATLAS_PROVIDER_SAMPLE_PATH?11349.13:500;
const rpc=(name,args)=>page.evaluate(async({name,args})=>window.ATLAS_CENTRAL.fetchJson('/rpc/'+name,{method:'POST',body:JSON.stringify(args)}),{name,args});
const sources=()=>rpc('atlas_read_reforecast_sources',{p_community_id:cid});
const idle=()=>page.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled);
const sourceDialog=()=>page.locator('dialog:has([data-source-type])');
const inspect=async()=>{await sourceDialog().locator('[data-inspect]').click();await page.waitForFunction(()=>!document.querySelector('[data-inspect]')?.disabled);assert.match(await sourceDialog().locator('[data-status]').innerText(),/Inspection complete/);};
const saveSource=async fileName=>{const start=transport.length;await sourceDialog().locator('[data-source-confirm]').check();await sourceDialog().locator('[data-save-source]').click();await page.waitForFunction(()=>document.querySelector('dialog:has([data-source-type]) [data-status]')?.textContent.includes('Original bytes saved and read back'));const receipt=(await sources()).find(row=>row.fileName===fileName);assert(receipt,'Source receipt must read back');const calls=transport.slice(start);assert.equal(calls[0]?.action,'begin');assert.equal(calls.at(-1)?.action,'finalize');assert(calls.some(row=>row.action==='put'),'Provider source must use the real bounded chunk protocol');assert.equal(new Set(calls.map(row=>row.requestId)).size,1);assert(calls.every(row=>row.communityId===cid&&row.bytes<=263168));return receipt;};
const reviewSource=async(fileName,{net=false,account='5120'}={})=>{
 await sourceDialog().locator('[data-receipts] tr').filter({hasText:fileName}).locator('[data-review-source]').click();const dialog=page.locator('dialog:has([data-review-decision])');
 await dialog.locator('[data-review-period]').fill(fileName.includes('contract')?'2026-09':'2026-08');if(net)await dialog.locator('[data-net-map]').selectOption('net_allocation');await dialog.locator('[data-source-gl]').fill(account);await dialog.locator('[data-source-reason]').fill('Compared the original bytes, full-month totals and reviewed mapping in the isolated fixture');await dialog.locator('[data-review-confirm]').check();await dialog.locator('[data-review-decision=approved]').click();await dialog.waitFor({state:'detached'});return (await sources()).find(row=>row.fileName===fileName);
};
try{
 await page.goto(url);await page.locator('[data-community]').selectOption(cid);await idle();await page.locator('[data-new]').click();await page.locator('[data-first]').fill('2026-09');await page.locator('[data-first]').dispatchEvent('change');await page.locator('[data-last]').fill('2026-10');await page.locator('[data-last]').dispatchEvent('change');await page.waitForFunction(()=>!document.querySelector('[data-create]')?.disabled);await page.locator('dialog [data-calendar-confirm]').check();await page.locator('[data-create]').click();await page.locator('[data-edit=reviewerId]').selectOption('00000000-0000-0000-0000-000000000001');await page.locator('[data-edit=reason]').fill('Synthetic editable draft for source acceptance');await page.locator('[data-action=save_draft]').click();await idle();assert.equal(await page.locator('[role=alert]').count(),0);
 await page.getByText('Sources and baseline lineage',{exact:true}).click();await page.locator('[data-provider-sources]').click();await sourceDialog().locator('[data-source-period]').fill('2026-08');await sourceDialog().locator('[data-source-file]').setInputFiles({name:'local-provider-sample.pdf',mimeType:'application/pdf',buffer:sourceBytes});await inspect();
 const preview=JSON.parse(await sourceDialog().locator('[data-source-preview] pre').innerText());assert.equal(preview.status,'reconciled');assert.equal(preview.summary.netAllocation,expectedNet);assert.equal(preview.summary.occupancyPercent,process.env.ATLAS_PROVIDER_SAMPLE_PATH?50.48:50);assert.equal(preview.metrics.netIncome,null);assert(!Object.hasOwn(preview,'units'));assert(!Object.hasOwn(preview,'reservations'));assert(!JSON.stringify(preview).includes('SYNTHETIC-UNIT'));assert(!JSON.stringify(preview).includes('SYNTHETIC-RESERVATION'));
 let provider=await saveSource('local-provider-sample.pdf');assert.equal(provider.sourceHash,createHash('sha256').update(sourceBytes).digest('hex'));assert.equal(provider.statement.summary.netAllocation,expectedNet);provider=await reviewSource('local-provider-sample.pdf',{net:true});assert.equal(provider.review.status,'approved');assert.equal(provider.statement.readbackVerified,true);assert.equal(provider.statement.metrics.netIncome,expectedNet);
 await page.screenshot({path:'output/playwright/forecast-provider/provider-receipt.png',fullPage:true});
 // The public source reader in an independent authorized browser returns the same immutable receipt.
 const second=await browser.newContext(),other=await second.newPage();await other.goto(url+'/?user=2');const independent=await other.evaluate(async cid=>window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_sources',{method:'POST',body:JSON.stringify({p_community_id:cid})}),cid);assert.equal(independent[0].sourceHash,provider.sourceHash);assert.equal(independent[0].reviewHash,provider.reviewHash);assert.equal(independent[0].statement.metrics.netIncome,expectedNet);assert(!JSON.stringify(independent).includes('originalFile'));assert(!JSON.stringify(independent).includes('reservationId'));assert(!JSON.stringify(independent).includes('unitId'));
 const denied=await other.evaluate(async({uploadId})=>{try{await window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_review_reforecast_source',{method:'POST',body:JSON.stringify({p_upload_id:uploadId,p_request_id:crypto.randomUUID(),p_review:{}})});return 'unexpected review';}catch(error){return error.message;}},{uploadId:provider.uploadId});assert.match(denied,/Admin or executive/);await second.close();

 // An unknown RISE template uses explicit manual mapping, never automatic inference.
 await sourceDialog().locator('[data-source-type]').selectOption('rise_str');await sourceDialog().locator('[data-source-file]').setInputFiles({name:'synthetic-rise-statement.pdf',mimeType:'application/pdf',buffer:await makePdf(['RISE STR monthly statement - August 2026','USD | 31 days | 2 available units | 62 available unit-nights | 31 occupied unit-nights','Occupancy 50% | Gross income 1000.00 | Service fee -100.00 | Net allocation 900.00'])});await sourceDialog().locator('[data-manual-fields] summary').click();
 for(const [key,value] of Object.entries({currency:'USD',calendarDays:'31',availableUnits:'2',availableUnitNights:'62',occupiedUnitNights:'31',occupancyPercent:'50',grossIncome:'1000',netAllocation:'900'}))await sourceDialog().locator('[data-manual-field='+key+']').fill(value);
 await sourceDialog().locator('[data-manual-reference]').fill('Page 1, monthly statement summary');await sourceDialog().locator('[data-manual-reason]').fill('Reviewed each mapped source figure');await sourceDialog().locator('[data-manual-fees]').fill('service_fee | -100 | Page 1, service fee');await sourceDialog().locator('[data-manual-complete]').check();await sourceDialog().locator('[data-manual-confirm]').check();
 // Missing source values stay unavailable and cannot be approved after immutable intake.
 await sourceDialog().locator('[data-manual-field=grossIncome]').fill('');await inspect();let invalid=JSON.parse(await sourceDialog().locator('[data-source-preview] pre').innerText());assert.equal(invalid.status,'needs_review');assert.equal(invalid.metrics.grossIncome,null);assert(invalid.checks.some(row=>row.code==='summary_net_allocation'&&row.status==='unavailable'));await saveSource('synthetic-rise-statement.pdf');
 await sourceDialog().locator('[data-receipts] tr').filter({hasText:'synthetic-rise-statement.pdf'}).locator('[data-review-source]').click();const invalidReview=page.locator('dialog:has([data-review-decision])');await invalidReview.locator('[data-review-period]').fill('2026-08');await invalidReview.locator('[data-net-map]').selectOption('net_allocation');await invalidReview.locator('[data-source-gl]').fill('5120');await invalidReview.locator('[data-source-reason]').fill('Attempt approval of incomplete source in the isolated fixture');await invalidReview.locator('[data-review-confirm]').check();await invalidReview.locator('[data-review-decision=approved]').click();await page.waitForFunction(()=>document.querySelector('dialog:has([data-review-decision]) [data-status]')?.textContent.includes('Statement must reconcile'));assert(await invalidReview.isVisible());await invalidReview.locator('[data-close]').click();assert.equal((await sources()).find(row=>row.fileName==='synthetic-rise-statement.pdf').review,null);
 await sourceDialog().locator('[data-manual-field=grossIncome]').fill('1000');await sourceDialog().locator('[data-manual-field=occupiedUnitNights]').fill('63');await sourceDialog().locator('[data-manual-field=occupancyPercent]').fill('101.61');await inspect();invalid=JSON.parse(await sourceDialog().locator('[data-source-preview] pre').innerText());assert.equal(invalid.status,'needs_review');assert.equal(invalid.metrics.occupiedUnitNights,63);assert.equal(invalid.metrics.availableUnitNights,62);
 await sourceDialog().locator('[data-manual-field=occupiedUnitNights]').fill('31');await sourceDialog().locator('[data-manual-field=occupancyPercent]').fill('-50');await inspect();invalid=JSON.parse(await sourceDialog().locator('[data-source-preview] pre').innerText());assert.equal(invalid.status,'needs_review');assert(invalid.checks.some(row=>row.code==='occupancy_percent'&&row.status==='mismatch'));
 await sourceDialog().locator('[data-manual-field=occupancyPercent]').fill('50');await sourceDialog().locator('[data-source-file]').setInputFiles({name:'synthetic-rise-reviewed.pdf',mimeType:'application/pdf',buffer:await makePdf(['RISE STR monthly statement - August 2026','USD | 31 days | 2 available units | 62 available unit-nights | 31 occupied unit-nights','Occupancy 50% | Gross income 1000.00 | Service fee -100.00 | Net allocation 900.00'])});await inspect();const mapped=JSON.parse(await sourceDialog().locator('[data-source-preview] pre').innerText());assert.equal(mapped.status,'reconciled');assert.equal(mapped.summary.netAllocation,900);await saveSource('synthetic-rise-reviewed.pdf');const rise=await reviewSource('synthetic-rise-reviewed.pdf',{net:true});assert.equal(rise.statement.metrics.netIncome,900);assert.equal(rise.statement.metrics.occupiedUnitNights,31);

 // Create a scoped canonical Contract Manager record before preserving and reviewing its source receipt.
 await sourceDialog().locator('[data-source-type]').selectOption('contract');await sourceDialog().locator('[data-source-period]').fill('2026-09');await sourceDialog().locator('[data-contract-fields] summary').click();await sourceDialog().locator('[data-new-contract]').click();const contractEditor=page.locator('dialog:has([data-save-contract])');
 for(const [key,value] of Object.entries({vendor:'Synthetic contract vendor',service:'Common-area service',effectiveDate:'2026-09-01',endDate:'2026-12-31',monthlyAmount:'100',reason:'Create the synthetic scoped contract record'}))await contractEditor.locator('[data-record='+key+']').fill(value);
 await contractEditor.locator('[data-save-contract]').click();await contractEditor.waitFor({state:'detached'});const contractId=await sourceDialog().locator('[data-contract=contractId]').inputValue();assert.match(contractId,/^[a-f0-9-]{36}$/);await sourceDialog().locator('[data-contract=accountCode]').fill('6200');await sourceDialog().locator('[data-contract=term]').fill('Four full calendar months');await sourceDialog().locator('[data-contract=extractionConfidence]').fill('Manually verified');await sourceDialog().locator('[data-source-file]').setInputFiles({name:'synthetic-contract.pdf',mimeType:'application/pdf',buffer:await makePdf(['Synthetic contract vendor - Common-area service','Effective September 1, 2026 through December 31, 2026','Monthly contracted amount 100.00 USD. No escalation clause.'])});await inspect();await saveSource('synthetic-contract.pdf');const contractReceipt=await reviewSource('synthetic-contract.pdf',{account:'6200'});assert.equal(contractReceipt.contract.contractId,contractId);assert.equal(contractReceipt.contract.monthlyAmount,100);
 await sourceDialog().locator('[data-receipts] tr').filter({hasText:'synthetic-contract.pdf'}).locator('[data-apply-contract]').click();const contractForecast=page.locator('dialog:has([data-calculate-contract])');await contractForecast.locator('[data-method]').selectOption('user_rate');await contractForecast.locator('[data-user-rate]').fill('200');await contractForecast.locator('[data-contract-reason]').fill('Reviewed explicit monthly forecast rate with separate one-month override');await contractForecast.locator('[data-calculate-contract]').click();await contractForecast.locator('[data-contract-override="2026-09"]').fill('220');await contractForecast.locator('[data-apply-contract]').click();await contractForecast.waitFor({state:'detached'});await sourceDialog().locator('[data-close]').click();await page.locator('[data-action=save_draft]').click();await idle();assert.equal(await page.locator('[role=alert]').count(),0,(await page.locator('[role=alert]').allTextContents()).join(' '));
 const workspace=await rpc('atlas_read_reforecast_workspace',{p_community_ids:[cid]}),draft=workspace[0];assert.equal(draft.head.status,'working_draft');const overrides=draft.revision.payload.overrides.filter(row=>row.source?.contractUploadId===contractReceipt.uploadId);assert.deepEqual(overrides.map(row=>[row.period,row.amount]),[['2026-09',220],['2026-10',200]]);assert.equal(draft.revision.payload.contractOverrides.length,1);assert.equal(draft.revision.payload.contractOverrides[0].originalValue,200);assert.equal(draft.revision.payload.contractOverrides[0].overrideValue,220);assert.equal((await rpc('atlas_read_forecast_contracts',{p_community_id:cid}))[0].amount,100,'Forecast overrides do not rewrite the canonical contract');assert.equal((await sources()).find(row=>row.uploadId===contractReceipt.uploadId).contract.monthlyAmount,100,'The original receipt remains immutable');
 await page.screenshot({path:'output/playwright/forecast-provider/contract-draft.png',fullPage:true});assert.deepEqual(errors,[]);
 console.log('PASS provider browser: native PDF extraction and signed reconciliation, original hash, private-summary boundary, source approval/readback in independent sessions, denied Regional review, explicit RISE mapping with incomplete and impossible occupancy rejection, canonical contract source review and separate user-rate override in an editable draft.');
}catch(error){console.error('Public UI status at failure:',await page.locator('dialog [data-status],[role=alert]').allTextContents());await page.screenshot({path:'output/playwright/forecast-provider/failure.png',fullPage:true});throw error;}
finally{await browser.close();if(server){server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}}
