// Current governed atomic workflow regression for bounded private validation memory.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
const root=path.join(__dirname,'..'),migration=name=>fs.readFileSync(path.join(root,'supabase/migrations',name),'utf8');
(async()=>{
 const {parseReforecastWorkbook}=await import('../docs/portfolio-operations-dashboard/features/reforecast-intake.mjs');
 const {planningMappingDispositions}=await import('../docs/portfolio-operations-dashboard/features/planning-governance.mjs');
 const {prepareScopedReforecastEvidence}=await import('../docs/portfolio-operations-dashboard/features/reforecast-authority.mjs');
 const XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
 const {db,A,B,BUDGET,CLOSE,signIn}=await fixture(),owner='00000000-0000-0000-0000-000000000001';
 const call=async(name,args)=>{const vp=name==='atlas_save_reforecast_scenario'&&args[4]==='vp_approve';if(vp)await signIn(5);try{return (await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result}finally{if(vp)await signIn(1)}};
 await db.exec('reset role');
 await db.exec(migration('20260924121641_planning_cell_workbook_integrity_governance.sql'));
 // Install the exact immutable audit storage/resolution functions; the remainder
 // of this migration concerns financial close ingestion outside this fixture.
 await db.exec(migration('20260924121647_immutable_workbook_audits_and_monthly_governance.sql').split('alter function atlas_private.finance_intake_validation')[0]);
 for(const file of ['20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql','20260925020220_reforecast_import_source_relationships.sql','20260925020222_reforecast_saved_json_str_programme.sql','20260925020226_reforecast_import_source_occurrence_index.sql','20260925071533_reforecast_request_identity_consistency.sql','20260925162050_budget_governed_draft_investor_lifecycle.sql'])await db.exec(migration(file));

 await db.exec("create function atlas_private.budget_calendar(cid uuid) returns jsonb language sql as $$select '{\"verified\":true,\"basis\":\"calendar\",\"startMonth\":1}'::jsonb$$");
 await db.exec(migration('20260928141143_reviewed_noncash_forecast_presentation.sql'));
 await db.exec(migration('20260928142628_indexed_import_validation_evidence.sql'));
 const memoryMigration=migration('20260928144620_bounded_reforecast_validation_memory.sql');
 await db.exec(memoryMigration);
 const relationshipOriginalDefinition=(await db.query("select pg_get_functiondef('atlas_private.validate_reforecast_source_relationships(jsonb,jsonb,jsonb)'::regprocedure) d")).rows[0].d;
 const coreDefinition=(await db.query("select pg_get_functiondef('atlas_private.calculate_reforecast_before_saved_str(jsonb,jsonb)'::regprocedure) d")).rows[0].d;
 const changedCore=coreDefinition.replace("   state:=jsonb_set(state,array[p||'|'||code],line,true);","   state :=jsonb_set(state,array[p||'|'||code],line,true);");
 assert.notEqual(changedCore,coreDefinition);await db.exec(changedCore);await db.exec('begin');await assert.rejects(()=>db.exec(migration('20260928192500_verified_workbook_blank_forecast_semantics.sql')),/prerequisite differs/i);await db.exec('rollback');assert.equal((await db.query("select to_regprocedure('atlas_private.reforecast_workbook_policy(jsonb)') p")).rows[0].p,null);await db.exec(coreDefinition);
 await db.exec(migration('20260928192500_verified_workbook_blank_forecast_semantics.sql'));
 const approvedMetricMappings={revenue:[{glCode:'5120',factor:1},{glCode:'5220',factor:1}],expenses:[{glCode:'6100',factor:1},{glCode:'6200',factor:1}],capital:[{glCode:'8100',factor:1}]};
 await db.query("update atlas_approved_budget_versions set payload=payload||jsonb_build_object('metricMappings',$1::jsonb,'mappingVersion','approved-fixture-v1') where version_id=$2",[approvedMetricMappings,BUDGET]);
 await signIn(1);
 const initialSource=await call('atlas_read_reforecast_builder_source',[A,['2026-02'],[BUDGET],null,'original_budget',null]);
 assert.equal(initialSource.registry.version,null);assert.equal(initialSource.baseline.approvedMetricMappings[0].versionId,BUDGET);assert.deepEqual(initialSource.baseline.approvedMetricMappings[0].metricMappings,approvedMetricMappings);
 assert.equal((await db.query('select count(*)::int n from atlas_reforecast_registries')).rows[0].n,0,'published metric evidence never creates a registry implicitly');
 const accounts=[['5120','Rent','income'],['5220','Vacancy','contra_income'],['6100','Payroll','expense'],['6200','Noncash','below_noi'],['8100','Capital','capital']].map(([accountCode,category,nature])=>({accountCode,category,nature,placement:['capital','below_noi'].includes(nature)?'below_noi':'above_noi',nonCash:nature==='below_noi',effectiveFrom:'2026-01'}));
 const registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),{accounts,nonCashClassificationVersion:1,driverMappings:{},reason:'Reviewed exact import registry',effectiveDate:'2026-01-01'}]);
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Scenario','Plan','Currency','Local'],['GL','Account','Feb 2026','Mar 2026'],['5120','Rent',1001.005,1002.5],['5220','Vacancy',0,-1.005],['6100','Payroll',null,null],['6200','Noncash',null,null]]),'Plan');
 const bytes=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});let evidence=await parseReforecastWorkbook(bytes,{xlsx:XLSX,fileName:'Blank-source.xlsx',includeOriginalBytes:true});
 const periods=['2026-02','2026-03'],reviewedAt='2026-09-28T00:00:00Z',assignment={communityId:A,confirmed:true,sourceEntities:[],actorId:owner,reason:'Reviewed community'};
 const policy={schemaVersion:1,mode:'workbook_exact',blankDisposition:'preserve_null',confirmed:true,reviewedBy:owner,reviewedAt,reason:'Preserve source blanks and exact numeric values'};
 const mapping={confirmed:true,version:registry.version_id,propertyAssignment:assignment,sourceScenario:'Plan',currency:'USD',periods,selectedLineIds:evidence.lines.map(l=>l.id),accountMappings:accounts.map(a=>({...a,sourceAccountCode:a.accountCode,sheet:'Plan',department:null,signMultiplier:1,allowReversal:false})),reason:'Import exact reviewed forecast values',reviewedBy:owner,reviewedAt,workbookSourcePolicy:policy,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:'Plan',reviewedBy:owner,reviewedAt},integrityReviews:[]};
 evidence=(await prepareScopedReforecastEvidence(evidence,mapping,{xlsx:XLSX,sourceBytes:bytes})).evidence;
 const audit=await call('atlas_save_workbook_audit',[A,evidence.source.sha256,evidence.integrity,randomUUID()]);
 mapping.inputReviews=evidence.lines.filter(l=>l.amount!==null).map(l=>({cellId:l.id,confirmed:true,ownerId:owner,effectivePeriod:l.period,before:l.amount,after:l.amount,reason:'Reviewed input value',reviewedAt,integrityFingerprint:audit.fingerprint}));Object.assign(mapping,planningMappingDispositions(evidence,mapping));
 // A reviewed cell blank is separate from its source row's legacy disposition.
 mapping.rowDispositions=mapping.rowDispositions.map(row=>row.row>=5?{...row,disposition:'subtotal_control'}:row);
 mapping.currencyMapping={sourceCurrency:'Local',reportingCurrency:'USD',method:'identity',confirmed:true,reviewedBy:owner,reviewedAt,reason:'Reviewed Local as USD'};
 const upload=await call('atlas_save_reforecast_upload',[A,randomUUID(),{...evidence,integrity:{auditId:audit.audit_id,fingerprint:audit.fingerprint},propertyAssignment:assignment}]);
 const payload={name:'Reviewed workbook blanks',model:'conventional',scenarioPurpose:'conventional',governanceSchemaVersion:2,calendar:{...mapping.calendar,scenario:'Reviewed workbook blanks'},periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:owner,reviewerId:owner,drivers:[],overrides:[],reason:'Review exact workbook blank semantics'};
 const scenario=randomUUID(),request=randomUUID();
 let result=await call('atlas_create_reforecast_from_import',[A,scenario,0,request,upload.upload_id,mapping,payload]);
 assert.equal(result.receipt.importedCells.length,8);assert.equal(result.receipt.reconciliation.zeroCellCount,1);assert.equal(result.receipt.reconciliation.workbookBlankCellCount,4);
 assert.equal(result.snapshot.workbookCoverage.sourceAbsentCellCount,2);assert.equal(result.snapshot.status,'action_required');
 assert.ok(result.snapshot.lines.filter(l=>l.disposition==='source_absent').every(l=>l.forecast===null&&l.originalBudget===20));await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,scenario,result.head.revision,randomUUID(),'submit',result.revision.payload]),/blockers/i);await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,scenario,result.head.revision,randomUUID(),'vp_approve',result.revision.payload]),/blockers/i);assert.deepEqual((await call('atlas_read_reforecast_import_receipt',[A,request])).receipt,result.receipt);
 assert.equal(result.snapshot.knownValueTotals.revenue,2002.5);assert.equal(result.snapshot.knownValueTotals.nonCashDepreciationAmortization,0);
 for(const cell of result.receipt.importedCells){const line=result.snapshot.lines.find(l=>l.period===cell.period&&l.accountCode===cell.accountCode);assert.equal(line.forecast,cell.amount);if(cell.isBlank){assert.equal(line.disposition,'workbook_blank');assert.equal(line.legitimateBlank,true);assert.equal(line.selectedBaseline,cell.accountCode==='6100'?200:50);const compact=result.revision.payload.overrides.find(o=>o.sourceLineId===cell.sourceLineId);assert.deepEqual(Object.keys(compact).sort(),['accountCode','amount','disposition','isBlank','legitimateBlank','period','sourceLineId','uploadId'].sort());}}
 const {computeReforecast,roundMoney}=await import('../docs/portfolio-operations-dashboard/features/reforecast-engine.mjs');
 const js=computeReforecast({...result.source,scenario:{...result.revision.payload,versionId:result.revision.revision_id,driverVersion:result.revision.payload.driverVersion||'fixture-driver'}});
 assert.deepEqual(js.knownValueTotals,result.snapshot.knownValueTotals);assert.deepEqual(js.totals.reforecast,result.snapshot.totals.reforecast);assert.deepEqual(js.workbookCoverage,result.snapshot.workbookCoverage);
 // Private attestations bind an exact immutable context; public payloads cannot
 // supply one, and each ordinary save rebuilds it before validation.
 await db.exec('reset role');
 const proofValid=async(source,config)=>(await db.query('select atlas_private.reforecast_workbook_relationship_proof($1::jsonb,$2::jsonb) valid',[source,config])).rows[0].valid;
 const firstProof=result.source.workbookRelationshipProofs[upload.upload_id];assert.equal(firstProof.schemaVersion,1);assert.equal(firstProof.auditId,audit.audit_id);assert.equal(await proofValid(result.source,result.revision.payload),true);
 for(const field of ['schemaVersion','communityId','uploadId','sourceHash','auditId','mappingFingerprint']){const changed=structuredClone(result.source);changed.workbookRelationshipProofs[upload.upload_id][field]=field==='schemaVersion'?2:'different';assert.equal(await proofValid(changed,result.revision.payload),false,field);}
 const malformed=structuredClone(result.source);malformed.workbookRelationshipProofs[upload.upload_id]=null;assert.equal(await proofValid(malformed,result.revision.payload),false);
 for(const mutate of [c=>c.importMapping.reason+=' changed',c=>c.importMapping.selectedLineIds.pop(),c=>c.uploadId=randomUUID()]){const changed=structuredClone(result.revision.payload);mutate(changed);assert.equal(await proofValid(result.source,changed),false);}
 assert.equal(await proofValid({...result.source,communityId:B},result.revision.payload),false);
 const deterministic=(await db.query('select atlas_private.reforecast_source_for_config($1::uuid,$2::jsonb) a,atlas_private.reforecast_source_for_config($1::uuid,$2::jsonb) b',[A,result.revision.payload])).rows[0];assert.equal(deterministic.a.sourceVersion,deterministic.b.sourceVersion);assert.deepEqual(deterministic.a.workbookRelationshipProofs,deterministic.b.workbookRelationshipProofs);
 await db.query("update atlas_user_profiles set status='inactive' where user_id=$1",[owner]);await db.query("select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000005',false)");assert.equal(await proofValid(result.source,result.revision.payload),false);await assert.rejects(()=>db.query('select atlas_private.reforecast_source_for_config($1::uuid,$2::jsonb)',[A,result.revision.payload]),/authorized owner/i);await db.query("update atlas_user_profiles set status='active' where user_id=$1",[owner]);await signIn(1);
 const injected={...payload,source:result.source,workbookRelationshipProofs:result.source.workbookRelationshipProofs};const injectedMapping=structuredClone(mapping);injectedMapping.selectedLineIds[0]='Plan!Z999';await assert.rejects(()=>call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),upload.upload_id,injectedMapping,injected]),/selected|source|cell/i);
 const injectedSaved=await call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',{...result.revision.payload,source:result.source,workbookRelationshipProofs:result.source.workbookRelationshipProofs}]);assert.deepEqual(injectedSaved.source.workbookRelationshipProofs,result.source.workbookRelationshipProofs);assert.equal(injectedSaved.snapshot.workbookCoverage.workbookBlankCellCount,4);
 assert.deepEqual((await call('atlas_create_reforecast_from_import',[A,scenario,0,request,upload.upload_id,mapping,payload])).receipt,result.receipt);
 // Direct API writes cannot bypass source coverage by omitting the UI policy.
 const legacyMapping=structuredClone(mapping);delete legacyMapping.workbookSourcePolicy;legacyMapping.selectedLineIds=evidence.lines.filter(l=>l.amount!==null).map(l=>l.id);
 const legacyId=randomUUID(),legacyRequest=randomUUID();const legacy=await call('atlas_create_reforecast_from_import',[A,legacyId,0,legacyRequest,upload.upload_id,legacyMapping,payload]);
 assert.ok(legacy.snapshot.diagnostics.some(d=>d.code==='workbook_source_policy_required'));assert.equal(legacy.snapshot.status,'action_required');
 await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,legacyId,legacy.head.revision,randomUUID(),'submit',legacy.revision.payload]),/blockers/i);
 const stripped=structuredClone(legacy.revision.payload);for(const key of ['uploadId','importMapping','importHistory','importIssues'])delete stripped[key];stripped.overrides=[];
 await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,legacyId,legacy.head.revision,randomUUID(),'save_draft',stripped]),/provenance/i);
 const discarded=structuredClone(legacy.revision.payload);discarded.overrides=[];discarded.importHistory=[];
 const discardedDraft=await call('atlas_save_reforecast_scenario',[A,legacyId,legacy.head.revision,randomUUID(),'save_draft',discarded]);assert.ok(discardedDraft.snapshot.diagnostics.filter(d=>d.code==='workbook_source_policy_required').length>=10);
 assert.deepEqual((await call('atlas_create_reforecast_from_import',[A,legacyId,0,legacyRequest,upload.upload_id,legacyMapping,payload])).receipt,legacy.receipt,'immutable request retry remains exact after later edits');
 const legacyJs=computeReforecast({...legacy.source,scenario:{...legacy.revision.payload,versionId:legacy.revision.revision_id,driverVersion:'fixture'}});assert.equal(legacyJs.diagnostics.filter(d=>d.code==='workbook_source_policy_required').length,legacy.snapshot.diagnostics.filter(d=>d.code==='workbook_source_policy_required').length);
 // Even a forged blank annotation cannot replace a populated numeric raw cell.
 await db.exec('reset role');const annotated={...evidence.lines.find(l=>l.amount!==null),amount:null,blank:true,formula:null,cachedValue:null},raw={value:42,formula:null,type:'n',address:annotated.address,row:annotated.row,column:annotated.column};
 assert.equal((await db.query('select atlas_private.reforecast_workbook_blank($1::jsonb,$2::jsonb,atlas_private.reforecast_workbook_predicate_mapping($3::jsonb),$4::jsonb) valid',[annotated,raw,mapping,{[annotated.id]:{id:annotated.id,sheet:annotated.sheet,address:annotated.address,row:annotated.row,column:annotated.column}}])).rows[0].valid,false);await signIn(1);
 const retiredSource=structuredClone(result.source);Object.assign(retiredSource.registry.accounts.find(a=>a.accountCode==='8100'),{retiredAfter:'2026-01',retirementReason:'Reviewed prospective retirement',successorDisposition:'no_successor'});await db.exec('reset role');const retiredSnapshot=(await db.query('select atlas_private.calculate_reforecast($1::jsonb,$2::jsonb) snapshot',[retiredSource,result.revision.payload])).rows[0].snapshot;await signIn(1);assert.ok(retiredSnapshot.lines.filter(l=>l.accountCode==='8100').every(l=>l.forecast===0));assert.equal(retiredSnapshot.workbookCoverage.sourceAbsentCellCount,0);const retiredJs=computeReforecast({...retiredSource,scenario:{...result.revision.payload,versionId:result.revision.revision_id,driverVersion:'fixture'}});assert.deepEqual(retiredJs.totals.reforecast,retiredSnapshot.totals.reforecast);
 const originalReceipt=structuredClone(result.receipt),prior=structuredClone(result.revision);
 const oldHistory=structuredClone(result.revision.payload.importHistory);
 const {projectImportUpdatePayload,verifyImportReadback}=await import('../docs/portfolio-operations-dashboard/features/reforecast-store.mjs');
 verifyImportReadback(result,{communityId:A,scenarioId:scenario,requestId:request,uploadId:upload.upload_id,mapping,expectedLines:result.receipt.importedCells});
 const scoped=structuredClone(mapping);scoped.workbookSourcePolicy.outsideForecastScope=periods.map(period=>({period,accountCode:'8100',confirmed:true,reviewedBy:owner,reviewedAt,reason:'Explicitly outside this workbook forecast source scope'}));
 const numericScope=structuredClone(scoped);numericScope.selectedLineIds=evidence.lines.filter(l=>l.amount!==null).map(l=>l.id);const scopeOnly=await call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),upload.upload_id,numericScope,payload]);assert.equal(scopeOnly.source.workbookBlankCells.length,0);assert.equal(scopeOnly.source.workbookOutsideScopeCells.length,2);assert.equal(scopeOnly.source.workbookRelationshipProofs[upload.upload_id].auditId,audit.audit_id);await db.exec('reset role');assert.equal(await proofValid(scopeOnly.source,scopeOnly.revision.payload),true);await signIn(1);
 const compact=projectImportUpdatePayload(result.revision.payload,{uploadId:upload.upload_id,mapping:scoped,expectedLines:result.receipt.importedCells});
 const updateRequest=randomUUID();result=await call('atlas_create_reforecast_from_import',[A,scenario,result.head.revision,updateRequest,upload.upload_id,scoped,compact]);
 assert.equal(result.snapshot.workbookCoverage.outsideForecastScopeCellCount,2);assert.equal(result.snapshot.workbookCoverage.complete,true);assert.equal(result.snapshot.completeness.blockerCount,0,JSON.stringify(result.snapshot.diagnostics));
 assert.equal(result.snapshot.totals.reforecast.cashFlow,2002.5);
 for(const line of result.snapshot.lines.filter(l=>l.accountCode==='8100')){assert.equal(line.forecast,null);assert.equal(line.originalBudget,20);assert.equal(line.legitimateBlank,false);assert.equal(line.disposition,'outside_forecast_scope');}
 const ordinaryPayload=structuredClone(result.revision.payload);ordinaryPayload.importHistory=[...oldHistory,...ordinaryPayload.importHistory];
 const ordinary=await call('atlas_save_reforecast_scenario',[A,scenario,result.head.revision,randomUUID(),'save_draft',ordinaryPayload]);assert.deepEqual(ordinary.snapshot.workbookCoverage,result.snapshot.workbookCoverage);
 const narrowed=structuredClone(ordinary.revision.payload);narrowed.importMapping.periods=[periods[0]];narrowed.importMapping.selectedLineIds=evidence.lines.filter(l=>l.period===periods[0]).map(l=>l.id);narrowed.importMapping.calendar.periods=[periods[0]];narrowed.importMapping.workbookSourcePolicy.outsideForecastScope=narrowed.importMapping.workbookSourcePolicy.outsideForecastScope.filter(r=>r.period===periods[0]);narrowed.importHistory=[];narrowed.overrides=narrowed.overrides.filter(r=>r.period===periods[0]);
 const narrowedSaved=await call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',narrowed]);assert.equal(narrowedSaved.snapshot.diagnostics.filter(d=>d.code==='workbook_source_policy_required'&&d.period===periods[1]).length,5);await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,narrowedSaved.head.scenario_id,narrowedSaved.head.revision,randomUUID(),'submit',narrowedSaved.revision.payload]),/blockers/i);
 const bad=structuredClone(ordinary.revision.payload);bad.overrides.find(o=>o.disposition==='workbook_blank').sourceLineId='Plan!C3';await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,scenario,ordinary.head.revision,randomUUID(),'save_draft',bad]),/blank|source/i);
 const invalidScope=structuredClone(scoped);invalidScope.workbookSourcePolicy.outsideForecastScope[0].accountCode='6100';await assert.rejects(()=>call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),upload.upload_id,invalidScope,payload]),/source row exists/i);
 assert.deepEqual((await call('atlas_read_reforecast_import_receipt',[A,request])).receipt,originalReceipt);
 assert.deepEqual((await db.query('select payload,snapshot from atlas_reforecast_revisions where revision_id=$1',[prior.revision_id])).rows[0],{payload:prior.payload,snapshot:prior.snapshot});
 const edit=structuredClone(ordinary.revision.payload),editedCells=[['5120',1100],['6100',25]];
 for(const [accountCode,amount]of editedCells){const before=ordinary.snapshot.lines.find(l=>l.period===periods[0]&&l.accountCode===accountCode).forecast;edit.overrides=edit.overrides.filter(o=>!(o.period===periods[0]&&o.accountCode===accountCode)).concat({period:periods[0],accountCode,amount,confirmed:true,reason:'Reviewed later working forecast adjustment',ownerId:owner,effectivePeriod:periods[0],reviewedAt,before,after:amount});}
 const edited=await call('atlas_save_reforecast_scenario',[A,scenario,ordinary.head.revision,randomUUID(),'save_draft',edit]);
 for(const [code,value]of editedCells){const row=edited.snapshot.lines.find(l=>l.period===periods[0]&&l.accountCode===code);assert.equal(row.forecast,value);assert.equal(row.disposition,'reviewer_override');assert.equal(row.workbookSourceAmount,code==='6100'?null:1001.005);}
 assert.equal(edited.snapshot.workbookCoverage.reviewerEditedCellCount,2);assert.deepEqual(edited.snapshot.workbookSourceTotals,ordinary.snapshot.workbookSourceTotals);
 const editedJs=computeReforecast({...edited.source,scenario:{...edited.revision.payload,versionId:edited.revision.revision_id,driverVersion:'fixture'}});assert.deepEqual(editedJs.knownValueTotals,edited.snapshot.knownValueTotals);assert.deepEqual(editedJs.workbookSourceTotals,edited.snapshot.workbookSourceTotals);
 const unreviewed=structuredClone(edit);unreviewed.overrides.find(o=>o.accountCode==='6100'&&o.period===periods[0]).confirmed=false;
 const pending=await call('atlas_save_reforecast_scenario',[A,scenario,edited.head.revision,randomUUID(),'save_draft',unreviewed]);assert.ok(pending.snapshot.completeness.blockerCount>0);await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,scenario,pending.head.revision,randomUUID(),'submit',unreviewed]),/review|blocking|completeness|validation/i);
 const drivenPayload=structuredClone(ordinary.revision.payload);drivenPayload.drivers=[{id:'accepted-rent-add',type:'reviewed',accountCodes:['5120'],periods,operation:'add',value:10,reason:'Accepted reviewed amount change'}];
 const driverScenario=randomUUID(),driverImported=await call('atlas_create_reforecast_from_import',[A,driverScenario,0,randomUUID(),upload.upload_id,scoped,payload]);
 const driven=await call('atlas_save_reforecast_scenario',[A,driverScenario,driverImported.head.revision,randomUUID(),'save_draft',{...driverImported.revision.payload,drivers:drivenPayload.drivers}]);assert.equal(driven.snapshot.lines.find(l=>l.period===periods[0]&&l.accountCode==='5120').forecast,1011.01);assert.deepEqual(driven.snapshot.workbookSourceTotals,ordinary.snapshot.workbookSourceTotals);
 const drivenJs=computeReforecast({...driven.source,scenario:{...driven.revision.payload,versionId:driven.revision.revision_id,driverVersion:'fixture'}});assert.deepEqual(drivenJs.knownValueTotals,driven.snapshot.knownValueTotals);
 // A newly scoped immutable upload replaces selected cells, while the prior
 // mapping remains a verified receipt reference rather than another large copy.
 const secondUpload=await call('atlas_save_reforecast_upload',[A,randomUUID(),{...evidence,integrity:{auditId:audit.audit_id,fingerprint:audit.fingerprint},propertyAssignment:assignment}]);
 const nextPayload=projectImportUpdatePayload(driven.revision.payload,{uploadId:secondUpload.upload_id,mapping:scoped,expectedLines:driverImported.receipt.importedCells});
 assert.equal(nextPayload.importMapping,undefined);assert.equal(nextPayload.importHistory[0].mappingReference.kind,'immutable_import_receipt');
 await assert.rejects(()=>call('atlas_create_reforecast_from_import',[A,driverScenario,driven.head.revision,randomUUID(),secondUpload.upload_id,scoped,nextPayload]),/readback differs/i);nextPayload.drivers=[];
 const transitioned=await call('atlas_create_reforecast_from_import',[A,driverScenario,driven.head.revision,randomUUID(),secondUpload.upload_id,scoped,nextPayload]);
 assert.equal(transitioned.snapshot.workbookCoverage.workbookBlankCellCount,4);assert.equal(transitioned.revision.payload.importHistory.length,2);
 const forgedHistory=structuredClone(transitioned.revision.payload);forgedHistory.importHistory.find(h=>h.mappingReference).mappingReference.requestId=randomUUID();await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,driverScenario,transitioned.head.revision,randomUUID(),'save_draft',forgedHistory]),/mapping reference/i);
 let publish=transitioned;
 for(const action of ['reconcile','ready','submit','vp_approve'])publish=await call('atlas_save_reforecast_scenario',[A,driverScenario,publish.head.revision,randomUUID(),action,publish.revision.payload]);
 const pub=publish.publication;assert.ok(pub.publication_id);
 const official=await call('atlas_read_reforecast_publication',[pub.publication_id]);assert.deepEqual(official.snapshot.workbookCoverage,publish.snapshot.workbookCoverage);assert.deepEqual(official.snapshot.workbookSourceTotals,publish.snapshot.workbookSourceTotals);
 const effective=await call('atlas_reforecast_effective_baseline',[[A],periods]);
 for(const month of effective)for(const row of month.lines.filter(l=>['6100','6200','8100'].includes(l.accountCode))){assert.equal(row.amount,null);assert.equal(row.disposition,row.accountCode==='8100'?'outside_forecast_scope':'workbook_blank');}
 const based={...payload,baselineType:'approved_reforecast',baselinePublicationIds:[pub.publication_id]},inheritedScenario=randomUUID();
 const inherited=await call('atlas_save_reforecast_scenario',[A,inheritedScenario,0,randomUUID(),'save_draft',based]);assert.equal(inherited.snapshot.lines.find(l=>l.accountCode==='8100').forecast,null);assert.equal(inherited.snapshot.lines.find(l=>l.accountCode==='8100').disposition,'outside_forecast_scope');assert.ok(!inherited.snapshot.diagnostics.some(d=>d.code==='open_value_missing'));
 const inheritedJs=computeReforecast({...inherited.source,scenario:{...inherited.revision.payload,versionId:inherited.revision.revision_id,driverVersion:'fixture'}});assert.deepEqual(inheritedJs.totals.reforecast,inherited.snapshot.totals.reforecast);assert.deepEqual(inheritedJs.categories,inherited.snapshot.categories.map(c=>({...c,monthly:c.monthly.map(m=>({...m,forecast:roundMoney(m.forecast)}))})));for(const category of ['Payroll','Noncash','Capital'])assert.ok(inherited.snapshot.categories.find(c=>c.category===category).monthly.every(m=>m.forecast===0));
 let inheritedPublication=inherited;for(const action of ['reconcile','ready','submit','vp_approve'])inheritedPublication=await call('atlas_save_reforecast_scenario',[A,inheritedScenario,inheritedPublication.head.revision,randomUUID(),action,inheritedPublication.revision.payload]);
 const inheritedReport=await call('atlas_read_reforecast_publication',[inheritedPublication.publication.publication_id]);assert.equal(inheritedReport.snapshot.workbookCoverage,undefined);for(const code of ['6100','6200','8100']){const expected=inherited.snapshot.lines.find(l=>l.accountCode===code),actual=inheritedReport.snapshot.lines.find(l=>l.accountCode===code);assert.equal(actual.disposition,expected.disposition);assert.equal(actual.legitimateBlank,expected.legitimateBlank);assert.equal(actual.forecast,null);}
 const future=await call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),secondUpload.upload_id,scoped,based]);
 assert.equal(future.snapshot.lines.find(l=>l.accountCode==='6100').selectedBaseline,null);assert.equal(future.snapshot.lines.find(l=>l.accountCode==='6100').originalBudget,200);assert.equal(future.snapshot.lines.find(l=>l.accountCode==='6100').forecast,null);
 // A numeric source GL outside the registry/baseline still requires explicit
 // per-cell exclusion; legacy generic reviewed_exclusion row annotations do not.
 const fullBook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(fullBook,XLSX.utils.aoa_to_sheet([['Scenario','Plan','Currency','Local'],['GL','Account','Feb 2026','Mar 2026'],...accounts.map((a,i)=>[a.accountCode,a.category,i===1?0:10,i===1?-1:20]),['5999','Unmapped source income',700,701]]),'Plan');
 const fullBytes=XLSX.write(fullBook,{type:'buffer',bookType:'xlsx'});let fullEvidence=await parseReforecastWorkbook(fullBytes,{xlsx:XLSX,fileName:'Numeric-source-coverage.xlsx',includeOriginalBytes:true});
 const fullMapping=structuredClone(legacyMapping);fullMapping.selectedLineIds=fullEvidence.lines.filter(l=>l.accountCode!=='5999').map(l=>l.id);fullMapping.sourceRowExclusions=fullEvidence.lines.filter(l=>l.accountCode==='5999').map(l=>({sourceLineId:l.id,confirmed:true,reviewedBy:owner,reviewedAt,reason:'Explicit reviewed source-only control outside this forecast'}));
 fullEvidence=(await prepareScopedReforecastEvidence(fullEvidence,fullMapping,{xlsx:XLSX,sourceBytes:fullBytes})).evidence;
 const fullAudit=await call('atlas_save_workbook_audit',[A,fullEvidence.source.sha256,fullEvidence.integrity,randomUUID()]);fullMapping.inputReviews=fullEvidence.lines.filter(l=>fullMapping.selectedLineIds.includes(l.id)).map(l=>({cellId:l.id,confirmed:true,ownerId:owner,effectivePeriod:l.period,before:l.amount,after:l.amount,reason:'Reviewed numeric source input',reviewedAt,integrityFingerprint:fullAudit.fingerprint}));Object.assign(fullMapping,planningMappingDispositions(fullEvidence,fullMapping));
 const fullUpload=await call('atlas_save_reforecast_upload',[A,randomUUID(),{...fullEvidence,integrity:{auditId:fullAudit.audit_id,fingerprint:fullAudit.fingerprint},propertyAssignment:assignment}]);
 const missingReview=structuredClone(fullMapping);delete missingReview.sourceRowExclusions;
 const spoofedEvidence=structuredClone(fullEvidence);for(const line of spoofedEvidence.lines.filter(l=>l.accountCode==='5999'))line.sourceKind='workbook_actual_evidence';
 const spoofedUpload=await call('atlas_save_reforecast_upload',[A,randomUUID(),{...spoofedEvidence,integrity:{auditId:fullAudit.audit_id,fingerprint:fullAudit.fingerprint},propertyAssignment:assignment}]);
 const spoofed=await call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),spoofedUpload.upload_id,missingReview,payload]);assert.equal(spoofed.snapshot.diagnostics.filter(d=>d.code==='numeric_source_exclusion_review_required').length,2);
 const incomplete=await call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),fullUpload.upload_id,missingReview,payload]);assert.equal(incomplete.snapshot.diagnostics.filter(d=>d.code==='numeric_source_exclusion_review_required').length,2);assert.equal(incomplete.snapshot.status,'action_required');assert.ok(!incomplete.snapshot.lines.some(l=>l.accountCode==='5999'));
 const exactMissingReview={...missingReview,workbookSourcePolicy:policy};const exactIncomplete=await call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),fullUpload.upload_id,exactMissingReview,payload]);assert.equal(exactIncomplete.snapshot.workbookCoverage.complete,false);assert.equal(exactIncomplete.snapshot.workbookCoverage.unreviewedSourceCellCount,2);assert.ok(exactIncomplete.snapshot.workbookCoverage.monthly.every(m=>m.complete===false&&m.unreviewedSourceCellCount===1));const exactIncompleteJs=computeReforecast({...exactIncomplete.source,scenario:{...exactIncomplete.revision.payload,versionId:exactIncomplete.revision.revision_id,driverVersion:'fixture'}});assert.deepEqual(exactIncompleteJs.workbookCoverage,exactIncomplete.snapshot.workbookCoverage);
 const fullyNumeric=await call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),fullUpload.upload_id,fullMapping,payload]);assert.equal(fullyNumeric.snapshot.completeness.blockerCount,0,JSON.stringify(fullyNumeric.snapshot.diagnostics));assert.equal(fullyNumeric.snapshot.workbookCoverage,undefined);assert.equal(fullyNumeric.snapshot.workbookSourceExclusions.length,2);assert.deepEqual(fullyNumeric.snapshot.workbookSourceExclusions.map(r=>r.sourceAmount),[700,701]);
 assert.deepEqual(fullyNumeric.source.workbookRelationshipProofs,{},'no proof is stamped for a resolver early return');
 const fullJs=computeReforecast({...fullyNumeric.source,scenario:{...fullyNumeric.revision.payload,versionId:fullyNumeric.revision.revision_id,driverVersion:'fixture'}});assert.deepEqual(fullJs.workbookSourceExclusions,fullyNumeric.snapshot.workbookSourceExclusions);assert.equal(fullJs.status,'ready');
 await db.exec('reset role');const closedCoverage=(await db.query('select atlas_private.reforecast_workbook_source_coverage($1::jsonb,$2::jsonb) coverage',[{...fullyNumeric.source,actuals:{...fullyNumeric.source.actuals,cutoffPeriod:periods[0]}},fullyNumeric.revision.payload])).rows[0].coverage;assert.equal(closedCoverage.issues.length,0);assert.equal(closedCoverage.exclusions.length,2);await signIn(1);
 // Canonical remaps control absence: raw source GL5120 mapped to5199 does
 // not falsely prevent an explicit exclusion of the old canonical5120.
 const remapped=structuredClone(fullMapping);remapped.accountMappings.find(m=>m.sourceAccountCode==='5120').accountCode='5199';remapped.workbookSourcePolicy={...policy,outsideForecastScope:periods.map(period=>({period,accountCode:'5120',confirmed:true,reviewedBy:owner,reviewedAt,reason:'Reviewed raw source now maps to the replacement canonical GL'}))};const remappedSource=structuredClone(fullyNumeric.source);remappedSource.registry.accounts.push({...remappedSource.registry.accounts.find(a=>a.accountCode==='5120'),accountCode:'5199'});const remappedConfig={...fullyNumeric.revision.payload,importMapping:remapped};await db.exec('reset role');const remappedScope=(await db.query('select atlas_private.resolve_reforecast_workbook_scope($1::jsonb,$2::jsonb) cells',[remappedSource,remappedConfig])).rows[0].cells;assert.equal(remappedScope.length,2);assert.ok(remappedScope.every(c=>c.accountCode==='5120'));remapped.accountMappings.push({...remapped.accountMappings.find(m=>m.sourceAccountCode==='5120'),accountCode:'5198'});await assert.rejects(()=>db.query('select atlas_private.resolve_reforecast_workbook_scope($1::jsonb,$2::jsonb)',[remappedSource,remappedConfig]),/ambiguous canonical/i);await signIn(1);
 // Preserve legacy numeric relationship validation, including hostile shapes.
 await db.exec('reset role');const unprojected=relationshipOriginalDefinition.replace('FUNCTION atlas_private.validate_reforecast_source_relationships(', 'FUNCTION atlas_private.test_workbook_relationships_unprojected(');await db.exec(unprojected);
 const relationshipResult=async(name,e,a)=>{try{await db.query(`select atlas_private.${name}($1::jsonb,$2::jsonb,$3::jsonb)`,[e,a,fullMapping]);return 'valid';}catch(error){return error.message;}};
 const checkProjection=async(e,a,valid=false)=>{const expected=await relationshipResult('test_workbook_relationships_unprojected',e,a),actual=await relationshipResult('validate_reforecast_source_relationships',e,a);assert.equal(actual,expected);if(valid)assert.equal(actual,'valid');else assert.notEqual(actual,'valid');};
 await checkProjection(fullEvidence,fullEvidence.integrity,true);
 for(const key of ['accountCode','period','scenario','amount'])for(const mode of ['absent','null','altered']){const changed=structuredClone(fullEvidence),row=changed.lines.find(l=>l.accountCode==='5999');if(mode==='absent')delete row[key];else row[key]=mode==='null'?null:key==='amount'?999:'altered';await checkProjection(changed,fullEvidence.integrity);}
 for(const key of ['row','column'])for(const mode of ['absent','null']){const changed=structuredClone(fullEvidence.integrity),cell=changed.inventory.sheets[0].cells.find(c=>c.address==='C3');if(mode==='absent')delete cell[key];else cell[key]=null;await checkProjection(fullEvidence,changed);}
 const serialAudit=structuredClone(fullEvidence.integrity),serialHeader=serialAudit.inventory.sheets[0].cells.find(c=>c.address==='C2');serialHeader.value=(Date.UTC(2026,1,1)-Date.UTC(1899,11,30))/86400000;serialHeader.numberFormat='yyyy-mm-dd';serialAudit.inventory.dateSystem='1900';await checkProjection(fullEvidence,serialAudit,true);delete serialHeader.numberFormat;await checkProjection(fullEvidence,serialAudit);await signIn(1);
 const partialMapping=structuredClone(fullMapping);partialMapping.workbookSourcePolicy=structuredClone(policy);partialMapping.periods=[periods[0]];partialMapping.calendar.periods=[periods[0]];partialMapping.selectedLineIds=fullEvidence.lines.filter(l=>l.accountCode!=='5999'&&l.period===periods[0]).map(l=>l.id);partialMapping.sourceRowExclusions=partialMapping.sourceRowExclusions.filter(r=>fullEvidence.lines.find(l=>l.id===r.sourceLineId).period===periods[0]);
 const partialUpload=await call('atlas_save_reforecast_upload',[A,randomUUID(),{...fullEvidence,integrity:{auditId:fullAudit.audit_id,fingerprint:fullAudit.fingerprint},propertyAssignment:assignment}]);
 const partialPayload=projectImportUpdatePayload(fullyNumeric.revision.payload,{uploadId:partialUpload.upload_id,mapping:partialMapping,expectedLines:fullyNumeric.receipt.importedCells.filter(c=>c.period===periods[0])});
 const partial=await call('atlas_create_reforecast_from_import',[A,fullyNumeric.head.scenario_id,fullyNumeric.head.revision,randomUUID(),partialUpload.upload_id,partialMapping,partialPayload]);assert.equal(partial.snapshot.completeness.blockerCount,0,JSON.stringify(partial.snapshot.diagnostics));for(const line of partial.snapshot.lines.filter(l=>l.period===periods[1]))assert.equal(line.forecast,fullyNumeric.snapshot.lines.find(old=>old.period===line.period&&old.accountCode===line.accountCode).forecast);
 const forgedOwner=structuredClone(partial.revision.payload);forgedOwner.importMapping.reviewedBy='00000000-0000-0000-0000-000000000005';forgedOwner.importMapping.sourceRowExclusions[0].reason='Different review impersonating another authorized reviewer';await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,partial.head.scenario_id,partial.head.revision,randomUUID(),'save_draft',forgedOwner]),/signed-in authorized reviewer/i);
 const duplicateReview=structuredClone(fullMapping);duplicateReview.sourceRowExclusions.push({...duplicateReview.sourceRowExclusions[0]});const duplicate=await call('atlas_create_reforecast_from_import',[A,randomUUID(),0,randomUUID(),fullUpload.upload_id,duplicateReview,payload]);assert.ok(duplicate.snapshot.diagnostics.some(d=>d.code==='numeric_source_exclusion_review_required'));
 await signIn(4);await assert.rejects(()=>call('atlas_read_reforecast_import_receipt',[A,request]),/access denied/i);
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from atlas_reforecast_publications')).rows[0].n,2);
 await db.close();console.log(JSON.stringify({status:'PASS',selectedCells:8,numericCells:4,explicitBlanks:4,outsideScope:2,checks:'immutable audit blank proof; exact source/header/mapping; subtotal_control rows; compact null persistence; source-absent blocking; explicit scope exclusion; JS/SQL parity; same-upload update and ordinary re-save; forged reference and existing-source exclusion rejection; historical receipt/revision unchanged; reviewed manual/driver changes; new-upload reference recovery; local VP publication/effective baseline and future blank inheritance; authorization; no production writes'}));
})().catch(error=>{console.error(error.message,error.where||error.stack);process.exitCode=1});
