import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {parseReforecastWorkbook} from '../docs/portfolio-operations-dashboard/features/reforecast-intake.mjs';
import {compareWorkbookEvidence,canonicalWorkbookEvidence} from '../docs/portfolio-operations-dashboard/features/workbook-integrity.mjs';
import {prepareScopedReforecastEvidence,reforecastAuthoritySelectionKey} from '../docs/portfolio-operations-dashboard/features/reforecast-authority.mjs';
const require=createRequire(import.meta.url),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
const workbook=XLSX.utils.book_new(),sheet={'!ref':'A1:H40'},put=(address,value,formula)=>{sheet[address]={t:typeof value==='number'?'n':'s',v:value,...formula?{f:formula}:{}};};
put('B19','Entity');put('D19','Source community');put('B20','Department');put('D20','Operations');put('B21','Currency');put('D21','USD');
for(const [col,month,scenario]of [['E',8,'Actual'],['F',9,'Plan'],['G',10,'Plan'],['H',11,'Plan']]){put(col+'14',2026);put(col+'15',month);put(col+'16',scenario);put(col+'17','Value');}
put('B36','5120 (Rent)');put('E36',100);put('F36',0);put('G36',7,"Supporting!A1");
XLSX.utils.book_append_sheet(workbook,sheet,'Input');
const support=XLSX.utils.aoa_to_sheet([[7]]);support.A1.f='INDIRECT("B1")';XLSX.utils.book_append_sheet(workbook,support,'Supporting');
const encode=w=>XLSX.write(w,{type:'array',bookType:'xlsx'}),bytes=encode(workbook),evidence=await parseReforecastWorkbook(bytes,{xlsx:XLSX,includeOriginalBytes:true});
const mapping={sourceScenario:'Plan',periods:['2026-09'],selectedLineIds:['Input!F36']};
const before=canonicalWorkbookEvidence(evidence),scoped=await prepareScopedReforecastEvidence(evidence,mapping,{xlsx:XLSX});
assert.equal(canonicalWorkbookEvidence(evidence),before,'Authority review must not mutate retained source evidence');
assert.equal(scoped.evidence.integrity.summary.blocking,0);
assert(scoped.evidence.integrity.findings.some(f=>f.code==='dynamic_dependency'&&f.severity==='review'&&f.scope==='supporting'));
assert.equal(scoped.evidence.integrity.safeToApprove,false,'Supporting reviews are not waived');
assert.deepEqual(scoped.evidence.source.originalFile,evidence.source.originalFile);
assert.deepEqual(scoped.evidence.sheets,evidence.sheets,'All original cells and worksheets remain present');
for(const id of ['Input!F36','Input!B36','Input!F14','Input!F15','Input!F16','Input!D19','Input!D20','Input!D21'])assert(scoped.authoritativeCells.includes(id),id);
assert.equal(scoped.evidence.lines.find(l=>l.id==='Input!F36').amount,0);
assert.equal(scoped.evidence.lines.find(l=>l.id==='Input!H36').amount,null);
const formulaMapping={sourceScenario:'Plan',periods:['2026-10'],selectedLineIds:['Input!G36']},blocked=await prepareScopedReforecastEvidence(evidence,formulaMapping,{xlsx:XLSX});
assert(blocked.evidence.integrity.findings.some(f=>f.code==='dynamic_dependency'&&f.severity==='blocking'&&f.scope==='authoritative'),'Cross-sheet dependencies cannot be waived');
assert.notEqual(scoped.selectionKey,reforecastAuthoritySelectionKey(evidence,formulaMapping));
for(const changed of [{periods:['2026-10']},{sourceScenario:'Actual'},{selectedLineIds:['Input!H36']},{selectedLineIds:['Input!F36','Input!F36']}])await assert.rejects(prepareScopedReforecastEvidence(evidence,{...mapping,...changed},{xlsx:XLSX}));
const modified=structuredClone(evidence);modified.lines.find(l=>l.id==='Input!F36').accountCode='9999';await assert.rejects(prepareScopedReforecastEvidence(modified,mapping,{xlsx:XLSX}),/original workbook relationship/);
await assert.rejects(prepareScopedReforecastEvidence(evidence,mapping,{xlsx:XLSX,sourceBytes:new Uint8Array([1,2,3])}),/source hash/);
const priorBook=structuredClone(workbook);priorBook.Sheets.Input.F36={t:'n',v:0,f:'SUM(0,0)'};
const prior=await parseReforecastWorkbook(encode(priorBook),{xlsx:XLSX}),compared={...evidence,integrity:compareWorkbookEvidence(evidence.integrity,prior.integrity)};
await assert.rejects(prepareScopedReforecastEvidence(compared,mapping,{xlsx:XLSX}),/earlier workbook audit/);
const comparison=await prepareScopedReforecastEvidence(compared,mapping,{xlsx:XLSX,previousEvidence:prior.integrity});
assert(comparison.evidence.integrity.findings.some(f=>f.code==='formula_to_hardcode'&&f.severity==='blocking'));
assert.equal(comparison.evidence.integrity.previousFingerprint,prior.integrity.fingerprint);
if(process.env.ATLAS_DORO_WORKBOOK){
 const bytes=fs.readFileSync(process.env.ATLAS_DORO_WORKBOOK),actual=await parseReforecastWorkbook(bytes,{xlsx:XLSX,fileName:path.basename(process.env.ATLAS_DORO_WORKBOOK),includeOriginalBytes:true});
 const periods=['2026-09','2026-10','2026-11','2026-12'],selectedLineIds=actual.lines.filter(l=>l.scenario==='Plan'&&periods.includes(l.period)&&Number.isFinite(l.amount)).map(l=>l.id);
 const result=await prepareScopedReforecastEvidence(actual,{sourceScenario:'Plan',periods,selectedLineIds},{xlsx:XLSX});
 assert.equal(result.selectedLineIds.length,455);assert.equal(result.evidence.integrity.summary.blocking,0);assert.equal(result.evidence.integrity.summary.review,48);
 assert.deepEqual(result.evidence.sheets,actual.sheets);assert.deepEqual(result.evidence.lines,actual.lines);assert.deepEqual(result.evidence.source.originalFile,actual.source.originalFile);
 assert(result.evidence.integrity.findings.some(f=>f.code==='embedded_image_evidence'&&f.sheet==='Input'&&f.address==='G29'&&f.scope==='supporting'));
 assert.equal(result.evidence.lines.filter(l=>selectedLineIds.includes(l.id)&&l.amount===0).length,97);
 assert.equal(result.evidence.integrity.summary.formulas,3879);assert.equal(result.evidence.integrity.summary.populatedCells,21397);
 console.log(JSON.stringify({actualWorkbookScope:'passed',selectedCells:result.selectedLineIds.length,roots:result.authoritativeCells.length,requiredNodes:result.evidence.integrity.authorityScope.requiredNodes.length,blockers:result.evidence.integrity.summary.blocking,reviewFindings:result.evidence.integrity.summary.review,sourceHash:result.sourceHash,integrityFingerprint:result.evidence.integrity.fingerprint}));
}
console.log('PASS complete source scope, zero versus blank, source/header/metadata relationships, cross-sheet blockers, non-waivable prior comparison, immutable original and explicit supporting review requirements.');
