import assert from 'node:assert/strict';
import {reforecastSourceChanged,reforecastCurrentSnapshot,reforecastScopePeriods,reforecastPublicationState,reforecastReportPeriods,reforecastMonthEvidence,readReforecastApprovalEvidence,cacheReforecastSource,readReforecastRevisionHistory,reforecastDraftFromLegacy,reforecastReportOptions,mountReforecast,clearReforecastSession} from '../docs/portfolio-operations-dashboard/features/reforecast-ui.mjs';
import {exportRows,analyticalExportRows} from '../docs/portfolio-operations-dashboard/features/reforecast-report.mjs';
const A='10000000-0000-0000-0000-000000000001',B='10000000-0000-0000-0000-000000000002',scenarioId='20000000-0000-0000-0000-000000000001',revisionId='30000000-0000-0000-0000-000000000001';
const periods=['2026-01','2026-02','2026-03','2026-04'];
const source={communityId:A,periods,sourceVersion:'source-v1',baseline:{versionIds:['original-budget'],lines:[{period:'2026-04',accountCode:'5120',amount:100}]},registry:{version:'registry-v1',accounts:[]},actuals:{cutoffPeriod:'2026-03',notApplicablePeriods:['2026-01'],closeVersions:[{period:'2026-03',versionId:'close-3'}]}};
const entry={head:{community_id:A,scenario_id:scenarioId,revision_id:revisionId,revision:7,status:'locked'},revision:{revision_id:revisionId,payload:{name:'Locked reforecast',periods},created_at:'2026-09-23'},snapshot:{diagnostics:[]},source};
const publication={communityId:A,scenarioId,revisionId,publicationId:'publication',periods:['2026-03','2026-04'],activePeriods:['2026-04']};
assert.equal(reforecastPublicationState(entry,[]).label,'Locked');
assert.equal(reforecastPublicationState(entry,[publication]).label,'Published / Active');
assert.deepEqual(reforecastPublicationState(entry,[publication]).activePeriods,['2026-04']);
assert.equal(reforecastPublicationState(entry,[{...publication,revisionId:'other-revision'}]).label,'Locked','publishing an older revision does not publish the selected revision');
assert.equal(reforecastPublicationState(entry,[{...publication,communityId:B}]).label,'Locked');
assert.equal(reforecastPublicationState(entry,[{...publication,activePeriods:[]}]).label,'Published / Superseded');
const evidence=period=>reforecastMonthEvidence({communityId:A,period,source,entries:[entry],publications:[publication]});
assert.equal(evidence('2026-01').status,'Not applicable');assert.equal(evidence('2026-03').status,'Closed');assert.equal(evidence('2026-04').status,'Published / Active');
assert.equal(reforecastMonthEvidence({communityId:A,period:'2026-03',source:{...source,actuals:{cutoffPeriod:null}},publications:[publication]}).status,'Blocked','publication periods alone do not prove a month remains active');
assert.equal(reforecastMonthEvidence({communityId:A,period:'2026-02',source}).status,'Blocked');
assert.match(reforecastMonthEvidence({communityId:A,period:'2026-02',source}).explanation,/No governed close/);
for(const state of ['working_draft','ready_for_review','submitted','approved','locked']){const record={...entry,head:{...entry.head,status:state}};assert.equal(reforecastMonthEvidence({communityId:A,period:'2026-04',source,entries:[record]}).status,state.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()));}
assert.equal(reforecastMonthEvidence({communityId:A,period:'2026-04',source,entries:[{...entry,snapshot:{diagnostics:[{severity:'error',period:'2026-04',message:'Missing mapping'}]}}]}).status,'Blocked · Locked');
assert.equal(reforecastMonthEvidence({communityId:A,period:'2026-04',source,uploads:[{community_id:A,periods:['2026-04']}]}).status,'Uploaded · Mapping Required');
assert.equal(reforecastMonthEvidence({communityId:A,period:'2026-04',sourceError:'access failed'}).status,'Unavailable');
const snapshot={identity:{periods},lines:periods.map((period,i)=>({period,accountCode:'5120',originalBudget:100,forecast:i===2?0:110,actual:null,nature:'income',placement:'above_noi',category:'Rent'})),monthly:periods.map(period=>({period,originalBudget:{revenue:100,noi:100},reforecast:{revenue:110,noi:110},actuals:{}}))};
assert.deepEqual(reforecastReportPeriods(snapshot,'2026-02','2026-03'),['2026-02','2026-03']);assert.throws(()=>reforecastReportPeriods(snapshot,'2026-04','2026-01'),/start month/);assert.throws(()=>reforecastReportPeriods(snapshot,'2027-01','2027-12'),/No months/);
const reportOptions=reforecastReportOptions({record:entry,active:[publication],edit:{name:'Report'},source,reportFrom:'2026-02',reportTo:'2026-03',grain:'month',metric:'noi'},null,snapshot);
assert.equal(reportOptions.status,'Published / Active');const rows=exportRows(snapshot,source,reportOptions);assert.equal(rows.length,2);assert.ok(rows.every(row=>['2026-02','2026-03'].includes(row.Period||row.period)));const analytical=analyticalExportRows(snapshot,source,reportOptions);assert.ok(Object.keys(analytical).length>0);
const R={app:{state:{properties:[{id:'direct',communityId:A},{id:'looks-like-a',name:'A'},{id:'explicit'}]}},reforecastPropertyAssignments:{explicit:A}};cacheReforecastSource(R,source,2026);assert.equal(R.reforecastSources[A+'|2026'],source);assert.equal(R.reforecastSources['direct|2026'],source);assert.equal(R.reforecastSources['explicit|2026'],source);assert.equal(R.reforecastSources['looks-like-a|2026'],undefined,'no name-based property authority');
const legacyInput={communityId:A,scenario:{drivers:[{id:'growth',value:0.05,periods:['2026-03','2026-04']}],overrides:[{period:'2026-03',accountCode:'5120',amount:999},{period:'2026-04',accountCode:'5120',amount:0,sourceLineId:'legacy'}]}};
const before=JSON.stringify({legacyInput,source}),draft=reforecastDraftFromLegacy({input:legacyInput,scenario:{id:'upside',name:'Upside',locked:true,status:'approved'},source,actor:'reviewer',propertyId:'browser-property',reason:'Copy reviewed assumptions',timestamp:'2026-09-23T10:00:00Z'});
assert.deepEqual(draft.drivers[0].periods,['2026-04']);assert.equal(draft.overrides[0].amount,0);assert.equal(draft.overrides[0].sourceLineId,undefined);assert.equal(draft.locked,undefined);assert.equal(draft.status,undefined);assert.equal(draft.reviewerId,null);assert.deepEqual(draft.baselineVersionIds,['original-budget']);assert.equal(draft.history[0].sourceScenarioId,'upside');assert.equal(JSON.stringify({legacyInput,source}),before);assert.throws(()=>reforecastDraftFromLegacy({input:{...legacyInput,communityId:B},source,actor:'reviewer',reason:'x'}),/canonical property/);
assert.deepEqual(reforecastScopePeriods('2026-07','2026-12'),['2026-07','2026-08','2026-09','2026-10','2026-11','2026-12']);assert.deepEqual(reforecastScopePeriods('2026-12','2027-01'),['2026-12','2027-01']);assert.throws(()=>reforecastScopePeriods('2026-12','2026-07'),/first reporting/);assert.throws(()=>reforecastScopePeriods('2026-01','2028-01'),/24/);
const freshSource={communityId:A,periods:['2026-04'],sourceVersion:'new-close',baseline:{versionIds:['budget'],lines:[{period:'2026-04',accountCode:'5120',amount:100}]},registry:{version:'mapping',accounts:[{accountCode:'5120',name:'Rent',nature:'income',category:'Rent',placement:'above_noi'}]},actuals:{cutoffPeriod:'2026-04',closeVersions:[{period:'2026-04',versionId:'close-apr'}],lines:[{period:'2026-04',accountCode:'5120',amount:90}]}},oldSnapshot={fingerprint:'retained-old-snapshot',identity:{sourceVersion:'before-close'}},unchangedInputs={periods:['2026-04'],drivers:[],overrides:[{period:'2026-04',accountCode:'5120',amount:200}]};
const mutable={record:{head:{status:'working_draft'},revision:{source:{sourceVersion:'before-close'}},snapshot:oldSnapshot},edit:structuredClone(unchangedInputs),source:freshSource,dirty:false};assert.equal(reforecastSourceChanged(mutable),true);const recalculated=reforecastCurrentSnapshot(mutable);assert.notEqual(recalculated,oldSnapshot);assert.equal(recalculated.lines[0].forecast,90);assert.equal(recalculated.lines[0].sourceKind,'closed_actual');assert.deepEqual(mutable.edit,unchangedInputs,'new closes do not rewrite saved input evidence');assert.equal(mutable.record.snapshot,oldSnapshot,'the previous immutable snapshot stays retained');const frozen={...mutable,record:{...mutable.record,head:{status:'locked'}},dirty:true,preview:null};assert.equal(reforecastCurrentSnapshot(frozen),oldSnapshot,'approved and locked vintages stay frozen even when source evidence changes');
let actor='reviewer',requests=[];const central={getSession:()=>({user:{id:actor}}),readCommunitiesForAccess:async()=>[{community_id:A,display_name:'A'},{community_id:B,display_name:'B'}],readUserProfiles:async()=>[],async fetchJson(url,options){requests.push({url,options});const args=options?.body?JSON.parse(options.body):{};
 if(url==='/rpc/atlas_read_reforecast_workspace'){assert.deepEqual(args.p_community_ids,[A,B]);return[entry];}
 if(url==='/rpc/atlas_read_active_reforecast')return[publication];
 if(url==='/rpc/atlas_read_reforecast_source'){if(args.p_community_id===B)throw Error('B canonical source unavailable');return {...source,periods:args.p_periods};}
 if(url.startsWith('/atlas_reforecast_uploads'))return[{community_id:A,upload_id:'upload',periods:['2026-04']}];
 if(url.startsWith('/atlas_reforecast_revisions'))return[{scenario_id:scenarioId,community_id:A,revision_id:revisionId,revision:1}];
 throw Error('Unexpected request '+url);
}};
const result=await readReforecastApprovalEvidence(central,{communityIds:[A,B],year:2026});assert.equal(result.entries.length,1);assert.equal(result.active.length,1);assert.equal(result.sources[A].communityId,A);assert.match(result.sourceErrors[B],/unavailable/);assert.equal(result.uploads.length,1);assert.ok(requests.find(row=>row.url.includes('select=upload_id,community_id,created_at,periods:payload->summary->periods')));
const history=await readReforecastRevisionHistory(central,{scenarioId,communityId:A});assert.equal(history.length,1);await assert.rejects(()=>readReforecastRevisionHistory(central,{scenarioId,communityId:B}),/scope mismatch/);
clearReforecastSession();const state=await mountReforecast({isConnected:false},{R:{app:{year:()=>2026,state:{properties:[]}}},central,hostWindow:{},mode:'approvals'});assert.equal(state.cid,'');assert.equal(state.approvalEvidence.entries.length,1,'all-property approval data must load on first mount without selecting a property');state.edit={name:'Unsaved personal draft'};state.dirty=true;await mountReforecast({isConnected:false},{R:state.R,central,hostWindow:{},mode:'approvals'});assert.equal(state.edit.name,'Unsaved personal draft');assert.equal(state.dirty,true,'approval reads must preserve working editor state');clearReforecastSession();
const changed={...central,async fetchJson(url,options){const value=await central.fetchJson(url,options);if(url.startsWith('/atlas_reforecast_uploads'))actor='another-user';return value;}};await assert.rejects(()=>readReforecastApprovalEvidence(changed,{communityIds:[A,B],year:2026}),/account changed/);
console.log('PASS reforecast UI governance: initial all-property reads, isolated working draft, exact active revision/month status, honest missing evidence, report/export range parity, immutable scoped history, explicit scenario copy and canonical cache assignment.');

const {updateReforecastCell}=await import('../docs/portfolio-operations-dashboard/features/reforecast-ui.mjs');const typing={actor:'test',edit:{periods:['2026-04'],overrides:[],reason:'Intentional zero'},record:null,source:{actuals:{cutoffPeriod:'2026-03'}},dirty:false};updateReforecastCell(typing,'2026-04','6200','0');assert.equal(typing.edit.overrides[0].amount,0);assert.equal(typing.dirty,true);updateReforecastCell(typing,'2026-04','6200','');assert.equal(typing.edit.overrides[0].amount,null);assert.equal(typing.edit.history[1].before[0].amount,0);assert.throws(()=>updateReforecastCell({...typing,source:{actuals:{cutoffPeriod:'2026-04'}}},'2026-04','6200','1'),/cannot be edited/);console.log('PASS GL input immediately enters draft before blur; intentional zero, blank and actual locks remain distinct');
