const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{const {db,A,B,BUDGET,signIn}=await fixture();const owner='00000000-0000-0000-0000-000000000001';await db.exec('reset role');
await db.exec(`create table atlas_bonus_periods(bonus_period_id uuid primary key,period_key text,year int,quarter text,start_date date,end_date date,status text);
create table atlas_bonus_calculation_runs(bonus_calculation_run_id uuid primary key,bonus_period_id uuid,community_id uuid,status text,calculation_hash text,inputs jsonb,exceptions jsonb,calculated_at timestamptz default now(),approved_by uuid,approved_at timestamptz,total_payout numeric,deleted_at timestamptz);
create table atlas_bonus_calculation_lines(bonus_line_id uuid primary key default gen_random_uuid(),bonus_calculation_run_id uuid,employee_id uuid,assignment_id uuid,incentive_plan_id uuid,metric_key text,metric_source_table text,metric_source_id uuid,payout_amount numeric,line_payload jsonb,deleted_at timestamptz);
create table atlas_employee_assignments(assignment_id uuid primary key,employee_id uuid,community_id uuid,deleted_at timestamptz,role_id uuid,version int,effective_start date,effective_end date,employment_status text);
create table atlas_employees(employee_id uuid primary key,status text,bonus_eligible boolean,bonus_effective_date date,deleted_at timestamptz);
create table atlas_incentive_plans(incentive_plan_id uuid primary key,role_id uuid,version int,effective_start date,effective_end date,eligibility_rules jsonb,metric_rules jsonb,deleted_at timestamptz);`);
await db.exec(fs.readFileSync(path.join(__dirname,'../docs/portfolio-operations-dashboard/centralization/reforecast-builder.sql'),'utf8'));
const periodId=randomUUID(),paidPeriodId=randomUUID(),employee=randomUUID(),assignment=randomUUID(),plan=randomUUID(),role=randomUUID(),staleRun=randomUUID(),unrelatedRun=randomUUID(),paidRun=randomUUID();
await db.query("insert into atlas_bonus_periods values($1,'2026-Q3',2026,'Q3','2026-07-01','2026-09-30','open'),($2,'2026-Q2',2026,'Q2','2026-04-01','2026-06-30','open')",[periodId,paidPeriodId]);
await db.query('insert into atlas_employee_assignments(assignment_id,employee_id,community_id,deleted_at) values($1,$2,$3,null)',[assignment,employee,A]);const unrelatedAssignment=randomUUID(),unrelatedEmployee=randomUUID();await db.query('insert into atlas_employee_assignments(assignment_id,employee_id,community_id,deleted_at) values($1,$2,$3,null)',[unrelatedAssignment,unrelatedEmployee,B]);
const metricDefinition={id:'revenue',metricKey:'revenue',goal:100,weight:100};const eligibilityRules={requireBonusEligible:true,communityIds:[A],roleIds:[role],employmentStatuses:['Active']};
await db.query("insert into atlas_employees values($1,'Active',true,'2026-01-01',null)",[employee]);await db.query("update atlas_employee_assignments set role_id=$1,version=1,effective_start='2026-01-01',effective_end='2026-12-31',employment_status='Active' where assignment_id=$2",[role,assignment]);await db.query("insert into atlas_incentive_plans values($1,$2,1,'2026-01-01','2026-12-31',$3,$4,null)",[plan,role,JSON.stringify(eligibilityRules),JSON.stringify([metricDefinition])]);
const insertRun=async(id,pid,status,payload,ass=assignment,emp=employee)=>{await db.exec('begin');await db.query("insert into atlas_bonus_calculation_runs(bonus_calculation_run_id,bonus_period_id,status,calculation_hash,inputs,exceptions,total_payout,approved_by,approved_at) values($1,$2,$3,encode(sha256(convert_to($4::jsonb::text,'UTF8')),'hex'),$4,'[]',123,$5,now())",[id,pid,status,JSON.stringify(payload),owner]);for(const line of payload.lines||[])await db.query("insert into atlas_bonus_calculation_lines(bonus_calculation_run_id,employee_id,assignment_id,incentive_plan_id,metric_key,payout_amount,line_payload) values($1,$2,$3,$4,'total',123,$5)",[id,emp,ass,plan,JSON.stringify(line)]);await db.exec('commit');};
const bareLine=(emp=employee,ass=assignment)=>({employee_id:emp,assignment_id:ass,incentive_plan_id:plan,metric_key:'total',payout_amount:123});
await insertRun(staleRun,periodId,'approved',{lines:[bareLine()]});await insertRun(unrelatedRun,periodId,'approved',{lines:[bareLine(unrelatedEmployee,unrelatedAssignment)]},unrelatedAssignment,unrelatedEmployee);await insertRun(paidRun,paidPeriodId,'locked',{lines:[bareLine()]});
assert.equal((await db.query("select atlas_private.reforecast_month_locked($1,'2026-04') value",[A])).rows[0].value,true,'null-community locked run inherits assignment scope');assert.equal((await db.query("select atlas_private.reforecast_month_locked($1,'2026-04') value",[B])).rows[0].value,false);
await signIn(1);const call=async(name,args)=>(await db.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
const accounts=[['5120','income'],['5220','contra_income'],['6100','expense'],['6200','expense'],['8100','capital']].map(([accountCode,nature])=>({accountCode,nature,category:accountCode,placement:nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'}));const reg=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),JSON.stringify({accounts,driverMappings:{},reason:'Reviewed synthetic registry',effectiveDate:'2026-01-01'})]);
const bytes=Buffer.from('%PDF synthetic source');const upload=await call('atlas_save_reforecast_upload',[A,randomUUID(),JSON.stringify({sourceType:'hello_landing',propertyAssignment:{communityId:A,confirmed:true},source:{fileName:'synthetic.pdf',sha256:createHash('sha256').update(bytes).digest('hex'),originalFile:{encoding:'base64',data:bytes.toString('base64')}},statement:{period:'2026-06',periodBasis:'calendar_month',status:'reconciled',summary:{netAllocation:100},metrics:{},checks:[],issues:[]}})]);await call('atlas_review_reforecast_source',[upload.upload_id,randomUUID(),JSON.stringify({sourceType:'hello_landing',period:'2026-06',status:'approved',mapping:{version:'v1'},reason:'Reviewed fixture source'})]);
const periods=['2026-07','2026-08','2026-09'];const payload={name:'Future Q3 fixture',model:'conventional',periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:reg.version_id,ownerId:owner,reviewerId:owner,drivers:[],overrides:[],sourceUploadIds:[upload.upload_id],reason:'Future approved fixture'};let forecast=await call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',JSON.stringify(payload)]);for(const action of ['reconcile','ready','submit','approve_lock'])forecast=await call('atlas_save_reforecast_scenario',[A,forecast.head.scenario_id,forecast.head.revision,randomUUID(),action,JSON.stringify(forecast.revision.payload)]);
await db.exec('reset role');let runs=(await db.query('select bonus_calculation_run_id,exceptions from atlas_bonus_calculation_runs')).rows;assert(runs.find(r=>r.bonus_calculation_run_id===staleRun).exceptions.some(e=>e.code==='baseline_stale'));assert.deepEqual(runs.find(r=>r.bonus_calculation_run_id===unrelatedRun).exceptions,[]);assert.deepEqual(runs.find(r=>r.bonus_calculation_run_id===paidRun).exceptions,[]);
const closes=[];for(const period of periods){const id=randomUUID();closes.push(id);await db.query('insert into atlas_financial_close_versions values($1,$2,$3,$4,now(),\'{}\')',[id,A,period,'close-'+period]);await db.query("insert into atlas_financial_close_heads values($1,$2,'accrual',$3)",[A,period,id]);}
await signIn(1);const baselines=await call('atlas_reforecast_effective_baseline',[[A],periods]);assert(baselines.every(b=>b.status==='available'));
const period={periodKey:'2026-Q3',start:'2026-07-01',end:'2026-09-30'},financialEvidence={periods,baselineEvidence:baselines,actualCloseVersions:closes,snapshotFingerprint:'synthetic-financial-snapshot',financialSnapshot:{identity:{communityId:A}}};const line={...bareLine(),retainedRow:{employee:{employeeId:employee,assignmentId:assignment,assignmentVersion:1,active:true,bonusEligible:true,effectiveStart:'2026-01-01',effectiveEnd:'2026-12-31'},plan:{id:plan,version:1,status:'active',roleId:role,effectiveStart:'2026-01-01',effectiveEnd:'2026-12-31',eligibilityRules,metrics:[metricDefinition]},period,finalPayout:123,metricResults:[{metric:metricDefinition,actual:3000,earned:123,financialEvidence}]}};
await db.exec('reset role');const approvedRun=randomUUID(),lockedRun=randomUUID();await insertRun(approvedRun,periodId,'approved',{lines:[line]});await insertRun(lockedRun,periodId,'locked',{lines:[line]});await signIn(1);
const receipt=async id=>(await call('atlas_read_bonus_receipts',['2026-Q3'])).find(r=>r.run?.bonus_calculation_run_id===id);assert.equal((await receipt(approvedRun)).verified,true);assert.equal((await receipt(lockedRun)).verified,true);
// Canonical eligibility changes invalidate unpaid proof while retained locked evidence remains available.
const verifyEligibilityChange=async(sql,args,restore,restoreArgs)=>{await db.exec('reset role');await db.query(sql,args);await signIn(1);assert.equal((await receipt(approvedRun)).verified,false);assert.equal((await receipt(lockedRun)).verified,true);await db.exec('reset role');await db.query(restore,restoreArgs);await signIn(1);assert.equal((await receipt(approvedRun)).verified,true);};
await verifyEligibilityChange('update atlas_incentive_plans set version=2 where incentive_plan_id=$1',[plan],'update atlas_incentive_plans set version=1 where incentive_plan_id=$1',[plan]);
await verifyEligibilityChange("update atlas_employee_assignments set effective_end='2026-08-31' where assignment_id=$1",[assignment],"update atlas_employee_assignments set effective_end='2026-12-31' where assignment_id=$1",[assignment]);
await verifyEligibilityChange('update atlas_incentive_plans set metric_rules=$1 where incentive_plan_id=$2',[JSON.stringify([{...metricDefinition,goal:200}]),plan],'update atlas_incentive_plans set metric_rules=$1 where incentive_plan_id=$2',[JSON.stringify([metricDefinition]),plan]);
await verifyEligibilityChange('update atlas_incentive_plans set eligibility_rules=$1 where incentive_plan_id=$2',[JSON.stringify({...eligibilityRules,communityIds:[B]}),plan],'update atlas_incentive_plans set eligibility_rules=$1 where incentive_plan_id=$2',[JSON.stringify(eligibilityRules),plan]);
await verifyEligibilityChange("update atlas_employee_assignments set employment_status='Inactive' where assignment_id=$1",[assignment],"update atlas_employee_assignments set employment_status='Active' where assignment_id=$1",[assignment]);
await verifyEligibilityChange('update atlas_employees set bonus_eligible=false where employee_id=$1',[employee],'update atlas_employees set bonus_eligible=true where employee_id=$1',[employee]);
const rewriteApproved=async changed=>{await db.exec('reset role');const payload=JSON.stringify({lines:[changed]});await db.query("update atlas_bonus_calculation_runs set inputs=$1,calculation_hash=encode(sha256(convert_to($1::jsonb::text,'UTF8')),'hex') where bonus_calculation_run_id=$2",[payload,approvedRun]);await db.query('update atlas_bonus_calculation_lines set line_payload=$1 where bonus_calculation_run_id=$2',[JSON.stringify(changed),approvedRun]);await signIn(1);};
const forgedMetric=structuredClone(line);forgedMetric.retainedRow.metricResults[0].metric.goal=500;await rewriteApproved(forgedMetric);assert.equal((await receipt(approvedRun)).verified,false,'matching content hash cannot authorize a changed metric rule');await rewriteApproved(line);assert.equal((await receipt(approvedRun)).verified,true);
const localPlan=structuredClone(line);localPlan.retainedRow.plan.id='plan_gm_local';await rewriteApproved(localPlan);assert.equal((await receipt(approvedRun)).verified,false,'local fallback plan never makes a payable canonical receipt');await rewriteApproved(line);
// A close replacement invalidates unpaid evidence without a forecast-publication event.
await db.exec('reset role');const replacement=randomUUID();await db.query('insert into atlas_financial_close_versions values($1,$2,\'2026-08\',\'replacement-hash\',now(),\'{}\')',[replacement,A]);await db.query("update atlas_financial_close_heads set version_id=$1 where community_id=$2 and period_key='2026-08'",[replacement,A]);await signIn(1);assert.equal((await receipt(approvedRun)).verified,false);assert.equal((await receipt(lockedRun)).verified,true,'locked history ignores later replacement');await db.exec('reset role');await db.query("update atlas_financial_close_heads set version_id=$1 where community_id=$2 and period_key='2026-08'",[closes[1],A]);await signIn(1);assert.equal((await receipt(approvedRun)).verified,true);
// A rejected provider mapping invalidates unpaid evidence through active-baseline verification.
await call('atlas_review_reforecast_source',[upload.upload_id,randomUUID(),JSON.stringify({sourceType:'hello_landing',period:'2026-06',status:'rejected',mapping:{version:'v2'},reason:'Review changed after approval'})]);assert.equal((await receipt(approvedRun)).verified,false);assert.equal((await receipt(lockedRun)).verified,true);
await db.exec('reset role');await db.query("insert into atlas_reforecast_events(community_id,scenario_id,publication_id,event_type,request_id,request_hash,detail,actor_id) values($1,$2,$3,'reopened',$4,'synthetic-reopen','{}',$5)",[A,forecast.head.scenario_id,forecast.publication.publication_id,randomUUID(),owner]);runs=(await db.query('select bonus_calculation_run_id,exceptions from atlas_bonus_calculation_runs')).rows;assert.equal(runs.find(r=>r.bonus_calculation_run_id===staleRun).exceptions.filter(e=>e.code==='baseline_stale').length,2,'reopen also invalidates scoped null-community pending run');assert.deepEqual(runs.find(r=>r.bonus_calculation_run_id===paidRun).exceptions,[]);
await db.close();console.log('PASS portfolio null-community Bonus stale/locked scope and unpaid canonical plan/assignment/metric eligibility and exact baseline/close freshness; paid/locked evidence retained after close replacement or source rejection');})().catch(e=>{console.error(e);process.exitCode=1});
