// Install all additive forecast migrations together, both on a fresh fixture and over a published vintage.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
const root=path.join(__dirname,'..'),sql=name=>fs.readFileSync(path.join(root,'docs/portfolio-operations-dashboard/centralization',name),'utf8');
(async()=>{for(const mode of ['clean','upgrade']){const {db,A,BUDGET,signIn}=await fixture();const call=async(name,args)=>(await db.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
const owner='00000000-0000-0000-0000-000000000001',periods=['2026-01','2026-02'];const accounts=[['5120','income'],['5220','contra_income'],['6100','expense'],['6200','expense'],['8100','capital']].map(([accountCode,nature])=>({accountCode,nature,category:accountCode,placement:nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'}));const reg=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),JSON.stringify({accounts,driverMappings:{},reason:'Integrated registry',effectiveDate:'2026-01-01'})]);
let payload={name:'Integrated forecast',model:'conventional',periods,baselineVersionIds:[BUDGET],registryVersionId:reg.version_id,ownerId:owner,reviewerId:owner,drivers:[],overrides:[],reason:'Integrated migration verification'},oldPublication=null;
const save=(p,id=randomUUID(),version=0,action='save_draft')=>call('atlas_save_reforecast_scenario',[A,id,version,randomUUID(),action,JSON.stringify(p)]);
if(mode==='upgrade'){let r=await save(payload);for(const action of ['reconcile','ready','submit','approve','lock'])r=await save(r.revision.payload,r.head.scenario_id,r.head.revision,action);oldPublication=await call('atlas_publish_reforecast',[r.head.scenario_id,r.head.revision,randomUUID(),'Retain pre-migration vintage']);}
await db.exec('reset role');await db.exec(sql('atlas-central-schema.sql').match(/create table if not exists atlas_contracts \([\s\S]*?\n\);/)[0]);await db.exec(sql('utility-forecasts.sql'));await db.exec("create function atlas_private.resolve_workbook_audit(a jsonb,h text) returns jsonb language sql as $$select a$$;create function atlas_private.finance_coverage(cid uuid,p text,h text) returns jsonb language sql as $$select jsonb_build_object('fullMonthAllowed',coalesce(current_setting('test.coverage_enabled',true),'true')<>'false')$$");
const files=['20260924121641_planning_cell_workbook_integrity_governance.sql','20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924165545_forecast_contract_workflow.sql','20260924165549_reforecast_utility_drivers.sql'];for(const file of files)await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',file),'utf8'));
await signIn(1);if(oldPublication)assert.deepEqual((await db.query('select to_jsonb(p) row from atlas_reforecast_publications p where publication_id=$1',[oldPublication.publication_id])).rows[0].row,oldPublication);
payload={...payload,governanceSchemaVersion:2,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:payload.name,reviewedBy:owner,reviewedAt:'2026-09-24T10:00:00Z'}};let record=await save(payload);for(const action of ['reconcile','ready','submit','approve_lock'])record=await save(record.revision.payload,record.head.scenario_id,record.head.revision,action);
const publication=await call('atlas_read_reforecast_publication',[record.publication.publication_id]);assert.equal(publication.verified,true);assert.equal(publication.contentHash,record.snapshot.fingerprint);const digest=await call('atlas_capture_reforecast_digest',[[A],periods,randomUUID()]);assert.equal(digest.verified,true);assert(digest.communities.length>=1&&digest.communities.every(row=>row.communityId===A));
const contract=await call('atlas_save_forecast_contract',[A,randomUUID(),0,randomUUID(),JSON.stringify({vendor:'Synthetic integrated vendor',amount:0,reason:'Verify canonical contract'})]);assert.equal((await call('atlas_read_forecast_contracts',[A]))[0].contract_id,contract.contract_id);
await signIn(2);assert.deepEqual(await call('atlas_read_reforecast_publication',[record.publication.publication_id]),publication);assert.deepEqual(await call('atlas_read_reforecast_digest',[digest.snapshotId]),digest);
await db.exec("reset role;set test.coverage_enabled='false'");await signIn(1);assert.equal((await call('atlas_reforecast_effective_baseline',[[A],['2026-02']]))[0].status,'unavailable','changed full-month coverage fails closed for frozen close evidence');
await db.exec('reset role;set role anon');await assert.rejects(()=>call('atlas_read_forecast_contracts',[A]),/permission denied/);await db.close();console.log('PASS all forecast migrations '+mode+': approval, report/digest readback, contract, authorized role agreement, coverage invalidation, immutable vintage retention');}})().catch(error=>{console.error(error);process.exitCode=1});
