import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {communityForecastReport,communityForecastWorkbook,communityForecastPdf,pairedForecastReports} from '../docs/portfolio-operations-dashboard/features/reforecast-report.mjs';
import {verifyOfficialExports} from './publication-export-acceptance.mjs';
const require=createRequire(import.meta.url),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js'),clone=structuredClone;
// In-memory regression fixture only. No synthetic report is a production publication.
const periods=['2026-09','2026-10'],sourceHash='a'.repeat(64),sourceReceiptId='test-saved-source',originalBudgetVersion='test-original';
const originalLines=periods.flatMap(period=>[{period,accountCode:'5120',accountName:'Rent',nature:'income',placement:'above_noi',originalBudget:100,selectedBaseline:100,forecast:100,actual:null,closeVersionId:null},{period,accountCode:'6500',accountName:'Service',nature:'expense',placement:'above_noi',originalBudget:20,selectedBaseline:20,forecast:20,actual:null,closeVersionId:null}]);
const parent={communityId:'test-community',scenarioId:'test-conventional',revisionId:'test-parent-revision',publicationId:'test-parent-publication',contentHash:'parent-test-hash',verified:true,approved:true,locked:true,periods,source:{registry:{relationships:[]}},snapshot:{fingerprint:'parent-test-snapshot',identity:{communityId:'test-community',periods,baselineVersionIds:[originalBudgetVersion],mappingRegistryVersion:'parent-map',actualCutoff:'2026-08',actualCloseVersions:[]},lines:originalLines,monthly:periods.map(period=>({period,reforecast:{grossIncome:100,contraRevenue:0,expenses:20,capital:0,noi:80},originalBudget:{grossIncome:100,contraRevenue:0,expenses:20,capital:0,noi:80},actuals:{grossIncome:null,contraRevenue:0,expenses:null,capital:0,noi:null}}))}};
const derived=clone(parent);Object.assign(derived,{scenarioId:'test-str',revisionId:'test-derived-revision',publicationId:'test-derived-publication',contentHash:'derived-test-hash'});
derived.snapshot.identity.parentPublication={publicationId:parent.publicationId,revisionId:parent.revisionId,contentHash:parent.contentHash};
derived.snapshot.identity.mappingRegistryVersion='derived-map';
derived.snapshot.savedStrProgramme={sourceReceiptId,sourceHash,sourceFingerprint:'b'.repeat(64),contentHash:'c'.repeat(64),programmeId:'test-programme',groupAllocationCount:2,allocatedUnits:5,unitRamp:periods.map((period,i)=>({period,units:i?5:0,privateKey:'DO_NOT_EXPORT_PRIVATE'})),groupAllocations:[{privateKey:'DO_NOT_EXPORT_PRIVATE'}],cells:[{privateKey:'DO_NOT_EXPORT_PRIVATE'}],rollupReview:{confirmed:true,sourceHash,authority:'saved_monthly_gl_cells',reason:'Retain saved monthly cents; original annual summary rounds differently.',privateKey:'DO_NOT_EXPORT_PRIVATE'},sourceRollupDifferences:[{year:'2026',metric:'totalRevenue',savedProgrammeTotal:50.12,savedMonthlyGLTotal:50.11,difference:-.01,authority:'saved_monthly_gl_cells',privateKey:'DO_NOT_EXPORT_PRIVATE'}],registryExtension:{kind:'preserve_parent_accounts',parentRegistryVersion:'parent-map',parentRegistryHash:'d'.repeat(64),registryVersion:'derived-map',registryHash:'e'.repeat(64),addedAccountCodes:['1504'],privateKey:'DO_NOT_EXPORT_PRIVATE'}};
for(const row of derived.snapshot.lines)if(row.accountCode==='5120')row.forecast=125;
for(const [index,period]of periods.entries())derived.snapshot.lines.push({period,accountCode:'1504',accountName:'Furnishing capital',nature:'capital',placement:'below_noi',originalBudget:null,selectedBaseline:null,forecast:index?50:0,actual:null,closeVersionId:null,baselineDisposition:{kind:'no_original_budget_row',confirmed:true,reviewedBy:'test-reviewer',reviewedAt:'2026-09-25T00:00:00Z',reason:'Explicit source contribution absent from original and parent',originalBudgetVersionIds:[originalBudgetVersion],parentDisposition:'no_parent_publication_row',sourceReceiptId}});
derived.snapshot.strBridge=derived.snapshot.lines.map(row=>{const prior=parent.snapshot.lines.find(p=>p.period===row.period&&p.accountCode===row.accountCode);return{period:row.period,accountCode:row.accountCode,conventional:prior?.forecast??null,strContribution:row.forecast-(prior?.forecast??0),withStr:row.forecast,parentDisposition:prior?'existing_parent_cell':'no_parent_publication_row'};});
derived.snapshot.strSchedules=periods.map((period,index)=>({streamId:'saved-test-programme',period,availableUnits:index?5:0,grossIncome:25,netIncome:25,capital:index?50:0,sourceKind:'saved_json_monthly_programme',sourceReceiptId,sourceHash,incomeBasis:'saved_monthly_gl_cells',application:'add',privateKey:'DO_NOT_EXPORT_PRIVATE'}));
for(const [index,row]of derived.snapshot.monthly.entries()){Object.assign(row.reforecast,{grossIncome:125,capital:index?50:0,noi:105});row.actuals.capital=null;}
const options={communityName:'Synthetic report regression'},pair=pairedForecastReports(parent,derived,options),report=pair.withStr;
assert.equal(pair.pairContext.mappingVersion,'parent-map');assert.equal(pair.pairContext.strMappingVersion,'derived-map');assert.equal(report.bridge.filter(row=>row.Conventional===null).length,2);assert.equal(report.bridge.find(row=>row.GL==='1504').STR_contribution,0,'Explicit source zero is retained separately from absent parent');
assert.equal(report.schedules[1].Capital,50);assert.equal(report.schedules[0].Income_basis,'saved_monthly_gl_cells');assert.equal(report.schedules[0].Source_receipt,sourceReceiptId);assert.equal(report.sourceReconciliation[0].Difference,-.01);assert.equal(report.appendix[0].Saved_STR_source_hash,sourceHash);assert.equal(report.appendix[0].Saved_STR_receipt_hash,'c'.repeat(64));assert(!JSON.stringify(report).includes('DO_NOT_EXPORT_PRIVATE'),'Only allowlisted source proof may enter ordinary reports');
const xlsxBytes=XLSX.write(communityForecastWorkbook(derived,XLSX,pair.reportOptions),{type:'buffer',bookType:'xlsx'}),pdfBytes=await communityForecastPdf(derived,pair.reportOptions),verified=await verifyOfficialExports({publication:derived,xlsxBytes,pdfBytes,screenRows:report.rows,screenMonthly:report.monthly,options:pair.reportOptions});assert.equal(verified.xlsxSheets,11);
const reopened=XLSX.read(xlsxBytes,{type:'array'});assert.equal(XLSX.utils.sheet_to_json(reopened.Sheets['Saved STR reconciliation'])[0].Difference,-.01);assert.equal(XLSX.utils.sheet_to_json(reopened.Sheets['STR schedule'])[1].Capital,50);
for(const mutate of [d=>delete d.snapshot.savedStrProgramme,d=>delete d.snapshot.lines.at(-1).baselineDisposition,d=>d.snapshot.lines.at(-1).baselineDisposition.sourceReceiptId='wrong',d=>d.snapshot.strBridge.at(-1).parentDisposition='existing_parent_cell',d=>d.snapshot.strBridge.at(-1).conventional=0,d=>d.snapshot.lines.at(-1).originalBudget=0,d=>d.snapshot.lines.at(-1).actual=0,d=>d.snapshot.lines.at(-1).selectedBaseline=0,d=>d.snapshot.lines[0].originalBudget=99,d=>d.snapshot.strBridge[0].strContribution=24,d=>d.snapshot.savedStrProgramme.registryExtension.parentRegistryVersion='wrong',d=>d.snapshot.savedStrProgramme.registryExtension.addedAccountCodes=['9999'],d=>d.snapshot.savedStrProgramme.registryExtension.addedAccountCodes.push('5120')]){const broken=clone(derived);mutate(broken);assert.throws(()=>pairedForecastReports(parent,broken,options));}
const omitted=clone(derived);omitted.snapshot.lines=omitted.snapshot.lines.filter(row=>row.accountCode!=='6500');omitted.snapshot.strBridge=omitted.snapshot.strBridge.filter(row=>row.accountCode!=='6500');assert.throws(()=>pairedForecastReports(parent,omitted,options),/omits/);
const duplicate=clone(derived);duplicate.snapshot.lines.push(clone(duplicate.snapshot.lines[0]));duplicate.snapshot.strBridge.push(clone(duplicate.snapshot.strBridge[0]));assert.throws(()=>pairedForecastReports(parent,duplicate,options),/duplicate/);
const wrongReview=clone(derived);wrongReview.snapshot.savedStrProgramme.rollupReview.confirmed=false;assert.throws(()=>communityForecastReport(wrongReview),/reconciliation review/);
const altered=clone(communityForecastWorkbook(derived,XLSX,pair.reportOptions)),rs=altered.Sheets['Saved STR reconciliation'],differenceColumn=Object.entries(rs).find(([address,cell])=>/^[A-Z]+1$/.test(address)&&cell.v==='Difference')[0].replace(/1$/,'');rs[differenceColumn+'2'].v=0;await assert.rejects(verifyOfficialExports({publication:derived,xlsxBytes:XLSX.write(altered,{type:'buffer',bookType:'xlsx'}),pdfBytes,options:pair.reportOptions}),/Saved STR reconciliation/);
if(process.env.ATLAS_REPORT_VISUAL_DIR){fs.mkdirSync(process.env.ATLAS_REPORT_VISUAL_DIR,{recursive:true});fs.writeFileSync(path.join(process.env.ATLAS_REPORT_VISUAL_DIR,'synthetic-saved-str-report.pdf'),pdfBytes);fs.writeFileSync(path.join(process.env.ATLAS_REPORT_VISUAL_DIR,'synthetic-saved-str-report.xlsx'),xlsxBytes);}
console.log('PASS exact Conventional parent bridge and reviewed prospective GLs, source/registry receipt bindings, saved rounding reconciliation, source capital/basis, private data exclusion, all 11 XLSX sheets reopened and PDF retained evidence parity. Synthetic regression only.');
