// Optional exact private workbook scale proof; source files never enter the repository.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{
 const file=process.env.ATLAS_WORKBOOK_BLANK_PRIVATE_FIXTURE;
 if(!file){console.log('SKIP optional private workbook blank volume fixture');return;}
 const input=JSON.parse(fs.readFileSync(file,'utf8')),root=path.join(__dirname,'..'),read=n=>fs.readFileSync(path.join(root,'supabase/migrations',n),'utf8'),owner='00000000-0000-0000-0000-000000000001',stamp='2026-09-28T00:00:00Z';
 const {db,A,BUDGET,signIn}=await fixture(),call=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args,{onNotice:notice=>{if(process.env.ATLAS_WORKBOOK_PROFILE&&notice.message.startsWith('PROFILE '))console.log(JSON.stringify({stage:'sql_profile',message:notice.message}));}})).rows[0].result;
 await db.exec('reset role');await db.exec(read('20260924121641_planning_cell_workbook_integrity_governance.sql'));await db.exec(read('20260924121647_immutable_workbook_audits_and_monthly_governance.sql').split('alter function atlas_private.finance_intake_validation')[0]);
 for(const name of ['20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql','20260925020220_reforecast_import_source_relationships.sql','20260925020222_reforecast_saved_json_str_programme.sql','20260925020226_reforecast_import_source_occurrence_index.sql','20260925071533_reforecast_request_identity_consistency.sql','20260925162050_budget_governed_draft_investor_lifecycle.sql'])await db.exec(read(name));
 await db.exec("create function atlas_private.budget_calendar(cid uuid) returns jsonb language sql as $$select '{\"verified\":true,\"basis\":\"calendar\",\"startMonth\":1}'::jsonb$$");
 for(const name of ['20260928141143_reviewed_noncash_forecast_presentation.sql','20260928142628_indexed_import_validation_evidence.sql','20260928144620_bounded_reforecast_validation_memory.sql'])await db.exec(read(name));
 const projection=await import('./workbook-projection-fixture.mjs');await projection.installProjectionFixture(db);await db.exec(read('20260928210158_verified_workbook_blank_forecast_semantics.sql'));
 // Optional local-only phase timing; does not change source or validations.
 if(process.env.ATLAS_WORKBOOK_PROFILE){
  await db.exec("create function atlas_private.workbook_profile(label text,started timestamptz) returns void language plpgsql stable as $$begin raise notice 'PROFILE % %ms',label,round(extract(epoch from clock_timestamp()-started)*1000);end;$$");
  const specs=[
   ['attach_reforecast_workbook_context(jsonb,jsonb)',["cells:=atlas_private.resolve_reforecast_workbook_blanks(source,config);","excluded:=atlas_private.resolve_reforecast_workbook_scope(source,config);","imported:=atlas_private.reforecast_workbook_imported_cells(cid,config);","coverage:=atlas_private.reforecast_workbook_source_coverage(source,config);"]],
   ['create_reforecast_from_import(uuid,uuid,integer,uuid,uuid,jsonb,jsonb)',["source:=atlas_private.reforecast_source_before_workbook_blanks(p_community_id,config);","source:=atlas_private.attach_reforecast_workbook_context(source,config);","-- Exclusion details cover the review's scenario/months.","issues:=atlas_private.reforecast_import_issues(source,config);","result:=atlas_private.save_reforecast_builder(p_community_id,p_scenario_id,p_expected_revision,p_request_id,'save_draft',config);"]],
   ['save_reforecast_builder(uuid,uuid,integer,uuid,text,jsonb)',["source:=atlas_private.reforecast_source_for_config(p_community_id,config);","snapshot:=atlas_private.calculate_reforecast(source,config);","if owner_id is null or reviewer_id is null then"]]
  ];
  for(const [name,anchors]of specs){let definition=(await db.query('select pg_get_functiondef($1::regprocedure) d',['atlas_private.'+name])).rows[0].d;definition=definition.replace('DECLARE ', 'DECLARE profile_started timestamptz:=clock_timestamp();').replace('declare ', 'declare profile_started timestamptz:=clock_timestamp();');for(const [i,anchor]of anchors.entries()){assert.equal(definition.split(anchor).length,2,anchor);const mark=`perform atlas_private.workbook_profile('${name.split('(')[0]}:${i+1}',profile_started);`;definition=definition.replace(anchor,anchor.startsWith('--')||anchor.startsWith('if owner')?mark+'\n '+anchor:anchor+'\n '+mark);}await db.exec(definition);}
 }
 // Baseline comparisons are the retained exact values, not synthetic substitutes.
 const budget=JSON.parse(fs.readFileSync(path.join(path.dirname(file),'doro-approved-budget-payload.json'),'utf8'));budget.communityId=A;await db.query('update atlas_approved_budget_versions set payload=$1 where version_id=$2',[budget,BUDGET]);
 await signIn(1);const registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),{...input.registry,version:undefined,reason:'Isolated reviewed registry fixture; no production writes'}]);
 const evidence=input.evidence,sourceBytes=Buffer.from(evidence.source.originalFile.data,'base64'),started=performance.now(),audit=await projection.saveProjectedAudit(db,A,evidence.integrity,sourceBytes),auditMs=Math.round(performance.now()-started);console.log(JSON.stringify({stage:'audit_retained',auditMs}));
 const assignment={...input.mapping.propertyAssignment,communityId:A,actorId:owner},mapping=structuredClone(input.mapping);Object.assign(mapping,{version:registry.version_id,propertyAssignment:assignment,reviewedBy:owner,reviewedAt:stamp});mapping.calendar={...mapping.calendar,reviewedBy:owner,reviewedAt:stamp};mapping.currencyMapping={...mapping.currencyMapping,reviewedBy:owner,reviewedAt:stamp};mapping.workbookSourcePolicy={...mapping.workbookSourcePolicy,reviewedBy:owner,reviewedAt:stamp};
 for(const group of ['rowDispositions','inputReviews','integrityReviews'])mapping[group]=(mapping[group]||[]).map(r=>({...r,ownerId:owner,reviewedAt:stamp,...(r.integrityFingerprint?{integrityFingerprint:audit.fingerprint}:{})}));
 mapping.accountMappings=mapping.accountMappings.map(m=>m.baselineDisposition?{...m,baselineDisposition:{...m.baselineDisposition,reviewedBy:owner,reviewedAt:stamp,originalBudgetVersionIds:[BUDGET]}}:m);
 const uploadId=randomUUID(),upload={...evidence,integrity:{auditId:audit.audit_id,fingerprint:audit.fingerprint,manifestHash:audit.manifest_hash},propertyAssignment:assignment};
 await db.exec('reset role');await db.query("insert into atlas_reforecast_uploads(upload_id,community_id,request_id,source_hash,content_hash,payload,created_by,created_role) values($1,$2,$3,$4,$5,$6,$7,'admin')",[uploadId,A,randomUUID(),evidence.source.sha256,'private-fixture',upload,owner]);await signIn(1);
 const payload={name:'Exact private blank volume',model:'conventional',scenarioPurpose:'conventional',governanceSchemaVersion:2,calendar:{...mapping.calendar,scenario:'Exact private blank volume'},periods:mapping.periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:owner,reviewerId:owner,drivers:[],overrides:[],reason:'Exact source blank volume proof; no production writes'},scenarioId=randomUUID(),requestId=randomUUID();
 const before=performance.now();let result=await call('atlas_create_reforecast_from_import',[A,scenarioId,0,requestId,uploadId,mapping,payload]);const createMs=Math.round(performance.now()-before);console.log(JSON.stringify({stage:'create_readback',createMs,selected:result.receipt.importedCells.length}));
 assert.equal(result.receipt.importedCells.length,input.expected.length);assert.equal(result.receipt.reconciliation.workbookBlankCellCount,input.expected.filter(c=>c.isBlank).length);assert.equal(result.snapshot.workbookCoverage.sourceAbsentCellCount,input.proposedScope.length);
 for(const cell of input.expected){const row=result.snapshot.lines.find(l=>l.period===cell.period&&l.accountCode===cell.accountCode);assert.equal(row.forecast,cell.amount,cell.sourceLineId);if(cell.isBlank)assert.equal(row.disposition,'workbook_blank');}
 const {computeReforecast}=await import('../docs/portfolio-operations-dashboard/features/reforecast-engine.mjs');const js=computeReforecast({...result.source,scenario:{...result.revision.payload,versionId:result.revision.revision_id,driverVersion:'private'}});for(const key of ['knownValueTotals','workbookSourceTotals']){const {margin:jsMargin,...jsMoney}=js[key],{margin:sqlMargin,...sqlMoney}=result.snapshot[key];assert.deepEqual(jsMoney,sqlMoney);assert.ok(Math.abs(jsMargin-sqlMargin)<=Number.EPSILON*Math.max(1,Math.abs(jsMargin)));}
 if(process.env.ATLAS_WORKBOOK_PROFILE_CREATE_ONLY){console.log(JSON.stringify({status:'PROFILE_ONLY',auditMs,createMs,exactSelectedCells:input.expected.length}));await db.close();return;}
 const retained={revision:structuredClone(result.revision),receipt:structuredClone(result.receipt)},scoped=structuredClone(mapping);scoped.workbookSourcePolicy.outsideForecastScope=input.proposedScope.map(r=>({...r,reviewedBy:owner,reviewedAt:stamp,reason:'Explicit local test scope exclusion; not user policy or production approval'}));
 const {projectImportUpdatePayload}=await import('../docs/portfolio-operations-dashboard/features/reforecast-store.mjs');const updatePayload=projectImportUpdatePayload(result.revision.payload,{uploadId,mapping:scoped,expectedLines:result.receipt.importedCells});const updateStart=performance.now();result=await call('atlas_create_reforecast_from_import',[A,scenarioId,result.head.revision,randomUUID(),uploadId,scoped,updatePayload]);const updateMs=Math.round(performance.now()-updateStart);
 assert.equal(result.snapshot.workbookCoverage.outsideForecastScopeCellCount,input.proposedScope.length);assert.equal(result.snapshot.completeness.blockerCount,0,JSON.stringify(result.snapshot.diagnostics.filter(d=>['blocking','error'].includes(d.severity))));
 const savedBytes=(await db.query('select octet_length(payload::text) n from atlas_reforecast_revisions where revision_id=$1',[result.revision.revision_id])).rows[0].n;assert.ok(savedBytes<=2097152);
 assert.deepEqual((await call('atlas_read_reforecast_import_receipt',[A,requestId])).receipt,retained.receipt);assert.deepEqual((await db.query('select payload from atlas_reforecast_revisions where revision_id=$1',[retained.revision.revision_id])).rows[0].payload,retained.revision.payload);
 const proof={status:'PASS',productionWrites:0,selected:input.expected.length,numeric:input.expected.filter(c=>Number.isFinite(c.amount)).length,zero:input.expected.filter(c=>c.amount===0).length,blank:input.expected.filter(c=>c.isBlank).length,scopeExclusions:input.proposedScope.length,sourceHash:evidence.source.sha256,auditMs,createMs,updateMs,savedBytes,responseBytes:Buffer.byteLength(JSON.stringify(result)),receiptBytes:Buffer.byteLength(JSON.stringify(result.receipt)),knownValueTotals:result.snapshot.knownValueTotals,workbookSourceTotals:result.snapshot.workbookSourceTotals,immutablePriorPreserved:true,notes:['Optional exclusions are isolated test data, not user approval.','Whole exact source/audit retained; every selected coordinate compared.']};
 fs.writeFileSync(path.join(path.dirname(file),'doro-workbook-blank-volume-db-proof.json'),JSON.stringify(proof,null,2)+'\n',{mode:0o600});console.log(JSON.stringify(proof));await db.close();
})().catch(e=>{console.error(e.message,e.where||e.stack);process.exitCode=1});
