import assert from 'node:assert/strict';
import 'fake-indexeddb/auto';
import {saveForecastRecovery,readForecastRecovery,listForecastRecovery,completeForecastImportRecovery,removeForecastRecovery,saveForecastRecoveryEntries} from '../docs/portfolio-operations-dashboard/features/reforecast-recovery.mjs';
const id=n=>'30000000-0000-0000-0000-'+String(n).padStart(12,'0'),hash='a'.repeat(64),parserVersion='atlas-reforecast-xlsx/3',evidenceId='workbook:'+hash+':'+parserVersion,actor=id(1);let activeActor=actor;
const central={getSession:()=>({user:{id:activeActor}})},line={period:'2026-09',accountCode:'5120',amount:0,sourceLineId:'Plan!A1',sourceHash:hash,sourceCoordinates:{sheet:'Plan',address:'A1',row:1,column:1}};
const request={communityId:id(2),scenarioId:id(3),requestId:id(4),uploadId:id(5),mapping:{version:id(6)},parserVersion,expectedLines:[line]},result={head:{community_id:request.communityId,scenario_id:request.scenarioId},revision:{revision_id:id(7),community_id:request.communityId,scenario_id:request.scenarioId,payload:{overrides:[line]}},snapshot:{lines:[{...line,forecast:0}]},receipt:{verified:true,request_id:request.requestId,upload_id:request.uploadId,mapping_version:request.mapping.version,revision_id:id(7),importedCells:[line]}};
const seed=async()=>{await saveForecastRecoveryEntries(central,[{id:evidenceId,value:{kind:'workbook-evidence',evidence:{source:{sha256:hash,originalFile:{encoding:'base64',data:'exact-workbook-bytes'}}}}},{id:'review-one',value:{kind:'import-review',reviewVersion:'version-one',evidenceId}}]);await saveForecastRecovery(central,'write-one',{kind:'import-write',request,reviewId:'review-one',reviewVersion:'version-one',evidenceId});};
await seed();const evidenceBefore=await readForecastRecovery(central,evidenceId);
for(const corrupted of [null,{...result,receipt:{...result.receipt,verified:false}},{...result,snapshot:{lines:[{...line,forecast:null}]}}]){await assert.rejects(()=>completeForecastImportRecovery(central,{recoveryId:'write-one',result:corrupted}));assert.deepEqual(await readForecastRecovery(central,evidenceId),evidenceBefore);assert(await readForecastRecovery(central,'review-one'));assert(await readForecastRecovery(central,'write-one'));}
// A second review of the same file needs the original bytes even after the first
// import commits. A second actor owns a separate copy under the same logical ID.
await saveForecastRecovery(central,'review-two',{kind:'import-review',reviewVersion:'version-two',evidenceId});activeActor=id(20);await seed();activeActor=actor;
await completeForecastImportRecovery(central,{recoveryId:'write-one',result});assert.equal(await readForecastRecovery(central,'write-one'),null);assert.equal(await readForecastRecovery(central,'review-one'),null);assert.deepEqual(await readForecastRecovery(central,evidenceId),evidenceBefore);assert(await readForecastRecovery(central,'review-two'));
await saveForecastRecovery(central,'write-two',{kind:'import-write',request,reviewId:'review-two',reviewVersion:'version-two',evidenceId});await completeForecastImportRecovery(central,{recoveryId:'write-two',result});assert.equal(await readForecastRecovery(central,evidenceId),null);assert.equal(await readForecastRecovery(central,'review-two'),null);assert.deepEqual(await listForecastRecovery(central),[]);await completeForecastImportRecovery(central,{recoveryId:'write-two',result});
activeActor=id(20);assert(await readForecastRecovery(central,evidenceId));assert(await readForecastRecovery(central,'write-one'));activeActor=actor;
// Old hidden completion markers have enough retained request provenance to
// identify their orphaned workbook. They are visible for receipt-only recovery.
await seed();await saveForecastRecovery(central,'write-one',{kind:'import-complete',request,reviewId:'review-one',reviewVersion:'version-one'});assert((await listForecastRecovery(central)).some(row=>row.kind==='import-complete'));await completeForecastImportRecovery(central,{recoveryId:'write-one',result});assert.equal(await readForecastRecovery(central,evidenceId),null);
await seed();await saveForecastRecovery(central,'write-one',{kind:'import-complete',request});await completeForecastImportRecovery(central,{recoveryId:'write-one',result});assert(await readForecastRecovery(central,evidenceId),'A distinct surviving review still references the shared evidence');
await removeForecastRecovery(central,'review-one');await saveForecastRecovery(central,'legacy-orphan',{kind:'import-complete',request});await completeForecastImportRecovery(central,{recoveryId:'legacy-orphan',result});assert.equal(await readForecastRecovery(central,evidenceId),null,'Legacy exact source hash and parser recover the orphaned evidence link');
await seed();const unrelatedId='workbook:'+'b'.repeat(64)+':'+parserVersion;await saveForecastRecovery(central,unrelatedId,{kind:'workbook-evidence',evidence:{source:{sha256:'b'.repeat(64),originalFile:{data:'different workbook'}}}});await saveForecastRecovery(central,'write-one',{kind:'import-write',request,reviewId:'review-one',reviewVersion:'version-one',evidenceId:unrelatedId});await completeForecastImportRecovery(central,{recoveryId:'write-one',result});assert(await readForecastRecovery(central,unrelatedId),'An incorrect reference cannot release bytes belonging to a different workbook');
// A second tab may reuse the review ID and persist newer mapping fields. The
// completed request owns only its frozen review version, never those new edits.
await seed();await saveForecastRecoveryEntries(central,[{id:evidenceId,value:{kind:'workbook-evidence',evidence:evidenceBefore.evidence},ifAbsent:true},{id:'review-one',value:{kind:'import-review',reviewVersion:'newer-version',evidenceId,fields:{reason:'Newer unsaved mapping from another tab'}}}]);await completeForecastImportRecovery(central,{recoveryId:'write-one',result});assert.equal((await readForecastRecovery(central,'review-one')).fields.reason,'Newer unsaved mapping from another tab');assert(await readForecastRecovery(central,evidenceId));
// A still-open tab can edit after cleanup. Conditional acquisition restores the
// shared bytes atomically with its newly persisted review, without an orphan.
await seed();await completeForecastImportRecovery(central,{recoveryId:'write-one',result});assert.equal(await readForecastRecovery(central,evidenceId),null);await saveForecastRecoveryEntries(central,[{id:evidenceId,value:{kind:'workbook-evidence',evidence:evidenceBefore.evidence},ifAbsent:true},{id:'review-one',value:{kind:'import-review',reviewVersion:'late-version',evidenceId}}]);assert.deepEqual((await readForecastRecovery(central,evidenceId)).evidence,evidenceBefore.evidence);assert.equal((await readForecastRecovery(central,'review-one')).reviewVersion,'late-version');
// Reference acquisition and verified cleanup may race across tabs. Whichever
// transaction wins, the new review must finish with its original bytes present.
for(const cleanupFirst of [true,false]){
 await seed();const acquire=()=>saveForecastRecoveryEntries(central,[{id:evidenceId,value:{kind:'workbook-evidence',evidence:evidenceBefore.evidence}},{id:'concurrent-review',value:{kind:'import-review',reviewVersion:'version-one',evidenceId}}]),cleanup=()=>completeForecastImportRecovery(central,{recoveryId:'write-one',result});
 await Promise.all(cleanupFirst?[cleanup(),acquire()]:[acquire(),cleanup()]);assert(await readForecastRecovery(central,'concurrent-review'));assert.deepEqual((await readForecastRecovery(central,evidenceId)).evidence,evidenceBefore.evidence);assert.equal(await readForecastRecovery(central,'write-one'),null);await removeForecastRecovery(central,'concurrent-review');
}
console.log('PASS import recovery cleanup: exact receipt required; invalid or uncertain readback preserves all records; verified completion atomically removes request/review/unreferenced bytes; concurrent shared-reference acquisition and actor isolation preserve required bytes; newer same-ID reviews and late edits retain bytes; legacy completion records remain recoverable.');
