import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {compactNewForecastCellHistoryEvent as compact,reconstructForecastCellHistoryEvent as reconstruct,expandedForecastCellHistory as expand} from '../docs/portfolio-operations-dashboard/features/reforecast-cell-history.mjs';
import {canonicalJson,sha256} from '../docs/portfolio-operations-dashboard/features/financial-snapshot.mjs';
import {updateReforecastCell,readReforecastRevisionHistory} from '../docs/portfolio-operations-dashboard/features/reforecast-ui.mjs';
import {undoRecommendationAction,applyRecommendations} from '../docs/portfolio-operations-dashboard/features/reforecast-engine.mjs';
const clone=structuredClone,id=n=>'90000000-0000-0000-0000-'+String(n).padStart(12,'0'),actor=id(9),period='2026-09';
const collection=p=>({overrides:clone(p.overrides||[]),drivers:clone(p.drivers||[])});
const overrides=Array.from({length:40},(_,index)=>({period,accountCode:String(6000+index),amount:index===0?0:index-15,reason:'Synthetic reviewed planning input '+index,source:{kind:'workbook',sourceLineId:'synthetic-'+index,coordinates:{sheet:'Input',row:index+20,column:'AW'},review:{actor,reason:'Synthetic source evidence retained without financial mutation'}}}));
const payload={periods:[period],drivers:[],overrides,history:[{action:'retained_synthetic_audit',reason:'This exact prior object must remain unchanged',other:{retained:['all','metadata']}}],suggestionDecisions:[]};
const base={community_id:id(1),scenario_id:id(2),revision_id:id(3),request_id:id(4),revision:11,status:'working_draft',payload,snapshot:{fingerprint:'a'.repeat(64),lines:[]}};
const meta={actor,timestamp:'2026-09-29T12:00:00Z',versionId:id(5),driverVersion:id(6)};
const legacy=(before,after,accountCode='6000')=>({action:'cell_edit',...meta,period,accountCode,before:clone(before.overrides),after:clone(after.overrides)});
const record=row=>({head:Object.fromEntries(['community_id','scenario_id','revision_id','revision','status'].map(key=>[key,row[key]])),revision:clone(row),snapshot:clone(row.snapshot)});
let before=collection(payload),after=clone(before);after.overrides=after.overrides.filter(row=>row.accountCode!=='6000').concat({...after.overrides[0],amount:0,reason:'Explicit synthetic zero review'});
const original=legacy(before,after),event=compact(original,{record:record(base),history:clone(payload.history),before,after});
assert.equal(event.cellHistory.kind,'revision_bound_cell_delta');assert.equal(event.before.length,1);assert.equal(event.after.length,1);
assert.deepEqual(reconstruct(event,{baseRevision:base,currentState:before}).after,after);
const expandedFirst=reconstruct(event,{baseRevision:base,currentState:before}).event;delete expandedFirst.cellHistory;assert.deepEqual(expandedFirst,original,'Full original event is exactly recoverable, including evidence and order');
assert.deepEqual(reconstruct(event,{baseRevision:base,currentState:after,direction:'backward'}).before,before);
assert(Buffer.byteLength(JSON.stringify(event))<Buffer.byteLength(JSON.stringify(original))/4);
const history=[...clone(payload.history),event],secondBefore=clone(after),secondAfter=clone(after);secondAfter.overrides.push({period,accountCode:'7000',amount:-1,reason:'Explicit synthetic negative'});
const second=compact(legacy(secondBefore,secondAfter,'7000'),{record:base,history,before:secondBefore,after:secondAfter});assert(second.cellHistory);history.push(second);
const thirdBefore=clone(secondAfter),thirdAfter=clone(secondAfter);thirdAfter.overrides=thirdAfter.overrides.filter(row=>row.accountCode!=='7000');
const third=compact(legacy(thirdBefore,thirdAfter,'7000'),{record:base,history,before:thirdBefore,after:thirdAfter});assert(third.cellHistory);history.push(third);
let backwards=clone(thirdAfter);for(const item of history.slice(payload.history.length).reverse())backwards=reconstruct(item,{baseRevision:base,currentState:backwards,direction:'backward'}).before;assert.deepEqual(backwards,before,'Multiple edits reverse losslessly; this is reconstruction, not a new financial undo UI');
const saved={...clone(base),revision_id:id(7),request_id:id(8),revision:12,payload:{...clone(payload),...thirdAfter,history}};
const fullHistory=expand(saved,[base,saved]);assert.deepEqual(fullHistory.slice(0,payload.history.length),payload.history);assert.deepEqual(fullHistory.at(-1).after,thirdAfter.overrides);
for(const mutate of [b=>b.community_id=id(90),b=>b.scenario_id=id(90),b=>b.revision_id=id(90),b=>b.request_id=id(90),b=>b.revision++,b=>b.snapshot.fingerprint='b'.repeat(64),b=>b.payload.reason='tampered',b=>b.payload.history[0].reason='tampered']){const wrong=clone(base);mutate(wrong);assert.throws(()=>reconstruct(event,{baseRevision:wrong,currentState:before}),/binding/);}
for(const mutate of [e=>e.actor=id(90),e=>e.cellHistory.beforeStateSha256='b'.repeat(64),e=>e.cellHistory.overrides.before[0].index++,e=>e.before[0].reason='tampered',e=>e.cellHistory.base.payloadSha256='b'.repeat(64)]){const wrong=clone(event);mutate(wrong);assert.throws(()=>reconstruct(wrong,{baseRevision:base,currentState:before}));}
assert.throws(()=>reconstruct(event,{baseRevision:base,currentState:after}),/state hash/);
assert.throws(()=>expand(saved,[saved]),/ancestor/);assert.throws(()=>expand(saved,[base,base,saved]),/duplicate/);
for(const mutate of [s=>s.community_id=id(90),s=>s.scenario_id=id(90),s=>s.revision=10]){const wrong=clone(saved);mutate(wrong);assert.throws(()=>expand(wrong,[base,wrong]),/ancestor/);}
const mismatched=record(base);mismatched.head.scenario_id=id(90);assert.deepEqual(compact(original,{record:mismatched,history:payload.history,before,after}),original);
assert.deepEqual(compact(original,{record:null,history:payload.history,before,after}),original);
assert.deepEqual(compact(original,{record:base,history:[],before,after}),original,'Unavailable immutable prefix retains the full legacy event');
const duplicate=clone(base);duplicate.payload.overrides.push(clone(duplicate.payload.overrides[0]));const duplicateBefore=collection(duplicate.payload),duplicateAfter=clone(duplicateBefore);duplicateAfter.overrides[0].amount=99;const duplicateEvent=legacy(duplicateBefore,duplicateAfter);assert.deepEqual(compact(duplicateEvent,{record:duplicate,history:duplicate.payload.history,before:duplicateBefore,after:duplicateAfter}),duplicateEvent);
console.log('PASS lossless indexed cell deltas, inserted/removed rows, zero/negative values, multi-edit backward reconstruction, immutable scope/hash/prefix binding and fail-safe legacy fallback.');

// Use the real UI clear path: accepted multi-cell amount evidence is preserved
// while only the selected cell target is removed from its driver.
const code='6400',otherPeriod='2026-10',review={period,accountCode:code,confirmed:true,reviewedBy:actor,reviewedAt:meta.timestamp,reason:'Synthetic reviewed editable blank'},uploadId='synthetic-upload',mapping={version:'synthetic-registry',confirmed:true,reviewedBy:actor,sourceScenario:'Plan',periods:[period,otherPeriod],selectedLineIds:[],workbookSourcePolicy:{schemaVersion:1,mode:'workbook_exact',blankDisposition:'preserve_null',confirmed:true,reviewedBy:actor,reviewedAt:meta.timestamp,reason:'Synthetic exact source review',outsideForecastScope:[],reviewedForecastBlanks:[review]}};
const blank={period,accountCode:code,amount:null,isBlank:true,legitimateBlank:true,disposition:'reviewed_forecast_blank',reviewedForecastBlankConfirmed:true,sourceScopeExclusionConfirmed:false,source:{kind:'reviewed_forecast_blank',workbookSourceAbsent:true,uploadId,auditId:'synthetic-audit',sourceHash:'c'.repeat(64),sourceScenario:'Plan',mappingVersion:mapping.version,review}};
const blankBase=clone(base);blankBase.payload={...clone(payload),periods:[period,otherPeriod],uploadId,importMapping:mapping,drivers:[{id:'synthetic-accepted',operation:'amount',value:5,periods:[period,otherPeriod],accountCodes:[code,'6500'],recommendationId:'synthetic-suggestion',ownerId:id(99),evidence:{method:'weighted_governed_actual_amount'},recommendationReview:{reviewedBy:id(99),reason:'Prior acceptance remains unchanged'}}],suggestionDecisions:[{id:'synthetic-suggestion',status:'accepted',actor:id(99)}]};blankBase.snapshot.lines=[{period,accountCode:code,forecast:5}];
const s={actor,cid:base.community_id,scenarioId:base.scenario_id,cellReason:'Synthetic explicit restore to intentional blank',record:record(blankBase),edit:clone(blankBase.payload),source:{actuals:{cutoffPeriod:'2026-08'},workbookReviewedForecastBlankCells:[blank]}};
const blankBefore=collection(s.edit);updateReforecastCell(s,period,code,'');const clear=s.edit.history.at(-1);assert(clear.cellHistory);assert.equal(clear.before,5);assert.equal(clear.after,null);assert.deepEqual(s.edit.suggestionDecisions,blankBase.payload.suggestionDecisions);assert.deepEqual(clear.source,blank.source);
const restored=reconstruct(clear,{baseRevision:blankBase,currentState:collection(s.edit),direction:'backward'});assert.deepEqual(restored.before,blankBefore);assert.deepEqual(restored.event.workingAfter,collection(s.edit));assert.equal(restored.event.before,5);assert.equal(restored.event.after,null);
const targets=s.edit.drivers.flatMap(d=>d.periods.flatMap(p=>d.accountCodes.map(c=>p+'|'+c)));assert.deepEqual(targets.sort(),[period+'|6500',otherPeriod+'|6400',otherPeriod+'|6500'].sort());assert(s.edit.drivers.every(d=>d.ownerId===id(99)));assert.deepEqual(s.edit.history.slice(0,blankBase.payload.history.length),blankBase.payload.history);
const editClear={...s,edit:clone(blankBase.payload),record:record(blankBase)},uiStates=[collection(blankBase.payload)];for(const value of ['0','-7','']){editClear.cellReason='Synthetic reviewed change '+(value||'restore blank');updateReforecastCell(editClear,period,code,value);assert(editClear.edit.history.at(-1).cellHistory);uiStates.push(collection(editClear.edit));}let uiReverse=collection(editClear.edit);for(let i=2;i>=0;i--){const item=editClear.edit.history[blankBase.payload.history.length+i],result=reconstruct(item,{baseRevision:blankBase,currentState:uiReverse,direction:'backward'});assert.deepEqual(result.before,uiStates[i]);uiReverse=result.before;}assert.deepEqual(uiReverse,collection(blankBase.payload));assert.equal(editClear.edit.history.at(-1).before,5,'Clear scalar stays anchored to saved value after multiple unsaved changes');assert.equal(editClear.edit.history.at(-1).after,null);assert.deepEqual(editClear.edit.history.at(-1).recommendationIds,['synthetic-suggestion']);assert.deepEqual(editClear.edit.suggestionDecisions,blankBase.payload.suggestionDecisions);
for(const action of ['cell_edit','clear_reviewed_forecast_blank','budget_driver_override','copy_browser_scenario','unrecognized'])assert.throws(()=>undoRecommendationAction({drivers:[],history:[{action,before:[],after:[]}]},meta),/Only a recommendation action/);
assert.throws(()=>undoRecommendationAction({drivers:[],history:[{action:'accept',before:[],after:[],cellHistory:{}}]},meta),/Only a recommendation action/);
const rec={id:'synthetic-ratio',driver:{id:'ratio-driver',operation:'percent_change',value:.1,periods:[period],accountCodes:['6000']},source:'synthetic',proposedValue:.1};
const accepted=applyRecommendations(clone(payload),[rec],{...meta,ids:[rec.id],action:'accept'});assert.equal(undoRecommendationAction(accepted,meta).drivers.length,0);
const mixedBefore=collection(accepted),mixedAfter=clone(mixedBefore);mixedAfter.overrides[0].amount=-12;const mixed=compact(legacy(mixedBefore,mixedAfter),{record:base,history:accepted.history,before:mixedBefore,after:mixedAfter});assert(mixed.cellHistory,'Legacy recommendation events can precede a new cell delta');
console.log('PASS actual UI reviewed-blank clear with accepted driver splitting, unchanged prior decisions/actor evidence, and recommendation-only undo type guard.');

let currentActor=actor;const central={getSession:()=>({user:{id:currentActor}}),fetchJson:async()=>[clone(base),clone(saved)]};assert.equal((await readReforecastRevisionHistory(central,{scenarioId:base.scenario_id,communityId:base.community_id})).length,2);
await assert.rejects(()=>readReforecastRevisionHistory({...central,getSession:()=>null},{scenarioId:base.scenario_id,communityId:base.community_id}),/Sign in/);
await assert.rejects(()=>readReforecastRevisionHistory({...central,fetchJson:async()=>[{...base,community_id:id(90)}]},{scenarioId:base.scenario_id,communityId:base.community_id}),/scope mismatch/);
await assert.rejects(()=>readReforecastRevisionHistory({...central,fetchJson:async()=>{currentActor=id(90);return [base];}},{scenarioId:base.scenario_id,communityId:base.community_id}),/signed-in account changed/);
console.log('PASS immutable history read rejects wrong community and changed signed-in actor.');

// Optional private, committed revision only. No financial values or private
// evidence are printed or embedded in this repository. No writes/RPC calls.
if(process.env.ATLAS_CELL_HISTORY_PRIVATE_REVISION){
 const privateBase=JSON.parse(fs.readFileSync(process.env.ATLAS_CELL_HISTORY_PRIVATE_REVISION,'utf8')),privateBefore=clone(privateBase),working={actor:privateBase.actor_id,cid:privateBase.community_id,scenarioId:privateBase.scenario_id,record:record(privateBase),edit:clone(privateBase.payload),source:clone(privateBase.source)},states=[collection(privateBase.payload)];
 const started=performance.now(),count=6;for(let i=0;i<count;i++){const row=working.edit.overrides.find(r=>typeof r.amount==='number'&&Number.isFinite(r.amount)&&(!working.source.actuals?.cutoffPeriod||r.period>working.source.actuals.cutoffPeriod));assert(row);working.cellReason='Synthetic same-value history preservation check '+i;updateReforecastCell(working,row.period,row.accountCode,String(row.amount));assert(working.edit.history.at(-1).cellHistory);states.push(collection(working.edit));}
 const elapsedMs=performance.now()-started,newEvents=working.edit.history.slice(privateBase.payload.history.length);let current=collection(working.edit);for(let i=newEvents.length-1;i>=0;i--){const result=reconstruct(newEvents[i],{baseRevision:privateBase,currentState:current,direction:'backward'});assert.deepEqual(result.before,states[i]);assert.deepEqual(result.after,states[i+1]);current=result.before;}
 assert.deepEqual(current,states[0]);assert.deepEqual(working.edit.history.slice(0,privateBase.payload.history.length),privateBase.payload.history);assert.deepEqual(working.edit.suggestionDecisions,privateBase.payload.suggestionDecisions);assert.deepEqual(working.edit.drivers,privateBase.payload.drivers);assert.deepEqual(privateBase,privateBefore);
 const moneyMap=rows=>Object.fromEntries(rows.map(row=>[JSON.stringify([row.period,row.accountCode]),row.amount]));assert.deepEqual(moneyMap(working.edit.overrides),moneyMap(privateBase.payload.overrides));
 const savedPrivate={...privateBase,revision_id:id(20),request_id:id(21),revision:privateBase.revision+1,payload:working.edit};assert.equal(expand(savedPrivate,[privateBase,savedPrivate]).length,working.edit.history.length);
 const proof={kind:'local_private_committed_revision_same_value_edits',liveAcceptance:false,revision:privateBase.revision,priorPayloadCanonicalSha256:sha256(canonicalJson(privateBase.payload)),priorHistoryCount:privateBase.payload.history.length,newCellEvents:count,priorHistoryUnchanged:true,acceptedDriversAndDecisionsUnchanged:true,amountsUnchanged:true,backwardReconstructionPassed:true,elapsedMs:Math.round(elapsedMs)};
 if(process.env.ATLAS_CELL_HISTORY_PGLITE_REPO){const require=createRequire(process.env.ATLAS_CELL_HISTORY_PGLITE_REPO+'/package.json'),{PGlite}=require('@electric-sql/pglite'),db=new PGlite();try{const sizes=await db.query('select octet_length($1::jsonb::text) as before_bytes,octet_length($2::jsonb::text) as after_bytes',[JSON.stringify(privateBase.payload),JSON.stringify(working.edit)]);Object.assign(proof,sizes.rows[0]);assert(proof.after_bytes<2097152,'Six new same-value edit histories must remain under the existing payload limit');}finally{await db.close();}}
 if(process.env.ATLAS_CELL_HISTORY_PRIVATE_RECEIPT)fs.writeFileSync(process.env.ATLAS_CELL_HISTORY_PRIVATE_RECEIPT,JSON.stringify(proof,null,2)+'\n',{flag:'wx'});
 console.log('PASS private committed-revision exact reconstruction and size proof '+JSON.stringify(proof));
}else console.log('SKIP optional private committed revision check (no fixture configured).');
