import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {parseReforecastWorkbook,REFORECAST_PARSER_VERSION} from '../docs/portfolio-operations-dashboard/features/reforecast-intake.mjs';
import {upgradeReforecastParserEvidence,needsReforecastParserRecovery} from '../docs/portfolio-operations-dashboard/features/reforecast-parser-recovery.mjs';
const require=createRequire(import.meta.url),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
const workbook=XLSX.utils.book_new(),sheet={'!ref':'A1:H40'},put=(address,value)=>{sheet[address]={t:typeof value==='number'?'n':'s',v:value};};
put('B19','Entity');put('D19','Source');put('B20','Department');put('D20','Operations');put('B21','Currency');put('D21','USD');
for(const [col,month,scenario]of [['E',8,'Actual'],['F',9,'Plan'],['G',10,'Plan'],['H',11,'Plan']]){put(col+'14',2026);put(col+'15',month);put(col+'16',scenario);put(col+'17','Value');}
put('B36','5120 (Gross Potential Rent (GPR))');put('F36',123.1234);put('G36',0);put('B37','6200 (Expense)');put('F37',5);XLSX.utils.book_append_sheet(workbook,sheet,'Input');
let bytes=XLSX.write(workbook,{type:'array',bookType:'xlsx'}),fileName='nested.xlsx';if(process.env.ATLAS_DORO_WORKBOOK){bytes=fs.readFileSync(process.env.ATLAS_DORO_WORKBOOK);fileName=path.basename(process.env.ATLAS_DORO_WORKBOOK);}
const current=await parseReforecastWorkbook(bytes,{xlsx:XLSX,includeOriginalBytes:true,fileName}),old=structuredClone(current);old.parserVersion='atlas-reforecast-xlsx/2';old.lines=old.lines.filter(line=>line.accountCode!=='5120');old.integrity.fingerprint='old-audit-fingerprint';old.propertyAssignment={confirmed:true};old.importMapping={confirmed:true,selectedLineIds:old.lines.map(line=>line.id)};const before=JSON.stringify(old);
const restored=await upgradeReforecastParserEvidence(old,{xlsx:XLSX,previousUploadId:'immutable-upload',previousAuditId:'immutable-audit'});assert.equal(restored.changed,true);assert.equal(restored.evidence.parserVersion,REFORECAST_PARSER_VERSION);assert.equal(JSON.stringify(old),before,'Old immutable evidence must remain unmodified');assert.equal(restored.evidence.source.sha256,current.source.sha256);assert.deepEqual(restored.evidence.lines,current.lines);assert(!restored.evidence.importMapping);assert(!restored.evidence.propertyAssignment);assert.equal(restored.evidence.parserUpgrade.reviewRequired,true);assert.equal(restored.evidence.parserUpgrade.previousUploadId,'immutable-upload');assert.equal(restored.evidence.parserUpgrade.previousAuditId,'immutable-audit');assert(restored.evidence.parserUpgrade.addedLineIds.length>0);assert.equal(needsReforecastParserRecovery(restored.evidence),false);assert.equal((await upgradeReforecastParserEvidence(current)).changed,false);
const corrupt=structuredClone(old);corrupt.source.sha256='0'.repeat(64);await assert.rejects(()=>upgradeReforecastParserEvidence(corrupt,{xlsx:XLSX}),/hash differs/);
const noBytes=structuredClone(old);delete noBytes.source.originalFile;await assert.rejects(()=>upgradeReforecastParserEvidence(noBytes,{xlsx:XLSX}),/exact original/);assert.equal((await upgradeReforecastParserEvidence(noBytes,{xlsx:XLSX,sourceBytes:bytes})).evidence.source.sha256,current.source.sha256);
if(process.env.ATLAS_DORO_WORKBOOK){const selected=restored.evidence.lines.filter(line=>line.scenario==='Plan'&&['2026-09','2026-10','2026-11','2026-12'].includes(line.period)&&Number.isFinite(line.amount));assert.equal(selected.length,455);assert.equal(selected.filter(line=>line.accountCode==='5120').length,4);const raw=XLSX.read(bytes,{type:'array'});for(const line of selected)assert.equal(line.amount,raw.Sheets[line.sheet][line.address].v,'Recovered value must equal its exact raw source cell');assert.equal(selected.filter(line=>line.amount===0).length,97);console.log('PASS actual Doro parser upgrade recovers all 455 numeric open-month cells, four nested-label GPR cells and 97 explicit zeros from exact original bytes.');}
console.log('PASS parser-version recovery: exact original hash, immutable old evidence retained, new inventory/line recognition, prior upload/audit lineage, no old assignment/mapping authority, missing/corrupt source blocked, current evidence unchanged.');
