// Original approved metric mappings remain usable before a forecast GL registry exists.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{const {db,A,BUDGET,signIn}=await fixture();await db.exec('reset role');
const part=(glCode,factor=1)=>({glCode,factor});const mappings={gpr:[part('5120')],revenue:[part('5120'),part('5220')],netRentalIncome:[part('5120'),part('5220')],expenses:[part('6100'),part('6200')],noi:[part('5120'),part('5220'),part('6100',-1),part('6200',-1)],cashFlow:[part('5120'),part('5220'),part('6100',-1),part('6200',-1),part('8100',-1)],capital:[part('8100')],debt:[part('9999')]};
await db.query("update atlas_approved_budget_versions set payload=payload||jsonb_build_object('metricMappings',$1::jsonb),covered_months='{0,1,2,3,4,5}' where version_id=$2",[JSON.stringify(mappings),BUDGET]);
const later=randomUUID();await db.query("insert into atlas_approved_budget_versions select $1,community_id,calendar_year,status,'{6,7,8,9,10,11}',payload,'Second-half.xlsx','second-half-hash' from atlas_approved_budget_versions where version_id=$2",[later,BUDGET]);
await db.exec(`create function public.atlas_read_finance(p_community_ids uuid[],p_periods text[]) returns table(community_id uuid,period_key text,fiscal_year integer,publication_id uuid,summary jsonb) language sql security definer set search_path='' as $$select b.community_id,p,2026,null::uuid,jsonb_build_object('communityId',b.community_id,'period',p,'budgetVersion',b.version_id,'budgetVersions',jsonb_build_object('2026-01','${BUDGET}','2026-02','${BUDGET}'),'fiscalPeriods',case when p='2026-02' then '["2026-01","2026-02"]'::jsonb else jsonb_build_array(p) end,'revenue',jsonb_build_object('actual',940,'budget',950),'expenses',jsonb_build_object('actual',240,'budget',250),'noi',jsonb_build_object('actual',700,'budget',700),'gpr',jsonb_build_object('actual',1000,'budget',1000),'capital',jsonb_build_object('actual',20,'budget',20),'cashFlow',jsonb_build_object('actual',680,'budget',680),'debt',jsonb_build_object('actual',0,'budget',null),'ytd',jsonb_build_object('expenses',jsonb_build_object('actual',480,'budget',500))) from public.atlas_approved_budget_versions b cross join unnest(p_periods)p where b.community_id=any(p_community_ids) and (right(p,2)::int-1)=any(b.covered_months) and public.atlas_can_access_community(b.community_id)$$`);
await db.exec(fs.readFileSync(path.join(__dirname,'../docs/portfolio-operations-dashboard/centralization/reforecast-builder.sql'),'utf8'));await signIn(1);
const finance=async month=>(await db.query('select summary from atlas_read_finance($1,$2)',[[A],[month]])).rows[0].summary;
const first=await finance('2026-02');assert.equal(first.effectiveBaseline.status,'available');assert.equal(first.effectiveBaseline.versionId,BUDGET);for(const [metric,n]of Object.entries({revenue:950,expenses:250,noi:700,gpr:1000,capital:20,cashFlow:680}))assert.equal(first[metric].activeBaseline,n,metric);assert.equal(first.expenses.variance,-10);assert.equal(first.expenses.status,'favorable');assert.equal(first.expenses.originalBudget,250);assert.equal(first.ytd.expenses.activeBaseline,500);assert.equal(first.ytd.expenses.variance,-20);assert.equal(first.debt.activeBaseline,null,'unknown mapping is not zero');
const second=await finance('2026-07');assert.equal(second.effectiveBaseline.status,'available');assert.equal(second.effectiveBaseline.versionId,later,'exact monthly version, not unrelated year versions');assert.equal(second.revenue.activeBaseline,950);
await db.exec('reset role');await db.query("update atlas_approved_budget_versions set payload=jsonb_set(payload,'{rows,2,monthly,1}','null') where version_id=$1",[BUDGET]);await signIn(1);const missing=await finance('2026-02');assert.equal(missing.expenses.activeBaseline,null);assert.equal(missing.ytd.expenses.activeBaseline,null);assert.equal(missing.expenses.originalBudget,250);
await db.exec('reset role');await db.query("update atlas_approved_budget_versions set payload=jsonb_set(payload,'{rows,2,monthly,1}','0') where version_id=$1",[BUDGET]);await signIn(1);const zero=await finance('2026-02');assert.equal(zero.expenses.activeBaseline,50);assert.equal(zero.ytd.expenses.activeBaseline,300);
await db.close();console.log('PASS original budget canonical metric mappings without registry, exact split-year monthly versions, fiscal YTD, signed variance, unknown vs zero');})().catch(e=>{console.error(e);process.exitCode=1});
