import assert from 'node:assert/strict';
import {reviewedForecastBlankForCell,updateReforecastCell,importReceiptHtml,reforecastBlankSummaryNotice,reforecastRecommendationAvailabilityHtml,undoReforecastSuggestionAction,reforecastRecommendationState} from '../docs/portfolio-operations-dashboard/features/reforecast-ui.mjs';
import {forecastGridHtml} from '../docs/portfolio-operations-dashboard/features/reforecast-builder-ui.mjs';
const period='2026-09',otherPeriod='2026-10',accountCode='6400',actor='current-editor',uploadId='retained-upload';
const review={period,accountCode,confirmed:true,reviewedBy:actor,reviewedAt:'2026-09-29T10:00:00Z',reason:'Retain account in the forecast as editable blank'};
const mapping={version:'registry',confirmed:true,reviewedBy:actor,sourceScenario:'Plan',periods:[period,otherPeriod],selectedLineIds:[],workbookSourcePolicy:{schemaVersion:1,mode:'workbook_exact',blankDisposition:'preserve_null',confirmed:true,reviewedBy:actor,reviewedAt:review.reviewedAt,reason:'Exact workbook source policy',outsideForecastScope:[],reviewedForecastBlanks:[review]}};
const cell={period,accountCode,amount:null,isBlank:true,legitimateBlank:true,disposition:'reviewed_forecast_blank',reviewedForecastBlankConfirmed:true,sourceScopeExclusionConfirmed:false,source:{kind:'reviewed_forecast_blank',workbookSourceAbsent:true,uploadId,auditId:'retained-audit',sourceHash:'a'.repeat(64),sourceScenario:'Plan',mappingVersion:'registry',review}};
const state={actor,cellReason:'Reviewed manual plan amount',edit:{periods:[period,otherPeriod],uploadId,importMapping:mapping,overrides:[],drivers:[],history:[],suggestionDecisions:[]},record:null,source:{actuals:{cutoffPeriod:'2026-08'},workbookReviewedForecastBlankCells:[cell]},dirty:false};
const policyBefore=JSON.stringify(mapping),sourceBefore=JSON.stringify(state.source);
assert.equal(reviewedForecastBlankForCell(state,period,accountCode),cell);
updateReforecastCell(state,period,accountCode,'0');assert.equal(state.edit.overrides[0].amount,0);assert.equal(state.edit.overrides[0].source.kind,'user');assert.equal(state.edit.overrides[0].source.workbookSourceAbsent,true);assert.equal(state.edit.overrides[0].ownerId,actor);assert.equal(state.edit.overrides[0].source.reviewedForecastBlank.review.reason,review.reason);
state.cellReason='';assert.throws(()=>updateReforecastCell(state,period,accountCode,''),/reason/);assert.equal(state.edit.overrides[0].amount,0);
state.cellReason='Restore intentional blank until plan is reviewed';updateReforecastCell(state,period,accountCode,'');assert.equal(state.edit.overrides.length,0);assert.equal(state.edit.history.at(-1).action,'clear_reviewed_forecast_blank');assert.equal(state.edit.history.at(-1).after,null);
state.edit.drivers=[{id:'weighted-amount',operation:'amount',recommendationId:'suggestion',accountCodes:[accountCode,'6500'],periods:[period,otherPeriod],value:75,evidence:{method:'weighted_governed_actual_amount'}},{id:'unrelated',operation:'percent_change',accountCodes:['9000'],periods:[period],value:.1}];state.edit.suggestionDecisions=[{id:'suggestion',status:'accepted'}];const decisions=JSON.stringify(state.edit.suggestionDecisions);
updateReforecastCell(state,period,accountCode,'');
const targets=state.edit.drivers.filter(row=>row.recommendationId).flatMap(row=>row.periods.flatMap(month=>row.accountCodes.map(code=>month+'|'+code))).sort();assert.deepEqual(targets,[period+'|6500',otherPeriod+'|6400',otherPeriod+'|6500'].sort());assert.equal(state.edit.drivers.find(row=>row.id==='unrelated').value,.1);assert.equal(JSON.stringify(state.edit.suggestionDecisions),decisions);assert.equal(state.edit.history.at(-1).workingBefore.drivers.length,2);
assert.equal(JSON.stringify(mapping),policyBefore);assert.equal(JSON.stringify(state.source),sourceBefore);
assert.throws(()=>updateReforecastCell({...state,source:{...state.source,lockedPeriods:[period]}},period,accountCode,'99'),/cannot be edited/);
assert.throws(()=>updateReforecastCell({...state,record:{head:{status:'locked'}}},period,accountCode,'99'),/not editable/);
assert.equal(reviewedForecastBlankForCell({...state,source:{...state.source,workbookReviewedForecastBlankCells:[cell,cell]}},period,accountCode),null);
assert.equal(reviewedForecastBlankForCell({...state,edit:{...state.edit,importMapping:{...mapping,reviewedBy:'forged'}}},period,accountCode),null);
const row={...cell,forecast:null,sourceKind:'forecast',originalBudget:100,selectedBaseline:100};const grid=forecastGridHtml({edit:{},glFilters:{}},{lines:[row]});assert.match(grid,/Reviewed intentional blank; no workbook GL row/);assert.match(grid,/Intentional blank \/ editable/);assert.match(grid,/actuals load separately/i);assert(!/data-gl-cell[^>]*disabled/.test(grid));assert(/data-gl-cell[^>]*disabled/.test(forecastGridHtml({edit:{},glFilters:{}},{lines:[row]},{locked:true})));
assert.match(importReceiptHtml({mapping,importedCells:[],excludedRows:[]},{lines:[row]}),/1 reviewed intentional forecast blanks/);
console.log('PASS intentional blank editing: explicit zero, user provenance, reasoned null restoration, recommendation-target cross-product isolation, source/history preservation, locks and clear receipt/grid labels.');

for(const savedValue of [null,0,75]){
 const batch=structuredClone(state);batch.record={head:{status:'working_draft',revision:9},snapshot:{lines:[{...row,forecast:savedValue}]}};batch.edit.overrides=[];batch.edit.drivers=[];batch.edit.history=[];batch.cellReason='Review two edits before the next atomic save';
 updateReforecastCell(batch,period,accountCode,'110');assert.equal(batch.edit.overrides[0].before,savedValue);
 updateReforecastCell(batch,period,accountCode,'220');assert.equal(batch.edit.overrides[0].before,savedValue,'Override comparison must stay anchored to the saved snapshot across unsaved typing');assert.equal(batch.edit.history.at(-1).priorWorkingValue,110);assert.equal(batch.edit.history.at(-1).savedBeforeValue,savedValue);assert.equal(batch.edit.history.at(-1).before[0].amount,110,'Working intermediate history remains separate');
 updateReforecastCell(batch,period,accountCode,'');const clear=batch.edit.history.at(-1);assert.equal(clear.action,'clear_reviewed_forecast_blank');assert.equal(clear.before,savedValue);assert.equal(clear.after,null);assert.equal(clear.priorWorkingValue,220);assert.equal(clear.actor,actor);assert.equal(clear.period,period);assert.equal(clear.accountCode,accountCode);assert.equal(clear.reason,batch.cellReason);assert(Number.isFinite(Date.parse(clear.timestamp)));assert.equal(clear.workingBefore.overrides[0].amount,220);assert.equal(batch.edit.overrides.length,0);assert.equal(batch.record.snapshot.lines[0].forecast,savedValue);
}
const missingSaved={...state,record:{head:{status:'working_draft'},snapshot:{lines:[]}}};assert.throws(()=>updateReforecastCell(missingSaved,period,accountCode,'10'),/exact saved cell is unavailable/);
const splitSaved=structuredClone(state);splitSaved.record={head:{status:'working_draft'},snapshot:{lines:[{...row,forecast:75}]}};splitSaved.edit.drivers=[{id:'accepted',operation:'amount',recommendationId:'accepted-amount',periods:[period,otherPeriod],accountCodes:[accountCode],value:75,evidence:{method:'weighted_governed_actual_amount'}}];updateReforecastCell(splitSaved,period,accountCode,'');assert.equal(splitSaved.edit.history.at(-1).before,75);assert.equal(splitSaved.edit.history.at(-1).after,null);assert.deepEqual(splitSaved.edit.drivers[0].periods,[otherPeriod]);
console.log('PASS saved-snapshot edit anchoring: repeated unsaved numeric edits and clear audit retain exact saved null/zero/amount, working intermediates, and accepted-driver target history.');

const summarySnapshot={identity:{workbookSourcePolicy:mapping.workbookSourcePolicy},lines:[row,{...row,period:otherPeriod,source:{...row.source,review:{...row.source.review,period:otherPeriod}}}]};assert.match(reforecastBlankSummaryNotice(summarySnapshot),/2 reviewed intentional forecast blanks/);assert.match(reforecastBlankSummaryNotice(summarySnapshot),/Totals cover entered forecast values\. Blank cells are not zeros/);assert.match(reforecastBlankSummaryNotice({...summarySnapshot,lines:[row,{...row,period:otherPeriod,forecast:75}]}),/1 reviewed intentional forecast blanks/);assert.equal(reforecastBlankSummaryNotice({identity:{},lines:[{period,accountCode,forecast:null}]}),'','Older snapshots are not relabeled');assert.match(reforecastBlankSummaryNotice({identity:{},lines:[row]}),/1 reviewed intentional forecast blanks/,'Inherited reviewed blanks retain the headline disclosure');
console.log('PASS headline totals disclose current intentional blank count, entered-value totals, no zero substitution and separate actuals; populated cells reduce the count.');

const inheritedCid='10000000-0000-0000-0000-000000000002',approvedVersion={period,sourceType:'approved_reforecast',publicationId:'approved-publication',versionId:'approved-revision',contentHash:'approved-fingerprint'},wrapper={sourceType:'approved_reforecast',publicationId:approvedVersion.publicationId,versionId:approvedVersion.versionId,revisionId:approvedVersion.versionId,contentHash:approvedVersion.contentHash,priorSource:cell.source};
const inheritedState=()=>({actor,cellReason:'Reviewed inherited blank planning edit',cid:inheritedCid,source:{communityId:inheritedCid,actuals:{cutoffPeriod:'2026-08'},baseline:{sourceType:'approved_reforecast',periodVersions:[approvedVersion],lines:[{...cell,source:wrapper,workbookSourceAmount:null,workbookSourceDisposition:'source_absent',workbookSource:cell.source}]}},edit:{periods:[period],baselineType:'approved_reforecast',baselinePublicationIds:[approvedVersion.publicationId],overrides:[],drivers:[],history:[]},record:{head:{status:'working_draft',community_id:inheritedCid},snapshot:{lines:[{...row,forecast:null}]}},dirty:false});
for(const shape of ['wrapped','direct']){const inherited=inheritedState();if(shape==='direct')inherited.source.baseline.lines[0]={...cell,baselineLineage:approvedVersion,workbookSourceAmount:null,workbookSourceDisposition:'source_absent',workbookSource:cell.source};assert.equal(reviewedForecastBlankForCell(inherited,period,accountCode).source.kind,'reviewed_forecast_blank');updateReforecastCell(inherited,period,accountCode,'25');assert.equal(inherited.edit.overrides[0].source.kind,'user');assert.equal(inherited.edit.overrides[0].before,null);updateReforecastCell(inherited,period,accountCode,'');assert.equal(inherited.edit.overrides.length,0);assert.equal(inherited.edit.history.at(-1).action,'clear_reviewed_forecast_blank');assert.equal(inherited.edit.history.at(-1).after,null);assert.equal(reviewedForecastBlankForCell(inherited,period,accountCode).amount,null);}
for(const mutate of [s=>s.source.communityId='other',s=>s.edit.baselinePublicationIds=['other'],s=>s.source.baseline.periodVersions.push({...approvedVersion}),s=>s.source.baseline.lines.push({...cell,source:wrapper}),s=>s.source.baseline.lines[0].source={...wrapper,contentHash:'wrong'},s=>s.source.baseline.lines[0].source={...wrapper,versionId:'wrong'},s=>s.source.baseline.lines[0].source={...wrapper,priorSource:{...cell.source,review:{...review,period:otherPeriod}}}]){const inherited=structuredClone(inheritedState());mutate(inherited);assert.equal(reviewedForecastBlankForCell(inherited,period,accountCode),null);}
for(const driver of [{id:'direct-amount',operation:'amount',value:10,periods:[period],accountCodes:[accountCode]},{id:'registry-amount',type:'payroll',operation:'amount',value:10},{id:'percent-needs-base',operation:'percent_change',value:.1,periods:[period],accountCodes:[accountCode]}]){const controlled=inheritedState();controlled.source.registry={driverMappings:{payroll:[accountCode]}};controlled.edit.drivers=[driver];controlled.edit.overrides=[{period,accountCode,amount:20,reason:controlled.cellReason,confirmed:true}];const before=JSON.stringify(controlled);assert.throws(()=>updateReforecastCell(controlled,period,accountCode,''),/controlling driver first/);assert.equal(JSON.stringify(controlled),before,'A refused clear cannot delete a driver, override or history');}
const unrelated=inheritedState();unrelated.edit.drivers=[{id:'other-month',operation:'amount',value:10,periods:[otherPeriod],accountCodes:[accountCode]},{id:'other-account',operation:'amount',value:10,periods:[period],accountCodes:['9999']}];const unrelatedDrivers=JSON.stringify(unrelated.edit.drivers);updateReforecastCell(unrelated,period,accountCode,'');assert.equal(JSON.stringify(unrelated.edit.drivers),unrelatedDrivers);
const chainSnapshot={...summarySnapshot,identity:{...summarySnapshot.identity,mappingRegistryVersion:'registry'},sunsetRelationships:[{accountCode:'6300',successorAccountCode:accountCode,approved:true,mappingRegistryVersion:'registry',retiredAfter:'2026-08'}]};assert.match(reforecastRecommendationAvailabilityHtml(chainSnapshot),/Historical account mapping needs review; enter a forecast amount directly/);assert(!reforecastRecommendationAvailabilityHtml(chainSnapshot).includes('successor_history_review_required'));
console.log('PASS approved-baseline blank edit/clear binding, malformed ancestry rejection, controlling-driver clear refusal without mutations, unrelated-driver preservation and friendly historical mapping review notice.');

const {applyRecommendations}=await import('../docs/portfolio-operations-dashboard/features/reforecast-engine.mjs');
const amountProposal={id:'two-actor-amount',operation:'amount',proposedValue:125,source:'synthetic-governed-history',cutoff:'2026-08',driver:{id:'historical-blank-'+accountCode,operation:'amount',value:125,periods:[period,otherPeriod],accountCodes:[accountCode],evidence:{method:'weighted_governed_actual_amount'},reason:'Original governed amount proposal'}};
function twoActorAccepted(){const s=structuredClone(state),reviewNext={...review,period:otherPeriod};s.actor='user-b';s.cellReason='Clear only this month after user B review';s.recommendationReason='Undo accepted amounts after user B review';s.record={head:{status:'working_draft',revision:12},snapshot:{lines:[{...row,forecast:125},{...row,period:otherPeriod,forecast:125}]}};s.edit={periods:[period,otherPeriod],uploadId,importMapping:{...mapping,workbookSourcePolicy:{...mapping.workbookSourcePolicy,reviewedForecastBlanks:[review,reviewNext]}},drivers:[],overrides:[],history:[],suggestionDecisions:[]};s.source.workbookReviewedForecastBlankCells=[cell,{...cell,period:otherPeriod,source:{...cell.source,review:reviewNext}}];s.edit=applyRecommendations(s.edit,[amountProposal],{ids:[amountProposal.id],action:'accept',actor:'user-a',timestamp:'2026-09-29T09:00:00Z',versionId:'accepted-v1',driverVersion:'accepted-driver-v1',reason:'User A accepted governed historical amount'});return s;}
const partialClear=twoActorAccepted(),acceptance=structuredClone(partialClear.edit.suggestionDecisions[0]),acceptedDriver=structuredClone(partialClear.edit.drivers[0]);updateReforecastCell(partialClear,period,accountCode,'');assert.deepEqual(partialClear.edit.suggestionDecisions[0],acceptance);assert.deepEqual(partialClear.edit.drivers[0],{...acceptedDriver,periods:[otherPeriod]});assert.equal(partialClear.edit.drivers[0].ownerId,'user-a');assert.equal(partialClear.edit.drivers[0].recommendationReview.reviewedBy,'user-a');assert.equal(partialClear.edit.history.at(-1).actor,'user-b');assert.equal(partialClear.edit.history.at(-1).before,125);assert.equal(partialClear.edit.history.at(-1).after,null);
const undoState=twoActorAccepted(),undoBefore=JSON.stringify(undoState.edit),undone=undoReforecastSuggestionAction(undoState);assert.equal(JSON.stringify(undoState.edit),undoBefore,'Undo preparation does not mutate the active draft');assert.equal(undone.drivers.length,0);assert.deepEqual(undone.suggestionDecisions,undoState.edit.suggestionDecisions,'Historical amount acceptance remains immutable after undo');const clears=undone.history.filter(event=>event.action==='clear_reviewed_forecast_blank');assert.equal(clears.length,2);assert(clears.every(event=>event.actor==='user-b'&&event.before===125&&event.after===null&&event.reason===undoState.recommendationReason));assert.deepEqual(clears.map(event=>event.period).sort(),[period,otherPeriod]);const undoEvent=undone.history.find(event=>event.action==='undo');assert.equal(undoEvent.actor,'user-b');assert.deepEqual(undoEvent.afterDecisions,undoState.edit.suggestionDecisions);assert.equal(undone.history[0].actor,'user-a');
for(const mutate of [s=>s.recommendationReason='',s=>s.source.lockedPeriods=[period],s=>s.edit.overrides.push({period,accountCode,amount:200})]){const s=twoActorAccepted();mutate(s);const before=JSON.stringify(s);assert.throws(()=>undoReforecastSuggestionAction(s));assert.equal(JSON.stringify(s),before);}
const ratioState=twoActorAccepted();ratioState.edit=applyRecommendations({periods:[period],drivers:[],history:[],suggestionDecisions:[]},[{...amountProposal,id:'ordinary-ratio',operation:'percent_change',proposedValue:.1,driver:{id:'ratio',operation:'percent_change',value:.1,periods:[period],accountCodes:[accountCode]}}],{ids:['ordinary-ratio'],action:'accept',actor:'user-a',timestamp:'2026-09-29T09:00:00Z',versionId:'ratio-v1',driverVersion:'ratio-driver-v1'});assert.equal(undoReforecastSuggestionAction(ratioState).suggestionDecisions.length,0,'Existing ordinary ratio undo behavior is unchanged');
console.log('PASS two-actor partial clear and historical amount undo preserve original acceptance/owner/review; new clear audits use clearing actor and saved values, while ordinary ratio undo remains unchanged.');

const offered={...amountProposal,periods:[period,otherPeriod],accountCodes:[accountCode]};assert.equal(reforecastRecommendationState(undoState.edit,offered).actionable,false);assert.equal(reforecastRecommendationState(undone,offered).actionable,true,'An explicit undo restores the same proposal ID to reviewable status');const reaccepted=applyRecommendations(undone,[offered],{ids:[offered.id],action:'accept',actor:'user-b',timestamp:'2026-09-29T10:00:00Z',versionId:'reaccepted-v2',driverVersion:'reaccepted-driver-v2',reason:'User B reviewed the same proposal again'});assert.equal(reaccepted.suggestionDecisions.length,2);assert.deepEqual(reaccepted.suggestionDecisions[0],undoState.edit.suggestionDecisions[0]);assert.equal(reaccepted.suggestionDecisions[1].actor,'user-b');assert.equal(reaccepted.drivers[0].ownerId,'user-b');assert.equal(reforecastRecommendationState(reaccepted,offered).actionable,false);
const allCleared=twoActorAccepted();updateReforecastCell(allCleared,period,accountCode,'');updateReforecastCell(allCleared,otherPeriod,accountCode,'');assert.equal(reforecastRecommendationState(allCleared.edit,offered).actionable,true);assert.equal(allCleared.edit.suggestionDecisions.length,1);const unexplained=twoActorAccepted();unexplained.edit.drivers=[];assert.equal(reforecastRecommendationState(unexplained.edit,offered).actionable,false,'Missing driver alone is not permission to repeat an acceptance');
const rejectedAfterClear=applyRecommendations(undone,[offered],{ids:[offered.id],action:'reject',actor:'user-b',timestamp:'2026-09-29T10:00:00Z',versionId:'reject-v2',driverVersion:'reject-driver-v2',reason:'Reject repeated suggestion'});assert.equal(reforecastRecommendationState(rejectedAfterClear,offered).actionable,false);const undoRejection=undoReforecastSuggestionAction({...undoState,edit:rejectedAfterClear});assert.equal(reforecastRecommendationState(undoRejection,offered).actionable,true);assert.deepEqual(undoRejection.suggestionDecisions,undone.suggestionDecisions);
console.log('PASS same-ID amount reacceptance is explicit after clear/undo, preserves prior accepted event, records fresh actor/time, and keeps rejection blocked until explicit undo.');
