const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{
 const {parseSavedStrMonthlyProgramme,prepareSavedStrMonthlyContribution}=await import('../docs/portfolio-operations-dashboard/features/reforecast-str-saved-programme.mjs');
 const {prepareStrRegistryExtension}=await import('../docs/portfolio-operations-dashboard/features/reforecast-str-registry-extension.mjs');
 const {pairedForecastReports,communityForecastWorkbook,communityForecastPdf}=await import('../docs/portfolio-operations-dashboard/features/reforecast-report.mjs');
 const {verifyOfficialExports}=await import('./publication-export-acceptance.mjs'),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
 const {savedStrProgrammeDraft}=await import('../docs/portfolio-operations-dashboard/features/reforecast-str-saved-programme-ui.mjs');
 const {db,A,B,BUDGET,signIn}=await fixture(),owner='00000000-0000-0000-0000-000000000001',read=name=>fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8');
 const call=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
 await db.exec('reset role');await db.exec(read('20260924121641_planning_cell_workbook_integrity_governance.sql'));await db.exec(read('20260924121647_immutable_workbook_audits_and_monthly_governance.sql').split('alter function atlas_private.finance_intake_validation')[0]);
 for(const file of ['20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql','20260925020222_reforecast_saved_json_str_programme.sql'])await db.exec(read(file));
 const periods=['2026-09','2026-10','2026-11','2026-12'];
 const annual=n=>[0,0,0,0,0,0,0,0,0,n,n,n],programmeId='synthetic-rise',propertyId='synthetic-property';
 const synthetic={formatVersion:1,savedAt:'2026-09-25T01:00:00Z',state:{properties:[{id:propertyId,units:[{id:'private-group',name:'Private group'}]}],strPrograms:[{id:programmeId,propertyId,operatorId:'rise_internal',config:{propertyId,programmeId,unitPicks:[{groupId:'private-group',units:4}],unitRamp:{2026:[0,0,0,0,0,0,0,0,0,1,2,4]}},byYear:{2026:{totalRevenue:300.01,expense:30,furnishCapex:1500,uplift:240.02}}}],lines:[['income','5144','income',100],['displaced','5220','contra_income',-10],['utility','6200','expense',10],['capital','1504','capital',500]].map(([id,gl,nature,n])=>({id,gl,nature,name:id,propertyId,strProgramId:programmeId,yearData:{2026:annual(n)}}))}};
 let source=await parseSavedStrMonthlyProgramme(JSON.stringify(synthetic),{fileName:'Synthetic saved STR.json',propertyId,programmeId,periods});
 if(process.env.ATLAS_SAVED_STR_JSON){source=await parseSavedStrMonthlyProgramme(fs.readFileSync(process.env.ATLAS_SAVED_STR_JSON),{fileName:path.basename(process.env.ATLAS_SAVED_STR_JSON),propertyId:'DORO',programmeId:'DORO-STR-DORORESIDENCES',periods});}
 const originalAccounts=[['5120','income'],['5220','contra_income'],['6100','expense'],['6200','expense'],['8100','capital']].map(([accountCode,nature])=>({accountCode,nature,category:accountCode,placement:nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'}));
 const accounts=[...originalAccounts];for(const row of source.lineEvidence){if(!accounts.some(a=>a.accountCode===row.line.gl))accounts.push({accountCode:row.line.gl,nature:row.line.nature,category:row.line.gl,placement:row.line.nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'});}
 const extensionAccounts=process.env.ATLAS_STR_UNCHANGED?[]:accounts.filter(a=>!originalAccounts.some(b=>b.accountCode===a.accountCode)).slice(0,8),extensionCodes=new Set(extensionAccounts.map(a=>a.accountCode)),parentAccounts=accounts.filter(a=>!extensionCodes.has(a.accountCode));
 const existing=new Set(originalAccounts.map(a=>a.accountCode));await db.query("update atlas_approved_budget_versions set payload=jsonb_set(payload,'{rows}',payload->'rows'||$1::jsonb) where version_id=$2",[parentAccounts.filter(a=>!existing.has(a.accountCode)).map(a=>({glCode:a.accountCode,monthly:Array(12).fill(a.accountCode==='5144'?100.000123:0)})),BUDGET]);await signIn(1);
 let registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),{accounts:parentAccounts,driverMappings:{},reason:'Reviewed source GL classifications',effectiveDate:'2026-01-01'}]);
 const reviewedAt='2026-09-25T01:00:00Z',payload={name:'Conventional saved-source parent',model:'conventional',governanceSchemaVersion:2,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:'Conventional saved-source parent',reviewedBy:owner,reviewedAt},periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:owner,reviewerId:owner,drivers:[],overrides:[],reason:'Approved exact Conventional parent'};
 const save=(p,id=randomUUID(),rev=0,action='save_draft',request=randomUUID())=>call('atlas_save_reforecast_scenario',[A,id,rev,request,action,p]);
 const advance=async record=>{for(const action of ['reconcile','ready','submit','approve_lock'])record=await save(record.revision.payload,record.head.scenario_id,record.head.revision,action);return record;};
 const conventional=await advance(await save(payload)),parent=await call('atlas_read_reforecast_publication',[conventional.publication.publication_id]),activeBefore=await call('atlas_read_active_reforecast',[[A],periods]);
 const parentRegistry=registry,context=await call('atlas_read_reforecast_str_mapping_context',[A,parent.publicationId]);assert.equal(context.parentRegistry.version,parentRegistry.version_id);assert.equal(context.currentRegistryVersionId,parentRegistry.version_id);assert.deepEqual(context.workbookAccountEvidence,[]);
 if(extensionAccounts.length){
 const extensionPayload=prepareStrRegistryExtension(context.parentRegistry,extensionAccounts.map(a=>{const line=source.lineEvidence.find(l=>l.line.gl===a.accountCode).line;return {...a,name:line.name,sourceLineId:line.id,confirmed:true,reason:'Explicit canonical account and absent parent review'};}),{reason:'Isolated prospective STR accounts only',effectiveDate:'2026-09-01',actor:owner,source,parentPublicationId:parent.publicationId});delete extensionPayload.contentHash;
 const extensionRequest=randomUUID(),extensionArgs=[A,parent.publicationId,context.currentRegistryVersionId,extensionRequest,extensionPayload];registry=await call('atlas_save_reforecast_str_registry_extension',extensionArgs);assert.equal(registry.previous_version_id,parentRegistry.version_id);assert.deepEqual(await call('atlas_save_reforecast_str_registry_extension',extensionArgs),registry);
 const registryHead=async()=>(await db.query('select version_id from atlas_reforecast_registry_heads where community_id=$1',[A])).rows[0].version_id;assert.equal(await registryHead(),parentRegistry.version_id,'Extension does not activate a different operating registry');assert.deepEqual(await call('atlas_read_active_reforecast',[[A],periods]),activeBefore);
 const mutateParent=structuredClone(extensionPayload);mutateParent.accounts[0].category='Changed inherited classification';await assert.rejects(()=>call('atlas_save_reforecast_str_registry_extension',[A,parent.publicationId,context.currentRegistryVersionId,randomUUID(),mutateParent]),/inherited registry relationships/);
 const mutateRelationships=structuredClone(extensionPayload);mutateRelationships.relationships=[];mutateRelationships.relationships.push({relationship:'separate_income',accountCode:'5120'});await assert.rejects(()=>call('atlas_save_reforecast_str_registry_extension',[A,parent.publicationId,context.currentRegistryVersionId,randomUUID(),mutateRelationships]),/inherited registry relationships/);
 await assert.rejects(()=>call('atlas_save_reforecast_str_registry_extension',[A,parent.publicationId,randomUUID(),randomUUID(),extensionPayload]),/changed in another session/);
 }
 const mappings=source.lineEvidence.map(({line})=>({sourceLineId:line.id,sourceGL:line.gl,accountCode:line.gl,confirmed:true,reason:'Reviewed exact source GL label and classification',...(extensionCodes.has(line.gl)?{parentDisposition:'no_parent_publication_row'}:{})}));
 const review=await prepareSavedStrMonthlyContribution(source,{publication:parent,registry:{...registry.payload,version:registry.version_id},parentRegistry:{...parentRegistry.payload,version:parentRegistry.version_id},mappings,actor:owner,reason:'Reviewed saved signed monthly programme',reviewedAt,allowHelloLandingGl5144:true,rollupReview:{confirmed:true,sourceHash:source.sourceHash,authority:'saved_monthly_gl_cells',reason:'Preserve exact saved monthly cells and disclosed summary differences'}});
 assert.equal(review.ready,true,JSON.stringify(review.blockers));
 const request=randomUUID(),args=[A,request,source,review];
 assert.equal(await call('atlas_read_reforecast_str_json_source_receipt',[A,request]),null);
 const receipt=await call('atlas_save_reforecast_str_json_source',args);assert.deepEqual(receipt.review,review);assert.deepEqual(receipt.registry_extension.addedAccountCodes,[...extensionCodes].sort());assert.deepEqual(await call('atlas_save_reforecast_str_json_source',args),receipt);assert.deepEqual(await call('atlas_read_reforecast_str_json_source_receipt',[A,request]),receipt);
 await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,request,source,{...review,reason:'Changed request'}]),/request ID reused/);
 const corrupted=structuredClone(source);corrupted.cells[0].sourceAmount=999;await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),corrupted,review]),/does not exactly reproduce/);
 await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[B,randomUUID(),source,review]),/Conventional parent/);
 await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,{...review,allowHelloLandingGl5144:false}]),/5144/);
 await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,{...review,rollupReview:null}]),/summary differences/);
 const noMappingReason=structuredClone(review);delete noMappingReason.mappings[0].reason;await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,noMappingReason]),/confirmed mapping/);
 const reversed=structuredClone(review);reversed.mappings[0].signMultiplier=-1;await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,reversed]),/preserve each saved signed/);
 const changedMapping=structuredClone(review);changedMapping.mappings[0].accountCode='8100';await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,changedMapping]),/financial classification|added STR account requires/);
 const wrongParent=structuredClone(review);wrongParent.parentPublication.contentHash='different';await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,wrongParent]),/ancestry/);
 const changedBytes=structuredClone(source);changedBytes.originalFile.data=Buffer.from('{}').toString('base64');await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),changedBytes,review]),/hash or size mismatch/);
 let draft=savedStrProgrammeDraft(source,review,receipt,{publication:parent,actor:owner});draft.reviewerId=owner;
 let record=await save(draft);assert.equal(record.snapshot.completeness.blockerCount,0,JSON.stringify(record.snapshot.diagnostics));assert.deepEqual(record.source.savedStrSourceReceipts[0],receipt);
 for(const c of review.cells)assert.equal(record.snapshot.lines.find(l=>l.period===c.period&&l.accountCode===c.accountCode).forecast,c.combinedForecast);
 const alternateInputs=structuredClone(record.revision.payload);alternateInputs.strStreams[0].units=[{id:'invented'}];await assert.rejects(()=>save(alternateInputs,record.head.scenario_id,record.head.revision),/without alternate rates or units/);
 const tampered=structuredClone(record.revision.payload);tampered.overrides[0].amount+=1;await assert.rejects(()=>save(tampered,record.head.scenario_id,record.head.revision),/override differs/);
 record=await advance(record);const publication=await call('atlas_read_reforecast_publication',[record.publication.publication_id]);assert.equal(publication.verified,true);assert.equal(publication.snapshot.savedStrProgramme.sourceHash,source.sourceHash);assert.equal(publication.snapshot.savedStrProgramme.groupAllocationCount,source.groupAllocations.length);assert.deepEqual(publication.snapshot.savedStrProgramme.sourceRollupDifferences,source.sourceRollupDifferences);assert.equal(publication.activePeriods.length,0);assert.deepEqual(publication.snapshot.savedStrProgramme.registryExtension,receipt.registry_extension);const pair=pairedForecastReports(parent,publication);assert(pair);for(const code of extensionCodes){for(const period of periods){const line=publication.snapshot.lines.find(l=>l.accountCode===code&&l.period===period);assert.equal(line.originalBudget,null);assert.equal(line.selectedBaseline,null);assert.equal(line.baselineDisposition.parentDisposition,'no_parent_publication_row');assert.equal(line.baselineDisposition.sourceReceiptId,receipt.source_receipt_id);}}assert.equal((await db.query('select version_id from atlas_reforecast_registry_heads where community_id=$1',[A])).rows[0].version_id,parentRegistry.version_id);
 const exportProof=await verifyOfficialExports({publication,xlsxBytes:XLSX.write(communityForecastWorkbook(publication,XLSX,pair.reportOptions),{type:'buffer',bookType:'xlsx'}),pdfBytes:await communityForecastPdf(publication,pair.reportOptions),screenRows:pair.withStr.rows,screenMonthly:pair.withStr.monthly,options:pair.reportOptions});assert.equal(exportProof.xlsxSheets,11);assert(exportProof.monthlyChecks.every(month=>month.basisChecks.length===3&&month.basisChecks.every(check=>check.independentGLReconciliation&&check.metrics===11)),'Every retained monthly metric reconciles against its source GLs or unavailable future actuals');
 assert.deepEqual(await call('atlas_read_active_reforecast',[[A],periods]),activeBefore);
 assert.deepEqual(await call('atlas_read_reforecast_publication',[parent.publicationId]),parent);
 await signIn(5);assert.deepEqual(await call('atlas_read_reforecast_str_json_source_receipt',[A,request]),receipt);assert.deepEqual(await call('atlas_read_reforecast_publication',[publication.publicationId]),publication);
 await signIn(4);await assert.rejects(()=>call('atlas_read_reforecast_str_mapping_context',[A,parent.publicationId]),/access denied/);await assert.rejects(()=>call('atlas_save_reforecast_str_registry_extension',[A,parent.publicationId,registry.version_id,randomUUID(),{}]),/required/);await assert.rejects(()=>call('atlas_read_reforecast_str_json_source_receipt',[A,request]),/access denied/);await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',args),/required/);assert.equal((await db.query('select * from atlas_reforecast_str_json_sources')).rows.length,0);
 // A later governed close must prohibit a new use of the old approved source;
 // the old request remains a historical read receipt and never creates a write.
 await db.exec('reset role');
 const cutoffOnly={...record.source,actuals:{...record.source.actuals,cutoffPeriod:'2026-09',latestFullClosePeriod:null}};
 await assert.rejects(()=>db.query('select atlas_private.reforecast_saved_str_receipt($1,$2)',[cutoffOnly,draft]),/governed actual or locked/);
 const latestOnly={...record.source,actuals:{...record.source.actuals,cutoffPeriod:null,latestFullClosePeriod:'2026-09'}};
 await assert.rejects(()=>db.query('select atlas_private.reforecast_saved_str_receipt($1,$2)',[latestOnly,draft]),/governed actual or locked/);
 const closeId=randomUUID();await db.query("insert into atlas_financial_close_versions values($1,$2,'2026-09','new-governed-source',now(),$3)",[closeId,A,{totalIncome:10,operatingExpenses:3,netOperatingIncome:7}]);await db.query("insert into atlas_financial_close_heads values($1,'2026-09','accrual',$2)",[A,closeId]);
 const revisionCount=(await db.query('select count(*)::int n from atlas_reforecast_revisions')).rows[0].n;await signIn(1);
 await assert.rejects(()=>save(draft),/Locked month inputs|governed actual|eligible open/);
 await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,review]),/eligible open/);
 assert.deepEqual(await call('atlas_save_reforecast_str_json_source',args),receipt,'Lost-response replay returns only the pre-existing immutable source receipt');
 assert.equal((await db.query('select count(*)::int n from atlas_reforecast_revisions')).rows[0].n,revisionCount);
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from atlas_reforecast_str_json_sources')).rows[0].n,1);await assert.rejects(()=>db.exec("update atlas_reforecast_str_json_sources set evidence='{}'"),/immutable/);const grants=(await db.query("select p.proname,has_function_privilege('anon',p.oid,'EXECUTE') anon_exec,has_function_privilege('authenticated',p.oid,'EXECUTE') auth_exec,n.nspname,p.prosecdef from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like '%saved_str%' or p.proname like '%str_json_source%' or p.proname like '%str_registry_extension%' or p.proname like '%str_mapping_context%'")).rows;for(const grant of grants){assert.equal(grant.anon_exec,false,grant.proname);if(grant.nspname==='public')assert.equal(grant.prosecdef,false,grant.proname);}
 await db.exec('set role anon');await assert.rejects(()=>call('atlas_read_reforecast_str_json_source_receipt',[A,request]),/permission denied/);
 const proof={status:'PASS',kind:process.env.ATLAS_SAVED_STR_JSON?'actual saved JSON isolated DB; not production acceptance':'synthetic saved JSON DB',sourceHash:source.sourceHash,sourceGLs:source.lineEvidence.length,cells:review.cells.length,zeros:review.cells.filter(c=>c.amount===0).length,negative:review.cells.filter(c=>c.amount<0).length,groupAllocations:source.groupAllocations.length,unitRamp:source.unitRamp.map(m=>({period:m.period,units:m.units})),rollupDifferences:source.sourceRollupDifferences,approved:true,conventionalUnchanged:true,operatingRegistryUnchanged:true,addedAccounts:extensionCodes.size,pairedReportsVerified:true,officialExportsReopened:true,exportSheets:exportProof.xlsxSheets,exportMonthlyMetricChecks:exportProof.monthlyChecks.reduce((total,month)=>total+month.basisChecks.reduce((count,check)=>count+(check.metrics||0),0),0),monthlyGLReconciliationComplete:exportProof.monthlyGLReconciliationComplete,draftBytes:Buffer.byteLength(JSON.stringify(draft))};if(process.env.ATLAS_SAVED_STR_JSON){const proofPath=path.join(__dirname,'../output/doro-saved-str-extension-db.json');fs.mkdirSync(path.dirname(proofPath),{recursive:true});fs.writeFileSync(proofPath,JSON.stringify(proof,null,2)+'\n');}console.log(JSON.stringify(proof));await db.close();
})().catch(error=>{console.error(error);process.exitCode=1});
