import assert from 'node:assert/strict';import fs from 'node:fs';import {randomUUID,createHash} from 'node:crypto';import {createRequire} from 'node:module';
import {parseReforecastWorkbook} from '../docs/portfolio-operations-dashboard/features/reforecast-intake.mjs';
import {persistWorkbookAudit} from '../docs/portfolio-operations-dashboard/features/workbook-audit-store.mjs';
import * as store from '../docs/portfolio-operations-dashboard/features/reforecast-store.mjs';
const require=createRequire(import.meta.url),{fixture}=require('./reforecast-fixture.cjs');
const {db,A,B,BUDGET,signIn}=await fixture();let failAfterCommit=false,tamper=false,actor='00000000-0000-0000-0000-000000000001';
const central={getSession:()=>({user:{id:actor}}),async fetchJson(path,options={}){
 if(path.startsWith('/rpc/')){const name=path.slice(5);assert(/^atlas_[a-z_]+$/.test(name));const params=JSON.parse(options.body),args=Object.values(params),names=Object.keys(params);assert(names.every(name=>/^p_[a-z_]+$/.test(name)));const result=(await db.query(`select to_jsonb(${name}(${names.map((key,i)=>key+' => $'+(i+1)).join(',')})) as result`,args.map(v=>v&&typeof v==='object'&&!Array.isArray(v)?JSON.stringify(v):v))).rows[0].result;if(failAfterCommit){failAfterCommit=false;throw Error('Connection lost after commit');}return ['atlas_save_reforecast_upload','atlas_save_reforecast_registry','atlas_publish_reforecast'].includes(name)?[result]:result;}
 const url=new URL(path,'http://fixture'),table=url.pathname.slice(1);assert(/^atlas_reforecast_[a-z_]+$/.test(table));const filters=[...url.searchParams].filter(([k,v])=>v.startsWith('eq.'));assert(filters.length);assert(filters.every(([key])=>['scenario_id','revision_id','upload_id','version_id','publication_id','request_id','community_id'].includes(key)));const rows=(await db.query(`select to_jsonb(t) as row from ${table} t where ${filters.map(([key],i)=>key+'=$'+(i+1)).join(' and ')}`,filters.map(([,value])=>value.slice(3)))).rows.map(r=>r.row);
 if(tamper&&table==='atlas_reforecast_revisions'){tamper=false;rows[0].snapshot.fingerprint='tampered';}return rows;
}};
// Install the production workbook transport dependencies without upgrading the
// legacy scenario engine that this test deliberately exercises before/after.
await db.exec('reset role');
const planning=fs.readFileSync(new URL('../supabase/migrations/20260924121641_planning_cell_workbook_integrity_governance.sql',import.meta.url),'utf8');
await db.exec(planning.slice(0,planning.indexOf('create or replace function atlas_private.reforecast_planning_issues'))+'commit;');
const audits=fs.readFileSync(new URL('../supabase/migrations/20260924121647_immutable_workbook_audits_and_monthly_governance.sql',import.meta.url),'utf8');
await db.exec(audits.slice(0,audits.indexOf('alter function atlas_private.finance_intake_validation')));
await db.exec(fs.readFileSync(new URL('../docs/portfolio-operations-dashboard/centralization/workbook-audit-chunks.sql',import.meta.url),'utf8'));
for(const name of ['20260925005521_workbook_audit_validation_performance.sql','20260925012008_reforecast_payload_receipt_recovery.sql'])await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));await signIn(1);
central.rpc=(name,args,options={})=>central.fetchJson('/rpc/'+name,{...options,method:'POST',body:JSON.stringify(args)});
const accounts=[['5120','Rent','income','above_noi'],['5220','Vacancy','contra_income','above_noi'],['6100','Payroll','expense','above_noi'],['6200','Utilities','expense','above_noi'],['8100','Capital','capital','below_noi']].map(([accountCode,category,nature,placement])=>({accountCode,category,nature,placement,effectiveFrom:'2026-01'}));
const registry=await store.saveRegistry(central,{communityId:A,requestId:randomUUID(),payload:{accounts,driverMappings:{payroll:['6100']},reason:'Reviewed source classification',effectiveDate:'2026-01-01'}});
let source=await store.readSourceBundle(central,{communityId:A,periods:['2026-01','2026-02','2026-03']});assert.equal(source.registry.version,registry.version_id);
const XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js'),workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,{A1:{t:'n',v:0,f:'1-1'},'!ref':'A1'},'Input');
const bytes=Buffer.from(XLSX.write(workbook,{type:'buffer',bookType:'xlsx'})),sourceHash=createHash('sha256').update(bytes).digest('hex'),evidence=await parseReforecastWorkbook(bytes,{xlsx:XLSX,fileName:'Test.xlsx',includeOriginalBytes:true});
const integrity=await persistWorkbookAudit(central,evidence.integrity,{communityId:A,sourceHash,sourceBytes:bytes});
const upload=await store.saveUpload(central,{communityId:A,requestId:randomUUID(),payload:{...evidence,integrity,propertyAssignment:{communityId:A,confirmed:true}}});assert.equal(upload.payload.sheets[0].cells[0].value,0);
let payload={name:'Governed working',model:'conventional',periods:source.periods,baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:actor,reviewerId:actor,drivers:[{id:'payroll',type:'payroll',operation:'percent_change',value:.1}],overrides:[],reason:'Budget variance review'};
const scenarioId=randomUUID(),request={communityId:A,scenarioId,expectedRevision:0,requestId:randomUUID(),payload};
failAfterCommit=true;await assert.rejects(()=>store.saveScenario(central,request),/lost/);let r=await store.saveScenario(central,request);assert.equal(r.head.revision,1);
const changed={...request,expectedRevision:1,requestId:randomUUID(),payload:{...payload,overrides:[{period:'2026-03',accountCode:'6200',amount:0,reason:'No utility expense planned'}]}};
tamper=true;await assert.rejects(()=>store.saveScenario(central,changed),/committed record/);r=await store.saveScenario(central,changed);assert.equal(r.snapshot.lines.find(l=>l.period==='2026-03'&&l.accountCode==='6200').forecast,0);
for(const action of ['reconcile','ready','submit','approve','lock'])r=await store.saveScenario(central,{communityId:A,scenarioId,expectedRevision:r.head.revision,requestId:randomUUID(),action,payload:r.revision.payload});
await assert.rejects(()=>store.publishActive(central,{scenarioId,expectedRevision:r.head.revision,requestId:randomUUID(),reason:'Publish approved operating benchmark'}),/Active baseline unavailable/,'Old database publication stays retained but cannot claim upgraded active verification');
const legacy=(await central.fetchJson('/rpc/atlas_read_active_reforecast',{body:JSON.stringify({p_community_ids:[A],p_periods:null})}))[0];const vintage=JSON.stringify(legacy.snapshot);assert.throws(()=>store.effectiveActiveSnapshot(legacy),/Active baseline unavailable/);
await db.exec('reset role');await db.exec(fs.readFileSync(new URL('../docs/portfolio-operations-dashboard/centralization/reforecast-builder.sql',import.meta.url),'utf8'));await signIn(1);
let pub=(await store.readActive(central,{communityIds:[A]}))[0];assert.equal(pub.verified,true);assert.equal(pub.approved,true);assert.equal(pub.locked,true);
assert.equal(store.effectiveActiveSnapshot(pub).lines.find(l=>l.period==='2026-03'&&l.accountCode==='6200').forecast,0);
await db.exec('reset role');const feb=randomUUID();await db.query('insert into atlas_financial_close_versions values($1,$2,\'2026-02\',\'feb\',now(),$3)',[feb,A,JSON.stringify({totalIncome:1000,operatingExpenses:300,netOperatingIncome:700,sourceControls:{'Net Cash Flow':{actual:680}}})]);await db.query('insert into atlas_financial_close_heads values($1,\'2026-02\',\'accrual\',$2)',[A,feb]);
for(const[code,n]of[['5120',1100],['5220',-100],['6100',250],['6200',50],['8100',20]])await db.query('insert into atlas_financial_close_rows values($1,$2,$3,$4)',[feb,code,n,'{}']);await signIn(1);
pub=(await store.readActive(central,{communityIds:[A]}))[0];assert.equal(JSON.stringify(pub.snapshot),vintage,'Published vintage never changes');const current=store.effectiveActiveSnapshot(pub);assert.equal(current.lines.find(l=>l.period==='2026-02'&&l.accountCode==='6100').forecast,legacy.snapshot.lines.find(l=>l.period==='2026-02'&&l.accountCode==='6100').forecast);assert.equal(current.monthly[1].reforecast.noi,legacy.snapshot.monthly[1].reforecast.noi);assert.equal(current.monthly[2].reforecast.noi,pub.snapshot.monthly[2].reforecast.noi);assert.equal(current.monthly[2].actuals.noi,null);assert.equal(current.totals.originalBudget.noi,pub.snapshot.totals.originalBudget.noi);
assert.equal(current.categories.find(c=>c.category==='Payroll').monthly[1].forecast,legacy.snapshot.categories.find(c=>c.category==='Payroll').monthly[1].forecast);assert.equal(current.totals.actualsThroughCutoff.noi,legacy.snapshot.totals.actualsThroughCutoff.noi);
await db.exec("reset role;update atlas_user_profiles set locked_tab_ids='{12}',locked_page_keys='{budget}' where role='admin'");await signIn(1);
assert.equal((await store.readWorkspace(central,{communityIds:[A]})).length,0);assert.equal((await store.readActive(central,{communityIds:[A]})).length,1,'Consumer reads published benchmark without draft-edit access');
await assert.rejects(()=>store.readSourceBundle(central,{communityId:A,periods:['2026-02']}),/denied/);
await signIn(4);actor='00000000-0000-0000-0000-000000000004';assert.equal((await store.readActive(central,{communityIds:[A]})).length,0);
await db.close();console.log('PASS real canonical reforecast adapter: verified readback/retries, zero override, frozen publication, old RPC rejection, verified migration upgrade, later actuals never replace the frozen active target, scoped consumer-only access');

let refreshWrites=0;let refreshActor='before';const switched={getSession:()=>({user:{id:refreshActor}}),refreshSession:async()=>{refreshActor='after';},fetchJson:async()=>{refreshWrites++;return {};}};await assert.rejects(()=>store.saveUpload(switched,{communityId:A,requestId:randomUUID(),payload:{}}),/signed-in account changed/);assert.equal(refreshWrites,0,'identity change during refresh prevents the write, rather than reporting it only after mutation');console.log('PASS session refresh identity guard prevents writes under a changed account');
