// Isolated SQL approval lifecycle. No remote connection and no private fixture
// bytes are copied into the repository. The optional fixture must be hash-bound.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto'),{pathToFileURL}=require('node:url'),{fixture}=require('./reforecast-fixture.cjs');
const migration='20260929155712_saved_str_v2_approval_authority.sql',read=name=>fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8');
(async()=>{
 const legacy=await import('../docs/portfolio-operations-dashboard/features/reforecast-str-saved-programme.mjs');
 const actual=process.env.ATLAS_STR_V2_PARSER_PATH?await import(pathToFileURL(path.resolve(process.env.ATLAS_STR_V2_PARSER_PATH)).href):null;
 const {workbookEvidenceHash}=await import('../docs/portfolio-operations-dashboard/features/workbook-integrity.mjs');
 const {savedStrProgrammeDraft}=await import('../docs/portfolio-operations-dashboard/features/reforecast-str-saved-programme-ui.mjs');
 const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
 const rehash=value=>{const {fingerprint,...rest}=value;return {...rest,fingerprint:workbookEvidenceHash(rest)};};
 // Independently reproduce the unchanged v1 envelope from the same structural
 // data, then bind the untouched original v2 bytes/hash. This is test code only:
 // the database always decodes and validates the original v2 document itself.
 const canonicalSource=async(bytes,options)=>{
  const document=JSON.parse(bytes),v1bytes=Buffer.from(JSON.stringify({...document,formatVersion:1}));
  const v1=await legacy.parseSavedStrMonthlyProgramme(v1bytes,options);
  const source=rehash({...v1,sourceHash:hash(bytes),byteLength:bytes.length,originalFile:{encoding:'base64',data:Buffer.from(bytes).toString('base64')}});
  if(actual){assert.deepEqual(await actual.parseSavedStrMonthlyProgramme(bytes,options),source,'Actual merged JS parser must exactly match independently reconstructed source');}
  return {source,v1};
 };
 const periods=['2026-09','2026-10','2026-11','2026-12'],propertyId='P',programmeId='RISE',monthly=n=>[0,0,0,0,0,0,0,0,0,n,n,n];
 const selected=[['income','5144','income',100],['displaced','5220','contra_income',-10],['utility','6200','expense',10],['capital','1504','capital',500]].map(([id,gl,nature,n])=>({id,gl,nature,name:id,propertyId,strProgramId:programmeId,yearData:{2026:monthly(n)}}));
 const supportingSchedules={2026:{schemaVersion:1,sourceKind:'str_builder',leasingSchedule:{periods,monthly:periods.map((period,index)=>({period,endingUnits:index?2**(index-1):0,availableNights:index?30*2**(index-1):0,bookedNights:index?15:0,budgetedOccupancy:index?0.5:0,adr:index?100/15:0,budgetedRevenue:index?100:0}))},channels:[{channel:'Direct',share:1,feePct:0}],assumptions:{averageLengthOfStay:3}}};
 const synthetic={formatVersion:2,savedAt:'2026-09-29T12:00:00Z',state:{properties:[{id:propertyId,units:[{id:'group',name:'Group'}]},{id:'Q',units:[]}],strPrograms:[{id:programmeId,propertyId,operatorId:'rise_internal',lineIds:selected.map(l=>l.id).reverse(),config:{propertyId,programmeId,unitPicks:[{groupId:'group',units:4}],unitRamp:{2026:[0,0,0,0,0,0,0,0,0,1,2,4]}},byYear:{2026:{totalRevenue:300.01,expense:30,furnishCapex:1500,uplift:240.02}},supportingSchedules},{id:'SIBLING',propertyId,operatorId:'reference',lineIds:['sibling']}],lines:[{id:'conventional',propertyId,gl:'5120',nature:'income',yearData:{2026:Array(12).fill(123456)}},{id:'sibling',propertyId,strProgramId:'SIBLING',gl:'9999',nature:'income',yearData:{2026:Array(12).fill(999999)}},{id:'other-property',propertyId:'Q',strProgramId:programmeId,gl:'9998',nature:'income',yearData:{2026:Array(12).fill(888888)}},...selected]},ui:{strCfg:{propertyId:'Q',programmeId:'SIBLING',adr:999999,unitPicks:[{groupId:'invented',units:9999}]}}};
 const fixtures=[{name:'Synthetic v2',bytes:Buffer.from(JSON.stringify(synthetic)),options:{fileName:'Synthetic v2.riseb.json',propertyId,programmeId,periods}}];
 if(process.env.ATLAS_STR_V2_SOURCE_JSON){
  assert.match(process.env.ATLAS_STR_V2_SOURCE_SHA256||'',/^[a-f0-9]{64}$/,'Supply independently verified private original SHA-256');
  const bytes=fs.readFileSync(process.env.ATLAS_STR_V2_SOURCE_JSON);assert.equal(hash(bytes),process.env.ATLAS_STR_V2_SOURCE_SHA256);assert(bytes.length<=1048576);
  const doc=JSON.parse(bytes);assert.equal(doc.formatVersion,2);
  fixtures.push({name:'Private hash-bound v2',bytes,options:{fileName:path.basename(process.env.ATLAS_STR_V2_SOURCE_JSON),propertyId:process.env.ATLAS_STR_V2_PROPERTY_ID,programmeId:process.env.ATLAS_STR_V2_PROGRAMME_ID,periods}});
 }
 for(const item of fixtures){
  const {source,v1}=await canonicalSource(item.bytes,item.options);assert.equal(source.blockers.length,0,JSON.stringify(source.blockers));
  const {db,A,B,BUDGET,signIn}=await fixture(),owner='00000000-0000-0000-0000-000000000005';
  const call=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
  try{
   await db.exec('reset role');await db.exec("alter table atlas_approved_budget_versions add column content_hash text,add column fiscal_year integer,add column fiscal_start_month integer,add column scenario_version text;alter table atlas_communities add column version integer default 1,add column budget_calendar jsonb;");
   await db.exec(read('20260924121641_planning_cell_workbook_integrity_governance.sql'));await db.exec(read('20260924121647_immutable_workbook_audits_and_monthly_governance.sql').split('alter function atlas_private.finance_intake_validation')[0]);
   for(const name of ['20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql','20260925020220_reforecast_import_source_relationships.sql','20260925020222_reforecast_saved_json_str_programme.sql','20260925020226_reforecast_import_source_occurrence_index.sql','20260925071533_reforecast_request_identity_consistency.sql','20260925162050_budget_governed_draft_investor_lifecycle.sql','20260925174317_shared_str_programme_draft_versions.sql','20260929154018_budget_export_integrity_history.sql','20260929154033_budget_leasing_driver_authority.sql','20260929154111_verified_str_budget_application.sql'])await db.exec(read(name));
   const beforeDefinition=(await db.query("select pg_get_functiondef('atlas_private.reforecast_saved_str_source(jsonb)'::regprocedure) d")).rows[0].d;
   await assert.rejects(()=>db.query('select atlas_private.reforecast_saved_str_source($1)',[source]),/Supported source format/,'Original production authority rejects v2');
   await db.exec(read(migration));
   assert.deepEqual((await db.query('select atlas_private.reforecast_saved_str_source($1) s',[source])).rows[0].s,source,'New SQL reconstructs exact original v2 evidence');
   assert.deepEqual((await db.query("select atlas_private.saved_str_identity_present(to_jsonb('v'::text)) single_v,atlas_private.saved_str_identity_present(to_jsonb('vv'::text)) double_v,atlas_private.saved_str_identity_present(to_jsonb(chr(11))) vertical_tab")).rows[0],{single_v:true,double_v:true,vertical_tab:false},'Literal v/vv identities are valid; vertical-tab-only identity is blank');
   assert.deepEqual((await db.query('select atlas_private.reforecast_saved_str_source($1) s',[v1])).rows[0].s,v1,'Existing v1 source shape and fingerprint remain unchanged');
   const accounts=new Map([['5120','income'],['5220','contra_income'],['6100','expense'],['6200','expense'],['8100','capital']]);for(const {line}of source.lineEvidence)accounts.set(line.gl,line.nature);
   const originalRows=[...accounts].map(([glCode])=>({glCode,monthly:Array(12).fill(glCode==='5120'?1000:0)}));await db.query("update atlas_approved_budget_versions set payload=jsonb_build_object('rows',$1::jsonb) where version_id=$2",[originalRows,BUDGET]);await db.query('update atlas_communities set budget_calendar=$1',[{verified:true,classification:'Multifamily',startMonth:1,source:'Isolated fixture reviewed calendar'}]);await signIn(5);
   const registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),{accounts:[...accounts].map(([accountCode,nature])=>({accountCode,category:accountCode,nature,placement:nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'})),driverMappings:{},reason:'Reviewed source account classifications',effectiveDate:'2026-01-01'}]);
   const reviewedAt='2026-09-29T12:00:00Z',payload={name:'V2 Conventional parent',model:'conventional',governanceSchemaVersion:2,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:'V2 Conventional parent',reviewedBy:owner,reviewedAt},periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:owner,reviewerId:owner,drivers:[],overrides:[],reason:'Reviewed exact Conventional parent'};
   let record=await call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',payload]);
   for(const action of ['reconcile','ready','submit','approve_lock'])record=await call('atlas_save_reforecast_scenario',[A,record.head.scenario_id,record.head.revision,randomUUID(),action,record.revision.payload]);
   const parent=await call('atlas_read_reforecast_publication',[record.publication.publication_id]),activeBefore=await call('atlas_read_active_reforecast',[[A],periods]);
   const options={publication:parent,registry:{...registry.payload,version:registry.version_id},mappings:source.lineEvidence.map(({line})=>({sourceLineId:line.id,sourceGL:line.gl,accountCode:line.gl,confirmed:true,reason:'Reviewed exact source signed contribution'})),actor:owner,reviewedAt,reason:'Approve original v2 programme cells',allowHelloLandingGl5144:true,rollupReview:{confirmed:true,sourceHash:source.sourceHash,authority:'saved_monthly_gl_cells',reason:'Preserve exact source monthly cells and disclosed summary differences'}};
   const oldReview=await legacy.prepareSavedStrMonthlyContribution(v1,{...options,rollupReview:{...options.rollupReview,sourceHash:v1.sourceHash}});
   const review=rehash({...oldReview,sourceHash:source.sourceHash,sourceFingerprint:source.fingerprint,rollupReview:options.rollupReview});assert.equal(review.ready,true,JSON.stringify(review.blockers));
   if(actual)assert.deepEqual(await actual.prepareSavedStrMonthlyContribution(source,options),review,'Merged JS contribution review equals SQL RPC input');
   const request=randomUUID(),args=[A,request,source,review];
   const receipt=await call('atlas_save_reforecast_str_json_source',args);assert.deepEqual(receipt.review,review);assert.deepEqual(await call('atlas_read_reforecast_str_json_source_receipt',[A,request]),receipt);assert.deepEqual(await call('atlas_save_reforecast_str_json_source',args),receipt,'Same request replay is exact');
   const retainedEvidence=(await db.query('select evidence from atlas_reforecast_str_json_sources where request_id=$1',[request])).rows[0].evidence;
   assert.deepEqual(Buffer.from(retainedEvidence.originalFile.data,'base64'),item.bytes,'Original bytes retained exactly');
   assert.deepEqual(retainedEvidence.lineEvidence.map(l=>l.sourceLineIndex),source.lineEvidence.map(l=>l.sourceLineIndex));
   await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,{...review,allowHelloLandingGl5144:false}]),/5144/);
   await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,{...review,rollupReview:null}]),/summary differences/);
   const changed=structuredClone(source);changed.cells[0].sourceAmount=777;await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),rehash(changed),review]),/does not exactly reproduce/);
   const wrongActor=rehash({...review,actorId:'00000000-0000-0000-0000-000000000001'});await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,wrongActor]),/Review actor/);
   await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[B,randomUUID(),source,review]),/Conventional parent/);
   assert.deepEqual(await call('atlas_read_active_reforecast',[[A],periods]),activeBefore,'Source approval never changes active property finance');
   if(item.name==='Synthetic v2'){
    const legacyReceipt=await call('atlas_save_reforecast_str_json_source',[A,randomUUID(),v1,oldReview]);assert.deepEqual(legacyReceipt.review,oldReview,'V1 RPC approval remains exact after v2 migration');
    const changedSupport=structuredClone(source);changedSupport.supportingSchedules[2026].channels[0].feePct=.5;await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),rehash(changedSupport),review]),/does not exactly reproduce/);
    const changedReview=structuredClone(review);changedReview.supportingSchedules[2026].channels[0].feePct=.5;await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),source,rehash(changedReview)]),/independently reconstructed/);
    assert.deepEqual(source.lineEvidence.map(l=>l.sourceLineIndex),[3,4,5,6]);assert.equal(source.cells.filter(c=>c.sourceAmount===0).length,4);assert(source.cells.some(c=>c.sourceAmount<0));assert.deepEqual(source.programme.config,synthetic.state.strPrograms[0].config,'Proposed UI assumptions are not authority');
    const draft=savedStrProgrammeDraft(source,review,receipt,{publication:parent,actor:owner});draft.reviewerId=owner;
    const applied=await call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',draft]);assert.deepEqual(applied.source.savedStrSourceReceipts[0].review.supportingSchedules,supportingSchedules);
    for(const c of review.cells)assert.equal(applied.snapshot.lines.find(l=>l.accountCode===c.accountCode&&l.period===c.period).forecast,c.combinedForecast);
    const preview=await call('atlas_preview_budget_export',[A,{revisionId:applied.revision.revision_id}]);assert.deepEqual(preview.config.strStreams[0].supportingSchedules,supportingSchedules);
    const tampered=structuredClone(draft);tampered.strStreams[0].supportingSchedules[2026].channels[0].feePct=.5;
    await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',tampered]),/without alternate rates or units/);
    for(const [name,mutate,pattern]of[
     ['string version',d=>d.formatVersion='2',/numeric saved STR format/],['unknown version',d=>d.formatVersion=3,/numeric saved STR format/],
     ['missing declared list',d=>delete d.state.strPrograms[0].lineIds,/declared lineIds/],['null declared list',d=>d.state.strPrograms[0].lineIds=null,/declared lineIds/],['duplicate declared id',d=>d.state.strPrograms[0].lineIds[0]=d.state.strPrograms[0].lineIds[1],/declared lineIds/],['sibling substituted',d=>d.state.strPrograms[0].lineIds[0]='sibling',/declared lineIds/],['retagged selected line',d=>d.state.lines[3].strProgramId='SIBLING',/declared lineIds/],
     ['duplicate sibling property',d=>d.state.properties.push({...d.state.properties[1]}),/unique identities/],['duplicate sibling programme',d=>d.state.strPrograms.push({...d.state.strPrograms[1]}),/unique identities/],['dangling sibling programme',d=>d.state.strPrograms[1].propertyId='absent',/exact property assignments/],['unrelated null row',d=>d.state.lines.push(null),/object rows/],['vertical-tab-only line id',d=>d.state.lines[3].id='\u000b',/line identities/],['whitespace line id',d=>d.state.lines[3].id='\t\n\u00a0',/line identities/],['non-string line id',d=>d.state.lines[3].id=10,/line identities/],['null source cell',d=>d.state.lines[3].yearData[2026][9]=null,/blank is not zero/],['short source month array',d=>d.state.lines[3].yearData[2026].pop(),/blank is not zero/],['null ramp cell',d=>d.state.strPrograms[0].config.unitRamp[2026][9]=null,/unit ramp/],['missing source config',d=>delete d.state.strPrograms[0].config,/exact property and programme/],['v1 null declared list',d=>{d.formatVersion=1;d.state.strPrograms[0].lineIds=null;},/declared lineIds/],['wrong source config',d=>d.state.strPrograms[0].config.propertyId='Q',/exact property and programme/]
    ]){
     const doc=structuredClone(synthetic);mutate(doc);const bytes=Buffer.from(JSON.stringify(doc)),input=rehash({...source,sourceHash:hash(bytes),byteLength:bytes.length,originalFile:{encoding:'base64',data:bytes.toString('base64')}});
     await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),input,review]),pattern,name);
    }
    const byteTamper=structuredClone(source);byteTamper.originalFile.data=Buffer.concat([item.bytes,Buffer.from(' ')]).toString('base64');await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',[A,randomUUID(),byteTamper,review]),/byte hash or size mismatch/);
    for(const shape of ['absent','null','empty']){const doc=structuredClone(synthetic);if(shape==='absent')delete doc.state.strPrograms[0].supportingSchedules;else doc.state.strPrograms[0].supportingSchedules=shape==='null'?null:{};const emptySupport=await canonicalSource(Buffer.from(JSON.stringify(doc)),item.options);assert.equal(Object.hasOwn(emptySupport.source,'supportingSchedules'),false);await db.exec('reset role');assert.deepEqual((await db.query('select atlas_private.reforecast_saved_str_source($1) s',[emptySupport.source])).rows[0].s,emptySupport.source,'Optional supporting schedules preserve '+shape+' shape');await signIn(5);}
    const numericIds=structuredClone(synthetic);numericIds.state.properties[0].id='123';numericIds.state.strPrograms[0].id='456';numericIds.state.strPrograms[0].config.propertyId='123';numericIds.state.strPrograms[0].config.programmeId='456';for(const prog of numericIds.state.strPrograms)prog.propertyId='123';for(const line of numericIds.state.lines){if(line.propertyId==='P')line.propertyId='123';if(line.strProgramId==='RISE')line.strProgramId='456';}numericIds.state.lines.push({...numericIds.state.lines[3],id:'numeric-tag-row',propertyId:123,strProgramId:456,gl:'9997'});
    const typed=await canonicalSource(Buffer.from(JSON.stringify(numericIds)),{...item.options,propertyId:'123',programmeId:'456'});assert.equal(typed.source.lineEvidence.length,4);await db.exec('reset role');assert.deepEqual((await db.query('select atlas_private.reforecast_saved_str_source($1) s',[typed.source])).rows[0].s,typed.source,'Numeric tag lookalikes never enter the string-selected source');await signIn(5);
    const letterIds=structuredClone(synthetic);letterIds.state.properties[0].id='v';letterIds.state.strPrograms[0].id='vv';letterIds.state.strPrograms[0].config.propertyId='v';letterIds.state.strPrograms[0].config.programmeId='vv';for(const prog of letterIds.state.strPrograms)prog.propertyId='v';for(const line of letterIds.state.lines){if(line.propertyId==='P')line.propertyId='v';if(line.strProgramId==='RISE')line.strProgramId='vv';}const letterSource=await canonicalSource(Buffer.from(JSON.stringify(letterIds)),{...item.options,propertyId:'v',programmeId:'vv'});await db.exec('reset role');assert.deepEqual((await db.query('select atlas_private.reforecast_saved_str_source($1) s',[letterSource.source])).rows[0].s,letterSource.source,'Actual source approval authority accepts property v and programme vv');await signIn(5);
    const noListV1=structuredClone(synthetic);noListV1.formatVersion=1;delete noListV1.state.strPrograms[0].lineIds;const v1NoList=await canonicalSource(Buffer.from(JSON.stringify(noListV1)),item.options);await db.exec('reset role');assert.deepEqual((await db.query('select atlas_private.reforecast_saved_str_source($1) s',[v1NoList.source])).rows[0].s,v1NoList.source,'V1 may still omit declared lineIds');await signIn(5);
   }
   await signIn(4);await assert.rejects(()=>call('atlas_save_reforecast_str_json_source',args),/required/);await assert.rejects(()=>call('atlas_read_reforecast_str_json_source_receipt',[A,request]),/access denied/);assert.equal((await db.query('select count(*)::int n from atlas_reforecast_str_json_sources')).rows[0].n,0);
   await db.exec('reset role');await assert.rejects(()=>db.exec("update atlas_reforecast_str_json_sources set evidence='{}'"),/immutable/);
   const grants=(await db.query("select p.proname,has_function_privilege('anon',p.oid,'execute') anon,has_function_privilege('authenticated',p.oid,'execute') auth from pg_proc p where oid in ('atlas_private.validate_saved_str_source_identity(jsonb,text,text)'::regprocedure,'atlas_private.reforecast_saved_str_source(jsonb)'::regprocedure,'atlas_private.saved_str_identity_present(jsonb)'::regprocedure)")).rows;for(const g of grants){assert.equal(g.anon,false);assert.equal(g.auth,false);}
   // A changed prerequisite aborts the entire migration and preserves the source.
   await db.exec('begin');await db.exec(beforeDefinition.replace("document->>'formatVersion' is distinct from '1'","document->>'formatVersion' <> '1'"));await db.exec('drop function atlas_private.validate_saved_str_source_identity(jsonb,text,text);drop function atlas_private.saved_str_identity_present(jsonb)');await db.exec('commit');
   const drift=(await db.query("select pg_get_functiondef('atlas_private.reforecast_saved_str_source(jsonb)'::regprocedure) d")).rows[0].d;
   await assert.rejects(()=>db.exec(read(migration)),/authority changed/);await db.exec('rollback');assert.equal((await db.query("select pg_get_functiondef('atlas_private.reforecast_saved_str_source(jsonb)'::regprocedure) d")).rows[0].d,drift);assert.equal((await db.query("select to_regprocedure('atlas_private.validate_saved_str_source_identity(jsonb,text,text)') f")).rows[0].f,null);
   console.log(JSON.stringify({status:'PASS',fixture:item.name,sourceHash:source.sourceHash,originalBytes:item.bytes.length,sourceLines:source.lineEvidence.length,sourceCells:source.cells.length,originalIndices:source.lineEvidence.map(l=>l.sourceLineIndex),zeros:source.cells.filter(c=>c.sourceAmount===0).length,negative:source.cells.filter(c=>c.sourceAmount<0).length,approvedReceiptRoundtrip:true,exactOriginalBytes:true,immutableScopedReceipt:true,activeFinanceUnchanged:true,actualMergedParserCompared:Boolean(actual)}));
  }finally{await db.close();}
 }
})().catch(error=>{console.error(error);process.exitCode=1;});
