import assert from 'node:assert/strict';
import {gapRows,trendRows,trendPoints,contributionRows,bridgeRows,forecastAccuracyByVintage,reportHtml,exportRows,analyticalExportRows,csv} from '../docs/portfolio-operations-dashboard/features/reforecast-report.mjs';
const periods=['2026-01','2026-02','2026-03'];
const amounts=[{budget:[100,20,0],forecast:[110,30,0],actual:[105,25,0]},{budget:[200,40,0],forecast:[220,50,0],actual:[null,null,null]},{budget:[100,20,0],forecast:[100,20,0],actual:[null,null,null]}];
const lines=periods.flatMap((period,i)=>['5120','6300','1500'].map((accountCode,j)=>({period,accountCode,accountName:['Rent','Payroll','Capital'][j],category:['Income','Payroll','Capital'][j],nature:['income','expense','capital'][j],placement:j===2?'below_noi':'above_noi',originalBudget:amounts[i].budget[j],forecast:amounts[i].forecast[j],actual:amounts[i].actual[j],closeVersionId:i===0?'close-jan':null,sourceKind:i===0?'closed_actual':'forecast'})));
const metrics=(values)=>{const [revenue,expenses,capital]=values;return {revenue,opex:expenses,expenses,noi:revenue===null||expenses===null?null:revenue-expenses,margin:revenue?((revenue-expenses)/revenue):null,cashFlow:revenue===null||expenses===null?null:revenue-expenses-capital};};
const snapshot={fingerprint:'frozen-v1',identity:{communityId:'A',periods,actualCutoff:'2026-01',baselineVersionIds:['baseline-v1'],mappingRegistryVersion:'map-v1'},lines,monthly:periods.map((period,i)=>({period,closed:i===0,originalBudget:metrics(amounts[i].budget),reforecast:metrics(amounts[i].forecast),actuals:metrics(amounts[i].actual)}))};
const latest={baseline:{versionIds:['UNRELATED-NEW-BUDGET'],lines:lines.map(row=>({period:row.period,accountCode:row.accountCode,amount:999}))},registry:{version:'NEW-MAP',accounts:[]},actuals:{cutoffPeriod:'2026-02',closeVersions:[{period:'2026-01',versionId:'close-jan-new'},{period:'2026-02',versionId:'close-feb'}],lines:periods.slice(0,2).flatMap((period,i)=>['5120','6300','1500'].map((accountCode,j)=>({period,accountCode,amount:[[106,26,0],[200,40,0]][i][j]}))),monthly:[{period:'2026-01',closeVersionId:'close-jan-new',source:'governed_close_controls',...metrics([106,26,0])},{period:'2026-02',closeVersionId:'close-feb',source:'governed_close_controls',...metrics([200,40,0])}]}};
const frozen=JSON.stringify(snapshot),rows=gapRows(snapshot,latest),trend=trendRows(snapshot,latest),exports=exportRows(snapshot,latest);
assert.equal(rows.find(row=>row.period==='2026-01'&&row.accountCode==='5120').budget,100,'original target comes from frozen snapshot, never newer source');
assert.equal(rows.find(row=>row.period==='2026-01'&&row.accountCode==='5120').actual,105,'default uses exact retained actual snapshot');
assert.equal(rows.find(row=>row.period==='2026-02'&&row.accountCode==='5120').actual,null);
assert.equal(exports[0].Baseline_versions,'baseline-v1');assert.equal(exports[0].Mapping_version,'map-v1');
for(const row of rows){const output=exports.find(item=>item.Period===row.period&&item.GL===row.accountCode);assert.equal(output.Original_budget,row.budget);assert.equal(output.Reforecast,row.forecast);assert.equal(output.Governed_actuals,row.actual);}
assert.equal(trend[0].actual,80);assert.equal(trend[1].actual,null);
const quarterly=gapRows(snapshot,latest,{grain:'quarter'});assert.equal(quarterly.find(row=>row.accountCode==='5120').forecast,430);assert.equal(quarterly.find(row=>row.accountCode==='5120').actual,null,'incomplete quarter actual never fills future with zero');
assert.equal(gapRows(snapshot,latest,{grain:'year',category:'Payroll',placement:'above_noi'})[0].forecast,100);
assert.equal(trendRows(snapshot,latest,{category:'Payroll',metric:'noi'})[0].forecast,-30,'cost contribution to NOI is negative');
const qmargin=trendRows(snapshot,latest,{grain:'quarter',metric:'margin'})[0].forecast;assert(Math.abs(qmargin-(430-100)/430)<1e-12,'quarter margin is ratio of totals, never sum or mean of percentages');
const contributions=contributionRows(snapshot,latest);assert.equal(contributions.find(row=>row.period==='2026-01'&&row.accountCode==='6300').budgetToForecastContribution,-10);
const bridges=bridgeRows(snapshot,latest);assert.equal(bridges[0].budgetToForecast.startNoi+bridges[0].budgetToForecast.revenueEffect+bridges[0].budgetToForecast.expenseEffect,bridges[0].budgetToForecast.endNoi);
assert(bridges[0].budgetToForecast.reconciles);
const cum=trendPoints(trend,{cumulative:true});assert.equal(cum[1].actual,null);assert.equal(cum[2].forecast,330);
const marginCum=trendPoints(trendRows(snapshot,latest,{metric:'margin'}),{cumulative:true,metric:'margin'});assert(Math.abs(marginCum[2].forecast-330/430)<1e-12);
const vintages=[{publicationId:'published-v1',publishedAt:'2026-01-31',snapshot},{snapshot}];
const accuracy=forecastAccuracyByVintage(vintages,latest);assert.equal(accuracy.rows.length,1,'only published and subsequently closed forecast months score');assert.equal(accuracy.rows[0].period,'2026-02');assert.equal(accuracy.rows[0].forecast,170);assert.equal(accuracy.rows[0].actual,160);assert.equal(accuracy.rows[0].actualCloseVersionId,'close-feb');assert.equal(accuracy.summaries[0].mae,10);
const explicitLatest=gapRows(snapshot,latest,{actualsMode:'latest'});assert.equal(explicitLatest.find(row=>row.period==='2026-02'&&row.accountCode==='5120').actual,200);
assert.equal(trendRows(snapshot,latest,{actualsMode:'latest'})[1].actual,160);
const capitalAccuracy=forecastAccuracyByVintage(vintages,latest,{account:'1500',metric:'cashFlow'});assert.equal(capitalAccuracy.rows[0].actual,0);assert.equal(capitalAccuracy.rows[0].absolutePercentError,null,'zero actual cannot produce division by zero or fake percentage');
const html=reportHtml(snapshot,latest,{communityName:'A <review>',vintages,latestSource:latest,cumulative:true});
for(const text of ['A &lt;review&gt;','NOI and margin bridges','contribution heatmap','Forecast accuracy by published vintage','frozen-v1','baseline-v1','Unavailable'])assert(html.includes(text));
assert(!html.includes('UNRELATED-NEW-BUDGET'));
const detail=analyticalExportRows(snapshot,latest,{vintages,latestSource:latest});const withoutLineage=rows=>rows.map(row=>Object.fromEntries(Object.entries(row).filter(([key])=>!['Snapshot','Snapshot_schema','Snapshot_kind','Source_versions'].includes(key))));assert.deepEqual(withoutLineage(detail.accuracy),accuracy.rows);assert.deepEqual(withoutLineage(detail.monthly),trend);assert(detail.monthly.every(row=>row.Snapshot===exports[0].Snapshot));assert.notEqual(explicitLatest[0].snapshotVersion,rows[0].snapshotVersion,'latest-actual comparison has its own bound source snapshot');
const csvOutput=csv(exports);assert(csvOutput.includes('"0"'));assert(csvOutput.includes('""'));assert(csv([{Label:'=bad()',Value:-1}]).includes('"\'=bad()","-1"'));
assert.equal(JSON.stringify(snapshot),frozen,'reports/analytics/exports never mutate frozen versions');
console.log('PASS immutable three-way snapshot/table/export parity; community-period-GL-category-placement filters; monthly/quarter/year null-safe ratios; NOI/margin bridges; contribution heatmaps; cumulative gaps; published-vintage accuracy and actual-version lineage');
