const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID,createHash}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{
 const {db,A,BUDGET,signIn}=await fixture(),sql=name=>fs.readFileSync(path.join(__dirname,'../docs/portfolio-operations-dashboard/centralization/'+name),'utf8'),user=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
 const call=async(name,args)=>(await db.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
 await db.exec('reset role');await db.exec("create function atlas_private.resolve_workbook_audit(a jsonb,h text) returns jsonb language sql as $$select a$$");
 await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260924121641_planning_cell_workbook_integrity_governance.sql'),'utf8'));
 await db.exec(sql('reforecast-builder.sql'));await db.exec(sql('reforecast-governed-close-scope.sql'));await db.exec(sql('reforecast-report-receipts.sql'));await db.exec(sql('reforecast-str-overlay.sql'));
 const extra=[['5144',100.0001],['5150',0],['5250',0],['5255',0]].map(([glCode,n])=>({glCode,monthly:Array(12).fill(n)}));
 await db.query("update atlas_approved_budget_versions set payload=jsonb_set(payload,'{rows}',(payload->'rows')||$1::jsonb) where version_id=$2",[JSON.stringify(extra),BUDGET]);await signIn(1);
 const accounts=[['5120','Rent','income','above_noi'],['5144','Hello Landing','income','above_noi'],['5150','RISE STR','income','above_noi'],['5220','Vacancy','contra_income','above_noi'],['5250','STR Vacancy','contra_income','above_noi'],['5255','STR Fees','contra_income','above_noi'],['6100','Payroll','expense','above_noi'],['6200','Utilities','expense','above_noi'],['8100','Capital','capital','below_noi']].map(([accountCode,category,nature,placement])=>({accountCode,category,nature,placement,effectiveFrom:'2026-01'}));
 const registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),JSON.stringify({accounts,driverMappings:{},reason:'Reviewed separate STR mappings',effectiveDate:'2026-01-01'})]);
 const periods=['2026-09','2026-10'],payload={name:'Conventional',model:'conventional',governanceSchemaVersion:2,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:'Conventional',reviewedBy:user(1),reviewedAt:'2026-09-24T10:00:00Z'},periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:user(1),reviewerId:user(5),drivers:[],overrides:[],reason:'Reviewed Conventional operating baseline'};
 const save=(p,id=randomUUID(),rev=0,action='save_draft',request=randomUUID())=>call('atlas_save_reforecast_scenario',[A,id,rev,request,action,JSON.stringify(p)]);
 const advance=async record=>{for(const action of ['reconcile','ready','submit','approve_lock'])record=await save(record.revision.payload,record.head.scenario_id,record.head.revision,action);return record;};
 const conventional=await advance(await save(payload)),parent=await call('atlas_read_reforecast_publication',[conventional.publication.publication_id]),beforeActive=await call('atlas_read_active_reforecast',[[A],periods]);
 await db.exec('reset role');await db.exec(`create table atlas_bonus_periods(bonus_period_id uuid primary key,status text,start_date date,end_date date);create table atlas_bonus_calculation_runs(bonus_calculation_run_id uuid primary key,bonus_period_id uuid,community_id uuid,status text,deleted_at timestamptz,inputs jsonb,exceptions jsonb);insert into atlas_bonus_periods values('60000000-0000-0000-0000-000000000001','open','2026-09-01','2026-10-31');insert into atlas_bonus_calculation_runs values('70000000-0000-0000-0000-000000000001','60000000-0000-0000-0000-000000000001','${A}','draft',null,'{"baselineVersion":"Conventional"}','[]');`);const bonusBytes=(await db.query('select jsonb_agg(to_jsonb(r))::text bytes from atlas_bonus_calculation_runs r')).rows[0].bytes;const baselineBytes=(await db.query('select payload::text bytes from atlas_approved_budget_versions where version_id=$1',[BUDGET])).rows[0].bytes,actualBytes=(await db.query('select jsonb_agg(to_jsonb(r))::text bytes from atlas_financial_close_rows r')).rows[0].bytes,parentBytes=JSON.stringify(conventional.publication);await signIn(1);
 const {createStrOverlayDraft,riseReviewScope,validateRiseOverlay}=await import('../docs/portfolio-operations-dashboard/features/reforecast-str-overlay.mjs');
 const {applyStrSchedules}=await import('../docs/portfolio-operations-dashboard/features/reforecast-builder-ui.mjs');
 const {calculateStrLeasingSchedule}=await import('../docs/portfolio-operations-dashboard/features/reforecast-provider.mjs');const fractional=calculateStrLeasingSchedule({periods:['2026-10'],streams:[{id:'rise_str',units:[{id:'A',availableFrom:'2026-10'}],monthly:[{period:'2026-10',occupancyPercent:50,grossPerOccupiedNight:1.001,feePerAvailableUnit:0,netMethod:'gross_plus_signed_fees'}]}]}).rows[0];assert.equal(fractional.vacancyLoss,-15.51);assert.equal(Math.round((fractional.grossPotentialIncome+fractional.vacancyLoss)*100)/100,fractional.grossIncome);

 let draft=createStrOverlayDraft(parent,{actor:user(1)});draft.reviewerId=user(5);draft.reason='Reviewed separate overlay';
 let record=await save(draft);assert(record.snapshot.diagnostics.some(row=>row.code==='str_source_required'));await assert.rejects(()=>save(record.revision.payload,record.head.scenario_id,record.head.revision,'ready'),/Resolve|before approval/);
 const stream=draft.strStreams[0];Object.assign(stream,{reviewed:true,reviewedBy:user(1),reviewedAt:'2026-09-24T12:00:00Z',incomeAccountCode:'5150',vacancyAccountCode:'5250',feeAccountCode:'5255',assumptionReason:'Reviewed exact roster and signed fee schedule',units:[{id:'PRIVATE-A',availableFrom:'2026-09',takeBackMonth:'2026-10'},{id:'PRIVATE-B',availableFrom:'2026-09',takeBackMonth:null}],monthly:periods.map(period=>({period,occupancyPercent:50,grossPerOccupiedNight:period==='2026-10'?1.001:100,netPerOccupiedNight:null,feePerAvailableUnit:-10,netMethod:'gross_plus_signed_fees'}))});
 const bytes=Buffer.from('Synthetic RISE full roster and schedule evidence'),upload=await call('atlas_save_reforecast_upload',[A,randomUUID(),JSON.stringify({sourceType:'rise_str',propertyAssignment:{communityId:A,confirmed:true},source:{fileName:'synthetic.xlsx',sha256:createHash('sha256').update(bytes).digest('hex'),originalFile:{encoding:'base64',data:bytes.toString('base64')}},statement:{period:'2026-09',periodBasis:'calendar_month',status:'reconciled',provider:'rise_str',streamId:'rise_str',summary:{},metrics:{},checks:[],issues:[]}})]);
 async function reviewSchedule(value){return call('atlas_review_reforecast_source',[upload.upload_id,randomUUID(),JSON.stringify({sourceType:'rise_str',period:'2026-09',status:'approved',mapping:{version:registry.version_id,riseScheduleEvidence:riseReviewScope(value)},reason:'Source confirms complete exact roster, rate, signed fee and method schedule'})]);}
 let review=await reviewSchedule(stream);stream.sourceReviewId=review.review_id;draft.sourceUploadIds=[upload.upload_id];record=await save(draft,record.head.scenario_id,record.head.revision);
 assert.deepEqual(validateRiseOverlay(draft,record.source),[]);draft=applyStrSchedules(draft,record.source,{actor:user(1)});
 record=await save(draft,record.head.scenario_id,record.head.revision);assert.equal(record.snapshot.completeness.blockerCount,0,JSON.stringify(record.snapshot.diagnostics));
 const tampered=structuredClone(record.revision.payload);tampered.strStreams[0].monthly[0].grossPerOccupiedNight=999;const changed=await save(tampered,record.head.scenario_id,record.head.revision);assert(changed.snapshot.diagnostics.some(row=>row.code==='str_review_scope_changed'));assert.throws(()=>applyStrSchedules(tampered,record.source,{actor:user(1)}),/changed after source review/);record=await save(draft,changed.head.scenario_id,changed.head.revision);
 const steal=structuredClone(record.revision.payload);steal.strStreams[0].incomeAccountCode='5144';const protectedRecord=await save(steal,record.head.scenario_id,record.head.revision);assert(protectedRecord.snapshot.diagnostics.some(row=>row.code==='str_hello_landing_protected'));record=await save(draft,protectedRecord.head.scenario_id,protectedRecord.head.revision);
 const stray=structuredClone(record.revision.payload);stray.drivers=[{id:'unauthorized',operation:'amount',type:'rent',accountCodes:['5120'],periods,value:999,reason:'Not an STR contribution'}];const strayRecord=await save(stray,record.head.scenario_id,record.head.revision);assert(strayRecord.snapshot.diagnostics.some(row=>row.code==='str_overlay_only'));record=await save(draft,strayRecord.head.scenario_id,strayRecord.head.revision);
 record=await advance(record);const withStr=await call('atlas_read_reforecast_publication',[record.publication.publication_id]);const retried=await save(record.revision.payload,record.head.scenario_id,record.head.revision-2,'approve_lock',record.publication.request_id);assert.deepEqual(retried.publication,record.publication,'Same approval request returns exact immutable overlay');assert.equal((await db.query('select count(*)::int n from atlas_reforecast_publications where scenario_id=$1',[record.head.scenario_id])).rows[0].n,1);
 assert.deepEqual(await call('atlas_read_active_reforecast',[[A],periods]),beforeActive,'Overlay approval must leave Conventional active values byte-identical');assert.equal(withStr.activePeriods.length,0);await db.exec('reset role');assert.equal((await db.query('select jsonb_agg(to_jsonb(r))::text bytes from atlas_bonus_calculation_runs r')).rows[0].bytes,bonusBytes,'Publishing STR must not invalidate Conventional bonus calculations');await signIn(1);
 assert.equal(withStr.snapshot.strSchedules[0].availableUnits,2);assert.equal(withStr.snapshot.strSchedules[1].availableUnits,1,'Take-back removes unit for the entire selected month');assert.equal(withStr.snapshot.strSchedules[1].vacancyLoss,-15.51);assert.equal(withStr.snapshot.strSchedules[1].grossIncome,15.52);
 assert.equal(withStr.snapshot.lines.find(row=>row.period===periods[0]&&row.accountCode==='5150').forecast,6000);assert.equal(withStr.snapshot.lines.find(row=>row.period===periods[0]&&row.accountCode==='5250').forecast,-3000);assert.equal(withStr.snapshot.lines.find(row=>row.period===periods[0]&&row.accountCode==='5255').forecast,-20);
 assert(withStr.snapshot.lines.filter(row=>row.accountCode==='5144').every(row=>row.forecast===100.0001));assert.equal(withStr.snapshot.lines.filter(row=>row.accountCode==='5144').length,periods.length);
 const report=await import('../docs/portfolio-operations-dashboard/features/reforecast-report.mjs'),pair=report.pairedForecastReports(parent,withStr,{communityName:'Synthetic Doro'});
 assert.equal(pair.conventional.rows[0].Pair_snapshot,pair.withStr.rows[0].Pair_snapshot);assert.notEqual(pair.conventional.rows[0].Publication,pair.withStr.rows[0].Publication);assert.equal(pair.withStr.bridge.length,withStr.snapshot.lines.length);assert(!JSON.stringify(pair).includes('PRIVATE-'));
 const {PDFDocument,PDFName,PDFDict,PDFArray,PDFRawStream,decodePDFRawStream}=await import('../docs/portfolio-operations-dashboard/vendor/pdf-lib-1.17.1.mjs');
 const XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');for(const [publication,expected] of [[parent,pair.conventional],[withStr,pair.withStr]]){const workbook=report.communityForecastWorkbook(publication,XLSX,pair.reportOptions),reopened=XLSX.read(XLSX.write(workbook,{type:'buffer',bookType:'xlsx'}),{type:'buffer'}),rows=XLSX.utils.sheet_to_json(reopened.Sheets['GL detail'],{defval:null});assert.deepEqual(rows,expected.rows);assert.deepEqual(XLSX.utils.sheet_to_json(reopened.Sheets['STR contribution bridge'],{defval:null}),expected.bridge);const pdf=await report.communityForecastPdf(publication,pair.reportOptions);const document=await PDFDocument.load(pdf),attachment=document.catalog.lookup(PDFName.of('Names'),PDFDict).lookup(PDFName.of('EmbeddedFiles'),PDFDict).lookup(PDFName.of('Names'),PDFArray).lookup(1,PDFDict).lookup(PDFName.of('EF'),PDFDict).lookup(PDFName.of('F'),PDFRawStream),evidence=JSON.parse(new TextDecoder().decode(decodePDFRawStream(attachment).decode()));assert.deepEqual(evidence.snapshot,expected.snapshot);assert.deepEqual(evidence.rows,[...expected.rows,...expected.monthly,...expected.schedules,...expected.utilities,...expected.drivers,...expected.overrides,...expected.baselines,...expected.risks,...expected.bridge,...expected.appendix]);assert(!JSON.stringify(evidence).includes('PRIVATE-'));const output=path.join(__dirname,'../output/doro-str-repair-synthetic');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,publication===parent?'SYNTHETIC-Conventional.pdf':'SYNTHETIC-With-STR.pdf'),pdf);}
 await signIn(5);assert.deepEqual(await call('atlas_read_reforecast_publication',[record.publication.publication_id]),withStr,'Two authorized sessions read identical snapshot values and versions');
 await signIn(1);const reopened=await call('atlas_reopen_reforecast',[record.head.scenario_id,record.head.revision,randomUUID(),'Revise only the overlay']);assert.deepEqual(await call('atlas_read_active_reforecast',[[A],periods]),beforeActive);assert.equal(JSON.stringify((await db.query('select to_jsonb(p) value from atlas_reforecast_publications p where publication_id=$1',[conventional.publication.publication_id])).rows[0].value),parentBytes);await db.exec('reset role');assert.equal((await db.query('select jsonb_agg(to_jsonb(r))::text bytes from atlas_bonus_calculation_runs r')).rows[0].bytes,bonusBytes,'Reopening STR must not invalidate Conventional bonus calculations');assert.equal((await db.query('select payload::text bytes from atlas_approved_budget_versions where version_id=$1',[BUDGET])).rows[0].bytes,baselineBytes);assert.equal((await db.query('select jsonb_agg(to_jsonb(r))::text bytes from atlas_financial_close_rows r')).rows[0].bytes,actualBytes);
 await signIn(1);
 // Net is a new reviewed schedule and posts reviewed income once, including fees.
 const netDraft=createStrOverlayDraft(parent,{actor:user(1)});netDraft.reason='Net method reviewed separately';netDraft.reviewerId=user(5);netDraft.strStreams=[{...stream,incomeBasis:'net'}];review=await reviewSchedule(netDraft.strStreams[0]);netDraft.strStreams[0].sourceReviewId=review.review_id;netDraft.sourceUploadIds=[upload.upload_id];let net=await save(netDraft,reopened.head.scenario_id,reopened.head.revision);net=await save(applyStrSchedules(netDraft,net.source,{actor:user(1)}),net.head.scenario_id,net.head.revision);assert.equal(net.snapshot.completeness.blockerCount,0,JSON.stringify(net.snapshot.diagnostics));assert.equal(net.revision.payload.overrides.length,periods.length);assert.equal(net.snapshot.lines.find(row=>row.period===periods[0]&&row.accountCode==='5150').forecast,2980);assert.equal(net.snapshot.lines.find(row=>row.period===periods[0]&&row.accountCode==='5250').forecast,0);assert.equal(net.snapshot.lines.find(row=>row.period===periods[0]&&row.accountCode==='5255').forecast,0);
 await db.exec('reset role');await assert.rejects(()=>db.query('update atlas_reforecast_active_heads set publication_id=$1 where community_id=$2',[record.publication.publication_id,A]),/overlay and cannot/);
 for(const fn of ['reforecast_rise_review_scope','reforecast_rise_issues','reforecast_overlay_snapshot_guard','reforecast_conventional_active_guard'])assert.equal((await db.query("select bool_or(has_function_privilege('authenticated',p.oid,'EXECUTE')) allowed from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='atlas_private' and p.proname=$1",[fn])).rows[0].allowed,false);
 console.log('PASS strict RISE source scope, exact parent, gross/net fee and vacancy accounting, full-month take-back, Hello Landing protection, unchanged active/original/actual/history, authorized-session parity and paired XLSX/PDF snapshots');await db.close();
})().catch(error=>{console.error(error);process.exit(1);});
