/* Regression coverage for recovered edits and immutable baseline selection in the production UI. */
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright');
const cid='10000000-0000-0000-0000-000000000001',url=process.env.ATLAS_UI_TEST_URL||'http://127.0.0.1:8773';
let server,serverOutput='';
if(!process.env.ATLAS_UI_TEST_URL){server=spawn(process.execPath,['tools/reforecast-harness-server.cjs'],{env:{...process.env,PORT:'8773',ATLAS_FIXTURE_SKIP_REGISTRY:'1'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('UI fixture startup timed out. '+serverOutput)),15000);server.once('exit',code=>{clearTimeout(timer);reject(Error('UI fixture exited '+code+': '+serverOutput));});for(const stream of [server.stdout,server.stderr])stream.on('data',chunk=>{serverOutput+=chunk;if(serverOutput.includes('acceptance http://127.0.0.1:8773')){clearTimeout(timer);resolve();}});});}
const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',error=>errors.push(error.message));
const idle=()=>page.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled);
const save=async action=>{await page.locator('[data-action='+action+']').click();await idle();assert.deepEqual(await page.locator('[role=alert]').allTextContents(),[]);};
const setup=async name=>{await page.locator('[data-new]').click();await page.locator('[data-name]').fill(name);await page.locator('[data-last]').fill('2026-03');await page.locator('[data-last]').dispatchEvent('change');await page.waitForFunction(()=>!document.querySelector('[data-create]')?.disabled);};
const finishSetup=async()=>{await page.locator('dialog [data-calendar-confirm]').check();await page.locator('[data-create]').click();await page.locator('[data-edit=reviewerId]').selectOption('00000000-0000-0000-0000-000000000001');await page.locator('[data-edit=reason]').fill('Synthetic final UI regression review');};
const map=()=>page.locator('dialog:has([data-maprow])');
try{
 await page.goto(url);await page.locator('[data-community]').selectOption(cid);await idle();await setup('Synthetic initial forecast');await finishSetup();
 const cell='[data-gl-cell][data-period="2026-02"][data-code="5120"]';
 if(!process.env.ATLAS_UI_TEST_URL){
  assert.equal(await page.locator(cell).count(),0,'A first-run null registry has no calculated cells yet');assert.equal(await page.locator('[data-map]').count(),1,'Missing registry must still render mapping controls');await page.locator('[data-map]').click();assert.equal(await map().locator('[data-maprow]').count(),5,'Canonical original-budget GLs seed the first review');assert.match(await map().locator('[data-maprow]').first().innerText(),/5120 Rent/);await map().locator('[data-save]').click();assert.match(await map().locator('[data-status]').innerText(),/review confirmation/);await map().locator('[data-reason]').fill('Reviewed first canonical GL mapping from the original budget');await map().locator('[data-confirm]').check();await map().locator('[data-save]').click();await map().waitFor({state:'detached'});assert.equal(await page.locator(cell).inputValue(),'1000');
 }

 await page.locator(cell).fill('15000');await page.locator(cell).dispatchEvent('change');assert.equal(await page.locator(cell).inputValue(),'15000','A failed reason check preserves the visible dense-grid edit');assert.match((await page.locator('[role=alert]').allTextContents()).join(' '),/adjustment reason/);
 await page.locator('[data-dense-reason]').fill('Reviewed corrected source expectation');await page.locator('[data-dense-reason]').dispatchEvent('change');await save('save_draft');assert.equal(await page.locator(cell).inputValue(),'15000','Entering the dense reason applies and clears pending edits');
 // Prospective GL additions retain every unsaved mapping input, without altering canonical mappings on cancel.
 await page.locator('[data-map]').click();const originalCategory=await map().locator('[data-maprow]').first().locator('[data-field=category]').inputValue();await map().locator('[data-maprow]').first().locator('[data-field=category]').fill('Reviewed temporary category');await map().locator('[data-reason]').fill('Local mapping edit retained while adding a prospective account');await map().getByText('Owner-specific GL addition',{exact:true}).click();await map().locator('[data-new-code]').fill('9999');await map().locator('[data-new-name]').fill('Synthetic prospective account');await map().locator('[data-add-account]').click();assert.equal(await map().locator('[data-maprow]').first().locator('[data-field=category]').inputValue(),'Reviewed temporary category');assert.equal(await map().locator('[data-reason]').inputValue(),'Local mapping edit retained while adding a prospective account');assert.equal(await map().locator('[data-maprow]').filter({hasText:'9999'}).count(),1);await map().locator('[data-close]').click();await page.locator('[data-map]').click();assert.equal(await map().locator('[data-maprow]').first().locator('[data-field=category]').inputValue(),originalCategory);assert.equal(await map().locator('[data-maprow]').filter({hasText:'9999'}).count(),0,'Cancel never changes the authoritative source registry');await map().locator('[data-close]').click();
 for(const action of ['reconcile','ready','submit'])await save(action);await page.locator('[data-approve-review]').click();await page.locator('[data-approval-confirm]').check();await page.locator('[data-confirm-approval]').click();await page.waitForSelector('[data-confirm-approval]',{state:'detached'});await idle();assert.deepEqual(await page.locator('[role=alert]').allTextContents(),[]);
 // Slow immutable reads must never relabel one community's financial results as another's.
 const approvedScenario=await page.locator('[data-scenario]').inputValue(),downloads=[];const trackDownload=download=>downloads.push(download);page.on('download',trackDownload);
 for(const [selector,routePattern] of [['[data-official-export=pdf]','**/__api/rpc/atlas_read_reforecast_publication'],['[data-official-export=xlsx]','**/__api/rpc/atlas_read_reforecast_publication'],['[data-export=json]','**/__api/atlas_reforecast_revisions?*']]){
  let release,intercepted;const gate=new Promise(resolve=>release=resolve),seen=new Promise(resolve=>intercepted=resolve);await page.route(routePattern,async route=>{const response=await route.fetch();intercepted();await gate;await route.fulfill({response});});
  try{await page.locator(selector).click();await seen;await page.locator('[data-community]').selectOption('10000000-0000-0000-0000-000000000002');await idle();release();await page.waitForFunction(()=>[...document.querySelectorAll('[role=alert]')].some(el=>el.textContent.includes('forecast selection changed')));assert.equal(downloads.length,0,'Changing community cancels an in-flight immutable export before download');}
  finally{release();await page.unroute(routePattern);}
  await page.locator('[data-community]').selectOption(cid);await idle();await page.locator('[data-scenario]').selectOption(approvedScenario);await idle();
 }
 page.off('download',trackDownload);
 // A newly reviewed registry cannot silently switch a latest-forecast draft back to original budget.
 await setup('Synthetic later forecast');assert.equal(await page.locator('[data-baseline]').inputValue(),'approved_reforecast');await finishSetup();const selected=()=>page.locator(cell).locator('..').locator('..').locator('td').nth(3);assert.equal(await selected().innerText(),'15,000.00');await page.locator('[data-map]').click();await map().locator('[data-maprow]').first().locator('[data-field=category]').fill('Reviewed forecast rent');await map().locator('[data-reason]').fill('Reviewed classification preserves the selected approved forecast');await map().locator('[data-confirm]').check();await map().locator('[data-save]').click();await map().waitFor({state:'detached'});assert.equal(await selected().innerText(),'15,000.00','Registry readback preserves the selected immutable forecast baseline');assert.equal(await page.locator(cell).inputValue(),'15000');await save('save_draft');
 const rows=await page.evaluate(async cid=>window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})}),cid),draft=rows.find(row=>row.revision.payload.name==='Synthetic later forecast');assert.equal(draft.revision.payload.baselineType,'approved_reforecast');assert.equal(draft.snapshot.lines.find(row=>row.period==='2026-02'&&row.accountCode==='5120').selectedBaseline,15000);assert.equal(draft.snapshot.lines.find(row=>row.period==='2026-02'&&row.accountCode==='5120').originalBudget,1000);
 // Scoped editors retain proposals through ordinary revision saves; only explicit Admin approval activates them.
 const regional=await browser.newPage({viewport:{width:1440,height:1000}});regional.setDefaultTimeout(15000);await regional.goto(url+'/?user=2');await regional.locator('[data-community]').selectOption(cid);await regional.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled);await regional.locator('[data-scenario]').selectOption(draft.head.scenario_id);await regional.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled);await regional.locator('[data-map]').click();const regionalMap=regional.locator('dialog:has([data-maprow])');assert.equal(await regionalMap.locator('[data-save]').count(),0,'Regional has no canonical activation action');await regionalMap.locator('[data-maprow]').first().locator('[data-field=category]').fill('Regional proposed rent grouping');await regionalMap.locator('[data-reason]').fill('Regional reviewed proposed rent grouping for Admin approval');await regionalMap.locator('[data-propose]').click();assert(await regional.locator('[data-pending-mapping]').isVisible());await regional.locator('#fail').click();await regional.locator('[data-action=save_draft]').click();await regional.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled);assert.match((await regional.locator('[role=alert]').allTextContents()).join(' '),/Simulated persistence failure/);assert(await regional.locator('[data-pending-mapping]').isVisible(),'Failed save preserves local mapping proposal');await regional.locator('[data-action=save_draft]').click();await regional.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled);assert.deepEqual(await regional.locator('[role=alert]').allTextContents(),[]);
 const proposed=await regional.evaluate(async({cid,id})=>(await window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})})).find(row=>row.head.scenario_id===id),{cid,id:draft.head.scenario_id});assert.equal(proposed.revision.payload.registryProposal.status,'proposed');assert.equal(proposed.revision.payload.registryProposal.proposedBy,'00000000-0000-0000-0000-000000000002');assert.equal(proposed.revision.payload.registryProposal.registry.accounts[0].category,'Regional proposed rent grouping');assert.equal(proposed.source.registry.version,draft.source.registry.version,'Proposal alone never creates a canonical registry');assert.equal(proposed.source.registry.accounts[0].category,'Reviewed forecast rent');assert(proposed.revision.payload.history.some(row=>row.action==='registry_mapping_proposed'));await regional.close();
 await page.locator('[data-refresh]').click();await idle();await page.locator('[data-scenario]').selectOption(draft.head.scenario_id);await idle();await page.locator('[data-map]').click();assert.equal(await map().locator('[data-maprow]').first().locator('[data-field=category]').inputValue(),'Regional proposed rent grouping');assert.match(await map().locator('[data-proposal-summary]').innerText(),/Test Regional/);await map().locator('[data-save]').click();assert.match(await map().locator('[data-status]').innerText(),/review confirmation/);await map().locator('[data-confirm]').check();await map().locator('[data-save]').click();await map().waitFor({state:'detached'});await save('save_draft');const approvedMapping=await page.evaluate(async({cid,id})=>(await window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})})).find(row=>row.head.scenario_id===id),{cid,id:draft.head.scenario_id});assert.equal(approvedMapping.revision.payload.registryProposal.status,'approved');assert.equal(approvedMapping.revision.payload.registryProposal.approvedRegistryVersionId,approvedMapping.source.registry.version);assert.notEqual(approvedMapping.source.registry.version,draft.source.registry.version);assert.equal(approvedMapping.source.registry.accounts[0].category,'Regional proposed rent grouping');assert(approvedMapping.revision.payload.history.some(row=>row.action==='registry_mapping_approved'));
 // A later full-month close is a separate accuracy overlay, never a rewrite of the published vintage.
 const immutable=rows.find(row=>row.head.scenario_id===approvedScenario),retained=JSON.stringify({snapshot:immutable.snapshot,source:immutable.revision.source});const close=await page.request.post(url+'/__close_fixture_month');assert.equal(close.ok(),true);await page.locator('[data-scenario]').selectOption(approvedScenario);await idle();assert(await page.getByText('Later or revised governed actuals are available for forecast accuracy.',{exact:false}).isVisible());await page.locator('#gap').click();const accuracy=page.locator('details').filter({has:page.locator('summary').getByText('Forecast accuracy by published vintage',{exact:true})});await accuracy.locator('summary').first().click();assert.match(await accuracy.innerText(),/855\.00/);await accuracy.getByText('Accuracy evidence by month and close version',{exact:true}).click();assert.match(await accuracy.innerText(),/30000000-0000-0000-0000-000000000002/);assert.match(await accuracy.innerText(),/13845/);
 const after=await page.evaluate(async cid=>window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})}),cid),unchanged=after.find(row=>row.head.scenario_id===approvedScenario);assert.equal(JSON.stringify({snapshot:unchanged.snapshot,source:unchanged.revision.source}),retained,'Fresh accuracy evidence never rewrites retained revision source or values');assert.equal(unchanged.snapshot.monthly.find(row=>row.period==='2026-02').closed,false);assert.equal(unchanged.snapshot.lines.find(row=>row.period==='2026-02'&&row.accountCode==='5120').actual,null);
 // A failed latest read must not present old close evidence as current accuracy.
 await page.locator('#workspace').click();await page.route('**/__api/rpc/atlas_read_reforecast_source',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Synthetic current actuals temporarily unavailable'})}));await page.locator('[data-scenario]').selectOption(draft.head.scenario_id);await idle();await page.locator('[data-scenario]').selectOption(approvedScenario);await idle();await page.locator('#gap').click();assert.match((await page.locator('[role=alert]').allTextContents()).join(' '),/Current governed actuals.*unavailable/);assert.equal(await page.getByText('855.00',{exact:true}).count(),0);await page.unroute('**/__api/rpc/atlas_read_reforecast_source');assert.deepEqual(errors,[]);
 console.log('PASS UI browser: scoped Regional draft mapping proposals preserve canonical registry until explicit Admin approval, failure/retry retains proposals, first-run canonical registry mapping, fresh later-close accuracy with immutable published source and unavailable-read protection, retained dense edits recover through visible reason, prospective GL addition preserves local mapping fields, cancel retains canonical registry, delayed PDF/XLSX/snapshot downloads stop when community changes, and mapping save preserves latest approved baseline and original budget separately.');
}catch(error){console.error('Public UI status at failure:',await page.locator('dialog [data-status],[role=alert]').allTextContents());throw error;}
finally{await browser.close();if(server){server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}}
