import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mkdir,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {listReportVersions,readReportVersion,buildReportFiles} from '../docs/portfolio-operations-dashboard/features/reforecast-report-library.mjs';
import {verifyOfficialExports} from './publication-export-acceptance.mjs';
import {reportLibraryFixture,ids} from './fixtures/reforecast-report-library-fixture.mjs';
import {PDFDocument,PDFName,PDFDict,PDFArray,PDFRawStream,decodePDFRawStream} from '../docs/portfolio-operations-dashboard/vendor/pdf-lib-1.17.1.mjs';
const XLSX=createRequire(import.meta.url)('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
const options={communityId:ids.community,communityName:'Synthetic Community'};
const visibleText=pdf=>pdf.getPages().flatMap(page=>{const contents=page.node.lookup(PDFName.of('Contents')),streams=contents instanceof PDFArray?Array.from({length:contents.size()},(_,i)=>contents.lookup(i,PDFRawStream)):[contents];return streams.flatMap(stream=>[...new TextDecoder().decode(decodePDFRawStream(stream).decode()).matchAll(/<([a-f0-9]+)>\s*Tj/gi)].map(match=>Buffer.from(match[1],'hex').toString('latin1')));}).join(' ');
async function pdfEvidence(bytes){assert.equal(new TextDecoder().decode(bytes.slice(0,5)),'%PDF-');const pdf=await PDFDocument.load(bytes),attachment=pdf.catalog.lookup(PDFName.of('Names'),PDFDict).lookup(PDFName.of('EmbeddedFiles'),PDFDict).lookup(PDFName.of('Names'),PDFArray).lookup(1,PDFDict).lookup(PDFName.of('EF'),PDFDict).lookup(PDFName.of('F'),PDFRawStream);return {pdf,text:visibleText(pdf),data:JSON.parse(new TextDecoder().decode(decodePDFRawStream(attachment).decode()))};}
function workbookRows(bytes){bytes=bytes instanceof ArrayBuffer?new Uint8Array(bytes):bytes;assert.equal(bytes[0],0x50);assert.equal(bytes[1],0x4b);const book=XLSX.read(bytes,{type:'array',cellFormula:true});for(const name of book.SheetNames)assert(!Object.entries(book.Sheets[name]).some(([key,cell])=>!key.startsWith('!')&&cell.f),'Exported values cannot inject formulas');return {book,rows:book.SheetNames.flatMap(name=>XLSX.utils.sheet_to_json(book.Sheets[name],{defval:null}))};}
const fixture=reportLibraryFixture(),before=JSON.stringify({parent:fixture.parent,str:fixture.str,revisions:fixture.revisions,budget:fixture.budget});
const entries=await listReportVersions(fixture.central,options),approvedEntry=entries.find(row=>row.kind==='approved_forecast'&&row.publicationId===ids.publication),draftEntry=entries.find(row=>row.kind==='saved_revision'&&row.revisionId===ids.draftRevision),strEntry=entries.find(row=>row.kind==='approved_forecast'&&row.publicationId===ids.strPublication);
assert(approvedEntry&&draftEntry&&strEntry,'The library must expose older approved publications beside the current saved draft and separate STR');
assert(entries.some(row=>row.kind==='original_budget'&&row.versionId===ids.budget),'Original budget history remains discoverable');
const approved=await readReportVersion(fixture.central,approvedEntry,options);
assert.equal(approved.publication.publicationId,ids.publication);assert.equal(approved.publication.revisionId,ids.approvedRevision);assert.equal(approved.publication.snapshot.lines[0].forecast,100,'Current draft200 cannot replace old approved100');
const officialXlsx=await buildReportFiles(approved,{format:'xlsx',XLSX,communityName:options.communityName}),officialPdf=await buildReportFiles(approved,{format:'pdf',communityName:options.communityName});assert.equal(officialXlsx.length,1);assert.equal(officialPdf.length,1);assert.equal(officialPdf[0].type,'application/pdf');assert.match(officialXlsx[0].name,/\.xlsx$/);assert.match(officialPdf[0].name,/\.pdf$/);
const officialWorkbook=workbookRows(officialXlsx[0].data),officialDocument=await pdfEvidence(officialPdf[0].data);assert(JSON.stringify(officialWorkbook.rows).includes(ids.publication));assert(JSON.stringify(officialDocument.data).includes(ids.publication));assert(!officialDocument.text.includes('Active NOI'));assert(!officialDocument.text.includes('Active baseline'));assert(officialDocument.text.includes('Approved forecast'),'A superseded version must describe its own approved forecast, not claim current active status');assert.equal(XLSX.utils.sheet_to_json(officialWorkbook.book.Sheets['GL detail'])[0].Active_baseline,100);assert(!officialDocument.text.includes('Current unfinished forecast'));

const officialReconciliation=await verifyOfficialExports({publication:approved.publication,xlsxBytes:new Uint8Array(officialXlsx[0].data),pdfBytes:officialPdf[0].data,options:{communityName:options.communityName,scenarioName:approved.publication.scenarioName}});assert.equal(officialReconciliation.glCells,fixture.parent.snapshot.lines.length);assert.equal(officialReconciliation.monthlyChecks.length,fixture.parent.periods.length);

const draft=await readReportVersion(fixture.central,draftEntry,options),draftFiles=await buildReportFiles(draft,{format:'xlsx',XLSX,communityName:options.communityName}),draftPdf=await buildReportFiles(draft,{format:'pdf',communityName:options.communityName}),draftBook=workbookRows(draftFiles[0].data),draftDoc=await pdfEvidence(draftPdf[0].data);
assert.match(draftFiles[0].name,/DRAFT/i);assert.match(draftPdf[0].name,/DRAFT/i);assert.match(draftDoc.text,/DRAFT/);assert.match(JSON.stringify(draftBook.rows),/DRAFT/);assert(JSON.stringify(draftBook.rows).includes(ids.draftRevision),'Excel retains exact saved revision identity');assert(JSON.stringify(draftDoc.data).includes(ids.draftRevision),'PDF retains exact saved revision identity');assert(JSON.stringify(draftBook.rows).includes(fixture.revisions[0].snapshot.fingerprint));assert(!JSON.stringify(draftBook.rows).includes(ids.publication),'A draft must not acquire an approved publication identity');assert.notEqual(officialXlsx[0].name,draftFiles[0].name);assert.notEqual(officialPdf[0].name,draftPdf[0].name);
const draftNumbers=draftBook.rows.flatMap(row=>Object.values(row));assert(draftNumbers.includes(200.1234)&&draftNumbers.includes(0)&&draftNumbers.includes(-2),'Saved draft exact values, zero and negative amounts survive reopening');
const draftGlRows=XLSX.utils.sheet_to_json(draftBook.book.Sheets['GL detail'],{defval:null}),draftMonthly=XLSX.utils.sheet_to_json(draftBook.book.Sheets['Monthly summary'],{defval:null});
for(const line of fixture.revisions[0].snapshot.lines){const row=draftGlRows.find(row=>row.Period===line.period&&row.GL===line.accountCode);for(const [output,input] of [['Forecast','forecast'],['Original_budget','originalBudget'],['Selected_baseline','selectedBaseline'],['Governed_actuals','actual']])assert.equal(row[output],line[input],'Every draft GL/month preserves its exact saved value');}
for(const month of fixture.revisions[0].snapshot.monthly){const row=draftMonthly.find(row=>row.Period===month.period);for(const [output,input] of [['Income','grossIncome'],['Contra_income','contraRevenue'],['Expenses','expenses'],['NOI','noi'],['Capital','capital']])assert.equal(row[output],month.reforecast[input],'Every draft monthly total preserves its saved value');}
await assert.rejects(()=>buildReportFiles({entry:approvedEntry,publication:fixture.parent},{format:'pdf'}),/read|verif|selection|retained/i,'Fabricated selections cannot bypass exact readback');

const derived=await readReportVersion(fixture.central,strEntry,options);assert.equal(derived.parentPublication.publicationId,ids.publication);const pairFiles=await buildReportFiles(derived,{format:'xlsx',XLSX,communityName:options.communityName});assert.equal(pairFiles.length,2,'STR export preserves a distinct Conventional parent file');assert.equal(new Set(pairFiles.map(file=>file.name)).size,2);const pairBooks=pairFiles.map(file=>workbookRows(file.data));assert(pairBooks.some(book=>book.rows.some(row=>row.Publication===ids.publication)));assert(pairBooks.some(book=>book.rows.some(row=>row.Publication===ids.strPublication)));for(const book of pairBooks)assert(book.rows.some(row=>row.Pair_snapshot),'Both files bind the exact report pair');

const malformed=reportLibraryFixture();malformed.onRead((request,result)=>request.url==='/rpc/atlas_read_reforecast_publication'?{...result,publicationId:ids.strPublication}:result);await assert.rejects(()=>readReportVersion(malformed.central,approvedEntry,options),/readback|identity|publication|match/i);
const changedVersion=reportLibraryFixture();changedVersion.onRead((request,result)=>request.url==='/rpc/atlas_read_reforecast_publication'?{...result,revisionId:ids.draftRevision}:result);await assert.rejects(()=>readReportVersion(changedVersion.central,approvedEntry,options),/revision|identity|readback|match/i);
const wrongParent=reportLibraryFixture();wrongParent.str.snapshot.identity.parentPublication.contentHash='e'.repeat(64);await assert.rejects(async()=>{const selected=await readReportVersion(wrongParent.central,strEntry,options);await buildReportFiles(selected,{format:'xlsx',XLSX});},/ancestor|parent|match|hash/i);
const wrongCommunity=reportLibraryFixture();wrongCommunity.onRead((request,result)=>request.url.startsWith('/atlas_reforecast_revisions?')&&Array.isArray(result)?result.map(row=>({...row,community_id:ids.otherCommunity})):result);await assert.rejects(()=>readReportVersion(wrongCommunity.central,draftEntry,options),/community|scope|readback|match/i);
const changedActor=reportLibraryFixture();changedActor.onRead((request,result)=>{if(request.url==='/rpc/atlas_read_reforecast_publication')changedActor.setActor(ids.otherActor);return result;});await assert.rejects(()=>readReportVersion(changedActor.central,approvedEntry,options),/account|session|actor/i);
for(const revoke of [f=>f.setActor(ids.otherActor),f=>f.profile.status='disabled',f=>f.profile.allowed_community_ids=[],f=>f.config.enabled=false]){const changed=reportLibraryFixture(),read=await readReportVersion(changed.central,approvedEntry,options);revoke(changed);await assert.rejects(()=>buildReportFiles(read,{format:'pdf'}),/account|access|session|actor/i,'Cached verified records cannot be exported after access changes');}
for(const corrupt of [row=>delete row.source,row=>delete row.snapshot.fingerprint]){const broken=reportLibraryFixture();broken.onRead((request,result)=>{if(request.url.startsWith('/atlas_reforecast_revisions?'))for(const row of result)corrupt(row);return result;});await assert.rejects(()=>readReportVersion(broken.central,draftEntry,options),/saved revision|match|readback/i);}
const switched=reportLibraryFixture();let current=true;switched.onRead((request,result)=>{if(request.url==='/rpc/atlas_read_reforecast_publication')current=false;return result;});await assert.rejects(()=>readReportVersion(switched.central,approvedEntry,{...options,guard:()=>{if(!current)throw Error('Selected report changed');}}),/Selected report changed/);
const stable=await readReportVersion(fixture.central,approvedEntry,options);await assert.rejects(()=>buildReportFiles(stable,{format:'pdf',guard:()=>{throw Error('Selection is no longer current');}}),/Selection is no longer current/);
assert.equal(JSON.stringify({parent:fixture.parent,str:fixture.str,revisions:fixture.revisions,budget:fixture.budget}),before,'Exports do not mutate immutable records or the open saved draft');assert(fixture.requests.every(({url,options})=>url==='/rpc/atlas_read_reforecast_publication'||!options.method||options.method==='GET'),'No financial writes');assert(!fixture.requests.some(({url})=>/actual|active_reforecast|finance|source_bundle/.test(url)),'Historical report reads do not require current actuals or baseline resolution');
if(process.env.ATLAS_REPORT_LIBRARY_QA_OUTPUT){
 const folder=process.env.ATLAS_REPORT_LIBRARY_QA_OUTPUT;await mkdir(folder,{recursive:true});
 for(const file of [...officialXlsx,...officialPdf,...draftFiles,...draftPdf,...pairFiles])await writeFile(join(folder,file.name),file.data instanceof ArrayBuffer?new Uint8Array(file.data):file.data);
 await writeFile(join(folder,'report-library-proof.json'),JSON.stringify({synthetic:true,productionAcceptance:false,approvedPublicationId:ids.publication,draftRevisionId:ids.draftRevision,derivedPublicationId:ids.strPublication,officialReconciliation,files:[...new Set([...officialXlsx,...officialPdf,...draftFiles,...draftPdf,...pairFiles].map(file=>file.name))]},null,2)+'\n');
}
console.log('PASS saved-report library: historical approved export while current draft differs and current actuals are unavailable; exact immutable readback; visible DRAFT PDF/XLSX metadata; reopened values; distinct version files; STR exact parent; actor/community/selection guards; fabricated selections denied; no financial writes.');
