const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.join(__dirname,'../docs/portfolio-operations-dashboard'),A='10000000-0000-0000-0000-000000000001',B='10000000-0000-0000-0000-000000000002';
// Execute real navigation/review event handlers against a minimal dialog surface.
class Element{
 constructor(tag){this.tagName=tag;this.children=[];this.nodes=new Map();this.dataset={};this.style={};this.value='';this.isConnected=true;this._html='';this.checked=false;}
 set innerHTML(html){this._html=html;this.children=[];this.nodes=new Map();for(const match of html.matchAll(/\b(data-[\w-]+)(?:="([^"]*)")?/g)){const attr=match[1];if(!this.nodes.has('['+attr+']'))this.nodes.set('['+attr+']',new Element('control'));}if(html.includes('role="status"'))this.nodes.set('[role=status]',new Element('status'));const selected=html.match(/<option value="([^"]+)" selected/);if(selected&&this.nodes.has('[data-community]'))this.nodes.get('[data-community]').value=selected[1];}
 get innerHTML(){return this._html;}
 set textContent(value){this._text=String(value);this.children=[];this.nodes.clear();}get textContent(){return this._text||'';}
 querySelector(q){return this.nodes.get(q)||this.children.map(c=>c.querySelector?.(q)).find(Boolean)||null;}
 querySelectorAll(){return [];}
 append(...items){this.children.push(...items);}prepend(...items){this.children.unshift(...items);}insertBefore(item){this.children.push(item);}replaceChildren(...items){this.children=items;this.nodes.clear();}showModal(){}remove(){this.isConnected=false;}close(){this.onclose?.();this.isConnected=false;}addEventListener(){}
}
(async()=>{
 let actor='reviewer',responseMode='valid',reads=[],applied=[],parsed,saves=[],failSave=true,stages=[],coverageMode='valid',coverageReads=[],pauseStage=false,releaseStage,startStage,stageSources=[];
 const policy={classification:'full_month',fullMonthAllowed:true,reason:'Accounting begins in this reporting month.',carryIn:[{reportedPeriod:'2026-03',sourcePeriod:'2026-02',classification:'prior_period_adjustment',reason:'Startup activity carried into the first full source.'}]};
 const communities=[{community_id:A,display_name:'Doro'},{community_id:B,display_name:'Anthem'}],review={review_id:'review-A',community_id:A,period_key:'2026-03',source_property:'Doro',source_file:'Doro March.pdf',status:'reviewed',certificate:{sourceFile:'Doro March.pdf',sourceHash:'a'.repeat(64),metadata:{period:'2026-03',sourceProperty:'Doro'},checks:[]}};
 const workflow={workflow_id:'workflow-A',community_id:A,period_key:'2026-03',source_file:'Doro March.pdf',status:'classified',source_hash:'a'.repeat(64),current_receipt_id:'receipt-A'};
 const central={getSession:()=>({user:{id:actor}}),readCommunitiesForAccess:async()=>communities,rpc:async()=>{throw Error('Unexpected RPC');},fetchJson:async url=>{reads.push(url);if(url.startsWith('/atlas_community_aliases')||responseMode==='empty')return[];if(url.startsWith('/atlas_financial_intake_receipts'))return[{receipt_id:'receipt-A',workflow_id:responseMode==='wrong-receipt'?'workflow-other':workflow.workflow_id,community_id:A,source_hash:'a'.repeat(64),status:'classified',evidence:{certificate:parsed}}];if(url.startsWith('/atlas_financial_intake_workflows'))return responseMode==='workflow'||responseMode==='wrong-receipt'?[workflow]:[];if(url.startsWith('/atlas_financial_package_reviews'))return[{...review,...(responseMode==='wrong-community'?{community_id:B}:{}),...(responseMode==='wrong-period'?{period_key:'2026-04'}:{})}];throw Error('Unexpected read '+url);}};
 const parent={location:{origin:'https://atlas.test'},ATLAS_CENTRAL:central,atlasAccessDecision:()=>({ok:true})},window={parent},document={body:new Element('body'),createElement:tag=>new Element(tag)},location={origin:'https://atlas.test',href:'https://atlas.test/builder?comparisonPeriod=2026-09'};
 const intakeStates=['uploaded','classified','community_period_confirmed','fully_mapped','reconciled','review_saved','admin_closed','canonically_published','readback_verified'];
 const reviewContext=vm.createContext({window,document,location,URL,Date,AbortController,console,centralClient:()=>central,readFinance:async(client,cids,periods)=>{coverageReads.push({cids,periods});return[{community_id:coverageMode==='wrong-community'?B:cids[0],period_key:periods[0],summary:{communityId:cids[0],period:periods[0],coveragePolicy:coverageMode==='blocked'?{classification:'partial_startup',fullMonthAllowed:false,reason:'No independently reconciled full-month source.'}:policy}}];},INTAKE_STATES:intakeStates,INTAKE_LABELS:intakeStates,evaluateFinancialPackageSafety:c=>({technicalReconciled:c.technicalReconciled}),createIntake:(client,options)=>{const flow={receipt:options.receipt,async stage(stage,certificate){stages.push(stage);stageSources.push({stage,file:certificate.sourceFile});if(pauseStage&&stage==='uploaded'){pauseStage=false;startStage();await new Promise(resolve=>releaseStage=resolve);}flow.receipt={status:stage,receipt_id:certificate.sourceFile+'-'+stage,created_at:'2026-09-23',actor_id:actor};options.onState(flow.receipt);return flow.receipt;}};return flow;},prepareReview:async(client,certificate,options)=>{saves.push({certificate,options});if(failSave)throw Error('Network failed while saving; edits retained.');return{certificate,review,intake:{receipt:{receipt_id:'saved-review-receipt'}}};},applyControls:async(c,r)=>applied.push(r),readPackage:async()=>parsed,resolveCommunity:name=>({communityId:communities.find(c=>c.display_name===name)?.community_id,status:'matched'})});
 const reviewSource=fs.readFileSync(path.join(root,'features/financial-package-review.mjs'),'utf8').replace(/^import .*;\n/gm,'').replace(/\bexport /g,'');vm.runInContext(reviewSource+'\nglobalThis.reviewAPI={openReview,dispose};',reviewContext);
 const navApp={h:{esc:String},go(){},toast(message){throw Error(message);}},R={app:navApp,views:{actuals:()=>''}};
 const navContext=vm.createContext({RBB:R,document:{addEventListener(){}},__loadReview:async()=>reviewContext.reviewAPI});
 vm.runInContext(fs.readFileSync(path.join(root,'budget-navigation.js'),'utf8').replace(/import\('\.\/features\/financial-package-review\.mjs\?v=[^']+'\)/,"__loadReview()"),navContext);
 const controls=new Map(['data-community','data-year','data-refresh','data-file'].map(key=>['['+key+']',{}])),button={dataset:{nextCid:A,nextMonth:'2026-03',nextStep:'actuals'}},container={querySelector:q=>controls.get(q)||null,querySelectorAll:q=>q==='[data-next-cid]'?[button]:[]};
 const uiContext=vm.createContext({console});vm.runInContext(fs.readFileSync(path.join(root,'features/reforecast-ui.mjs'),'utf8').replace(/^import .*;\n/gm,'').replace(/\bexport /g,'')+'\nglobalThis.bindActualsTest=bind;',uiContext);
 uiContext.bindActualsTest({container,R,cid:B,year:2027,dirty:false});await button.onclick();
 let dialog=document.body.children.at(-1);const period=()=>dialog.querySelector('[data-period]'),list=()=>dialog.querySelector('[data-history-list]'),load=()=>dialog.querySelector('[data-load]').onclick();
 assert.equal(period().value,'2026-03');assert.equal(period().disabled,true);
 assert(reads.some(url=>url.startsWith('/atlas_financial_package_reviews')&&url.includes('period_key=eq.2026-03&community_id=eq.'+A)));
 assert(reads.some(url=>url.startsWith('/atlas_financial_intake_workflows')&&url.includes('period_key=eq.2026-03&community_id=eq.'+A)));
 const historyButton=text=>list().children.flatMap(p=>p.children).find(b=>b.textContent===text);
 await historyButton('Read review and close controls').onclick();assert.equal(applied.length,1);assert.equal(applied[0].community_id,A);
 for(const mode of ['wrong-community','wrong-period']){responseMode=mode;await load();assert.match(list().textContent,/scope|period|community/i);assert.equal(list().children.length,0,'Out-of-scope rows never create controls');assert.equal(applied.length,1);}responseMode='valid';
 const upload=async (metadata,sourceFile='fixture.pdf')=>{parsed={metadata,technicalReconciled:true,sourceFile,sourceHash:'a'.repeat(64),sourceBytes:100,rows:[{kind:'posting',glCode:'5120',values:{actual:0}}],checks:[],exceptions:[],intakeEvidence:{rowInventory:[],leafChecks:[],hierarchy:[],mappingVersion:'fixture-1'}};await dialog.querySelector('[data-file]').onchange({target:{files:[{name:'fixture.pdf'}],value:'fixture.pdf'}});};
 await upload({sourceProperty:'Doro',period:'2026-04'});assert.match(dialog.querySelector('[role=status]').textContent,/2026-03/);assert.equal(period().value,'2026-03');
 await upload({sourceProperty:'Anthem',period:'2026-03'});assert.match(dialog.querySelector('[role=status]').textContent,/does not match|different|selected Doro/i);assert.equal(stages.length,0,'Wrong-source upload must not stage under a forced community');
 await upload({sourceProperty:'Doro',period:'2026-03'});assert.deepEqual(stages,['uploaded','classified']);
 const result=dialog.querySelector('[data-result]'),select=result.querySelector('[data-community]'),save=result.querySelector('[data-save]'),message=result.querySelector('[data-saved]');assert.equal(select.value,A);assert.equal(select.disabled,true);assert.match(result.querySelector('[data-coverage-policy]').textContent,/Carry-in disclosure.*2026-02/);assert.deepEqual(JSON.parse(JSON.stringify(coverageReads.at(-1))),{cids:[A],periods:['2026-03']});
 result.querySelector('[data-confirm]').checked=true;result.querySelector('[data-exclusions]').checked=true;await save.onclick();
 assert.equal(saves.length,1);assert.equal(saves[0].certificate.rows[0].values.actual,0);assert.equal(saves[0].options.communityId,A);assert.equal(saves[0].options.period,'2026-03');assert.deepEqual(JSON.parse(JSON.stringify(saves[0].options.coverage)),policy,'Carry-in policy is passed exactly without changing source amounts');assert.match(message.textContent,/Network failed/);assert.doesNotMatch(message.textContent,/Review Saved/);assert.equal(save.disabled,false);assert.equal(select.value,A);assert(result.querySelector('[data-confirm]').checked);assert(result.querySelector('[data-exclusions]').checked);assert.equal(applied.length,1,'Failed persistence cannot expose close controls');
 failSave=false;await save.onclick();assert.match(message.textContent,/Review Saved.*saved-review-receipt/);assert.match(message.textContent,/has not published actuals/);assert.equal(applied.length,2);
 responseMode='wrong-receipt';await load();await historyButton('Read saved intake').onclick();assert.match(dialog.querySelector('[role=status]').textContent,/scope|receipt|workflow/i);assert.deepEqual(stages,['uploaded','classified'],'Mismatched receipt cannot resume an intake');
 await assert.rejects(()=>reviewContext.reviewAPI.openReview({communityId:'10000000-0000-0000-0000-000000000099',period:'2026-03'}),/authorized scope/);
 actor='changed';await load();assert.match(list().textContent,/signed-in account changed/);actor='reviewer';
 responseMode='empty';reads=[];await navApp.openFinancialPackageReview();dialog=document.body.children.at(-1);assert.equal(period().value,'2026-09');assert.notEqual(period().disabled,true);assert(reads.some(url=>url.startsWith('/atlas_financial_package_reviews')&&url.includes('period_key=eq.2026-09')&&!url.includes('community_id=eq.')));
 await upload({sourceProperty:'Doro',period:'2026-03'});let unrestricted=dialog.querySelector('[data-result]'),community=unrestricted.querySelector('[data-community]');assert.equal(community.disabled,false);unrestricted.querySelector('[data-confirm]').checked=true;unrestricted.querySelector('[data-exclusions]').checked=true;coverageMode='blocked';community.value=B;await community.onchange();assert.equal(unrestricted.querySelector('[data-confirm]').checked,false,'Community change resets the explicit identity confirmation');assert.equal(unrestricted.querySelector('[data-exclusions]').checked,false);assert.equal(unrestricted.querySelector('[data-save]').disabled,true);assert.match(unrestricted.querySelector('[data-coverage-policy]').textContent,/partial_startup.*not eligible/);assert.equal(parsed.rows[0].values.actual,0,'Coverage must never alter monthly amounts');
 coverageMode='wrong-community';community.value=A;await community.onchange();assert.equal(unrestricted.querySelector('[data-save]').disabled,true);assert.match(unrestricted.querySelector('[data-coverage-policy]').textContent,/scope mismatch/);
 coverageMode='valid';const started=new Promise(resolve=>startStage=resolve);pauseStage=true;const pendingUpload=upload({sourceProperty:'Doro',period:'2026-03'},'stale.pdf');await started;await upload({sourceProperty:'Doro',period:'2026-03'},'fresh.pdf');const currentReceipt=dialog.querySelector('[data-receipt]').textContent;assert.match(currentReceipt,/fresh.pdf-classified/);releaseStage();await pendingUpload;assert.equal(dialog.querySelector('[data-receipt]').textContent,currentReceipt,'Late source receipt cannot repaint a newer upload');assert(!stageSources.some(x=>x.file==='stale.pdf'&&x.stage==='classified'),'Canceled source cannot advance to a further stage');
 console.log('PASS scoped actuals navigation, community/month/receipt guards, durable-stage display, failed-save edit retention/no false success, explicit review receipt, canonical coverage/carry-in preservation, policy blocking and actor change protection.');
})().catch(e=>{console.error(e);process.exitCode=1;});
