/* Real UI + SQL: independent editor recovery and receipt-first pending writes. */
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright');
const cid='10000000-0000-0000-0000-000000000001',url='http://127.0.0.1:8798';
const server=spawn(process.execPath,['tools/reforecast-harness-server.cjs'],{env:{...process.env,PORT:'8798'},stdio:['ignore','pipe','pipe']});let output='';
await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error(output||'Fixture timed out')),15000);server.once('exit',code=>{clearTimeout(timer);reject(Error('Fixture exited '+code+' '+output));});for(const stream of [server.stdout,server.stderr])stream.on('data',chunk=>{output+=chunk;if(output.includes(url)){clearTimeout(timer);resolve();}});});
const browser=await chromium.launch({headless:true}),context=await browser.newContext(),a=await context.newPage(),b=await context.newPage();
for(const page of [a,b])page.setDefaultTimeout(15000);
const idle=page=>page.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled),cell='[data-gl-cell][data-period="2026-02"][data-code="5120"]';
const recovery=page=>page.evaluate(async()=>{const m=await import('/docs/portfolio-operations-dashboard/features/reforecast-recovery.mjs');return m.listForecastRecovery(window.ATLAS_CENTRAL);});
const rows=page=>page.evaluate(cid=>window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})}),cid);
async function edit(page,amount){await page.locator('[data-dense-reason]').fill('Synthetic reviewed source adjustment');await page.locator('[data-dense-reason]').dispatchEvent('change');await page.locator(cell).fill(String(amount));await page.locator(cell).dispatchEvent('change');await page.waitForFunction(async amount=>{const m=await import('/docs/portfolio-operations-dashboard/features/reforecast-recovery.mjs');return (await m.listForecastRecovery(window.ATLAS_CENTRAL)).some(row=>row.kind==='draft-edit'&&row.payload.overrides.some(value=>value.amount===amount));},amount);}
try{
 await a.goto(url);await a.locator('[data-community]').selectOption(cid);await idle(a);await a.locator('[data-new]').click();await a.locator('[data-name]').fill('Synthetic safe saves');await a.locator('[data-last]').fill('2026-03');await a.locator('[data-last]').dispatchEvent('change');await a.waitForFunction(()=>!document.querySelector('[data-create]')?.disabled);await a.locator('dialog [data-calendar-confirm]').check();await a.locator('[data-create]').click();await a.locator('[data-edit=reviewerId]').selectOption('00000000-0000-0000-0000-000000000001');await a.locator('[data-edit=reason]').fill('Synthetic outbox verification');await a.locator('[data-action=save_draft]').click();await idle(a);
 let saved=(await rows(a))[0];assert.equal(saved.head.revision,1);const scenario=saved.head.scenario_id;
 await a.locator('[data-action=save_draft]').dblclick();assert.equal((await rows(a))[0].head.revision,1,'Repeated Save on an unchanged verified draft creates no revisions');
 await b.goto(url);await b.locator('[data-community]').selectOption(cid);await idle(b);await b.locator('[data-scenario]').selectOption(scenario);await idle(b);
 let release,seen;const gate=new Promise(r=>release=r),started=new Promise(r=>seen=r);await a.route('**/__api/rpc/atlas_save_reforecast_scenario',async route=>{const response=await route.fetch();seen();await gate;await route.fulfill({response});});
 await edit(a,2000);await a.locator('[data-action=save_draft]').click();await started;await edit(b,3000);
 const pending=(await recovery(b)).find(row=>row.kind==='draft-write');assert(pending?.request.requestId);const newer=(await recovery(b)).find(row=>row.kind==='draft-edit'&&row.payload.overrides.some(value=>value.amount===3000));assert(newer);assert.notEqual(newer.id,pending.editId,'Each editor retains its own unsaved copy');
 let bWrites=0;b.on('request',request=>{if(request.url().endsWith('/rpc/atlas_save_reforecast_scenario'))bWrites++;});await b.locator('[data-action=save_draft]').click();await idle(b);assert.match((await b.locator('[role=alert]').allTextContents()).join(' '),/Another save.*awaiting readback/);assert.equal(bWrites,0,'A second tab cannot write over a pending request');assert.deepEqual((await recovery(b)).find(row=>row.kind==='draft-write').request,pending.request,'Newer editing/saving cannot replace an uncertain request');
 release();await idle(a);await a.unroute('**/__api/rpc/atlas_save_reforecast_scenario');assert.equal((await rows(a))[0].head.revision,2);assert((await recovery(b)).some(row=>row.id===newer.id),'First tab completion preserves the second tab edit');assert(!(await recovery(a)).some(row=>row.kind==='draft-write'));
 // A response can be lost after commit. Unavailable receipt must preserve the
 // exact request through refresh and prohibit a second write on recovery.
 let receiptAvailable=false,writes=0;await a.route('**/__api/rpc/atlas_save_reforecast_scenario',async route=>{writes++;await route.fetch();await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Synthetic lost save response'})});});await a.route('**/__api/rpc/atlas_read_reforecast_save_receipt',async route=>{if(writes&&!receiptAvailable)await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Synthetic receipt unavailable'})});else await route.continue();});
 await edit(a,4000);await a.locator('[data-action=save_draft]').click();await a.waitForFunction(()=>document.querySelector('[role=alert]')?.textContent.includes('uncertain'));const retained=(await recovery(a)).find(row=>row.kind==='draft-write');assert(retained);await a.reload();await a.locator('[data-recovery]').click();const recover=a.locator('[data-recover]').filter({hasText:'Recover and verify'});const pendingRow=a.locator('dialog p').filter({hasText:'Save awaiting verified readback'}).filter({has:recover});await pendingRow.first().locator('[data-recover]').click();await a.waitForFunction(()=>document.querySelector('dialog [data-status]')?.textContent.includes('receipt unavailable'));assert.equal(writes,1);assert.deepEqual((await recovery(a)).find(row=>row.kind==='draft-write').request,retained.request);
 receiptAvailable=true;await pendingRow.first().locator('[data-recover]').click();await a.locator('dialog').waitFor({state:'detached'});assert.equal(writes,1,'Verified replay is receipt-only after restart');assert.equal((await rows(a))[0].head.revision,3);assert.equal(await a.locator(cell).inputValue(),'4000');assert(!(await recovery(a)).some(row=>row.kind==='draft-write'));assert((await recovery(a)).some(row=>row.id===newer.id),'Recovery also preserves another tab’s newer edit');
 // Navigation away and back while the receipt read is pending must stay invalid.
 let releaseReceipt,receiptSeen;const receiptGate=new Promise(r=>releaseReceipt=r),receiptStarted=new Promise(r=>receiptSeen=r);await a.unroute('**/__api/rpc/atlas_read_reforecast_save_receipt');await a.route('**/__api/rpc/atlas_read_reforecast_save_receipt',async route=>{const response=await route.fetch();receiptSeen();await receiptGate;await route.fulfill({response});});await edit(a,5000);await a.locator('[data-action=save_draft]').click();await receiptStarted;await a.locator('#gap').click();await a.locator('#workspace').click();releaseReceipt();await idle(a);assert.equal(writes,1,'Navigation round trip cancels the pre-write continuation');assert((await recovery(a)).some(row=>row.kind==='draft-write'),'A canceled continuation keeps its request for deliberate recovery');await a.unroute('**/__api/rpc/atlas_read_reforecast_save_receipt');await edit(a,6000);await a.locator('[data-action=save_draft]').click();await idle(a);assert.equal((await rows(a))[0].head.revision,4);assert.equal(await a.locator(cell).inputValue(),'6000','An explicit correction replaces only this editor’s confirmed-absent request');assert(!(await recovery(a)).some(row=>row.kind==='draft-write'));
 // An old committed receipt can point to a newer head. Its subsequent workspace
 // read must not replace a community or edit chosen while that read is delayed.
 await a.unroute('**/__api/rpc/atlas_save_reforecast_scenario');
 await a.evaluate(async ({cid,pending})=>{const m=await import('/docs/portfolio-operations-dashboard/features/reforecast-recovery.mjs');await m.saveForecastRecovery(window.ATLAS_CENTRAL,'historical-write',{kind:'draft-write',communityId:cid,name:'Historical receipt',request:pending.request});},{cid,pending});
 async function beginPausedHistoricalRead(){
  let release,seen,held=false;const gate=new Promise(r=>release=r),started=new Promise(r=>seen=r);
  await a.route('**/__api/rpc/atlas_read_reforecast_workspace',async route=>{if(held)return route.continue();held=true;const response=await route.fetch();seen();await gate;await route.fulfill({response});});
  await a.locator('[data-recovery]').click();await a.evaluate(()=>{window.__lateRecoveryDialog=document.querySelector('dialog');});await a.locator('dialog p').filter({hasText:'Historical receipt'}).locator('[data-recover]').click();await started;
  assert.equal(await a.locator('dialog [data-recover]:enabled').count(),0,'Only one recovery may run in a dialog');
  return release;
 }
 await a.reload();await a.locator('[data-community]').selectOption(cid);await idle(a);await a.locator('[data-scenario]').selectOption(scenario);await idle(a);
 const releaseCommunity=await beginPausedHistoricalRead();await a.locator('dialog [data-close]').click();
 const otherCommunity='10000000-0000-0000-0000-000000000002';await a.locator('[data-community]').selectOption(otherCommunity);await idle(a);releaseCommunity();
 await a.waitForFunction(()=>/selection changed|Recovery was closed/.test(window.__lateRecoveryDialog?.querySelector('[data-status]')?.textContent));
 assert.equal(await a.locator('[data-community]').inputValue(),otherCommunity,'A delayed latest-head recovery cannot switch back to its prior community');assert.equal(await a.locator(cell).count(),0);assert((await recovery(a)).some(row=>row.id==='historical-write'),'Context cancellation preserves the exact receipt request');await a.unroute('**/__api/rpc/atlas_read_reforecast_workspace');
 await a.reload();await a.locator('[data-community]').selectOption(cid);await idle(a);await a.locator('[data-scenario]').selectOption(scenario);await idle(a);
 const releaseEdit=await beginPausedHistoricalRead();await a.locator('dialog [data-close]').click();await edit(a,7000);releaseEdit();
 await a.waitForFunction(()=>/selection changed|Recovery was closed/.test(window.__lateRecoveryDialog?.querySelector('[data-status]')?.textContent));
 assert.equal(await a.locator(cell).inputValue(),'7000','A delayed latest-head recovery cannot overwrite newer unsaved edits');assert((await recovery(a)).some(row=>row.kind==='draft-edit'&&row.payload.overrides.some(value=>value.amount===7000)));assert((await recovery(a)).some(row=>row.id==='historical-write'));assert.equal((await rows(a))[0].head.revision,4,'Canceled recovery performs no additional write');await a.unroute('**/__api/rpc/atlas_read_reforecast_workspace');
 // A deliberate recovery from another report year/approval view opens the
 // current workspace revision and its actual year, retaining separate edits.
 // Preserve a real, older readback of this SAME scenario in the approval cache.
 let staleApprovalReads=0;await a.route('**/__api/rpc/atlas_read_reforecast_workspace',route=>{staleApprovalReads++;return route.fulfill({contentType:'application/json',body:JSON.stringify([saved])});});
 await a.reload();await a.locator('#approvals').click();await idle(a);await a.locator('[data-year]').fill('2027');await a.locator('[data-year]').dispatchEvent('change');await idle(a);assert(staleApprovalReads>0);await a.unroute('**/__api/rpc/atlas_read_reforecast_workspace');
 await a.locator('[data-recovery]').click();await a.locator('dialog p').filter({hasText:'Historical receipt'}).locator('[data-recover]').click();await a.locator('dialog').waitFor({state:'detached'});await idle(a);
 assert.equal(await a.locator('h2').first().textContent(),'Governed Reforecast Workspace');assert.equal(await a.locator('[data-year]').inputValue(),'2026');assert.equal(await a.locator(cell).inputValue(),'6000','Historical receipt opens the latest verified revision, never its older values');assert(!(await recovery(a)).some(row=>row.id==='historical-write'));assert((await recovery(a)).some(row=>row.kind==='draft-edit'&&row.payload.overrides.some(value=>value.amount===7000)),'Successful historical readback leaves newer editor recovery intact');assert.equal((await rows(a))[0].head.revision,4);
 assert.match(await a.locator(`[data-scenario] option[value="${scenario}"]`).textContent(),/v4$/,'Fresh workspace picker must not inherit the stale approval revision');await a.locator('[data-scenario]').selectOption(scenario);await idle(a);assert.equal(await a.locator(cell).inputValue(),'6000','Re-selecting after recovery cannot reopen cached older approval values');
 // The same-head path must also use the verified revision's reporting year.
 const current=(await rows(a))[0],currentRequest={communityId:cid,scenarioId:scenario,expectedRevision:3,requestId:current.revision.request_id,action:'save_draft',payload:current.revision.payload};
 await a.evaluate(async ({cid,request})=>{const m=await import('/docs/portfolio-operations-dashboard/features/reforecast-recovery.mjs');await m.saveForecastRecovery(window.ATLAS_CENTRAL,'current-write',{kind:'draft-write',communityId:cid,name:'Current receipt',request});},{cid,request:currentRequest});
 await a.locator('#approvals').click();await idle(a);await a.locator('[data-year]').fill('2027');await a.locator('[data-year]').dispatchEvent('change');await idle(a);await a.locator('[data-recovery]').click();await a.locator('dialog p').filter({hasText:'Current receipt'}).locator('[data-recover]').click();await a.locator('dialog').waitFor({state:'detached'});assert.equal(await a.locator('[data-year]').inputValue(),'2026');assert.equal(await a.locator(cell).inputValue(),'6000');assert.equal((await rows(a))[0].head.revision,4);
 console.log('PASS draft outbox: unchanged repeated saves create no revision; cross-tab editing and save cannot replace pending request; exact completion preserves separate newer edits; lost response survives refresh and recovers receipt-only without duplicate revision; late newer-head reads preserve changed community and unsaved edits.');
}finally{await browser.close();server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));}
