import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {normalizeReforecastAccount,parseReforecastWorkbook} from '../docs/portfolio-operations-dashboard/features/reforecast-intake.mjs';
const require=createRequire(import.meta.url),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
for(const [raw,code,name]of [['5120 (Gross Potential Rent (GPR))','5120','Gross Potential Rent (GPR)'],['6333 (Temporary Salaries (Leasing))','6333','Temporary Salaries (Leasing)'],['0012.10 (Repairs (Interior (Non-Turn)))','0012.10','Repairs (Interior (Non-Turn))'],['0012-10 (Cost (Group))','0012-10','Cost (Group)'],['5120 - Rent (GPR)','5120','Rent (GPR)'],['5120','5120','']])assert.deepEqual(normalizeReforecastAccount(raw),{accountCode:code,accountName:name,raw});
for(const raw of ['5120 (Rent (GPR)','5120 (Rent))','5120 (Rent) suffix','5120 ()','5120_Rent','5120 (Rent)(Other)','Budget total','12 (Not a GL)'])assert.equal(normalizeReforecastAccount(raw),null,raw);
const w=XLSX.utils.book_new(),s=XLSX.utils.aoa_to_sheet([['GL','2026-09','2026-10'],['5120 (Gross Potential Rent (GPR))',0,12.34],['6333 (Temporary Salaries (Leasing))',null,5]]);XLSX.utils.book_append_sheet(w,s,'Monthly');
const e=await parseReforecastWorkbook(XLSX.write(w,{type:'array',bookType:'xlsx'}),{xlsx:XLSX,includeOriginalBytes:true});assert.equal(e.parserVersion,'atlas-reforecast-xlsx/3');assert.equal(e.lines.length,4);assert.equal(e.lines.find(l=>l.id==='Monthly!B2').amount,0);assert.equal(e.lines.find(l=>l.id==='Monthly!B3').amount,null);assert.equal(e.lines.find(l=>l.id==='Monthly!C2').accountName,'Gross Potential Rent (GPR)');
if(process.env.ATLAS_DORO_WORKBOOK){
 const bytes=fs.readFileSync(process.env.ATLAS_DORO_WORKBOOK),raw=XLSX.read(bytes,{type:'array',cellFormula:true,cellNF:true,cellStyles:true,sheetStubs:true,bookFiles:true}),sheet=raw.Sheets.Input;
 const columns=[['AW',9],['AX',10],['AY',11],['AZ',12]];
 for(const [column,month]of columns){assert.equal(sheet[column+'14'].v,2026);assert.equal(sheet[column+'15'].v,month);assert.equal(sheet[column+'16'].v,'Plan');}
 // Independent source coverage: identify vendor Account-column labels by
 // their leading GL token, not by the production label normalizer.
 const sourceRows=[];for(const [address,cell]of Object.entries(sheet)){if(!/^J\d+$/.test(address)||typeof cell.v!=='string')continue;const match=/^(\d{3,}(?:[-.]\d+)*)(?=\s|\(|$)/.exec(cell.v.trim());if(!match)continue;const row=Number(address.slice(1));sourceRows.push({accountCode:match[1],accountAddress:address,label:cell.v,row});}
 const actual=await parseReforecastWorkbook(bytes,{xlsx:XLSX,fileName:path.basename(process.env.ATLAS_DORO_WORKBOOK),includeOriginalBytes:true}),lines=actual.lines.filter(l=>l.sheet==='Input'&&l.scenario==='Plan'&&columns.some(([c])=>l.address===c+l.row)),byId=new Map(lines.map(l=>[l.id,l]));
 const numeric=[];for(const row of sourceRows)for(const [column,month]of columns){const address=column+row.row,cell=sheet[address];if(cell?.t==='n'&&typeof cell.v==='number'&&Number.isFinite(cell.v)){const line=byId.get('Input!'+address);assert(line,`Numeric source GL cell ${address} (${row.label}) was dropped`);assert.equal(line.accountCode,row.accountCode);assert.equal(line.period,`2026-${String(month).padStart(2,'0')}`);assert.equal(line.amount,cell.v);assert.equal(line.formula,cell.f||null);numeric.push({id:line.id,code:row.accountCode,zero:cell.v===0});}}
 assert.equal(lines.filter(l=>Number.isFinite(l.amount)).length,numeric.length,'Parser must neither omit nor invent numeric GL cells');assert.equal(new Set(numeric.map(c=>c.id)).size,numeric.length);
 const receipt={actualRawGLCoverage:'passed',parserVersion:actual.parserVersion,rawSourceAccountRows:sourceRows.length,parsedSourceRows:new Set(lines.map(l=>l.row)).size,numericCells:numeric.length,numericGLs:new Set(numeric.map(l=>l.code)).size,explicitZeros:numeric.filter(l=>l.zero).length,sourceLineCount:actual.lines.length,eligibleLineCount:lines.length,eligibleBlankCount:lines.filter(l=>l.amount===null).length,gprCells:numeric.filter(l=>l.code==='5120').map(l=>l.id),sourceHash:actual.source.sha256,coverageMethod:'Independent raw Input account-column leading GL token scan; eligible year, month and scenario headers verified; exact GL, period, signed amount and formula compared for every numeric source cell; missing, invented and duplicate cells rejected',scope:'Read-only local source coverage; not an authenticated save or readback',supersedesNumericCellCount:451};if(process.env.ATLAS_DORO_COVERAGE_RECEIPT)fs.writeFileSync(process.env.ATLAS_DORO_COVERAGE_RECEIPT,JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
}
console.log('PASS balanced nested account labels, preserved raw labels and exact GL tokens, malformed-label rejection, and numeric/zero/blank source relationships.');
