// Visible production intake against isolated production SQL. Synthetic fixture;
// authenticated actual-workbook production acceptance remains a separate gate.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
const cid='10000000-0000-0000-0000-000000000001',url='http://127.0.0.1:18774';
let output='',server=spawn(process.execPath,['tools/reforecast-harness-server.cjs'],{env:{...process.env,PORT:'18774'},stdio:['ignore','pipe','pipe']});
await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(Error(output||'Fixture startup timed out')),20000);server.once('exit',code=>{clearTimeout(timeout);reject(Error('Fixture exited '+code+': '+output));});for(const stream of [server.stdout,server.stderr])stream.on('data',chunk=>{output+=chunk;if(output.includes(url)){clearTimeout(timeout);resolve();}});});
await fs.mkdir('work',{recursive:true});const profile=await fs.mkdtemp('work/atomic-import-profile-');let context,otherBrowser;
const launch=()=>chromium.launchPersistentContext(profile,{headless:true,viewport:{width:1440,height:1000}}),idle=page=>page.waitForFunction(()=>!document.querySelector('[data-refresh]')?.disabled),errors=[];
try{
 context=await launch();let page=context.pages()[0];page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push(error.message));
 await page.goto(url);await page.locator('[data-community]').selectOption(cid);await idle(page);
 const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Scenario','Plan'],['GL','Account','Feb 2026','Mar 2026'],['5120','Rent',1001.25,1002.5],['6100','Payroll',0,210],['6200','Utilities',null,55]]),'Plan');
 await page.locator('[data-file]').setInputFiles({name:'Synthetic Conventional.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))});
 const modal=()=>page.locator('dialog.rfi[open]');
 await modal().locator('[data-property]').selectOption(cid);await modal().locator('[data-assignment-reason]').fill('Reviewed fixture community and workbook');await modal().locator('[data-confirm-property]').check();await modal().locator('[data-prior-version]').selectOption('none');await modal().locator('[data-save-evidence]').click();await modal().locator('[data-scenario]').waitFor();
 await modal().locator('[data-scenario]').selectOption('Plan');await modal().locator('[data-currency]').selectOption('USD');await modal().locator('[data-exact]').click();await modal().locator('[data-calendar]').selectOption('calendar');await modal().locator('[data-start-month]').selectOption('1');await modal().locator('[data-calendar-confirm]').check();await modal().locator('[data-scope]').click();await page.waitForFunction(()=>document.querySelector('dialog.rfi [data-status]')?.textContent.includes('Exact selected forecast authority reviewed'));await modal().locator('[data-input-reason]').fill('Reviewed every finite workbook source amount including zero');await modal().locator('[data-review-inputs]').click();await modal().locator('[data-mapping-reason]').fill('Use exact source GL and month values; retain blank as excluded evidence');await modal().locator('[data-confirm-mapping]').check();await modal().locator('[data-check]').click();assert.match(await modal().locator('[data-review-status]').innerText(),/Ready to save.*5 included cells \(1 explicit zeros\)/);
 // Mapping and workbook bytes survive a full browser process restart.
 await modal().locator('[data-close]').click();await context.close();context=await launch();page=context.pages()[0];page.setDefaultTimeout(20000);page.on('pageerror',error=>errors.push(error.message));await page.goto(url);await page.locator('[data-recovery]').click();await page.locator('[data-recover]').first().click();await modal().locator('[data-scenario]').waitFor();assert.equal(await modal().locator('[data-scenario]').inputValue(),'Plan');assert.equal(await modal().locator('[data-confirm-mapping]').isChecked(),true);assert.equal(await modal().locator('[data-destination]').inputValue(),'new');await modal().locator('[data-check]').click();assert.match(await modal().locator('[data-review-status]').innerText(),/Ready to save/);
 let atomicWrites=0;await page.route('**/__api/rpc/atlas_create_reforecast_from_import',async route=>{atomicWrites++;await route.fetch();await route.abort('failed');});
 await modal().locator('[data-apply]').click();await modal().waitFor({state:'detached'});await idle(page);assert.equal(atomicWrites,1);assert.match(await page.locator('[role=status].rf-success').innerText(),/saved and exact server readback verified/);
 const zero='[data-gl-cell][data-period="2026-02"][data-code="6100"]';assert.equal(await page.locator(zero).inputValue(),'0');assert.equal(await page.locator('[data-gl-cell][data-period="2026-02"][data-code="5120"]').inputValue(),'1001.25');assert.match(await page.locator('[data-detail-key="import-receipt"]').innerText(),/5 imported cells.*1 explicit zeros/);
 const record=await page.evaluate(async cid=>(await window.ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_reforecast_workspace',{method:'POST',body:JSON.stringify({p_community_ids:[cid]})}))[0],cid);assert.equal(record.head.revision,1);const scenarioId=record.head.scenario_id;assert.equal(record.revision.payload.model,'conventional');assert.equal(record.revision.payload.importMapping.sourceScenario,'Plan');
 await page.reload();await page.locator('[data-community]').selectOption(cid);await idle(page);await page.locator('[data-scenario]').selectOption(scenarioId);await idle(page);assert.equal(await page.locator(zero).inputValue(),'0');assert.match(await page.locator('[data-detail-key="import-receipt"]').innerText(),/Every imported GL\/month value matches this screen/);
 otherBrowser=await chromium.launch({headless:true});const other=await otherBrowser.newPage();await other.goto(url+'/?user=2');await other.locator('[data-community]').selectOption(cid);await idle(other);await other.locator('[data-scenario]').selectOption(scenarioId);await idle(other);assert.equal(await other.locator(zero).inputValue(),'0');assert.match(await other.locator('[data-detail-key="import-receipt"]').innerText(),/5 imported cells/);
 await page.locator('[data-dense-reason]').fill('Reviewed continued editable payroll forecast');await page.locator('[data-dense-reason]').dispatchEvent('change');await page.locator(zero).fill('7');await page.locator(zero).dispatchEvent('change');await page.locator('[data-action=save_draft]').click();await idle(page);assert.deepEqual(await page.locator('[role=alert]').allTextContents(),[]);assert.equal(await page.locator(zero).inputValue(),'7');assert.match(await page.locator('[data-detail-key="import-receipt"]').innerText(),/1 imported cells differ/);
 assert.deepEqual(errors,[]);console.log('PASS visible atomic import: immutable evidence, reviewed mapping, new Conventional scenario, exact zero/GL/month values, lost-response receipt recovery without duplicate write, full browser restart before save, refresh, independent authorized second session, persisted reconciliation and continued editing.');
}catch(error){for(const p of context?.pages()||[])console.error('Visible status:',await p.locator('[data-status],[role=alert]').allTextContents());throw error;}finally{await context?.close();await otherBrowser?.close();server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));await fs.rm(profile,{recursive:true,force:true});}
