import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {verifyOfficialExports,reconcilePublicationTotals} from './publication-export-acceptance.mjs';
import {verifyBudgetExportDelivery} from '../docs/portfolio-operations-dashboard/features/budget-export-delivery.mjs';
import {createRequire} from 'node:module';
import {reportLibraryFixture,ids} from './fixtures/reforecast-report-library-fixture.mjs';
import {workbookReportEvidence,workbookCoverageHtml,communityForecastReport,communityForecastWorkbook,reportHtml,reportWorkbook,reportPdf,exportRows,gapRows} from '../docs/portfolio-operations-dashboard/features/reforecast-report.mjs';
import {listReportVersions,readReportVersion,reportVersionPreview,reportVersionPreviewHtml,buildReportFiles} from '../docs/portfolio-operations-dashboard/features/reforecast-report-library.mjs';
import {PDFDocument,PDFName,PDFDict,PDFArray,PDFRawStream,decodePDFRawStream} from '../docs/portfolio-operations-dashboard/vendor/pdf-lib-1.17.1.mjs';
const XLSX=createRequire(import.meta.url)('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
async function pdfEvidence(bytes){const pdf=await PDFDocument.load(bytes),stream=pdf.catalog.lookup(PDFName.of('Names'),PDFDict).lookup(PDFName.of('EmbeddedFiles'),PDFDict).lookup(PDFName.of('Names'),PDFArray).lookup(1,PDFDict).lookup(PDFName.of('EF'),PDFDict).lookup(PDFName.of('F'),PDFRawStream);const data=JSON.parse(new TextDecoder().decode(decodePDFRawStream(stream).decode()));const text=pdf.getPages().flatMap(page=>{const contents=page.node.lookup(PDFName.of('Contents')),streams=contents instanceof PDFArray?Array.from({length:contents.size()},(_,i)=>contents.lookup(i,PDFRawStream)):[contents];return streams.flatMap(s=>[...new TextDecoder().decode(decodePDFRawStream(s).decode()).matchAll(/<([a-f0-9]+)>\s*Tj/gi)].map(m=>Buffer.from(m[1],'hex').toString('latin1')));}).join(' ');return {data,text};}
const f=reportLibraryFixture(),snapshot=f.parent.snapshot;
const metrics=revenue=>({revenue,expenses:0,noi:revenue,cashFlowBeforeNoncash:revenue,nonCashDepreciationAmortization:0,cashFlowAfterNoncash:revenue});
for(const row of snapshot.lines){if(row.accountCode==='5120')Object.assign(row,{forecast:row.period==='2026-09'?100.125:0,disposition:'included',isBlank:false,legitimateBlank:false});else if(row.accountCode==='5250')Object.assign(row,{forecast:null,disposition:'workbook_blank',isBlank:true,legitimateBlank:true});else Object.assign(row,{forecast:null,disposition:'outside_forecast_scope',isBlank:false,legitimateBlank:false,sourceScopeExclusionConfirmed:true});}
for(const row of snapshot.lines){row.workbookSourceAmount=row.forecast;row.workbookSourceDisposition=row.disposition;}
snapshot.workbookCoverage={schemaVersion:1,numericCellCount:2,workbookBlankCellCount:2,sourceAbsentCellCount:0,outsideForecastScopeCellCount:2,reviewerEditedCellCount:0,complete:true,totalsBasis:'known_workbook_values',privateExtra:'PRIVATE',monthly:snapshot.monthly.map((month,i)=>({period:month.period,numericCellCount:1,workbookBlankCellCount:1,sourceAbsentCellCount:0,outsideForecastScopeCellCount:1,reviewerEditedCellCount:0,complete:true,knownValueTotals:metrics(i?0:100.13)}))};
snapshot.knownValueTotals={...metrics(100.13),privateExtra:'PRIVATE'};
snapshot.workbookSourceTotals=structuredClone(snapshot.knownValueTotals);
for(const month of snapshot.monthly){const evidence=snapshot.workbookCoverage.monthly.find(row=>row.period===month.period);month.workbookCoverage={...evidence};delete month.workbookCoverage.knownValueTotals;month.knownValueTotals=evidence.knownValueTotals;month.workbookSourceTotals=structuredClone(evidence.knownValueTotals);month.closed=false;month.reforecast={...metrics(month.period==='2026-09'?100.13:0),grossIncome:month.period==='2026-09'?100.13:0,contraRevenue:0,capital:0};month.actuals={grossIncome:null,contraRevenue:null,expenses:null,capital:null,noi:null};}
f.revisions[0].snapshot=structuredClone(snapshot);const draft=f.revisions[0].snapshot;draft.fingerprint='saved-source-gap';draft.lines.push({period:'2026-09',accountCode:'9999',accountName:'Unresolved source',nature:'expense',placement:'above_noi',forecast:null,originalBudget:30,selectedBaseline:40,actual:null,disposition:'source_absent',isBlank:false,legitimateBlank:false});draft.workbookCoverage.sourceAbsentCellCount=1;draft.workbookCoverage.complete=false;draft.workbookCoverage.monthly[0].sourceAbsentCellCount=1;draft.workbookCoverage.monthly[0].complete=false;draft.monthly[0].workbookCoverage.sourceAbsentCellCount=1;draft.monthly[0].workbookCoverage.complete=false;for(const key of Object.keys(draft.monthly[0].reforecast))draft.monthly[0].reforecast[key]=null;draft.diagnostics=[{severity:'blocking',code:'workbook_source_absent',period:'2026-09',accountCode:'9999',message:'Missing source blocks publication.'}];
const original=JSON.stringify({parent:f.parent,revision:f.revisions[0]});
const evidence=workbookReportEvidence(snapshot);assert.equal(evidence.coverage[0].Workbook_blank_cells,2);assert.equal(evidence.coverage[0].Outside_forecast_scope_cells,2);assert.equal(evidence.knownValues.find(row=>row.Period==='Reviewed workbook scope'&&row.Metric==='Revenue').Known_forecast_value,100.13);assert(!JSON.stringify(evidence).includes('PRIVATE'));
assert.equal(workbookReportEvidence({...snapshot,workbookCoverage:undefined}),null);
assert.throws(()=>workbookReportEvidence({...snapshot,workbookCoverage:{schemaVersion:2}}),/Unsupported/);
const unknown=structuredClone(snapshot);delete unknown.knownValueTotals.noi;delete unknown.workbookCoverage.numericCellCount;assert.equal(workbookReportEvidence(unknown).coverage[0].Numeric_cells,null);assert.equal(workbookReportEvidence(unknown).knownValues.find(row=>row.Period==='Reviewed workbook scope'&&row.Metric==='NOI').Known_forecast_value,null);
for(const options of [{},{account:'5120',periods:['2026-09']},{grain:'year'}]){const html=reportHtml(snapshot,null,options);assert(html.includes('entire reviewed included workbook scope'));assert(html.includes('Known forecast values'));assert(!html.includes('PRIVATE'));}
const year=gapRows(snapshot,null,{grain:'year'}).find(row=>row.accountCode==='5250');assert.equal(year.forecast,null);assert.equal(year.workbookDispositions.length,2);
const rows=exportRows(snapshot,null);assert.equal(rows.find(row=>row.GL==='5120'&&row.Period==='2026-10').Reforecast,0);assert.equal(rows.find(row=>row.GL==='5250').Reforecast,null);assert.match(rows.find(row=>row.GL==='5250').Workbook_disposition,/Verified workbook blank/);
const analysisBook=reportWorkbook(snapshot,null,XLSX),analysisPdf=await pdfEvidence(await reportPdf(snapshot,null));assert.deepEqual(XLSX.utils.sheet_to_json(analysisBook.Sheets['Known forecast values'],{defval:null}),evidence.knownValues);assert.deepEqual(analysisPdf.data.sections.find(s=>s.title==='Workbook source coverage').rows,evidence.coverage);assert(analysisPdf.text.includes('Verified workbook blank (null)'));assert(analysisPdf.text.includes('100.125'));
const blocked=f.parent.snapshot;assert.throws(()=>communityForecastReport({...f.parent,snapshot:draft}),/missing workbook source coverage/);assert.throws(()=>communityForecastReport({...f.parent,snapshot:{...draft,diagnostics:[]}}),/missing workbook source coverage/);assert(workbookCoverageHtml(draft).includes('Incomplete - missing source blocks publication'));
const options={communityId:ids.community,communityName:'Synthetic Community'},entries=await listReportVersions(f.central,options);
for(const [kind,id] of [['approved_forecast',ids.publication],['saved_revision',ids.draftRevision]]){
 const entry=entries.find(row=>row.kind===kind&&(row.publicationId||row.revisionId)===id),selection=await readReportVersion(f.central,entry,options),model=reportVersionPreview(selection,options),html=reportVersionPreviewHtml(selection,options);
 const [excel]=await buildReportFiles(selection,{format:'xlsx',XLSX,...options}),[pdf]=await buildReportFiles(selection,{format:'pdf',...options}),book=XLSX.read(excel.data,{type:'array'}),document=await pdfEvidence(pdf.data);
 for(const [sheet,field,title] of [['Workbook coverage','coverage','Workbook source coverage'],['Known forecast values','knownValues','Known forecast values'],['Workbook source controls','sourceValues','Workbook source controls']]){assert.deepEqual(XLSX.utils.sheet_to_json(book.Sheets[sheet],{defval:null}),model.workbook[field]);assert.deepEqual(document.data.sections.find(row=>row.title===title).rows,model.workbook[field]);assert(html.includes(title));assert(document.text.includes(title));}
 assert.deepEqual(document.data.snapshot,model.snapshot,'PDF and preview use exactly the same retained model');assert(!JSON.stringify(model).includes('PRIVATE'));assert(!document.text.includes('PRIVATE'));
 const detail=XLSX.utils.sheet_to_json(book.Sheets['GL detail'],{defval:null}),blank=detail.find(row=>row.GL==='5250'),excluded=detail.find(row=>row.GL==='6100'),zero=detail.find(row=>row.GL==='5120'&&row.Period==='2026-10'),field=kind==='saved_revision'?'Forecast':'Active_baseline';
 assert.equal(blank[field],null);assert.equal(blank.Original_budget,-1);assert.equal(blank.Selected_baseline,-1);assert.equal(blank.Workbook_source_amount,null);assert.equal(blank.Workbook_source_disposition,'workbook_blank');assert.match(blank.Workbook_disposition,/Verified workbook blank/);assert.equal(excluded[field],null);assert.equal(excluded.Original_budget,11);assert.equal(excluded.Selected_baseline,11);assert.equal(excluded.Workbook_source_amount,null);assert.equal(excluded.Workbook_source_disposition,'outside_forecast_scope');assert.match(excluded.Workbook_disposition,/Reviewed outside forecast scope/);assert.equal(zero[field],0);assert(html.includes('Workbook disposition'));
 if(kind==='approved_forecast'){assert.equal((await verifyOfficialExports({publication:selection.publication,xlsxBytes:new Uint8Array(excel.data),pdfBytes:pdf.data,screenRows:model.rows,screenMonthly:model.monthly,options})).status,'matched');}
 if(kind==='saved_revision'){assert(html.includes('Missing source - blocks publication'));assert(document.text.includes('Missing source - blocks publication'));assert.equal(detail.find(row=>row.GL==='9999').Forecast,null);}else{assert.equal(excel.delivery.delivery_status,'verified');assert.equal(pdf.delivery.delivery_status,'verified');for(const sheetName of ['Workbook coverage','Known forecast values','Workbook source controls']){const tampered=communityForecastWorkbook(selection.publication,XLSX,options),sheet=tampered.Sheets[sheetName];sheet.A2.v='Tampered';await assert.rejects(verifyBudgetExportDelivery(f.central,selection.publication,{format:'xlsx',bytes:XLSX.write(tampered,{type:'array',bookType:'xlsx'}),XLSX,reportOptions:options}),new RegExp(sheetName));await assert.rejects(verifyOfficialExports({publication:selection.publication,xlsxBytes:XLSX.write(tampered,{type:'buffer',bookType:'xlsx'}),pdfBytes:pdf.data,options}),new RegExp(sheetName));}const extra=communityForecastWorkbook(selection.publication,XLSX,options);XLSX.utils.book_append_sheet(extra,XLSX.utils.json_to_sheet([{Injected:'not retained'}]),'Unreviewed totals');await assert.rejects(verifyBudgetExportDelivery(f.central,selection.publication,{format:'xlsx',bytes:XLSX.write(extra,{type:'array',bookType:'xlsx'}),XLSX,reportOptions:options}),/unexpected or reordered/);}
}
const allBlank=structuredClone(f.parent);for(const row of allBlank.snapshot.lines)Object.assign(row,{forecast:null,disposition:'workbook_blank',isBlank:true,legitimateBlank:true});for(const month of allBlank.snapshot.monthly)for(const key of Object.keys(month.reforecast))month.reforecast[key]=0;assert.equal(reconcilePublicationTotals(allBlank).length,2,'Reviewed all-blank contributions aggregate without converting the retained GL nulls');const invalidBlank=structuredClone(allBlank);invalidBlank.snapshot.lines[0].mappingValid=false;assert.throws(()=>reconcilePublicationTotals(invalidBlank),/complete GL detail/,'Blank disposition cannot hide a mapping failure');const unknownBlank=structuredClone(f.parent);delete unknownBlank.snapshot.lines.find(row=>row.disposition==='workbook_blank').legitimateBlank;assert.throws(()=>reconcilePublicationTotals(unknownBlank),/complete GL detail/,'Unverified missing values may not disappear from source reconciliation');
const edited=structuredClone(snapshot),edit=edited.lines.find(row=>row.accountCode==='5250'&&row.period==='2026-09');Object.assign(edit,{forecast:7,disposition:'reviewer_override',isBlank:false,legitimateBlank:false});edited.workbookCoverage.reviewerEditedCellCount=1;edited.knownValueTotals.revenue=107.13;edited.knownValueTotals.noi=107.13;const editedReport=communityForecastReport({...f.parent,snapshot:edited}),editedRow=editedReport.rows.find(row=>row.GL==='5250'&&row.Period==='2026-09');assert.equal(editedRow.Active_baseline,7);assert.equal(editedRow.Workbook_source_amount,null);assert.equal(editedRow.Workbook_source_disposition,'workbook_blank');assert.equal(editedRow.Workbook_disposition,'Reviewed forecast change');assert.equal(editedReport.workbook.coverage[0].Reviewer_edited_cells,1);assert.equal(editedReport.workbook.knownValues.find(row=>row.Period==='Reviewed workbook scope'&&row.Metric==='Revenue').Known_forecast_value,107.13);assert.equal(editedReport.workbook.sourceValues.find(row=>row.Period==='Reviewed workbook scope'&&row.Metric==='Revenue').Workbook_source_value,100.13);
assert.equal(JSON.stringify({parent:f.parent,revision:f.revisions[0]}),original,'Reports do not mutate retained values, flags, comparisons, or history');
// Fixed fingerprints were captured after byte/model parity against the pre-policy
// implementation. This remains meaningful after the change itself is committed.
const legacy=reportLibraryFixture(),hash=value=>createHash('sha256').update(typeof value==='string'?value:JSON.stringify(value)).digest('hex');
assert.equal(hash(communityForecastReport(legacy.parent)),'ddc8db155468853999c0822efc76f684aab5c68669ab6cb53ff3f9cad98e0772');
assert.equal(hash(reportHtml(legacy.parent.snapshot,legacy.parent.source)),'cf531d7d2a5519098a5dfa4ef36758ef1236f6903e24560e236288a58ef9df88');
assert.equal(hash(exportRows(legacy.parent.snapshot,legacy.parent.source)),'28147184c8e068f9638468c96b72656148e2c21ef776f75c892d89e2de178a6c');
assert.deepEqual(reportWorkbook(legacy.parent.snapshot,legacy.parent.source,XLSX).SheetNames,['Forecast detail']);
console.log('PASS workbook coverage and known-value screen/PDF/XLSX parity, exact numeric/null/zero and comparison columns, explicit exclusions, missing-source blocking, private-field allowlists, immutable history, and legacy projection parity.');
