import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {parseSavedStrJson,recoverStrOverlayFromJson,savedStrJsonBytes} from '../docs/portfolio-operations-dashboard/features/reforecast-str-json-recovery.mjs';
const publication={verified:true,approved:true,locked:true,publicationId:'publication',revisionId:'revision',contentHash:'parent-hash',communityId:'community',periods:['2026-09','2026-10','2026-11','2026-12'],source:{},snapshot:{identity:{communityId:'community',mappingRegistryVersion:'mapping',baselineVersionIds:['original-budget']}}};
const payload={formatVersion:1,state:{budgetYear:2026,properties:[{id:'P',name:'Property'}],strPrograms:[{id:'STR',propertyId:'P',operatorId:'rise_internal',name:'RISE',targetUnits:20,config:{adrMode:'monthly',occMode:'monthly',blockedMode:'monthly',adrMonthly:{2026:Array(12).fill(250)},occMonthly:{2026:Array(12).fill(.62)},blockedMonthly:{2026:Array(12).fill(.08)},unitRamp:{2026:[0,0,0,0,0,0,0,0,0,5,10,20]}}}],lines:[{id:'line',propertyId:'P',strProgramId:'STR',gl:'5144',manualMonthly:[0,100]}],strReference:{operator:'Hello Landing',grossIncome:999999}}};
const raw=JSON.stringify(payload),evidence=await parseSavedStrJson(raw,{fileName:'saved.riseb.json'}),before=JSON.stringify(publication),draft=recoverStrOverlayFromJson(evidence,{publication,propertyId:'P',programmeId:'STR',actor:'actor',reason:'Reviewed selected source property'});
assert.equal(new TextDecoder().decode(savedStrJsonBytes(evidence)),raw);assert.equal(draft.strStreams[0].monthly[1].grossPerOccupiedNight,250);assert.equal(draft.strStreams[0].monthly[1].occupancyPercent,62);assert.equal(draft.strRecoveryEvidence.nativeMonthlyCandidates[1].availableUnitCount,5);assert.equal(draft.strRecoveryEvidence.lineEvidence.length,1);assert.equal(draft.strStreams[0].units.length,0,'group counts never invent physical unit IDs');assert.equal(draft.strStreams[0].monthly[1].feePerAvailableUnit,null,'legacy costs are not collapsed into an invented fee');assert.equal(draft.strStreams[0].sourceReviewId,null);assert.equal(draft.strStreams[0].reviewed,false);assert.equal(draft.strStreams[0].incomeAccountCode,'','legacy GL 5144 is retained evidence, not automatic RISE authority');assert.equal(JSON.stringify(publication),before);assert.equal(draft.parentPublication.publicationId,'publication');assert.ok(draft.strRecoveryEvidence.blockers.some(row=>row.code==='saved_str_blocked_nights_review'));assert.equal(draft.overrides.length,0);
const shell=structuredClone(evidence);shell.programmes[0].config=null;const empty=recoverStrOverlayFromJson(shell,{publication,propertyId:'P',programmeId:'STR',actor:'actor',reason:'Retain shell'});assert.ok(empty.strRecoveryEvidence.blockers.some(row=>row.code==='saved_str_config_missing'));assert.equal(empty.strStreams[0].monthly[0].grossPerOccupiedNight,null);
const reference=structuredClone(evidence);reference.programmes[0].operatorId='hello_landing';assert.throws(()=>recoverStrOverlayFromJson(reference,{publication,propertyId:'P',programmeId:'STR',actor:'actor',reason:'Review source'}),/Hello Landing/);
await assert.rejects(()=>parseSavedStrJson('{'),/valid UTF-8/);assert.throws(()=>recoverStrOverlayFromJson(evidence,{publication:{...publication,locked:false},propertyId:'P',programmeId:'STR',actor:'actor',reason:'Review source'}),/verified approved/);
if(process.env.ATLAS_STR_RECOVERY_JSON){
 const path=process.env.ATLAS_STR_RECOVERY_JSON,bytes=await fs.readFile(path),actual=await parseSavedStrJson(bytes,{fileName:path.split('/').at(-1)}),programme=actual.programmes.find(row=>row.operatorId==='rise_internal');assert.ok(programme);const restored=recoverStrOverlayFromJson(actual,{publication,propertyId:programme.propertyId,programmeId:programme.id,actor:'fixture-reviewer',reason:'Test explicit saved programme recovery'});assert.deepEqual(Buffer.from(savedStrJsonBytes(restored.strRecoveryEvidence)),bytes);assert.equal(restored.strRecoveryEvidence.programme.applied,true);assert.equal(restored.strRecoveryEvidence.programme.targetUnits,20);assert.equal(restored.strRecoveryEvidence.lineEvidence.length,31);assert.deepEqual(restored.strRecoveryEvidence.nativeMonthlyCandidates.map(row=>row.availableUnitCount),[0,5,10,20]);assert.deepEqual(restored.strStreams[0].monthly.map(row=>row.grossPerOccupiedNight),[250,250,250,250]);assert.deepEqual(restored.strStreams[0].monthly.map(row=>row.occupancyPercent),[60.69,62,62,60]);assert.equal(restored.strStreams[0].units.length,0);console.log('PASS selected actual 6:09 JSON: exact original bytes, applied programme, 20-unit target, 31 GL lines, Sep–Dec ramp/rates/occupancy preserved; physical roster, blocked-night treatment, signed-fee mapping and approved source review remain explicit blockers.');
}
console.log('PASS STR JSON recovery: immutable parent identity, exact bytes and raw config, native monthly candidates, zero/null distinction, no invented roster or fees, no Hello Landing substitution, no automatic approval or active-baseline change.');
