const assert=require('node:assert/strict'),{randomUUID,createHash}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{const{db,A,B,BUDGET,CLOSE,signIn}=await fixture();
const call=async(name,args)=>(await db.query(`select to_jsonb(${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) as result`,args)).rows[0].result;
const accounts=[['5120','Rent','income','above_noi'],['5220','Vacancy','contra_income','above_noi'],['6100','Payroll','expense','above_noi'],['6200','Utilities','expense','above_noi'],['8100','Capital','capital','below_noi']].map(([accountCode,category,nature,placement])=>({accountCode,category,nature,placement,effectiveFrom:'2026-01'}));
let registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),JSON.stringify({accounts,driverMappings:{payroll:['6100'],utilities:['6200'],occupancy:['5220']},reason:'Reviewed GL placements',effectiveDate:'2026-01-01'})]);
const file=Buffer.from('PKsynthetic workbook fixture');const uploadPayload={propertyAssignment:{communityId:A,confirmed:true},source:{fileName:'Fixture.xlsx',sha256:createHash('sha256').update(file).digest('hex'),originalFile:{encoding:'base64',data:file.toString('base64')}},sheets:[{name:'Input',cells:[{address:'A1',value:0,formula:'1-1'}]}]};
const uid=randomUUID(),upload=await call('atlas_save_reforecast_upload',[A,uid,JSON.stringify(uploadPayload)]);assert.equal((await call('atlas_save_reforecast_upload',[A,uid,JSON.stringify(uploadPayload)])).upload_id,upload.upload_id);
await assert.rejects(()=>call('atlas_save_reforecast_upload',[B,randomUUID(),JSON.stringify(uploadPayload)]),/community/);
const source=await call('atlas_read_reforecast_source',[A,['2026-01','2026-02'],[BUDGET],registry.version_id]);assert.equal(source.actuals.lines.find(l=>l.accountCode==='6100').amount,190);assert.equal(source.baseline.lines.find(l=>l.accountCode==='6100').amount,200);assert.equal(source.actuals.monthly[0].noi,700);
const scenarioId=randomUUID();let payload={name:'Working test',model:'conventional',periods:['2026-01','2026-02'],baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,uploadId:null,ownerId:'00000000-0000-0000-0000-000000000001',reviewerId:'00000000-0000-0000-0000-000000000002',drivers:[{id:'pay',type:'payroll',operation:'percent_change',value:.1}],overrides:[],reason:'Prepared from original'};
const save=(revision,action='save_draft',p=payload,id=randomUUID())=>call('atlas_save_reforecast_scenario',[A,scenarioId,revision,id,action,JSON.stringify(p)]);
let r=await save(0);assert.equal(r.head.status,'working_draft');assert.equal(r.snapshot.lines.find(l=>l.period==='2026-01'&&l.accountCode==='6100').forecast,190);assert.equal(r.snapshot.lines.find(l=>l.period==='2026-02'&&l.accountCode==='6100').forecast,220);assert.equal(r.snapshot.monthly[1].reforecast.noi,680);assert.equal(r.snapshot.monthly[0].actuals.noi,700);assert.equal(r.snapshot.monthly[1].actuals.noi,null);
await assert.rejects(()=>save(0),/another session/);
for(const action of ['reconcile','ready','submit','approve','lock'])r=await save(r.head.revision,action);
assert.equal(r.head.status,'locked');const lockedFingerprint=r.snapshot.fingerprint;
await assert.rejects(()=>save(r.head.revision),/immutable/);
const pubRequest=randomUUID(),pub=await call('atlas_publish_reforecast',[scenarioId,r.head.revision,pubRequest,'Activate reviewed operating benchmark']);assert.equal(pub.snapshot.fingerprint,lockedFingerprint);assert.equal((await call('atlas_publish_reforecast',[scenarioId,r.head.revision,pubRequest,'Activate reviewed operating benchmark'])).publication_id,pub.publication_id);
const active=await call('atlas_read_active_reforecast',[[A],null]);assert.equal(active[0].snapshot.fingerprint,lockedFingerprint);assert.deepEqual(active[0].activePeriods,['2026-01','2026-02']);
const workspace=await call('atlas_read_reforecast_workspace',[[A]]);assert.equal(workspace[0].head.status,'locked');
await signIn(4);assert.deepEqual(await call('atlas_read_reforecast_workspace',[[A]]),[]);await assert.rejects(()=>call('atlas_read_reforecast_source',[A,['2026-02'],null,null]),/denied/);
await signIn(3);await assert.rejects(()=>call('atlas_publish_reforecast',[scenarioId,r.head.revision,randomUUID(),'Forbidden publisher']),/Admin/);
await signIn(1);await assert.rejects(()=>db.query('update atlas_reforecast_heads set revision=999'),/permission denied/);await db.exec('reset role');await assert.rejects(()=>db.query("update atlas_reforecast_revisions set payload='{}'"),/immutable/);
await db.exec('set role anon');await assert.rejects(()=>db.query('select * from atlas_reforecast_publications'),/permission denied/);
await db.exec('reset role');
const tables=(await db.query("select c.relname,c.relrowsecurity,has_table_privilege('anon',c.oid,'SELECT') anon_read,has_table_privilege('authenticated',c.oid,'SELECT') auth_read,has_table_privilege('authenticated',c.oid,'INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') auth_write from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and c.relname like 'atlas_reforecast_%' order by c.relname")).rows;assert.equal(tables.length,7);for(const t of tables){assert.equal(t.relrowsecurity,true,t.relname+' RLS');assert.equal(t.anon_read,false,t.relname+' anon');assert.equal(t.auth_read,true,t.relname+' authenticated read');assert.equal(t.auth_write,false,t.relname+' direct write');}
const functions=(await db.query("select n.nspname,p.proname,p.prosecdef,p.proconfig,has_function_privilege('anon',p.oid,'EXECUTE') anon_exec,has_function_privilege('authenticated',p.oid,'EXECUTE') auth_exec from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','atlas_private') and (p.proname like '%reforecast%' or p.proname='calculate_reforecast')")).rows;assert(functions.length>=12);for(const f of functions){assert.equal(f.anon_exec,false,f.proname+' anonymous execution');assert.equal(f.auth_exec,f.nspname==='public'||f.proname==='reforecast_access',f.proname+' function grant');if(f.prosecdef)assert(f.proconfig.some(setting=>/^search_path=\"?\"?$/.test(setting)),f.proname+' secure search path');}
const draftBudget=randomUUID();await db.query("insert into atlas_approved_budget_versions select $1,community_id,calendar_year,'draft',covered_months,payload,source_file,source_hash from atlas_approved_budget_versions where version_id=$2",[draftBudget,BUDGET]);await signIn(1);const onlyLocked=await call('atlas_read_reforecast_source',[A,['2026-02'],null,registry.version_id]);assert.deepEqual(onlyLocked.baseline.versionIds,[BUDGET]);await assert.rejects(()=>call('atlas_read_reforecast_source',[A,['2026-02'],[draftBudget],registry.version_id]),/not authorized/);

await db.close();console.log('PASS governed reforecast PostgreSQL baseline/actual isolation, driver recalculation, immutable import and review/lock/publish, active readback, RLS');
})().catch(e=>{console.error(e);process.exitCode=1;});
