import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {parseHelloLandingStatement,inspectProviderStatement,providerStatementPublicSummary,mappedProviderStatement,calculateStrLeasingSchedule,recommendStrStatementBehavior,calculateContractDriver,createContractOverride,UTILITY_RELATIONSHIP_CANDIDATES} from '../docs/portfolio-operations-dashboard/features/reforecast-provider.mjs';
const require=createRequire(import.meta.url),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
const communityId='10000000-0000-0000-0000-000000000001',sourceHash='a'.repeat(64);
const metadata={communityId,sourceHash,filename:'synthetic-provider-statement.pdf',mimeType:'application/pdf',uploadedBy:'fixture-editor',uploadedAt:'2026-09-01T00:00:00Z',currency:'USD'};
const unitHeaders=['Unit Number','Occupied Nights','Rent','Utilities','Late Fee','Damages','Parking','Pet','Other','Total Revenue','Net Rent %','Net Rent','Install / Other Fees','FF&E Service Fee','WiFi Service Fee','Partner Adjustment','Net Allocation'];
const reservationHeaders=['Unit Number','Reference ID','Start Date','End Date','Standby','Rent','Utilities','Late Fee','Damages','Parking','Pet','Other','Total Revenue','Net Rent %','Net Rent','Partner Adjustment','Reservation Net'];
// Synthetic identities, dates and detail distribution. Only the provided summary control values are retained.
const unitRows=Array.from({length:20},(_,index)=>{
 const active=index<16,last=index===15,gross=active?(last?1863.67:1500):0,net=active?(last?1462.89:900):0,fee=active?(last?-218.76:-216):0,adjustment=index===0?-155:0,other=index===1?-92.65:0;
 return [`fixture-unit-${index+1}`,active?(last?13:20):0,gross-other,0,0,0,0,0,other,gross,active?`${net/gross*100}%`:'0%',net,0,fee,0,adjustment,Math.round((net+fee+adjustment)*100)/100];
});
const reservationRows=unitRows.filter(row=>row[1]).map((row,index)=>[row[0],`fixture-reservation-${index+1}`,'2026-08-01',`2026-08-${String(row[1]+1).padStart(2,'0')}`,'No',...row.slice(2,10),row[10],row[11],row[15],Math.round((row[11]+row[15])*100)/100]);
const summaryRows=[['Autopilot Revenue Share','synthetic-property'],['Property Name','Synthetic Community','Total Revenue',24363.67],['Month','August 2026','Management Fee',-9400.78],['Occupancy Rate','50.48%','Install / Other Fees',0],['FF&E Service Fee',-3458.76],['WiFi Service Fee',0],['Partner Adjustment',-155],['Net Allocation',11349.13]];
const rows=[...summaryRows,['Unit Level Detail'],unitHeaders,...unitRows,['Reservation Level Detail'],reservationHeaders,...reservationRows];
const money=value=>typeof value==='number'?(value<0?`($${(-value).toFixed(2)})`:`$${value.toFixed(2)}`):value;
const pdfText=[...summaryRows.map(row=>row.map(money).join(' ')),'Unit Level Detail',unitHeaders.join(' '),...unitRows.map(row=>row.map((value,i)=>i>1&&i!==10?money(value):value).join(' ')),'Reservation Level Detail',reservationHeaders.join(' '),...reservationRows.map(row=>row.map((value,i)=>i>=5&&i!==13?money(value):value).join(' '))].join('\n');
const statement=parseHelloLandingStatement({rows,metadata});
assert.equal(statement.status,'reconciled',JSON.stringify(statement.issues));
assert.equal(statement.summary.totalRevenue,24363.67);assert.equal(statement.summary.managementFee,-9400.78);assert.equal(statement.summary.ffeServiceFee,-3458.76);assert.equal(statement.summary.partnerAdjustment,-155);assert.equal(statement.summary.netAllocation,11349.13);
assert.equal(statement.units.length,20);assert.equal(statement.metrics.occupiedUnitNights,313);assert.equal(statement.metrics.availableUnitNights,620);assert.equal(statement.units.filter(row=>row.occupiedNights===0).length,4);assert.equal(statement.units[1].other,-92.65);
assert.equal(statement.metrics.netIncome,null,'Net allocation needs reviewed equivalence mapping.');assert.equal(statement.actualsAuthority,false);
const mapped=parseHelloLandingStatement({rows,metadata,mapping:{reviewState:'approved',version:'mapping-1',netIncomeMetric:'net_allocation'}});assert.equal(mapped.metrics.netIncome,11349.13);
const pdf=parseHelloLandingStatement({text:pdfText,metadata});assert.equal(pdf.status,'reconciled',JSON.stringify(pdf.issues));assert.deepEqual(pdf.summary,statement.summary);assert.equal(pdf.metrics.netRent,14962.89);
const missingRows=structuredClone(rows);missingRows.find(row=>row[0]==='WiFi Service Fee')[1]='';assert.equal(parseHelloLandingStatement({rows:missingRows,metadata}).summary.wifiServiceFee,null);assert.equal(parseHelloLandingStatement({rows:missingRows,metadata}).status,'needs_review');
const badRows=structuredClone(rows);badRows.find(row=>row[0]==='Net Allocation')[1]=11349;assert.equal(parseHelloLandingStatement({rows:badRows,metadata}).status,'needs_review');
const duplicateRows=[...rows,reservationRows[0]];assert.ok(parseHelloLandingStatement({rows:duplicateRows,metadata}).issues.some(row=>row.code==='reservation_identity_conflict'));
assert.equal(parseHelloLandingStatement({rows,metadata:{...metadata,period:'2026-09'}}).status,'needs_review');
assert.equal(parseHelloLandingStatement({rows,metadata:{...metadata,sourceHash:null}}).status,'needs_review');
const publicSummary=providerStatementPublicSummary(statement),serialized=JSON.stringify(publicSummary);assert.ok(!serialized.includes('fixture-unit-'));assert.ok(!serialized.includes('fixture-reservation-'));assert.equal(publicSummary.metrics.occupiedUnitNights,313);assert.equal(publicSummary.periodBasis,'calendar_month');
const workbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(workbook,XLSX.utils.aoa_to_sheet(rows),'Statement');const bytes=XLSX.write(workbook,{type:'array',bookType:'xlsx'});
const read=await inspectProviderStatement(bytes,{...metadata,filename:'synthetic-statement.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',xlsx:XLSX});assert.equal(read.status,'reconciled',JSON.stringify(read.issues));assert.deepEqual(Buffer.from(read.source.originalFile.data,'base64'),Buffer.from(bytes));assert.match(read.source.sha256,/^[a-f0-9]{64}$/);assert.equal(read.source.fileName,'synthetic-statement.xlsx');
const zeroRows=structuredClone(rows);zeroRows.find(row=>row[0]==='WiFi Service Fee')[1]=0;assert.equal(parseHelloLandingStatement({rows:zeroRows,metadata}).summary.wifiServiceFee,0);

const scheduleInput={periods:['2026-08','2026-09'],streams:[{id:'hello_landing',units:[{id:'synthetic-a'},{id:'synthetic-b',takeBackMonth:'2026-09'}],monthly:[{period:'2026-08',occupancyPercent:50,grossPerOccupiedNight:100,netPerOccupiedNight:60},{period:'2026-09',occupancyPercent:50,grossPerOccupiedNight:100,netPerOccupiedNight:60}]},{id:'rise_str',units:[{id:'synthetic-a'}],monthly:[{period:'2026-08',occupancyPercent:100,grossPerOccupiedNight:150},{period:'2026-09',includedUnitIds:[],occupancyPercent:0,grossPerOccupiedNight:150}]}]};
const schedule=calculateStrLeasingSchedule(scheduleInput);assert.equal(schedule.status,'ready');assert.equal(schedule.rows[0].occupiedUnitNights,31);assert.equal(schedule.rows[0].grossIncome,3100);assert.equal(schedule.rows[0].vacancyLoss,-3100);assert.equal(schedule.rows[1].availableUnits,1);assert.equal(schedule.rows[1].grossIncome,1500);assert.equal(schedule.rows[2].grossIncome,4650);assert.equal(schedule.rows[3].grossIncome,0);assert.equal(schedule.rows[2].netIncome,null,'Missing net behavior stays missing.');
assert.equal(schedule.rows[0].grossPotentialIncome,6200);assert.equal(schedule.rows[0].grossPotentialIncome+schedule.rows[0].vacancyLoss,schedule.rows[0].grossIncome,'Post gross potential plus contra vacancy, or post earned/net alone.');
const feeSchedule=structuredClone(scheduleInput);Object.assign(feeSchedule.streams[0].monthly[0],{netMethod:'gross_plus_signed_fees',feePerAvailableUnit:-100});const feeResult=calculateStrLeasingSchedule(feeSchedule).rows[0];assert.equal(feeResult.fees,-200);assert.equal(feeResult.netIncome,2900);assert.equal(feeResult.feesAppliedToNet,true);
delete feeSchedule.streams[0].monthly[0].netMethod;delete feeSchedule.streams[0].monthly[0].netPerOccupiedNight;assert.equal(calculateStrLeasingSchedule(feeSchedule).rows[0].netIncome,null,'Fee sign or net-income method is never inferred.');
assert.throws(()=>calculateStrLeasingSchedule({...scheduleInput,streams:[scheduleInput.streams[0],scheduleInput.streams[0]]}),/unique identifier/);
const duplicateUnits=structuredClone(scheduleInput);duplicateUnits.streams[0].units.push(duplicateUnits.streams[0].units[0]);assert.throws(()=>calculateStrLeasingSchedule(duplicateUnits),/unique identifier/);
assert.throws(()=>calculateStrLeasingSchedule({...scheduleInput,periods:['2026-08-01']}),/full calendar/);
const invalidRoster=structuredClone(scheduleInput);invalidRoster.streams[0].monthly[1].includedUnitIds=['synthetic-b'];assert.equal(calculateStrLeasingSchedule(invalidRoster).rows[1].status,'unavailable');assert.equal(calculateStrLeasingSchedule(invalidRoster).rows[1].grossIncome,null);
const mismatch=structuredClone(scheduleInput);mismatch.streams[0].monthly[0].availableUnits=3;assert.equal(calculateStrLeasingSchedule(mismatch).status,'needs_review');
const missingOccupancy=structuredClone(scheduleInput);delete missingOccupancy.streams[0].monthly[0].occupancyPercent;assert.equal(calculateStrLeasingSchedule(missingOccupancy).rows[0].occupiedUnitNights,null);

const history=['2026-05','2026-06','2026-07'].map((period,index)=>({...mapped,period,reviewState:'approved',readbackVerified:true,metadata:{...metadata,sourceHash:String(index+1).repeat(64)},metrics:{...mapped.metrics,occupiedUnitNights:10*(index+1),grossIncome:1000*(index+1),netIncome:600*(index+1)}}));
const args={statements:history,communityId,provider:'hello_landing',streamId:'hello_landing',asOfPeriod:'2026-08'};
const recommendation=recommendStrStatementBehavior(args);assert.equal(recommendation.status,'proposed');assert.equal(recommendation.grossPerOccupiedNight,100,'Changing unit counts must not average raw totals.');assert.equal(recommendation.netPerOccupiedNight,60);assert.equal(recommendation.evidence.length,3);assert.equal(recommendation.requiresAcceptance,true);
assert.equal(recommendStrStatementBehavior({...args,statements:history.slice(1)}).reason,'insufficient_history');
for(const invalid of [{reviewState:'unreviewed'},{readbackVerified:false},{reopened:true},{stale:true},{periodBasis:'partial_month'},{communityId:'other'},{provider:'other'},{streamId:'other'}]){const changed=structuredClone(history);Object.assign(changed[0],invalid);assert.equal(recommendStrStatementBehavior({...args,statements:changed}).status,'unavailable');}
assert.equal(recommendStrStatementBehavior({...args,statements:[...history,history[0]]}).reason,'ambiguous_statement_vintage');
assert.throws(()=>recommendStrStatementBehavior({...args,weights:[0,0,0]}),/positive total/);
const assumed=recommendStrStatementBehavior({...args,statements:[],reviewedAssumption:{reviewState:'approved',actor:'fixture-user',reviewedAt:'2026-08-01T00:00:00Z',reason:'Reviewed initial assumption',grossPerOccupiedNight:80}});assert.equal(assumed.basis,'reviewed_assumption');

const contract={reviewState:'approved',sourceHash,effectiveFrom:'2026-01',effectiveTo:'2026-12',monthlyAmount:100,escalation:{rate:.1,effectiveMonth:'2026-09',clauseReference:'page 2, clause 4'}};
assert.deepEqual(calculateContractDriver({contract,periods:['2026-08','2026-09']}).map(row=>row.amount),[100,110]);assert.equal(calculateContractDriver({contract:{...contract,reviewState:'unreviewed'},periods:['2026-08']})[0].amount,null);assert.equal(calculateContractDriver({contract:{...contract,effectiveTo:null},periods:['2026-08']})[0].status,'unavailable');
const override={scenarioId:'scenario',revisionId:'revision',periods:['2026-08'],accountCode:'6450',originalValue:100,overrideValue:0,reason:'Approved vacancy',actor:'fixture-user',timestamp:'2026-08-01T00:00:00Z'};assert.equal(createContractOverride(override).overrideValue,0);assert.equal(contract.monthlyAmount,100);assert.throws(()=>createContractOverride({...override,reason:''}),/override needs/);
assert.equal(UTILITY_RELATIONSHIP_CANDIDATES.find(row=>row.accountCode==='5956').relationship,'separate_income');assert.ok(!UTILITY_RELATIONSHIP_CANDIDATES.some(row=>row.incomeAccount==='5956'));
const manualInput={metadata:{...metadata,provider:'rise_str',streamId:'rise_str',period:'2026-08'},fields:{period:'2026-08',currency:'USD',calendarDays:31,availableUnits:2,availableUnitNights:62,occupiedUnitNights:31,occupancyPercent:50,grossIncome:1000,netAllocation:925,feeComponents:[{id:'service_fee',amount:-100},{id:'provider_credit',amount:25}]},mapping:{method:'manual',version:'manual-map-1',confirmed:true,actor:'synthetic-reviewer',reviewedAt:'2026-09-01T00:00:00Z',reason:'Compared mapped fields with original source',periodBasis:'calendar_month',feesComplete:true,sourceReference:'Page 1, monthly summary'}};
const beforeManual=JSON.stringify(manualInput),manual=mappedProviderStatement(manualInput);assert.equal(manual.status,'reconciled',JSON.stringify(manual.issues));assert.equal(manual.reviewState,'unreviewed','Manual field confirmation cannot approve a statement.');assert.equal(manual.metrics.fees,-75);assert.equal(manual.summary.netAllocation,925);assert.equal(manual.metrics.netIncome,null);assert.equal(manual.mappingEvidence.fields.grossIncome.sourceReference,'Page 1, monthly summary');assert.equal(JSON.stringify(manualInput),beforeManual,'Manual mapping preserves the original evidence object.');
const manualNet=mappedProviderStatement({...manualInput,mapping:{...manualInput.mapping,reviewState:'approved',netIncomeMetric:'net_allocation'}});assert.equal(manualNet.metrics.netIncome,925);assert.equal(manualNet.reviewState,'unreviewed');
const perCell=structuredClone(manualInput);perCell.fields.grossIncome={value:'$1,000.00',sourceReference:{sheet:'Monthly statement',address:'B12'}};assert.deepEqual(mappedProviderStatement(perCell).mappingEvidence.fields.grossIncome.sourceReference,{sheet:'Monthly statement',address:'B12'});
for(const [key,value,code] of [['calendarDays',30,'full_calendar_days'],['netAllocation',926,'summary_net_allocation'],['occupiedUnitNights',63,'manual_occupied_capacity_exceeded'],['occupancyPercent',49,'occupancy_percent'],['period','2026-08-15','manual_full_month_required'],['currency','EUR','manual_currency_required']]){const input=structuredClone(manualInput);input.fields[key]=value;assert.ok(mappedProviderStatement(input).issues.some(item=>item.code===code),key);}
const noCurrency=structuredClone(manualInput);noCurrency.fields.currency='';assert.equal(mappedProviderStatement(noCurrency).currency,null);assert.equal(mappedProviderStatement(noCurrency).status,'needs_review');
const blankAmount=structuredClone(manualInput);blankAmount.fields.grossIncome='';assert.equal(mappedProviderStatement(blankAmount).metrics.grossIncome,null);assert.equal(mappedProviderStatement(blankAmount).status,'needs_review');
const noReference=structuredClone(manualInput);delete noReference.mapping.sourceReference;assert.equal(mappedProviderStatement(noReference).status,'needs_review');
const zero=structuredClone(manualInput);Object.assign(zero.fields,{occupiedUnitNights:0,occupancyPercent:0,grossIncome:0,netAllocation:0,feeComponents:[]});assert.equal(mappedProviderStatement(zero).status,'reconciled');assert.equal(mappedProviderStatement(zero).metrics.fees,0);assert.equal(mappedProviderStatement(zero).metrics.grossIncome,0);
const unknownFees=structuredClone(manualInput);delete unknownFees.fields.feeComponents;assert.equal(mappedProviderStatement(unknownFees).metrics.fees,null);assert.equal(mappedProviderStatement(unknownFees).status,'needs_review');
const noUnitCount=structuredClone(manualInput);delete noUnitCount.fields.availableUnits;assert.equal(mappedProviderStatement(noUnitCount).metrics.availableUnits,null);assert.equal(mappedProviderStatement(noUnitCount).status,'reconciled','Explicit capacity nights support comparison when roster count is unavailable.');
const propertyStatement=mappedProviderStatement({...manualInput,metadata:{...manualInput.metadata,provider:'monthly_property_statement',streamId:'rise_str'}});assert.equal(propertyStatement.provider,'monthly_property_statement');assert.equal(propertyStatement.status,'reconciled');
const manualHistory=['2026-05','2026-06','2026-07'].map((period,index)=>({...manualNet,period,reviewState:'approved',readbackVerified:true,sourceHash:String(index+4).repeat(64),metadata:undefined}));const manualRecommendation=recommendStrStatementBehavior({statements:manualHistory,communityId,provider:'rise_str',streamId:'rise_str',asOfPeriod:'2026-08'});assert.equal(manualRecommendation.status,'proposed');assert.equal(manualRecommendation.evidence[0].sourceHash,'4'.repeat(64));assert.equal(recommendStrStatementBehavior({statements:manualHistory.slice(0,2),communityId,provider:'rise_str',streamId:'rise_str',asOfPeriod:'2026-08'}).reason,'insufficient_history');
// Optional source verification: extracted text remains outside the repository and is never logged.
if(process.env.ATLAS_PROVIDER_PDF_TEXT){const source=parseHelloLandingStatement({text:readFileSync(process.env.ATLAS_PROVIDER_PDF_TEXT,'utf8'),metadata});assert.equal(source.status,'reconciled',JSON.stringify(source.issues));assert.equal(source.metrics.occupiedUnitNights,313);assert.equal(source.summary.netAllocation,11349.13);}
console.log('PASS provider PDF text/XLSX and explicit manual monthly mappings, full-month/occupancy/net reconciliation, private-detail boundaries, original bytes, zeros/nulls/signed amounts, normalized approved history, separate STR rosters and take-backs, reviewed contracts, overrides and utility relationships.');
