const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
const migration=name=>fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8');
(async()=>{
 const {db,A,signIn}=await fixture();await db.exec('reset role');
 await db.exec(migration('20260924121641_planning_cell_workbook_integrity_governance.sql'));
 await db.exec(migration('20260924121647_immutable_workbook_audits_and_monthly_governance.sql').split('alter function atlas_private.finance_intake_validation')[0]);
 for(const name of ['20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql','20260925020220_reforecast_import_source_relationships.sql','20260925020222_reforecast_saved_json_str_programme.sql'])await db.exec(migration(name));
 await (await import('./workbook-projection-fixture.mjs')).installProjectionFixture(db);
 await db.exec(migration('20260925020224_reforecast_bounded_request_timeouts.sql'));
 const save='public.atlas_save_reforecast_scenario(uuid,uuid,integer,uuid,text,jsonb)',create='public.atlas_create_reforecast_from_import(uuid,uuid,integer,uuid,uuid,jsonb,jsonb)';
 const meta=async signature=>(await db.query("select proowner,prosecdef,provolatile,prosrc,proconfig,proacl,has_function_privilege('anon',oid,'execute') anon,has_function_privilege('authenticated',oid,'execute') authenticated from pg_proc where oid=$1::regprocedure",[signature])).rows[0];
 assert((await meta(save)).proconfig.includes('statement_timeout=45s'));
 for(const name of ['20260925020226_reforecast_import_source_occurrence_index.sql','20260925071533_reforecast_request_identity_consistency.sql','20260925162050_budget_governed_draft_investor_lifecycle.sql'])await db.exec(migration(name));
 await db.exec("create function atlas_private.budget_calendar(cid uuid) returns jsonb language sql as $$select '{\"verified\":true,\"basis\":\"calendar\",\"startMonth\":1}'::jsonb$$");
 for(const name of ['20260928141143_reviewed_noncash_forecast_presentation.sql','20260928142628_indexed_import_validation_evidence.sql','20260928144620_bounded_reforecast_validation_memory.sql'])await db.exec(migration(name));
 const beforeSave=await meta(save),beforeCreate=await meta(create);
 assert(!beforeSave.proconfig.some(c=>c.startsWith('statement_timeout=')),'reproduce loss when governed wrapper is replaced');assert(beforeCreate.proconfig.includes('statement_timeout=45s'));
 const baselineSettings=(await db.query("select current_setting('statement_timeout') statement,current_setting('lock_timeout') lock,current_setting('search_path') path")).rows[0];
 const repair=migration('20260928150652_governed_reforecast_save_timeout.sql');assert.match(repair,/notify pgrst, 'reload schema'/i);await db.exec(repair);
 const afterSave=await meta(save);assert.deepEqual({...afterSave,proconfig:afterSave.proconfig.filter(c=>!c.startsWith('statement_timeout='))},beforeSave,'only bounded timeout changes; implementation, privileges and search_path are identical');assert(afterSave.proconfig.includes('statement_timeout=45s'));assert.equal(afterSave.prosecdef,false);assert.equal(afterSave.anon,false);assert.equal(afterSave.authenticated,true);
 assert.deepEqual(await meta(create),beforeCreate,'atomic import settings/auth are untouched');assert.deepEqual((await db.query("select current_setting('statement_timeout') statement,current_setting('lock_timeout') lock,current_setting('search_path') path")).rows[0],baselineSettings,'session defaults unchanged');
 await db.exec(repair);assert.deepEqual(await meta(save),afterSave,'repair is replay-safe');
 const args=[A,randomUUID(),0,randomUUID(),'save_draft',{}];
 await db.exec("set role anon");await assert.rejects(()=>db.query('select public.atlas_save_reforecast_scenario($1,$2,$3,$4,$5,$6)',args),/permission denied/);
 await signIn(4);await assert.rejects(()=>db.query('select public.atlas_save_reforecast_scenario($1,$2,$3,$4,$5,$6)',args),/access denied/);
 await signIn(1);await assert.rejects(()=>db.query('select public.atlas_save_reforecast_scenario($1,$2,$3,$4,$5,$6)',[...args.slice(0,4),'vp_approve',{}]),/VP|vice president/i);
 await db.exec('reset role');assert.equal((await db.query('select count(*)::int n from atlas_reforecast_revisions')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from atlas_reforecast_publications')).rows[0].n,0);
 await db.close();console.log('PASS governed save timeout: chronological regression reproduced; save/import45s; schema reload; exact auth/body/search_path preservation; replay-safe; anon/property/VP rejection; no financial mutation');
})().catch(e=>{console.error(e);process.exitCode=1});
