/* Production workspace recovery after source approval and before a working save. */
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createRequire} from 'node:module';
import {parseSavedStrMonthlyProgramme,prepareSavedStrMonthlyContribution} from '../docs/portfolio-operations-dashboard/features/reforecast-str-saved-programme.mjs';
import {savedStrProgrammeDraft} from '../docs/portfolio-operations-dashboard/features/reforecast-str-saved-programme-ui.mjs';
import {prepareStrRegistryExtension} from '../docs/portfolio-operations-dashboard/features/reforecast-str-registry-extension.mjs';
import {readRecoveredDraftSource,readStrRegistryExtension} from '../docs/portfolio-operations-dashboard/features/reforecast-ui.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),root=path.resolve('docs/portfolio-operations-dashboard'),id=n=>'20000000-0000-0000-0000-'+String(n).padStart(12,'0');
const actor=id(1),communityId=id(2),periods=['2026-09','2026-10'],parentRegistry={version:id(3),contentHash:'a'.repeat(64),schemaVersion:2,customClassificationRule:{version:'retained-parent-semantics'},accounts:[{accountCode:'5120',name:'Conventional rent',nature:'income',category:'Revenue',placement:'above_noi',effectiveFrom:'2026-01'}],relationships:[],driverMappings:{},reason:'Immutable parent review',effectiveDate:'2026-01-01'};
const publication={communityId,publicationId:id(4),revisionId:id(5),contentHash:'exact-parent',verified:true,approved:true,locked:true,periods,source:{},snapshot:{identity:{communityId,mappingRegistryVersion:parentRegistry.version,baselineVersionIds:[id(6)]},lines:periods.map(period=>({period,accountCode:'5120',forecast:100.125}))}};
const raw=JSON.stringify({formatVersion:1,state:{properties:[{id:'P',name:'Synthetic source',units:[{id:'group',units:20}]}],strPrograms:[{id:'RISE',propertyId:'P',operatorId:'rise_internal',config:{propertyId:'P',programmeId:'RISE',unitPicks:[{groupId:'group',units:20}],unitRamp:{2026:[0,0,0,0,0,0,0,0,0,5,10,20]}}}],lines:[{id:'income',propertyId:'P',strProgramId:'RISE',gl:'5144',name:'Saved lodging income',nature:'income',yearData:{2026:[0,0,0,0,0,0,0,0,0,20.125,0,0]}}]}});
const evidence=await parseSavedStrMonthlyProgramme(raw,{fileName:'synthetic.riseb.json',propertyId:'P',programmeId:'RISE',periods}),extensionPayload=prepareStrRegistryExtension(parentRegistry,[{sourceLineId:'income',accountCode:'5144',name:'Reviewed lodging income',category:'Revenue',nature:'income',placement:'above_noi',effectiveFrom:'2026-09',reason:'Reviewed exact source line as new canonical lodging income',confirmed:true}],{reason:'Add reviewed source account without changing parent semantics',effectiveDate:'2026-09-01',actor,source:evidence,parentPublicationId:publication.publicationId}),extensionRow={community_id:communityId,version_id:id(9),previous_version_id:parentRegistry.version,content_hash:'b'.repeat(64),payload:extensionPayload},registry={...extensionPayload,version:extensionRow.version_id,contentHash:extensionRow.content_hash};
const review=await prepareSavedStrMonthlyContribution(evidence,{publication,parentRegistry,registry,mappings:[{sourceLineId:'income',sourceGL:'5144',accountCode:'5144',confirmed:true,parentDisposition:'no_parent_publication_row',reason:'Explicit new lodging account preserves the exact absent parent'}],actor,reason:'Review exact additive source and parent',allowHelloLandingGl5144:true});assert.equal(review.ready,true,JSON.stringify(review.blockers));
const receipt={source_receipt_id:id(8),request_id:id(7),community_id:communityId,actor_id:actor,status:'approved',source_hash:evidence.sourceHash,source_fingerprint:evidence.fingerprint,content_hash:'c'.repeat(64),review,registry_extension:{kind:'preserve_parent_accounts',parentRegistryVersion:parentRegistry.version,parentRegistryHash:parentRegistry.contentHash,registryVersion:registry.version,registryHash:registry.contentHash,addedAccountCodes:['5144']}};
const draft=savedStrProgrammeDraft(evidence,review,receipt,{publication,actor}),recovery={kind:'draft-edit',communityId,scenarioId:id(99),expectedRevision:0,name:draft.name,payload:draft},projectRegistry=value=>({version:value.version,accounts:value.accounts,driverMappings:value.driverMappings,relationships:value.relationships,effectiveDate:value.effectiveDate});
const builderSource={communityId,periods,registry:projectRegistry(registry),baseline:{versionIds:[id(6)],sourceType:'approved_reforecast',lines:publication.snapshot.lines.map(row=>({...row,amount:row.forecast})),originalBudgetLines:publication.snapshot.lines.map(row=>({...row,amount:row.forecast})),periodVersions:periods.map(period=>({period,publicationId:publication.publicationId,versionId:publication.revisionId,contentHash:publication.contentHash}))},actuals:{cutoffPeriod:'2026-08',latestFullClosePeriod:'2026-08'}};
// Exact registry reload rejects context/hash substitutions and retains unprojected semantics.
let testRow=structuredClone(extensionRow),testReceipt=structuredClone(receipt),reads=[];
const central={getSession:()=>({user:{id:actor}}),async fetchJson(url,{body}={}){reads.push(url);if(url.startsWith('/atlas_reforecast_registries?'))return [testRow];if(url==='/rpc/atlas_read_reforecast_str_json_source_receipt')return testReceipt;if(url==='/rpc/atlas_read_reforecast_builder_source')return structuredClone(builderSource);throw Error('Unexpected read '+url);}};
const registryArgs={communityId,versionId:registry.version,parentRegistryVersion:parentRegistry.version,parentPublicationId:publication.publicationId,expectedContentHash:registry.contentHash};
assert.deepEqual(await readStrRegistryExtension(central,registryArgs),registry);
for(const patch of [{community_id:id(70)},{version_id:id(70)},{content_hash:'d'.repeat(64)},{previous_version_id:id(70)},{payload:{...extensionPayload,strExtensionParent:{...extensionPayload.strExtensionParent,publicationId:id(70)}}}]){testRow={...extensionRow,...patch};await assert.rejects(()=>readStrRegistryExtension(central,registryArgs),/registry receipt differs/);}testRow=structuredClone(extensionRow);
assert.deepEqual((await readRecoveredDraftSource(central,{communityId,payload:draft})).savedStrSourceReceipts,[receipt]);
for(const changed of ['parent','registry','hash','cell']){const candidate=structuredClone(draft);if(changed==='parent')candidate.parentPublication.publicationId=id(70);if(changed==='registry')candidate.strStreams[0].mappingVersion=id(70);if(changed==='hash')candidate.strRegistryExtension.registryHash='d'.repeat(64);if(changed==='cell')candidate.overrides[1].amount+=1;await assert.rejects(()=>readRecoveredDraftSource(central,{communityId,payload:candidate}),/verification failed/);}
testReceipt=null;reads=[];await assert.rejects(()=>readRecoveredDraftSource(central,{communityId,payload:draft}),/receipt is unavailable/);assert(!reads.includes('/rpc/atlas_read_reforecast_builder_source'),'No unverified preview source should be applied after a missing receipt');testReceipt=receipt;
let mode='unavailable',sourceReads=0,writes=0;
const parentDraft={name:'Approved Conventional',model:'conventional',periods,baselineType:'original_budget',baselineVersionIds:[id(6)],registryVersionId:parentRegistry.version,ownerId:actor,drivers:[],overrides:[],strStreams:[]},parentRecord={head:{scenario_id:id(10),community_id:communityId,revision_id:publication.revisionId,revision:1,status:'locked'},revision:{revision_id:publication.revisionId,scenario_id:id(10),community_id:communityId,payload:parentDraft},source:{...builderSource,registry:projectRegistry(parentRegistry)},snapshot:publication.snapshot};
const html=`<!doctype html><html><body><main id="app"></main><script type="module">import {mountReforecast,reforecastCurrentSnapshot,readStrRegistryExtension} from '/features/reforecast-ui.mjs';import {saveForecastRecovery,readForecastRecovery} from '/features/reforecast-recovery.mjs';const actor=${JSON.stringify(actor)},communityId=${JSON.stringify(communityId)},central={getSession:()=>({user:{id:actor}}),getStoredProfile:()=>({role:'admin'}),readCommunitiesForAccess:async()=>[{community_id:communityId,display_name:'Synthetic community'}],readUserProfiles:async()=>[{user_id:actor,display_name:'Reviewer',role:'admin',status:'active'}],fetchJson:async(p,o)=>{const r=await fetch(p,o);if(!r.ok)throw Error(await r.text());return r.json();}};window.ATLAS_CENTRAL=central;window.recovery=${JSON.stringify(recovery)};window.readRecovery=()=>readForecastRecovery(central,'draft:'+window.recovery.scenarioId);window.seed=()=>saveForecastRecovery(central,'draft:'+window.recovery.scenarioId,window.recovery);window.readRegistry=()=>readStrRegistryExtension(central,${JSON.stringify(registryArgs)});window.state=await mountReforecast(document.querySelector('#app'),{central,hostWindow:window,R:{app:{year:()=>2026,state:{properties:[]},notifyAtlasHeight(){},go(){}}}});window.snapshot=()=>reforecastCurrentSnapshot(window.state);window.ready=true;</script></body></html>`;
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');res.setHeader('content-type','application/json');if(url.pathname==='/atlas_reforecast_registries'){res.end(JSON.stringify([extensionRow]));return;}if(url.pathname==='/atlas_reforecast_publications'){res.end(JSON.stringify([{publication_id:publication.publicationId,revision_id:publication.revisionId,scenario_id:parentRecord.head.scenario_id,community_id:communityId,periods,snapshot:publication.snapshot,source:publication.source}]));return;}if(req.method==='POST'){let body='';for await(const chunk of req)body+=chunk;const args=JSON.parse(body);if(url.pathname.includes('save_'))writes++;let data;switch(url.pathname){case '/rpc/atlas_read_reforecast_str_json_source_receipt':sourceReads++;assert.equal(args.p_request_id,receipt.request_id);if(mode==='unavailable'){res.writeHead(503).end('Synthetic source receipt temporarily unavailable');return;}data=mode==='mismatch'?{...receipt,source_hash:'d'.repeat(64)}:receipt;break;case '/rpc/atlas_read_reforecast_workspace':data=[parentRecord];break;case '/rpc/atlas_read_reforecast_builder_source':data={...builderSource,registry:args.p_registry_version_id===parentRegistry.version?projectRegistry(parentRegistry):projectRegistry(registry)};break;case '/rpc/atlas_read_reforecast_source':data={...builderSource,registry:projectRegistry(parentRegistry)};break;case '/rpc/atlas_read_active_reforecast':data=[];break;case '/rpc/atlas_read_reforecast_publication_history':data=[{publicationId:publication.publicationId,revisionId:publication.revisionId,communityId}];break;case '/rpc/atlas_read_reforecast_publication':data=publication;break;case '/rpc/atlas_read_reforecast_str_mapping_context':data={parentRegistry,currentRegistryVersionId:parentRegistry.version,workbookAccountEvidence:[]};break;default:throw Error('Unexpected endpoint '+url.pathname);}res.end(JSON.stringify(data));return;}if(url.pathname==='/'){res.setHeader('content-type','text/html');res.end(html);return;}const file=path.resolve(root,'.'+url.pathname);if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('content-type','application/javascript');res.end(await fs.readFile(file));}catch(error){res.writeHead(500).end(error.message);}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port,profile=await fs.mkdtemp(path.join(os.tmpdir(),'atlas-str-draft-recovery-'));let context;
try{
 context=await chromium.launchPersistentContext(profile,{headless:true});let page=await context.newPage();page.setDefaultTimeout(10000);await page.goto(base);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>window.seed());await context.close();
 context=await chromium.launchPersistentContext(profile,{headless:true});page=await context.newPage();page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(base);await page.waitForFunction(()=>window.ready);await page.locator('[data-recovery]').click();await page.locator('[data-recover]').click();await page.waitForFunction(()=>document.querySelector('dialog [data-status]')?.textContent.includes('temporarily unavailable'));assert.equal(await page.locator('[data-gl-cell]').count(),0);assert.equal(await page.evaluate(()=>window.state.edit??null),null);assert.equal(await page.evaluate(()=>window.state.cid),'','Failed recovery must not relabel the current workspace');assert.deepEqual(await page.evaluate(()=>window.readRecovery()).then(value=>value.payload),draft);
 mode='mismatch';await page.locator('[data-recover]').click();await page.waitForFunction(()=>document.querySelector('dialog [data-status]')?.textContent.includes('does not match'));assert.equal(await page.locator('[data-gl-cell]').count(),0);assert.equal(writes,0);
 mode='verified';await page.locator('[data-recover]').click();await page.locator('dialog').waitFor({state:'detached'});assert.equal(await page.locator('[data-gl-cell][data-code="5144"][data-period="2026-09"]').inputValue(),'0');assert.equal(await page.locator('[data-gl-cell][data-code="5144"][data-period="2026-10"]').inputValue(),'20.125');assert.match((await page.locator('[role=status]').allTextContents()).join(' '),/UNSAVED working edits recovered/);
 const restored=await page.evaluate(()=>({source:window.state.source,snapshot:window.snapshot()}));assert.deepEqual(restored.source.savedStrSourceReceipts,[receipt]);assert(!restored.snapshot.diagnostics.some(row=>row.code==='saved_str_source_required'));assert(restored.snapshot.lines.filter(row=>row.accountCode==='5144').every(row=>row.originalBudget===null&&row.baselineDisposition.kind==='no_original_budget_row'));assert.equal(restored.snapshot.totals.originalBudget.revenue,200.26);assert.equal(writes,0);assert.equal(sourceReads,3);assert.equal((await page.evaluate(()=>window.readRegistry())).customClassificationRule.version,'retained-parent-semantics');
 // The real main-workspace entry point must pass the full immutable parent, not its builder projection.
 await page.reload();await page.waitForFunction(()=>window.ready);await page.locator('[data-community]').selectOption(communityId);await page.waitForFunction(()=>!document.querySelector('[data-refresh]').disabled);await page.locator('[data-workspace-view=history]').click();await page.waitForFunction(()=>!document.querySelector('[data-refresh]').disabled);await page.locator('[data-open="'+parentRecord.head.scenario_id+'"]').click();await page.waitForFunction(()=>!document.querySelector('[data-refresh]').disabled);await page.locator('[data-str-json]').click();await page.waitForFunction(()=>document.querySelector('[data-programme-file]')||[...document.querySelectorAll('[role=alert]')].some(row=>row.textContent));assert.deepEqual(await page.locator('[role=alert]').allTextContents(),[]);await page.locator('[data-programme-file]').setInputFiles({name:'synthetic.riseb.json',mimeType:'application/json',buffer:Buffer.from(raw)});await page.locator('[data-property]').waitFor();const retainedRegistry=await page.evaluate(async({communityId,publicationId})=>{const {readForecastRecovery}=await import('/features/reforecast-recovery.mjs');return (await readForecastRecovery(window.ATLAS_CENTRAL,'str-json-source:'+communityId+':'+publicationId)).registry;},{communityId,publicationId:publication.publicationId});assert.deepEqual(retainedRegistry,parentRegistry);assert.deepEqual(errors,[]);assert.equal(writes,0);
 console.log('PASS STR draft restart: source receipt read before preview; unavailable/mismatched receipt retains edits with no write; verified exact cells, absent-parent totals and UNSAVED state recover; full immutable registry semantics and hashes survive main UI and extension reload.');
}finally{if(context)await context.close();await new Promise(resolve=>server.close(resolve));await fs.rm(profile,{recursive:true,force:true});}
