import assert from 'node:assert/strict';
import {forecastPermissions,selectedPublicationIds,forecastSetupPayload,applyStrSchedules,forecastGridHtml} from '../docs/portfolio-operations-dashboard/features/reforecast-builder-ui.mjs';
const communityId='10000000-0000-0000-0000-000000000001',periods=['2026-10','2026-11'];
const source={communityId,periods,baseline:{sourceType:'approved_reforecast',versionIds:['original'],periodVersions:periods.map(period=>({period,publicationId:'publication'})),lines:periods.flatMap(period=>[{period,accountCode:'4110',amount:1000},{period,accountCode:'4190',amount:-100}])},registry:{version:'mapping',accounts:[{accountCode:'4110',nature:'income'},{accountCode:'4190',nature:'contra_income'}]},actuals:{closeVersions:[]}};
for(const role of ['admin','executive'])assert.deepEqual(forecastPermissions(role),{edit:true,approve:true});
for(const role of ['regional','centra','community_manager'])assert.deepEqual(forecastPermissions(role),{edit:true,approve:false});
for(const role of ['VP','Central Services','finance','viewer',''])assert.deepEqual(forecastPermissions(role),{edit:false,approve:false});
assert.deepEqual(selectedPublicationIds([{communityId,verified:true,approved:true,locked:true,publicationId:'v1',activePeriods:['2026-10']},{communityId,verified:true,approved:true,locked:true,publicationId:'v2',activePeriods:['2026-11']}],communityId,periods),['v1','v2']);
assert.deepEqual(selectedPublicationIds([{communityId,verified:true,approved:true,locked:true,publicationId:'v1',activePeriods:['2026-10']}],communityId,periods),[]);
assert.deepEqual(selectedPublicationIds([{communityId,verified:false,approved:true,locked:true,publicationId:'v1',activePeriods:periods}],communityId,periods),[]);
const draft=forecastSetupPayload({communityId,periods,model:'mixed',name:'Mixed community',calendar:{basis:'calendar',startMonth:1,confirmed:true},source,streams:['hello_landing','rise_str'],actor:'editor'});
assert.deepEqual(draft.baselinePublicationIds,['publication']);assert.equal(draft.strStreams.length,2);assert.equal(draft.strStreams[0].monthly[0].occupancyPercent,null);assert.equal(draft.calendar.scenario,'Mixed community');
assert.throws(()=>forecastSetupPayload({communityId,periods:['2026-10-15'],source}),/full calendar/);
assert.throws(()=>forecastSetupPayload({communityId:'other',periods,source}),/canonical community/);
const stream={id:'hello_landing',incomeAccountCode:'4110',vacancyAccountCode:'4190',incomeBasis:'gross',application:'replace',assumptionReason:'Reviewed starter assumptions',reviewed:true,units:[{id:'SYNTHETIC-A'},{id:'SYNTHETIC-B',takeBackMonth:'2026-11'}],monthly:periods.map(period=>({period,occupancyPercent:50,grossPerOccupiedNight:100,netPerOccupiedNight:60}))};
const edited={...draft,strStreams:[stream]};let applied=applyStrSchedules(edited,source,{actor:'editor'});
assert.equal(applied.overrides.find(row=>row.period==='2026-10'&&row.accountCode==='4110').amount,6200,'gross potential avoids charging vacancy twice');
assert.equal(applied.overrides.find(row=>row.period==='2026-10'&&row.accountCode==='4190').amount,-3100);
assert.equal(applied.overrides.find(row=>row.period==='2026-11'&&row.accountCode==='4110').amount,3000,'takeback changes future full-month capacity');
assert.equal(applied.overrides.find(row=>row.period==='2026-11'&&row.accountCode==='4190').amount,-1500);
applied=applyStrSchedules({...edited,strStreams:[{...stream,application:'add'}]},source,{actor:'editor'});assert.equal(applied.overrides[0].amount,7200,'mixed conventional keeps selected baseline when explicitly additive');
applied=applyStrSchedules({...edited,strStreams:[{...stream,incomeBasis:'net',vacancyAccountCode:''}]},source,{actor:'editor'});assert.equal(applied.overrides.length,2);assert.equal(applied.overrides[0].amount,1860,'net income is not reduced by vacancy a second time');
const locked=applyStrSchedules(edited,{...source,lockedPeriods:['2026-10']},{actor:'editor'});assert(locked.overrides.every(row=>row.period==='2026-11'));
assert.throws(()=>applyStrSchedules({...edited,overrides:[{period:'2026-10',accountCode:'4110',amount:9}]},source,{actor:'editor'}),/manual override/);
assert.throws(()=>applyStrSchedules({...edited,strStreams:[{...stream,monthly:[{period:'2026-10',occupancyPercent:null}]}]},source,{actor:'editor'}),/Missing history/);
const html=forecastGridHtml({glFilters:{},edit:{}},{lines:[{period:'2026-10',accountCode:'4110',selectedBaseline:null,originalBudget:100,forecast:90,sourceKind:'inherited_locked',immutable:true}]});
assert.match(html,/disabled/);assert.match(html,/<td>100.00<\/td><td>Unavailable<\/td>/,'missing selected baseline never substitutes original');
console.log('PASS forecast setup roles, verified exact coverage, mixed streams, potential/earned/net accounting, unit takebacks, explicit additive baseline, inherited locks and missing-value preservation');
