// Local-only UI regression. Source authority and financial writes are synthetic.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {currentReforecastParserVersion} from '../docs/portfolio-operations-dashboard/features/reforecast-parser-recovery.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),root=path.resolve(import.meta.dirname,'..');
const actor='10000000-0000-0000-0000-000000000001',cid='10000000-0000-0000-0000-000000000002',periods=['2026-09','2026-10','2026-11'];
const data={actor,assignment:{communityId:cid,actorId:actor,explicit:true,confirmed:true,reason:'Synthetic fixture assignment'},evidence:{parserVersion:currentReforecastParserVersion,source:{fileName:'Synthetic mapping.xlsx',sha256:'b'.repeat(64)},metadata:{entities:[],currencies:['USD']},lines:periods.map((period,index)=>({id:'Input!'+String.fromCharCode(65+index)+'1',sheet:'Input',address:String.fromCharCode(65+index)+'1',row:1,column:index+1,accountCode:'4000',department:null,amount:100,period,scenario:'Plan',sourceKind:'workbook_forecast_evidence'})),sheets:[],issues:[],integrity:{fingerprint:'a'.repeat(64),inventory:{sheets:[]},graph:{nodes:[],edges:[]},findings:[]}},source:{sourceVersion:'c'.repeat(64),registry:{version:'synthetic-v1',accounts:[{accountCode:'4000',nature:'income',placement:'above_noi'},{accountCode:'6400',nature:'expense',placement:'above_noi'}]},baseline:{lines:periods.flatMap(period=>[{period,accountCode:'4000',amount:100},{period,accountCode:'6400',amount:40}])},actuals:{cutoffPeriod:'2026-08'}},periods,scenario:'Plan',currency:'USD',reason:'Reviewed synthetic source',calendar:{basis:'calendar',startMonth:1,confirmed:true},accountChoices:{'["Input","4000",null]':{accountCode:'4000',signMultiplier:'1'}},preserveWorkbookBlanks:true,outsideForecastScope:[],reviewedForecastBlanks:[],reviewedForecastBlankReason:''};
let server,browser;
try{
 server=createServer(async(req,res)=>{try{if(req.url==='/'){res.setHeader('content-type','text/html');res.end('<!doctype html><dialog open class="rfi"><p data-status></p><div data-body></div></dialog><div id="recommendations"><div data-recommendations></div></div>');return;}const url=new URL(req.url,'http://local'),filename=path.resolve(root,'.'+url.pathname);if(!filename.startsWith(root+path.sep))throw Error('outside fixture');let text=await fs.readFile(filename,'utf8');if(url.pathname.endsWith('/reforecast-import-ui.mjs'))text+='\nexport {renderMapping,readReviewFields,prepareRecovery};';if(url.pathname.endsWith('/reforecast-ui.mjs'))text+='\nexport {renderRecommendations};';res.setHeader('content-type','text/javascript');res.end(text);}catch(error){res.writeHead(404);res.end(error.message);}});
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));browser=await chromium.launch({headless:true});const page=await browser.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:'+server.address().port+'/');
 const setup=async()=>page.evaluate(async data=>{window.ui=await import('/docs/portfolio-operations-dashboard/features/reforecast-import-ui.mjs');window.state={...data,selected:new Set(data.evidence.lines.map(row=>row.id)),communities:[{community_id:data.assignment.communityId,display_name:'Synthetic'}],el:document.querySelector('dialog'),destination:'new',confirmed:false};state.central={getSession:()=>({user:{id:state.actor},access_token:'synthetic-only',expires_at:Math.floor(Date.now()/1000)+3600})};state.scopedFingerprint=state.evidence.integrity.fingerprint;await ui.prepareRecovery(state);ui.renderMapping(state);},data);
 await setup();await page.locator('[data-review-absent-blanks]').evaluate(el=>el.closest('details').open=true);
 assert.equal(await page.locator('[data-reviewed-forecast-blank]:checked').count(),0,'Never automatically choose a blank disposition');
 await page.locator('[data-review-absent-blanks]').click();assert.match(await page.locator('[data-status]').innerText(),/Enter the reason/);assert.equal(await page.locator('[data-reviewed-forecast-blank]:checked').count(),0);
 await page.locator('[data-forecast-blank-reason]').fill('Keep these open-month accounts blank and editable until planning is complete');await page.locator('[data-review-absent-blanks]').click();assert.equal(await page.locator('[data-reviewed-forecast-blank]:checked').count(),3);assert.equal(await page.locator('[data-outside-scope]:checked').count(),0);
 await page.locator('[data-reviewed-forecast-blank]').first().evaluate(el=>el.closest('details').open=true);await page.locator('[data-outside-scope]').first().check();assert.equal(await page.locator('[data-reviewed-forecast-blank]:checked').count(),2);await page.locator('[data-reviewed-forecast-blank]').first().check();assert.equal(await page.locator('[data-outside-scope]:checked').count(),0);
 const before=await page.evaluate(async()=>{ui.readReviewFields(state);await state.recoveryPromise;const {readForecastRecovery}=await import('/docs/portfolio-operations-dashboard/features/reforecast-recovery.mjs');const saved=await readForecastRecovery(state.central,state.reviewId);return {reviewId:state.reviewId,blanks:saved.fields.reviewedForecastBlanks,reason:saved.fields.reviewedForecastBlankReason};});assert.equal(before.blanks.length,3);
 await page.reload();await setup();const after=await page.evaluate(()=>({reviewId:state.reviewId,blanks:state.reviewedForecastBlanks,reason:state.reviewedForecastBlankReason}));assert.deepEqual(after,before,'Actual IndexedDB review recovery preserves explicit choices and reason');assert.equal(await page.locator('[data-reviewed-forecast-blank]:checked').count(),3);
 await page.evaluate(()=>{state.source.registry.version='new-registry';ui.renderMapping(state);});assert.equal(await page.locator('[data-reviewed-forecast-blank]:checked').count(),0,'Changed registry requires renewed absence decisions');
 await page.evaluate(async()=>{
  document.querySelector('dialog').remove();
  window.forecastUi=await import('/docs/portfolio-operations-dashboard/features/reforecast-ui.mjs');const review={confirmed:true,reviewedBy:'synthetic-reviewer',reviewedAt:'2026-09-29T10:00:00Z',reason:'Keep reviewed forecast blank'};
  window.snapshot={fingerprint:'snapshot',identity:{actualCutoff:'2026-08'},lines:[...['2026-06','2026-07','2026-08'].map(period=>({period,accountCode:'6400',actual:100,selectedBaseline:0,sourceKind:'closed_actual',sourceHash:'verified-source',closeVersionId:'close-'+period,historyEligible:true})),...['2026-09','2026-10'].map(period=>({period,accountCode:'6400',forecast:null,isBlank:true,legitimateBlank:true,disposition:'reviewed_forecast_blank',reviewedForecastBlankConfirmed:true,sourceScopeExclusionConfirmed:false,sourceKind:'forecast',source:{kind:'reviewed_forecast_blank',workbookSourceAbsent:true,uploadId:'synthetic-upload',auditId:'synthetic-audit',sourceHash:'d'.repeat(64),mappingVersion:'synthetic-registry',sourceScenario:'Plan',review:{...review,period,accountCode:'6400'}}}))]};
  const target=document.querySelector('#recommendations');window.recState={actor:'synthetic-reviewer',container:{isConnected:false,querySelector:target.querySelector.bind(target)},edit:{periods:['2026-09','2026-10'],drivers:[],overrides:[],suggestionDecisions:[],history:[]},source:{}};forecastUi.renderRecommendations(recState,snapshot);
 });
 const amount=page.locator('[data-rec-amount]');assert.equal(await amount.count(),1);assert.equal(await amount.inputValue(),'100');assert.match(await page.locator('[data-recommendations]').innerText(),/100\.00 per selected month/);assert.equal((await page.evaluate(()=>recState.edit.drivers)).length,0,'Rendering history estimate never fills a blank');
 await page.locator('[data-rec]').check();await amount.fill('125.5');await page.locator('[data-accept-selected]').click();assert.match(await page.evaluate(()=>recState.error),/reason/);assert.equal((await page.evaluate(()=>recState.edit.drivers)).length,0);
 await page.locator('[data-rec-reason]').fill('Reviewed timing; use revised expected monthly spend');await page.locator('[data-accept-selected]').click();const accepted=await page.evaluate(()=>({drivers:recState.edit.drivers,decisions:recState.edit.suggestionDecisions,error:recState.error}));assert.equal(accepted.error,'');assert.equal(accepted.drivers[0].value,125.5);assert.equal(accepted.drivers[0].evidence.method,'weighted_governed_actual_amount');assert.equal(accepted.decisions[0].proposedValue,100);assert.equal(accepted.decisions[0].appliedValue,125.5);
 await page.evaluate(()=>{const cells=snapshot.lines.filter(row=>row.disposition==='reviewed_forecast_blank'),reviews=cells.map(row=>row.source.review),mapping={version:'synthetic-registry',confirmed:true,reviewedBy:recState.actor,reviewedAt:reviews[0].reviewedAt,sourceScenario:'Plan',periods:cells.map(row=>row.period),selectedLineIds:[],workbookSourcePolicy:{schemaVersion:1,mode:'workbook_exact',blankDisposition:'preserve_null',confirmed:true,reviewedBy:recState.actor,reviewedAt:reviews[0].reviewedAt,reason:'Reviewed exact synthetic source',outsideForecastScope:[],reviewedForecastBlanks:reviews}};recState.edit.uploadId='synthetic-upload';recState.edit.importMapping=mapping;recState.source.workbookReviewedForecastBlankCells=cells.map(row=>({...row,amount:null}));});
 await page.locator('[data-undo]').click();const undone=await page.evaluate(()=>recState.edit);assert.equal(undone.drivers.length,0);assert.equal(undone.suggestionDecisions.length,1);assert.deepEqual(undone.suggestionDecisions,accepted.decisions);assert.equal(undone.history.filter(row=>row.action==='clear_reviewed_forecast_blank').length,2);
 await page.evaluate(()=>forecastUi.renderRecommendations(recState,snapshot));assert.equal(await page.locator('[data-rec]').isEnabled(),true);assert.match(await page.locator('[data-recommendations]').innerText(),/Previously accepted, then cleared; review again/);await page.locator('[data-rec]').check();await page.locator('[data-accept-selected]').click();const reaccepted=await page.evaluate(()=>recState.edit);assert.equal(reaccepted.drivers.length,1);assert.equal(reaccepted.suggestionDecisions.length,2);assert.deepEqual(reaccepted.suggestionDecisions[0],accepted.decisions[0]);assert.equal(reaccepted.suggestionDecisions[0].id,reaccepted.suggestionDecisions[1].id);assert(reaccepted.suggestionDecisions[1].timestamp>=reaccepted.suggestionDecisions[0].timestamp);

 await page.evaluate(()=>{recState.edit={periods:['2026-09','2026-10'],drivers:[],overrides:[],suggestionDecisions:[],history:[]};forecastUi.renderRecommendations(recState,snapshot);});await page.locator('[data-rec]').check();await page.locator('[data-reject-selected]').click();const rejected=await page.evaluate(()=>recState.edit);assert.equal(rejected.drivers.length,0);assert.equal(rejected.suggestionDecisions[0].status,'rejected');assert.deepEqual(errors,[]);
 console.log('PASS intentional forecast blank browser workflow: explicit displayed-only choices, reason gate, mutual exclusion, native IndexedDB recovery, scope invalidation, advisory dollar display, reasoned edited acceptance, append-only undo/reaccept and rejection without autofill.');
}finally{await browser?.close();if(server)await new Promise(resolve=>server.close(resolve));}
