const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');require('fake-indexeddb/auto');const {IDBObjectStore}=require('fake-indexeddb');
const core=fs.readFileSync(require.resolve('../docs/portfolio-operations-dashboard/workspace-core.js'),'utf8'),fn=name=>{const m=core.match(new RegExp('^(?:async )?function '+name+'\\([^\\n]*\\) \\{[\\s\\S]*?^\\}','m'));assert(m);return m[0]};
const open=(name,store='checkpoint')=>new Promise((resolve,reject)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>r.result.createObjectStore(store);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
const io=(db,mode,action)=>new Promise((resolve,reject)=>{const tx=db.transaction('checkpoint',mode);let r;try{r=action(tx.objectStore('checkpoint'))}catch(e){tx.abort();reject(e);return}tx.oncomplete=()=>resolve(r?.result);tx.onabort=tx.onerror=()=>reject(tx.error||r?.error)});
const remove=db=>new Promise((resolve,reject)=>{const name=db.name;db.close();const r=indexedDB.deleteDatabase(name);r.onsuccess=resolve;r.onerror=()=>reject(r.error)});
async function fixture({metadata=true,receipt=false,invalidReceipt=false,scope=true}={}){const name='atlas_replay_checkpoint_'+crypto.randomUUID(),db=await open(name),entry={id:'source',fileHash:'hash',batchId:'batch',reportType:'rent_roll',importStatus:'Approved',communities:['Example']},meta={schemaVersion:1,checkpoint:name,receiptKey:'atlas_replay_receipt_v1:'+name,actor:'actor',access:'scope',database:'primary',identity:'identity',createdAt:'2026-09-28T21:00:00Z',source:{archiveId:'source',fileHash:'hash',reportType:'rent_roll',batchId:'batch'}};await io(db,'readwrite',s=>{s.put({huge:'this old envelope must never be read'},'before');if(metadata)s.put(meta,'metadata')});let downloads=[],alerts=[],access='scope',reads=[];const g={console,Date,JSON,indexedDB,ATLAS_STATE_DB_NAME:'primary',dataImport2State:{sourceArchive:[entry]},dataImportCanManageArchitecture:()=>true,atlasAccessDecision:()=>({ok:true}),atlasDashboardUserCanSeeCommunityName:()=>scope,prompt:()=>name,alert:v=>alerts.push(v),downloadAtlasJsonFile:v=>downloads.push(v),ATLAS_CENTRAL:{getSession:()=>({user:{id:'actor'}}),getAccessContextKey:()=>access},withAtlasStateStore:async(mode,fn)=>{assert.equal(mode,'readonly');return fn({get:key=>{reads.push(key);return receipt?{value:{...meta,status:'committed',publishedAt:'2026-09-28T21:01:00Z',...(invalidReceipt?{actor:'other'}:{})}}:null}})}};g.window=g;vm.createContext(g);vm.runInContext(fn('inspectDataImportReplayReceipt'),g);return {g,db,name,downloads,alerts,reads,setAccess:v=>access=v};}
test('legacy checkpoint inspection never reads before or rewrites/deletes checkpoint',async()=>{const f=await fixture({metadata:false}),get=IDBObjectStore.prototype.get;let beforeReads=0;IDBObjectStore.prototype.get=function(key){if(key==='before'){beforeReads++;throw Error('Forbidden legacy envelope read')}return get.call(this,key)};try{await f.g.inspectDataImportReplayReceipt('source');assert.equal(beforeReads,0);assert.equal(f.downloads[0].outcome,'legacy_or_unavailable_receipt_outcome_unknown');assert.equal(f.downloads[0].retainedCheckpoint,true);assert.equal(f.downloads[0].atomicCommitReceipt,false);assert.equal((await indexedDB.databases()).some(x=>x.name===f.name),true);assert.equal(f.reads.length,1);assert(f.alerts[0].includes('Nothing was restored, saved or deleted'));}finally{IDBObjectStore.prototype.get=get;await remove(f.db)}});
test('future small metadata with no receipt cannot claim a commit',async()=>{const f=await fixture();try{await f.g.inspectDataImportReplayReceipt('source');assert.equal(f.downloads[0].metadataAvailable,true);assert.equal(f.downloads[0].outcome,'no_atomic_commit_receipt_recorded');assert.equal(f.downloads[0].atomicCommitReceipt,false)}finally{await remove(f.db)}});
test('exact atomic receipt is local-only and never a Central/cross-client claim',async()=>{const f=await fixture({receipt:true});try{await f.g.inspectDataImportReplayReceipt('source');assert.equal(f.downloads[0].outcome,'committed_in_this_local_workspace');assert.equal(f.downloads[0].publishedAt,'2026-09-28T21:01:00Z');assert.match(f.downloads[0].limitations,/does not prove Central Save or cross-client persistence/);assert(!Object.hasOwn(f.downloads[0],'imports'));assert(!Object.hasOwn(f.downloads[0],'before'));}finally{await remove(f.db)}});
test('another actor, changed access, or unauthorized source prevents disclosure',async()=>{for(const mode of ['actor','access','source']){const f=await fixture({receipt:true,invalidReceipt:mode==='actor',scope:mode!=='source'});try{if(mode==='access'){const read=f.g.withAtlasStateStore;f.g.withAtlasStateStore=async(...args)=>{const row=await read(...args);f.setAccess('changed');return row}}await f.g.inspectDataImportReplayReceipt('source');assert.equal(f.downloads.length,0);assert.match(f.alerts.at(-1),/does not match|authorized source or workspace changed/);}finally{await remove(f.db)}}});
test('inspection cannot create a missing checkpoint database',async()=>{const f=await fixture({metadata:false});await remove(f.db);await f.g.inspectDataImportReplayReceipt('source');assert.equal(f.downloads[0].retainedCheckpoint,false);assert.equal((await indexedDB.databases()).some(x=>x.name===f.name),false)});
test('non-checkpointed source types cannot prompt for or read receipts',async()=>{for(const reportType of ['box_score','delinquency','leasing_resident_data']){const f=await fixture();try{f.g.dataImport2State.sourceArchive[0].reportType=reportType;f.g.prompt=()=>{throw Error('No checkpoint prompt is valid for this route')};await f.g.inspectDataImportReplayReceipt('source');assert.equal(f.reads.length,0);assert.equal(f.downloads.length,0);assert.match(f.alerts[0],/only for Rent Roll and Trending Occupancy/)}finally{await remove(f.db)}}});

test('current publication refuses a pre-existing receipt before invoking worker publication',async()=>{let publications=0;const g={console,ATLAS_STATE_COMMUNITY_KEY:'communities',getAtlasRenderContextKey:()=> 'same',buildSerializedSavedDataPayload:()=>({zero:0}),serializeDataImport2State:()=>({historyStorage:{view:'full'}}),queueAtlasStateWrite:async task=>task(),dataImportHistoryRevision:1,dataImportHistoryOperation:async operation=>{if(operation==='records')return {records:[{value:{zero:0},hash:'community-hash'},{value:{existing:true},hash:'receipt-hash'}]};publications++;throw Error('Unexpected publication')},AtlasOccupancyReplay:null};g.window=g;vm.createContext(g);vm.runInContext(fn('persistDataImportPublication'),g);await assert.rejects(()=>g.persistDataImportPublication({receiptKey:'existing',assertCurrent(){},assertRecords:async()=>{},ownWrite(){},publicationReceipt:()=>({status:'committed'})}),/receipt already exists/);assert.equal(publications,0)});
