import assert from 'node:assert/strict';import {createRequire} from 'node:module';
import {riseWorkbookBytes} from '../docs/portfolio-operations-dashboard/features/rise-workbook-export.mjs';
import {RISE_REPORT_LOGO} from '../docs/portfolio-operations-dashboard/features/rise-report-brand.mjs';
const require=createRequire(import.meta.url),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js');
const wb=XLSX.utils.book_new(),sheet=XLSX.utils.aoa_to_sheet([['GL','January','February','Total'],['004100',0,null,null],['006200',1234.56789,-40.33,null]]);sheet.D3={t:'n',v:1194.23789,f:'SUM(B3:C3)',z:'#,##0.00'};sheet['!autofilter']={ref:'A1:D3'};XLSX.utils.book_append_sheet(wb,sheet,'GL detail');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Snapshot','Status'],['hash-1','Investor Approved']]),'Evidence');wb.Workbook={Names:[{Name:'LocalTotal',Ref:"'GL detail'!$D$3",Sheet:0}]};const before=structuredClone(wb);
const bytes=riseWorkbookBytes(wb,XLSX,{title:'Approved Budget',communityName:'RISE Sample',version:4,status:'Pending Investor Approval',periods:['2026-01','2026-02'],snapshotFingerprint:'hash-1'});assert.deepEqual(wb,before,'Never mutate the financial workbook/snapshot');
const read=XLSX.read(bytes,{type:'array',cellFormula:true,cellNF:true});assert.equal(read.SheetNames[0],'RISE Report');for(const name of before.SheetNames){assert.deepEqual(XLSX.utils.sheet_to_json(read.Sheets[name],{header:1,defval:null,raw:true}),XLSX.utils.sheet_to_json(before.Sheets[name],{header:1,defval:null,raw:true}));}assert.equal(read.Sheets['GL detail'].D3.f,'SUM(B3:C3)');assert.equal(read.Sheets['GL detail'].B2.v,0);assert.equal(read.Sheets['GL detail'].C2,undefined);assert.equal(read.Sheets['GL detail'].A2.v,'004100');assert.equal(read.Workbook.Names.find(n=>n.Name==='LocalTotal').Sheet,1);
const zip=XLSX.CFB.read(bytes,{type:'buffer'}),text=p=>new TextDecoder().decode(XLSX.CFB.find(zip,'Root Entry/'+p).content);assert(text('xl/drawings/riseLogo.xml').includes('rIdRiseImage'));assert(text('xl/drawings/_rels/riseLogo.xml.rels').includes('../media/riseLogo.png'));assert(text('xl/worksheets/_rels/sheet3.xml.rels').includes('rIdRiseLogo'));assert(text('xl/worksheets/sheet3.xml').includes('<drawing r:id="rIdRiseLogo"/>'));assert(text('xl/styles.xml').includes('FF126F8A'));assert(text('xl/styles.xml').includes('FF173B45'));assert(text('[Content_Types].xml').includes('image/png'));assert.deepEqual(Buffer.from(XLSX.CFB.find(zip,'Root Entry/xl/media/riseLogo.png').content),Buffer.from(RISE_REPORT_LOGO.split(',')[1],'base64'));
console.log('PASS branded Excel cover, existing logo/drawing relationships, RISE colors, financial roundtrip, exact precision, missing vs zero, formula and named-range preservation, no mutation.');
