/* Production saved-programme UI + real SQL; synthetic source data only. */
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),{fixture}=require('./reforecast-fixture.cjs'),{db,A:cid,signIn}=await fixture(),root=path.resolve('docs/portfolio-operations-dashboard');
await db.exec('reset role');await db.exec("create function atlas_private.resolve_workbook_audit(a jsonb,h text) returns jsonb language sql as $$select a$$");
for(const name of ['20260924121641_planning_cell_workbook_integrity_governance.sql','20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260925174317_shared_str_programme_draft_versions.sql'])await db.exec(await fs.readFile('supabase/migrations/'+name,'utf8'));
const property={id:'source',name:'Test Community',units:[{id:'group',units:20}]},config={propertyId:'source',programmeId:'applied',name:'Retained 31-style programme',adr:100,unitPicks:[{groupId:'group',units:20}]},lines=[{id:'rent',propertyId:'source',strProgramId:'applied',gl:'5144',name:'STR revenue',nature:'income',yearData:{2026:Array(12).fill(100)}},{id:'cost',propertyId:'source',strProgramId:'applied',gl:'6100',name:'STR expense',nature:'expense',yearData:{2026:[null,0,...Array(10).fill(10)]}}],programmes=[{id:'other',propertyId:'source',name:'Other programme',applied:false,config:null,lineIds:[]},{id:'applied',propertyId:'source',name:config.name,applied:true,config,lineIds:lines.map(row=>row.id)}];
const source={formatVersion:1,state:{properties:[property],strPrograms:programmes,lines,activeProperty:'source',activeScenario:'working',scenarios:[{id:'working',name:'Browser Working Draft'}]},ui:{strCfg:config},libraries:{}};
const html=`<!doctype html><html><head><meta charset="utf-8"></head><body><div id="content"></div><p id="toast"></p><script src="/assets/xlsx.full.min.js"></script><script type="module">
import {installSavedStrProgrammes} from '/features/saved-str-programmes.mjs';const original=${JSON.stringify(source)};window.actor=Number(new URL(location.href).searchParams.get('user')||1);const user=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');window.ATLAS_CENTRAL={getSession:()=>({user:{id:user(window.actor)}}),refreshSession:async()=>{},readCommunitiesForAccess:async()=>[{community_id:${JSON.stringify(cid)},display_name:'Test Community'}],fetchJson:async(route,options={})=>{const res=await fetch(route,{...options,headers:{...options.headers,'content-type':'application/json','x-user':window.actor}});const value=await res.json();if(!res.ok)throw Error(value.message);return value;}};
const state=structuredClone(original.state),R={YEARS:[2026],views:{},budgetNavigation:{groups:[['budget','Budget',['strbuild']]]},persist:{serialize:()=>({libraries:{}}),snapshotUndo(){}},strBuilder:{apply(){window.calculatorCalls++;throw Error('No implicit recalculation permitted');}}};window.calculatorCalls=0;R.app={state,strCfg:structuredClone(original.ui.strCfg),view:'strbuild',VIEWS:[],year:()=>2026,scenario:()=>state.scenarios[0],isLocked:()=>false,go(view){this.view=view;this.render();},render(){document.querySelector('#content').innerHTML=R.views[this.view]();},invalidate(){},touch(){},toast(message){document.querySelector('#toast').textContent=message;}};R.views.strbuild=()=>'<h1>STR Builder</h1><label>ADR<input data-adr value="'+R.app.strCfg.adr+'"></label><button data-local-apply onclick="RBB.app.strApply()">Update programme</button>';R.views.workspace=()=>'<h1>Browser Working Draft</h1><p data-budget-lines>'+R.app.state.lines.length+' saved source lines</p>';window.RBB=R;installSavedStrProgrammes(R,{central:ATLAS_CENTRAL});document.addEventListener('input',event=>{if(event.target.matches('[data-adr]')){R.app.strCfg.adr=Number(event.target.value);R.app.touch();}});
</script></body></html>`;
let queue=Promise.resolve(),writes=0;
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('content-type','text/html');res.end(html);return;}if(url.pathname==='/atlas_community_aliases'){res.setHeader('content-type','application/json');res.end('[]');return;}if(url.pathname.startsWith('/rpc/')){let raw='';for await(const chunk of req)raw+=chunk;const args=JSON.parse(raw),name=url.pathname.slice(5);if(name==='atlas_save_str_programme_draft')writes++;if(!['atlas_read_reforecast_workspace','atlas_save_str_programme_draft','atlas_read_str_programme_draft_receipt','atlas_read_str_programme_drafts','atlas_read_str_programme_history'].includes(name))throw Error('Unexpected fixture RPC');const task=queue.then(async()=>{await signIn(Number(req.headers['x-user']||1));const keys=Object.keys(args),values=keys.map(key=>args[key]&&typeof args[key]==='object'&&!Array.isArray(args[key])?JSON.stringify(args[key]):args[key]);return (await db.query('select to_jsonb('+name+'('+keys.map((key,i)=>key+'=> $'+(i+1)).join(',')+')) value',values)).rows[0].value;});queue=task.catch(()=>{});res.setHeader('content-type','application/json');res.end(JSON.stringify(await task));return;}const file=path.resolve(root,'.'+url.pathname);if(!file.startsWith(root+path.sep))throw Error('Invalid asset');res.setHeader('content-type',file.endsWith('.js')||file.endsWith('.mjs')?'text/javascript':'application/octet-stream');res.end(await fs.readFile(file));}catch(error){res.writeHead(400,{'content-type':'application/json'});res.end(JSON.stringify({message:error.message}));}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const url='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',error=>errors.push(error.message));page.setDefaultTimeout(15000);const rows=()=>page.evaluate(async cid=>ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_str_programme_drafts',{method:'POST',body:JSON.stringify({p_community_ids:[cid],p_programme_id:null})}),cid),saved=()=>page.waitForFunction(()=>document.querySelector('[data-saved-str-status]')?.textContent.startsWith('Saved shared programme'));
try{
 await page.goto(url);await page.getByRole('button',{name:'Save programme',exact:true}).click();await page.locator('[data-str-confirm]').check();await page.locator('[data-str-save]').click();await page.locator('dialog[open]').waitFor({state:'detached'});await saved();const first=(await rows())[0];assert.equal(first.head.revision,1);assert.deepEqual(first.revision.payload.lines,lines);assert.equal(await page.evaluate(()=>calculatorCalls),0);assert.equal(await page.evaluate(()=>RBB.app.state.strPrograms.length),2);
 const toolbarPopupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'Print saved report',exact:true}).click();const toolbarPopup=await toolbarPopupPromise;await toolbarPopup.locator('[data-saved-str-print]').waitFor();assert.equal(await toolbarPopup.locator('[data-saved-str-print]').getAttribute('data-saved-str-print'),first.revision.revision_id);await toolbarPopup.close();
 await page.getByRole('button',{name:'Saved STR programmes',exact:true}).click();await page.locator('[data-str-inspect]').click();assert.match(await page.locator('[data-str-detail]').innerText(),/Unavailable/);const downloads=[];for(const type of ['pdf','xlsx','json']){const pending=page.waitForEvent('download');await page.locator('[data-str-'+type+']').click();downloads.push(await pending);}assert.equal(downloads.length,3);const pdf=await downloads[0].createReadStream();let bytes=[];for await(const part of pdf)bytes.push(part);assert.equal(Buffer.concat(bytes).subarray(0,4).toString(),'%PDF');
 const popupPromise=page.waitForEvent('popup');await page.locator('[data-str-print]').click();const popup=await popupPromise;await popup.locator('[data-saved-str-print]').waitFor();assert.equal(await popup.locator('[data-saved-str-print]').getAttribute('data-saved-str-print'),first.revision.revision_id);assert.equal(await popup.getByRole('button',{name:'Print this saved report'}).count(),1);assert.equal(await page.evaluate(()=>calculatorCalls),0,'Print uses retained saved report, never calculator');await popup.close();
 await page.locator('[data-str-open-target]').click();assert.match(await page.locator('[data-budget-lines]').innerText(),/2 saved source lines/);
 // Another authorized context reads the identical shared report after reload.
 const other=await browser.newPage();await other.goto(url+'/?user=2');await other.evaluate(()=>RBB.app.go('savedstr'));await other.locator('[data-str-inspect]').click();const independent=await other.evaluate(async cid=>(await ATLAS_CENTRAL.fetchJson('/rpc/atlas_read_str_programme_drafts',{method:'POST',body:JSON.stringify({p_community_ids:[cid],p_programme_id:null})}))[0],cid);assert.deepEqual(independent.revision,first.revision);await other.reload();await other.evaluate(()=>RBB.app.go('savedstr'));await other.locator('[data-str-resume]').click();await other.locator('[data-saved-str-status]').waitFor();
 // Same local ID with different local values cannot contaminate a resumed revision.
 await page.evaluate(()=>{RBB.app.state.lines[0].yearData[2026][0]=9999;RBB.app.go('savedstr');});await page.locator('[data-str-resume]').click();await page.locator('[data-adr]').fill('125');await page.waitForFunction(()=>document.querySelector('[data-saved-str-status]')?.textContent.includes('version 2'));const second=(await rows())[0];assert.equal(second.revision.payload.lines[0].yearData[2026][0],100);assert.equal(second.revision.payload.config.adr,125);assert.equal(second.revision.payload.reportSnapshot.assumptions.find(row=>row.name==='adr').value,100);assert.equal(second.revision.payload.reportSnapshot.proposedAssumptions.find(row=>row.name==='adr').value,125);
 await page.evaluate(()=>RBB.app.go('savedstr'));await page.locator('[data-str-inspect]').click();assert.match(await page.locator('[data-str-detail]').innerText(),/proposed and have not recalculated/);await page.locator('[data-str-history]').click();await page.locator('[data-str-history-version] option').first().waitFor({state:'attached'});assert.equal(await page.locator('[data-str-history-version] option').count(),2);await page.locator('dialog [data-close]').click();await page.locator('[data-str-open-target]').click();await page.waitForFunction(()=>document.querySelector('[data-str-list-status]')?.textContent.includes('differs from this saved programme'));assert.match(await page.locator('[data-str-list-status]').innerText(),/differs from this saved programme/);
 // A captured old-account callback cannot inject saved source into another account.
 await page.evaluate(()=>window.actor=2);await page.locator('[data-str-resume]').click();assert.match(await page.locator('[data-str-list-status]').innerText(),/account changed/);await page.evaluate(()=>window.actor=1);
 // Portable recovery saves selected exact programme without touching current local lines or siblings.
 const before=await page.evaluate(()=>JSON.stringify(RBB.app.state));await page.locator('[data-str-backup-file]').setInputFiles({name:'retained.riseb.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(source))});await page.locator('[data-str-portable-programme]').selectOption('other');await page.locator('[data-str-portable-save]').click();await page.locator('[data-str-confirm]').check();await page.locator('[data-str-save]').click();await page.locator('dialog[open]').waitFor({state:'detached'});await page.locator('[data-str-inspect]').first().waitFor();assert.equal(await page.evaluate(()=>JSON.stringify(RBB.app.state)),before);assert.equal((await rows()).length,2);
 // Lost commit response and unreadable receipt retain the exact outbox across reload.
 await page.evaluate(()=>RBB.app.go('strbuild'));await page.getByRole('button',{name:'Save programme',exact:true}).click();await page.locator('[data-str-name]').fill('Uncertain retained copy');await page.locator('[data-str-destination]').selectOption('new');await page.locator('[data-str-confirm]').check();let lost=false;await page.route('**/rpc/atlas_save_str_programme_draft',async route=>{await route.fetch();lost=true;await route.abort();});await page.route('**/rpc/atlas_read_str_programme_draft_receipt',route=>lost?route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({message:'Synthetic unavailable receipt'})}):route.continue());await page.locator('[data-str-save]').click();await page.waitForFunction(()=>document.querySelector('dialog [data-status]')?.textContent.includes('unavailable receipt'));const committedWrites=writes;await page.unroute('**/rpc/atlas_save_str_programme_draft');await page.unroute('**/rpc/atlas_read_str_programme_draft_receipt');await page.reload();await page.evaluate(()=>RBB.app.go('savedstr'));await page.locator('[data-str-recover-write]').click();await page.locator('[data-str-recover-write]').waitFor({state:'detached'});assert.equal(writes,committedWrites,'Committed request recovery never duplicates the programme');
 assert.deepEqual(errors,[]);await fs.mkdir('output/playwright/saved-str',{recursive:true});await page.screenshot({path:'output/playwright/saved-str/library.png',fullPage:true});await other.close();console.log('PASS visible saved STR: explicit shared save; exact retained lines/no recalculation; PDF, Excel, backup and printable PDF viewer; linked browser target; reload and second authorized session; private bound editor/old local data isolation; applied vs proposed assumptions; account-change guards; portable incomplete programme recovery; persistent exact-request lost-response recovery.');
}catch(error){console.error(await page.locator('[data-status],[data-str-list-status],#toast').allTextContents());throw error;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));await db.close();}
