const assert=require('node:assert/strict');
const fs=require('node:fs');
const {migrationHistoryFixture}=require('./migration-history-fixture.cjs');
const migration='supabase/migrations/20260924205459_scoped_workspace_projection.sql';
const canonical='docs/portfolio-operations-dashboard/centralization/scoped-workspace-projection.sql';
(async()=>{
 assert.equal(fs.readFileSync(migration,'utf8'),fs.readFileSync(canonical,'utf8'));
 const {db,migrations}=await migrationHistoryFixture({includeLater:true});
 try {
  const ids={admin:'81000000-0000-4000-8000-000000000001',regional:'81000000-0000-4000-8000-000000000002',executive:'81000000-0000-4000-8000-000000000003',viewer:'81000000-0000-4000-8000-000000000004',disabled:'81000000-0000-4000-8000-000000000005',outside:'81000000-0000-4000-8000-000000000006',a:'82000000-0000-4000-8000-000000000001',b:'82000000-0000-4000-8000-000000000002',inactive:'82000000-0000-4000-8000-000000000003'};
  for(const role of ['admin','regional','executive','viewer','disabled','outside']){
   await db.query('insert into auth.users(id) values($1)',[ids[role]]);
   await db.query(`insert into public.atlas_user_profiles(user_id,email,display_name,role,status,account_status,allowed_community_ids) values($1,$2,$3,$4,$5,'active',$6)`,[ids[role],role+'@example.invalid','Synthetic '+role,['disabled','outside'].includes(role)?'viewer':role,role==='disabled'?'disabled':'active',role==='outside'?[ids.b]:[ids.a]]);
  }
  await db.query(`insert into public.atlas_communities(community_id,canonical_name,display_name,status) values($1,'Allowed Canonical','Allowed','active'),($2,'Outside Canonical','Outside','active'),($3,'Inactive Canonical','Inactive','inactive')`,[ids.a,ids.b,ids.inactive]);
  await db.query(`insert into public.atlas_community_aliases(community_id,alias,source_module) values($1,'Allowed Alias','fixture'),($1,'Ambiguous','fixture'),($2,'Ambiguous','fixture-secondary'),($2,'Expired Alias','fixture')`,[ids.a,ids.b]);
  await db.exec(`update public.atlas_community_aliases set active=false where alias='Expired Alias'`);
  const source={documentKey:'atlas_dashboard_state_v1',version:2,archiveHash:'a'.repeat(64),effectiveAt:'2026-09-24T20:00:00.000Z'};
  const monthly={guestCards:0,renewalExpirations:0,renewalSigned:null,occupiedSnapshot:0,rentableUnits:10,marketRent:null,leasedSnapshot:0,snapshotVerified:true,metricProvenance:{occupiedSnapshot:{community:'Allowed',period:'2026-09',source:'safe-source',sourceHash:'b'.repeat(64),revisionKey:'exact-revision',salary:90000,residentName:'PRIVATE_RESIDENT'}},physicalSnapshotHistory:{'2026-09-01':{occupiedSnapshot:0,rentableUnits:10,metricProvenance:{occupiedSnapshot:{source:'safe-source'}},residents:[{name:'PRIVATE_RESIDENT'}]}},trendSource:{start:'2026-09-01',end:'2026-09-30',base:10,beginningUnits:0,endingUnits:null,moveIns:0,moveOuts:0,provenance:{sourceHash:'c'.repeat(64),salary:123}},unknownNested:{private:'PRIVATE_NESTED'}};
  const record={communityId:ids.a,propertyName:'Allowed',customUnits:10,currentOccupied:0,currentLeased:null,reportYear:2026,sourceVersion:'v1',monthlyData:[monthly],monthlyHistoryByPeriod:{'2026-09':monthly},savedBudgetTargets:[0,null,95],bonusPayouts:{employee:'PRIVATE_EMPLOYEE',amount:100},communityTeamProfiles:{name:'PRIVATE_EMPLOYEE'},renewalDetailRowsByMonth:[{resident:'PRIVATE_RESIDENT'}],financialContractDocuments:[{private:'PRIVATE_CONTRACT'}],extra:'PRIVATE_EXTRA'};
  const body={format:1,source,communityData:{Allowed:record,'Allowed Alias':record,'Outside':{...record,communityId:ids.b,sourceVersion:'outside'},Ambiguous:record,Unknown:record,Inactive:{...record,communityId:ids.inactive},'Expired Alias':record,'Allowed Canonical':{...record,sourceIds:{atlasCommunityId:ids.b}}},opsGlobalData:{portfolioMonthScopeByPeriod:{'2026-09':['Allowed','Outside','Ambiguous','Allowed Alias']},bonusEmployees:[{name:'PRIVATE_GLOBAL'}],arbitrary:'PRIVATE_GLOBAL'},importState:{lineage:[{id:'current',communityName:'Allowed',periodKey:'2026-09',atlasField:'occupied_units',originalField:'occupied_units',sourceArchiveId:'archive-retained',value:0,importedValue:0,sectionPeriod:{asOf:'2026-09-30',start:'2026-09-01',end:'2026-09-30',private:'PRIVATE_IMPORT'},currentState:true,fileHash:'d'.repeat(64),salary:'PRIVATE_IMPORT'},{id:'outside',communityName:'Outside',atlasField:'occupied_units',value:22,currentState:true},{id:'notcurrent',communityName:'Allowed',atlasField:'occupied_units',value:1,currentState:false},{id:'wrongfield',communityName:'Allowed',atlasField:'resident_name',value:'PRIVATE_RESIDENT',currentState:true},{id:'mixed',communityName:'Allowed',communities:['Allowed','Outside'],atlasField:'occupied_units',value:99,currentState:true}],canonicalRecords:[{key:'safe',communityName:'Allowed',reportType:'box_score',periodKey:'2026-09',fileHash:'e'.repeat(64),sectionPeriod:{asOf:'2026-09-30',start:'2026-09-01',end:'2026-09-30',private:'PRIVATE_IMPORT'},values:{occupied_units:0,rentable_units:10,new_leads:0,leases_completed:0,net_rent:null,residentName:'PRIVATE_RESIDENT'}},{key:'outside',communityName:'Outside',reportType:'box_score',values:{occupied_units:10}}],sourceArchive:[{communities:['Allowed','Outside'],private:'PRIVATE_IMPORT'}],batches:[{summary:'PRIVATE_IMPORT'}],exceptions:[{details:'PRIVATE_IMPORT'}],arbitrary:'PRIVATE_IMPORT'}};
  const {digest}=await import('../docs/portfolio-operations-dashboard/features/workspace-bootstrap.mjs');
  const projection={...body,contentHash:await digest(body)};
  const parent={bundle:{bundleType:'atlas_migration_archive_v1',sha256:source.archiveHash,parts:[{private:'PRIVATE_ARCHIVE'}]}};
  await db.query(`insert into public.atlas_app_documents(document_key,module_key,payload,payload_hash,version,source_module,created_by,updated_by,updated_at) values($1,'dashboard',$2,'caller-hash',2,'fixture',$3,$3,$4)`,[source.documentKey,JSON.stringify(parent),ids.admin,source.effectiveAt]);
  const key=`atlas_workspace_projection_v1:${source.archiveHash}:2`;
  await db.query(`insert into public.atlas_app_documents(document_key,module_key,payload,payload_hash,source_module,created_by,updated_by) values($1,'dashboard',$2,'caller-hash','workspace_projection',$3,$3)`,[key,JSON.stringify(projection),ids.admin]);
  const actor=async id=>{await db.exec('reset role');await db.query(`select set_config('request.jwt.claim.sub',$1,false)`,[id||'']);await db.exec(id?'set role authenticated':'set role anon');};
  const read=async()=> (await db.query('select public.atlas_read_workspace_projection() value')).rows[0].value;
  await actor(ids.regional);
  let scoped=await read();assert.equal(scoped.status,'available');assert.equal(scoped.fullProjection,false);assert.equal(scoped.projection.contentHash,undefined);
  assert.deepEqual(Object.keys(scoped.projection.communityData).sort(),['Allowed','Allowed Alias']);
  assert.deepEqual(scoped.projection.communityData.Allowed.monthlyData[0].marketRent,null);assert.equal(scoped.projection.communityData.Allowed.monthlyData[0].occupiedSnapshot,0);
  assert.equal(scoped.projection.communityData.Allowed.monthlyData[0].metricProvenance.occupiedSnapshot.revisionKey,'exact-revision');
  assert.equal(scoped.projection.communityData.Allowed.monthlyData[0].physicalSnapshotHistory['2026-09-01'].occupiedSnapshot,0);
  assert.equal(scoped.projection.communityData.Allowed.monthlyData[0].trendSource.endingUnits,null);
  assert.deepEqual(scoped.projection.communityData.Allowed.savedBudgetTargets,[0,null,95]);
  assert.deepEqual(scoped.projection.opsGlobalData,{portfolioMonthScopeByPeriod:{'2026-09':['Allowed','Allowed Alias']}});
  assert.equal(scoped.projection.importState.lineage.length,1);assert.equal(scoped.projection.importState.lineage[0].value,0);assert.equal(scoped.projection.importState.canonicalRecords.length,1);assert.equal(scoped.projection.importState.lineage[0].importedValue,0);assert.equal(scoped.projection.importState.lineage[0].originalField,'occupied_units');assert.equal(scoped.projection.importState.lineage[0].sourceArchiveId,'archive-retained');assert.deepEqual(scoped.projection.importState.canonicalRecords[0].sectionPeriod,{asOf:'2026-09-30',start:'2026-09-01',end:'2026-09-30'});assert.deepEqual(scoped.projection.importState.lineage[0].sectionPeriod,scoped.projection.importState.canonicalRecords[0].sectionPeriod);
  assert.deepEqual(scoped.projection.importState.canonicalRecords[0].values,{occupied_units:0,rentable_units:10,new_leads:0,leases_completed:0});
  assert(!JSON.stringify(scoped).includes('PRIVATE_'));assert(!JSON.stringify(scoped.projection).includes('outside'));
  assert.equal((await db.query('select count(*)::int n from public.atlas_app_documents')).rows[0].n,0,'raw document RLS remains private');
  await assert.rejects(db.query(`select atlas_private.workspace_community('{}'::jsonb)`),/permission denied/);
  const priorFingerprint=scoped.scopeFingerprint;
  await db.exec('reset role');await db.query(`update public.atlas_user_profiles set allowed_community_ids=array[$1::uuid] where user_id=$2`,[ids.b,ids.regional]);await actor(ids.regional);
  scoped=await read();assert.deepEqual(Object.keys(scoped.projection.communityData),['Outside']);assert.notEqual(scoped.scopeFingerprint,priorFingerprint,'scope changes invalidate old local namespace');
  for(const role of ['admin','executive']){await actor(ids[role]);const full=await read();assert.equal(full.fullProjection,true);assert.deepEqual(full.projection,projection);assert.equal(await digest(Object.fromEntries(Object.entries(full.projection).filter(([key])=>key!=='contentHash'))),projection.contentHash);}
  await actor(ids.viewer);assert.deepEqual(Object.keys((await read()).projection.communityData).sort(),['Allowed','Allowed Alias']);
  await actor(ids.disabled);await assert.rejects(read(),/Workspace access denied/);
  await actor(null);await assert.rejects(read(),/permission denied/);
  const onlyTabs=async(user,allowed,role='regional')=>{await db.exec('reset role');await db.query(`update public.atlas_user_profiles set role=$3,allowed_community_ids=array[$4::uuid],locked_tab_ids=$2,locked_page_keys='{}',account_status='active' where user_id=$1`,[user,Array.from({length:17},(_,i)=>String(i)).filter(id=>!allowed.map(String).includes(id)),role,ids.a]);await actor(user);return read();};
  const commandOnly=await onlyTabs(ids.regional,[2]);assert.equal(commandOnly.operationalMode,'operational');assert.equal(commandOnly.projection.communityData.Allowed.monthlyData[0].marketRent,null);assert.equal(commandOnly.projection.communityData.Allowed.monthlyData[0].guestCards,0);
  const bonusOnly=await onlyTabs(ids.regional,[9]);assert.equal(bonusOnly.operationalMode,'identity');assert.equal(bonusOnly.projection.communityData.Allowed.monthlyData,undefined);assert.equal(bonusOnly.projection.communityData.Allowed.currentOccupied,undefined);assert.equal(bonusOnly.projection.communityData.Allowed.customUnits,10);assert.deepEqual(bonusOnly.projection.importState.lineage,[]);assert.deepEqual(bonusOnly.projection.importState.canonicalRecords,[]);
  const trafficOnly=await onlyTabs(ids.regional,[3]);assert.equal(trafficOnly.operationalMode,'category');assert.equal(trafficOnly.projection.communityData.Allowed.monthlyData[0].guestCards,0);assert(!Object.hasOwn(trafficOnly.projection.communityData.Allowed.monthlyData[0],'marketRent'));assert(!Object.hasOwn(trafficOnly.projection.communityData.Allowed.monthlyData[0],'renewalExpirations'));assert.equal(trafficOnly.projection.importState.lineage[0].importedValue,0);
  const renewalOnly=await onlyTabs(ids.regional,[5]);assert.equal(renewalOnly.projection.communityData.Allowed.monthlyData[0].renewalExpirations,0);assert.equal(renewalOnly.projection.communityData.Allowed.monthlyData[0].renewalSigned,null);assert(!Object.hasOwn(renewalOnly.projection.communityData.Allowed.monthlyData[0],'guestCards'));assert(!Object.hasOwn(renewalOnly.projection.importState.canonicalRecords[0].values,'new_leads'));
  const allLocked=await onlyTabs(ids.regional,[]);assert.equal(allLocked.status,'available');assert.equal(allLocked.operationalMode,'settings');assert.deepEqual(allLocked.projection.communityData,{});assert.deepEqual(allLocked.projection.opsGlobalData,{portfolioMonthScopeByPeriod:{}});assert.deepEqual(allLocked.projection.importState.canonicalRecords,[]);
  const wrongRole=await onlyTabs(ids.viewer,[3],'maintenance');assert.equal(wrongRole.operationalMode,'settings','Unlocking a role-denied tab never grants access');
  const maintenanceOnly=await onlyTabs(ids.viewer,[10],'maintenance');assert.equal(maintenanceOnly.operationalMode,'identity');assert.equal(maintenanceOnly.projection.communityData.Allowed.monthlyData,undefined);
  const adminSettings=await onlyTabs(ids.admin,[],'admin');assert.equal(adminSettings.fullProjection,false);assert.deepEqual(adminSettings.projection.communityData,{});
  await onlyTabs(ids.admin,[0,2,8],'admin');
  await onlyTabs(ids.regional,[0,2,8]);
  await db.exec('reset role');await db.query(`update public.atlas_user_profiles set locked_tab_ids='{}',account_status='password_reset_required' where user_id=$1`,[ids.viewer]);await actor(ids.viewer);await assert.rejects(read(),/Workspace access denied/);
  await actor(ids.admin);
  // Changed source, wrong module/source binding and missing projection all fail closed without archive fallback.
  await db.exec('reset role');await db.query(`update public.atlas_app_documents set version=3 where document_key=$1`,[source.documentKey]);await actor(ids.admin);assert.equal((await read()).reason,'workspace_projection_unavailable');
  await db.exec('reset role');await db.query(`update public.atlas_app_documents set version=2 where document_key=$1`,[source.documentKey]);await db.query(`update public.atlas_app_documents set payload=jsonb_set(payload,'{source,archiveHash}','"mismatch"') where document_key=$1`,[key]);await actor(ids.regional);assert.equal((await read()).reason,'workspace_projection_source_mismatch');
  await db.exec('reset role');await db.query(`update public.atlas_app_documents set payload=$2 where document_key=$1`,[key,JSON.stringify(projection)]);await db.query(`update public.atlas_app_documents set updated_at=updated_at+interval '1 second' where document_key=$1`,[source.documentKey]);await actor(ids.regional);assert.equal((await read()).reason,'workspace_projection_source_mismatch');
  console.log(`PASS scoped workspace projection on ${migrations.length} migrations: active roles, alias ambiguity, scope change, locks/revocation, module-category locks and self-service-only context, private boundaries, exact admin hash, numeric null/zero/provenance and missing/stale source`);
 }finally{await db.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
