/* Shared STR persistence: history, report reconciliation, exact target lineage and authorization. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{
 const {buildStrProgrammeReport,strProgrammeReport}=await import('../docs/portfolio-operations-dashboard/features/saved-str-programmes.mjs');
 const {db,A,B,BUDGET,signIn}=await fixture(),read=name=>fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8'),user=n=>'00000000-0000-0000-0000-'+String(n).padStart(12,'0');
 const call=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
 await db.exec('reset role');await db.exec("create function atlas_private.resolve_workbook_audit(a jsonb,h text) returns jsonb language sql as $$select a$$");
 for(const name of ['20260924121641_planning_cell_workbook_integrity_governance.sql','20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260925174317_shared_str_programme_draft_versions.sql'])await db.exec(read(name));
 await signIn(1);
 const years=[2026,2027],sourcePropertyId='source-property',sourceProgrammeId='source-programme',config={propertyId:sourcePropertyId,programmeId:sourceProgrammeId,name:'Retained programme',unitPicks:[{groupId:'retained-group',units:20}],adr:125},property={id:sourcePropertyId,name:'Retained community',units:[{id:'retained-group',units:20}]};
 const lines=[['rent','5144','income',101.25],['displaced','5220','contra_income',-10.001234],['utilities','6200','expense',9.95],['furniture','1504','capital',50],['debt','8010','debt',2],['other','8011','below_noi',1]].map(([id,gl,nature,amount])=>({id,gl,nature,name:id,propertyId:sourcePropertyId,strProgramId:sourceProgrammeId,yearData:Object.fromEntries(years.map(y=>[y,Array(12).fill(amount)]))}));
 const payload={schemaVersion:'atlas.str-programme-draft.v1',name:'Retained programme',sourcePropertyId,sourceProgrammeId,config,property,groups:property.units,programme:{id:sourceProgrammeId,propertyId:sourcePropertyId,name:'Retained programme',applied:true,config},lines,years,reportBasisConfig:config,sourceContext:{property,lines:[],libraries:{assumptions:{retained:true}}},browserTarget:{propertyId:sourcePropertyId,scenarioId:'local-only'},targetBudget:null,reason:'Preserve reviewed browser programme',reportSnapshot:buildStrProgrammeReport({name:'Retained programme',communityName:'Community',years,lines,config})};
 const programme=randomUUID(),request=randomUUID(),save=(p=payload,{cid=A,pid=programme,expected=0,rid=randomUUID()}={})=>call('atlas_save_str_programme_draft',[cid,pid,expected,rid,p]);
 const receipt=(cid,rid)=>call('atlas_read_str_programme_draft_receipt',[cid,rid]),list=(cid,pid=null,revision=null)=>call('atlas_read_str_programme_drafts',[[cid],pid,revision]);
 assert.equal(await receipt(A,request),null);
 const first=await save(payload,{rid:request});assert.equal(first.verified,true);assert.equal(first.head.revision,1);assert.deepEqual(first.revision.payload,payload);assert.deepEqual(strProgrammeReport(first),payload.reportSnapshot,'JSONB key ordering must not change the retained report model');assert.equal(first.revision.target_budget,null);assert.match(first.revision.content_hash,/^[a-f0-9]{64}$/);assert.equal(first.revision.status,'working_draft');assert.deepEqual(await receipt(A,request),first);assert.deepEqual(await save(payload,{rid:request}),first);
 assert.equal((await call('atlas_read_active_reforecast',[[A],['2026-02']])).length,0,'Saving a programme does not publish a baseline');
 assert.equal((await db.query('select count(*)::int n from atlas_reforecast_revisions')).rows[0].n,0,'Saving a programme does not claim application to a canonical budget');
 const originalBytes=JSON.stringify(first.revision);
 await assert.rejects(()=>save({...payload,name:'Changed'},{rid:request}),/request ID reused/);
 await signIn(2);assert.deepEqual((await list(A))[0].revision,first.revision,'A second authorized account reads the exact retained programme and report');
 await assert.rejects(()=>save(payload,{rid:request}),/request ID reused/,'A second actor cannot impersonate an earlier save request');
 const changed=structuredClone(payload);changed.config.adr=130;changed.reportBasisConfig=structuredClone(changed.config);changed.reason='Regional reviewed the assumption';changed.reportSnapshot=buildStrProgrammeReport({name:changed.name,communityName:'Community',years,lines,config:changed.config});
 const second=await save(changed,{expected:1});assert.equal(second.head.revision,2);assert.equal(second.revision.previous_revision_id,first.revision.revision_id);assert.equal(second.revision.actor_id,user(2));assert.equal(second.revision.actor_role,'regional');assert.equal(JSON.stringify((await list(A,programme,first.revision.revision_id))[0].revision),originalBytes,'Historical report snapshots remain byte-identical');
 await assert.rejects(()=>save(changed,{expected:1}),/another session/);
 await signIn(1);const replay=await save(payload,{rid:request});assert.equal(replay.head.revision,1);assert.equal(replay.currentHead.revision,2,'Lost-response recovery identifies a newer head without rewriting its earlier receipt');
 const twin=await save(payload,{pid:randomUUID()});assert.notEqual(twin.head.programme_id,programme);assert.equal((await list(A)).length,2,'Multiple programmes for one property coexist');
 const incomplete={...payload,sourceProgrammeId:'unfinished-programme',name:'Unfinished legacy programme',config:null,programme:{id:'unfinished-programme',propertyId:sourcePropertyId,applied:false,config:null},lines:[],reportSnapshot:null,reportUnavailableReason:'Driver settings have not been completed'};
 const shell=await save(incomplete,{cid:B,pid:randomUUID()});assert.equal(shell.revision.payload.config,null);assert.equal(shell.revision.payload.reportSnapshot,null);assert.equal(shell.revision.target_budget,null,'An incomplete programme saves without an existing approved or forecast baseline');
 await assert.rejects(()=>save({...incomplete,reportUnavailableReason:''},{pid:randomUUID()}),/unfinished STR report/);
 const blank=structuredClone(payload);blank.lines.find(l=>l.nature==='expense').yearData[2026][0]=null;blank.lines.find(l=>l.nature==='capital').yearData[2026][1]=0;blank.reportSnapshot=buildStrProgrammeReport({name:blank.name,communityName:'Community',years,lines:blank.lines,config:blank.config});
 const blankSaved=await save(blank,{pid:randomUUID()});assert.equal(blankSaved.revision.payload.reportSnapshot.monthly[0].expenses,null);assert.equal(blankSaved.revision.payload.reportSnapshot.totals.netCashFlow,null);assert.equal(blankSaved.revision.payload.reportSnapshot.rows.find(r=>r.sourceLineId==='furniture'&&r.period==='2026-02').amount,0);
 for(const [value,expected] of [[1.005,1.01],[-10.005,-10.01]]){const precise=structuredClone(payload);for(const line of precise.lines)for(const year of years)line.yearData[year]=Array(12).fill(0);precise.lines[0].yearData[2026][0]=value;precise.reportSnapshot=buildStrProgrammeReport({name:precise.name,communityName:'Community',years,lines:precise.lines,config:precise.config});const result=await save(precise,{pid:randomUUID()});assert.equal(result.revision.payload.lines[0].yearData[2026][0],value);assert.equal(result.revision.payload.reportSnapshot.monthly[0].revenue,expected,'Decimal rounding must match PostgreSQL while preserving source precision');}
 for(const change of [p=>p.reportSnapshot.rows[0].amount++,p=>p.reportSnapshot.rows.pop(),p=>p.reportSnapshot.monthly[0].netCashFlow++,p=>p.reportSnapshot.totals.expenses++,p=>p.reportSnapshot.status='Investor Approved',p=>p.lines[0].propertyId='another-property',p=>p.sourceContext.lines.push({propertyId:'another-property'})]){const bad=structuredClone(payload);change(bad);await assert.rejects(()=>save(bad,{pid:randomUUID()}),/STR|source property/);}
 // A canonical target is an exact, server-verified reference only. It is never silently applied.
 const accounts=[['5120','Rent','income'],['5220','Vacancy','contra_income'],['6100','Payroll','expense'],['6200','Utilities','expense'],['8100','Capital','capital']].map(([accountCode,category,nature])=>({accountCode,category,nature,placement:nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'}));
 const registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),{accounts,driverMappings:{},reason:'Reviewed canonical mapping',effectiveDate:'2026-01-01'}]),periods=['2026-02'];
 const budgetPayload={name:'Canonical target',model:'conventional',governanceSchemaVersion:2,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:'Canonical target',reviewedBy:user(1),reviewedAt:'2026-09-25T00:00:00Z'},periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:user(1),reviewerId:user(1),drivers:[],overrides:[],reason:'Create canonical budget target'};
 const budgetSave=(r,action='save_draft')=>call('atlas_save_reforecast_scenario',[A,r?.head.scenario_id||randomUUID(),r?.head.revision||0,randomUUID(),action,r?.revision.payload||budgetPayload]);
 let target=await budgetSave();const targetBudget={scenarioId:target.head.scenario_id,revisionId:target.revision.revision_id};
 const linked=await save({...payload,targetBudget},{pid:randomUUID()});assert.equal(linked.revision.target_budget.relationship,'planning_reference_not_applied');assert.equal(linked.revision.target_budget.verified,true);assert.equal(linked.revision.target_budget.registryVersionId,registry.version_id);assert.match(linked.revision.target_budget.snapshotFingerprint,/^[a-f0-9]{64}$/);
 await assert.rejects(()=>save({...payload,targetBudget},{cid:B,pid:randomUUID()}),/does not belong/);
 target=await budgetSave(target);await assert.rejects(()=>save({...payload,targetBudget},{pid:randomUUID()}),/Target budget changed/);
 await assert.rejects(()=>save({...payload,targetBudget:{scenarioId:target.head.scenario_id,revisionId:target.revision.revision_id,publicationId:randomUUID()}},{pid:randomUUID()}),/Target publication/);
 for(const action of ['reconcile','ready','submit','approve_lock'])target=await budgetSave(target,action);
 const approvedLink=await save({...payload,targetBudget:{scenarioId:target.head.scenario_id,revisionId:target.revision.revision_id,publicationId:target.publication.publication_id}},{pid:randomUUID()});assert.equal(approvedLink.revision.target_budget.publicationId,target.publication.publication_id);assert.equal(approvedLink.revision.status,'working_draft');
 const activeBefore=await call('atlas_read_active_reforecast',[[A],periods]);await save(payload,{pid:randomUUID()});assert.deepEqual(await call('atlas_read_active_reforecast',[[A],periods]),activeBefore,'STR draft saves never change approved platform values');
 if(process.env.ATLAS_SAVED_STR_JSON){
  const source=JSON.parse(fs.readFileSync(process.env.ATLAS_SAVED_STR_JSON,'utf8'));let restored=0;
  for(const programme of source.state.strPrograms||[]){
   const property=source.state.properties.find(p=>p.id===programme.propertyId),lines=source.state.lines.filter(l=>l.propertyId===programme.propertyId&&l.strProgramId===programme.id),years=[...new Set(lines.flatMap(l=>Object.keys(l.yearData||{})).map(Number))].sort();if(!years.length)years.push(source.state.budgetYear);
   const config=structuredClone(programme.config||null),name=programme.name||'Retained STR programme',complete=Boolean(config&&lines.length),reportSnapshot=complete?buildStrProgrammeReport({name,communityName:property.name,years,lines,config}):null;
   const p={schemaVersion:'atlas.str-programme-draft.v1',name,sourcePropertyId:property.id,sourceProgrammeId:programme.id,property,groups:property.units||[],programme,config,lines,years,reportSnapshot,reportBasisConfig:config,...(complete?{}:{reportUnavailableReason:'Retained original programme has no completed driver configuration or calculated lines'}),sourceContext:{property,lines:source.state.lines.filter(l=>l.propertyId===property.id),libraries:source.libraries||{},retainedUiConfig:source.ui?.strCfg||null},targetBudget:null,reason:'Exact private source recovery in isolated test only'};
   const saved=await save(p,{cid:B,pid:randomUUID()});assert.deepEqual(saved.revision.payload,p);if(complete)assert.deepEqual(strProgrammeReport(saved),reportSnapshot,'Export model reads the exact saved original monthly lines without recalculation');await signIn(4);assert.deepEqual((await list(B,saved.head.programme_id))[0].revision.payload,p,'Separate authorized account reads the original source bytes and exact report');await signIn(1);assert.deepEqual((await receipt(B,saved.revision.request_id)).revision,saved.revision);restored++;
  }
  console.log('PASS private saved STR source: '+restored+' original programmes round-trip through isolated shared revisions and another authorized account; no production changes.');
 }
 await signIn(4);assert.deepEqual(await list(A),[]);assert.deepEqual(await call('atlas_read_str_programme_history',[programme]),[]);await assert.rejects(()=>receipt(A,request),/access denied/);await assert.rejects(()=>save(payload),/access denied/);
 await signIn(2);await db.exec('reset role');await db.query("update atlas_user_profiles set locked_tab_ids=array['12'] where user_id=$1",[user(2)]);await signIn(2);assert.deepEqual(await list(A),[]);await assert.rejects(()=>save(changed,{expected:2}),/access denied/);
 await db.exec('reset role');await assert.rejects(()=>db.query("update atlas_str_programme_revisions set payload='{}' where revision_id=$1",[first.revision.revision_id]),/immutable/);await assert.rejects(()=>db.query('delete from atlas_str_programme_revisions where revision_id=$1',[first.revision.revision_id]),/immutable/);
 const grants=(await db.query("select p.proname,n.nspname,p.prosecdef,has_function_privilege('anon',p.oid,'EXECUTE') anon_exec from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname like '%str_programme%'")).rows;for(const row of grants){assert.equal(row.anon_exec,false,row.proname);if(row.nspname==='public')assert.equal(row.prosecdef,false,row.proname);}
 assert.equal((await db.query("select has_table_privilege('authenticated','atlas_str_programme_revisions','INSERT') allowed")).rows[0].allowed,false);
 await signIn(1);assert.equal((await call('atlas_read_str_programme_history',[programme])).length,2);
 console.log('PASS shared STR: exact save/readback and second account; optimistic concurrency; immutable revisions/reports; incomplete legacy recovery with no baseline; null vs zero; reconciled reports; verified target ancestry; no implicit publication; property/page authorization and no anonymous/direct writes.');await db.close();
})().catch(error=>{console.error(error);process.exitCode=1;});
