import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),root=path.resolve('docs/portfolio-operations-dashboard');
const html=`<!doctype html><html><body><script src="/assets/xlsx.full.min.js"></script><script type="module">
import {standardBudgetExportDialog} from '/features/standard-budget-export-ui.mjs';
import {computeReforecast} from '/features/reforecast-engine.mjs';
const cid='10000000-0000-4000-8000-000000000001',actor='10000000-0000-4000-8000-000000000002',rid='10000000-0000-4000-8000-000000000003',eid='10000000-0000-4000-8000-000000000004',fid='10000000-0000-4000-8000-000000000005',periods=['2026-08','2026-09'];
const scenario={name:'Student export',model:'student',periods,calendar:{startMonth:8},versionId:'draft',driverVersion:'drivers',ownerId:actor,drivers:[],overrides:[]},source={communityId:cid,periods,baseline:{versionId:'original',lines:periods.flatMap(period=>[{period,accountCode:'5120',amount:100000},{period,accountCode:'6500',amount:2000}])},actuals:{},registry:{version:'mapping',accounts:[{accountCode:'5120',name:'Rent',nature:'income',category:'Revenue',placement:'above_noi'},{accountCode:'6500',name:'Utilities',nature:'expense',category:'Utilities',placement:'above_noi'}]}};
const snapshot=computeReforecast({...source,scenario});window.selection={entry:{kind:'saved_revision',communityId:cid,revisionId:rid,version:3,status:'Draft'},revision:{snapshot,payload:scenario,source}};window.captures=[];window.completions=[];window.actor=actor;window.loseResponse=true;
window.central={getSession:()=>({user:{id:window.actor}}),getStoredProfile:()=>({display_name:'Reviewer'}),isAuthenticated:()=>true,isEnabled:()=>true,fetchJson:async(url,options)=>{const args=options?JSON.parse(options.body):{};if(url.endsWith('atlas_preview_budget_export'))return {snapshot,config:scenario,source,communityName:'RISE Student',portfolio:'Student',region:'Southeast',communityId:cid,revisionId:rid,budgetVersion:'3',budgetStatus:'Draft',contentHash:'retained-source',sourceFingerprint:'source-fingerprint',verified:true,validation:{status:'passed',checks:[],issues:[]}};if(url.includes('atlas_capture_budget_export')){captures.push(args);window.receipt={snapshot,config:scenario,source,communityName:'RISE Student',portfolio:'Student',region:'Southeast',exportId:eid,communityId:cid,revisionId:rid,budgetVersion:'3',budgetStatus:'Draft',generatedAt:'2026-09-29T16:00:00Z',generatedBy:actor,contentHash:'retained-source',sourceFingerprint:'source-fingerprint',verified:true,options:args.p_options,validation:{status:'warnings',checks:[{key:'fiscal_calendar',status:'passed'}],issues:[{code:'manual_override',severity:'warning',message:'Retained override note'}]}};return receipt;}if(url.endsWith('atlas_read_budget_export'))return receipt;if(url.includes('atlas_complete_budget_export')){completions.push(args);window.fileRecord={file_record_id:fid,request_id:args.p_request_id,files:args.p_files};if(loseResponse){window.loseResponse=false;throw Error('Simulated lost completion response');}return {verified:true,communityId:cid,exportId:eid,fileRecordId:fid,files:args.p_files};}if(url.includes('/atlas_budget_export_files?'))return [fileRecord];if(url.includes('/atlas_budget_exports?'))return [];if(url.includes('tolerances'))return {communityId:cid,version:0,rules:{},canAdminister:false};throw Error('Unexpected call '+url);}};
const dialog=title=>{const el=document.createElement('dialog');el.innerHTML='<h2>'+title+'</h2><div data-body></div><p data-status role="status"></p>';document.body.append(el);el.onclose=()=>el.remove();el.showModal();return el;};
window.openExport=()=>standardBudgetExportDialog({central,selection,communityName:'RISE Student',dialog});openExport();
</script></body></html>`;
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/'){res.setHeader('content-type','text/html');res.end(html);return;}const filename=path.resolve(root,'.'+u.pathname);if(!filename.startsWith(root+path.sep)){res.writeHead(403).end();return;}res.setHeader('content-type',filename.endsWith('.png')?'image/png':'application/javascript');res.end(await fs.readFile(filename));}catch(error){res.writeHead(500).end(error.message);}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[],downloads=[];page.on('pageerror',e=>errors.push(e.message));page.on('download',d=>downloads.push(d));
try{
 page.setDefaultTimeout(15000);
 await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('[data-generate]').waitFor();assert.equal(await page.locator('[data-section="str"]').count(),0);await page.locator('[data-preset]').selectOption('executive');assert.equal(await page.locator('[data-section="assumptions"]').isChecked(),false);await page.locator('[data-section="assumptions"]').check();assert.equal(await page.locator('[data-preset]').inputValue(),'custom');await page.locator('[data-charts-on]').uncheck();assert.equal(await page.locator('[data-chart-list]').isVisible(),false);await page.locator('[data-generate]').click();await page.waitForFunction(()=>document.querySelector('[data-status]').textContent.includes('Simulated lost')).catch(async error=>{throw Error(await page.locator('[data-status]').innerText());});
 assert.equal(await page.evaluate(()=>captures.length),1);await page.locator('[data-generate]').click();await page.waitForFunction(()=>document.querySelector('[data-status]').textContent.includes('2 file(s) generated'));await page.waitForTimeout(100);assert.equal(downloads.length,2);const state=await page.evaluate(()=>({captures,completions}));assert.equal(state.captures.length,1,'Retries reuse captured version');assert.deepEqual(state.completions[0],state.completions[1],'Retry uses exact same file hashes and completion request');assert.deepEqual(state.captures[0].p_options.formats,['xlsx','pdf']);assert.equal(state.captures[0].p_options.includeCharts,false);assert(state.completions[0].p_files.every(f=>f.sha256.length===64&&f.size>1000));
 const xlsx=downloads.find(d=>d.suggestedFilename().endsWith('.xlsx')),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js'),bytes=await fs.readFile(await xlsx.path()),zip=XLSX.CFB.read(bytes,{type:'buffer'}),model=JSON.parse(new TextDecoder().decode(XLSX.CFB.find(zip,'Root Entry/xl/atlas-report.json').content));assert.equal(model.validation.issues[0].message,'Retained override note');assert.equal(model.metadata.region,'Southeast');assert.equal(model.metadata.validationStatus,'warnings');assert.equal(model.metadata.version,'3');assert(!XLSX.CFB.find(zip,'Root Entry/xl/charts/chart1.xml'));
 await page.locator('[data-tolerances]').click();await page.waitForFunction(()=>document.querySelector('[data-status]').textContent.includes('Only an administrator'));await page.evaluate(()=>window.actor='10000000-0000-4000-8000-000000000099');await page.locator('[data-generate]').click();assert.match(await page.locator('[data-status]').innerText(),/signed-in session changed/);assert.deepEqual(errors,[]);
 console.log('PASS export browser: selected version, applicable sections, presets, charts OFF, both formats, exact retry bytes, immutable receipt validation/metadata, administrator settings guard, session drift refusal.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
