import assert from 'node:assert/strict';
import {standardBudgetModel,budgetIntegrityCheck} from '../docs/portfolio-operations-dashboard/features/standard-budget-model.mjs';
import {aggregateForecastLines,sumMoney} from '../docs/portfolio-operations-dashboard/features/reforecast-engine.mjs';
const periods=Array.from({length:12},(_,i)=>new Date(Date.UTC(2026,7+i,1)).toISOString().slice(0,7));
const lines=periods.flatMap((period,i)=>[{period,accountCode:'4000',accountName:'Rent',nature:'income',placement:'above_noi',mappingValid:true,forecast:100000+i*1000},{period,accountCode:'6000',accountName:'Utilities',category:'utilities',nature:'expense',placement:'above_noi',mappingValid:true,forecast:12000+i*100}]);
const monthly=periods.map(period=>({period,applicable:true,reforecast:aggregateForecastLines(lines.filter(l=>l.period===period),'forecast')}));
const snapshot={identity:{communityId:'c1',periods,reforecastVersion:'v1'},fingerprint:'saved-v1',lines,monthly,totals:{reforecast:Object.fromEntries(['revenue','expenses','noi','capital','debt','cashFlow'].map(key=>[key,sumMoney(monthly.map(m=>m.reforecast[key]))]))},leasing:periods.map(period=>({period,units:100,occupiedUnits:90,occupancy:.9,marketRent:1500}))};
const opts={snapshot,scenario:{modelType:'student',calendar:{startMonth:8}},metadata:{community:'Student Test',version:1,status:'Draft'}};
const model=standardBudgetModel(opts);
assert.equal(model.periods[0],'2026-08');assert.equal(model.periods.at(-1),'2027-07');assert.equal(model.sections.some(s=>s.id==='str'),false);assert.equal(model.sections.some(s=>s.id==='channels'),false);
assert.equal(model.sections.find(s=>s.id==='revenue').rows[0].annual,1266000);assert.equal(model.sections.find(s=>s.id==='summary').rows[0].annual,1266000);
assert.equal(model.sections.find(s=>s.id==='leasing').rows.find(r=>r.label==='Occupancy').annual,null,'Occupancy percentages must never sum');
assert.equal(model.validation.status,'passed');assert.equal(model.sections.some(s=>s.charts),false);
const charts=standardBudgetModel({...opts,options:{includeCharts:true,charts:['monthly_revenue'],sections:['summary','revenue']}});assert.deepEqual(charts.sections.map(s=>s.id),['summary','revenue']);assert.equal(charts.sections[0].charts.length,1);
const prior=JSON.stringify(model),copy=structuredClone(snapshot);copy.lines[0].forecast=145000;const conflict=budgetIntegrityCheck({snapshot:copy,periods});assert.ok(conflict.issues.some(i=>i.code==='formula_inconsistency'));assert.equal(JSON.stringify(model),prior,'Retained export must not change');
copy.totals.reforecast.revenue=1;assert.ok(budgetIntegrityCheck({snapshot:copy,periods}).issues.some(i=>i.code==='annual_total'));
const missing=structuredClone(snapshot);missing.lines[0].forecast=null;assert.ok(standardBudgetModel({...opts,snapshot:missing}).validation.issues.some(i=>i.code==='missing_assumption'));assert.equal(standardBudgetModel({...opts,snapshot:missing}).sections.find(s=>s.id==='revenue').rows[0].annual,null);
const fractional=structuredClone(snapshot);fractional.lines.filter(l=>l.accountCode==='4000').forEach(l=>l.forecast=1.234);assert.equal(standardBudgetModel({...opts,snapshot:fractional}).sections.find(s=>s.id==='revenue').rows[0].annual,14.808,'Detail source precision is retained');
const v2=standardBudgetModel({...opts,metadata:{...opts.metadata,version:2}});assert.notEqual(v2.metadata.version,model.metadata.version);
assert.throws(()=>standardBudgetModel({...opts,options:{sections:[]}}),/Select/);
console.log('Standard budget model acceptance: fiscal calendar, selected sections, integrity, exact totals, missing values, chart choices and retained versions passed');
const supportModel=standardBudgetModel({snapshot,scenario:{...opts.scenario,strBudgetApplications:[{name:'RISE STR',programmeId:'programme',revisionId:'programme-revision',version:2,reason:'Reviewed programme',appliedAt:'2026-09-29T00:00:00Z',cells:[{period:periods[0],accountCode:'4100',strAmount:1234.56}],supportingSchedules:Object.fromEntries([2026,2027].map(year=>[year,{channels:[{channel:'Direct',share:.2,feePct:.03}],utilities:{byGl:[{gl:'6400',name:'Water',cost:Array(12).fill(45)}]},sensitivities:[{label:'ADR',noiDn:-100,noiUp:100,upliftDn:-100,upliftUp:100}],assumptions:{adr:220}}]))}]},metadata:opts.metadata,options:{includeCharts:true}});
assert(supportModel.sections.some(s=>s.id==='str'));
assert.equal(supportModel.sections.find(s=>s.id==='utilities').rows.find(r=>r.label==='RISE STR · Water').annual,540);
assert(supportModel.sections.find(s=>s.id==='channels').rows[0].values.every(v=>v===.2));
assert.equal(supportModel.sections.find(s=>s.id==='sensitivities').rows.length,8);
assert(supportModel.sections.find(s=>s.id==='assumptions').notes.some(n=>n.includes('adr')||n.includes('Adr')));
const inconsistent=structuredClone(snapshot);inconsistent.totals.reforecast.revenue+=100;
const draftIssue=standardBudgetModel({...opts,snapshot:inconsistent});assert.equal(draftIssue.sections[0].rows[0].annualFormula,undefined,'Draft with inconsistent totals remains exportable with retained values and findings');
