const {readDashboardSource}=require('./dashboard-source.cjs');
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=readDashboardSource(__dirname+'/../docs/portfolio-operations-dashboard/index.html');
const names=['readOpsGlobalStorageRaw','writeOpsGlobalStorage','hydrateOpsGlobalStorage','persistOpsGlobalSnapshot'];
function context(){const db=new Map(),small=new Map(),errors=[];const c={JSON,Promise,Error,atlasScopedLocalKey:key=>key,OPS_GLOBAL_STORAGE_KEY:'global',opsGlobalStorageCache:null,localStorage:{getItem:k=>small.get(k)??null,removeItem:k=>small.delete(k)},openAtlasStateDb:async()=>true,atlasStateSetValue:async(k,v)=>db.set(k,JSON.parse(JSON.stringify(v))),atlasStateGetValue:async k=>db.get(k)??null,markAtlasPersistenceError:e=>errors.push(e.message),alert:m=>errors.push(m),queueAtlasStateWrite:task=>{c.completion=(c.completion||Promise.resolve()).then(task).catch(e=>errors.push(e.message));return c.completion;}};vm.createContext(c);for(const n of names)vm.runInContext(html.match(new RegExp('^(?:async )?function '+n+'\\([^\\n]*\\) \\{[\\s\\S]*?^\\}','m'))[0],c);return {c,db,small,errors};}
(async()=>{
 let {c,db,small}=context();const large={notes:'x'.repeat(6*1024*1024),settings:{period:'2026-09'}};small.set('global',JSON.stringify(large));await c.hydrateOpsGlobalStorage();assert.equal(small.has('global'),false);assert.deepEqual(JSON.parse(c.readOpsGlobalStorageRaw()),large);
 const edited={notes:'preserved',settings:{period:'2026-10'}};const result=c.persistOpsGlobalSnapshot(edited);edited.notes='mutated after queue';await result.completion;assert.equal(db.get('global').notes,'preserved');c.opsGlobalStorageCache=null;await c.hydrateOpsGlobalStorage();assert.equal(JSON.parse(c.readOpsGlobalStorageRaw()).settings.period,'2026-10');
 const f=context();f.small.set('global',JSON.stringify(large));f.c.atlasStateSetValue=async()=>{throw new Error('disk full')};await f.c.hydrateOpsGlobalStorage();assert(f.small.has('global'),'Failed migration preserves original');assert.equal(f.errors.length,1);await f.c.persistOpsGlobalSnapshot({notes:'unsaved'}).completion;assert(f.errors.some(e=>e.includes('Keep it open')));assert.equal(JSON.parse(f.c.readOpsGlobalStorageRaw()).notes,'unsaved');
 const unavailable=context();unavailable.small.set('global','{"notes":"original"}');unavailable.c.openAtlasStateDb=async()=>null;await unavailable.c.hydrateOpsGlobalStorage();assert(unavailable.small.has('global'));
 const corrupt=context();corrupt.small.set('global','{"notes":"original"}');corrupt.c.atlasStateGetValue=async()=>null;await corrupt.c.hydrateOpsGlobalStorage();assert(corrupt.small.has('global'),'Verification failure keeps original');
 assert(html.includes('key === OPS_GLOBAL_STORAGE_KEY ? readOpsGlobalStorageRaw() : localStorage.getItem(key)'));
 console.log('PASS large settings migration, immutable queued save, reload, backup inclusion, unavailable/full database and failed verification preserve originals.');
})().catch(e=>{console.error(e);process.exit(1)});
