import assert from 'node:assert/strict';
import {buildStrBudgetApplicationRequest,suggestStrBudgetMappings,isActiveStrDestination,previewStrBudgetApplication,applyStrBudgetApplication} from '../docs/portfolio-operations-dashboard/features/str-budget-application.mjs';
const actor='editor',cid='community',pid='programme',rid='source-revision',tid='target-revision',sid='scenario';
const record={verified:true,head:{community_id:cid,programme_id:pid},revision:{community_id:cid,revision_id:rid,revision:1,content_hash:'a'.repeat(64),payload:{name:'Saved programme',reportSnapshot:{},lines:[{id:'rent',gl:'5144',name:'STR rental',nature:'income'},{id:'utility',gl:'6100',name:'STR utilities',nature:'expense'}]}}};
const target={head:{community_id:cid,scenario_id:sid,revision_id:tid,status:'working_draft',revision:2},revision:{community_id:cid,revision_id:tid,payload:{name:'Property budget',periods:['2026-08','2026-09']}},source:{communityId:cid,registry:{accounts:[{accountCode:'5144',nature:'income'},{accountCode:'6200',nature:'expense'}]}},permissions:{canEdit:true,canApprovePublication:false}};
const mapping=suggestStrBudgetMappings(record,target,[{source_line_id:'previous-id',source_name:'STR utilities',source_gl:'6100',source_nature:'expense',account_code:'6200',mapping:{reason:'Reviewed utilities mapping'}}]);assert.equal(mapping[0].accountCode,'5144');assert.equal(mapping[1].accountCode,'6200','A regenerated source identity reuses reviewed category mapping');assert(mapping.every(m=>m.confirmed===false));
const args={record,target,mappings:mapping.map(m=>({...m,confirmed:true})),reason:'Apply reviewed economics',requestId:'request',reviewedAt:'2026-09-29T12:00:00Z'};
const request=buildStrBudgetApplicationRequest(args);assert.equal(request.scenarioId,sid);assert.equal(request.targetRevisionId,tid);assert.throws(()=>buildStrBudgetApplicationRequest({...args,record:{...record,verified:false}}),/shared STR/);assert.throws(()=>buildStrBudgetApplicationRequest({...args,target:{...target,head:{...target.head,community_id:'other'}}}),/same community/);assert.throws(()=>buildStrBudgetApplicationRequest({...args,destination:'active_revision',name:'Active fork'}),/VP/);assert.throws(()=>buildStrBudgetApplicationRequest({...args,mappings:mapping}),/Confirm each/);assert.throws(()=>buildStrBudgetApplicationRequest({...args,destination:'new_draft'}),/Name/);
const fork=buildStrBudgetApplicationRequest({...args,destination:'new_draft',name:'Alternative',scenarioId:'new-id'});assert.equal(fork.scenarioId,'new-id');
const preview={verified:true,request,communityId:cid,targetRevisionId:tid,programmeRevisionId:rid,previewHash:'b'.repeat(64),periods:['2026-08'],cells:[{accountCode:'5144',period:'2026-08',combinedAmount:150}],application:{programmeId:pid}};
const receipt={verified:true,request,applicationId:request.requestId,previewHash:preview.previewHash,application:preview.application,head:{revision_id:'applied'},revision:{community_id:cid,scenario_id:sid,request_id:request.requestId,actor_id:actor,revision_id:'applied'},snapshot:{lines:[{period:'2026-08',accountCode:'5144',forecast:150}]}};
let currentActor=actor,stored=null,writes=0,failWrite=false,corrupt=false;const central={getSession:()=>({user:{id:currentActor}}),refreshSession:async()=>{},getStoredProfile:()=>({role:'regional'}),fetchJson:async(url,options)=>{const body=JSON.parse(options.body);if(url.endsWith('atlas_preview_str_budget_application'))return structuredClone(preview);if(url.endsWith('atlas_read_str_budget_application'))return structuredClone(stored);if(url.endsWith('atlas_apply_str_budget_programme')){writes++;assert.deepEqual(body,{p_request:request,p_preview_hash:preview.previewHash});stored=structuredClone(receipt);if(corrupt)stored.snapshot.lines[0].forecast++;if(failWrite)throw Error('Lost response');return structuredClone(stored);}throw Error(url);}};
assert.deepEqual(await previewStrBudgetApplication(central,request),preview);assert.deepEqual(await applyStrBudgetApplication(central,preview),receipt);assert.equal(writes,1);assert.deepEqual(await applyStrBudgetApplication(central,preview),receipt);assert.equal(writes,1,'Repeated confirmation only reads existing receipt');stored=null;failWrite=true;assert.deepEqual(await applyStrBudgetApplication(central,preview),receipt,'A lost commit response recovers the exact receipt');assert.equal(writes,2);stored=null;failWrite=false;corrupt=true;await assert.rejects(()=>applyStrBudgetApplication(central,preview),/exact STR application/);corrupt=false;stored=null;
const switched={...central,refreshSession:async()=>{currentActor='different';}};await assert.rejects(()=>previewStrBudgetApplication(switched,request),/account or access changed/);assert.equal(writes,3);currentActor=actor;
const invalid={...central,fetchJson:async()=>({...preview,request:{...request,scenarioId:'other'}})};await assert.rejects(()=>previewStrBudgetApplication(invalid,request),/could not be verified/);
console.log('PASS saved origin and scope, draft/active governance, persistent source-category mapping, preview identity, exact financial receipt verification, idempotency, lost response and actor-change protection.');

const finalized={...target,head:{...target.head,status:'investor_approved'},revision:{...target.revision,payload:{...target.revision.payload,investorPublicationId:'publication'}},snapshot:{fingerprint:'exact',monthly:[]}},publication={verified:true,activePeriods:['2026-08'],communityId:cid,scenarioId:sid,publicationId:'publication',revisionId:'prior-approved',snapshot:finalized.snapshot,source:finalized.source};assert.equal(isActiveStrDestination(finalized,publication),true);assert.equal(isActiveStrDestination({...finalized,snapshot:{...finalized.snapshot,monthly:[100]}},publication),false);assert.equal(isActiveStrDestination(finalized,{...publication,scenarioId:'other'}),false);
