// Browser integration uses the shipped STR producer, calculation engine, local
// persistence adapter and export runtimes. All operating data is a QA fixture.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {PDFDocument} from '../docs/portfolio-operations-dashboard/vendor/pdf-lib-1.17.1.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),XLSX=require('../docs/portfolio-operations-dashboard/assets/xlsx.full.min.js'),root=path.resolve('docs/portfolio-operations-dashboard');
const builder=await fs.readFile(path.join(root,'RISE-Budget-Builder.html'),'utf8'),producer=[...builder.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.includes('R.buildState =')&&s.includes('S.apply ='));
assert(producer,'Production STR producer must be present in Budget Builder.');
const html=`<!doctype html><html><head><meta charset="utf-8"><style>body{margin:0;font-family:Arial,sans-serif;background:#f0f5f6}</style></head><body><div id="content"></div><div id="toast"></div><script src="/real-builder.js"></script><script type="module">
const R=window.RBB,A=R.app;R.YEARS=[2026];A.state=R.buildState();A.state.activeProperty='DORO';A.state.activeScenario='SC-WORK';A.state.actuals={};A.state.actualsDetail=[];A.state.periods={};
const property=A.state.properties.find(p=>p.id==='DORO'),group=property.units.find(g=>g.cat!=='str'&&g.units>=12);property.name='RISE Browser QA Property';window.qaGroup=structuredClone(group);
const config={...A.defaultStrCfg(property),propertyId:property.id,programmeId:'QA-COMPARISON',name:'QA saved STR program',unitPicks:[{groupId:group.id,units:12}],unitRamp:{2026:[0,0,4,8,12,12,12,12,12,12,12,12]}};
A.state.strPrograms=[{id:config.programmeId,propertyId:property.id,name:config.name,config,applied:false,lineIds:[]}];A.state.lines=A.state.lines.filter(l=>!l.strProgramId);A.strCfg=structuredClone(config);A.view='segments';A.VIEWS=[{id:'segments',label:'Conventional vs STR'},{id:'compare',label:'Legacy compare'}];
A.year=()=>2026;A.prop=()=>A.state.properties.find(p=>p.id===A.state.activeProperty);A.scenario=()=>A.state.scenarios.find(s=>s.id===A.state.activeScenario);A.isLocked=()=>false;A.go=function(v){this.view=v;this.render();};A.render=function(){document.querySelector('#content').innerHTML=R.views[this.view]();};A.setProperty=function(id){this.state.activeProperty=id;this.render();};A.invalidate=()=>{};A.touch=()=>{};A.toast=t=>document.querySelector('#toast').textContent=t;
window.qaBefore=JSON.stringify(A.state);window.qaCfgBefore=JSON.stringify(A.strCfg);window.applyCalls=0;A.strApply=()=>{window.applyCalls++;throw Error('Comparison must not apply the program');};R.strBuilder.apply=()=>{window.applyCalls++;throw Error('Comparison must not apply the program');};
await import('/features/str-ltr-comparison-ui.mjs');window.qaReady=true;
</script></body></html>`;
const server=createServer(async(req,res)=>{try{const u=new URL(req.url,'http://localhost');if(u.pathname==='/'){res.setHeader('content-type','text/html');res.end(html);return;}if(u.pathname==='/real-builder.js'){res.setHeader('content-type','text/javascript');res.end(producer);return;}const file=path.resolve(root,'.'+u.pathname);if(!file.startsWith(root+path.sep))throw Error('Invalid asset');res.setHeader('content-type',/\.(mjs|js)$/.test(file)?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.png')?'image/png':'application/octet-stream');res.end(await fs.readFile(file));}catch(error){res.statusCode=404;res.end(error.message);}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true}),errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));page.on('console',m=>{if(m.type()==='error')console.error(m.location(),m.text());});
const saved=()=>page.waitForFunction(()=>document.querySelector('[data-comparison-save]')?.dataset.state==='saved');
const change=async(selector,value)=>{const el=page.locator(selector);await el.fill(String(value));await el.press('Tab');};
try{
 const cdp=await page.context().newCDPSession(page);await cdp.send('Runtime.enable');cdp.on('Runtime.exceptionThrown',event=>console.error('Browser exception location:',event.exceptionDetails.url,event.exceptionDetails.lineNumber,event.exceptionDetails.columnNumber));
 await page.goto(base);await page.waitForFunction(()=>window.qaReady);await page.locator('[data-program] option[value="QA-COMPARISON"]').waitFor({state:'attached'});
 assert.match(await page.locator('#atlas-str-ltr-comparison').innerText(),/Choose a saved STR program/);
 await page.locator('[data-program]').selectOption('QA-COMPARISON');await saved();
 assert.equal(await page.locator('[data-program]').inputValue(),'QA-COMPARISON');assert.equal(await page.evaluate(()=>RBB.app.view),'segments');assert.equal(await page.evaluate(()=>applyCalls),0);
 const identity=await page.evaluate(()=>({group:qaGroup,record:RBB.strLtrComparison.ui.record,result:RBB.strLtrComparison.ui.result}));assert.equal(identity.result.metadata.inventoryUnits,12);assert.equal(identity.result.floorPlans[0].sourceLtRent,identity.group.marketRent);assert.equal(identity.result.floorPlans[0].units,12);assert.equal(identity.result.actuals.status,'unavailable');assert.equal(identity.result.totals.actual.noi,null);assert.deepEqual(identity.record.inputs.program.config.unitRamp[2026],[0,0,4,8,12,12,12,12,12,12,12,12]);
 await change('[data-field="name"]','Investor browser case');await saved();await change('[data-rent]',identity.group.marketRent+125);await saved();
 const firstId=await page.evaluate(()=>RBB.strLtrComparison.ui.record.id);await page.locator('[data-action="duplicate"]').click();await page.waitForFunction(id=>RBB.strLtrComparison.ui.record.id!==id,firstId);
 await page.locator('[data-reopen]').selectOption(firstId);await page.waitForFunction(id=>RBB.strLtrComparison.ui.record?.id===id,firstId);await page.waitForFunction(()=>document.querySelector('[data-field="name"]')?.value==='Investor browser case');await saved();assert.equal(await page.locator('[data-rent]').inputValue(),String(identity.group.marketRent+125));assert.equal(await page.locator('[data-field="name"]').inputValue(),'Investor browser case');
 await page.locator('[data-reset-rent]').click();await saved();assert.equal(await page.locator('[data-rent]').inputValue(),String(identity.group.marketRent));
 await page.locator('[data-field="mode"]').selectOption('performance');await saved();assert.match(await page.locator('#atlas-str-ltr-comparison').innerText(),/Recorded STR actuals/);assert.equal(await page.evaluate(()=>RBB.strLtrComparison.ui.result.totals.actual.noi),null);assert.equal(await page.evaluate(()=>RBB.strLtrComparison.ui.result.monthly.length),0);assert.match(await page.locator('#atlas-str-ltr-comparison').innerText(),/Unavailable/);
 await page.locator('[data-field="mode"]').selectOption('budget');await saved();await page.locator('[data-field="occupancy.mode"]').selectOption('custom');await change('[data-field="occupancy.str"]',74);await change('[data-field="occupancy.ltr"]',91);await saved();assert.equal(await page.evaluate(()=>RBB.strLtrComparison.ui.record.scenario.occupancy.str),.74);assert.equal(await page.evaluate(()=>RBB.strLtrComparison.ui.record.scenario.occupancy.ltr),.91);await page.locator('[data-field="occupancy.mode"]').selectOption('full');await saved();assert.equal(await page.evaluate(()=>RBB.strLtrComparison.ui.record.scenario.occupancy.mode),'full');
 await page.locator('[data-include-gl]').check();
 for(const format of ['pdf','pptx','xlsx']){
  const waiting=page.waitForEvent('download',{timeout:60000});await page.locator('[data-export="'+format+'"]').click();const download=await waiting,stream=await download.createReadStream(),parts=[];for await(const part of stream)parts.push(part);const bytes=Buffer.concat(parts);assert(download.suggestedFilename().startsWith('RISE_'));assert(download.suggestedFilename().endsWith('.'+format));assert(bytes.length>1000);
  if(format==='pdf')assert((await PDFDocument.load(bytes)).getPageCount()>=7);
  if(format==='xlsx'){const workbook=XLSX.read(bytes,{type:'array'});assert.equal(workbook.SheetNames.length,8);assert.equal(workbook.Sheets['Floor-plan results'].D8.v,12);assert.equal(workbook.Sheets['Floor-plan results'].E8.v,identity.group.marketRent);const zip=XLSX.CFB.read(bytes,{type:'buffer'}),retained=JSON.parse(new TextDecoder().decode(XLSX.CFB.find(zip,'Root Entry/xl/atlas-comparison.json').content));assert.equal(retained.snapshot.scenario.id,firstId);assert.equal(retained.snapshot.actuals.status,'unavailable');}
 }
 assert.equal(await page.evaluate(()=>JSON.stringify(RBB.app.state)),await page.evaluate(()=>qaBefore),'Loading, editing and exporting comparisons never changes property budget state');assert.equal(await page.evaluate(()=>JSON.stringify(RBB.app.strCfg)),await page.evaluate(()=>qaCfgBefore),'Saved STR configuration remains untouched');assert.equal(await page.evaluate(()=>applyCalls),0);
 await page.reload();await page.waitForFunction(()=>window.qaReady);await page.locator('[data-reopen] option[value="'+firstId+'"]').waitFor({state:'attached'});await page.locator('[data-reopen]').selectOption(firstId);await page.waitForFunction(()=>RBB.strLtrComparison.ui.record?.name==='Investor browser case');assert.equal(await page.locator('[data-field="occupancy.mode"]').inputValue(),'full');await change('[data-rent]',identity.group.marketRent+25);await saved();assert.equal(await page.evaluate(()=>RBB.strLtrComparison.ui.record.scenario.rentOverrides[qaGroup.id]),identity.group.marketRent+25);
 await fs.mkdir('output/playwright/str-ltr-comparison',{recursive:true});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'output/playwright/str-ltr-comparison/calculator.png',fullPage:true});await page.screenshot({path:'output/playwright/str-ltr-comparison/desktop-overview.png'});await page.setViewportSize({width:390,height:844});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'output/playwright/str-ltr-comparison/mobile-overview.png'});await page.screenshot({path:'output/playwright/str-ltr-comparison/mobile-calculator.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Mobile layout must not overflow the viewport outside its scrollable tables');
 assert.deepEqual(errors,[]);console.log('PASS STR/LTR browser direct program load, exact inventory/rent/ramp, no application or property mutation, autosave/reopen/duplicate/reset, missing actual coverage, full occupancy, and PDF/PPTX/XLSX downloads using the real STR producer.');
}catch(error){console.error('Browser comparison status:',await page.locator('[role="alert"],[data-comparison-save]').allTextContents());console.error('Page errors:',errors);throw error;}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
