import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createServer} from 'node:http';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(process.env.ATLAS_PLAYWRIGHT||'playwright'),root=path.resolve('docs/portfolio-operations-dashboard');
const html=`<!doctype html><meta charset="utf-8"><button id="open">Apply retained programme</button><p id="applied"></p><script type="module">
import {openStrBudgetApplication} from '/features/str-budget-application.mjs';
window.writes=0;window.receipt=null;window.actor='editor';const cid='community',record={verified:true,head:{community_id:cid,programme_id:'programme'},revision:{community_id:cid,revision_id:'programme-revision',revision:3,content_hash:'a'.repeat(64),payload:{name:'Saved STR programme',reportSnapshot:{communityName:'Fiscal community'},lines:[{id:'rent',gl:'5144',name:'STR revenue',nature:'income'}]}}},target={head:{community_id:cid,scenario_id:'scenario',revision_id:'target',revision:2,status:'working_draft'},revision:{community_id:cid,revision_id:'target',payload:{name:'Fiscal FY2027',periods:['2026-08','2026-09']}},source:{communityId:cid,registry:{accounts:[{accountCode:'5144',category:'Revenue',nature:'income'}]}},permissions:{canEdit:true,canApprovePublication:false}};
window.central={getSession:()=>({user:{id:actor}}),getConfig:()=>({supabaseUrl:'https://example.invalid'}),refreshSession:async()=>{},fetchJson:async(url,options={})=>{const q=options.body?JSON.parse(options.body):{};if(url.startsWith('/atlas_str_budget_account_mappings'))return [];if(url.endsWith('atlas_read_str_programme_drafts'))return [structuredClone(record)];if(url.endsWith('atlas_read_reforecast_workspace'))return [structuredClone(target)];if(url.endsWith('atlas_read_active_reforecast'))return [];if(url.endsWith('atlas_preview_str_budget_application')){const request=q.p_request;window.preview={verified:true,request,communityId:cid,programmeRevisionId:record.revision.revision_id,targetRevisionId:'target',targetVersion:2,periods:target.revision.payload.periods,previewHash:'b'.repeat(64),application:{programmeId:'programme'},cells:[{period:'2026-08',accountCode:'5144',conventionalAmount:1000,strAmount:500,combinedAmount:1500}],beforeMonthly:[{period:'2026-08',reforecast:{revenue:1000,opex:400,noi:600}}],afterMonthly:[{period:'2026-08',reforecast:{revenue:1500,opex:400,noi:1100}}],excludedClosedPeriods:[]};return structuredClone(preview);}if(url.endsWith('atlas_read_str_budget_application'))return structuredClone(receipt);if(url.endsWith('atlas_apply_str_budget_programme')){writes++;const request=q.p_request;window.receipt={verified:true,applicationId:request.requestId,request,previewHash:preview.previewHash,application:preview.application,head:{revision_id:'applied'},revision:{revision:3,revision_id:'applied',community_id:cid,scenario_id:request.scenarioId,request_id:request.requestId,actor_id:actor},snapshot:{lines:[{accountCode:'5144',period:'2026-08',forecast:1500}]}};throw Error('Synthetic lost response after commit');}throw Error(url);}};document.querySelector('#open').onclick=()=>openStrBudgetApplication({central,record,onApplied:r=>document.querySelector('#applied').textContent='Saved version '+r.revision.revision});window.ready=true;
</script>`;
const server=createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('content-type','text/html');res.end(html);return;}const file=path.resolve(root,'.'+url.pathname);if(!file.startsWith(root+path.sep))throw Error('Invalid path');res.setHeader('content-type','text/javascript');res.end(await fs.readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:1400,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
try{await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready);await page.locator('#open').click();await page.locator('[data-preview]').waitFor();assert.equal(await page.locator('[data-confirm]').isDisabled(),true);assert.match(await page.locator('[data-periods]').innerText(),/2026-08, 2026-09/);await page.locator('[data-destination]').selectOption('active_revision');assert.equal(await page.locator('[data-target] option').count(),0,'Unauthorized active destination has no selectable target');await page.locator('[data-destination]').selectOption('new_draft');await page.locator('[data-name]').fill('Alternative FY2027');await page.locator('[data-reviewed]').check();await page.locator('[data-preview]').click();await page.waitForFunction(()=>!document.querySelector('[data-confirm]').disabled);assert.match(await page.locator('[data-impact]').innerText(),/1,000.00 → 1,500.00/);assert.match(await page.locator('[data-impact]').innerText(),/400.00 → 400.00/);assert.match(await page.locator('[data-impact]').innerText(),/600.00 → 1,100.00/);assert.equal(await page.evaluate(()=>writes),0,'Preview never writes');await page.locator('[data-reason]').fill('Reviewed changed reason');assert.equal(await page.locator('[data-confirm]').isDisabled(),true,'Any changed choice invalidates prior impact');await page.locator('[data-preview]').click();await page.waitForFunction(()=>!document.querySelector('[data-confirm]').disabled);await page.locator('[data-confirm]').click();await page.waitForFunction(()=>document.querySelector('#applied').textContent==='Saved version 3');assert.equal(await page.evaluate(()=>writes),1);assert.match(await page.locator('[data-status]').innerText(),/VP publication is required/);assert.equal(await page.locator('[data-confirm]').isDisabled(),true);assert.deepEqual(errors,[]);console.log('PASS shared STR application modal: exact retained source, fiscal target, existing/new/active permissions, mappings, monthly before/after, changed-input invalidation, confirm and lost-response recovery.');}finally{await browser.close();await new Promise(r=>server.close(r));}
