const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{fixture}=require('./reforecast-fixture.cjs');
(async()=>{
 const {buildStrProgrammeReport}=await import('../docs/portfolio-operations-dashboard/features/saved-str-programmes.mjs');
 const {db,A,B,BUDGET,signIn}=await fixture(),read=name=>fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8'),user='00000000-0000-0000-0000-000000000001';
 try{
 const call=async(name,args)=>(await db.query(`select to_jsonb(public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})) result`,args)).rows[0].result;
 await db.exec('reset role');await db.exec("alter table atlas_approved_budget_versions add column content_hash text,add column fiscal_year integer,add column fiscal_start_month integer,add column scenario_version text;alter table atlas_communities add column version integer default 1,add column budget_calendar jsonb;");
 await db.exec(read('20260924121641_planning_cell_workbook_integrity_governance.sql'));await db.exec(read('20260924121647_immutable_workbook_audits_and_monthly_governance.sql').split('alter function atlas_private.finance_intake_validation')[0]);
 for(const name of ['20260924165534_reforecast_builder_governance.sql','20260924165542_reforecast_report_receipts.sql','20260924232842_reforecast_governed_close_scope.sql','20260924232853_reforecast_str_overlay_isolation.sql','20260924235553_reforecast_active_import_close_scope.sql','20260925012933_reforecast_atomic_create_from_import.sql','20260925020220_reforecast_import_source_relationships.sql','20260925020222_reforecast_saved_json_str_programme.sql','20260925020226_reforecast_import_source_occurrence_index.sql','20260925071533_reforecast_request_identity_consistency.sql','20260925162050_budget_governed_draft_investor_lifecycle.sql','20260925174317_shared_str_programme_draft_versions.sql','20260929154018_budget_export_integrity_history.sql','20260929154033_budget_leasing_driver_authority.sql','20260929154111_verified_str_budget_application.sql'])await db.exec(read(name));
 await db.query("update atlas_approved_budget_versions set payload=jsonb_set(payload,'{rows}',(payload->'rows')||$1::jsonb)",[[{glCode:'5144',monthly:Array(12).fill(0)}]]);await db.exec("insert into atlas_financial_close_rows select version_id,'5144',0,'{}' from atlas_financial_close_versions");
 await db.query('update atlas_communities set budget_calendar=$1',[{verified:true,classification:'Multifamily',startMonth:1,source:'Test reviewed calendar'}]);await signIn(1);
 const accounts=[['5120','Rent','income'],['5144','STR rent','income'],['5220','Vacancy','contra_income'],['6100','Payroll','expense'],['6200','Utilities','expense'],['8100','Capital','capital']].map(([accountCode,category,nature])=>({accountCode,category,nature,placement:nature==='capital'?'below_noi':'above_noi',effectiveFrom:'2026-01'}));
 const registry=await call('atlas_save_reforecast_registry',[A,null,randomUUID(),{accounts,driverMappings:{},reason:'Reviewed canonical mapping',effectiveDate:'2026-01-01'}]),periods=['2026-01','2026-02','2026-03'];
 const budgetPayload={name:'Canonical property target',model:'conventional',governanceSchemaVersion:2,calendar:{basis:'calendar',startMonth:1,confirmed:true,periods,scenario:'Target',reviewedBy:user,reviewedAt:'2026-09-29T00:00:00Z'},periods,baselineType:'original_budget',baselineVersionIds:[BUDGET],registryVersionId:registry.version_id,ownerId:user,reviewerId:user,drivers:[],overrides:[],reason:'Create canonical budget target'};
 const target=await call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',budgetPayload]);
 const years=[2026],sourcePropertyId='source-property',sourceProgrammeId='source-programme',config={propertyId:sourcePropertyId,programmeId:sourceProgrammeId,name:'STR Builder programme',adr:125},property={id:sourcePropertyId,name:'Community',units:[]};
 const lines=[['rent','5144','income',101.005],['displaced','5220','contra_income',-10.001234],['utilities','6200','expense',9.95],['furniture','8100','capital',50]].map(([id,gl,nature,amount])=>({id,gl,nature,name:id,propertyId:sourcePropertyId,strProgramId:sourceProgrammeId,yearData:{2026:Array(12).fill(amount)}}));
 const payload={schemaVersion:'atlas.str-programme-draft.v1',name:config.name,sourcePropertyId,sourceProgrammeId,config,property,groups:[],programme:{id:sourceProgrammeId,propertyId:sourcePropertyId,name:config.name,applied:false,config},lines,years,reportBasisConfig:config,sourceContext:{property,lines:[],libraries:{}},targetBudget:null,reason:'Reviewed programme drivers',reportSnapshot:buildStrProgrammeReport({name:config.name,communityName:'Community',years,lines,config})};
 const programme=await call('atlas_save_str_programme_draft',[A,randomUUID(),0,randomUUID(),payload]);
 const request={communityId:A,requestId:randomUUID(),scenarioId:target.head.scenario_id,programmeRevisionId:programme.revision.revision_id,targetRevisionId:target.revision.revision_id,destination:'existing_draft',name:'Canonical property target',reason:'Reviewed STR property application',reviewedAt:'2026-09-29T12:00:00Z',mappings:lines.map(line=>({sourceLineId:line.id,sourceGL:line.gl,accountCode:line.gl,parentAbsent:line.gl==='5144',confirmed:true,reason:'Reviewed account contribution'}))};
 const preview=await call('atlas_preview_str_budget_application',[request]);assert.equal(preview.verified,true);assert.deepEqual(preview.excludedClosedPeriods,['2026-01']);assert.equal(preview.cells.find(c=>c.period==='2026-02'&&c.accountCode==='5144').combinedAmount,101.01);assert.equal(preview.cells.find(c=>c.period==='2026-02'&&c.accountCode==='6200').combinedAmount,59.95);
 assert.deepEqual(await call('atlas_preview_str_budget_application',[request]),preview,'Preview is deterministic and read-only');assert.equal((await db.query('select count(*)::int n from atlas_reforecast_revisions')).rows[0].n,1);
 await assert.rejects(()=>call('atlas_apply_str_budget_programme',[request,'bad']),/changed/);
 const applied=await call('atlas_apply_str_budget_programme',[request,preview.previewHash]);assert.equal(applied.revision.revision,2);assert.equal(applied.published,false);assert.deepEqual(applied.application,preview.application);assert.deepEqual(await call('atlas_apply_str_budget_programme',[request,preview.previewHash]),applied,'Repeated confirmation returns exact receipt');
 assert.equal(applied.snapshot.lines.find(l=>l.accountCode==='5120'&&l.period==='2026-02').forecast,1000,'Unrelated conventional rental account retained');assert.equal(applied.snapshot.lines.find(l=>l.accountCode==='5220'&&l.period==='2026-02').forecast,-60);assert.equal(applied.snapshot.lines.find(l=>l.accountCode==='6200'&&l.period==='2026-01').forecast,50,'Closed actuals remain immutable');
 assert.equal((await db.query('select count(*)::int n from atlas_str_budget_account_mappings')).rows[0].n,4);
 const replacement={...request,requestId:randomUUID(),targetRevisionId:applied.revision.revision_id},again=await call('atlas_preview_str_budget_application',[replacement]);assert.equal(again.cells.find(c=>c.accountCode==='5144'&&c.period==='2026-02').combinedAmount,101.01,'Reapplication replaces, never doubles');assert.equal(again.cells.find(c=>c.accountCode==='6200'&&c.period==='2026-02').conventionalAmount,50);
 const next=await call('atlas_apply_str_budget_programme',[replacement,again.previewHash]);assert.equal(next.revision.payload.strBudgetApplications.length,1);assert.deepEqual(await call('atlas_read_str_budget_application',[A,request.requestId]),applied,'Historical receipt remains exact after a later revision');
 await assert.rejects(()=>call('atlas_preview_str_budget_application',[{...request,requestId:randomUUID()}]),/destination budget changed/);
 const fork={...request,destination:'new_draft',requestId:randomUUID(),scenarioId:randomUUID(),targetRevisionId:next.revision.revision_id,name:'Alternative mixed draft'},forkPreview=await call('atlas_preview_str_budget_application',[fork]),forked=await call('atlas_apply_str_budget_programme',[fork,forkPreview.previewHash]);assert.equal(forked.revision.revision,1);assert.equal(forked.revision.payload.forkedFromRevisionId,next.revision.revision_id);assert.equal(forked.revision.status,'working_draft');
 const bad={...next.revision.payload,strBudgetApplications:[{...next.revision.payload.strBudgetApplications[0],programmeId:randomUUID()}]};await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,next.head.scenario_id,next.head.revision,randomUUID(),'save_draft',bad]),/verified STR Builder/);
 const altered=structuredClone(next.revision.payload);altered.overrides[0].amount++;await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,next.head.scenario_id,next.head.revision,randomUUID(),'save_draft',altered]),/confirmed Builder source/);
 // Manual decisions remain possible, but STR-linked finance must warn until reviewed.
 const manual=structuredClone(forked.revision.payload),adjusted=manual.overrides.find(o=>o.accountCode==='5144'&&o.period==='2026-02');adjusted.source={kind:'user'};adjusted.amount=145000;adjusted.after=145000;adjusted.reason='Known higher revenue';
 const warned=await call('atlas_save_reforecast_scenario',[A,forked.head.scenario_id,1,randomUUID(),'save_draft',manual]);assert(warned.snapshot.driverValidation.warnings.some(w=>w.accountCode==='5144'&&w.expectedAmount===101.01&&w.manualAmount===145000));
 await assert.rejects(()=>call('atlas_preview_str_budget_application',[{...request,requestId:randomUUID(),scenarioId:warned.head.scenario_id,targetRevisionId:warned.revision.revision_id}]),/existing manual driver adjustment/);
 const accepted=structuredClone(warned.revision.payload),decision=accepted.overrides.find(o=>o.accountCode==='5144'&&o.period==='2026-02');decision.driverOverride={reason:'Known Revenue Change',comment:'Reviewed contract',userId:'spoof',timestamp:'2000-01-01T00:00:00Z',calculatedAmount:101.01,manualAmount:145000,affectedDrivers:['str-programme-'+programme.head.programme_id]};
 const approvedManual=await call('atlas_save_reforecast_scenario',[A,forked.head.scenario_id,2,randomUUID(),'save_draft',accepted]);assert(!approvedManual.snapshot.driverValidation.warnings.some(w=>w.accountCode==='5144'));assert.equal(approvedManual.revision.payload.overrides.find(o=>o.driverOverride).driverOverride.userId,user);
 await assert.rejects(()=>call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',{...budgetPayload,model:'short_term'}]),/STR Builder/);
 // Publishing is the existing explicit VP workflow; applying to active creates a separate draft.
 let activeTarget=await call('atlas_save_reforecast_scenario',[A,randomUUID(),0,randomUUID(),'save_draft',{...budgetPayload,registryVersionId:registry.version_id,name:'Active conventional',calendar:{...budgetPayload.calendar,scenario:'Active conventional'}}]);
 for(const action of ['reconcile','ready','submit']){activeTarget=await call('atlas_save_reforecast_scenario',[A,activeTarget.head.scenario_id,activeTarget.head.revision,randomUUID(),action,activeTarget.revision.payload]);}await signIn(5);activeTarget=await call('atlas_save_reforecast_scenario',[A,activeTarget.head.scenario_id,activeTarget.head.revision,randomUUID(),'approve_lock',activeTarget.revision.payload]);const activeBefore=await call('atlas_read_active_reforecast',[[A],periods]);
 const activeRequest={...request,requestId:randomUUID(),scenarioId:randomUUID(),destination:'active_revision',name:'New revision of active',targetRevisionId:activeTarget.revision.revision_id,mappings:request.mappings.map(m=>({...m,accountCode:m.accountCode==='5144'?'5120':m.accountCode}))},activePreview=await call('atlas_preview_str_budget_application',[activeRequest]),activeDraft=await call('atlas_apply_str_budget_programme',[activeRequest,activePreview.previewHash]);assert.equal(activeDraft.revision.status,'working_draft');assert.notEqual(activeDraft.head.scenario_id,activeTarget.head.scenario_id);assert.deepEqual(await call('atlas_read_active_reforecast',[[A],periods]),activeBefore,'Application never publishes or changes existing active finance');
 const finalized=await call('atlas_save_reforecast_scenario',[A,activeTarget.head.scenario_id,activeTarget.head.revision,randomUUID(),'investor_approve',{...activeTarget.revision.payload,investorApprovalDate:'2026-09-29',reason:'Investor final approval'}]);assert.equal(finalized.revision.status,'investor_approved');assert.deepEqual(finalized.snapshot,activeTarget.snapshot);
 const finalRequest={...activeRequest,requestId:randomUUID(),scenarioId:randomUUID(),targetRevisionId:finalized.revision.revision_id},finalPreview=await call('atlas_preview_str_budget_application',[finalRequest]),finalDraft=await call('atlas_apply_str_budget_programme',[finalRequest,finalPreview.previewHash]);assert.equal(finalDraft.revision.status,'working_draft');assert.equal(finalDraft.revision.payload.forkedFromRevisionId,finalized.revision.revision_id);assert.deepEqual((await call('atlas_read_active_reforecast',[[A],periods]))[0].snapshot,activeBefore[0].snapshot);await signIn(1);
 // The shipped producer's retained fiscal schedule reconciles in SQL without re-running its STR calculator.
 const vm=require('node:vm'),html=fs.readFileSync(path.join(__dirname,'../docs/portfolio-operations-dashboard/RISE-Budget-Builder.html'),'utf8'),start=html.indexOf('var RBB ='),end=html.indexOf('})(RBB);',html.indexOf('R.buildState ='))+'})(RBB);'.length,context=vm.createContext({console,Date,Map,Set,window:{},setTimeout:()=>0});vm.runInContext(html.slice(start,end),context);const R=context.RBB,state=R.buildState(),actualProperty=state.properties.find(p=>p.id==='DORO'),group=actualProperty.units.find(row=>row.units>=2),cfg={propertyId:actualProperty.id,programmeId:'test-programme',name:'Schedule acceptance',unitPicks:[{groupId:group.id,units:2}],unitRamp:{2026:Array(12).fill(2),2027:Array(12).fill(2)},adr:200,occupancy:.5,alos:2,blockedPct:0,curve:'flat'};
 R.strBuilder.apply(state,cfg,[2026,2027]);const produced=state.strPrograms.find(p=>p.id==='test-programme'),producedLines=state.lines.filter(l=>l.strProgramId==='test-programme'),fiscalPeriods=Array.from({length:12},(_,i)=>{const d=new Date(Date.UTC(2026,7+i,1));return d.toISOString().slice(0,7);}),report=buildStrProgrammeReport({name:'Schedule acceptance',communityName:'Community',years:[2026,2027],lines:producedLines,config:cfg});
 await db.exec('reset role');const checked=(await db.query('select atlas_private.shared_str_schedules($1) result',[{periods:fiscalPeriods,strBudgetApplications:[{programmeId:'test-programme',supportingSchedules:JSON.parse(JSON.stringify(produced.supportingSchedules)),reportSnapshot:report}]}])).rows[0].result;assert.deepEqual(checked.issues,[],'Actual STR Builder fiscal schedule must reconcile to its retained signed monthly revenue/expense lines');assert.equal(checked.schedules[0].monthly[0].period,'2026-08');assert.equal(checked.schedules[0].monthly.at(-1).period,'2027-07');assert.equal(checked.schedules[0].totals.adr,200);
 await signIn(2);await assert.rejects(()=>call('atlas_preview_str_budget_application',[{...fork,requestId:randomUUID(),scenarioId:randomUUID(),destination:'active_revision'}]),/authorized VP/);await assert.rejects(()=>call('atlas_apply_str_budget_programme',[request,preview.previewHash]),/reused/);
 await signIn(4);await assert.rejects(()=>call('atlas_preview_str_budget_application',[request]),/denied/);assert.equal((await db.query('select * from atlas_str_budget_account_mappings')).rows.length,0);await assert.rejects(()=>call('atlas_read_str_budget_application',[A,request.requestId]),/denied/);
 await db.exec('reset role');await assert.rejects(()=>db.exec('delete from atlas_str_budget_applications'),/immutable/);await db.exec('set role anon');await assert.rejects(()=>call('atlas_preview_str_budget_application',[request]),/permission denied/);
 console.log('PASS STR origin, preview/confirm, conventional preservation, closed-period protection, exact-cent accounting, replacement without doubling, persistent mapping, forked drafts, actor/idempotency/concurrency and immutable receipt/RLS.');
 }finally{await db.close();}
})().catch(error=>{console.error(error.message,error.where||'',error.stack);process.exitCode=1;});
