import assert from 'node:assert/strict';import fs from 'node:fs';
import {parseForecast,percentage,matchForecast,recommend,blendedForecast,reconcile,actualMetrics,canActivate} from '../docs/portfolio-operations-dashboard/features/utility-forecast.mjs';
assert.equal(percentage(''),null);assert.equal(percentage('Utility Bills Unavailable'),null);assert.equal(percentage('-0.4%'),-.004);assert.equal(percentage('0%'),0);
const row={communityId:'one',type:'electricity',provider:'A',city:'Jacksonville',state:'FL',status:'Eligible',monthly:Array(12).fill(.034),sheet:'Report',row:11};
assert.equal(matchForecast([row],{communityId:'other',type:'electricity',location:{city:'Jacksonville',state:'FL'},provider:'B'}).row,null);
assert.equal(matchForecast([row],{communityId:'other',type:'electricity',location:{city:'Jacksonville',state:'FL'},provider:'A'}).row,row);
assert.equal(matchForecast([{...row,cancelled:true}],{communityId:'one',type:'electricity'}).row,null);
assert.equal(matchForecast([{...row,communityId:null}],{type:'electricity',provider:'A',location:{city:'Jacksonville',state:'FL'}}).row,null);
assert.equal(blendedForecast(.1,.2,{water:75,sewer:25,source:'bills'}),.125);assert.equal(blendedForecast(.1,.2,null),null);
assert.equal(recommend({forecast:.1,historicalCost:100,basis:'prior August'}).cost,110.00000000000001);
assert.equal(recommend({forecast:0,historicalCost:100,basis:'prior August'}).cost,100);
assert.equal(recommend({forecast:null,historicalCost:100,basis:'prior August'}).cost,null);
assert.equal(recommend({forecast:.1,usage:20,tariff:2,fixed:10,demand:5}).cost,59);
assert.equal(actualMetrics({totalCost:100,occupiedUnits:10}).usage,null);
const dir=process.env.UTILITY_FIXTURE_DIR;
if(dir){const versions=['initial','updated'].map(v=>{const f=JSON.parse(fs.readFileSync(dir+'/'+v+'.json'));return parseForecast(f.sheets,{...f,resolve:p=>p});});const [initial,updated]=versions;
 assert.deepEqual(updated.validation.errors,[]);assert.deepEqual(initial.validation.errors,[]);assert.equal(initial.counts.active,96);assert.equal(updated.counts.active,80);assert.equal(updated.counts.cancelled,16);assert.equal(updated.counts.properties,20);
 const find=(p,t)=>updated.rows.find(r=>r.property.toLowerCase().includes(p)&&r.type===t);
 assert.ok(Math.abs(find('bartram','electricity').annual-.06075)<1e-10);assert.equal(find('bartram','electricity').monthly[0],.034);
 assert.ok(Math.abs(find('sereno','natural_gas').annual-.01275)<1e-10);assert.equal(find('sereno','natural_gas').monthly[8],-.004);
 assert.ok(Math.abs(find('preserve','water').annual-.2495)<1e-10);
 assert.ok(updated.rows.filter(r=>/doro/i.test(r.property)).every(r=>r.monthly.every(v=>v===null)));
 assert.equal(reconcile(initial,updated).length,36,'36 active rows change including analyst metadata');assert.ok(canActivate(updated,initial));assert.equal(canActivate(initial,updated),false);
 console.log(JSON.stringify({initial:initial.counts,updated:updated.counts,changedActiveCombinations:36,changedForecastOrProviderValues:24,initialCompleted:initial.completed,updatedCompleted:updated.completed}));
}else console.log('Private workbook regression skipped: set UTILITY_FIXTURE_DIR');
console.log('Utility forecast numeric, matching, exclusion and normalization checks passed');
const headings=['Property Name','City','State','Utility Type','Assigned To','Utility Provider','Projected Annual (+/- %)','Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul'];
const sheet=[['Budget Type:','Fiscal Year 2027 (08/01/26 - 07/31/27)'],['Completed Date (Initial Version):',46080],headings,['Synthetic','Test','FL','Electricity','Analyst','Provider',.01,...Array(12).fill(.01)]];
let p=parseForecast({Report:sheet},{resolve:()=> 'one'});assert.equal(p.validation.errors.length,0);assert.ok(Math.abs(p.rows[0].annual-.01)<1e-10);
let bad=structuredClone(sheet);bad[2][8]='Aug';assert(parseForecast({Report:bad},{resolve:()=> 'one'}).validation.errors.some(e=>e.includes('distinct')));
bad=structuredClone(sheet);bad.push(bad.at(-1));assert(parseForecast({Report:bad},{resolve:()=> 'one'}).validation.errors.some(e=>e.includes('Duplicate')));
bad=structuredClone(sheet);bad[3][6]=.2;assert(parseForecast({Report:bad},{resolve:()=> 'one'}).validation.errors.some(e=>e.includes('reconcile')));
bad=structuredClone(sheet);bad[3][7]='';assert(parseForecast({Report:bad},{resolve:()=> 'one'}).validation.errors.some(e=>e.includes('Missing')));
console.log('Header, fiscal period, duplicate, annual reconciliation and missing-percentage validation passed');
