const {PGlite}=require('@electric-sql/pglite'),fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
(async()=>{const db=new PGlite();await db.exec(`create role authenticated;create role anon;create schema auth;create schema atlas_private;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create table atlas_user_profiles(user_id uuid,role text,status text,locked_tab_ids text[]);create table atlas_communities(community_id uuid primary key);create function atlas_private.command_access(cid uuid,action text) returns boolean language sql security definer as $$select auth.uid()='00000000-0000-0000-0000-000000000001'::uuid$$;grant usage on schema auth,atlas_private to authenticated;insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');insert into atlas_user_profiles values('00000000-0000-0000-0000-000000000001','admin','active','{}');insert into atlas_communities values('10000000-0000-0000-0000-000000000001');`);
await db.exec(fs.readFileSync('docs/portfolio-operations-dashboard/centralization/utility-forecasts.sql','utf8'));
await db.exec(`set request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';set role authenticated;`);
const source=Buffer.from('synthetic source'),hash=crypto.createHash('sha256').update(source).digest('hex');const f={schemaVersion:1,fileName:'synthetic.csv',fileHash:hash,fiscalYear:2027,start:'2026-08-01',end:'2027-07-31',periods:Array.from({length:12},(_,i)=>new Date(Date.UTC(2026,7+i,1)).toISOString().slice(0,7)),completed:'2026-09-01',validation:{errors:[]},rows:[{communityId:'10000000-0000-0000-0000-000000000001',property:'Test',type:'electricity',sheet:'Report',row:11,cancelled:false,city:'Test',state:'FL',provider:'A',status:'Eligible',monthly:Array(12).fill(.02),annual:.02,reportedAnnual:.02}]};
const save=async x=>(await db.query('select atlas_import_utility_forecast($1,$2) id',[x,source.toString('base64')])).rows[0].id;
const id=await save(f);assert.equal(await save(f),id,'hash replay idempotent');const activate=async(expected,rollback=false)=>(await db.query('select atlas_activate_utility_forecast($1,$2,$3,$4) id',[id,expected,'Reviewed forecast',rollback])).rows[0].id;
const second=Buffer.from('earlier synthetic source'),older={...f,fileHash:crypto.createHash('sha256').update(second).digest('hex'),completed:'2026-02-27'};
const olderId=(await db.query('select atlas_import_utility_forecast($1,$2) id',[older,second.toString('base64')])).rows[0].id;
const activation=await activate(null);assert.equal(await activate(id),activation);await assert.rejects(()=>activate(null),/changed/);
await assert.rejects(()=>db.query('select atlas_activate_utility_forecast($1,$2,$3,false)',[olderId,id,'Restore earlier forecast']),/newer/);
await db.query('select atlas_activate_utility_forecast($1,$2,$3,true)',[olderId,id,'Reviewed rollback to retained source']);
assert.equal((await db.query('select vintage_id from atlas_utility_forecast_activations order by id desc limit 1')).rows[0].vintage_id,olderId);

await assert.rejects(()=>db.query('update atlas_utility_forecast_rows set payload=$1',[{}]),/permission denied/);
await db.exec(`reset role;set request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';set role authenticated;`);
assert.equal((await db.query('select * from atlas_utility_forecast_rows')).rows.length,0);assert.equal((await db.query('select * from atlas_utility_forecast_files')).rows.length,0);await assert.rejects(()=>save(f),/Admin/);
console.log('Utility database immutable source, hash replay, optimistic activation and access isolation passed');await db.close();})().catch(e=>{console.error(e);process.exit(1)});
