import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
import {createHash,randomUUID} from 'node:crypto';
import {workbookEvidenceHash} from '../docs/portfolio-operations-dashboard/features/workbook-integrity.mjs';
import {inspectActualWorkbook} from './doro-workbook-acceptance.mjs';
const require=createRequire(import.meta.url),{fixture}=require('./financial-intake-fixture.cjs');
const {db,cid,other,signIn}=await fixture();
const hash=v=>createHash('sha256').update(v).digest('hex'),source=Buffer.from('Exact source fixture'),sourceHash=hash(source);
const migrations=['20260924121641_planning_cell_workbook_integrity_governance.sql','20260924121647_immutable_workbook_audits_and_monthly_governance.sql','20260924232845_bounded_workbook_audit_transport.sql','20260925011545_workbook_audit_validation_performance.sql','20260925032350_workbook_raw_json_canonical.sql','20260925033844_workbook_raw_evidence_projections.sql','20260925035358_workbook_typed_raw_validation.sql'];
const call=async(name,args)=>(await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
const seal=a=>{delete a.fingerprint;a.fingerprint=workbookEvidenceHash(a);return a;};
const cell=(address,value,extra={})=>({id:'Input!'+address,sheet:'Input',address,row:Number(address.match(/\d+/)[0]),column:address.charCodeAt(0)-64,type:typeof value==='number'?'n':'s',value,...extra});
const makeAudit=()=>{const cells=[cell('A1',0),cell('A2',null,{populated:true}),cell('B1',2,{formula:'A1+2',cachePresent:true,cachedValue:2}),cell('C1','GL'),cell('D1','Sep 2026'),cell('C2','5120 (Gross Potential Rent (GPR))'),cell('D2',17),cell('D3',0,{numberFormat:'0.00',arbitraryPreservedField:{blank:null,zero:0}})];return seal({schemaVersion:'atlas.workbook-integrity.v1',inventory:{sourceHash,packageMetadataAvailable:true,dateSystem:'1900',definedNames:[],sheets:[{name:'Input',cells,rowMetadata:[{index:1}],columnMetadata:[{index:1}],rowInventory:[{row:1}]}]},graph:{nodes:cells.map(c=>({id:c.id,sheet:c.sheet,address:c.address,formula:c.formula??null,kind:'cell'})),edges:[{from:'Input!B1',to:'Input!A1'}]},authorityScope:{type:'selected_cells_and_dependencies',selectedCells:['Input!B1'],requiredNodes:['Input!A1','Input!B1']},findings:[],summary:{populatedCells:cells.length,formulas:1}});};
const prepare=async a=>{await db.exec('reset role');const start=performance.now();const r=(await db.query('select atlas_private.prepare_workbook_projection_raw($1::json,$2) result',[JSON.stringify(a),a.fingerprint])).rows[0].result;return {...r,elapsedMs:Math.round(performance.now()-start)};};
const stage=async(a,bytes=source,{serialized=JSON.stringify(a),requestId=randomUUID(),community=cid}={})=>{
 const auditBytes=Buffer.from(serialized),chunkBytes=196608,manifest={schemaVersion:'atlas.workbook-audit-upload.v1',sourceHash:hash(bytes),fingerprint:a.fingerprint,chunkBytes,audit:{byteLength:auditBytes.length,sha256:hash(auditBytes),chunkCount:Math.ceil(auditBytes.length/chunkBytes)},source:{byteLength:bytes.length,sha256:hash(bytes),chunkCount:Math.ceil(bytes.length/chunkBytes)}},manifestHash=workbookEvidenceHash(manifest);
 await signIn(1);const u=await call('atlas_begin_workbook_audit_upload',[community,requestId,manifest,manifestHash]);
 for(const [stream,data] of [['audit',auditBytes],['source',bytes]])for(let offset=0,index=0;offset<data.length;offset+=chunkBytes,index++){const chunk=data.subarray(offset,offset+chunkBytes);await call('atlas_put_workbook_audit_chunk',[u.upload_id,stream,index,chunk.toString('base64'),hash(chunk)]);}
 return {u,manifest,manifestHash,requestId,auditBytes,bytes,a};
};
const finalize=s=>call('atlas_finalize_workbook_audit_upload',[s.u.upload_id,s.requestId,s.manifestHash]);
const rawRead=async(receipt,s)=>{for(const stream of ['audit','source']){const chunks=[];for(let i=0;i<s.manifest[stream].chunkCount;i++){const c=await call('atlas_read_workbook_audit_chunk',[receipt.audit_id,stream,i,s.manifestHash]);chunks.push(Buffer.from(c.data,'base64'));}const actual=Buffer.concat(chunks),expected=stream==='audit'?s.auditBytes:s.bytes;assert.equal(actual.length,expected.length,'Raw evidence byte length');assert.equal(hash(actual),hash(expected),'Raw evidence byte hash');}};
const ref=(receipt)=>({auditId:receipt.audit_id,fingerprint:receipt.fingerprint,manifestHash:receipt.manifest_hash});
const adversaries=[];let actualProof=null;
try{
 await db.exec('reset role');for(const name of migrations)await db.exec(fs.readFileSync(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
 const unchanged=(await db.query("select pg_get_functiondef('atlas_private.finalize_workbook_audit_upload(uuid,uuid,text)'::regprocedure) f,pg_get_functiondef('atlas_private.resolve_workbook_audit(jsonb,text)'::regprocedure) r")).rows[0];assert(!unchanged.f.includes('finalize_workbook_audit_upload_projected'));assert(!unchanged.r.includes('resolve_workbook_audit_projected'));
 await db.exec("alter function public.atlas_finalize_workbook_audit_upload(uuid,uuid,text) set statement_timeout='45s'");
 // This explicit test fixture is intentionally absent from deployable migrations.
 await db.exec(fs.readFileSync(new URL('./fixtures/workbook-raw-evidence-projection-activation.sql',import.meta.url),'utf8'));
 const grants=(await db.query("select p.proname,n.nspname,p.proconfig,has_function_privilege('anon',p.oid,'EXECUTE') anon,has_function_privilege('authenticated',p.oid,'EXECUTE') authenticated from pg_proc p join pg_namespace n on n.oid=p.pronamespace where p.proname in ('atlas_finalize_workbook_audit_upload','atlas_save_workbook_audit','finalize_workbook_audit_upload_projected','prepare_workbook_projection_raw','resolve_workbook_audit_projected','save_workbook_audit_before_projection')")).rows;for(const g of grants){assert.equal(g.anon,false);assert.equal(g.authenticated,g.nspname==='public');if(g.nspname==='public')assert(g.proconfig.includes('statement_timeout=45s'));}
 const base=makeAudit(),prepared=await prepare(base);assert.deepEqual(prepared.issues,[]);assert.equal(prepared.state,'validated');assert.equal(prepared.runtime.schemaVersion,'atlas.workbook-runtime-projection.v1');assert(!('graph' in prepared.runtime));assert.deepEqual(prepared.runtime.inventory.sheets[0].cells,base.inventory.sheets[0].cells);assert.equal(prepared.runtime.inventory.dateSystem,'1900');
 const attacks=[
  ['inactive node binding',a=>a.graph.nodes.find(n=>n.id==='Input!C1').address='Z9','workbook_node_binding'],
  ['inactive edge endpoint',a=>a.graph.edges.push({from:'Input!C1',to:'Input!MISSING'}),'workbook_edge_invalid'],
  ['inactive duplicate node',a=>a.graph.nodes.push({...a.graph.nodes.at(-1)}),'workbook_duplicate_node'],
  ['inactive invalid range',a=>a.graph.nodes.push({id:'@range:Input!A9:A1',sheet:'Input',kind:'range',start:'A9',end:'A1'}),'workbook_range_binding'],
  ['inactive defined name',a=>a.inventory.definedNames.push({name:'GlobalRate',sheet:null,reference:'Input!A1'}),'workbook_name_binding'],
  ['source inventory count',a=>a.summary.populatedCells--,'workbook_inventory_count'],
  ['fake selected source',a=>{a.graph.nodes.push({id:'Input!Z99',sheet:'Input',address:'Z99'});a.authorityScope.requiredNodes.push('Input!Z99');a.authorityScope.selectedCells.push('Input!Z99');},'workbook_scope_invalid'],
  ['scope closure',a=>a.graph.edges.push({from:'Input!B1',to:'Input!D2'}),'workbook_scope_incomplete'],
  ['active formula omitted edge',a=>a.graph.edges=[],'workbook_dependency_omitted'],
  ['active range omitted inactive source',a=>{a.graph.nodes.push({id:'@range:Input!D1:D3',sheet:'Input',kind:'range',start:'D1',end:'D3'});a.authorityScope.requiredNodes.push('@range:Input!D1:D3');},'workbook_range_cell_omitted'],
 ];
 for(const [name,edit,code] of attacks){const a=structuredClone(base);edit(a);seal(a);const result=await prepare(a);assert(result.issues.some(i=>i.code===code),name+': '+JSON.stringify(result.issues));adversaries.push(name);}
 const named=structuredClone(base);named.inventory.definedNames.push({name:'InactiveName',sheet:null,reference:'Input!D2'});named.graph.nodes.push({id:'@name:*!InactiveName',sheet:null,formula:'Input!D2',kind:'name'});named.graph.edges.push({from:'@name:*!InactiveName',to:'Input!D2'});seal(named);assert.deepEqual((await prepare(named)).issues,[],'All supplemental name bindings retained without making their formulas authoritative');
 const unscoped=structuredClone(base);delete unscoped.authorityScope;seal(unscoped);assert.deepEqual((await prepare(unscoped)).issues,[],'Small unscoped complete audits keep existing approval semantics');
 const large=structuredClone(base);delete large.authorityScope;large.graph.nodes.push(...Array.from({length:10001},(_,i)=>({id:'Input!Z'+(i+1),sheet:'Input',address:'Z'+(i+1),kind:'cell'})));seal(large);const waiting=await prepare(large);assert.equal(waiting.state,'needs_authority_review');assert(waiting.issues.some(i=>i.code==='workbook_authority_review_required'));
 const declared=structuredClone(base);declared.findings.push({id:'blocked-1',code:'test_blocker',severity:'blocking',reason:'Retained original blocker'});seal(declared);assert.equal((await prepare(declared)).issues.filter(i=>i.code==='workbook_test_blocker').length,1);
 await signIn(1);await assert.rejects(db.query('select atlas_private.prepare_workbook_projection_raw($1::json,$2)',[JSON.stringify(base),base.fingerprint]),/permission denied/);await assert.rejects(db.query('select * from atlas_private.workbook_audit_projections'),/permission denied/);
 const staged=await stage(base),concurrent=await Promise.all([finalize(staged),finalize(staged)]),receipt=concurrent[0];assert.equal(concurrent[1].audit_id,receipt.audit_id,'Overlapping client retries use one immutable audit');assert.equal((await finalize(staged)).audit_id,receipt.audit_id);await rawRead(receipt,staged);
 await db.exec('reset role');const stored=(await db.query('select a.evidence,p.* from atlas_workbook_audits a join atlas_private.workbook_audit_projections p using(audit_id) where a.audit_id=$1',[receipt.audit_id])).rows[0];assert.equal(stored.evidence.schemaVersion,'atlas.workbook-evidence-manifest.v2');assert.equal(stored.projection_hash,workbookEvidenceHash(stored.runtime_projection));assert.deepEqual((await db.query('select atlas_private.resolve_workbook_audit($1,$2) r',[ref(receipt),sourceHash])).rows[0].r,prepared.runtime);await assert.rejects(db.query('select atlas_private.resolve_workbook_audit($1,$2)',[{auditId:receipt.audit_id,fingerprint:receipt.fingerprint},sourceHash]),/manifest reference required/);
 await assert.rejects(db.query('update atlas_private.workbook_audit_projections set projection_hash=$1 where audit_id=$2',['a'.repeat(64),receipt.audit_id]),/immutable/i);
 await assert.rejects(db.query('delete from atlas_private.workbook_audit_projections where audit_id=$1',[receipt.audit_id]),/immutable/i);
 await signIn(1);const legacyReceipt=await call('atlas_save_workbook_audit',[cid,sourceHash,base,randomUUID()]);assert.equal(legacyReceipt.manifest_hash,receipt.manifest_hash,'Legacy direct-save dedupe returns the original raw manifest');
 const legacyNew=structuredClone(base);legacyNew.previousFingerprint='a'.repeat(64);seal(legacyNew);const legacyNewReceipt=await call('atlas_save_workbook_audit',[cid,sourceHash,legacyNew,randomUUID()]);assert(!legacyNewReceipt.manifest_hash);await db.exec('reset role');assert.deepEqual((await db.query('select evidence from atlas_workbook_audits where audit_id=$1',[legacyNewReceipt.audit_id])).rows[0].evidence,legacyNew,'Previously supported direct JSONB save remains complete evidence');
 const equivalent=await stage(base,source,{serialized:JSON.stringify(base,null,1)}),equivalentReceipt=await finalize(equivalent);assert.equal(equivalentReceipt.audit_id,receipt.audit_id);assert.notEqual(equivalentReceipt.manifest_hash,receipt.manifest_hash);await rawRead(equivalentReceipt,equivalent);
 await db.exec('reset role');assert.equal((await db.query('select upload_id from atlas_private.workbook_audit_projections where audit_id=$1',[receipt.audit_id])).rows[0].upload_id,staged.u.upload_id,'Equivalent transports never rebind first immutable projection');assert.deepEqual((await db.query('select atlas_private.resolve_workbook_audit($1,$2) r',[ref(equivalentReceipt),sourceHash])).rows[0].r,prepared.runtime);
 await signIn(1);await assert.rejects(call('atlas_begin_workbook_audit_upload',[cid,staged.requestId,equivalent.manifest,equivalent.manifestHash]),/reused with different evidence/);
 const waitingStage=await stage(large),waitingReceipt=await finalize(waitingStage);await db.exec('reset role');const waitingStored=(await db.query('select evidence,server_validation from atlas_workbook_audits where audit_id=$1',[waitingReceipt.audit_id])).rows[0];assert.equal(waitingStored.evidence.validationState,'needs_authority_review');assert(waitingStored.server_validation.some(i=>i.code==='workbook_authority_review_required'));
 const laterScope=structuredClone(large);laterScope.authorityScope=base.authorityScope;seal(laterScope);const laterStage=await stage(laterScope),laterReceipt=await finalize(laterStage);await db.exec('reset role');assert.deepEqual((await db.query('select server_validation from atlas_workbook_audits where audit_id=$1',[laterReceipt.audit_id])).rows[0].server_validation,[],'Previously retained unscoped evidence supports a later approved authority scope');
 const rollbackAudit=structuredClone(base);rollbackAudit.previousFingerprint='b'.repeat(64);seal(rollbackAudit);const rollbackStage=await stage(rollbackAudit);await db.exec('reset role');await db.exec("create function atlas_private.test_projection_failure() returns trigger language plpgsql as $$begin raise exception 'injected projection failure';end;$$;create trigger test_projection_failure before insert on atlas_private.workbook_audit_projections for each row execute function atlas_private.test_projection_failure()");await signIn(1);await assert.rejects(finalize(rollbackStage),/injected projection failure/);await db.exec('reset role');assert.equal((await db.query('select audit_id from atlas_private.workbook_audit_uploads where upload_id=$1',[rollbackStage.u.upload_id])).rows[0].audit_id,null);assert.equal((await db.query('select count(*)::int n from atlas_workbook_audits where fingerprint=$1',[rollbackAudit.fingerprint])).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from atlas_private.workbook_audit_chunks where upload_id=$1',[rollbackStage.u.upload_id])).rows[0].n,rollbackStage.manifest.audit.chunkCount+rollbackStage.manifest.source.chunkCount);await db.exec('drop trigger test_projection_failure on atlas_private.workbook_audit_projections');await signIn(1);await finalize(rollbackStage);
 const tampered=structuredClone(base);tampered.inventory.sheets[0].cells.at(-1).value=1;const tamperedStage=await stage(tampered);await assert.rejects(finalize(tamperedStage),/fingerprint does not match/);await db.exec('reset role');assert.equal((await db.query('select audit_id from atlas_private.workbook_audit_uploads where upload_id=$1',[tamperedStage.u.upload_id])).rows[0].audit_id,null);
 await signIn(2);await rawRead(receipt,staged);await assert.rejects(finalize(await Promise.resolve(staged)),/authorization mismatch/);await signIn(3);await assert.rejects(rawRead(receipt,staged),/outside authorized scope/);
 await db.exec('reset role;set role anon');await assert.rejects(finalize(staged),/permission denied/);
 if(process.env.ATLAS_DORO_EVIDENCE){
  const evidence=JSON.parse(fs.readFileSync(process.env.ATLAS_DORO_EVIDENCE,'utf8')),a=evidence.integrity,bytes=Buffer.from(evidence.source.originalFile.data,'base64');
  const p=await prepare(a);assert.equal(p.globalValidation.length,0);assert.equal(p.issues.length,a.findings.filter(f=>f.severity==='blocking').length);assert.equal(p.state,'blocked');
  for(let i=0;i<a.inventory.sheets.length;i++)assert.equal(workbookEvidenceHash(p.runtime.inventory.sheets[i].cells),workbookEvidenceHash(a.inventory.sheets[i].cells),'Complete actual cell inventory hash matches for each sheet');
  const s=await stage(a,bytes),t=performance.now(),r=await finalize(s);const finalizeMs=Math.round(performance.now()-t);await rawRead(r,s);
  const inspected=await inspectActualWorkbook(bytes,{fileName:'private-source.xlsx',periods:['2026-09','2026-10','2026-11','2026-12']}),scoped=await prepare(inspected.audit);assert.deepEqual(scoped.issues,[],'Actual scoped Doro authority must pass unchanged dependency validator');
  let stages=null;if(process.env.ATLAS_PROJECTION_PROFILE){await db.exec('reset role');stages={};for(const [name,sql,args] of [['global','select atlas_private.workbook_global_validation_raw($1::json) r',[JSON.stringify(inspected.audit)]],['runtime','select atlas_private.workbook_runtime_projection_raw($1::json) r',[JSON.stringify(inspected.audit)]],['authority','select atlas_private.workbook_authority_input_raw($1::json,$2::jsonb) r',[JSON.stringify(inspected.audit),scoped.runtime]]]){const t=performance.now();const result=(await db.query(sql,args)).rows[0].r;stages[name]=Math.round(performance.now()-t);console.log(JSON.stringify({stage:name,ms:stages[name]}));if(name==='authority'){const t=performance.now();await db.query('select atlas_private.workbook_integrity_issues_verified($1,$2)',[result,inspected.audit.fingerprint]);stages.authorityValidator=Math.round(performance.now()-t);}}}
  const scopedStage=await stage(inspected.audit,bytes),scopedReceipt=await finalize(scopedStage);await rawRead(scopedReceipt,scopedStage);
  actualProof={sourceHash:hash(bytes),auditFingerprint:a.fingerprint,auditBytes:s.auditBytes.length,rawCounts:p.counts,globalIssues:p.globalValidation.length,retainedBlockingIssues:p.issues.length,projectionBytes:Buffer.byteLength(JSON.stringify(p.runtime)),prepareMs:p.elapsedMs,finalizeMs,allOriginalCellFieldsPreserved:true,exactCompleteRawStreamsReadback:true,scopedFingerprint:inspected.audit.fingerprint,scopedIssueCount:scoped.issues.length,scopedPrepareMs:scoped.elapsedMs,stages};
 }
 const proof={scope:'Local isolated PostgreSQL regression; no production acceptance claimed',adversaries,allCellFieldsAndZeroNullRetained:true,projectionPrivateAndImmutable:true,legacyInlineUnchanged:true,helperOnlyLeavesActivePathsUnchanged:true,activationAclAndTimeoutsPreserved:true,overlappingClientRetriesSingleAudit:true,lateFailureRollsBackAndRetainsChunks:true,largeUnscopedSaveBlockedThenScopedApproval:true,canonicalEquivalentManifestDedupe:true,projectionOriginalBindingUnchanged:true,exactRawReadback:true,requestConflictAndFreshTamperingDenied:true,authorizedSecondReader:true,unauthorizedDenied:true,actual:actualProof};
 if(process.env.ATLAS_PROJECTION_PROOF)fs.writeFileSync(process.env.ATLAS_PROJECTION_PROOF,JSON.stringify(proof,null,2)+'\n');console.log(JSON.stringify(proof));
}catch(error){console.error(JSON.stringify({message:error.message,where:error.where,code:error.code}));process.exitCode=1;}finally{await db.close();}
