import assert from 'node:assert/strict';
import {digest,readWorkspace,accessNamespace} from '../docs/portfolio-operations-dashboard/features/workspace-bootstrap.mjs';
const source={documentKey:'atlas_dashboard_state_v1',version:4,archiveHash:'a'.repeat(64),effectiveAt:'2026-09-24T18:00:00.123456+00:00'};
const body={format:1,source,communityData:{Example:{occupied:0,unknown:null}},opsGlobalData:{},importState:{lineage:[{importedValue:0,currentState:true}]}};
const projection={...body,contentHash:await digest(body)};
const envelope={status:'available',source,projection,scopeFingerprint:'b'.repeat(64),projectionVersion:1,projectionContentHash:'c'.repeat(64),projectionHashFormat:'postgres-jsonb-sha256',fullProjection:true};
let response=envelope,calls=[];
const central={fetchJson:async(...args)=>{calls.push(args);return response;},getSession:()=>({user:{id:'actor-one'}}),getConfig:()=>({supabaseUrl:'https://example.invalid'})};
const nativeDigest=crypto.subtle.digest;let digestCalls=0;
crypto.subtle.digest=function(...args){digestCalls++;return nativeDigest.apply(this,args);};
const phases=[];globalThis.AtlasPerformance={start:name=>{phases.push(['start',name]);return ()=>phases.push(['end',name]);}};
const full=await readWorkspace(central);
assert.deepEqual(phases,[['start','workspace-projection-read'],['end','workspace-projection-read'],['start','workspace-projection-verify'],['end','workspace-projection-verify']]);
assert.equal(digestCalls,1,"Full projection integrity is checked once before its validated digest is retained");
assert.equal(calls[0][0],'/rpc/atlas_read_workspace_projection');assert.equal(calls[0][1].body,'{}');
assert.deepEqual(full.projection,projection);assert.equal(full.binding.projectionContentHash,envelope.projectionContentHash);
response={...envelope,fullProjection:false,projection:body};
assert.deepEqual((await readWorkspace(central)).projection,projection,'filtered response has its own digest, preserving zero/null');
assert.equal(digestCalls,2,"Filtered projections calculate their independent integrity digest");
crypto.subtle.digest=nativeDigest;
response={...envelope,projection:{...projection,communityData:{Example:{occupied:1}}}};
await assert.rejects(readWorkspace(central),/fingerprint mismatch/);
response={...envelope,source:{...source,version:5}};
await assert.rejects(readWorkspace(central),/source receipt/);
response={status:'unavailable',reason:'workspace_projection_unavailable'};
await assert.rejects(readWorkspace(central),/temporarily unavailable/);
assert(calls.every(([url])=>url==='/rpc/atlas_read_workspace_projection'),'no archive read fallback');
const controller=new AbortController();controller.abort();response=envelope;
await assert.rejects(readWorkspace(central,{signal:controller.signal}),{name:'AbortError'});
const profile={user_id:'actor-one',status:'active',account_status:'active',role:'regional',allowed_community_ids:['example'],access_backend:'https://example.invalid',access_verified_at:'today'};
const namespace=await accessNamespace(central,profile);
assert.equal(await accessNamespace(central,{...profile,access_verified_at:'later'}),namespace,'verification timestamp does not change cache scope');
assert.notEqual(await accessNamespace(central,{...profile,allowed_community_ids:['different']}),namespace);
await assert.rejects(accessNamespace(central,{...profile,user_id:'actor-two'}),/current access/);
await assert.rejects(accessNamespace(central,{...profile,status:'disabled'}),/current access/);
await assert.rejects(accessNamespace(central,{...profile,account_status:'password_reset_required'}),/current access/);
delete globalThis.AtlasPerformance;
console.log('PASS scoped RPC receipts, full/filtered integrity, source mismatch, no unfiltered fallback, abort, actor/scope/account cache isolation');
