const assert=require('node:assert/strict'),vm=require('node:vm'),{indexedDB}=require('fake-indexeddb');
const {readDashboardSource}=require('./dashboard-source.cjs');
const text=readDashboardSource('docs/portfolio-operations-dashboard/index.html'),start=text.indexOf('async function applyDashboardStorageBundle('),end=text.indexOf('\nasync function importDashboardStorageBundleFromClipboard',start);
let source=text.slice(start,end).replace(/const \{historyOperation\} = await import\('\.\/features\/import-history\.mjs(?:\?v=[^']+)?'\);/g,'const {historyOperation}=historyFixture;').replace(/const \{sourceIdentity,stableJson\}=await import\("\.\/features\/workspace-bootstrap\.mjs(?:\?v=[^"]+)?"\);/g,'const {sourceIdentity,stableJson}=workspaceFixture;');
globalThis.indexedDB=indexedDB;
(async()=>{
 const {executeHistory}=await import('../docs/portfolio-operations-dashboard/features/import-history-store.mjs'),workspace=await import('../docs/portfolio-operations-dashboard/features/workspace-bootstrap.mjs');
 const parent={document_key:'atlas_dashboard_state_v1',version:3,updated_at:'2026-09-24T12:00:00.123456+00:00',payload:{bundle:{bundleType:'atlas_migration_archive_v1',sha256:'a'.repeat(64)}}},binding=workspace.sourceIdentity(parent);
 async function boot(label){const dbName='restore-'+label,db=await new Promise(resolve=>{const r=indexedDB.open(dbName,1);r.onupgradeneeded=()=>r.result.createObjectStore('records',{keyPath:'key'});r.onsuccess=()=>resolve(r.result);});
 const transaction=(mode,fn)=>new Promise((resolve,reject)=>{const tx=db.transaction('records',mode);let request;try{request=fn(tx.objectStore('records'));}catch(error){tx.abort();return reject(error);}tx.oncomplete=()=>resolve(request?.result);tx.onerror=tx.onabort=()=>reject(tx.error);});
 const get=async key=>(await transaction('readonly',store=>store.get(key)))?.value;
 await transaction('readwrite',store=>{store.put({key:'community_data',value:{A:{value:91}}});store.put({key:'atlas_workspace_source_v2',value:{identity:binding,dirty:false}});});
 const unpacked={bundle:{keys:{},indexedDb:{communityData:{A:{value:0}}}},records:[{key:'imports',value:{canonicalRecords:[],lineage:[],sourceArchive:[],batches:[{id:'one',beforeSnapshot:{capturedAt:'original',savedData:{A:{value:91}}}}]}}]};
 const c={Date,DOMException,JSON,atlasWorkspaceAccess:{epoch:1,controller:new AbortController()},ATLAS_STATE_DB_NAME:dbName,ATLAS_STATE_STORE_NAME:'records',ATLAS_STATE_COMMUNITY_KEY:'community_data',DATA_IMPORT_2_STATE_KEY:'imports',DATA_IMPORT_FILE_ARCHIVE_PREFIX:'file:',OPS_GLOBAL_STORAGE_KEY:'global',ATLAS_STATE_WEEKLY_SNAPSHOT_KEY:'weekly',ATLAS_STATE_DAILY_BACKUP_INDEX_KEY:'backups',DASHBOARD_DAILY_BACKUP_RETENTION:30,savedData:{},atlasStateWritePromise:Promise.resolve(),JSZip:{},scope:'A',getAtlasRenderContextKey:()=>c.scope,atlasStateGetValue:get,atlasStateSetValue:(key,value)=>transaction('readwrite',store=>store.put({key,value})),withAtlasStateStore:transaction,mergeDashboardCommunityDataMaps:(_,incoming)=>incoming,removeLegacyCommunityStorageKeys(){},removeLegacyDailyBackupStorageKeys(){},removeLegacyWeeklySnapshotStorageKey(){},markAtlasPersistenceError:e=>{throw e;},historyFixture:{historyOperation:executeHistory},workspaceFixture:workspace,window:{AtlasFeatures:{load:async()=>{}},AtlasMigrationArchive:{hydrate:async archive=>archive,unpack:async()=>{await c.duringUnpack?.();return unpacked;}},ATLAS_CENTRAL:{readDocument:async()=>structuredClone(parent)}}};
 vm.createContext(c);vm.runInContext(source,c);return {c,db,get,unpacked};}
 const local=await boot('local');await local.c.applyDashboardStorageBundle(parent.payload.bundle);assert.equal((await local.get('atlas_workspace_source_v2')).dirty,true);assert.equal((await local.get('community_data')).A.value,0);assert.equal((await local.get('imports')).__atlasImportHistory,2);local.db.close();
 const canonical=await boot('canonical');await canonical.c.applyDashboardStorageBundle(parent.payload.bundle,{canonicalSource:binding});assert.equal((await canonical.get('atlas_workspace_source_v2')).dirty,false);assert.deepEqual((await canonical.get('atlas_import_archive_receipt_v2')).source,binding);assert.equal((await canonical.get('community_data')).A.value,0);canonical.db.close();
 const changed=await boot('changed');changed.c.window.ATLAS_CENTRAL.readDocument=async()=>({...parent,version:4});await assert.rejects(changed.c.applyDashboardStorageBundle(parent.payload.bundle,{canonicalSource:binding}),/central source changed/);assert.equal((await changed.get('community_data')).A.value,91);assert.equal(await changed.get('imports'),undefined);changed.db.close();
 const switched=await boot('actor');switched.c.duringUnpack=()=>{switched.c.scope='B';};await assert.rejects(switched.c.applyDashboardStorageBundle(parent.payload.bundle),{name:'AbortError'});assert.equal((await switched.get('community_data')).A.value,91);switched.db.close();
 console.log('PASS actual restore flow: local backup marks dirty, canonical exact source receipt remains bound, real zero preserved, source/actor changes abort before storage mutation.');
})().catch(error=>{console.error(error);process.exitCode=1;});
