import assert from 'node:assert/strict';
import {ensureWorkspaceProjection} from '../docs/portfolio-operations-dashboard/features/workspace-publication.mjs';
import {projectionKey,sourceIdentity,buildProjection,accessNamespace} from '../docs/portfolio-operations-dashboard/features/workspace-bootstrap.mjs';
const parent={document_key:'atlas_dashboard_state_v1',version:7,updated_at:'2026-09-24T12:00:00.123456+00:00',payload:{bundle:{bundleType:'atlas_migration_archive_v1',sha256:'a'.repeat(64),bytes:3,recordCount:1,dataDocuments:[{documentKey:'part'}]}}};
const archive={...parent.payload.bundle,data:'eHl6'};
let builds=0,hydrates=0,delayBuild=null;
globalThis.window={AtlasFeatures:{load:async()=>{}},AtlasMigrationArchive:{hydrate:async()=>{hydrates++;return archive;}}};
globalThis.Worker=class{
 constructor(){this.closed=false;}
 postMessage({archive:input,source}){builds++;assert.equal(input.data,'eHl6');queueMicrotask(async()=>{if(delayBuild)await delayBuild();if(!this.closed)this.onmessage({data:{ok:true,value:{format:1,source,communityData:{A:{zero:0,nullable:null}},opsGlobalData:{},importState:{lineage:[],canonicalRecords:[]}}}});});}
 terminate(){this.closed=true;}
};
function client(){const documents=new Map([[parent.document_key,structuredClone(parent)]]),writes=[];return {documents,writes,failWrite:false,afterWrite:null,readDocument:async key=>structuredClone(documents.get(key)||null),async rpc(name,args){assert.equal(name,'atlas_publish_workspace_projection');assert.deepEqual(Object.keys(args),['p_projection']);if(this.failWrite)throw Error('Synthetic projection write failure');const payload=args.p_projection,documentKey=projectionKey(payload.source);writes.push({name,args:structuredClone(args),documentKey,payload});documents.set(documentKey,{document_key:documentKey,module_key:'dashboard',source_module:'workspace_projection',payload:structuredClone(payload),version:1});this.afterWrite?.();return {version:1};}};}
const initial=client();const completed=await ensureWorkspaceProjection(initial,{document:parent,archive});assert.equal(completed.status,'complete');assert.equal(completed.projectionVerified,true);assert.equal(hydrates,0,'Just-built archive bytes are reused');assert.equal(initial.writes.length,1);assert.equal(initial.writes[0].name,'atlas_publish_workspace_projection');assert.equal(initial.writes[0].args.p_projection.source.version,parent.version);assert.equal(initial.writes[0].payload.communityData.A.zero,0);assert.equal(initial.writes[0].payload.communityData.A.nullable,null);
const before=builds;await ensureWorkspaceProjection(initial,{document:parent});assert.equal(builds,before,'Hash-matched projection retry performs no archive decode');assert.equal(hydrates,0);assert.equal(initial.writes.length,1);
const failed=client();failed.failWrite=true;const pending=await ensureWorkspaceProjection(failed,{document:parent,archive});assert.equal(pending.status,'archive_saved_projection_pending');assert.equal(pending.parentSaved,true);assert.equal(pending.source.version,7);assert.equal(pending.projectionVerified,false);failed.failWrite=false;assert.equal((await ensureWorkspaceProjection(failed,{document:parent,archive})).status,'complete');assert(failed.writes.every(row=>row.documentKey!==parent.document_key),'Retry never writes the parent archive');
const during=client();delayBuild=async()=>{during.documents.set(parent.document_key,{...parent,version:8});};const stale=await ensureWorkspaceProjection(during,{document:parent,archive});assert.equal(stale.status,'archive_saved_projection_pending');assert.match(stale.message,/source changed/);assert.equal(during.writes.length,0);delayBuild=null;
const after=client();after.afterWrite=()=>after.documents.set(parent.document_key,{...parent,version:8});assert.equal((await ensureWorkspaceProjection(after,{document:parent,archive})).status,'archive_saved_projection_pending','A source change after projection save prevents fresh-success claim');
initial.documents.get(projectionKey(sourceIdentity(parent))).payload.communityData.A.zero=4;assert.equal((await ensureWorkspaceProjection(initial,{document:parent})).status,'archive_saved_projection_pending','Tampered retained projection is never accepted or replaced implicitly');
await assert.rejects(buildProjection(initial,parent,{archive:{...archive,sha256:'b'.repeat(64)}}),/does not match/);
const stopped=new AbortController();stopped.abort();assert.equal((await ensureWorkspaceProjection(client(),{document:parent,archive,signal:stopped.signal})).status,'archive_saved_projection_pending');
const actor='synthetic-actor',profile={user_id:actor,status:'active',account_status:null,access_backend:'test-backend',access_verified_at:'2026-09-24',role:'admin'},identityClient={getSession:()=>({user:{id:actor}}),getConfig:()=>({supabaseUrl:'test-backend'})};
assert.notEqual(await accessNamespace(identityClient,profile),await accessNamespace(identityClient,{...profile,account_status:'active'}));await assert.rejects(accessNamespace(identityClient,{...profile,account_status:'disabled'}),/current access/);
console.log('PASS workspace publication: exact inline archive reuse, projection-only retry, parent CAS freshness before/after, honest committed-parent pending receipt, null/zero preservation, tamper denial and cancellation.');
