const assert=require('node:assert/strict'),vm=require('node:vm');
const {readDashboardSource}=require('./dashboard-source.cjs');
const source=readDashboardSource('docs/portfolio-operations-dashboard/index.html');
const start=source.indexOf('async function saveAtlasCentralAppState('),end=source.indexOf('\nasync function inspectAtlasOccupancyReadback',start);
const fn=source.slice(start,end).replace(/const \{ensureWorkspaceProjection\} = await import\("\.\/features\/workspace-publication\.mjs(?:\?v=[^"]+)?"\);/g,'const {ensureWorkspaceProjection} = projectionFixture;');
function fixture(){
 const records=new Map(),calls={build:0,parts:0,parent:0,projection:0},messages=[];
 let parent={document_key:'atlas_dashboard_state_v1',version:1,payload_hash:'old',updated_at:'2026-09-24T12:00:00Z',payload:{bundle:{sha256:'old'}}};
 const c={console,Date,DOMException,captureAtlasSaveContext:()=>()=>true,ATLAS_STATE_DB_NAME:'db-A',actor:'A',atlasWorkspaceActorKey:()=>c.actor,atlasWorkspaceAccess:{controller:new AbortController()},atlasCentralRuntimeMeta:{lastDocumentVersion:1},atlasCentralCanUseDatabase:()=>({ok:true}),atlasCentralAutosaveGateSatisfied:()=>true,getAtlasCentralDocumentKey:()=> 'atlas_dashboard_state_v1',atlasStateGetValue:async key=>records.get(key)||null,atlasStateSetValue:async(key,value)=>{records.set(key,value);await c.afterStorage?.(key,value);},buildAtlasCentralAppStatePayload:async()=>{calls.build++;await c.afterBuild?.();return {bundle:{bundleType:'atlas_migration_archive_v1',sha256:'new',data:'local-inline'},reconciliation:{},exceptions:[]};},projectionFixture:{ensureWorkspaceProjection:async(_,input)=>{calls.projection++;await c.duringProjection?.();return {status:c.projectionFails?'archive_saved_projection_pending':'complete',message:'Synthetic pending',source:{version:input.document.version}};}},setAtlasCentralRuntimeMessage:(ok,error)=>messages.push({ok,error}),alert:()=>{},renderTab:()=>{},window:{}};
 c.window.AtlasMigrationArchive={publish:async archive=>{calls.parts++;return {...archive,data:undefined,dataDocuments:[]};}};
 c.window.ATLAS_CENTRAL={computeSha256:async()=> 'new-payload-hash',readDocument:async()=>{if(c.failReadback&&calls.parent){c.failReadback=false;throw Error('Synthetic readback unavailable');}return structuredClone(parent);},saveDocument:async value=>{calls.parent++;parent={document_key:value.documentKey,version:2,payload_hash:'new-payload-hash',updated_at:'2026-09-24T12:01:00Z',payload:structuredClone(value.payload)};return {version:2,payload_hash:parent.payload_hash};}};
 vm.createContext(c);vm.runInContext(fn,c);return {c,calls,records,messages,setParent:value=>{parent=value;}};
}
(async()=>{
 const a=fixture();a.c.failReadback=true;assert.equal(await a.c.saveAtlasCentralAppState({silent:true}),false);assert.equal(a.calls.parent,1);assert.equal(a.records.get('atlas_workspace_projection_pending_v1').version,2);assert.match(a.messages.at(-1).error,/was saved/);assert.equal(await a.c.saveAtlasCentralAppState({silent:true}),true);assert.deepEqual(a.calls,{build:1,parts:1,parent:1,projection:1});assert.equal(a.records.get('atlas_workspace_projection_pending_v1'),null);
 const b=fixture();b.c.projectionFails=true;assert.equal(await b.c.saveAtlasCentralAppState({silent:true}),false);b.c.projectionFails=false;assert.equal(await b.c.saveAtlasCentralAppState({silent:true}),true);assert.equal(b.calls.parent,1);assert.equal(b.calls.parts,1);assert.equal(b.calls.projection,2);
 const changed=fixture();changed.c.afterBuild=()=>{changed.c.actor='B';changed.c.ATLAS_STATE_DB_NAME='db-B';};assert.equal(await changed.c.saveAtlasCentralAppState({silent:true}),false);assert.equal(changed.calls.parts,0);assert.equal(changed.calls.parent,0);assert.equal(changed.messages.length,0);
 const late=fixture();late.c.duringProjection=()=>{late.c.actor='B';late.c.ATLAS_STATE_DB_NAME='db-B';};assert.equal(await late.c.saveAtlasCentralAppState({silent:true}),false);assert.equal(late.c.atlasCentralRuntimeMeta.lastDocumentVersion,1);assert.equal(late.messages.length,0);
 const match=fixture();match.setParent({document_key:'atlas_dashboard_state_v1',version:1,payload_hash:'new-payload-hash',payload:{bundle:{sha256:'new'}}});assert.equal(await match.c.saveAtlasCentralAppState({silent:true}),true);assert.equal(match.calls.parent,0);assert.equal(match.calls.projection,1);
 const archiveApi=require('../docs/portfolio-operations-dashboard/migration-archive.js');
 let permitted=true,partWrites=0;const partClient={readDocument:async()=>null,saveDocument:async()=>{partWrites++;permitted=false;}};
 await assert.rejects(archiveApi.publish({bundleType:archiveApi.TYPE,data:'abcdefghijklmnop'},partClient,4,{isCurrent:()=>permitted}),{name:'AbortError'});assert.equal(partWrites,1,'Accepted first part may settle; later parts never cross actor boundaries');
 permitted=true;partWrites=0;partClient.readDocument=async()=>{permitted=false;return null;};await assert.rejects(archiveApi.publish({bundleType:archiveApi.TYPE,data:'abcdefghijklmnop'},partClient,4,{isCurrent:()=>permitted}),{name:'AbortError'});assert.equal(partWrites,0,'Access change after read cannot authorize a part write');
 console.log('PASS actual Central Save flow: parent readback failure recovery, durable projection-only retry, hash-match completion, no actor-switched part writes or stale metadata/UI updates.');
})().catch(error=>{console.error(error);process.exitCode=1;});
