revoke execute on function atlas_current_role() from public;
revoke execute on function atlas_current_role() from anon;
revoke execute on function atlas_can_write(text[]) from public;
revoke execute on function atlas_can_write(text[]) from anon;
revoke execute on function atlas_has_role(text[]) from public;
revoke execute on function atlas_has_role(text[]) from anon;
revoke execute on function atlas_current_allowed_community_ids() from public;
revoke execute on function atlas_current_allowed_community_ids() from anon;
revoke execute on function atlas_can_access_community(uuid) from public;
revoke execute on function atlas_can_access_community(uuid) from anon;
revoke execute on function atlas_hash_payload(jsonb) from public;
revoke execute on function atlas_hash_payload(jsonb) from anon;
revoke execute on function atlas_claim_first_admin(text) from public;
revoke execute on function atlas_claim_first_admin(text) from anon;
revoke execute on function atlas_update_app_document(text, text, jsonb, integer, text, text, jsonb) from public;
revoke execute on function atlas_update_app_document(text, text, jsonb, integer, text, text, jsonb) from anon;
revoke execute on function atlas_upload_legacy_snapshot(text, text, text, text, jsonb, jsonb) from public;
revoke execute on function atlas_upload_legacy_snapshot(text, text, text, text, jsonb, jsonb) from anon;
revoke execute on function atlas_lookup_or_create_community(text, text, boolean) from public;
revoke execute on function atlas_lookup_or_create_community(text, text, boolean) from anon;
revoke execute on function atlas_upsert_people_directory(jsonb, uuid, boolean) from public;
revoke execute on function atlas_upsert_people_directory(jsonb, uuid, boolean) from anon;
revoke execute on function atlas_upsert_marketing_metrics(jsonb, boolean) from public;
revoke execute on function atlas_upsert_marketing_metrics(jsonb, boolean) from anon;
revoke execute on function atlas_upsert_maintenance_inspections(jsonb, boolean) from public;
revoke execute on function atlas_upsert_maintenance_inspections(jsonb, boolean) from anon;
revoke execute on function atlas_record_bonus_calculation(text, integer, text, date, date, jsonb, text) from public;
revoke execute on function atlas_record_bonus_calculation(text, integer, text, date, date, jsonb, text) from anon;

grant execute on function atlas_current_role() to authenticated;
grant execute on function atlas_can_write(text[]) to authenticated;
grant execute on function atlas_has_role(text[]) to authenticated;
grant execute on function atlas_current_allowed_community_ids() to authenticated;
grant execute on function atlas_can_access_community(uuid) to authenticated;
grant execute on function atlas_claim_first_admin(text) to authenticated;
grant execute on function atlas_update_app_document(text, text, jsonb, integer, text, text, jsonb) to authenticated;
grant execute on function atlas_upload_legacy_snapshot(text, text, text, text, jsonb, jsonb) to authenticated;
grant execute on function atlas_upsert_people_directory(jsonb, uuid, boolean) to authenticated;
grant execute on function atlas_upsert_marketing_metrics(jsonb, boolean) to authenticated;
grant execute on function atlas_upsert_maintenance_inspections(jsonb, boolean) to authenticated;
grant execute on function atlas_record_bonus_calculation(text, integer, text, date, date, jsonb, text) to authenticated;